Repository bioconda/bioconda-recipes, pull requests merged in 2018-07, with the labels that each got.

#9711 Remove recipes from the blacklist after the conda build 3 migration
  build-fail-blacklist
  recipes/hmmer/2.3.2/build.sh
  recipes/hmmer/2.3.2/meta.yaml
  recipes/hmmer/build.sh
  recipes/hmmer/meta.yaml
  recipes/prophyle/0.3.0/build.sh
  recipes/prophyle/0.3.0/meta.yaml
Labels: hackathon

#7941 Build breakdancer again.
  build-fail-blacklist
Labels: WIP

#10011 Sourcetracker
  recipes/sourcetracker/meta.yaml
Labels: help wanted

#10145 updating cromwell to 0.34
  recipes/cromwell/meta.yaml
Labels: enhancement
