Repository bioconda/bioconda-recipes, pull requests merged in 2018-12, with the labels that each got.

#12436 Update scnic to 0.6.0
  recipes/scnic/meta.yaml
Labels: autobump

#12369 Update ncrf to 1.00.06
  recipes/ncrf/meta.yaml
Labels: autobump

#12375 Update r-goeveg to 0.4.2
  recipes/r-goeveg/meta.yaml
Labels: autobump

#12516 Update duphold to 0.1.1
  recipes/duphold/meta.yaml
Labels: autobump

#12515 Update starfish to 0.0.31
  recipes/starfish/meta.yaml
Labels: autobump

#12512 Update perl-term-app-roles to 0.02
  recipes/perl-term-app-roles/meta.yaml
Labels: autobump

#12511 Update perl-dbd-sqlite to 1.60
  recipes/perl-dbd-sqlite/meta.yaml
Labels: autobump

#12509 Update perl-json to 4.00
  recipes/perl-json/meta.yaml
Labels: autobump

#12508 Update kipoi to 0.6.5
  recipes/kipoi/meta.yaml
Labels: autobump

#12507 Update illumina-interop to 1.1.8
  recipes/illumina-interop/meta.yaml
Labels: autobump

#12523 Update beagle-lib to 3.1.2
  recipes/beagle-lib/meta.yaml
Labels: autobump

#12522 Update pysradb to 0.3.0
  recipes/pysradb/meta.yaml
Labels: autobump

#12525 Update bioconda-utils to 0.15.2
  recipes/bioconda-utils/meta.yaml
Labels: autobump

#12524 Update perl-json-pp to 4.0
  recipes/perl-json-pp/meta.yaml
Labels: autobump

#12529 Update perl-term-table to 0.013
  recipes/perl-term-table/meta.yaml
Labels: autobump

#12528 Update abyss to 2.1.5
  recipes/abyss/meta.yaml
Labels: autobump

#12527 Update perl-test2-suite to 0.000117
  recipes/perl-test2-suite/meta.yaml
Labels: autobump

#12505 Update wtforms-alchemy to 0.16.8
  recipes/wtforms-alchemy/meta.yaml
Labels: autobump

#12518 Update perl-carp-clan to 6.07
  recipes/perl-carp-clan/meta.yaml
Labels: autobump

#12519 Update perl-date-manip to 6.75
  recipes/perl-date-manip/meta.yaml
Labels: autobump

#12540 Update vsearch to 2.10.1
  recipes/vsearch/meta.yaml
Labels: autobump

#12539 Update moff to 2.0.2
  recipes/moff/meta.yaml
Labels: autobump

#12544 Update biolite to 1.2.0
  recipes/biolite/meta.yaml
Labels: autobump

#12543 Update kneaddata to 0.7.2
  recipes/kneaddata/meta.yaml
Labels: autobump

#12546 Update bioconda-utils to 0.15.3
  recipes/bioconda-utils/meta.yaml
Labels: autobump

#12517 Update nanosim to 2.2.0
  recipes/nanosim/meta.yaml
Labels: autobump

#12579 Update vsearch to 2.10.2
  recipes/vsearch/meta.yaml
Labels: autobump

#12578 Update mentalist to 0.2.4
  recipes/mentalist/meta.yaml
Labels: autobump

#12575 Update krakenuniq to 0.5.5
  recipes/krakenuniq/meta.yaml
Labels: autobump

#12572 Update mlst to 2.16
  recipes/mlst/meta.yaml
Labels: autobump

#12570 Update transit to 2.3.3
  recipes/transit/meta.yaml
Labels: autobump

#12568 Update anndata to 0.6.14
  recipes/anndata/meta.yaml
Labels: autobump

#12566 Update svim to 0.4.2
  recipes/svim/meta.yaml
Labels: autobump

#12569 Update perl-test-cleannamespaces to 0.24
  recipes/perl-test-cleannamespaces/meta.yaml
Labels: autobump

#12574 Update jcvi to 0.8.12
  recipes/jcvi/meta.yaml
Labels: autobump

#12564 add cromwell-tools (CLI and API for Cromwell workflow manager).
  recipes/cromwell-tools/meta.yaml
Labels: enhancement, please review & merge

#12609 Update slicedimage to 1.0.2
  recipes/slicedimage/meta.yaml
Labels: autobump

#12608 Update perl-module-scandeps to 1.26
  recipes/perl-module-scandeps/meta.yaml
Labels: autobump

#12605 Update scanpy to 1.3.6
  recipes/scanpy/meta.yaml
Labels: autobump

#12602 Update abeona to 0.40.2
  recipes/abeona/meta.yaml
Labels: autobump

#12607 Update confindr to 0.4.8
  recipes/confindr/meta.yaml
Labels: autobump

#12606 Update anndata to 0.6.15
  recipes/anndata/meta.yaml
Labels: autobump

#12634 Update galaxy-parsec to 1.0.6
  recipes/galaxy-parsec/meta.yaml
Labels: autobump

#12638 Update deepvariant to 0.7.2
  recipes/deepvariant/meta.yaml
Labels: autobump

#12637 Update abeona to 0.41.1
  recipes/abeona/meta.yaml
Labels: autobump

#12636 Update shmlast to 1.3
  recipes/shmlast/meta.yaml
Labels: autobump

#12633 Update krakenuniq to 0.5.6
  recipes/krakenuniq/meta.yaml
Labels: autobump

#12632 Update selene-sdk to 0.2.0
  recipes/selene-sdk/meta.yaml
Labels: autobump

#12667 Update sevenbridges-python to 0.17.3
  recipes/sevenbridges-python/meta.yaml
Labels: autobump

#12666 Update slicedimage to 1.0.3
  recipes/slicedimage/meta.yaml
Labels: autobump

#12665 Update cat to 4.3.3
  recipes/cat/meta.yaml
Labels: autobump

#12664 Update crossmap to 0.3.2
  recipes/crossmap/meta.yaml
Labels: autobump

#12254 Update meraculous to 2.2.6
  recipes/meraculous/meta.yaml
Labels: autobump

#12604 Update BioExcel_SeqQC to 0.6
  recipes/BioExcel_SeqQC/meta.yaml
Labels: autobump

#12676 Update anndata to 0.6.16
  recipes/anndata/meta.yaml
Labels: autobump

#12675 Update pysradb to 0.4.2
  recipes/pysradb/meta.yaml
Labels: autobump

#12225 Update perl-html-formatter to 2.16
  recipes/perl-html-formatter/meta.yaml
Labels: autobump

#12153 Update perl-readonly to 2.05
  recipes/perl-readonly/meta.yaml
Labels: autobump

#12187 Update perl-html-tidy to 1.60
  recipes/perl-html-tidy/meta.yaml
Labels: autobump

#12180 Update perl-libwww-perl to 6.36
  recipes/perl-libwww-perl/meta.yaml
Labels: autobump

#12662 Use quotes when extending PATH.
  .circleci/setup.sh
  recipes/r-biodb/meta.yaml
Labels: bug

#12158 Update perl-math-derivative to 1.01
  recipes/perl-math-derivative/meta.yaml
Labels: autobump

#12170 Update perl-parallel-forkmanager to 2.02
  recipes/perl-parallel-forkmanager/meta.yaml
Labels: autobump

#12687 Update bioblend to 0.12.0
  recipes/bioblend/meta.yaml
Labels: autobump

#12686 Update abeona to 0.42.0
  recipes/abeona/meta.yaml
Labels: autobump

#12697 Update prokka to 1.13.4
  recipes/prokka/meta.yaml
Labels: autobump

#12698 Update flashlfq to 0.1.111
  recipes/flashlfq/meta.yaml
Labels: autobump

#12699 Update gatk4 to 4.0.12.0
  recipes/gatk4/meta.yaml
Labels: autobump

#12701 Update picard to 2.18.21
  recipes/picard/meta.yaml
Labels: autobump

#12702 Update sevenbridges-python to 0.17.4
  recipes/sevenbridges-python/meta.yaml
Labels: autobump

#12688 Update python-intervaltree to 3.0.1
  recipes/python-intervaltree/meta.yaml
Labels: autobump

#12713 Update perl-io-socket-ssl to 2.060
  recipes/perl-io-socket-ssl/meta.yaml
Labels: autobump

#12712 Update perl-parallel-loops to 0.10
  recipes/perl-parallel-loops/meta.yaml
Labels: autobump

#12700 Update perl-math-bigint to 1.999816
  recipes/perl-math-bigint/meta.yaml
Labels: autobump

#12710 Update perl-text-parsewords to 3.30
  recipes/perl-text-parsewords/meta.yaml
Labels: autobump

#12709 Update python-intervaltree to 3.0.2
  recipes/python-intervaltree/meta.yaml
Labels: autobump

#12707 Update perl-archive-zip to 1.64
  recipes/perl-archive-zip/meta.yaml
Labels: autobump

#12706 Update perl-module-corelist to 5.20181130
  recipes/perl-module-corelist/meta.yaml
Labels: autobump

#12704 Update perl-test-simple to 1.302141
  recipes/perl-test-simple/meta.yaml
Labels: autobump

#12703 Update perl-exporter-tiny to 1.002001
  recipes/perl-exporter-tiny/meta.yaml
Labels: autobump

#12714 Update perl-cpan-meta to 2.150010
  recipes/perl-cpan-meta/meta.yaml
Labels: autobump

#12711 Update r-wgcna to 1.66
  recipes/r-wgcna/meta.yaml
Labels: autobump

#12696 Update mygene to 3.1.0
  recipes/mygene/build.sh
  recipes/mygene/meta.yaml
Labels: autobump

#12708 Update mashtree to 0.35.4
  recipes/mashtree/Build.PL
  recipes/mashtree/build.sh
  recipes/mashtree/meta.yaml
Labels: autobump

#12705 Update fraggenescan to 1.31
  recipes/fraggenescan/hmm_lib.c.patch
  recipes/fraggenescan/meta.yaml
  recipes/fraggenescan/util_lib.c.patch
Labels: autobump

#12725 add cromshell, a command-line interface to the cromwell workflow runner
  recipes/cromshell/build.sh
  recipes/cromshell/meta.yaml
Labels: enhancement, please review & merge

#12746 Update iqtree to 1.6.9
  recipes/iqtree/meta.yaml
Labels: autobump

#12743 Update perl-module-corelist to 5.20181218
  recipes/perl-module-corelist/meta.yaml
Labels: autobump

#12742 Update perl-unicode-normalize to 1.26
  recipes/perl-unicode-normalize/meta.yaml
Labels: autobump

#12741 Update netreg to 1.6.0
  recipes/netreg/meta.yaml
Labels: autobump

#12744 Update bioconductor-rhdf5 to 2.26.1
  recipes/bioconductor-rhdf5/meta.yaml
Labels: autobump

#12206 Update phyloflash to 3.3b1
  recipes/phyloflash/meta.yaml
Labels: autobump

#12752 Update vsearch to 2.10.3
  recipes/vsearch/meta.yaml
Labels: autobump

#12770 Update scvi to 0.2.4
  recipes/scvi/meta.yaml
Labels: autobump

#12815 Update meta-sparse to 0.1.12
  recipes/meta-sparse/meta.yaml
Labels: autobump

#12814 Update pysradb to 0.6.0
  recipes/pysradb/meta.yaml
Labels: autobump

#12811 Update bcalm to 2.2.1
  recipes/bcalm/meta.yaml
Labels: autobump

#12810 Update sevenbridges-python to 0.17.5
  recipes/sevenbridges-python/meta.yaml
Labels: autobump

#12806 Update pymisc-utils to 0.2.11
  recipes/pymisc-utils/meta.yaml
Labels: autobump

#12805 Update super-focus to 0.33
  recipes/super-focus/meta.yaml
Labels: autobump

#12803 Update pairtools to 0.2.1
  recipes/pairtools/meta.yaml
Labels: autobump

#12520 Update diamond to 0.9.24
  recipes/diamond/meta.yaml
Labels: autobump

#12816 Update perl-test-class-moose to 0.96
  recipes/perl-test-class-moose/meta.yaml
Labels: autobump

#12813 Update perl-test-sys-info to 0.23
  recipes/perl-test-sys-info/meta.yaml
Labels: autobump

#12804 Update perl-algorithm-dependency to 1.111
  recipes/perl-algorithm-dependency/meta.yaml
Labels: autobump

#12808 Update perl-sys-info-driver-osx to 0.7959
  recipes/perl-sys-info-driver-osx/meta.yaml
Labels: autobump

#12812 Update perl-sys-info-base to 0.7807
  recipes/perl-sys-info-base/meta.yaml
Labels: autobump

#12807 Update perl-sys-info to 0.7811
  recipes/perl-sys-info/meta.yaml
Labels: autobump

#12822 Update perl-sys-info-driver-linux to 0.7904
  recipes/perl-sys-info-driver-linux/meta.yaml
Labels: autobump

#12208 Update ema to 0.6.2
  recipes/ema/meta.yaml
Labels: autobump, autobump-broken

#12834 Update xmatchview to 1.1.1
  recipes/xmatchview/meta.yaml
Labels: autobump

#12833 Update treetime to 0.5.2
  recipes/treetime/meta.yaml
Labels: autobump

#12831 Update genologics to 0.4.1
  recipes/genologics/meta.yaml
Labels: autobump

#12827 Update snp-pileup to 0.5.14
  recipes/snp-pileup/meta.yaml
Labels: autobump

#12856 Update vcftoolbox to 1.5.1
  recipes/vcftoolbox/meta.yaml
Labels: autobump

#12200 Update pypore to 0.0.6.dev20180702231556
  recipes/pypore/meta.yaml
Labels: autobump

#12160 Update tandem-genotypes to 1.4.0
  recipes/tandem-genotypes/meta.yaml
Labels: autobump

#12855 Update nanoplot to 1.20.0
  recipes/nanoplot/meta.yaml
Labels: autobump

#12854 Update fitter to 1.0.9
  recipes/fitter/meta.yaml
Labels: autobump

#12857 Update perl-dbd-sqlite to 1.62
  recipes/perl-dbd-sqlite/meta.yaml
Labels: autobump

#12852 Update perl-bio-db-hts to 2.11
  recipes/perl-bio-db-hts/meta.yaml
Labels: autobump

#12853 Update pronto to 0.12.0
  recipes/pronto/meta.yaml
Labels: autobump

#12870 Update perl-sys-info-driver-linux to 0.7905
  recipes/perl-sys-info-driver-linux/meta.yaml
Labels: autobump

#12877 Update ococo to 0.1.2.7
  recipes/ococo/meta.yaml
Labels: autobump

#12878 Update perl-compress-raw-bzip2 to 2.083
  recipes/perl-compress-raw-bzip2/meta.yaml
Labels: autobump

#12875 Update perl-compress-raw-zlib to 2.083
  recipes/perl-compress-raw-zlib/meta.yaml
Labels: autobump
