Repository bioconda/bioconda-recipes, pull requests merged in 2018-06, with the labels that each got.

#9149 Add r-ngsplot package
  recipes/r-ngsplot/build.sh
  recipes/r-ngsplot/meta.yaml
Labels: help wanted

#9022 update KMC kmer counter to 3.1.0
  recipes/kmc/3.0.1/0001-kmc-use-make-user-flags.patch
  recipes/kmc/3.0.1/0002-kmc-no-stdlib-static-link.patch
  recipes/kmc/3.0.1/0003-kmc-c++11-compat.patch
  recipes/kmc/3.0.1/0004-kmc-no-libz-libbz2-static-link.patch
  recipes/kmc/3.0.1/build.sh
  recipes/kmc/3.0.1/meta.yaml
  recipes/kmc/build.sh
  recipes/kmc/meta.yaml
Labels: enhancement

#9302 Remove voluptuous
  recipes/voluptuous/build.sh
  recipes/voluptuous/meta.yaml
Labels: in other channel

#9294 Remove requests-toolbelt
  recipes/requests-toolbelt/build.sh
  recipes/requests-toolbelt/meta.yaml
Labels: in other channel

#9293 Remove requests-cache
  recipes/requests-cache/build.sh
  recipes/requests-cache/meta.yaml
Labels: in other channel

#9306 Remove flask-bootstrap
  recipes/flask-bootstrap/build.sh
  recipes/flask-bootstrap/meta.yaml
Labels: in other channel

#9275 Remove svgutils
  recipes/svgutils/build.sh
  recipes/svgutils/meta.yaml
Labels: in other channel

#9301 Remove visitor
  recipes/visitor/build.sh
  recipes/visitor/meta.yaml
Labels: in other channel

#9453 try to fix xxmotif
  recipes/xxmotif/meta.yaml
Labels: WIP

#9579 New recipe for mauveAligner
  recipes/mauvealigner/build.sh
  recipes/mauvealigner/meta.yaml
Labels: WIP

#9670 Fix rust-overlaps using the same fix from rust-bio-tools
  build-fail-blacklist
  recipes/rust-overlaps/build.sh
  recipes/rust-overlaps/meta.yaml
Labels: hackathon

#9672 fix slang download source
  build-fail-blacklist
  recipes/slang/meta.yaml
Labels: hackathon
