Repository bioconda/bioconda-recipes, pull requests merged in 2019-06, with the labels that each got.

#15670 csvtk-0.18.1
  recipes/csvtk/meta.yaml
Labels: please review & merge

#15678 Bump tspex to 0.5.0
  recipes/tspex/meta.yaml
Labels: please review & merge

#15677 Update PAL2NAL to v14.1
  recipes/pal2nal/meta.yaml
Labels: please review & merge

#15689 Update ephemeris to 0.10.0
  recipes/ephemeris/meta.yaml
Labels: autobump, new version

#15697 Update perl-module-corelist to 5.20190524
  recipes/perl-module-corelist/meta.yaml
Labels: autobump, new version

#15694 Update chado-tools to 0.2.11
  recipes/chado-tools/meta.yaml
Labels: autobump, new version

#15692 Update sambamba to 0.7.0
  recipes/sambamba/meta.yaml
Labels: autobump, new version

#15688 Update r-spp to 1.16.0
  recipes/r-spp/meta.yaml
Labels: autobump, new version

#15684 Update r-fastqcr to 0.1.2
  recipes/r-fastqcr/meta.yaml
Labels: autobump, new version

#15685 Update kma to 1.2.5
  recipes/kma/meta.yaml
Labels: autobump, new version

#15682 Update ont-fast5-api to 1.4.0
  recipes/ont-fast5-api/meta.yaml
Labels: autobump, new version

#15693 Update slivar to 0.1.3
  recipes/slivar/meta.yaml
Labels: autobump, new version

#15691 Update crispresso2 to 2.0.29
  recipes/crispresso2/meta.yaml
Labels: autobump, new version

#15681 Update sevenbridges-python to 0.20.3
  recipes/sevenbridges-python/meta.yaml
Labels: autobump, new version

#15701 Update Circos and Circos-Tools with current perl version
  recipes/circos-tools/meta.yaml
  recipes/circos/meta.yaml
Labels: please review & merge

#15669 Circle-Map bioconda recipe
  recipes/circle-map/meta.yaml
Labels: please review & merge

#15705 epic2: fix missing dep
  recipes/epic2/meta.yaml
Labels: please review & merge

#15708 Update planemo to 0.60.0
  recipes/planemo/meta.yaml
Labels: autobump, new version

#15707 Update nanoplotter to 1.8.1
  recipes/nanoplotter/meta.yaml
Labels: autobump, new version

#15646 Update PeptideShaker to 1.16.40
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
Labels: please review & merge

#15709 Update perl-cgi to 4.44
  recipes/perl-cgi/meta.yaml
Labels: autobump, new version, please review & merge

#15715 msstitch version to 2.13
  recipes/msstitch/meta.yaml
Labels: please review & merge

#15713 pyranges 0.0.44
  recipes/pyranges/meta.yaml
Labels: please review & merge

#15718 Bump wg-blimp to v0.9.3
  recipes/wg-blimp/meta.yaml
Labels: new version, please review & merge

#15722 Add ncbi-amr (antimicrobial resistance) recipe.
  recipes/insilicoseq/meta.yaml
  recipes/ncbi-amr/build.sh
  recipes/ncbi-amr/compile-fix.patch
  recipes/ncbi-amr/meta.yaml
Labels: please review & merge

#15714 epic2: 0.0.36 create-bigwigs
  recipes/epic2/LICENSE
  recipes/epic2/meta.yaml
Labels: please review & merge

#15727 Update mtsv to 1.0.4
  recipes/mtsv/meta.yaml
Labels: please review & merge

#15721 Vardict update
  recipes/hyphy/meta.yaml
  recipes/msstitch/meta.yaml
  recipes/peptide-shaker/meta.yaml
  recipes/perl-cgi/meta.yaml
  recipes/vardict-java/meta.yaml
  recipes/vardict/meta.yaml
Labels: please review & merge

#15735 MetaPhlAn2 updated to 2.9.11
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#15726 Bump freebayes to v1.3.1
  recipes/freebayes/build.sh
  recipes/freebayes/meta.yaml
Labels: please review & merge

#15737 Fix scikit-learn version dependency
  recipes/tapestry/meta.yaml
Labels: please review & merge

#15738 Add samplot 1.0.1
  recipes/samplot/build.sh
  recipes/samplot/meta.yaml
Labels: please review & merge

#15743 PacBio: Update `pbsv` to version 2.2.1
  recipes/pbsv/meta.yaml
Labels: please review & merge

#15728 Bump/proteinortho
  recipes/proteinortho/meta.yaml
Labels: new version, please review & merge

#15744 InSilicoSeq (version bump: 1.4.2)
  recipes/insilicoseq/meta.yaml
Labels: please review & merge

#15741 Bump wasabi to version which supports Salmon 0.14.
  recipes/r-wasabi/meta.yaml
Labels: please review & merge

#15742 csvtk 0.18.2
  recipes/csvtk/meta.yaml
Labels: please review & merge

#15749 MicroHapulator (version bump: 0.3)
  recipes/microhapulator/meta.yaml
Labels: please review & merge

#15753 bump sourmash to 2.0.1
  recipes/sourmash/meta.yaml
Labels: please review & merge

#15760 Update hicap to 1.0.1
  recipes/hicap/meta.yaml
Labels: new version, please review & merge

#15761 python-apollo: update to 3.1
  recipes/apollo/meta.yaml
Labels: please review & merge

#15764 add Illumina's paragraph tool
  recipes/paragraph/build.sh
  recipes/paragraph/meta.yaml
Labels: please review & merge

#15765 update seqcluster to fix bug
  recipes/seqcluster/meta.yaml
Labels: please review & merge

#15483 Update arvados-python-client to 1.4.0
  recipes/arvados-python-client/meta.yaml
Labels: autobump, new version

#15766 Update unitig-counter to v1.0.5
  recipes/unitig-counter/meta.yaml
Labels: please review & merge

#15782 Purge Haplotigs: Update to v1.1.0
  recipes/purge_haplotigs/meta.yaml
Labels: new version, please review & merge

#15768 update stream_atac to 0.3.3a
  recipes/stream_atac/meta.yaml
Labels: please review & merge

#15784 Wgfast update
  recipes/wgfast/meta.yaml
Labels: please review & merge

#15754 Blast2.9.0 update
  recipes/blast/build.sh
  recipes/blast/meta.yaml
  recipes/blast/run_test.sh
Labels: please review & merge

#15797 Ac trnanalysis
  recipes/trnanalysis/meta.yaml
Labels: please review & merge

#15791 ipyrad: make noarch python and use pip install
  recipes/ipyrad/meta.yaml
Labels: please review & merge, question

#15725 Metabat2: fix patch
  recipes/metabat2/0001-Fix-syntax-error-in-omp-reduction-initializer.patch
  recipes/metabat2/meta.yaml
Labels: please review & merge

#15757 Update mlst to 2.16.2
  recipes/mlst/meta.yaml
Labels: autobump, new version, please review & merge

#15808 update collect-columns
  recipes/collect-columns/meta.yaml
Labels: please review & merge

#15807 Gimmemotifs build
  recipes/gimmemotifs/meta.yaml
Labels: new version, please review & merge

#15811 update tb-profiler to v2.4
  recipes/tb-profiler/meta.yaml
Labels: new version, please review & merge

#15810 DeepBGC version 0.1.7
  recipes/deepbgc/meta.yaml
Labels: new version, please review & merge

#15813 Bump tximport version to 1.12.1.
  recipes/bioconductor-tximport/meta.yaml
Labels: please review & merge

#15814 Update MetaPhlAn2.9.12
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#15816 tximport: Add pointer to license file.
  recipes/bioconductor-tximport/meta.yaml
Labels: please review & merge

#15827 pysamstats: pin pysam version
  recipes/pysamstats/meta.yaml
Labels: please review & merge

#15832 [bbmap] Bump to 38.51
  recipes/bbmap/meta.yaml
Labels: new version

#15836 [socru] bump 2.0.0
  recipes/socru/meta.yaml
Labels: new version

#15830 snippy 4.4.0
  recipes/snippy/meta.yaml
Labels: new version

#15835 mtbseq bumb to v1.0.4
  recipes/mtbseq/meta.yaml
Labels: please review & merge

#15868 [socru] bump 2.1.0
  recipes/socru/meta.yaml
Labels: new version

#15752 New release of cgat-apps 0.5.4
  recipes/cgat-apps/build.sh
  recipes/cgat-apps/meta.yaml
Labels: please review & merge

#15719 Added recipe for biobaseHTTPtools
  recipes/biobasehttptools/build.sh
  recipes/biobasehttptools/meta.yaml
Labels: WIP

#15870 Atlas 2.1.3
  recipes/metagenome-atlas/meta.yaml
Labels: please review & merge

#15862 ribotricer: 1.0.3
  recipes/ribotricer/meta.yaml
Labels: new version, please review & merge

#15893 Update pyseer to v1.3.0
  recipes/pyseer/meta.yaml
Labels: please review & merge

#15861 plastid - fix using incompatible numpy
  recipes/plastid/meta.yaml
Labels: please review & merge

#15976 gat bump
  recipes/gat/build.sh
  recipes/gat/meta.yaml
Labels: new version, please review & merge

#15978 pysamstats strict pysam pinning
  recipes/pysamstats/meta.yaml
Labels: please review & merge

#15980 Add Xbioc
  recipes/xbioc/build.sh
  recipes/xbioc/meta.yaml
Labels: please review & merge

#15986 Add MuSiC, which I'm calling music-deconvolution
  recipes/music-deconvolution/build.sh
  recipes/music-deconvolution/meta.yaml
Labels: please review & merge

#15989 ensembl vep: bump subversio
  recipes/ensembl-vep/meta.yaml
Labels: please review & merge

#15990 new recipe: r-R4cker
  recipes/r-r4cker/build.sh
  recipes/r-r4cker/meta.yaml
Labels: please review & merge

#15988 add recipe for chunked-scatter
  recipes/chunked-scatter/meta.yaml
Labels: please review & merge

#15992 Bumping digestiflow-demux to v0.3.0
  recipes/digestiflow-demux/meta.yaml
Labels: please review & merge

#15979 Raxml ng
  recipes/raxml-ng/build.sh
  recipes/raxml-ng/meta.yaml
Labels: please review & merge

#15998 snakemake 5.5.1
  recipes/snakemake-minimal/meta.yaml
  recipes/snakemake/meta.yaml
Labels: please review & merge

#15993 trnanalysis
  recipes/trnanalysis/build.sh
  recipes/trnanalysis/meta.yaml
Labels: please review & merge

#16002 update pylibseq recipe
  recipes/pylibseq/build.sh
  recipes/pylibseq/header.patch
  recipes/pylibseq/meta.yaml
Labels: please review & merge

#16004 Advntr-1.3.1
  recipes/advntr/meta.yaml
Labels: GCC problems, help wanted

#16006 Update QTL-seq v2.0.2
  recipes/mutmap/meta.yaml
  recipes/qtlseq/meta.yaml
Labels: please review & merge

#16008 Added version 1.6.0
  recipes/rnalien/build.sh
  recipes/rnalien/meta.yaml
Labels: WIP, discussion, haskell

#16010 Bump CellBrowser to 0.5.37
  recipes/ucsc-cell-browser/meta.yaml
Labels: please review & merge

#16030 Releasing scelvis v0.3.0
  recipes/scelvis/meta.yaml
Labels: please review & merge

#16021 mirtop:update to last version
  recipes/mirtop/meta.yaml
Labels: please review & merge

#16028 Ncbi amrfinderplus
  recipes/ncbi-amrfinderplus/build.sh
  recipes/ncbi-amrfinderplus/compile-fix.patch
  recipes/ncbi-amrfinderplus/meta.yaml
Labels: please review & merge

#16040 Ncbi amrfinderplus
  recipes/ncbi-amrfinderplus/build.sh
  recipes/ncbi-amrfinderplus/compile-fix.patch
  recipes/ncbi-amrfinderplus/meta.yaml
Labels: please review & merge

#16044 Fix RNAsamba
  recipes/rnasamba/meta.yaml
Labels: please review & merge

#16047 Recipe for bustools (formerly #16042)
  recipes/bustools/build.sh
  recipes/bustools/meta.yaml
Labels: please review & merge

#16048 adVNTR-1.3.2
  recipes/advntr/meta.yaml
Labels: please review & merge

#12161 Update sqlalchemy-datatables to 2.0.1
  recipes/sqlalchemy-datatables/build.sh
  recipes/sqlalchemy-datatables/meta.yaml
Labels: autobump, please review & merge

#16062 Update adapterremoval to 2.3.1
  recipes/adapterremoval/meta.yaml
Labels: autobump

#15746 Fix GlimmerHMM missing training code
  recipes/glimmerHMM/build.sh
  recipes/glimmerhmm/build.sh
  recipes/glimmerhmm/meta.yaml
Labels: please review & merge

#16071 update seqbuster
  recipes/seqbuster/meta.yaml
Labels: please review & merge

#16039 Initial attempt at HMMRATAC
  recipes/hmmratac/HMMRATAC
  recipes/hmmratac/LICENSE
  recipes/hmmratac/build.sh
  recipes/hmmratac/meta.yaml
Labels: please review & merge

#16063 ldc > 1.10 causes segfaults
  recipes/sambamba/meta.yaml
Labels: please review & merge

#16070 Update segway recipe to version 2.0.5
  recipes/segway/meta.yaml
Labels: please review & merge

#16065 First attempt at sabre v1.000 recipe for BioConda
  recipes/sabre/build.sh
  recipes/sabre/makefile.patch
  recipes/sabre/meta.yaml
Labels: please review & merge

#15786 Guessmylt recipe
  recipes/guessmylt/meta.yaml
Labels: please review & merge

#16090 gtdbtk 0.3.0 update to post-link message
  recipes/gtdbtk/meta.yaml
  recipes/gtdbtk/post-link.sh
Labels: please review & merge

#16094 new version of cgatcore
  recipes/cgat-core/meta.yaml
Labels: please review & merge

#16043 Bump salmon version to v0.14.1 [WIP Please don't merge]
  recipes/salmon/meta.yaml
Labels: WIP

#16100 Use proper version number for seq2c.
  recipes/seq2c/meta.yaml
Labels: please review & merge

#16099 Update ncbi-vdb to 2.9.6
  recipes/ncbi-vdb/ar.patch
  recipes/ncbi-vdb/build.sh
  recipes/ncbi-vdb/exe.patch
  recipes/ncbi-vdb/gcc.patch
  recipes/ncbi-vdb/konfigure.patch
  recipes/ncbi-vdb/meta.yaml
Labels: please review & merge

#15763 Skip noarch linting for cnvkit
  recipes/cnvkit/meta.yaml
Labels: please review & merge

#16064 PICRUSt 1.1.3 --> 1.1.4
  recipes/picrust/meta.yaml
Labels: please review & merge

#16123 Add hca-matrix-downloader
  recipes/hca-matrix-downloader/meta.yaml
Labels: please review & merge

#16106 smof 2.14.3
  recipes/smof/meta.yaml
Labels: please review & merge

#16130 update BBMap to 38.56
  recipes/bbmap/0001-changed-jni-makefiles-to-be-more-standards-compatibl.patch
  recipes/bbmap/0002-enable-jni-path.patch
  recipes/bbmap/build.sh
  recipes/bbmap/meta.yaml
  recipes/bbmap/run_test.sh
Labels: new version, please review & merge
