Repository bioconda/bioconda-recipes, pull requests merged in 2019-05, with the labels that each got.

#14994 add recipe for thapbi-pict v0.1.6
  recipes/thapbi-pict/meta.yaml
Labels: enhancement

#14685 Rebuild bs_call
  recipes/bs_call/build.sh
  recipes/bs_call/meta.yaml
Labels: autobump, update pinning

#14580 Rebuild snp-dists
  recipes/snp-dists/build.sh
  recipes/snp-dists/meta.yaml
Labels: autobump, update pinning

#14930 Rebuild prophyle (python)
  recipes/prophyle/build.sh
  recipes/prophyle/meta.yaml
Labels: autobump, update pinning

#14791 Update scanpy to 1.4.1
  recipes/scanpy/meta.yaml
Labels: autobump, new version

#14888 Update bioconductor-variancepartition to 1.12.3
  recipes/bioconductor-variancepartition/meta.yaml
Labels: autobump, new version

#14894 Update bioconductor-immunespacer to 1.10.5
  recipes/bioconductor-immunespacer/meta.yaml
Labels: autobump, new version

#14935 Update bioconductor-rtn to 2.6.3
  recipes/bioconductor-rtn/meta.yaml
Labels: autobump, new version

#14798 Update r-samr to 3.0
  recipes/r-samr/meta.yaml
Labels: autobump, new version

#15048 Update StringTie to 1.3.6
  recipes/stringtie/1.0.3/build.sh
  recipes/stringtie/1.0.3/meta.yaml
  recipes/stringtie/1.0.4/build.sh
  recipes/stringtie/1.0.4/meta.yaml
  recipes/stringtie/meta.yaml
  recipes/stringtie/samtools_makefile.patch
Labels: new version

#14818 Update starfish to 0.1.0
  recipes/starfish/meta.yaml
Labels: autobump, new version

#15082 Update bbmap to 38.46
  recipes/bbmap/meta.yaml
Labels: autobump, new version

#15087 Update kipoi to 0.6.13
  recipes/kipoi/meta.yaml
Labels: autobump, new version

#15080 Update spaln to 2.3.3c
  recipes/spaln/meta.yaml
Labels: autobump, new version

#15089 Update vsearch to 2.13.3
  recipes/vsearch/meta.yaml
Labels: autobump, new version

#15086 Update bedops to 2.4.36
  recipes/bedops/meta.yaml
Labels: autobump, new version

#15085 Update parasail-python to 1.1.17
  recipes/parasail-python/meta.yaml
Labels: autobump, new version

#15088 Update arvados-python-client to 1.3.2.20190402172810
  recipes/arvados-python-client/meta.yaml
Labels: autobump, new version

#15110 Update minimap2 to v2.17
  recipes/mappy/meta.yaml
  recipes/minimap2/meta.yaml
Labels: new version

#14914 Rebuild molpopgen-analysis (gsl, openblas)
  recipes/molpopgen-analysis/meta.yaml
Labels: autobump, update pinning

#15124 Rebuild xatlas
  recipes/xatlas/meta.yaml
Labels: autobump, update pinning

#15123 Update perl-inline to 0.83
  recipes/perl-inline/meta.yaml
Labels: autobump, new version

#15121 Update arvados-cwl-runner to 1.3.2.20190419203205
  recipes/arvados-cwl-runner/meta.yaml
Labels: autobump, new version

#15131 Rebuild r2r (compiler)
  recipes/r2r/meta.yaml
Labels: autobump, update pinning

#15126 Update bioconductor-glimma to 1.10.1
  recipes/bioconductor-glimma/meta.yaml
Labels: autobump, new version

#15130 Update bioconductor-compcoder to 1.18.1
  recipes/bioconductor-compcoder/meta.yaml
Labels: autobump, new version

#15119 Update r-pscbs to 0.65.0
  recipes/r-pscbs/meta.yaml
Labels: autobump, new version

#15129 Update bioconductor-nbsplice to 1.0.6
  recipes/bioconductor-nbsplice/meta.yaml
Labels: autobump, new version

#15128 Update bioconductor-manta to 1.28.1
  recipes/bioconductor-manta/meta.yaml
Labels: autobump, new version

#15127 Update bioconductor-samexplorer to 1.6.1
  recipes/bioconductor-samexplorer/meta.yaml
Labels: autobump, new version

#15125 Update bioconductor-erccdashboard to 1.16.1
  recipes/bioconductor-erccdashboard/meta.yaml
Labels: autobump, new version

#15142 New recipe for InSilicoSeq
  recipes/insilicoseq/meta.yaml
Labels: please review & merge

#15107 rebuild perl-moose
  recipes/perl-moose/build.sh
  recipes/perl-moose/meta.yaml
Labels: help wanted

#15122 Update proteinortho to 6.0
  recipes/proteinortho/build.sh
  recipes/proteinortho/meta.yaml
Labels: autobump, new version

#14867 Update wiggletools to 1.2.3
  recipes/wiggletools/build.sh
  recipes/wiggletools/meta.yaml
Labels: autobump, new version

#14561 Update mash to 2.1.1
  recipes/mash/meta.yaml
Labels: autobump, new version

#14925 Update epic2 to 0.0.33
  recipes/epic2/meta.yaml
Labels: autobump, new version

#15215 Update seqlogo to 5.29.4
  recipes/seqlogo/meta.yaml
Labels: autobump, new version

#15174 Move cromwell to conda-forge
  recipes/cromwell/build.sh
  recipes/cromwell/cromwell.py
  recipes/cromwell/meta.yaml
  recipes/cromwell/womtool.py
Labels: WIP

#15240 Fix InSilicoSeq dependencies
  recipes/insilicoseq/bogus-genome.fasta.gz
  recipes/insilicoseq/checksums.md5
  recipes/insilicoseq/meta.yaml
  recipes/insilicoseq/run_test.sh
Labels: bug, please review & merge

#15254 Update fast5-research to 1.2.17
  recipes/fast5-research/meta.yaml
Labels: autobump, new version

#15250 Update sevenbridges-python to 0.20.2
  recipes/sevenbridges-python/meta.yaml
Labels: autobump, new version

#15251 Update validators to 0.12.6
  recipes/validators/meta.yaml
Labels: autobump, new version

#15252 Update vsearch to 2.13.4
  recipes/vsearch/meta.yaml
Labels: autobump, new version

#15257 Update treetime to 0.5.6
  recipes/treetime/meta.yaml
Labels: autobump, new version

#15258 Update slicedimage to 3.1.0
  recipes/slicedimage/meta.yaml
Labels: autobump, new version

#15259 Update pyteomics to 4.1.1
  recipes/pyteomics/meta.yaml
Labels: autobump, new version

#15261 Update ucsc-cell-browser to 0.5.21
  recipes/ucsc-cell-browser/meta.yaml
Labels: autobump, new version

#15256 Update arvados-python-client to 1.3.3.20190402172810
  recipes/arvados-python-client/meta.yaml
Labels: autobump, new version

#15260 Update scanpy to 1.4.2
  recipes/scanpy/meta.yaml
Labels: autobump, new version

#15263 Update phylopandas to 0.7.3
  recipes/phylopandas/meta.yaml
Labels: autobump, new version

#15266 Update duphold to 0.1.4
  recipes/duphold/meta.yaml
Labels: autobump, new version

#15267 Update sequenza-utils to 3.0.0
  recipes/sequenza-utils/meta.yaml
Labels: autobump, new version

#15268 Update r-classdiscovery to 3.3.12
  recipes/r-classdiscovery/meta.yaml
Labels: autobump, new version

#15269 Update perl-net-ssleay to 1.88
  recipes/perl-net-ssleay/meta.yaml
Labels: autobump, new version

#15272 Update r-phylosignal to 1.2.1
  recipes/r-phylosignal/meta.yaml
Labels: autobump, new version

#15273 Update perl-date-manip to 6.76
  recipes/perl-date-manip/meta.yaml
Labels: autobump, new version

#15274 Update r-cp4p to 0.3.6
  recipes/r-cp4p/meta.yaml
Labels: autobump, new version

#15271 Update arvados-cwl-runner to 1.3.3.20190419203205
  recipes/arvados-cwl-runner/meta.yaml
Labels: autobump, new version

#15275 Update bioconductor-flowutils to 1.46.1
  recipes/bioconductor-flowutils/meta.yaml
Labels: autobump, new version

#15276 Update bioconductor-flowviz to 1.46.1
  recipes/bioconductor-flowviz/meta.yaml
Labels: autobump, new version

#15277 Update uropa to 3.3.0
  recipes/uropa/meta.yaml
Labels: autobump, new version

#15278 Update bioconductor-flowai to 1.12.7
  recipes/bioconductor-flowai/meta.yaml
Labels: autobump, new version

#15279 Update perl-json to 4.02
  recipes/perl-json/meta.yaml
Labels: autobump, new version

#15281 Update nanofilt to 2.3.0
  recipes/nanofilt/meta.yaml
Labels: autobump, new version

#15284 Update perl-test-simple to 1.302164
  recipes/perl-test-simple/meta.yaml
Labels: autobump, new version

#15287 Update r-wgcna to 1.67
  recipes/r-wgcna/meta.yaml
Labels: autobump, new version

#15299 Update perl-extutils-depends to 0.8000
  recipes/perl-extutils-depends/meta.yaml
Labels: autobump, new version

#15302 Update perl-cgi to 4.43
  recipes/perl-cgi/meta.yaml
Labels: autobump, new version

#15300 Update perl-yaml to 1.28
  recipes/perl-yaml/meta.yaml
Labels: autobump, new version

#15291 Update wgs2ncbi to 1.0.3
  recipes/wgs2ncbi/meta.yaml
Labels: autobump, new version

#15288 Update perl-module-corelist to 5.20190420
  recipes/perl-module-corelist/meta.yaml
Labels: autobump, new version

#15298 Update bioconductor-flowsom to 1.14.1
  recipes/bioconductor-flowsom/meta.yaml
Labels: autobump, new version

#15297 Update bioconductor-ncdfflow to 2.28.1
  recipes/bioconductor-ncdfflow/meta.yaml
Labels: autobump, new version

#15295 Update bioconductor-deseq to 1.34.1
  recipes/bioconductor-deseq/meta.yaml
Labels: autobump, new version

#15294 Update bioconductor-sva to 3.30.1
  recipes/bioconductor-sva/meta.yaml
Labels: autobump, new version

#15292 Update bioconductor-msnbase to 2.8.3
  recipes/bioconductor-msnbase/meta.yaml
Labels: autobump, new version

#15289 Update bioconductor-phyloseq to 1.26.1
  recipes/bioconductor-phyloseq/meta.yaml
Labels: autobump, new version

#15286 Update perl-module-metadata to 1.000036
  recipes/perl-module-metadata/meta.yaml
Labels: autobump, new version

#15265 Update nanoplotter to 1.8.0
  recipes/nanoplotter/meta.yaml
Labels: autobump, new version

#15262 Update r-rgbif to 1.3.0
  recipes/r-rgbif/meta.yaml
Labels: autobump, new version

#15310 Update r-msqrob to 0.7.6
  recipes/r-msqrob/meta.yaml
Labels: autobump, new version

#15313 Update bioconductor-flowworkspace to 3.30.2
  recipes/bioconductor-flowworkspace/meta.yaml
Labels: autobump, new version

#15308 Update perl-module-scandeps to 1.27
  recipes/perl-module-scandeps/meta.yaml
Labels: autobump, new version

#15307 Update nanoplot to 1.24.0
  recipes/nanoplot/meta.yaml
Labels: autobump, new version

#15315 Update bioconductor-flowdensity to 1.16.1
  recipes/bioconductor-flowdensity/meta.yaml
Labels: autobump, new version

#15316 Update bioconductor-ggcyto to 1.10.2
  recipes/bioconductor-ggcyto/meta.yaml
Labels: autobump, new version

#15323 Update proteinortho to 6.0.1
  recipes/proteinortho/meta.yaml
Labels: autobump, new version

#15309 Update perl-html-form to 6.04
  recipes/perl-html-form/meta.yaml
Labels: autobump, new version

#15283 Update r-loose.rock to 1.0.12
  recipes/r-loose.rock/meta.yaml
Labels: autobump, new version

#14921 Update cpat to 2.0.0
  recipes/cpat/meta.yaml
Labels: autobump, new version

#15318 Update rsem to 1.3.2
  recipes/rsem/01_fix_cxx_11.patch
  recipes/rsem/02_fix_makefile.patch
  recipes/rsem/build.sh
  recipes/rsem/meta.yaml
Labels: autobump, new version

#15134 [WIP] Dependencies for r-dartr update
  recipes/r-hierfstat/build.sh
  recipes/r-hierfstat/meta.yaml
  recipes/r-mmod/build.sh
  recipes/r-mmod/meta.yaml
  recipes/r-popgenreport/build.sh
  recipes/r-popgenreport/meta.yaml
Labels: please review & merge

#15311 Update perl-sereal-decoder to 4.007
  recipes/perl-sereal-decoder/meta.yaml
Labels: autobump, new version

#15303 Update perl-dbd-pg to 3.8.0
  recipes/perl-dbd-pg/meta.yaml
Labels: autobump, new version

#15301 Update perl-devel-size to 0.83
  recipes/perl-devel-size/meta.yaml
Labels: autobump, new version

#14808 Update bioconductor-deqms to 1.0.1
  recipes/bioconductor-deqms/meta.yaml
Labels: autobump, new version

#14917 Update r-dartr to 1.1.11
  recipes/r-dartr/build.sh
  recipes/r-dartr/meta.yaml
Labels: autobump, new version

#15353 version bump (InSilicoSeq 1.3.6)
  recipes/insilicoseq/meta.yaml
Labels: please review & merge

#15372 Bumping scelvis to v0.2.0.
  recipes/scelvis/meta.yaml
Labels: please review & merge

#15040 Microhapulator
  recipes/microhapulator/meta.yaml
  recipes/microhapulator/run_test.sh
Labels: please review & merge

#15255 Update goatools to 0.9.5
  recipes/goatools/meta.yaml
Labels: autobump, new version

#14345 fineRADstructure
  recipes/fineradstructure/build.sh
  recipes/fineradstructure/meta.yaml
Labels: please review & merge

#15395 Bumping varfish-annotator to v0.5.
  recipes/varfish-annotator-cli/meta.yaml
Labels: please review & merge

#15413 update SPAdes to 3.13.1
  recipes/spades/meta.yaml
Labels: enhancement, new version

#15402 Add unitig-caller
  recipes/unitig-caller/meta.yaml
Labels: please review & merge

#15411 Update MetaBat to 2.13, add OSX, build from source
  recipes/metabat2/0001-Fix-syntax-error-in-omp-reduction-initializer.patch
  recipes/metabat2/0002-Rewrite-gzipFileBuf-without-gnu-ext-usage-breaks-osx.patch
  recipes/metabat2/0003-Remove-vendoring-of-zlib-and-htslib.patch
  recipes/metabat2/0004-Disable-CMake-c-14-pinning.patch
  recipes/metabat2/build.sh
  recipes/metabat2/meta.yaml
Labels: new version, please review & merge

#15388 update Crumble to version 0.82
  recipes/crumble/meta.yaml
Labels: please review & merge

#15424 Bumping varfish-annotator-cli to v0.6.
  recipes/varfish-annotator-cli/meta.yaml
Labels: please review & merge

#15446 Added purple-bio 0.4.2.1 to recipes
  recipes/purple-bio/meta.yaml
Labels: please review & merge

#14765 Update gappa to 0.4.0
  recipes/gappa/meta.yaml
Labels: autobump, new version

#15482 Update bbmap to 38.49
  recipes/bbmap/meta.yaml
Labels: autobump, new version

#15480 Update libbigwig to 0.4.4
  recipes/libbigwig/meta.yaml
Labels: autobump, new version

#15369 Add recipe for Telescope version 1.0.3
  recipes/telescope/meta.yaml
Labels: please review & merge

#15486 Update r-seurat to 3.0.1
  recipes/r-seurat/meta.yaml
Labels: autobump, new version

#15500 Update hic2cool to 0.6.0
  recipes/hic2cool/meta.yaml
Labels: autobump, new version

#15484 Update slicedimage to 3.1.1
  recipes/slicedimage/meta.yaml
Labels: autobump, new version

#15479 Update pauvre to 0.1923
  recipes/pauvre/meta.yaml
Labels: autobump, new version

#15494 Update cyvcf2 to 0.11.2
  recipes/cyvcf2/meta.yaml
Labels: autobump, new version

#15491 Update mothur to 1.42.1
  recipes/mothur/meta.yaml
Labels: autobump, new version

#15489 Update womtool to 41
  recipes/womtool/meta.yaml
Labels: autobump, new version

#15492 Update scanpy to 1.4.3
  recipes/scanpy/meta.yaml
Labels: autobump, new version

#15487 Update validators to 0.13.0
  recipes/validators/meta.yaml
Labels: autobump, new version

#15504 Update perl-sereal-encoder to 4.007
  recipes/perl-sereal-encoder/meta.yaml
Labels: autobump, new version

#15503 Update perl-net-http to 6.19
  recipes/perl-net-http/meta.yaml
Labels: autobump, new version

#15493 Update perl-text-csv to 2.00
  recipes/perl-text-csv/meta.yaml
Labels: autobump, new version

#15478 Update taxtastic to 0.8.11
  recipes/taxtastic/meta.yaml
Labels: autobump, new version

#15485 Update bcbiogff to 0.6.6
  recipes/bcbiogff/meta.yaml
Labels: autobump, new version

#15521 Recipe for new package rsidx
  recipes/rsidx/meta.yaml
  recipes/rsidx/run_test.sh
Labels: please review & merge

#15501 Update perl-yaml to 1.29
  recipes/perl-yaml/meta.yaml
Labels: autobump, new version

#15522 Update MicroHapulator recipe to release 0.2
  recipes/microhapulator/meta.yaml
  recipes/microhapulator/run_test.sh
Labels: please review & merge

#15496 Update r-xgr to 1.1.5
  recipes/r-xgr/meta.yaml
Labels: autobump, new version

#15488 Update moods to 1.9.4.1
  recipes/moods/meta.yaml
Labels: autobump, new version

#15498 Update tiddit to 2.7.1
  recipes/tiddit/LICENSE
  recipes/tiddit/meta.yaml
Labels: autobump, new version

#15497 Update atropos to 1.1.22
  recipes/atropos/meta.yaml
Labels: autobump, new version

#15542 Update perl-sereal to 4.007
  recipes/perl-sereal/meta.yaml
Labels: autobump, new version

#15543 Rebuilding bamhash to compile in latest libssl
  recipes/bamhash/1.1/meta.yaml
Labels: please review & merge

#15547 Bumping jannovar to v0.31.
  recipes/jannovar-cli/meta.yaml
Labels: please review & merge

#15568 add fastqsplitter recipe
  recipes/fastqsplitter/meta.yaml
Labels: please review & merge

#14659 Rebuild libgtextutils
  recipes/libgtextutils/meta.yaml
  recipes/libgtextutils/patch
Labels: autobump, update pinning

#14665 Rebuild libgenome
  recipes/libgenome/build.sh
  recipes/libgenome/meta.yaml
Labels: autobump, update pinning

#14669 Rebuild mageck
  recipes/mageck/build.sh
  recipes/mageck/meta.yaml
Labels: autobump, update pinning

#14663 Rebuild bpp-core
  recipes/bpp-core/meta.yaml
Labels: autobump, update pinning

#14645 Rebuild fraggenescan
  recipes/fraggenescan/build.sh
  recipes/fraggenescan/meta.yaml
Labels: autobump, update pinning

#14632 Rebuild centrifuge
  recipes/centrifuge/build.sh
  recipes/centrifuge/meta.yaml
Labels: autobump, update pinning

#15282 Update kipoi_veff to 0.3.0
  recipes/kipoi_veff/meta.yaml
Labels: autobump, new version

#14657 Rebuild shustring
  recipes/shustring/build.sh
  recipes/shustring/meta.yaml
Labels: autobump, update pinning

#14631 Rebuild beagle-lib
  recipes/beagle-lib/meta.yaml
Labels: autobump, update pinning

#14696 Rebuild swarm
  recipes/swarm/build.sh
  recipes/swarm/meta.yaml
Labels: autobump, update pinning

#14701 Rebuild python-hyphy-python
  recipes/python-hyphy-python/build.sh
  recipes/python-hyphy-python/meta.yaml
Labels: autobump, update pinning
