Repository bioconda/bioconda-recipes, pull requests merged in 2019-10, with the labels that each got.

#17725 bump FileDirUtil to v0.04
  recipes/perl-filedirutil/meta.yaml
Labels: please review & merge

#17800 Add a new tool, cvbio, for read-pair multi-species disambiguation
  recipes/cvbio/build.sh
  recipes/cvbio/cvbio.py
  recipes/cvbio/meta.yaml
Labels: please review & merge

#16256 Add SeqAn 3.0.0
  recipes/seqan3/bioconda.patch
  recipes/seqan3/build.sh
  recipes/seqan3/meta.yaml
Labels: please review & merge

#17834 Bumps r-loom to latest development version.
  recipes/r-loom/meta.yaml
Labels: please review & merge

#17816 nullarbor 2.0.20191003
  recipes/nullarbor/build.sh
  recipes/nullarbor/meta.yaml
Labels: new version, please review & merge

#17847 Force icu >=64 to avoid missing library issue for stringi
  recipes/r-loom/meta.yaml
Labels: please review & merge

#17829 Add fastalite
  recipes/fastalite/meta.yaml
Labels: please review & merge

#17932 Update GraphAligner to version 1.0.9
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#17946 Add recipe for bel-resources
  recipes/bel-resources/meta.yaml
Labels: please review & merge

#17950 Bump mapcaller
  recipes/mapcaller/meta.yaml
  recipes/mapcaller/src_makefile_flags.patch
Labels: please review & merge

#14929 Rebuild misopy
  recipes/misopy/meta.yaml
  recipes/misopy/patch
Labels: autobump, update pinning

#17947 add R package dependencies installation
  recipes/mapdamage2/meta.yaml
Labels: please review & merge

#17716 rmblast 2.9.0
  build-fail-blacklist
  recipes/maker/meta.yaml
  recipes/rmblast/boost_106400.patch
  recipes/rmblast/boost_106500.patch
  recipes/rmblast/build.sh
  recipes/rmblast/isb-2.9.0+-rmblast-p2.patch
  recipes/rmblast/meta.yaml
Labels: new version, please review & merge

#18010 change snpeff wrapper from shell script to python script
  recipes/snpeff/build.sh
  recipes/snpeff/meta.yaml
  recipes/snpeff/snpeff.py
  recipes/snpeff/snpeff.sh
Labels: please review & merge

#18058 fix repdenovo
  recipes/repdenovo/ContigsMerger.Makefile.new
  recipes/repdenovo/ContigsMerger.Makefile.patch
  recipes/repdenovo/TERefiner.Makefile.new
  recipes/repdenovo/TERefiner.Makefile.patch
  recipes/repdenovo/build.sh
  recipes/repdenovo/meta.yaml
Labels: please review & merge

#18069 nullarbor - add missing new deps
  recipes/nullarbor/meta.yaml
Labels: enhancement

#18082 Update Planemo requirements
  recipes/planemo/meta.yaml
Labels: please review & merge

#18070 SpliceAi python version
  recipes/spliceai/meta.yaml
Labels: please review & merge

#18090 RSEM Bump for R3.6.1
  build-fail-blacklist
  recipes/rsem/build.sh
  recipes/rsem/meta.yaml
Labels: please review & merge

#18089 mash 2.2.1 (fix wrong version reporting)
  recipes/mash/build.sh
  recipes/mash/meta.yaml
Labels: enhancement

#18098 mitos: version bump for bugfix release
  recipes/mitos/meta.yaml
  recipes/mitos/mitos1/meta.yaml
Labels: please review & merge

#18106 Decoypyrat
  recipes/decoypyrat/meta.yaml
Labels: please review & merge

#18096 rust-bio-tools 0.8.0
  recipes/rust-bio-tools/meta.yaml
Labels: please review & merge

#18109 mitos2: needs blast instead of legacy blast
  recipes/mitos/meta.yaml
Labels: please review & merge

#18114 Screw the bot
  recipes/mosdepth/build.sh
  recipes/mosdepth/install.diff
  recipes/mosdepth/meta.yaml
Labels: please review & merge

#18092 Bumped r-ichorcna version
  build-fail-blacklist
  recipes/r-ichorcna/build.sh
  recipes/r-ichorcna/meta.yaml
Labels: please review & merge

#18124 Added recipe for GenMap 1.0.2
  recipes/genmap/build.sh
  recipes/genmap/meta.yaml
Labels: please review & merge

#18130 Rebuild for R 3.6
  recipes/r-sleuth/meta.yaml
Labels: please review & merge

#18137 GenMap: fixed recipe
  recipes/genmap/build.sh
  recipes/genmap/meta.yaml
Labels: please review & merge

#18146 qualimap-2.1.1: Use OpenJDK
  recipes/qualimap/2.1.1/build.sh
  recipes/qualimap/2.1.1/meta.yaml
Labels: please review & merge

#18145 picard-1.141: Use OpenJDK
  recipes/picard/1.141/build.sh
  recipes/picard/1.141/meta.yaml
  recipes/picard/1.141/picard.sh
Labels: please review & merge

#18144 gatk-3.6: Use OpenJDK
  recipes/gatk/3.6/build.sh
  recipes/gatk/3.6/gatk-register.sh
  recipes/gatk/3.6/gatk.py
  recipes/gatk/3.6/meta.yaml
  recipes/gatk/3.6/post-link.sh
Labels: please review & merge

#18143 fastqc-0.11.5: Use OpenJDK
  recipes/fastqc/0.11.5/build.sh
  recipes/fastqc/0.11.5/java_xms.patch
  recipes/fastqc/0.11.5/meta.yaml
Labels: please review & merge

#18142 Update spectrum_utils: Add missing RDKit dependency
  recipes/spectrum_utils/meta.yaml
Labels: please review & merge

#18155 jpredapi
  recipes/jpredapi/meta.yaml
Labels: please review & merge

#18159 [fpa] try a macos build
  recipes/fpa/v0.5/meta.yaml
Labels: please review & merge

#18093 Added ABRA2 recipe
  recipes/abra2/abra2-wrapper.sh
  recipes/abra2/build.sh
  recipes/abra2/meta.yaml
Labels: help wanted

#18190 Bump RNAsamba to 0.2.0
  recipes/rnasamba/build.sh
  recipes/rnasamba/meta.yaml
Labels: please review & merge

#18212 snp-sites update to 2.5.1
  recipes/snp-sites/configure.patch
  recipes/snp-sites/meta.yaml
Labels: please review & merge

#18226 Update MicroHapDB to 0.4.1
  recipes/microhapdb/meta.yaml
  recipes/microhapdb/run_test.sh
Labels: please review & merge

#18219 adding ISEScan recipe
  recipes/isescan/build.sh
  recipes/isescan/constants.patch
  recipes/isescan/meta.yaml
Labels: please review & merge

#18218 Add TETyper
  recipes/tetyper/meta.yaml
Labels: please review & merge

#18252 add recipe for fastq-dl
  recipes/fastq-dl/build.sh
  recipes/fastq-dl/meta.yaml
Labels: please review & merge

#18256 Add LoomExperiment as dependency for SCMap
  recipes/scmap-cli/meta.yaml
Labels: please review & merge

#18264 dialign-tx : disable SSE and MMX optimization
  recipes/dialign-tx/build.sh
  recipes/dialign-tx/meta.yaml
Labels: please review & merge

#18263 Boink07
  recipes/graph-boink/build.sh
  recipes/graph-boink/meta.yaml
Labels: please review & merge

#18282 Bump duphold to 0.2.1.
  recipes/duphold/meta.yaml
Labels: please review & merge

#18296 Adding clsify v0.1.0.
  recipes/clsify/meta.yaml
Labels: please review & merge

#18306 Add knock-knock 0.2.1
  recipes/knock-knock/meta.yaml
Labels: please review & merge

#18311 Add recipe for vibrant
  recipes/vibrant/build.sh
  recipes/vibrant/download-db.sh
  recipes/vibrant/meta.yaml
  recipes/vibrant/path.patch
  recipes/vibrant/post-link.sh
Labels: please review & merge

#18317 added BiasAway
  recipes/biasaway/meta.yaml
Labels: please review & merge

#18331 Add wget dependency
  recipes/vibrant/meta.yaml
Labels: please review & merge

#18341 Coding quarry fix build QuarryFiles location
  recipes/codingquarry/build.sh
  recipes/codingquarry/meta.yaml
Labels: please review & merge

#18304 Fix isescan
  recipes/isescan/build.sh
  recipes/isescan/meta.yaml
Labels: please review & merge

#18387 EaCoN
  recipes/r-eacon/build.sh
  recipes/r-eacon/meta.yaml
Labels: please review & merge

#18391 add mtsv_tools 1.0.0 recipe
  recipes/mtsv-tools/build.sh
  recipes/mtsv-tools/meta.yaml
Labels: please review & merge

#18400 Salmon 1.0.0 breaks Trinity
  recipes/trinity/meta.yaml
Labels: please review & merge
