Repository bioconda/bioconda-recipes, pull requests merged in 2019-12, with the labels that each got.

#19011 update SPAdes to 3.13.2
  recipes/spades/meta.yaml
Labels: new version, please review & merge

#19012 add tar requirement to maxbin2
  recipes/maxbin2/meta.yaml
Labels: please review & merge

#19017 Update mafft
  recipes/mafft/build.sh
  recipes/mafft/linux-makefile.patch
  recipes/mafft/meta.yaml
  recipes/mafft/osx-makefile.patch
Labels: please review & merge

#19010 Update primer3 py
  recipes/primer3-py/build.sh
  recipes/primer3-py/meta.yaml
Labels: please review & merge

#19025 Update CheckM to 1.1.0 which now uses python 3.6
  recipes/checkm-genome/meta.yaml
Labels: please review & merge

#19026 Update gemma to 0.98.1
  recipes/gemma/build.sh
  recipes/gemma/meta.yaml
Labels: please review & merge

#19034 updated icun_sim to 1.5
  recipes/iucn_sim/meta.yaml
Labels: please review & merge

#19036 Phyphy
  recipes/phyphy/LICENSE.txt
  recipes/phyphy/meta.yaml
Labels: please review & merge

#19042 Coinfinder recipe
  recipes/coinfinder/build.sh
  recipes/coinfinder/meta.yaml
Labels: please review & merge

#19041 qualimap add fonts requirement
  recipes/qualimap/meta.yaml
Labels: please review & merge

#19060 abyss: Add util-linux for column command
  recipes/abyss/meta.yaml
Labels: please review & merge

#19062 Use extended base for quast
  recipes/quast/meta.yaml
Labels: please review & merge

#19065 Update genie recipe
  recipes/genie/build.sh
  recipes/genie/meta.yaml
Labels: please review & merge

#19051 Fastml
  recipes/fastml/build.sh
  recipes/fastml/meta.yaml
  recipes/fastml/post-link.sh
Labels: please review & merge

#19046 Add array-as-vcf
  recipes/array-as-vcf/meta.yaml
Labels: please review & merge

#19071 rebuild xsd
  recipes/xsd/build.sh
  recipes/xsd/meta.yaml
Labels: please review & merge

#19016 blast 2.2.21 -> 2.2.31: and backport changes from latest
  build-fail-blacklist
  recipes/blast/2.2.21/build.sh
  recipes/blast/2.2.21/legacy_blast.pl.patch
  recipes/blast/2.2.21/update_blastdb.pl.patch
  recipes/blast/2.2.31/build.sh
  recipes/blast/2.2.31/configure.patch
  recipes/blast/2.2.31/meta.yaml
  recipes/blast/2.2.31/run_test.sh
  recipes/blast/2.2.31/test.fa
  recipes/blast/2.2.31/testdatabase.fa
Labels: please review & merge

#19078 Update pyseer to 1.3.4
  recipes/pyseer/meta.yaml
Labels: please review & merge

#19053 [Biotradis] Update to version 1.4.5
  recipes/biotradis/meta.yaml
Labels: please review & merge

#19096 GTDB-Tk version 1.0.0
  recipes/gtdbtk/meta.yaml
  recipes/gtdbtk/post-link.sh
Labels: please review & merge

#19093 [Biotradis] Fix bioperl path
  recipes/biotradis/meta.yaml
Labels: please review & merge

#19106 Mwga utils
  recipes/mwga-utils/build.sh
  recipes/mwga-utils/meta.yaml
Labels: please review & merge

#19101 new recipe for nseg to be used to fix RepeatScout and RepeatModeler recipes
  recipes/nseg/build.sh
  recipes/nseg/meta.yaml
Labels: please review & merge

#19120 Update plass to release 3-764a3
  recipes/plass/meta.yaml
Labels: please review & merge

#19123 gtdbtk to support linux only
  recipes/gtdbtk/meta.yaml
Labels: please review & merge

#19124 update genie recipe
  recipes/genie/meta.yaml
Labels: please review & merge

#19128 Add dash
  recipes/mafft/build.sh
  recipes/mafft/meta.yaml
Labels: please review & merge

#19108 perl-data-predicate, perl-ensembl-core, perl-ensembl-funcgen
  recipes/perl-data-predicate/build.sh
  recipes/perl-data-predicate/meta.yaml
  recipes/perl-ensembl-core/build.sh
  recipes/perl-ensembl-core/meta.yaml
  recipes/perl-ensembl-funcgen/build.sh
  recipes/perl-ensembl-funcgen/meta.yaml
Labels: please review & merge

#19029 stacks: add 1.46 branch
  recipes/stacks/1.46/at.patch
  recipes/stacks/1.46/build.sh
  recipes/stacks/1.46/meta.yaml
Labels: please review & merge

#19115 GraphEmbed v2.4
  recipes/graph_embed/LICENSE
  recipes/graph_embed/build.sh
  recipes/graph_embed/meta.yaml
Labels: please review & merge

#18392 Add perl-bio-bigfile
  recipes/perl-bio-bigfile/build.sh
  recipes/perl-bio-bigfile/meta.yaml
Labels: please review & merge

#19130 Rebuild mtnucratio
  recipes/mtnucratio/meta.yaml
Labels: please review & merge

#19133 GimmeMotifs: fix osx
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#18808 Add perl-ensembl-core
  recipes/perl-ensembl-compara/build.sh
  recipes/perl-ensembl-compara/meta.yaml
  recipes/perl-ensembl-genomes/build.sh
  recipes/perl-ensembl-genomes/meta.yaml
  recipes/perl-ensembl-io/build.sh
  recipes/perl-ensembl-io/meta.yaml
  recipes/perl-ensembl-variation/build.sh
  recipes/perl-ensembl-variation/meta.yaml
Labels: please review & merge

#19136 recipe for scpred-cli
  recipes/scpred-cli/build.sh
  recipes/scpred-cli/meta.yaml
Labels: please review & merge

#19142 update genie recipe
  recipes/genie/meta.yaml
Labels: please review & merge

#19153 Add mtsv-tools requirement to mtsv
  recipes/mtsv/meta.yaml
Labels: please review & merge

#19157 perl-ensembl-api
  recipes/perl-ensembl-api/meta.yaml
Labels: please review & merge

#19129 Fixed a bug
  recipes/mafft/build.sh
  recipes/mafft/meta.yaml
Labels: please review & merge

#19164 Trying to rebuild perl-string-random
  build-fail-blacklist
  recipes/perl-string-random/0.30/meta.yaml
Labels: please review & merge

#19173 Mwga utils
  recipes/mwga-utils/meta.yaml
Labels: please review & merge

#19179 makeblastdb for RepeatPeps.lib needed for RepeatModeler
  recipes/repeatmasker/build.sh
  recipes/repeatmasker/meta.yaml
Labels: please review & merge

#16532 rebuild percolator
  build-fail-blacklist
  recipes/percolator/build.sh
  recipes/percolator/meta.yaml
Labels: please review & merge

#19217 recipe for MinYS
  recipes/minys/build.sh
  recipes/minys/meta.yaml
Labels: please review & merge

#19230 meme-5.1.0
  recipes/meme/meta.yaml
Labels: please review & merge

#19220 Specify gsl version
  recipes/phylocsf/meta.yaml
Labels: please review & merge

#19216 Bumped svdb version. Now with Python 3 support.
  recipes/svdb/meta.yaml
Labels: please review & merge

#19232 Update Galaxy-ML to v0.8.0
  recipes/galaxy-ml/meta.yaml
Labels: please review & merge

#19253 first attempt to add falco to bioconda
  recipes/falco/build.sh
  recipes/falco/meta.yaml
Labels: please review & merge

#19249 add assemblytics
  recipes/assemblytics/build.sh
  recipes/assemblytics/libexec.patch
  recipes/assemblytics/meta.yaml
Labels: please review & merge

#19252 Gtdbtk 1.0.2 updates
  recipes/gtdbtk/meta.yaml
  recipes/gtdbtk/post-link.sh
Labels: please review & merge

#19237 Recipe to build scvelo python package.
  recipes/scvelo/meta.yaml
Labels: please review & merge

#19137 Fix repeatmodeler recipe
  recipes/repeatmodeler/RepModelConfig.pm
  recipes/repeatmodeler/build.sh
  recipes/repeatmodeler/meta.yaml
  recipes/repeatmodeler/run_test.sh
  recipes/repeatmodeler/test.fa
Labels: please review & merge

#19262 Maintain pysam 0.15.2 for medaka
  .github/workflows/CommentResponder.yml
  recipes/pysam/0.15.2/build.sh
  recipes/pysam/0.15.2/meta.yaml
Labels: please review & merge

#19275 Add samtools headers to the conda include folder (for tools that require samtools as a build dependency)
  recipes/samtools/build.sh
  recipes/samtools/meta.yaml
Labels: please review & merge

#19284 update sha256sum for falco. Release was changed to be conda compatible
  recipes/falco/build.sh
  recipes/falco/meta.yaml
Labels: please review & merge

#19268 Atlas v2.3
  recipes/metagenome-atlas/meta.yaml
Labels: please review & merge

#19292 CoverM: Update to 0.3.2.
  recipes/coverm/build.sh
  recipes/coverm/meta.yaml
Labels: please review & merge

#19298 Update tRNAscan-SE to 2.0.5
  recipes/trnascan-se/meta.yaml
Labels: please review & merge

#19297 Add Bolt recipe
  recipes/bolt/build.sh
  recipes/bolt/meta.yaml
Labels: please review & merge

#19308 Add TEtranscripts
  recipes/tetranscripts/meta.yaml
Labels: please review & merge

#19315 [medusa] Add recipes for medusa
  recipes/medusa/build.sh
  recipes/medusa/meta.yaml
Labels: please review & merge

#19333 update for v0.98.15 of w4mclassfilter
  recipes/w4mclassfilter/meta.yaml
Labels: please review & merge

#19336 Adding Haplotype-LSO
  recipes/haplotype-lso/meta.yaml
Labels: please review & merge

#19343 add ReferenceSeeker v1.2
  recipes/referenceseeker/meta.yaml
Labels: please review & merge

#19341 [medusa] add forgoten python dependencys
  recipes/medusa/meta.yaml
Labels: please review & merge

#19349 bump referenceseeker version v1.3
  recipes/referenceseeker/meta.yaml
Labels: please review & merge

#19348 New OncoGEMINI recipe
  recipes/oncogemini/meta.yaml
Labels: please review & merge

#19355 Add velocyto.py
  recipes/velocyto.py/meta.yaml
Labels: please review & merge

#19367 dsh-bio 1.3
  recipes/dsh-bio/build.sh
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#19368 adam 0.30.0
  recipes/adam/meta.yaml
Labels: please review & merge

#19299 Add DeepLC recipe
  recipes/deeplc/LICENSE
  recipes/deeplc/meta.yaml
Labels: please review & merge

#19131 Busco 4.0.0 beta
  recipes/busco/build.sh
  recipes/busco/meta.yaml
  recipes/busco/post-link.sh
  recipes/busco/run_test.sh
Labels: help wanted, please review & merge

#19369 cannoli 0.8.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#19259 Add ngsderive recipe to bioconda
  recipes/ngsderive/meta.yaml
Labels: please review & merge

#19383 Update clair build
  recipes/clair/meta.yaml
Labels: please review & merge

#19392 bump referenceseeker to v1.4
  recipes/referenceseeker/meta.yaml
Labels: please review & merge

#19391 Bio::Trace::Abif
  recipes/perl-bio-trace-abif/build.sh
  recipes/perl-bio-trace-abif/meta.yaml
Labels: please review & merge

#19386 GimmeMotifs version 0.14.1
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#19409 Removing nanoplotter
  recipes/nanocomp/meta.yaml
  recipes/nanoplot/meta.yaml
Labels: please review & merge

#19428 update ganon to version 0.2.0
  recipes/ganon/meta.yaml
Labels: please review & merge

#19410 [perl-fastx-abi] Recipe for FASTX::Abi
  recipes/perl-fastx-abi/build.sh
  recipes/perl-fastx-abi/meta.yaml
Labels: please review & merge

#19444 PacBio: Add `pbmarkdup` version 0.2.0
  recipes/pbmarkdup/build.sh
  recipes/pbmarkdup/meta.yaml
  recipes/pbmarkdup/post-link.sh
Labels: please review & merge

#19447 gatk4-r-deps
  recipes/gatk4/meta.yaml
Labels: please review & merge

#19439 Add MACARON 0.7
  recipes/macaron/build.sh
  recipes/macaron/meta.yaml
Labels: please review & merge

#19420 Add scripts to novobreak recipe
  recipes/novobreak/build.sh
  recipes/novobreak/meta.yaml
Labels: please review & merge

#19397 Busco 4.0.0
  recipes/busco/build.sh
  recipes/busco/meta.yaml
  recipes/busco/post-link.sh
  recipes/busco/run_test.sh
Labels: please review & merge

#19466 ipyrad: Remove patch which was breaking the bioconda build
  recipes/ipyrad/meta.yaml
  recipes/ipyrad/patch
Labels: please review & merge

#19385 extended-base for fastx_toolkit
  recipes/fastx_toolkit/build.sh
  recipes/fastx_toolkit/meta.yaml
Labels: please review & merge

#19436 Revert PR #19275 -- don't install legacy samtools headers
  recipes/samtools/build.sh
  recipes/samtools/meta.yaml
Labels: please review & merge

#19471 Adding Haplotype-Lso v0.3.4
  recipes/haplotype-lso/meta.yaml
Labels: please review & merge

#19460 Ac tranalysis v0.1.8 b1
  recipes/trnanalysis/meta.yaml
Labels: please review & merge

#19459 New: gnomic, microbial genotype/phenotype grammar
  recipes/gnomic/meta.yaml
Labels: please review & merge

#19472 New: escher, metabolic pathway visualization
  recipes/escher/meta.yaml
Labels: please review & merge

#19474 add recipe for ncbitk
  recipes/ncbitk/meta.yaml
Labels: please review & merge

#19476 Bumping haplotype-lso to v0.4.0
  recipes/haplotype-lso/meta.yaml
Labels: please review & merge

#19486 w4mclassfilter v0.98.18
  recipes/w4mclassfilter/meta.yaml
Labels: please review & merge

#19495 bump gffutils to v0.10.1
  recipes/gffutils/build.sh
  recipes/gffutils/meta.yaml
Labels: please review & merge

#19494 Phispy
  recipes/phispy/meta.yaml
Labels: please review & merge
