Repository bioconda/bioconda-recipes, pull requests merged in 2019-08, with the labels that each got.

#16624 mkl build of blas for concoct
  recipes/concoct/meta.yaml
Labels: please review & merge

#16661 Fix nightly
  recipes/colombo/meta.yaml
Labels: please review & merge

#16659 amptk v1.4.1 bump version
  recipes/amptk/meta.yaml
Labels: please review & merge

#16631 Update selene-sdk to 0.4.1
  recipes/selene-sdk/meta.yaml
Labels: please review & merge

#16585 Add recipe for CARNAC-LR
  recipes/carnac-lr/License.txt
  recipes/carnac-lr/build.sh
  recipes/carnac-lr/makefile.patch
  recipes/carnac-lr/meta.yaml
  recipes/carnac-lr/python_path.patch
  recipes/carnac-lr/run_test.sh
  recipes/carnac-lr/test.input
Labels: please review & merge

#16608 PICRUSt2 update from 2.1.4-b to 2.2.0-b
  recipes/picrust2/meta.yaml
  recipes/picrust2/post-link.sh
Labels: please review & merge

#16676 Adding new recipe for BAMscale
  recipes/bamscale/build.sh
  recipes/bamscale/meta.yaml
Labels: please review & merge

#16662 update fastqsplitter to 1.1.0
  recipes/fastqsplitter/meta.yaml
Labels: please review & merge

#16704 Add recipe for rTASSEL
  recipes/r-rtassel/build.sh
  recipes/r-rtassel/meta.yaml
Labels: please review & merge

#16713 Locarna2
  build-fail-blacklist
  recipes/locarna/1.8.10/build.sh
  recipes/locarna/1.8.10/meta.yaml
  recipes/locarna/1.8.11/build.sh
  recipes/locarna/1.8.11/meta.yaml
  recipes/locarna/1.8.12/meta.yaml
  recipes/locarna/1.8.7/build.sh
  recipes/locarna/1.8.7/meta.yaml
  recipes/locarna/1.8.9/build.sh
  recipes/locarna/1.8.9/meta.yaml
  recipes/locarna/1.9.0/build.sh
  recipes/locarna/1.9.0/meta.yaml
  recipes/locarna/1.9.1/build.sh
  recipes/locarna/1.9.2/biotools.yaml
  recipes/locarna/1.9.2/build.sh
  recipes/locarna/1.9.2/meta.yaml
  recipes/locarna/build.sh
  recipes/locarna/meta.yaml
Labels: please review & merge

#16723 [intarna] Remove old recipe 2.1.0 from repository and blacklist
  build-fail-blacklist
  recipes/intarna/2.1.0/build.sh
  recipes/intarna/2.1.0/meta.yaml
Labels: please review & merge

#16729 Bumping Meme to version 5.0.5
  recipes/meme/build.sh
  recipes/meme/meta.yaml
Labels: please review & merge

#16732 Restore linking of PureCN analysis scripts.
  build-fail-blacklist
  recipes/bioconductor-genomicfeatures/meta.yaml
  recipes/bioconductor-purecn/build.sh
  recipes/bioconductor-purecn/meta.yaml
  recipes/bioconductor-rtracklayer/meta.yaml
Labels: please review & merge

#16758 update crispritz to 2.1.0
  recipes/crispritz/meta.yaml
Labels: autobump, new version

#16767 Update GraphAligner to version 1.0.8
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#16770 Fix bamread py3k builds
  recipes/bamread/meta.yaml
Labels: please review & merge

#16771 Build pyrle for all py3k
  recipes/pyrle/meta.yaml
Labels: please review & merge

#16777 Pathogist 0.3.6
  recipes/pathogist/meta.yaml
  recipes/pathogist/setup.py
Labels: please review & merge

#16803 prokka 1.14.0
  recipes/prokka/build.sh
  recipes/prokka/meta.yaml
Labels: new version

#16817 Bumped GATK4 version
  recipes/gatk4/meta.yaml
Labels: please review & merge

#16852 trinity: change quoting in perl script
  recipes/trinity/build.sh
  recipes/trinity/meta.yaml
Labels: please review & merge

#16813 [seurat-scripts] Adds mscorefonts to avoid plots with no letters
  recipes/seurat-scripts/meta.yaml
Labels: please review & merge

#16866 trying to support PBWT on Mac
  recipes/pbwt/meta.yaml
Labels: please review & merge

#16873 trinity: restore missing semicolon
  recipes/trinity/build.sh
  recipes/trinity/meta.yaml
Labels: please review & merge

#12220 Update hichipper to 0.7.7
  recipes/hichipper/meta.yaml
Labels: autobump

#16882 add python-htsget
  recipes/python-htsget/meta.yaml
Labels: please review & merge

#12169 Update phizz to 0.2.3
  recipes/phizz/meta.yaml
Labels: autobump

#16827 isPcr 33 (new recipe)
  recipes/ispcr/0001-remove-Werror.patch
  recipes/ispcr/build.sh
  recipes/ispcr/meta.yaml
Labels: WIP

#16919 Bump medaka's minimap2 version
  recipes/medaka/meta.yaml
Labels: please review & merge

#16918 Update meta.yaml to remove mpi4py
  recipes/ipyrad/meta.yaml
Labels: please review & merge

#16911 Phylo csf
  recipes/phylocsf/LICENSE
  recipes/phylocsf/build.sh
  recipes/phylocsf/meta.yaml
  recipes/phylocsf/tests/tal-AA.fa
Labels: please review & merge

#16928 MetaPhlAn2 updated to version 2.9.20
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#12163 Update synapseclient to 1.9.3
  recipes/synapseclient/meta.yaml
Labels: autobump

#16926 Try to fix opencontactcli recipe
  recipes/opencontactcli/meta.yaml
Labels: please review & merge

#14809 Update eagle to 0.9.4.6
  recipes/eagle/build.sh
  recipes/eagle/meta.yaml
Labels: autobump, new version

#16927 update stringTie
  recipes/stringtie/build.sh
  recipes/stringtie/meta.yaml
Labels: please review & merge

#16960 remove migrated recipes
  recipes/r-bipartite/build.sh
  recipes/r-bipartite/meta.yaml
  recipes/r-enrichr/build.sh
  recipes/r-enrichr/meta.yaml
  recipes/r-kaos/build.sh
  recipes/r-kaos/meta.yaml
  recipes/r-loose.rock/build.sh
  recipes/r-loose.rock/meta.yaml
  recipes/r-rbison/build.sh
  recipes/r-rbison/meta.yaml
  recipes/r-taxa/build.sh
  recipes/r-taxa/meta.yaml
Labels: please review & merge

#16764 Added SvABA recipe
  recipes/svaba/build.sh
  recipes/svaba/meta.yaml
Labels: help wanted

#15696 Update hic2cool to 0.7.3
  recipes/hic2cool/meta.yaml
Labels: autobump, new version

#16990 Add Logomaker
  recipes/logomaker/meta.yaml
Labels: please review & merge

#16989 bcftools polysomy
  recipes/bcftools/build.sh
  recipes/bcftools/meta.yaml
Labels: please review & merge

#16937 build spades from source
  recipes/spades/0001-change-verbosity.patch
  recipes/spades/0001-fix-cpu-count.patch
  recipes/spades/0002-disable-parallel-libstdc.patch
  recipes/spades/build.sh
  recipes/spades/meta.yaml
Labels: please review & merge

#16103 add r-immunedeconv
  recipes/r-immunedeconv/meta.yaml
Labels: please review & merge

#17004 Remove 5 packages from the blacklist
  build-fail-blacklist
  recipes/bioconductor-pga/meta.yaml
  recipes/bioconductor-proteoqc/meta.yaml
  recipes/bioconductor-rtandem/build.sh
  recipes/bioconductor-rtandem/meta.yaml
  recipes/bioconductor-rtandem/patch
  recipes/bioconductor-sapfinder/meta.yaml
  recipes/bioconductor-shinytandem/meta.yaml
Labels: please review & merge

#17006 spades: dropped unneeded dependencies; added post-link script to warn about a MacOS issue; cleaned up meta.yaml .
  recipes/spades/meta.yaml
  recipes/spades/post-link.sh
Labels: please review & merge, update build number

#17011 Aquila umap
  recipes/aquila_umap/meta.yaml
Labels: please review & merge

#17014 kounta 0.2.0 (new recipe)
  recipes/kounta/build.sh
  recipes/kounta/meta.yaml
Labels: please review & merge

#17030 Update MAGeCK to 0.5.9.2
  recipes/mageck/meta.yaml
Labels: new version, please review & merge

#17043 Update MMseqs2 to new release 10-6d92c
  recipes/mmseqs2/meta.yaml
Labels: new version, please review & merge

#17046 abricate 0.9.3
  recipes/abricate/meta.yaml
Labels: new version, please review & merge

#17070 Add Msaconverter: A command line tool for converting multiple sequence alignments (MSAs) into different formats
  recipes/msaconverter/meta.yaml
Labels: please review & merge

#17071 Add bold-identification: A tool for taxonomic assignment for given sequences
  recipes/bold-identification/meta.yaml
Labels: please review & merge

#17076 Remove pin on pysam
  recipes/crossmap/meta.yaml
Labels: enhancement

#17050 vcflib 1.0.0-rc3
  recipes/vcflib/build.sh
  recipes/vcflib/meta.yaml
Labels: GCC problems, help wanted, new version

#17081 Add taxonomy_ranks: A tool for getting the lineage information of input taxid, species name, or higher ranks (e.g., Family, Order) with ETE3 package.
  recipes/taxonomy_ranks/meta.yaml
Labels: please review & merge

#17082 Add extract_fasta_seq: A tool for extracting specific FASTA sequences
  recipes/extract_fasta_seq/meta.yaml
Labels: please review & merge

#17089 snippy 4.4.3 - update dependencies
  recipes/snippy/meta.yaml
Labels: enhancement, please review & merge, update build number

#17096 Add extract-codon-alignment: A tool for extracting some codon positions (1st, 2nd, 3rd) from a CDS alignment
  recipes/extract-codon-alignment/meta.yaml
Labels: please review & merge

#17124 Adding jupyterpngsplugin python package to Bioconda
  recipes/jupyterngsplugin/meta.yaml
Labels: help wanted

#14862 Update angsd to 0.931
  recipes/angsd/build.sh
  recipes/angsd/meta.yaml
Labels: autobump, new version

#17131 Adding goenrichment python package
  recipes/python-goenrichment/meta.yaml
Labels: help wanted

#17138 bump iranges to 2.18.2
  recipes/bioconductor-iranges/meta.yaml
  recipes/r-transformer/meta.yaml
Labels: please review & merge

#17140 Smudgeplot
  recipes/smudgeplot/build.sh
  recipes/smudgeplot/meta.yaml
Labels: please review & merge

#12573 Update downpore to 0.3.3
  recipes/downpore/build.sh
  recipes/downpore/meta.yaml
Labels: autobump

#12213 Update gprofiler-official to 1.0.0
  recipes/gprofiler-official/build.sh
  recipes/gprofiler-official/meta.yaml
Labels: autobump

#12199 Update control-freec to 11.5
  recipes/control-freec/build.sh
  recipes/control-freec/meta.yaml
Labels: autobump

#17150 minced 0.4.0 - build with older java
  recipes/minced/build.sh
  recipes/minced/meta.yaml
Labels: enhancement

#15706 Update masurca to 3.3.3
  recipes/masurca/build.sh
  recipes/masurca/meta.yaml
Labels: autobump, new version

#12188 Update breseq to 0.33.2
  recipes/breseq/build.sh
  recipes/breseq/meta.yaml
Labels: autobump

#12175 Update spine to 0.3.2
  recipes/spine/meta.yaml
  recipes/spine/spine.patch
Labels: autobump
