Repository bioconda/bioconda-recipes, pull requests merged in 2019-07, with the labels that each got.

#16155 Bumping varfish-annotator-cli to v0.8
  recipes/varfish-annotator-cli/meta.yaml
Labels: please review & merge

#16129 update stream_atac to 0.3.4
  recipes/stream_atac/meta.yaml
Labels: please review & merge

#16186 MetaPhlAn2 updated to 2.9.13
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#16185 VEP: bump version
  recipes/ensembl-vep/build.sh
  recipes/ensembl-vep/meta.yaml
Labels: new version, please review & merge

#16172 Circos to version 0.69.8
  recipes/circos/meta.yaml
Labels: please review & merge

#16190 Qcat 1 0 7
  recipes/qcat/meta.yaml
Labels: please review & merge

#16196 Revision up sample-sheet to 0.9.1
  recipes/sample-sheet/meta.yaml
Labels: help wanted

#16199 try building on OSX
  recipes/pytabix/build.sh
  recipes/pytabix/meta.yaml
Labels: please review & merge

#16205 Bumping varfish-annotator-cli version to v0.9
  recipes/varfish-annotator-cli/meta.yaml
Labels: please review & merge

#16197 Update CONTRIBUTING hyperlink
  CONTRIBUTING.md
Labels: please review & merge

#16203 Bump/scanpy scripts
  recipes/scanpy-scripts/build.sh
  recipes/scanpy-scripts/meta.yaml
  recipes/scanpy-scripts/post-link.sh
Labels: please review & merge

#16208 r-nanopore package for analysis of nanopore data
  recipes/r-nanopore/build.sh
  recipes/r-nanopore/meta.yaml
Labels: please review & merge

#16218 Update adam to 0.28.0
  recipes/adam/meta.yaml
Labels: please review & merge

#16220 Update dsh-bio to 1.2
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#16228 Update ngless to 1.0.1
  recipes/ngless/build.sh
  recipes/ngless/meta.yaml
Labels: please review & merge

#16234 TaxonKit-0.5.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#16219 Update cannoli to 0.6.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#16248 Update Centreseq
  recipes/centreseq/meta.yaml
Labels: please review & merge

#16242 Adding surpyvor
  recipes/surpyvor/meta.yaml
Labels: please review & merge

#16204 Fixed merge MetaPhlAn tables
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#16213 Update bcalm build instruction to solve bug GATB/bcalm#44
  recipes/bcalm/build.sh
  recipes/bcalm/meta.yaml
Labels: please review & merge

#16269 cgat-core
  recipes/cgat-core/meta.yaml
Labels: please review & merge

#16243 bump build number, fix python version
  recipes/spades/3.9.1/meta.yaml
Labels: please review & merge

#16107 update riboseed,remove most pins
  recipes/riboseed/build.sh
  recipes/riboseed/meta.yaml
Labels: please review & merge

#16272 Increment build number to rebuild genomedata recipe
  recipes/genomedata/meta.yaml
Labels: please review & merge

#16275 Update unitig-caller recipe to v1.0.0
  recipes/unitig-caller/meta.yaml
Labels: please review & merge

#16282 new build to pass trough review
  recipes/das_tool/meta.yaml
Labels: please review & merge

#16302 updating ganon to version 0.1.3
  recipes/ganon/build.sh
  recipes/ganon/meta.yaml
Labels: please review & merge

#16321 Snakemake 5.5.3, merge snakemake and snakemake-minimal into a single …
  recipes/snakemake-minimal/meta.yaml
  recipes/snakemake/meta.yaml
Labels: please review & merge

#16325 sentieon: update to 201808.07
  recipes/sentieon/meta.yaml
Labels: please review & merge

#16328 Update BASIC to v1.5.0
  recipes/basic/build.sh
  recipes/basic/meta.yaml
Labels: please review & merge

#16316 midas-1.2.2
  recipes/midas/1.2.2/build.sh
  recipes/midas/1.2.2/meta.yaml
  recipes/midas/1.2.2/midas.patch
Labels: please review & merge

#16326 R tftargets
  recipes/r-tftargets/build.sh
  recipes/r-tftargets/meta.yaml
Labels: please review & merge

#16349 Update BASIC to v1.5.1
  recipes/basic/build.sh
  recipes/basic/meta.yaml
Labels: please review & merge

#16338 fix update ganon v0.1.3
  recipes/ganon/build.sh
  recipes/ganon/meta.yaml
Labels: please review & merge

#16360 Update pairtools to 0.3.0
  recipes/pairtools/meta.yaml
Labels: autobump, new version

#16362 Bumped version to trigger R 3.5.1 build; cleaned up meta.yaml a bit..
  build-fail-blacklist
  recipes/r-annotables/meta.yaml
Labels: please review & merge

#16409 Bumping scelvis to 0.4.0.
  recipes/scelvis/meta.yaml
Labels: please review & merge

#16399 VEP: bump subversion
  recipes/ensembl-vep/meta.yaml
Labels: new version, please review & merge

#16395 Added DiNAMO recipe
  recipes/dinamo/Makefile.patch
  recipes/dinamo/build.sh
  recipes/dinamo/meta.yaml
Labels: please review & merge

#16396 Added ProSampler recipe
  recipes/prosampler/build.sh
  recipes/prosampler/meta.yaml
Labels: please review & merge

#16207 Bump MEGAHIT to 1.2.6
  build-fail-blacklist
  recipes/megahit/build.sh
  recipes/megahit/meta.yaml
Labels: please review & merge

#16432 tb_variant_filter 0.1.1: Fixes error when VCF has multiple ANN records
  recipes/tb_variant_filter/meta.yaml
Labels: please review & merge

#16436 Update welcome_new_contributor.md
  .github/welcome_new_contributor.md
Labels: please review & merge

#16443 added bftools recipe
  recipes/bftools/build.sh
  recipes/bftools/meta.yaml
Labels: please review & merge

#16431 StrainPhlAn now is Python3 compatible
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#16078 genform: initial commit
  recipes/genform/build.sh
  recipes/genform/meta.yaml
Labels: please review & merge

#16344 Add ELECTOR: EvaLuator of Error Correction Tools for lOng Reads
  recipes/elector/build.sh
  recipes/elector/meta.yaml
Labels: please review & merge

#16479 switch to newer version
  recipes/sepp/meta.yaml
Labels: new version, please review & merge

#16480 fix chiron recipe
  recipes/chiron/meta.yaml
Labels: please review & merge

#16493 Adding AltamISA v0.2.0.
  recipes/altamisa/meta.yaml
Labels: please review & merge

#16502 Updated MetaPhlAn2 version
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#16503 init add ezclermont
  recipes/ezclermont/build.sh
  recipes/ezclermont/meta.yaml
Labels: please review & merge

#16526 Update metaphlan2 to 2.9.18
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#16527 update rgi5.0.0 recipe
  recipes/rgi/meta.yaml
Labels: please review & merge

#16565 fasta-splitter update to version 0.2.6
  recipes/fasta-splitter/build.sh
  recipes/fasta-splitter/meta.yaml
Labels: please review & merge

#16572 Update dbgraph version and build
  recipes/dbgraph/meta.yaml
Labels: please review & merge

#16524 please review & merge: add moabs
  recipes/moabs/build.sh
  recipes/moabs/meta.yaml
  recipes/moabs/post-link.sh
Labels: please review & merge

#16566 Update RnaChipIntegrator to version 1.2.0
  recipes/rnachipintegrator/meta.yaml
Labels: please review & merge

#16602 MetaPhlAn2 updated to 2.9.19
  recipes/metaphlan2/2.9.0/meta.yaml
Labels: please review & merge

#16595 Update FastSpar to 0.0.10
  build-fail-blacklist
  recipes/fastspar/meta.yaml
Labels: new version

#16621 Bumping version of jannovar-cli to v0.33.
  recipes/jannovar-cli/meta.yaml
Labels: please review & merge

#16619 Bump up DeepBGC version to 0.1.8
  recipes/deepbgc/meta.yaml
Labels: please review & merge

#16611 fix rgi recipe
  recipes/rgi/meta.yaml
Labels: please review & merge

#16629 UCSC CellBrowser pip skeleton and bump to 0.5.43
  recipes/ucsc-cell-browser/meta.yaml
Labels: please review & merge

#16636 Adding MACE
  recipes/mace/LICENSE
  recipes/mace/meta.yaml
  recipes/mace/source.patch
Labels: please review & merge

#16613 Atlas 2.1.4
  recipes/metagenome-atlas/build.sh
  recipes/metagenome-atlas/meta.yaml
Labels: please review & merge

#16641 Upstream uses tags now, switching over.
  recipes/spliceai/meta.yaml
Labels: please review & merge

#16626 seqkit 0.10.2
  recipes/seqkit/meta.yaml
Labels: please review & merge

#16645 Update vcfanno to 0.3.2
  recipes/vcfanno/meta.yaml
Labels: please review & merge

#16462 Upgrade r-minems2 to 0.9.2.
  recipes/r-minems2/meta.yaml
Labels: please review & merge

#16648 Mace
  recipes/mace/meta.yaml
Labels: update build number

#16654 modeltest-ng
  recipes/modeltest-ng/build.sh
  recipes/modeltest-ng/meta.yaml
Labels: please review & merge
