Repository bioconda/bioconda-recipes, pull requests merged in 2019-04, with the labels that each got.

#12809 Update libdeflate to 1.1
  recipes/libdeflate/0001-Build-dylib-on-MacOS.patch
  recipes/libdeflate/build.sh
  recipes/libdeflate/meta.yaml
Labels: autobump

#14452 Update BioBlend run requirements
  recipes/bioblend/meta.yaml
Labels: bug

#14539 Rebuild abyss
  recipes/abyss/meta.yaml
Labels: autobump, update pinning

#14543 Rebuild ucsc-liftover (openssl)
  recipes/ucsc-liftover/meta.yaml
Labels: autobump, update pinning

#14545 Update bioconductor-biocparallel to 1.16.6
  recipes/bioconductor-biocparallel/meta.yaml
Labels: autobump, new version

#14544 Update bioconductor-qvalue to 2.14.1
  recipes/bioconductor-qvalue/meta.yaml
Labels: autobump, new version

#14546 Update perl-db-file to 1.852
  recipes/perl-db-file/meta.yaml
Labels: autobump, new version

#14547 Update bioconductor-massspecwavelet to 1.48.1
  recipes/bioconductor-massspecwavelet/meta.yaml
Labels: autobump, new version

#14556 Rebuild perl-heap-simple-xs (compiler)
  recipes/perl-heap-simple-xs/meta.yaml
Labels: autobump, update pinning

#14562 Update perl-class-inspector to 1.34
  recipes/perl-class-inspector/meta.yaml
Labels: autobump, new version

#14569 Update arvados-python-client to 1.3.1.20190402172810
  recipes/arvados-python-client/meta.yaml
Labels: autobump, new version

#14565 Rebuild vcftools (compiler)
  recipes/vcftools/meta.yaml
Labels: autobump, update pinning

#14566 Rebuild snp-sites (compiler)
  recipes/snp-sites/meta.yaml
Labels: autobump, update pinning

#14570 Rebuild rust-overlaps (compiler)
  recipes/rust-overlaps/meta.yaml
Labels: autobump, update pinning

#14571 Update bioconductor-flowpeaks to 1.28.1
  recipes/bioconductor-flowpeaks/meta.yaml
Labels: autobump, new version

#14572 Update r-shazam to 0.1.11
  recipes/r-shazam/meta.yaml
Labels: autobump, new version

#14573 Update r-rnexml to 2.3.0
  recipes/r-rnexml/meta.yaml
Labels: autobump, new version

#14584 Rebuild perl-unicode-map
  recipes/perl-unicode-map/meta.yaml
Labels: autobump, update pinning

#14557 Rebuild mummer4
  recipes/mummer4/meta.yaml
Labels: autobump, update pinning

#14577 Rebuild perl-math-cdf (compiler)
  recipes/perl-math-cdf/meta.yaml
Labels: autobump, update pinning

#14585 Rebuild pysvmlight (compiler)
  recipes/pysvmlight/meta.yaml
Labels: autobump, update pinning

#14583 Rebuild diamond (boost)
  recipes/diamond/meta.yaml
Labels: autobump, update pinning

#14589 Rebuild npyscreen (ncurses)
  recipes/npyscreen/meta.yaml
Labels: autobump, update pinning

#14591 Update vsearch to 2.13.0
  recipes/vsearch/meta.yaml
Labels: autobump, new version

#14592 Rebuild perl-sub-uplevel (compiler)
  recipes/perl-sub-uplevel/meta.yaml
Labels: autobump, update pinning

#14590 Update idba_subasm to 1.1.3a2
  recipes/idba_subasm/meta.yaml
Labels: autobump, new version

#14593 Rebuild biolite-tools (compiler)
  recipes/biolite-tools/meta.yaml
Labels: autobump, update pinning

#14595 Update kallisto to 0.45.1
  recipes/kallisto/meta.yaml
Labels: autobump, new version

#14594 Rebuild perl-termreadkey (compiler)
  recipes/perl-termreadkey/meta.yaml
Labels: autobump, update pinning

#14560 Update bbmap to 38.44
  recipes/bbmap/0002-enable-jni-path.patch
  recipes/bbmap/meta.yaml
Labels: autobump, new version

#14564 Update krona to 2.7.1
  recipes/krona/meta.yaml
Labels: autobump, new version

#14541 Rebuild genometools-genometools
  recipes/genometools-genometools/build.sh
  recipes/genometools-genometools/meta.yaml
Labels: autobump, update pinning

#14600 Update phyml to 3.3.20190321
  recipes/phyml/meta.yaml
Labels: autobump, new version

#14548 Rebuild samblaster
  recipes/samblaster/build.sh
  recipes/samblaster/meta.yaml
Labels: autobump, update pinning

#14602 Update pyteomics to 4.1
  recipes/pyteomics/meta.yaml
Labels: autobump, new version

#14605 Update perl-extutils-manifest to 1.72
  recipes/perl-extutils-manifest/meta.yaml
Labels: autobump, new version

#14606 Update perl-compress-raw-zlib to 2.086
  recipes/perl-compress-raw-zlib/meta.yaml
Labels: autobump, new version

#14607 Update perl-json-pp to 4.02
  recipes/perl-json-pp/meta.yaml
Labels: autobump, new version

#14608 Update perl-compress-raw-bzip2 to 2.086
  recipes/perl-compress-raw-bzip2/meta.yaml
Labels: autobump, new version

#14579 Rebuild starcode
  recipes/starcode/build.sh
  recipes/starcode/meta.yaml
Labels: autobump, update pinning

#14576 Rebuild skesa
  recipes/skesa/build.sh
  recipes/skesa/meta.yaml
Labels: autobump, update pinning

#14568 Rebuild scoop (compiler)
  recipes/scoop/meta.yaml
Labels: autobump, update pinning

#14609 Update perl-file-path to 2.16
  recipes/perl-file-path/meta.yaml
Labels: autobump, new version

#14563 Rebuild bgreat (compiler)
  recipes/bgreat2/build.sh
  recipes/bgreat2/meta.yaml
Labels: autobump, update pinning

#14634 Update r-msm to 1.6.7
  recipes/r-msm/meta.yaml
Labels: autobump, new version

#14629 Update bioconductor-ebseq to 1.22.1
  recipes/bioconductor-ebseq/meta.yaml
Labels: autobump, new version

#14598 Rebuild raxml
  recipes/raxml/build.sh
  recipes/raxml/meta.yaml
Labels: autobump, update pinning

#14633 Update pybigwig to 0.3.14
  recipes/pybigwig/meta.yaml
Labels: autobump, new version

#14635 Update nanomath to 0.23.1
  recipes/nanomath/meta.yaml
Labels: autobump, new version

#14647 Update bioconductor-treeio to 1.6.2
  recipes/bioconductor-treeio/meta.yaml
Labels: autobump, new version

#14648 Update bioconductor-samspectral to 1.36.1
  recipes/bioconductor-samspectral/meta.yaml
Labels: autobump, new version

#14644 Update bioconductor-rsubread to 1.32.4
  recipes/bioconductor-rsubread/meta.yaml
Labels: autobump, new version

#14646 Rebuild racon (compiler)
  recipes/racon/meta.yaml
Labels: autobump, update pinning

#14643 Update kma to 1.2.1
  recipes/kma/meta.yaml
Labels: autobump, new version

#14638 Update bioconductor-mixomics to 6.6.2
  recipes/bioconductor-mixomics/meta.yaml
Labels: autobump, new version

#14641 Rebuild perl-perl-unsafe-signals (compiler)
  recipes/perl-perl-unsafe-signals/meta.yaml
Labels: autobump, update pinning

#14639 Update bioconductor-sseq to 1.20.1
  recipes/bioconductor-sseq/meta.yaml
Labels: autobump, new version

#14640 Update picard to 2.19.2
  recipes/picard/meta.yaml
Labels: autobump, new version

#14636 Update bioconductor-tximport to 1.10.1
  recipes/bioconductor-tximport/meta.yaml
Labels: autobump, new version

#14582 Rebuild libbigwig (compiler)
  recipes/libbigwig/build.sh
  recipes/libbigwig/meta.yaml
Labels: autobump, update pinning

#14655 Rebuild fastq-scan (compiler)
  recipes/fastq-scan/meta.yaml
Labels: autobump, update pinning

#14660 Update inheritance to 0.1.5
  recipes/inheritance/meta.yaml
Labels: autobump, new version

#14664 Update validators to 0.12.5
  recipes/validators/meta.yaml
Labels: autobump, new version

#14667 Update xopen to 0.5.1
  recipes/xopen/meta.yaml
Labels: autobump, new version

#14662 Rebuild alignlib-lite (python)
  recipes/alignlib-lite/meta.yaml
Labels: autobump, update pinning

#14666 Update bioconductor-rpx to 1.18.1
  recipes/bioconductor-rpx/meta.yaml
Labels: autobump, new version

#14674 Update pronto to 0.12.2
  recipes/pronto/meta.yaml
Labels: autobump, new version

#14671 Update sevenbridges-python to 0.20.0
  recipes/sevenbridges-python/meta.yaml
Labels: autobump, new version

#14679 Update bioconductor-genie3 to 1.4.3
  recipes/bioconductor-genie3/meta.yaml
Labels: autobump

#14680 Update nmrglue to 0.7
  recipes/nmrglue/meta.yaml
Labels: autobump

#14698 Rebuild perl-convert-binary-c (compiler)
  recipes/perl-convert-binary-c/meta.yaml
Labels: autobump, update pinning

#14692 Update bbmap to 38.45
  recipes/bbmap/meta.yaml
Labels: autobump, new version

#14697 Update scrappie to 1.4.2
  recipes/scrappie/meta.yaml
Labels: autobump, new version

#14700 Update ont-fast5-api to 1.3.0
  recipes/ont-fast5-api/meta.yaml
Labels: autobump, new version

#14693 Update chainmap to 1.0.3
  recipes/chainmap/meta.yaml
Labels: autobump, new version

#14728 Rebuild fasttree (compiler)
  recipes/fasttree/build.sh
  recipes/fasttree/meta.yaml
Labels: autobump, update pinning

#14726 Update treetime to 0.5.5
  recipes/treetime/meta.yaml
Labels: autobump

#14687 Update slicedimage to 3.0.0
  recipes/slicedimage/meta.yaml
Labels: autobump, new version

#14732 Update rnablueprint to 1.2.3
  recipes/rnablueprint/meta.yaml
Labels: autobump, new version

#14733 Update fast5-research to 1.2.15
  recipes/fast5-research/meta.yaml
Labels: autobump, new version

#14731 Rebuild pullseq (compiler)
  recipes/pullseq/meta.yaml
Labels: autobump, update pinning

#14699 Rebuild bedops
  recipes/bedops/build.sh
  recipes/bedops/meta.yaml
Labels: autobump, update pinning

#14691 Rebuild bioawk (compiler)
  recipes/bioawk/build.sh
  recipes/bioawk/meta.yaml
Labels: autobump, update pinning

#14694 Update r-fateid to 0.1.7
  recipes/r-fateid/build.sh
  recipes/r-fateid/meta.yaml
Labels: autobump, new version

#14690 Rebuild dinopy (python)
  recipes/dinopy/meta.yaml
Labels: autobump, update pinning

#14695 Rebuild fastani
  recipes/fastani/build.sh
  recipes/fastani/meta.yaml
Labels: autobump, update pinning

#14689 Update r-hardyweinberg to 1.6.2
  recipes/r-hardyweinberg/meta.yaml
Labels: autobump, new version

#14684 Update minced to 0.4.0
  recipes/minced/meta.yaml
Labels: autobump, new version

#14686 Update r-geiger to 2.0.6.1
  recipes/r-geiger/meta.yaml
Labels: autobump, new version

#14688 Update kma to 1.2.3
  recipes/kma/meta.yaml
Labels: autobump, new version

#14661 Update clustergrammer to 1.13.6
  recipes/clustergrammer/meta.yaml
Labels: autobump, new version

#14670 Update schema to 0.7.0
  recipes/schema/meta.yaml
Labels: autobump, new version

#14762 Update vsearch to 2.13.1
  recipes/vsearch/meta.yaml
Labels: autobump, new version

#14730 Update sina to 1.6.0
  recipes/sina/build.sh
  recipes/sina/meta.yaml
Labels: autobump, new version

#14761 Update sharedmem to 0.3.6
  recipes/sharedmem/meta.yaml
Labels: autobump, new version

#14764 Rebuild weeder
  recipes/weeder/meta.yaml
Labels: autobump, update pinning

#14771 Update bioconductor-ebseqhmm to 1.16.1
  recipes/bioconductor-ebseqhmm/meta.yaml
Labels: autobump, new version

#14772 Rebuild perl-digest-sha1 (compiler)
  recipes/perl-digest-sha1/meta.yaml
Labels: autobump, update pinning

#14775 Update perl-test-needs to 0.002006
  recipes/perl-test-needs/meta.yaml
Labels: autobump, new version

#14774 Update perl-canary-stability to 2013
  recipes/perl-canary-stability/meta.yaml
Labels: autobump, new version

#14779 Update perl-image-exiftool to 11.30
  recipes/perl-image-exiftool/meta.yaml
Labels: autobump, new version

#14777 Rebuild perl-ipc-sharelite (compiler)
  recipes/perl-ipc-sharelite/meta.yaml
Labels: autobump, update pinning

#14805 Rebuild perl-padwalker
  recipes/perl-padwalker/meta.yaml
Labels: autobump, update pinning

#14780 Rebuild perl-json-parse
  recipes/perl-json-parse/meta.yaml
Labels: autobump, update pinning

#14781 Update pyimzml to 1.2.6
  recipes/pyimzml/meta.yaml
Labels: autobump, new version

#14782 Update shapeshifter-cli to 1.0.0
  recipes/shapeshifter-cli/meta.yaml
Labels: autobump, new version

#14783 Update bioconductor-synlet to 1.12.1
  recipes/bioconductor-synlet/meta.yaml
Labels: autobump, new version

#14784 Update bioconductor-bacon to 1.10.1
  recipes/bioconductor-bacon/meta.yaml
Labels: autobump, new version

#14786 Update bioconductor-dcgsa to 1.10.1
  recipes/bioconductor-dcgsa/meta.yaml
Labels: autobump, new version

#14787 Update pymummer to 0.11.0
  recipes/pymummer/meta.yaml
Labels: autobump, new version

#14785 Update bioconductor-oscope to 1.12.1
  recipes/bioconductor-oscope/meta.yaml
Labels: autobump, new version

#14789 Update bioconductor-ggtree to 1.14.6
  recipes/bioconductor-ggtree/meta.yaml
Labels: autobump, new version

#14788 Update bioconductor-mzid to 1.20.1
  recipes/bioconductor-mzid/meta.yaml
Labels: autobump, new version

#14790 Update gseapy to 0.9.13
  recipes/gseapy/meta.yaml
Labels: autobump, new version

#14792 Update ucsc-cell-browser to 0.4.56
  recipes/ucsc-cell-browser/meta.yaml
Labels: autobump, new version

#14793 Rebuild barriers (compiler)
  recipes/barriers/meta.yaml
Labels: autobump, update pinning

#14795 Update intarna to 2.4.1
  recipes/intarna/meta.yaml
Labels: autobump, new version

#14796 Update r-mess to 0.5.5
  recipes/r-mess/meta.yaml
Labels: autobump, new version

#14797 Update bioconductor-cqn to 1.28.1
  recipes/bioconductor-cqn/meta.yaml
Labels: autobump, new version

#14817 Update r-rgbif to 1.2.0
  recipes/r-rgbif/meta.yaml
Labels: autobump, new version

#14816 Update bioconductor-linnorm to 2.6.1
  recipes/bioconductor-linnorm/meta.yaml
Labels: autobump, new version

#14815 Update womtool to 40
  recipes/womtool/meta.yaml
Labels: autobump, new version

#14814 Update bioconductor-countclust to 1.10.1
  recipes/bioconductor-countclust/meta.yaml
Labels: autobump, new version

#14812 Update mhcflurry to 1.2.4
  recipes/mhcflurry/meta.yaml
Labels: autobump, new version

#14811 Update bioconductor-edger to 3.24.3
  recipes/bioconductor-edger/meta.yaml
Labels: autobump, new version

#14810 Update bioconductor-ctsge to 1.8.1
  recipes/bioconductor-ctsge/meta.yaml
Labels: autobump, new version

#14806 Update r-treesim to 2.4
  recipes/r-treesim/meta.yaml
Labels: autobump, new version

#14807 Update r-phylobase to 0.8.6
  recipes/r-phylobase/meta.yaml
Labels: autobump, new version

#14801 Update bioconductor-sights to 1.8.1
  recipes/bioconductor-sights/meta.yaml
Labels: autobump, new version

#14800 Update bioconductor-opweight to 1.4.1
  recipes/bioconductor-opweight/meta.yaml
Labels: autobump, new version

#14799 Update r-pma to 1.1
  recipes/r-pma/meta.yaml
Labels: autobump, new version

#14823 Update bioconductor-rhtslib to 1.14.1
  recipes/bioconductor-rhtslib/meta.yaml
Labels: autobump, new version

#14824 Update pyensembl to 1.7.4
  recipes/pyensembl/meta.yaml
Labels: autobump, new version

#14822 Update bioconductor-stattarget to 1.12.1
  recipes/bioconductor-stattarget/meta.yaml
Labels: autobump, new version

#14821 Update galaxy-parsec to 1.12.0
  recipes/galaxy-parsec/meta.yaml
Labels: autobump, new version

#14820 Update bioconductor-compass to 1.20.1
  recipes/bioconductor-compass/meta.yaml
Labels: autobump, new version

#14826 Update bioconductor-matter to 1.8.3
  recipes/bioconductor-matter/meta.yaml
Labels: autobump, new version

#14828 Update bioconductor-ihw to 1.10.1
  recipes/bioconductor-ihw/meta.yaml
Labels: autobump, new version

#14825 Rebuild unifrac (python)
  recipes/unifrac/meta.yaml
Labels: autobump, update pinning

#14827 Update nanoplotter to 1.6.1
  recipes/nanoplotter/meta.yaml
Labels: autobump, new version

#14830 Update perl-data-uuid to 1.224
  recipes/perl-data-uuid/meta.yaml
Labels: autobump, new version

#14832 Update cat to 4.6
  recipes/cat/meta.yaml
Labels: autobump, new version

#14829 Update cgatcore to 0.5.13
  recipes/cgat-core/meta.yaml
Labels: autobump, new version

#14833 Update bioconductor-famagg to 1.10.4
  recipes/bioconductor-famagg/meta.yaml
Labels: autobump, new version

#14831 Update bioconda-utils to 0.15.11
  recipes/bioconda-utils/meta.yaml
Labels: autobump, new version

#14840 Rebuild kwip (compiler)
  recipes/kwip/meta.yaml
Labels: autobump, update pinning

#14845 Rebuild perl-acme-damn (compiler)
  recipes/perl-acme-damn/meta.yaml
Labels: autobump, update pinning

#14843 Update perl-inline to 0.82
  recipes/perl-inline/meta.yaml
Labels: autobump, new version

#14837 Rebuild gubbins (python)
  recipes/gubbins/meta.yaml
Labels: autobump, update pinning

#14842 Rebuild perl-devel-assert (compiler)
  recipes/perl-devel-assert/meta.yaml
Labels: autobump, update pinning
