Repository bioconda/bioconda-recipes, pull requests merged in 2019-02, with the labels that each got.

#13582 updating cromwell to 0.37
  recipes/cromwell/meta.yaml
Labels: enhancement

#13566 update mykrobe to v0.6.1
  recipes/mykrobe/build.sh
  recipes/mykrobe/meta.yaml
  recipes/mykrobe/post-link.sh
Labels: please review & merge

#13350 Update kipoi_veff to 0.2.2
  recipes/kipoi_veff/meta.yaml
Labels: autobump

#13547 Update sina to 1.5.0
  recipes/sina/build.sh
  recipes/sina/meta.yaml
Labels: autobump

#13249 Update treetime to 0.5.3
  recipes/treetime/meta.yaml
Labels: autobump

#13258 Update cgpbigwig to 1.0.3
  recipes/cgpbigwig/meta.yaml
Labels: autobump

#13686 Rebuild exonerate
  recipes/exonerate/build.sh
  recipes/exonerate/meta.yaml
Labels: help wanted
