Repository bioconda/bioconda-recipes, pull requests merged in 2019-11, with the labels that each got.

#18411 Add recipe for methylpy
  recipes/methylpy/build.sh
  recipes/methylpy/meta.yaml
Labels: please review & merge

#18426 update sourmash meta.yaml
  recipes/sourmash/meta.yaml
Labels: please review & merge

#18424 Update gffread to 0.11.6
  recipes/gffread/meta.yaml
Labels: please review & merge

#18397 Atlas
  recipes/metagenome-atlas/meta.yaml
Labels: please review & merge

#18401 Enable mango widgets in biocontainers
  recipes/mango/activate.sh
  recipes/mango/build.sh
  recipes/mango/deactivate.sh
  recipes/mango/meta.yaml
Labels: please review & merge

#18412 Update DFAST to 1.2.4
  recipes/dfast/build.sh
  recipes/dfast/meta.yaml
  recipes/dfast/post-link.sh
Labels: please review & merge

#18460 Bumping WisecondorX version.
  recipes/wisecondorx/meta.yaml
Labels: please review & merge

#18454 Increase maximum sample size available
  recipes/fsm-lite/0001-Increase-DBITS.patch
  recipes/fsm-lite/0002-CXX-in-Makefile.patch
  recipes/fsm-lite/meta.yaml
Labels: please review & merge

#18463 update keras/tf dependency in medaka
  recipes/medaka/meta.yaml
Labels: please review & merge

#18471 mtsv update recipe requirements
  recipes/mtsv/build.sh
  recipes/mtsv/meta.yaml
Labels: please review & merge

#18487 Update MicroHapDB to 0.4.3
  recipes/microhapdb/meta.yaml
Labels: please review & merge

#18509 adding legacy 14.2-1 update
  recipes/salmon/0.14.2-1/build.sh
  recipes/salmon/0.14.2-1/meta.yaml
Labels: please review & merge

#18505 Ac trna
  recipes/trnanalysis/meta.yaml
Labels: please review & merge

#18488 Update MicroHapulator to 0.4.1
  recipes/microhapulator/meta.yaml
  recipes/microhapulator/run_test.sh
Labels: please review & merge

#18527 [Picard] respect ${_JAVA_OPTIONS} and set default memory to 2GB
  recipes/picard/meta.yaml
  recipes/picard/picard.sh
Labels: please review & merge

#18538 Fix recipe for vcf-kit
  build-fail-blacklist
  recipes/vcfkit/build.sh
  recipes/vcfkit/meta.yaml
  recipes/vcfkit/numpy.patch
  recipes/vcfkit/setup.patch
Labels: please review & merge

#18547 Gtdbtk 0.3.2 updates
  recipes/gtdbtk/meta.yaml
Labels: please review & merge

#18566 Add tagged release for qgrs-cpp
  recipes/qgrs-cpp/meta.yaml
Labels: please review & merge

#18567 New recipe for GoGetData (GGD)
  recipes/ggd/meta.yaml
  recipes/ggd/post-link.sh
Labels: please review & merge

#18573 PASA v2.4.1
  recipes/pasa/build.sh
  recipes/pasa/meta.yaml
Labels: please review & merge

#18574 minor bug fix
  recipes/ggd/meta.yaml
Labels: please review & merge

#18581 Add transrate
  recipes/transrate/build.sh
  recipes/transrate/meta.yaml
  recipes/transrate/patch
Labels: please review & merge

#18612 Update bad sha256sum for ggd bioconda recipe
  recipes/ggd/meta.yaml
Labels: please review & merge

#18637 Metagene annotator bump
  recipes/metagene_annotator/meta.yaml
Labels: please review & merge

#18636 Samplot
  recipes/samplot/build.sh
  recipes/samplot/meta.yaml
Labels: please review & merge

#18633 Add recipe for r-fastbaps
  recipes/r-fastbaps/meta.yaml
Labels: please review & merge

#18643 varlociraptor 1.3.0
  recipes/varlociraptor/meta.yaml
Labels: please review & merge

#18653 Revert numpy version requirement
  recipes/rnasamba/meta.yaml
Labels: please review & merge

#18670 Bump wg-blimp to v0.9.5
  recipes/wg-blimp/meta.yaml
Labels: please review & merge

#18601 Eggnog-mapper 2.0.1
  recipes/eggnog-mapper/meta.yaml
Labels: please review & merge

#18622 validators: remove recipe (moving to conda-forge)
  recipes/validators/meta.yaml
Labels: Move to Conda-Forge

#18690 Add recipe for rasusa
  recipes/rasusa/build.sh
  recipes/rasusa/meta.yaml
Labels: please review & merge

#18702 new file: gsalign/build.sh
  recipes/dart/build.sh
  recipes/dart/meta.yaml
Labels: please review & merge

#18709 Fixes dtype issue of h5py 2.10
  recipes/sccaf/meta.yaml
Labels: please review & merge

#18705 release genomepy 0.7.0
  recipes/genomepy/meta.yaml
Labels: new version, please review & merge

#18697 wg-blimp: Replace snakemake with snakemake-minimal
  recipes/wg-blimp/meta.yaml
Labels: please review & merge

#18693 Update genmap to 1.1.0
  recipes/genmap/meta.yaml
Labels: new version, please review & merge

#18691 Trinity -- export TRINITY_HOME ENV variable
  recipes/trinity/build.sh
  recipes/trinity/meta.yaml
Labels: please review & merge

#18704 add recipe for ldsc
  recipes/ldsc/build.sh
  recipes/ldsc/meta.yaml
  recipes/ldsc/setup.py
Labels: please review & merge

#18722 new file: build.sh
  recipes/gsalign/build.sh
  recipes/gsalign/meta.yaml
Labels: please review & merge

#18703 Add hmmer 3.0
  recipes/hmmer/3.0/build.sh
  recipes/hmmer/3.0/meta.yaml
Labels: please review & merge

#18731 add samtools to control-freec
  recipes/control-freec/meta.yaml
Labels: please review & merge

#18724 Fix TIDDIT
  recipes/tiddit/build.sh
  recipes/tiddit/meta.yaml
Labels: please review & merge

#18388 play with bioconda-bot via github actions
  .github/workflows/CommentResponder.yml
Labels: WIP, enhancement

#18723 Fix bcftools license when compiled with GSL
  recipes/bcftools/meta.yaml
Labels: please review & merge

#18762 Update meta.yaml
  recipes/bioconductor-qvalue/meta.yaml
Labels: please review & merge

#18769 Watchdog - update for support of GUI
  recipes/watchdog-wms/meta.yaml
  recipes/watchdog-wms/run_test.sh
Labels: please review & merge

#18771 Add r-vision recipe
  recipes/r-vision/build.sh
  recipes/r-vision/meta.yaml
Labels: please review & merge

#18791 Funannotate v1.7.1
  recipes/funannotate/meta.yaml
Labels: please review & merge

#18783 Update genomepy
  recipes/genomepy/meta.yaml
Labels: please review & merge

#18800 add perl-bio-das recipe
  recipes/perl-bio-das/build.sh
  recipes/perl-bio-das/meta.yaml
Labels: please review & merge

#18796 loosen matplotlib restriction in multiqc
  recipes/multiqc/meta.yaml
  recipes/multiqc/patch
Labels: please review & merge

#18812 added perl-email-simple
  recipes/perl-email-simple/build.sh
  recipes/perl-email-simple/meta.yaml
Labels: please review & merge

#18814 Funannotate update build for some missing dependencies
  recipes/funannotate/meta.yaml
  recipes/funannotate/post-link.sh
Labels: please review & merge

#18854 Update GraphAligner to version 1.0.10
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#18853 Add recipe for bindash
  recipes/bindash/build.sh
  recipes/bindash/meta.yaml
Labels: please review & merge

#18875 update pygtftk to 1.1
  recipes/pygtftk/meta.yaml
Labels: please review & merge

#18815 MetaPhlAn2 updated to version 2.9.5
  recipes/metaphlan2/meta.yaml
Labels: please review & merge

#18885 Add svist4get
  recipes/svist4get/meta.yaml
Labels: please review & merge

#18908 patch to remove incorrect statistics and argparse requirements
  recipes/svist4get/meta.yaml
  recipes/svist4get/patch
Labels: please review & merge

#18936 Added MetabAnalystR as r-metaboanalyst
  recipes/r-metaboanalyst/build.sh
  recipes/r-metaboanalyst/meta.yaml
Labels: please review & merge

#18942 modified: build.sh (gsalign)
  recipes/gsalign/build.sh
  recipes/gsalign/meta.yaml
Labels: please review & merge

#18922 Phast
  recipes/phast/build.sh
  recipes/phast/meta.yaml
Labels: please review & merge

#18947 update recipe (dart)
  recipes/dart/build.sh
  recipes/dart/meta.yaml
Labels: please review & merge

#18967 Damageprofiler Bump to 0.4.8
  recipes/damageprofiler/damageprofiler.py
  recipes/damageprofiler/meta.yaml
Labels: please review & merge

#18982 Fix kobas for Biopython >=1.73
  recipes/kobas/Replace-deprecated-Seq.tostring-method.patch
  recipes/kobas/meta.yaml
  recipes/kobas/package.patch
Labels: please review & merge

#18692 Dashing
  recipes/dashing/build.sh
  recipes/dashing/meta.yaml
Labels: MacOS related, help wanted

#18995 Damageprofiler
  recipes/damageprofiler/meta.yaml
Labels: please review & merge

#19003 Adding digestiflow-demux v0.5.0
  recipes/digestiflow-demux/meta.yaml
Labels: please review & merge

#18971 Fix TIDDIT
  recipes/tiddit/build.sh
  recipes/tiddit/meta.yaml
Labels: please review & merge

#19006 Damageprofiler bump to 0.4.9
  recipes/damageprofiler/damageprofiler.py
  recipes/damageprofiler/meta.yaml
Labels: please review & merge

#18992 Blacklist update
  build-fail-blacklist
  recipes/antismash/build.sh
  recipes/antismash/meta.yaml
  recipes/antismash/post-link.sh
  recipes/dx-cwl/meta.yaml
  recipes/fastqmetrics/meta.yaml
  recipes/maxentscan/meta.yaml
  recipes/theta2/build.sh
  recipes/theta2/meta.yaml
Labels: please review & merge

#19002 Build ema on macOS
  recipes/ema/Makefile.patch
  recipes/ema/build.sh
  recipes/ema/meta.yaml
Labels: please review & merge
