Repository bioconda/bioconda-recipes, pull requests merged in 2020-11, with the labels that each got.

#25122 Update taxonkit to v0.6.2
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#25108 NGLess: remove python dependency
  recipes/ngless/meta.yaml
Labels: please review & merge

#25119 update xmatchview to 1.2.5
  recipes/xmatchview/build.sh
  recipes/xmatchview/meta.yaml
Labels: please review & merge

#25056 Macrel add atomicwrites
  recipes/macrel/meta.yaml
Labels: please review & merge

#25139 Fix python version of ganon 0.3.3
  recipes/ganon/meta.yaml
Labels: please review & merge

#25128 added mirge3
  recipes/mirge3/LICENSE
  recipes/mirge3/meta.yaml
Labels: please review & merge

#7138 add GATK jar file
  recipes/gatk/3.6/build.sh
  recipes/gatk/3.6/meta.yaml
  recipes/gatk/build.sh
  recipes/gatk/meta.yaml
Labels: please review & merge

#25099 update mykrobe install process
  recipes/mykrobe/build.sh
  recipes/mykrobe/meta.yaml
Labels: please review & merge, update build number

#25143 [elector] R dependency is optional
  recipes/elector/meta.yaml
Labels: please review & merge

#25154 Update my recipe
  recipes/mirge-build/LICENSE
  recipes/mirge-build/meta.yaml
  recipes/mirge3/meta.yaml
Labels: please review & merge

#24305 trigger rebuild of ddocent
  recipes/ddocent/meta.yaml
  recipes/ddocent/version.patch
Labels: please review & merge

#25155 Update adVNTR build
  recipes/advntr/meta.yaml
Labels: please review & merge

#25166 Bump up abnumber to 0.1.4
  recipes/abnumber/meta.yaml
Labels: please review & merge

#25148 Tesorter
  recipes/tesorter/build.sh
  recipes/tesorter/meta.yaml
Labels: please review & merge

#25140 add test for bowtie2 in unicycler tests
  recipes/bowtie2/meta.yaml
  recipes/unicycler/meta.yaml
Labels: please review & merge

#25158 Add Regenie
  recipes/regenie/build.sh
  recipes/regenie/conda_build_config.yaml
  recipes/regenie/meta.yaml
  recipes/regenie/patches/0001-use-shared-cxxopts.patch
  recipes/regenie/patches/0002-import-shared-Eigen3.patch
  recipes/regenie/patches/0003-use-conda-cmakelists.patch
  recipes/regenie/patches/0004-fix-fail-exit-on-help.patch
Labels: please review & merge

#25178 Update hmftools-purple: add r-cairo package dependency
  recipes/hmftools-purple/meta.yaml
Labels: please review & merge

#25179 Fix GATK3 overwriting GATK4 executable
  recipes/gatk/3.6/build.sh
  recipes/gatk/3.6/meta.yaml
  recipes/gatk/build.sh
  recipes/gatk/meta.yaml
Labels: please review & merge

#25183 adding arcasHLA v0.2.0
  recipes/arcas-hla/build.sh
  recipes/arcas-hla/meta.yaml
Labels: please review & merge

#25187 Update HTSlib recipe: patches to fix https/S3/GCS/etc plugins
  recipes/htslib/meta.yaml
  recipes/htslib/plugin-fixes.patch
Labels: please review & merge

#25174 Add recipe for new package: PanACoTA
  recipes/panacota/meta.yaml
Labels: please review & merge

#25188 Add Shasta Genome Assembler
  recipes/shasta/build.sh
  recipes/shasta/meta.yaml
Labels: please review & merge

#25198 Add R-saige
  recipes/r-saige/build.sh
  recipes/r-saige/conda_build_config.yaml
  recipes/r-saige/meta.yaml
  recipes/r-saige/patches/0001-use-shared-libs-in-makevars.patch
  recipes/r-saige/patches/0002-fix-rcpp-returns.patch
  recipes/r-saige/patches/0003-fix-gettimeofday-import.patch
  recipes/r-saige/patches/0004-fix-paths-of-imported-libs-should-never-use-path.patch
  recipes/r-saige/patches/0005-add-minCovariateCount-in-step-1.patch
  recipes/r-saige/patches/0358-use-shared-libs-in-makevars-0.35.8.patch
Labels: please review & merge

#25218 rebuild saige with R=4
  recipes/r-saige/conda_build_config.yaml
  recipes/r-saige/meta.yaml
Labels: please review & merge

#25107 Update sequnwinder to 0.1.4
  recipes/sequnwinder/build.sh
  recipes/sequnwinder/meta.yaml
  recipes/sequnwinder/sequnwinder.sh
Labels: help wanted

#25219 Bump r saige 0.42
  recipes/r-saige/meta.yaml
Labels: please review & merge

#25235 intervene: fix pandas version <1.0
  recipes/intervene/meta.yaml
Labels: please review & merge

#25238 Update OrthoFinder recipe version requirement for DIAMOND
  recipes/orthofinder/meta.yaml
Labels: please review & merge

#25234 Update wg-blimp version to v0.9.7
  recipes/wg-blimp/meta.yaml
Labels: please review & merge

#25240 Add verifyIDintensity
  recipes/verifyidintensity/build.sh
  recipes/verifyidintensity/meta.yaml
Labels: please review & merge

#25245 Update blacklist
  build-fail-blacklist
  recipes/bioconductor-bayesspace/meta.yaml
  recipes/bioconductor-gsgalgor/meta.yaml
  recipes/bioconductor-mogamun/meta.yaml
  recipes/r-biomartr/meta.yaml
Labels: please review & merge

#25246 Bump r-saige 0.42 (R 3.6.1)
  recipes/r-saige/conda_build_config.yaml
  recipes/r-saige/meta.yaml
Labels: please review & merge

#25262 flair: add kerneltree requirement
  recipes/flair/meta.yaml
Labels: please review & merge

#25259 submission-tool-validation recipe add
  recipes/submission-tool-validator/meta.yaml
Labels: please review & merge

#25261 blacklist updates 10.11.20
  build-fail-blacklist
  recipes/bioconductor-adimpute/meta.yaml
  recipes/bioconductor-anvilbilling/meta.yaml
  recipes/bioconductor-chipcomp/meta.yaml
  recipes/bioconductor-famat/meta.yaml
  recipes/bioconductor-genegeneinter/build.sh
  recipes/bioconductor-genegeneinter/meta.yaml
  recipes/bioconductor-getdee2/meta.yaml
Labels: please review & merge

#25275 Fix bioconductor-cardinal 2.8.0 build
  build-fail-blacklist
  recipes/bioconductor-cardinal/buildfixes.patch
  recipes/bioconductor-cardinal/meta.yaml
Labels: please review & merge

#25274 Remove another 5 recipes from the blacklist
  build-fail-blacklist
  recipes/bioconductor-gwena/meta.yaml
  recipes/bioconductor-msimpute/meta.yaml
  recipes/bioconductor-nearbynding/meta.yaml
Labels: please review & merge

#25264 add SAIGE 0.39
  recipes/r-saige/0.39/build.sh
  recipes/r-saige/0.39/conda_build_config.yaml
  recipes/r-saige/0.39/meta.yaml
  recipes/r-saige/0.39/patches/0001-use-shared-libs-in-makevars.patch
  recipes/r-saige/0.39/patches/0002-fix-rcpp-returns.patch
  recipes/r-saige/0.39/patches/0003-fix-gettimeofday-import.patch
  recipes/r-saige/0.39/patches/0004-fix-paths-of-imported-libs-should-never-use-path.patch
  recipes/r-saige/0.39/patches/0005-add-minCovariateCount-in-step-1.patch
  recipes/r-saige/0.39/patches/0358-use-shared-libs-in-makevars-0.35.8.patch
Labels: please review & merge

#25282 Another 5 excluded recipes
  build-fail-blacklist
Labels: please review & merge

#25279 Add dagchainer
  recipes/dagchainer/build.sh
  recipes/dagchainer/meta.yaml
Labels: please review & merge

#25241 Update Panacota
  recipes/panacota/meta.yaml
Labels: please review & merge

#25265 bump r-saige to 0.42.1
  recipes/r-saige/meta.yaml
Labels: please review & merge

#25285 Blacklist updates for bioconductor
  build-fail-blacklist
  recipes/bioconductor-transite/meta.yaml
  recipes/bioconductor-vanillaice/meta.yaml
Labels: please review & merge

#25278 Add KrakMeOpen
  recipes/krakmeopen/meta.yaml
Labels: please review & merge

#25297 Update Jasmine to version 1.0.10
  recipes/jasminesv/meta.yaml
Labels: please review & merge

#25311 Bioconductor 3.12 hackathon: fix bgmix
  build-fail-blacklist
  recipes/bioconductor-bgmix/build.sh
  recipes/bioconductor-bgmix/meta.yaml
Labels: please review & merge

#25308 Bioconductor 3.12 hackathon: fix iclusterplus
  build-fail-blacklist
  recipes/bioconductor-iclusterplus/0001-Detect-compiler-with-gfortran-suffix.patch
  recipes/bioconductor-iclusterplus/build.sh
  recipes/bioconductor-iclusterplus/meta.yaml
Labels: please review & merge

#25310 Bioconductor 3.12 hackathon: fix bgx
  build-fail-blacklist
  recipes/bioconductor-bgx/build.sh
  recipes/bioconductor-bgx/meta.yaml
Labels: please review & merge

#25306 Bioconductor 3.12 hackathon: fix networkbma
  build-fail-blacklist
  recipes/bioconductor-networkbma/0001-Fix-sort_index-sort_direction-parameter.patch
  recipes/bioconductor-networkbma/meta.yaml
Labels: please review & merge

#25307 Bioconductor 3.12 hackathon: fix chicago, pchicdata
  build-fail-blacklist
Labels: please review & merge

#25305 Bioconductor 3.12 hackathon: fix rariant
  build-fail-blacklist
  recipes/bioconductor-rariant/0001-Replace-deprecated-rbind_all-with-bind_rows.patch
  recipes/bioconductor-rariant/meta.yaml
Labels: please review & merge

#25313 Bioconductor 3.12 hackathon: fix dep r-gmwt
  recipes/r-gmwt/meta.yaml
Labels: please review & merge

#25312 Bioconductor 3.12 hackathon: fix dep libsbml
  recipes/libsbml/build.sh
  recipes/libsbml/meta.yaml
Labels: please review & merge

#25304 Bioconductor 3.12 hackathon: fix sictools
  build-fail-blacklist
  recipes/bioconductor-sictools/build.sh
  recipes/bioconductor-sictools/meta.yaml
Labels: please review & merge

#25309 Bioconductor 3.12 hackathon: fix netboost
  recipes/bioconductor-netboost/0001-Omit-non-compiling-unused-function.patch
  recipes/bioconductor-netboost/build.sh
  recipes/bioconductor-netboost/meta.yaml
Labels: please review & merge

#25104 New software for phylogenetic placement: App-SpaM
  recipes/appspam/build.sh
  recipes/appspam/meta.yaml
Labels: please review & merge

#25321 libsbml: try macOS build
  recipes/libsbml/meta.yaml
Labels: please review & merge

#25327 Fix bioconductor-rbowtie build on macOS
  build-fail-blacklist
  recipes/bioconductor-rbowtie/build.sh
  recipes/bioconductor-rbowtie/ldflags.patch
  recipes/bioconductor-rbowtie/meta.yaml
Labels: please review & merge

#25317 Bioconductor 3.12 hackathon: fix rsbml
  build-fail-blacklist
  recipes/bioconductor-rsbml/meta.yaml
Labels: please review & merge

#25330 Kakscalculator2
  recipes/kakscalculator2/build.sh
  recipes/kakscalculator2/meta.yaml
Labels: please review & merge

#25334 Rebuild packages that depend on bioconductor-rbowtie
  build-fail-blacklist
  recipes/bioconductor-macpet/meta.yaml
  recipes/bioconductor-quasr/meta.yaml
Labels: please review & merge

#25303 Update lorikeet-genome to v0.5.0
  recipes/lorikeet-genome/build.sh
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#25338 test some bioconductor packages
  build-fail-blacklist
  recipes/bioconductor-mafh5.gnomad.r3.0.grch38/meta.yaml
Labels: please review & merge

#25348 Add Bioframe 0.0.12
  recipes/bioframe/meta.yaml
Labels: please review & merge

#25350 Add cooltools 0.3.2
  recipes/cooltools/meta.yaml
Labels: please review & merge

#25374 Remove bioconductor-transite from the blacklist
  build-fail-blacklist
Labels: please review & merge

#25375 Remove bioconductor-wpm from the blacklist
  build-fail-blacklist
Labels: please review & merge

#25376 Update vcf2maf: use most recent sha256sum
  recipes/vcf2maf/meta.yaml
Labels: please review & merge

#25379 Fix r-misha build on macOS
  build-fail-blacklist
  recipes/r-misha/meta.yaml
  recipes/r-misha/omit-FileUtils.patch
Labels: please review & merge

#25378 Use extended image for irida-uploader
  recipes/irida-uploader/meta.yaml
Labels: please review & merge

#25392 add proper tests to intervene
  recipes/intervene/meta.yaml
Labels: please review & merge

#25396 Update r-misha to 4.0.11
  recipes/r-misha/meta.yaml
  recipes/r-misha/omit-FileUtils.patch
Labels: please review & merge

#25300 Update gnali to version 1.0.0
  recipes/gnali/meta.yaml
  recipes/gnali/post-link.sh
Labels: please review & merge

#25397 R-saige fix build
  recipes/r-saige/0.39/build.sh
  recipes/r-saige/0.39/meta.yaml
  recipes/r-saige/build.sh
  recipes/r-saige/meta.yaml
Labels: please review & merge

#25424 Update bioconductor-atacseqqc to 1.14.4
  recipes/bioconductor-atacseqqc/meta.yaml
Labels: please review & merge

#25434 dsh-bio 1.4
  recipes/dsh-bio/build.sh
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#25418 DROP requirements and test fixes
  recipes/drop/meta.yaml
  recipes/drop/run_test.sh
Labels: please review & merge

#25440 Change how mmseqs2 is dealing with openmp
  recipes/mmseqs2/meta.yaml
Labels: please review & merge

#25452 Add kmer-db
  recipes/kmer-db/build.sh
  recipes/kmer-db/meta.yaml
Labels: please review & merge

#25444 Add batch_brb
  recipes/batch_brb/LICENSE
  recipes/batch_brb/build.sh
  recipes/batch_brb/meta.yaml
Labels: please review & merge

#25461 migmap: restrict java <9
  recipes/migmap/meta.yaml
Labels: please review & merge

#25393 switch ensemble-vep to extended-base
  recipes/ensembl-vep/meta.yaml
Labels: please review & merge

#25465 Add Qax 0.4.0
  recipes/qax/build.sh
  recipes/qax/meta.yaml
Labels: please review & merge

#25467 Update rnaQUAST to 2.2.0
  recipes/rnaquast/meta.yaml
Labels: please review & merge

#25477 Update gNALI recipe
  recipes/gnali/meta.yaml
Labels: please review & merge

#25479 update - goleft version
  recipes/goleft/meta.yaml
Labels: please review & merge

#25471 Add initial Bakta v0.3
  recipes/bakta/meta.yaml
Labels: please review & merge

#25487 Updated App-SpaM with bug fixes
  recipes/appspam/meta.yaml
Labels: please review & merge

#25482 bump r-saige to 0.43
  recipes/r-saige/build.sh
  recipes/r-saige/meta.yaml
Labels: please review & merge

#25489 Add GECKO tool recipe
  recipes/gecko/build.sh
  recipes/gecko/meta.yaml
Labels: please review & merge

#25497 Update refseq_masher to 0.1.2
  recipes/refseq_masher/meta.yaml
Labels: please review & merge

#25495 Set RepeatMasker default search engine to rmblast
  recipes/repeatmasker/build.sh
  recipes/repeatmasker/meta.yaml
Labels: please review & merge

#25508 encyclopedia and mpa-portable: add fonts and fix permissions
  recipes/encyclopedia/meta.yaml
  recipes/mpa-portable/build.sh
  recipes/mpa-portable/meta.yaml
Labels: please review & merge

#25511 Add recipes for tools KNOT: Knowledge Network Overlap exTraction
  recipes/knot-asm-analysis/meta.yaml
Labels: please review & merge

#25529 Update idemux to 0.1.5
  recipes/idemux/meta.yaml
Labels: please review & merge

#25526 Update of tool GECKO (from 1.0.2 to 1.0.3)
  recipes/gecko/meta.yaml
Labels: please review & merge

#25523 Update mafft to 7.475
  recipes/mafft/meta.yaml
Labels: please review & merge

#25530 Update qax to 0.6.0
  recipes/qax/meta.yaml
Labels: please review & merge

#25535 Update Danpos run dependency
  recipes/danpos/meta.yaml
Labels: please review & merge

#25536 Add Kaptive
  recipes/kaptive/build.sh
  recipes/kaptive/meta.yaml
  recipes/kaptive/post-link.sh
Labels: please review & merge

#25504 Add predicthaplo recipe
  recipes/predicthaplo/meta.yaml
Labels: please review & merge

#25531 Add variantmap
  recipes/variantmap/meta.yaml
  recipes/variantmap/run_test.py
Labels: please review & merge

#25553 update artic-tools
  recipes/artic-tools/build.sh
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#25547 update ganon to 0.3.4
  recipes/ganon/meta.yaml
Labels: please review & merge

#25562 Bump up abnumber to 0.1.5
  recipes/abnumber/meta.yaml
Labels: please review & merge

#25572 Update shortstack 3.8.5 recipe
  recipes/shortstack/build.sh
  recipes/shortstack/meta.yaml
Labels: please review & merge

#25576 Update recipes wrapper added
  recipes/submission-tool-validator/build.sh
  recipes/submission-tool-validator/meta.yaml
  recipes/submission-tool-validator/submission-tool-validator.py
Labels: please review & merge
