Repository bioconda/bioconda-recipes, pull requests merged in 2020-01, with the labels that each got.

#19516 Update recipe for FusionCatcher with newer dependency and data versions
  recipes/fusioncatcher/download-human-db.sh
  recipes/fusioncatcher/meta.yaml
  recipes/fusioncatcher/post-link.sh
Labels: please review & merge

#19523 Add ncbimeta
  recipes/ncbimeta/meta.yaml
Labels: please review & merge

#19538 Updated pinned dependencies for version 1.8.0
  recipes/rnalien/meta.yaml
Labels: enhancement, haskell, please review & merge

#19505 moabs/meta.yaml: add host and run dependencies
  recipes/moabs/meta.yaml
Labels: please review & merge

#19529 Add famsa
  recipes/famsa/LICENSE
  recipes/famsa/build.sh
  recipes/famsa/fix-osx-vectorclass.patch
  recipes/famsa/meta.yaml
Labels: please review & merge

#19546 New: cameo v0.11.15 -- metabolic engineering strain design
  recipes/cameo/meta.yaml
Labels: please review & merge

#19550 Update Rnachipintegrator recipe to 2.0.0
  recipes/rnachipintegrator/meta.yaml
Labels: please review & merge

#19553 update SPAdes to 3.14.0
  recipes/spades/0001-add-rt-lib-to-easel.patch
  recipes/spades/0001-fix-cpu-count.patch
  recipes/spades/0001-link-rt-for-static-jemalloc.patch
  recipes/spades/0002-disable-parallel-libstdc.patch
  recipes/spades/meta.yaml
Labels: new version, please review & merge

#19340 [FEATURE] Restructure Openms related recipes
  recipes/openms/apple-fixup-pyoms.patch
  recipes/openms/build.sh
  recipes/openms/c17.patch
  recipes/openms/compilerflags.patch
  recipes/openms/conda_build_config.yaml
  recipes/openms/install_pyopenms.sh
  recipes/openms/library.patch
  recipes/openms/meta.yaml
  recipes/openms/package_libopenms.sh
  recipes/openms/package_openms-tools.sh
  recipes/openms/setup.py.patch
Labels: please review & merge

#19564 add influx_si
  recipes/influx_si/LICENSE
  recipes/influx_si/meta.yaml
Labels: please review & merge

#19518 Use newer macOS image on CircleCI
  .circleci/config.yml
Labels: bioconda-infrastructure

#19579 Mwga utils
  recipes/mwga-utils/meta.yaml
Labels: please review & merge

#19610 CircleCI: macOS: run_conda_forge_build_setup
  .circleci/setup.sh
Labels: please review & merge

#19623 Transposcope
  recipes/transposcope/meta.yaml
Labels: please review & merge

#19625 tracy v0.5.6
  recipes/tracy/meta.yaml
Labels: please review & merge

#19649 Transposcope
  recipes/transposcope/meta.yaml
Labels: please review & merge

#19650 alfred v0.1.18
  recipes/alfred/Makefile.patch
  recipes/alfred/build.sh
  recipes/alfred/meta.yaml
Labels: please review & merge

#19653 Update r-immunedeconv to 2.0.1.
  recipes/r-immunedeconv/meta.yaml
Labels: please review & merge

#19644 cgat-apps 0.5.6
  recipes/cgat-apps/meta.yaml
Labels: please review & merge

#19639 PR template visuals
  .github/PULL_REQUEST_TEMPLATE.md
Labels: please review & merge

#19679 Replaced SHA
  recipes/hypo/meta.yaml
Labels: please review & merge

#19678 Update MOABS to v1.3.8.4: add libis run time dependency
  recipes/moabs/meta.yaml
Labels: please review & merge

#19685 Rebuild MOABS to resolve LiBis dependency
  recipes/moabs/meta.yaml
Labels: please review & merge

#19688 moabs/meta.yaml: add pysam dependency for libis
  recipes/moabs/meta.yaml
Labels: please review & merge

#19691 Rebuild r-wasabi for R 3.6
  recipes/r-wasabi/meta.yaml
Labels: please review & merge

#19667 add older version (1.6.4.4) for compatibility with python3
  recipes/pp/1.6.4.4/meta.yaml
Labels: please review & merge

#19695 Updated to 1.0.1
  recipes/hypo/march.patch
  recipes/hypo/meta.yaml
Labels: please review & merge

#19692 [yacrd] add yacrd 0.6.0 version
  recipes/yacrd/build.sh
  recipes/yacrd/meta.yaml
Labels: please review & merge

#19699 Interleafq v0.92
  recipes/interleafq/build.sh
  recipes/interleafq/meta.yaml
Labels: please review & merge

#19705 Add tar to Centrifuge
  recipes/centrifuge/meta.yaml
Labels: please review & merge

#19702 PretextGraph
  recipes/pretextgraph/build.sh
  recipes/pretextgraph/meta.yaml
Labels: please review & merge

#19706 Chromosight
  recipes/chromosight/meta.yaml
Labels: please review & merge

#19714 Update spectrum_utils to version 0.3.3
  recipes/spectrum_utils/meta.yaml
Labels: please review & merge

#19715 Imsindel
  recipes/imsindel/build.sh
  recipes/imsindel/meta.yaml
Labels: please review & merge

#19717 r-vcfr migration to conda-forge.
  recipes/r-vcfr/build.sh
  recipes/r-vcfr/meta.yaml
Labels: WIP

#19708 Add tar to Clark
  recipes/clark/build.sh
  recipes/clark/meta.yaml
Labels: please review & merge

#19720 Pretext-Suite -> add PretextGraph
  recipes/pretext-suite/meta.yaml
Labels: please review & merge

#19730 update KMC kmer counter to bug-fix release 3.1.2rc1
  recipes/kmc/meta.yaml
Labels: new version, please review & merge

#19735 Updated biobasehttptools to version 1.1.0
  recipes/biobasehttptools/build.sh
  recipes/biobasehttptools/meta.yaml
Labels: haskell, please review & merge

#19728 dsh-bio 1.3.1
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#19743 Add macrel at v0.2
  recipes/macrel/build.sh
  recipes/macrel/meta.yaml
Labels: please review & merge

#19750 Add tinyalign recipe
  recipes/tinyalign/meta.yaml
Labels: please review & merge

#19719 TEsorter python3
  recipes/tesorter/meta.yaml
Labels: please review & merge

#19683 Add THESIAS 3.1
  recipes/thesias/THESIAS.py
  recipes/thesias/build.sh
  recipes/thesias/meta.yaml
Labels: please review & merge

#19747 Add recipe for pp-sketchlib
  recipes/pp-sketchlib/meta.yaml
Labels: please review & merge

#19772 Sctools
  recipes/sctools/build.sh
  recipes/sctools/meta.yaml
Labels: please review & merge

#19784 add EMBLmyGFF3 recipe
  recipes/emblmygff3/meta.yaml
Labels: please review & merge

#19779 Perl text csv xs
  recipes/perl-text-csv_xs/build.sh
  recipes/perl-text-csv_xs/meta.yaml
Labels: please review & merge

#19777 Add locus-processing recipe.
  recipes/locus_processing/meta.yaml
Labels: please review & merge

#19792 update pyfaidx after "hotfix", same version
  recipes/pyfaidx/meta.yaml
Labels: please review & merge

#19828 Bump vSNP in a cleaner way
  recipes/vsnp/meta.yaml
Labels: please review & merge

#19829 Bumping digestiflow-demux.
  recipes/digestiflow-demux/meta.yaml
Labels: please review & merge

#19832 Bump IgDiscover to 0.12
  build-fail-blacklist
  build.sh
  meta.yaml
  recipes/igdiscover/cpucount-osx.patch
  recipes/igdiscover/meta.yaml
Labels: please review & merge

#19856 updated requirements for star-fusion 1.8.1
  recipes/star-fusion/meta.yaml
Labels: please review & merge

#19771 Perl metabolomics fragment annotation 0.2.0
  recipes/perl-metabolomics-fragment-annotation/build.sh
  recipes/perl-metabolomics-fragment-annotation/meta.yaml
Labels: please review & merge

#19837 Fix transit pinning
  recipes/transit/meta.yaml
Labels: please review & merge

#19841 add recipe for Generic repeat finder
  recipes/genericrepeatfinder/build.sh
  recipes/genericrepeatfinder/meta.yaml
Labels: please review & merge

#19863 bump svim and enforce pysam version>=0.15
  recipes/svim/meta.yaml
Labels: new version, please review & merge

#19843 Add recipe for velocyto.R
  recipes/r-velocyto.r/meta.yaml
Labels: please review & merge

#19864 Add ntHits
  recipes/nthits/build.sh
  recipes/nthits/meta.yaml
Labels: please review & merge

#19868 scalpel: fix build for Microassembler
  recipes/scalpel/build.sh
  recipes/scalpel/meta.yaml
Labels: please review & merge

#19470 Add libgcc to kissplice runtime requirements
  recipes/kissplice/meta.yaml
Labels: please review & merge

#19876 Update pp-sketchlib to v1.0.1
  recipes/pp-sketchlib/meta.yaml
Labels: please review & merge

#19885 [FIX] Autodetection in CMake of SeqAn3 recipe
  recipes/seqan3/build.sh
  recipes/seqan3/meta.yaml
Labels: please review & merge

#19896 Bump freebayes to 1.3.2
  recipes/freebayes/meta.yaml
Labels: please review & merge

#19898 Update SeqAn to 3.0.1
  recipes/seqan3/build.sh
  recipes/seqan3/meta.yaml
Labels: please review & merge

#19891 Add qtl2
  recipes/r-qtl2/build.sh
  recipes/r-qtl2/meta.yaml
Labels: please review & merge

#19900 Update recipe for vibrant 1.0.1
  recipes/vibrant/meta.yaml
  recipes/vibrant/path.patch
Labels: please review & merge

#19912 Pin mongoengine for mykrobe
  recipes/mykrobe/meta.yaml
Labels: please review & merge

#19914 macrel: Update to 0.3
  recipes/macrel/meta.yaml
Labels: please review & merge

#19936 star-fusion requirements updated
  recipes/star-fusion/meta.yaml
Labels: please review & merge

#19926 Fix mykrobe pin
  recipes/mykrobe/meta.yaml
Labels: please review & merge

#19917 Add crisprbact recipe
  recipes/crisprbact/meta.yaml
Labels: please review & merge

#19910 Ltr retriever
  recipes/ltr_retriever/build.sh
  recipes/ltr_retriever/meta.yaml
Labels: please review & merge

#19923 Update chexmix to 0.45
  recipes/chexmix/build.sh
  recipes/chexmix/chexmix.sh
  recipes/chexmix/meta.yaml
Labels: please review & merge

#19941 Replace PR #19803, update pyomero-upload and remove migrated zeroc-ice
  build-fail-blacklist
  recipes/pyomero-upload/meta.yaml
  recipes/zeroc-ice/build.sh
  recipes/zeroc-ice/meta.yaml
Labels: please review & merge

#19701 KOFAMSCAN
  recipes/kofamscan/build.sh
  recipes/kofamscan/meta.yaml
  recipes/kofamscan/post-link.sh
Labels: please review & merge

#19944 Update meta.yaml
  recipes/scanpy/meta.yaml
Labels: please review & merge

#19951 Updated fastqc to 0.11.9
  recipes/fastqc/meta.yaml
Labels: please review & merge

#19964 Update BinSanity to 0.3.4
  recipes/binsanity/meta.yaml
Labels: please review & merge

#19977 Added a missing file for Kaiju
  recipes/kaiju/build.sh
  recipes/kaiju/meta.yaml
Labels: please review & merge

#19794 Add pgx-variant-tools recipe.
  recipes/pgx-variant-tools/meta.yaml
Labels: please review & merge

#19978 bumpy fwdpy11 to 0.5.5
  recipes/fwdpy11/meta.yaml
Labels: please review & merge

#19976 Add Conterminator package
  recipes/conterminator/build.sh
  recipes/conterminator/meta.yaml
Labels: please review & merge

#19982 update trnanalysis=0.1.10
  recipes/trnanalysis/meta.yaml
Labels: please review & merge

#19984 Pgx extended
  recipes/pgx-variant-tools/meta.yaml
Labels: please review & merge

#19965 update ntCard to 1.2.0
  build-fail-blacklist
  recipes/ntcard/meta.yaml
Labels: please review & merge

#19988 Rename r-bioverbs to r-acidgenerics
  recipes/r-acidgenerics/build.sh
  recipes/r-acidgenerics/meta.yaml
Labels: please review & merge

#19985 Depend on matplotlib-base instead of matplotlib
  recipes/deeptools/meta.yaml
Labels: please review & merge

#19986 Bump monocle3-cli to 0.0.5
  recipes/monocle3-cli/meta.yaml
Labels: please review & merge

#19993 Add scikit-learn dependency to macrel
  recipes/macrel/meta.yaml
Labels: please review & merge

#19987 Add phastaf
  recipes/phastaf/build.sh
  recipes/phastaf/meta.yaml
Labels: please review & merge

#19995 Pyfastx
  recipes/pyfastx/meta.yaml
Labels: please review & merge

#19895 Perl metabolomics fragment annotation 0.3
  recipes/perl-metabolomics-fragment-annotation/meta.yaml
Labels: please review & merge

#20004 update ntcard to 1.2.1
  recipes/ntcard/meta.yaml
Labels: please review & merge

#19998 thapbi-pict 0.6.5, has slight dep change
  recipes/thapbi-pict/meta.yaml
Labels: please review & merge

#20005 Correct version number
  recipes/freebayes/meta.yaml
Labels: please review & merge

#20006 Ltr finder
  recipes/ltr_finder/build.sh
  recipes/ltr_finder/meta.yaml
  recipes/ltr_finder/run_test.sh
Labels: please review & merge

#20000 Phylics
  recipes/phylics/build.sh
  recipes/phylics/meta.yaml
Labels: please review & merge

#20009 Bump sourmash to 3.2.0 and add bam2fasta dependency
  recipes/sourmash/meta.yaml
Labels: please review & merge

#20013 Need python- prefix for edlib in bioconda world.
  recipes/pgx-variant-tools/meta.yaml
Labels: please review & merge

#20019 Phylics
  recipes/phylics/build.sh
  recipes/phylics/meta.yaml
Labels: please review & merge

#20018 Update Segway recipe to version 3.0
  recipes/segway/meta.yaml
Labels: please review & merge

#19849 Create ntjoin recipe
  recipes/ntjoin/build.sh
  recipes/ntjoin/meta.yaml
Labels: please review & merge

#19847 Add new meta.yaml recipe for ntedit
  recipes/ntedit/build.sh
  recipes/ntedit/meta.yaml
Labels: please review & merge

#20021 Catch up with upstream change.
  recipes/pgx-variant-tools/meta.yaml
Labels: please review & merge

#20023 Version bump for scelvis v0.8.2
  recipes/scelvis/meta.yaml
Labels: please review & merge

#20016 Add geosketch
  recipes/geosketch/meta.yaml
Labels: please review & merge

#20025 Bump MethylDackel to 0.5.0
  recipes/methyldackel/build.sh
  recipes/methyldackel/meta.yaml
Labels: please review & merge

#20027 Update ABySS to 2.2.4
  recipes/abyss/meta.yaml
Labels: please review & merge

#20011 Add pgx-pipe-helper.
  recipes/pgx-pipe-helper/meta.yaml
Labels: please review & merge

#20028 Update gimmemotifs to 0.14.2
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#20026 Initial meta.yaml for pyslim
  recipes/pyslim/meta.yaml
Labels: please review & merge

#20017 Add SICER2
  recipes/sicer2/meta.yaml
Labels: please review & merge

#20074 Coral
  recipes/coral/build.sh
  recipes/coral/meta.yaml
Labels: please review & merge
