Repository bioconda/bioconda-recipes, pull requests merged in 2020-04, with the labels that each got.

#21222 2020.4
  recipes/biobb_common/meta.yaml
Labels: please review & merge

#21154 update recipe for sequana 0.8.2
  recipes/sequana/build.sh
  recipes/sequana/meta.yaml
  recipes/sequana/patch.diff
Labels: please review & merge

#21215 Add TreeSAPP recipe
  recipes/treesapp/meta.yaml
Labels: please review & merge

#21231 transindel patch
  recipes/transindel/meta.yaml
  recipes/transindel/transIndel_call.py.patch
Labels: please review & merge

#21149 Add HiTaC
  recipes/hitac/meta.yaml
Labels: please review & merge

#21256 Add artic-porechop
  recipes/artic-porechop/build.sh
  recipes/artic-porechop/meta.yaml
Labels: please review & merge

#21263 Add lusSTR
  recipes/lusstr/meta.yaml
  recipes/lusstr/run_test.sh
Labels: please review & merge

#21240 [Update] smallgenomeutilities version upgrade to 0.3.0
  recipes/smallgenomeutilities/0.3.0/build.sh
  recipes/smallgenomeutilities/0.3.0/meta.yaml
Labels: please review & merge

#21268 Update URLs for PlaScope.
  recipes/plascope/meta.yaml
Labels: please review & merge

#21267 Update sensv to 1.0.2
  recipes/sensv/meta.yaml
Labels: please review & merge

#21211 deepvariant: update 0.10.0: fix zipfile issue, finalize deps
  recipes/deepvariant/build.sh
  recipes/deepvariant/meta.yaml
  recipes/deepvariant/post-link.sh
Labels: please review & merge

#21257 Bump porechop to 0.2.4
  build-fail-blacklist
  recipes/porechop/build.sh
  recipes/porechop/meta.yaml
Labels: please review & merge

#21258 Update gimmemotifs to 0.14.4
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#21261 Add ANANSE
  recipes/ananse/meta.yaml
Labels: please review & merge

#21270 Add recipe phylodm 1.0.0
  recipes/phylodm/meta.yaml
Labels: please review & merge

#21281 Update anvio 6.2 recipe to set critical version numbers
  recipes/anvio-minimal/meta.yaml
Labels: please review & merge

#21279 Add recipe for cell-types-analysis
  recipes/cell-types-analysis/build.sh
  recipes/cell-types-analysis/meta.yaml
Labels: please review & merge

#21255 Add recipe for bifrost
  recipes/bifrost/build.sh
  recipes/bifrost/cross-linux.cmake
  recipes/bifrost/meta.yaml
Labels: please review & merge

#21049 Add ExpressBetaDiversity 1.0.10
  recipes/expressbetadiversity/build.sh
  recipes/expressbetadiversity/meta.yaml
Labels: please review & merge

#21226 Add MSAProbs recipe
  recipes/msaprobs/Makefile.patch
  recipes/msaprobs/build.sh
  recipes/msaprobs/meta.yaml
Labels: please review & merge

#21276 Update unitig-caller to v1.0.1
  recipes/unitig-caller/meta.yaml
Labels: please review & merge

#21319 Add PrimedRPA tool
  recipes/primedrpa/meta.yaml
Labels: please review & merge

#21313 perl-fastx-reader update to 0.87
  build-fail-blacklist
  recipes/perl-fastx-reader/meta.yaml
Labels: please review & merge

#21320 Update odgi to 0.3
  recipes/odgi/meta.yaml
Labels: please review & merge

#21330 nanopolish: fix macOS build
  recipes/nanopolish/build.sh
  recipes/nanopolish/meta.yaml
Labels: please review & merge

#21337 Update Transposcope
  recipes/transposcope/meta.yaml
Labels: please review & merge

#21354 Update fermi2 recipe to use Conda GCC
  recipes/fermi2/build.sh
  recipes/fermi2/meta.yaml
Labels: please review & merge

#21356 Update seqwish to v0.4
  recipes/seqwish/meta.yaml
Labels: please review & merge

#21335 Update coinfinder recipe
  recipes/coinfinder/meta.yaml
Labels: please review & merge

#21329 Update Cluster Picker to v. 1.2.5
  recipes/clusterpicker/build.sh
  recipes/clusterpicker/meta.yaml
Labels: please review & merge

#21355 Update metaeuk to 2-ddf2742
  recipes/metaeuk/meta.yaml
Labels: please review & merge

#21372 Update CLIPcontext
  recipes/clipcontext/meta.yaml
Labels: please review & merge

#21360 added recipe for transcov
  recipes/transcov/meta.yaml
Labels: please review & merge

#21341 panaroo: Update recipe to work with most recent release
  recipes/panaroo/meta.yaml
Labels: please review & merge

#21375 bump luciphor to 2.1
  recipes/luciphor2/meta.yaml
Labels: please review & merge

#21401 Remove augustus constraint for BUSCO v4.0.6
  recipes/busco/meta.yaml
Labels: please review & merge

#21403 Add - Blast legacy old version for interproscan
  recipes/blast-legacy/2.2.19/build.sh
  recipes/blast-legacy/2.2.19/meta.yaml
Labels: please review & merge

#21383 Update trimadap recipe to use Conda GCC
  recipes/trimadap/build.sh
  recipes/trimadap/meta.yaml
Labels: please review & merge

#21412 Add Pftools
  recipes/pftools/build.sh
  recipes/pftools/meta.yaml
Labels: please review & merge

#21393 pin r-base to 3.6.0 for biotradis
  recipes/biotradis/meta.yaml
Labels: please review & merge

#21425 Add tag library v0.4
  recipes/tag/meta.yaml
  recipes/tag/run_test.sh
Labels: please review & merge

#21380 Add Terminus
  recipes/terminus/build.sh
  recipes/terminus/meta.yaml
Labels: please review & merge

#21422 N50 - Version 1.2.0 bump and metadata update
  recipes/n50/meta.yaml
Labels: please review & merge

#21388 Add MetaMaps
  recipes/metamaps/build.sh
  recipes/metamaps/meta.yaml
Labels: please review & merge

#21331 Add diego recipe
  recipes/diego/LICENSE
  recipes/diego/build.sh
  recipes/diego/meta.yaml
Labels: please review & merge

#21376 Bump NGLess to v1.1.1
  recipes/ngless/build.sh
  recipes/ngless/meta.yaml
Labels: please review & merge

#21413 Update Mikado to 2.0 RC1
  recipes/mikado/meta.yaml
Labels: new version, please review & merge

#20842 Add package singlem 0.13.2
  recipes/singlem/meta.yaml
Labels: please review & merge

#21447 Update bcalm to version 2.2.2
  recipes/bcalm/CMakeLists.patch
  recipes/bcalm/meta.yaml
Labels: please review & merge

#21444 Add DeepMAsED
  recipes/deepmased/LICENSE
  recipes/deepmased/meta.yaml
Labels: please review & merge

#21499 Add MPRA data access portal recipe.
  recipes/mpra-data-access-portal/build.sh
  recipes/mpra-data-access-portal/meta.yaml
  recipes/mpra-data-access-portal/wrapper.sh
Labels: WIP

#21528 Add networkx to OpenDUck requirements
  recipes/openduck/meta.yaml
Labels: please review & merge

#21531 Update clair to 2.1.0
  recipes/clair/meta.yaml
Labels: please review & merge

#21504 Add scirpy
  recipes/scirpy/meta.yaml
Labels: please review & merge

#21502 Making MPRA data acess host/port configurable.
  recipes/mpra-data-access-portal/app.patch
  recipes/mpra-data-access-portal/meta.yaml
  recipes/mpra-data-access-portal/wrapper.sh
Labels: please review & merge

#21547 Update pysradb to 0.10.3
  recipes/pysradb/meta.yaml
Labels: please review & merge

#21518 Add abpoa
  recipes/abpoa/build.sh
  recipes/abpoa/meta.yaml
Labels: please review & merge

#21446 Update dsk to 2.3.1 version
  build-fail-blacklist
  recipes/dsk/build.sh
  recipes/dsk/install_paths.patch
  recipes/dsk/meta.yaml
Labels: please review & merge

#21488 Update bcalm to the good gatb-core version
  recipes/bcalm/build.sh
  recipes/bcalm/meta.yaml
Labels: please review & merge

#21535 Update - fix Kraken2 segmentation fault
  recipes/kraken2/meta.yaml
Labels: please review & merge

#21479 create haphpipe recipe
  recipes/haphpipe/meta.yaml
Labels: please review & merge

#21553 Update ddrage to 1.7.1
  recipes/ddrage/meta.yaml
Labels: please review & merge

#21501 Update hmmer to keep easel lib in /share
  recipes/hmmer/build.sh
  recipes/hmmer/meta.yaml
Labels: please review & merge

#21347 Update optitype recipe
  build-fail-blacklist
  recipes/optitype/build.sh
  recipes/optitype/config.ini
  recipes/optitype/meta.yaml
Labels: please review & merge

#21429 Update bwakit 0.7.15 to de-vendor binaries and add missing dependencies
  recipes/bwakit/build.sh
  recipes/bwakit/meta.yaml
  recipes/bwakit/patches/run-HLA.patch
  recipes/bwakit/patches/run-bwamem.patch
  recipes/bwakit/patches/run-gen-ref.patch
  recipes/fermi2/r170/build.sh
  recipes/fermi2/r170/meta.yaml
  recipes/htsbox/r315/build.sh
  recipes/htsbox/r315/meta.yaml
  recipes/samblaster/0.1.20/build.sh
  recipes/samblaster/0.1.20/meta.yaml
  recipes/samblaster/0.1.20/osx.patch
  recipes/samtools/1.3/build.sh
  recipes/samtools/1.3/meta.yaml
  recipes/trimadap/r2/build.sh
  recipes/trimadap/r2/meta.yaml
  recipes/trimadap/r2/streams.patch
Labels: please review & merge

#21500 seqfu v.0.2.0 - updated recipe
  recipes/seqfu/build.sh
  recipes/seqfu/meta.yaml
  recipes/seqfu/run_test.sh
Labels: please review & merge

#21562 Properly starting shiny in server.
  recipes/mpra-data-access-portal/app.patch
  recipes/mpra-data-access-portal/meta.yaml
  recipes/mpra-data-access-portal/wrapper.sh
Labels: please review & merge

#21523 Update medpy recipe for graphcut support
  recipes/medpy/graphcut_boost_lib.patch
  recipes/medpy/meta.yaml
Labels: please review & merge

#21567 update haphpipe
  recipes/haphpipe/meta.yaml
Labels: please review & merge

#21589 Update Kc-Align Dependencies
  recipes/kcalign/meta.yaml
Labels: enhancement

#21588 Genometester4 update
  build-fail-blacklist
  recipes/genometester4/build.sh
  recipes/genometester4/meta.yaml
Labels: please review & merge

#21574 Add recipe for R package sgtr
  recipes/r-sgtr/build.sh
  recipes/r-sgtr/meta.yaml
Labels: please review & merge

#21594 Supports full-length MSA of closely-related viral genomes
  recipes/mafft/meta.yaml
Labels: please review & merge

#21595 Add sfld recipe (needed for interproscan)
  recipes/sfld/build.sh
  recipes/sfld/conda_build_config.yaml
  recipes/sfld/meta.yaml
  recipes/sfld/patch1
Labels: please review & merge

#21359 Update watchdog-wms to make JARs and helper scripts better accessible
  recipes/watchdog-wms/build.sh
  recipes/watchdog-wms/meta.yaml
Labels: please review & merge

#21569 Perl bio phylo cipres
  recipes/perl-bio-phylo-cipres/v0.2.1/build.sh
  recipes/perl-bio-phylo-cipres/v0.2.1/meta.yaml
Labels: please review & merge

#21516 Strainseeker recipe
  recipes/strainseeker/build.sh
  recipes/strainseeker/meta.yaml
Labels: please review & merge

#21612 Update GraphAligner to version 1.0.11
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#21635 Update PopPUNK to v2.0.2
  recipes/poppunk/meta.yaml
Labels: please review & merge

#21627 Update source for igphyml recipe
  recipes/igphyml/meta.yaml
Labels: please review & merge

#21621 Add d-genies
  recipes/dgenies/meta.yaml
  recipes/tendo/meta.yaml
Labels: please review & merge

#21654 add nebulizer 0.5.0
  recipes/nebulizer/meta.yaml
Labels: please review & merge

#21634 Add recipe for KrakenTools
  recipes/krakentools/build.sh
  recipes/krakentools/meta.yaml
  recipes/krakentools/patch_combine_kreports.py
  recipes/krakentools/patch_extract_kraken_reads.py
  recipes/krakentools/patch_filter_bracken.out.py
  recipes/krakentools/patch_fix_unmapped.py
  recipes/krakentools/patch_kreport2krona.py
  recipes/krakentools/patch_make_kreport.py
  recipes/krakentools/patch_make_ktaxonomy.py
Labels: please review & merge

#21656 update ivar (v 1.2.1)
  recipes/ivar/build.sh
  recipes/ivar/meta.yaml
Labels: please review & merge

#21670 Sanitize me
  recipes/sanitizeme/build.sh
  recipes/sanitizeme/meta.yaml
Labels: please review & merge

#21665 Update mgkit recipe for release 0.4.3
  recipes/mgkit/meta.yaml
Labels: please review & merge

#21686 Update graphtyper to 2.3
  recipes/graphtyper/meta.yaml
Labels: please review & merge

#21685 Add mp3treesim
  recipes/mp3treesim/meta.yaml
Labels: please review & merge

#21672 Add deepaclive
  recipes/deepaclive/LICENSE
  recipes/deepaclive/meta.yaml
Labels: please review & merge

#21602 tracy: update to v0.5.7
  recipes/tracy/build.sh
  recipes/tracy/meta.yaml
Labels: please review & merge

#21626 Update radsex to 1.0.0
  recipes/radsex/build.sh
  recipes/radsex/meta.yaml
Labels: please review & merge

#21699 Add pMMRCalculator recipe.
  recipes/pmmrcalculator/build.sh
  recipes/pmmrcalculator/meta.yaml
Labels: please review & merge

#21706 sanitizeme_update
  recipes/sanitizeme/meta.yaml
Labels: please review & merge

#21708 Update: TEtranscripts
  recipes/tetoolkit/meta.yaml
  recipes/tetranscripts/meta.yaml
Labels: please review & merge

#21704 Update RepeatMasker - add wublastToCrossmatch.pl buildRMLibFromEMBL.pl utils missing. Fix #…
  recipes/repeatmasker/build.sh
  recipes/repeatmasker/meta.yaml
Labels: please review & merge

#21711 new recipe: metalign
  recipes/metalign/meta.yaml
Labels: please review & merge

#21717 Update dependencies for croo
  recipes/croo/meta.yaml
Labels: please review & merge

#21727 add gifrop recipe
  recipes/gifrop/build.sh
  recipes/gifrop/meta.yaml
Labels: please review & merge

#21732 bump ganon version to 0.2.2
  recipes/ganon/meta.yaml
Labels: please review & merge

#21736 Bumping hlso v0.4.4.
  recipes/haplotype-lso/meta.yaml
Labels: please review & merge

#21701 Update python-bioext to 0.19.7
  recipes/python-bioext/build.sh
  recipes/python-bioext/meta.yaml
  recipes/python-bioext/scipy-stats.patch
Labels: please review & merge

#21739 update scmap-cli to 0.0.8
  recipes/scmap-cli/build.sh
  recipes/scmap-cli/meta.yaml
Labels: please review & merge

#21740 update scpred-cli to 0.0.7
  recipes/scpred-cli/meta.yaml
Labels: please review & merge

#21640 Add Cath tools
  recipes/cath-tools/build.sh
  recipes/cath-tools/conda_build_config.yaml
  recipes/cath-tools/meta.yaml
Labels: please review & merge

#21763 update dicey v0.1.7
  recipes/dicey/build.sh
  recipes/dicey/meta.yaml
Labels: please review & merge

#21744 [Update] watchdog-wms - let conda handle javafx
  recipes/watchdog-wms/build.sh
  recipes/watchdog-wms/meta.yaml
Labels: bug, please review & merge, update build number

#21766 Update iucn_sim
  recipes/iucn_sim/meta.yaml
Labels: please review & merge

#21792 Update hivtrace to 0.5.0
  build-fail-blacklist
  recipes/hivtrace/meta.yaml
Labels: please review & merge

#21781 Add opentargets v3.1.16
  recipes/opentargets/meta.yaml
Labels: please review & merge

#21795 Update iucn_sim v2.0
  recipes/iucn_sim/meta.yaml
Labels: please review & merge

#21765 Updated minimum Python version required
  recipes/metaphlan/3.0.0.alpha/meta.yaml
  recipes/metaphlan/meta.yaml
Labels: please review & merge

#21764 Add quasildr recipe
  recipes/quasildr/meta.yaml
Labels: please review & merge

#21810 Update graphtyper to 2.4
  recipes/graphtyper/meta.yaml
Labels: please review & merge

#21778 Update MetaPhlAn2 package for GitHub migration
  recipes/metaphlan2/meta.yaml
Labels: please review & merge

#21777 Add tgsgapcloser recipes
  recipes/tgsgapcloser/build.sh
  recipes/tgsgapcloser/conda_build_config.yaml
  recipes/tgsgapcloser/meta.yaml
Labels: please review & merge

#21811 Add hicstuff
  recipes/hicstuff/LICENSE
  recipes/hicstuff/meta.yaml
Labels: please review & merge

#21837 Update MATAM
  recipes/matam/meta.yaml
Labels: please review & merge

#21816 Adding gcnvkernel from GATK 4.1.7.0
  recipes/gcnvkernel/build.sh
  recipes/gcnvkernel/meta.yaml
Labels: please review & merge

#21844 Add cthreepo
  recipes/cthreepo/meta.yaml
Labels: please review & merge

#21847 Relocate2 build4
  build-fail-blacklist
  recipes/relocate2/meta.yaml
Labels: please review & merge

#21773 update nebulizer: add script entry point
  recipes/nebulizer/meta.yaml
Labels: please review & merge

#21808 On branch master
  recipes/parent-map/meta.yaml
Labels: please review & merge

#21854 Update database url for PlasmidFinder 2.1
  recipes/plasmidfinder/download-db.sh
  recipes/plasmidfinder/meta.yaml
Labels: please review & merge

#21856 Add new variant phasing tool unfazed
  recipes/unfazed/meta.yaml
Labels: please review & merge

#21865 Update to pychopper v2.4.0
  recipes/pychopper/meta.yaml
Labels: please review & merge
