Repository bioconda/bioconda-recipes, pull requests merged in 2020-10, with the labels that each got.

#24616 Update Phylophlan package to v 3.0.1
  recipes/phylophlan/meta.yaml
Labels: please review & merge

#24531 Add eigenstratdatabasetools recipe
  recipes/eigenstratdatabasetools/build.sh
  recipes/eigenstratdatabasetools/meta.yaml
Labels: please review & merge

#24600 bioinfokit update to v0.9.8
  recipes/bioinfokit/meta.yaml
Labels: please review & merge

#24647 Update MBG to version 1.0.2
  recipes/mbg/meta.yaml
Labels: please review & merge

#24632 Update ngs-bits to version 2020_09
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#24604 Update openms to 2.6.0
  recipes/openms-meta/build.sh
  recipes/openms-meta/meta.yaml
Labels: please review & merge

#24655 Update gimmemotifs build
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#24583 Update funannotate v1.8.1 build -- add missing dependencies
  recipes/funannotate/meta.yaml
Labels: please review & merge

#24631 Update Pgcgap
  recipes/pgcgap/meta.yaml
Labels: please review & merge, update build number

#24480 Update seqscreen
  recipes/seqscreen/meta.yaml
  recipes/seqscreen/run_test.sh
Labels: please review & merge

#24667 latest release with faster calculations and doi link
  recipes/popgen-entropy/meta.yaml
Labels: please review & merge

#24429 New recipe PM4NGS
  recipes/pm4ngs/meta.yaml
Labels: please review & merge

#24405 Add MMULT
  recipes/mmult/build.sh
  recipes/mmult/meta.yaml
Labels: please review & merge

#24703 Add r-kernsmooth to dupRadar recipe
  recipes/bioconductor-dupradar/meta.yaml
Labels: please review & merge

#24696 Update to version 0.4.0
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#24691 Update GTDBTk 1.3.0 req FastANI to 1.32
  recipes/gtdbtk/meta.yaml
Labels: please review & merge

#23990 initial commit of seqiolib
  recipes/seqiolib/meta.yaml
Labels: please review & merge

#24724 Add --RefVCF option to the recipe
  recipes/verifybamid2/meta.yaml
  recipes/verifybamid2/verifybamid2.sh
Labels: please review & merge

#24728 Update Flapjack to 1.20.10.07
  recipes/flapjack/meta.yaml
Labels: new version

#24738 Update ganon to version 0.3.2
  recipes/ganon/meta.yaml
Labels: please review & merge

#24225 Update Tigmint to 1.2.1
  recipes/tigmint/meta.yaml
Labels: please review & merge

#24745 update raxml-ng to 1.0.1. switch source to github source zip
  recipes/raxml-ng/meta.yaml
Labels: please review & merge

#24744 Update meta.yaml
  recipes/find_differential_primers/meta.yaml
Labels: please review & merge

#24739 Update mosdepth to 0.3.1.
  recipes/mosdepth/conda_build_config.yaml
  recipes/mosdepth/meta.yaml
Labels: please review & merge

#24694 update url location of scnic
  recipes/scnic/meta.yaml
Labels: please review & merge

#24742 Add raptor recipe
  recipes/raptor/build.sh
  recipes/raptor/meta.yaml
Labels: please review & merge

#24777 Update gromacs to 2020.4
  recipes/gromacs/2020/meta.yaml
Labels: please review & merge

#24756 Update meta.yaml
  recipes/find_differential_primers/meta.yaml
Labels: please review & merge

#24649 Add recipe: ncbi-vdb-py
  recipes/ncbi-vdb-py/meta.yaml
  recipes/ncbi-vdb-py/run_test.py
  recipes/ncbi-vdb-py/vdb-py.patch
Labels: please review & merge

#24794 Update JBrowse to 1.16.10
  recipes/jbrowse/meta.yaml
Labels: please review & merge

#24800 Update: Fixed dependency version conflicts
  recipes/intervene/meta.yaml
Labels: please review & merge

#24793 Update MetaPhlAn 3.0.4
  recipes/metaphlan/meta.yaml
Labels: please review & merge

#24789 Update raptor to 1.0.1
  recipes/raptor/meta.yaml
Labels: please review & merge

#24767 Update scpred-cli
  recipes/scpred-cli/meta.yaml
Labels: please review & merge

#24792 Add AbNumber first release
  recipes/abnumber/meta.yaml
Labels: please review & merge

#24803 Add orfipy
  recipes/orfipy/meta.yaml
Labels: please review & merge

#24782 Add CPgeneProfiler
  recipes/cpgeneprofiler/meta.yaml
Labels: please review & merge

#24733 Add ChromImpute 1.0.3
  recipes/chromimpute/ChromImpute.sh
  recipes/chromimpute/build.sh
  recipes/chromimpute/meta.yaml
Labels: please review & merge

#24813 Update SeqAn3 to 3.0.2
  recipes/seqan3/bioconda.patch
  recipes/seqan3/build.sh
  recipes/seqan3/meta.yaml
Labels: please review & merge

#24461 Add - recipe for open-cravat 2.1.2
  recipes/open-cravat/LICENSE
  recipes/open-cravat/meta.yaml
  recipes/open-cravat/post-link.sh
Labels: please review & merge

#24735 Add papaa package bioconda recipe
  recipes/papaa/build.sh
  recipes/papaa/meta.yaml
Labels: please review & merge

#20761 Adding new package scepia
  recipes/scepia/meta.yaml
Labels: please review & merge

#22908 Add vsclust
  recipes/vsclust/build.sh
  recipes/vsclust/meta.yaml
Labels: please review & merge

#23996 Add samwell
  recipes/samwell/do_not_require_cython.patch
  recipes/samwell/meta.yaml
Labels: please review & merge

#24046 Add `pyhalcyon` recepi
  recipes/pyhalcyon/meta.yaml
  recipes/pyhalcyon/patch
Labels: please review & merge

#24063 Update conda recipe for Toil
  recipes/toil/meta.yaml
Labels: please review & merge

#24116 add recipe for gofasta
  recipes/gofasta/meta.yaml
Labels: please review & merge

#24163 Update constax with path fixes.
  recipes/constax/build.sh
  recipes/constax/meta.yaml
Labels: please review & merge

#24258 Add gargammel slim
  recipes/gargammel-slim/0001-gargammel-Makefile-keep-basic.patch
  recipes/gargammel-slim/0002-gargammel-src-Makefile-change-CXXFLAGS-and-LDFLAGS.patch
  recipes/gargammel-slim/0003-libgab-gzstream-Makefile-use-CXXFLAGS-and-LDFLAGS.patch
  recipes/gargammel-slim/0004-libgab-Makefile-removed-CXX.patch
  recipes/gargammel-slim/0005-libgab-ReconsReferenceBAM-OSX.patch
  recipes/gargammel-slim/build.sh
  recipes/gargammel-slim/meta.yaml
Labels: please review & merge

#24194 idemux recipe
  recipes/idemux/meta.yaml
Labels: please review & merge

#24260 Update Gargammel recipe
  recipes/gargammel/0001-gargammel-Makefile-nobamtools.patch
  recipes/gargammel/0002-gargammel-src-Makefile-change-CXXFLAGS-and-LDFLAGS.patch
  recipes/gargammel/0003-libgab-gzstream-Makefile-use-CXXFLAGS-and-LDFLAGS.patch
  recipes/gargammel/0004-libgab-Makefile-removed-CXX.patch
  recipes/gargammel/0005-libgab-ReconsReferenceBAM-OSX.patch
  recipes/gargammel/build.sh
  recipes/gargammel/meta.yaml
Labels: please review & merge

#24839 Updated description and tests in a Phigaro recipe
  recipes/phigaro/meta.yaml
Labels: please review & merge

#24584 Add recipe for lukasa
  recipes/lukasa/build.sh
  recipes/lukasa/meta.yaml
Labels: please review & merge

#24436 Add pORFast 0.8
  recipes/porfast/build.sh
  recipes/porfast/meta.yaml
Labels: please review & merge

#24715 Update TreeSAPP to include vsearch and update RAxML-NG dependency
  recipes/treesapp/meta.yaml
Labels: please review & merge

#24392 Blast 2.10.1 - try to add rpsbproc for OSX
  recipes/blast/build.sh
  recipes/blast/meta.yaml
  recipes/blast/normbase.patch
Labels: please review & merge

#24847 Add r-viscorvar
  recipes/r-viscorvar/build.sh
  recipes/r-viscorvar/meta.yaml
Labels: please review & merge

#24850 Update to 0.2.1
  recipes/hiline/conda_build_config.yaml
  recipes/hiline/meta.yaml
Labels: please review & merge

#24849 Bump kraken2 to 2.1.0
  recipes/kraken2/meta.yaml
Labels: please review & merge

#24804 Add md-cogent v7.0.0 recipe
  recipes/md-cogent/meta.yaml
Labels: please review & merge

#24861 Update CONSTAX to v2.0.3
  recipes/constax/build.sh
  recipes/constax/meta.yaml
Labels: please review & merge

#23911 Add fanc recipe
  recipes/fanc/meta.yaml
Labels: please review & merge

#24820 Add ggCaller
  recipes/ggcaller/meta.yaml
Labels: please review & merge

#24874 Update Jasmine to v1.0.8
  recipes/jasminesv/build.sh
  recipes/jasminesv/meta.yaml
Labels: please review & merge

#24740 Add bolt-lmm 2.3.4
  recipes/bolt-lmm/build.sh
  recipes/bolt-lmm/meta.yaml
Labels: please review & merge

#24873 Add gunc recipe
  recipes/gunc/meta.yaml
Labels: please review & merge

#24848 Update: Fix versioning info in Segway recipe
  recipes/segway/meta.yaml
Labels: please review & merge

#23004 add metapi
  recipes/metapi/meta.yaml
Labels: please review & merge

#24882 Update HiTaC to v1.3
  recipes/hitac/meta.yaml
Labels: please review & merge

#24881 Update - cellsnp-lite update homepage
  recipes/cellsnp-lite/meta.yaml
Labels: please review & merge

#24802 Update slivar recipe to include pslivar
  recipes/slivar/build.sh
  recipes/slivar/meta.yaml
Labels: please review & merge

#24883 Unblacklist cassiopee
  build-fail-blacklist
  recipes/cassiopee/build.sh
  recipes/cassiopee/meta.yaml
Labels: please review & merge

#24884 Fix missing in elector dependencies
  recipes/elector/meta.yaml
Labels: please review & merge

#24734 Patch for recipe "checkm-genome": enable build from local database
  recipes/checkm-genome/meta.yaml
  recipes/checkm-genome/post-link.sh
Labels: please review & merge

#24889 Add Ancestry_HMM-S
  recipes/ancestry_hmm-s/build.sh
  recipes/ancestry_hmm-s/meta.yaml
Labels: please review & merge

#24886 Add pbmpi recipe
  recipes/phylobayes-mpi/build.sh
  recipes/phylobayes-mpi/meta.yaml
Labels: please review & merge

#24838 Add SnakeLines tool
  recipes/snakelines/build.sh
  recipes/snakelines/meta.yaml
Labels: please review & merge

#24753 Add BURST aligner as a recipe to bioconda channel.
  recipes/burst/build.sh
  recipes/burst/meta.yaml
  recipes/burst/run_test.sh
Labels: please review & merge

#24902 update wbuild version
  recipes/drop/meta.yaml
Labels: please review & merge

#24909 Bump r-acidbase and r-acidgenerics
  recipes/r-acidbase/meta.yaml
  recipes/r-acidgenerics/meta.yaml
Labels: please review & merge

#24899 Update DamageProfiler to v1.1
  recipes/damageprofiler/damageprofiler.py
  recipes/damageprofiler/meta.yaml
Labels: please review & merge

#24915 Add ccmetagen
  recipes/ccmetagen/meta.yaml
Labels: please review & merge

#24924 Update Bumbershoot to 3.0.20290
  recipes/bumbershoot/meta.yaml
Labels: please review & merge

#24913 Build pygtftk for osx
  recipes/pygtftk/meta.yaml
  recipes/pygtftk/run_test.sh
Labels: please review & merge

#24946 Add CliqueSNV
  recipes/cliquesnv/build.sh
  recipes/cliquesnv/cliquesnv.py
  recipes/cliquesnv/meta.yaml
Labels: please review & merge

#24954 Bump GMAP
  recipes/gmap/meta.yaml
Labels: please review & merge

#24960 Update (to fix) adapterremovalfixprefix
  recipes/adapterremovalfixprefix/AdapterRemovalFixPrefix.py
  recipes/adapterremovalfixprefix/meta.yaml
Labels: please review & merge

#24950 Add kb-python package
  recipes/kb-python/meta.yaml
Labels: please review & merge

#24843 Add PILER-CR
  recipes/piler-cr/build.sh
  recipes/piler-cr/meta.yaml
Labels: please review & merge

#24966 Update Bumbershoot to 3.0.295 bfe5db0
  recipes/bumbershoot/meta.yaml
Labels: please review & merge

#24975 Update meta.yaml
  recipes/crispritz/meta.yaml
Labels: please review & merge

#24982 Update hail to v0.2.58
  recipes/hail/meta.yaml
Labels: please review & merge

#24967 cellprofiler-core v4.0.6 (for CellProfiler 4 eventually)
  recipes/cellprofiler-core/LICENSE
  recipes/cellprofiler-core/meta.yaml
Labels: please review & merge

#24991 Update metaeuk to 3-8dc7e0b
  recipes/metaeuk/build.sh
  recipes/metaeuk/meta.yaml
Labels: please review & merge

#24989 Update `pyrodigal` recipe to `v0.3.0`
  recipes/pyrodigal/meta.yaml
Labels: please review & merge

#24997 Update xmatchview to 1.2.4
  recipes/xmatchview/meta.yaml
Labels: please review & merge

#25007 Add libmaus2
  recipes/libmaus2/build.sh
  recipes/libmaus2/meta.yaml
  recipes/libmaus2/patch
Labels: please review & merge

#25015 Add SCRAMble recipe
  recipes/scramble/build.sh
  recipes/scramble/meta.yaml
  recipes/scramble/run_test.sh
  recipes/scramble/scramble.sh
Labels: please review & merge

#9119 Adding phyx
  recipes/phyx/build.sh
  recipes/phyx/meta.yaml
Labels: please review & merge

#25047 Update hmftools-cobalt to v1.10
  recipes/hmftools-cobalt/meta.yaml
Labels: please review & merge

#25042 Add rustynuc recipe
  recipes/rustynuc/build.sh
  recipes/rustynuc/meta.yaml
Labels: please review & merge

#25044 update Mykrobe build
  recipes/mykrobe/meta.yaml
Labels: please review & merge, update build number

#25035 Add savvy package
  recipes/savvy/build.sh
  recipes/savvy/meta.yaml
  recipes/savvy/patches/0001-Quick-fix-for-hts_hdr-destruction-bug.patch
  recipes/savvy/patches/0002-Quick-fix-for-hts-rec-destruction-bug.patch
  recipes/savvy/patches/0003-Fixes-s1r-bug-in-last-leaf-node.patch
  recipes/savvy/patches/0004-Patch-CMakeLists-for-conda-build.patch
Labels: please review & merge

#25048 Add recipe for crisprme
  recipes/crisprme/build.sh
  recipes/crisprme/meta.yaml
Labels: please review & merge

#25025 Update recipe with new module version (0.6.2)
  recipes/perl-metabolomics-fragment-annotation/meta.yaml
Labels: new version, please review & merge

#25022 Update zga
  recipes/zga/meta.yaml
Labels: please review & merge

#25051 Update flair, Add kernel tree
  recipes/flair/meta.yaml
  recipes/kerneltree/meta.yaml
Labels: please review & merge

#24930 Add recipe for moments
  recipes/moments/build.sh
  recipes/moments/meta.yaml
Labels: please review & merge

#25003 New perl-sort-key recipe
  recipes/perl-sort-key/LICENSE.txt
  recipes/perl-sort-key/build.sh
  recipes/perl-sort-key/meta.yaml
Labels: help wanted, please review & merge

#25068 Add sibeliaz recipe
  recipes/sibeliaz/build.sh
  recipes/sibeliaz/meta.yaml
  recipes/sibeliaz/sibeliaz.patch
Labels: please review & merge

#25070 Add new perl-fast recipe
  recipes/perl-fast/LICENSE
  recipes/perl-fast/build.sh
  recipes/perl-fast/meta.yaml
Labels: please review & merge

#25081 Patch Savvy cxx11 ABI
  recipes/savvy/build.sh
  recipes/savvy/meta.yaml
Labels: please review & merge

#25083 Build for all versions of Python 3.
  recipes/moments/meta.yaml
Labels: please review & merge

#25092 Update savvy to 1.3.0
  recipes/savvy/meta.yaml
  recipes/savvy/patches/0001-Quick-fix-for-hts_hdr-destruction-bug.patch
  recipes/savvy/patches/0001-patch-cmakelists-for-conda-build.patch
  recipes/savvy/patches/0002-Quick-fix-for-hts-rec-destruction-bug.patch
  recipes/savvy/patches/0003-Fixes-s1r-bug-in-last-leaf-node.patch
Labels: please review & merge

#25098 update seqkit to 0.14.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#25089 add coreutils to avoid error in containers
  recipes/edta/meta.yaml
Labels: please review & merge

#25097 Update cd-hit-auxtools
  recipes/cd-hit-auxtools/meta.yaml
Labels: please review & merge

#25102 Update ganon to 0.3.3
  recipes/ganon/meta.yaml
Labels: please review & merge

#25101 update taxonkit to 0.6.1
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#25106 update csvtk to 0.21.0
  recipes/csvtk/meta.yaml
Labels: please review & merge

#25073 add coolbox recipe
  recipes/coolbox/meta.yaml
Labels: please review & merge

#25109 Update Jalview to 2.11.1.3
  recipes/jalview/meta.yaml
Labels: please review & merge
