Repository bioconda/bioconda-recipes, pull requests merged in 2020-03, with the labels that each got.

#20640 Add recipe for Perl module YAML::PP.
  recipes/perl-yaml-pp/0.021/build.sh
  recipes/perl-yaml-pp/0.021/meta.yaml
Labels: please review & merge

#20638 nanovar-1.3.1 fix
  recipes/nanovar/meta.yaml
Labels: please review & merge

#20660 Svaba - build issue
  recipes/svaba/build.sh
  recipes/svaba/meta.yaml
Labels: please review & merge

#20642 add sketchy recipe
  recipes/sketchy/build.sh
  recipes/sketchy/meta.yaml
Labels: MacOS related, help wanted

#20669 Update igv
  recipes/igv/build.sh
  recipes/igv/meta.yaml
Labels: please review & merge

#20519 initial commit for entropy recipe with yaml and sh file
  recipes/popgen-entropy/build.sh
  recipes/popgen-entropy/meta.yaml
Labels: please review & merge

#20570 Megalodon 1.0
  recipes/megalodon/meta.yaml
Labels: please review & merge

#20691 add gaas toolkit recipe
  recipes/gaas/build.sh
  recipes/gaas/meta.yaml
Labels: please review & merge

#20651 Updated GRIDSS recipe to reflect GRIDSS API
  recipes/gridss/build.sh
  recipes/gridss/gridss
  recipes/gridss/gridss.py
  recipes/gridss/gridss_java_entrypoint
  recipes/gridss/gridss_r_script
  recipes/gridss/meta.yaml
Labels: please review & merge

#20709 Specify python version to >=3.4, needed for modules that otherwise get placed in python2.7 lib
  recipes/isonclust/meta.yaml
Labels: please review & merge

#20725 Curl is missing for running updateTaxonomy.sh.
  recipes/krona/meta.yaml
Labels: please review & merge

#20730 Update tximeta to version 1.4.3
  recipes/bioconductor-tximeta/meta.yaml
Labels: please review & merge

#20726 Garnett cli
  recipes/garnett-cli/build.sh
  recipes/garnett-cli/meta.yaml
Labels: please review & merge, update build number

#20605 fix cffi dep version for sourmash
  recipes/sourmash/meta.yaml
Labels: please review & merge

#20728 v 5.0.3 and added entry_points, description fields
  recipes/influx_si/meta.yaml
Labels: please review & merge

#20742 Bump fastq-screen to 0.14.0
  recipes/fastq-screen/meta.yaml
Labels: please review & merge

#20331 Add kcounter
  recipes/kcounter/build.sh
  recipes/kcounter/meta.yaml
Labels: please review & merge

#20754 update mosdepth to 0.2.9
  recipes/mosdepth/meta.yaml
Labels: please review & merge

#20753 Add taxonomy
  recipes/taxonomy/LICENSE
  recipes/taxonomy/build.sh
  recipes/taxonomy/meta.yaml
Labels: please review & merge

#20747 Add taxopy
  recipes/taxopy/meta.yaml
Labels: please review & merge

#20760 Update download-db.sh
  recipes/vibrant/download-db.sh
  recipes/vibrant/meta.yaml
Labels: please review & merge

#20743 Update pycoqc
  recipes/pycoqc/meta.yaml
Labels: please review & merge

#20657 Fixed openmpi version of ray to 3.1.3
  recipes/ray/meta.yaml
Labels: please review & merge

#20776 Bump flextaxd
  recipes/flextaxd/meta.yaml
Labels: please review & merge

#20783 add peaksql recipe
  recipes/peaksql/meta.yaml
Labels: please review & merge

#20805 update stacks to 2.52
  recipes/stacks/meta.yaml
Labels: please review & merge

#20798 Psass
  recipes/psass/build.sh
  recipes/psass/meta.yaml
Labels: please review & merge

#20803 add recipe for svim-asm
  recipes/svim-asm/meta.yaml
Labels: please review & merge

#20739 Add hail
  recipes/hail/build.sh
  recipes/hail/meta.yaml
Labels: please review & merge

#20806 GGD Update
  recipes/ggd/meta.yaml
Labels: new version, please review & merge

#20801 Gotree v0.4.0
  recipes/gotree/build.sh
  recipes/gotree/meta.yaml
Labels: please review & merge

#20795 Garnett cli
  recipes/garnett-cli/meta.yaml
Labels: please review & merge, update build number

#20723 Build NGLess directly by first building GHC
  recipes/ngless/build.sh
  recipes/ngless/meta.yaml
Labels: please review & merge

#20824 upgrade pretextmap to version 0.1.2
  recipes/pretextmap/meta.yaml
Labels: please review & merge

#20797 Pyomero upload
  recipes/pyomero-upload/meta.yaml
Labels: please review & merge

#20099 Percolator fix for tandem2pin, msgf2pin, add tests to recipe
  recipes/percolator/build.sh
  recipes/percolator/meta.yaml
Labels: please review & merge

#20822 cgat-apps update cgatcore
  recipes/cgat-apps/meta.yaml
Labels: please review & merge

#20836 Add missing scripts in hisat2
  recipes/hisat2/build.sh
  recipes/hisat2/meta.yaml
Labels: please review & merge

#20838 Add recipe for pybiomart
  recipes/pybiomart/meta.yaml
Labels: please review & merge

#20839 Set GTDB-Tk hmmer version to 3.1b2
  recipes/gtdbtk/meta.yaml
Labels: please review & merge

#20807 Add mpa server
  recipes/mpa-server/build.sh
  recipes/mpa-server/meta.yaml
  recipes/mpa-server/mpa-server.py
Labels: please review & merge

#20845 update ganon version 0.2.1
  recipes/ganon/meta.yaml
Labels: please review & merge

#20850 Update mpa server
  recipes/mpa-server/meta.yaml
  recipes/mpa-server/mpa-server.py
Labels: please review & merge

#20866 shovill 1.1.0 (do not use autobump)
  recipes/shovill/meta.yaml
Labels: please review & merge

#20870 STAR-Fusion not compatible with samtools 1.10
  recipes/star-fusion/meta.yaml
Labels: please review & merge

#20784 Add recipe for gNALI
  recipes/gnali/meta.yaml
Labels: please review & merge

#20880 Update MSGF+ to get latest unimod including TMTpro
  recipes/msgf_plus/meta.yaml
Labels: please review & merge

#20865 Add phylorank 0.0.43
  recipes/phylorank/LICENSE.txt
  recipes/phylorank/meta.yaml
Labels: please review & merge

#20867 Update biolib - fix python version
  recipes/biolib/meta.yaml
Labels: please review & merge

#20903 update transabyss recipe
  recipes/transabyss/LICENSE
  recipes/transabyss/meta.yaml
Labels: please review & merge

#20904 GATK4, add R dependencies in host
  recipes/gatk4/meta.yaml
Labels: please review & merge

#20913 fix blobtools recipe
  recipes/blobtools/build.sh
  recipes/blobtools/meta.yaml
Labels: please review & merge

#20863 Remove retry_decorator, in conda-forge now
  recipes/retry_decorator/meta.yaml
Labels: please review & merge

#20969 PHATE v1.0.4
  recipes/phate/meta.yaml
Labels: please review & merge

#20859 Update iqtree
  recipes/iqtree/0001-PATCH-macos-10.9.patch
  recipes/iqtree/build.sh
  recipes/iqtree/conda_build_config.yaml
  recipes/iqtree/meta.yaml
Labels: please review & merge

#20986 Snakemake 5.11.2
  recipes/snakemake/meta.yaml
Labels: please review & merge

#20985 Macrel 040
  recipes/macrel/meta.yaml
Labels: please review & merge

#21000 Upgraded iVar to 1.1-beta (1.1_beta)
  recipes/ivar/meta.yaml
Labels: please review & merge

#20990 compiling with x64bit support for large genome sizes
  recipes/mummer/build.sh
  recipes/mummer/meta.yaml
Labels: please review & merge

#20999 Fix PureCN issues
  recipes/bioconductor-purecn/build.sh
  recipes/bioconductor-purecn/meta.yaml
Labels: please review & merge

#20998 faqcs: add R version requirement
  recipes/faqcs/build.sh
  recipes/faqcs/meta.yaml
Labels: please review & merge

#21009 add minipolish
  recipes/minipolish/meta.yaml
Labels: please review & merge

#21001 Add TideHunter
  recipes/tidehunter/build.sh
  recipes/tidehunter/meta.yaml
Labels: please review & merge

#21014 update TideHunter
  recipes/tidehunter/build.sh
  recipes/tidehunter/meta.yaml
Labels: please review & merge

#20997 Add sensv
  recipes/sensv/build.sh
  recipes/sensv/meta.yaml
Labels: please review & merge

#20973 Add EukRep
  recipes/eukrep/LICENSE.txt
  recipes/eukrep/meta.yaml
Labels: please review & merge

#21017 Bump antismash to 5.1.2
  recipes/antismash/meta.yaml
Labels: please review & merge

#21031 update prophane to V4.0.5
  recipes/prophane/meta.yaml
Labels: please review & merge

#21036 Disable certain SIMD features for kalign3.
  recipes/kalign3/configure.patch
  recipes/kalign3/meta.yaml
Labels: bug, please review & merge

#21019 Add singlecellnet
  recipes/r-singlecellnet/meta.yaml
Labels: please review & merge

#21042 Daligner update
  recipes/daligner/build.sh
  recipes/daligner/meta.yaml
Labels: please review & merge

#21047 Add r-loomr
  recipes/r-loomr/meta.yaml
Labels: please review & merge

#21046 Add lamassemble
  recipes/lamassemble/meta.yaml
Labels: please review & merge

#21080 Add binlorry
  recipes/binlorry/meta.yaml
Labels: please review & merge

#21107 Update mpa 3.4
  recipes/mpa-server/build.sh
  recipes/mpa-server/meta.yaml
  recipes/mpa-server/mpa-server.py
Labels: please review & merge

#21094 Build rust-bio-tools for macOS
  recipes/rust-bio-tools/meta.yaml
Labels: MacOS related, please review & merge

#21100 New build of HyPhy 2.5.8
  recipes/hyphy/meta.yaml
Labels: bug, please review & merge

#21098 update ppanggolin 1.1.72 recipe
  recipes/ppanggolin/meta.yaml
Labels: please review & merge

#21119 Add recipe for LAST 1047
  recipes/last/meta.yaml
Labels: please review & merge

#21097 Added new recipe for CMSeq
  recipes/cmseq/meta.yaml
Labels: please review & merge

#21072 add new recipes for itolapi
  recipes/itolapi/meta.yaml
Labels: please review & merge

#21081 r-stitch: update to v1.6.3
  recipes/r-stitch/meta.yaml
Labels: please review & merge

#21133 Add recipe for LAST 1060
  recipes/last/meta.yaml
Labels: please review & merge

#15994 Bump IgBLAST to 1.15.0
  recipes/igblast/build.sh
  recipes/igblast/conda_build_config.yaml
  recipes/igblast/igblastn.sh
  recipes/igblast/meta.yaml
  recipes/igblast/shared_vdb.patch
Labels: please review & merge

#21138 Medaka: dont use mkl on MacOS
  recipes/medaka/meta.yaml
Labels: please review & merge

#21127 HiLine 0.0.1
  recipes/hiline/meta.yaml
Labels: please review & merge

#21129 Add crispector
  recipes/crispector/meta.yaml
Labels: please review & merge

#21175 deepvariant: 0.10.0 requires p36, adjust pinnings
  recipes/deepvariant/meta.yaml
Labels: please review & merge

#21179 Update and add dependency for pgx-variant-tools.
  recipes/pgx-variant-tools/meta.yaml
Labels: please review & merge

#21189 Hg color fix
  recipes/hg-color/build.sh
  recipes/hg-color/meta.yaml
Labels: please review & merge

#21188 Bump to version 1.12.2
  recipes/bioconductor-mspurity/meta.yaml
Labels: please review & merge

#21184 samsum v0.1.1 build recipe
  recipes/samsum/meta.yaml
Labels: please review & merge

#21194 Update rnaquast to 2.0.1
  recipes/rnaquast/meta.yaml
Labels: please review & merge

#21197 update svim to version 1.3.1 and fix matplotlib dependency
  recipes/svim/build.sh
  recipes/svim/meta.yaml
Labels: new version

#21032 Metaphlan3
  recipes/metaphlan/meta.yaml
Labels: please review & merge

#21212 sixgill: restrict to py2
  recipes/sixgill/meta.yaml
Labels: please review & merge
