Repository bioconda/bioconda-recipes, pull requests merged in 2020-09, with the labels that each got.

#24171 coverm: Update to 0.5.0.
  recipes/coverm/meta.yaml
Labels: please review & merge

#24170 galah: Update to 0.2.0.
  recipes/galah/meta.yaml
Labels: please review & merge

#24178 Update MMseqs2 to version 12-113e3
  recipes/mmseqs2/meta.yaml
Labels: please review & merge

#24179 Update plass to 4-687d7
  recipes/plass/meta.yaml
Labels: please review & merge

#24175 Update Cmip try to add MacOS compatibility
  recipes/cmip/meta.yaml
Labels: please review & merge

#24166 Updated edirect to version 13.8
  recipes/entrez-direct/meta.yaml
Labels: new version, please review & merge

#23483 Add recipe sherpas
  recipes/sherpas/build.sh
  recipes/sherpas/meta.yaml
Labels: please review & merge

#24195 Update Cmip : Modify post-link.sh to correctly show a message after installation
  recipes/cmip/meta.yaml
  recipes/cmip/post-link.sh
Labels: please review & merge

#24111 Update r-stitch to 1.6.5
  recipes/r-stitch/meta.yaml
Labels: please review & merge

#24196 Update MBG to 1.0.1
  recipes/mbg/meta.yaml
Labels: please review & merge

#24145 [ci skip] Update sniffles to 1.0.12a
  recipes/sniffles/meta.yaml
Labels: please review & merge

#24223 Flye 2.8.1
  recipes/flye/meta.yaml
Labels: please review & merge

#24062 Update MALT to v0.5.0
  recipes/malt/build.sh
  recipes/malt/meta.yaml
Labels: please review & merge

#24252 Update meta.yaml for Trim Galore v0.6.6
  recipes/trim-galore/meta.yaml
Labels: please review & merge

#24256 Fix CheckV requirements
  recipes/checkv/meta.yaml
Labels: please review & merge

#24251 recipe fix
  recipes/flye/meta.yaml
Labels: please review & merge

#24233 Add Flippyr to bioconda
  recipes/flippyr/meta.yaml
Labels: please review & merge

#24207 Update star-fusion to v1.9.1
  recipes/star-fusion/meta.yaml
Labels: please review & merge

#24217 Update hiline to 0.1
  recipes/hiline/0001-Do-not-fetch-hyperscan-via-git.patch
  recipes/hiline/0002-Use-more-general-compiler-detection.patch
  recipes/hiline/0003-Disambiguate-sequence-struct-type.patch
  recipes/hiline/0004-hyperline-cmake-build_wrapper.sh.patch
  recipes/hiline/conda_build_config.yaml
  recipes/hiline/meta.yaml
Labels: please review & merge

#24242 Bump inStrain to 1.3.4
  recipes/instrain/meta.yaml
Labels: please review & merge

#24219 Update secapr
  recipes/secapr/meta.yaml
Labels: please review & merge

#24187 Add sidr
  recipes/sidr/meta.yaml
Labels: please review & merge

#24231 add HaMiP
  recipes/hamip/meta.yaml
Labels: please review & merge

#24268 TIDDIT: fix TIDDIT executable.
  recipes/tiddit/build.sh
  recipes/tiddit/meta.yaml
Labels: please review & merge

#24271 Update hmftools-sage: add R package dependencies
  recipes/hmftools-sage/meta.yaml
Labels: please review & merge

#24272 Update hmftools-cobalt: add R package dependency
  recipes/hmftools-cobalt/meta.yaml
Labels: please review & merge

#24261 Update ganon to version 0.3.0
  recipes/ganon/build.sh
  recipes/ganon/meta.yaml
Labels: please review & merge

#24249 Add FastMLST v0.0.4
  recipes/fastmlst/meta.yaml
Labels: please review & merge

#24224 Update post-link.sh
  recipes/cmip/post-link.sh
Labels: please review & merge

#24283 Update hmftools-sage: Add xorg-libxt as dependency of hmftools-sage
  recipes/hmftools-sage/meta.yaml
Labels: please review & merge

#24284 TIDDIT: fix location of the TIDDIT binary that TIDDIT.py looks for.
  recipes/tiddit/TIDDIT.py.patch
  recipes/tiddit/meta.yaml
Labels: please review & merge

#24286 Add new recipe for Phigaro.
  recipes/phigaro/LICENSE.md
  recipes/phigaro/meta.yaml
  recipes/phigaro/post-link.sh
Labels: please review & merge

#24291 Update biopython.convert: Add missing pbr dependency
  recipes/biopython.convert/meta.yaml
Labels: please review & merge

#24278 Update old dependencies with new ones
  recipes/treesapp/meta.yaml
Labels: please review & merge

#24293 Update artic-tools
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#24303 Update collect-columns: new version
  recipes/collect-columns/meta.yaml
Labels: please review & merge

#24070 Coinfinder update recipe to include osx
  recipes/coinfinder/meta.yaml
Labels: please review & merge

#24327 Update vardict/vardict-java to 1.8.1.
  recipes/vardict-java/meta.yaml
  recipes/vardict/meta.yaml
Labels: please review & merge

#24328 Add NiemaDS
  recipes/niemads/meta.yaml
Labels: please review & merge

#24319 Update Infernal to version 1.1.3
  recipes/infernal/build.sh
  recipes/infernal/meta.yaml
Labels: help wanted

#24334 Add TreeCluster
  recipes/treecluster/meta.yaml
Labels: please review & merge

#24336 Update hmftools-purple: add R package dependencies + circos
  recipes/hmftools-purple/PURPLE.sh
  recipes/hmftools-purple/meta.yaml
Labels: please review & merge

#24332 HAPHPIPE v1.0.2
  recipes/haphpipe/meta.yaml
Labels: please review & merge

#24314 Update ISMapper - Pin BioPython version
  recipes/ismapper/meta.yaml
Labels: please review & merge

#24318 Updated cmseq to 1.0.2
  recipes/cmseq/meta.yaml
Labels: please review & merge

#24337 Update hmftools-linx
  recipes/hmftools-linx/linx.sh
  recipes/hmftools-linx/meta.yaml
Labels: please review & merge

#24321 Update tRNAscan-SE to version 2.0.6
  recipes/trnascan-se/meta.yaml
Labels: help wanted, please review & merge

#24344 Update gromacs_py
  recipes/gromacs_py/meta.yaml
Labels: please review & merge

#24349 Update pronto to v2.2.4
  recipes/pronto/meta.yaml
Labels: please review & merge

#24290 Update SISTR 1.0.2
  recipes/sistr_cmd/1.0.2/meta.yaml
Labels: please review & merge

#24262 Ngless v1.2.0 macosx build
  build-fail-blacklist
  recipes/ngless/build.sh
  recipes/ngless/meta.yaml
Labels: please review & merge

#24379 Add badread
  recipes/badread/meta.yaml
Labels: please review & merge

#24247 Add CONSENT a self long read corrector v2.1
  recipes/consent/CONSENT-correct.patch
  recipes/consent/CONSENT-polish.patch
  recipes/consent/build.sh
  recipes/consent/meta.yaml
Labels: please review & merge

#24359 Hydra
  recipes/hydra-multi/build.sh
  recipes/hydra-multi/meta.yaml
Labels: please review & merge

#24389 Update ganon to 0.3.1
  recipes/ganon/meta.yaml
Labels: please review & merge

#24304 Add NECAT
  recipes/necat/build.sh
  recipes/necat/meta.yaml
  recipes/necat/src_asm_pm_asmpm.mk.patch
  recipes/necat/src_consensus_main.mk.patch
  recipes/necat/src_ctg_cns_main.mk.patch
  recipes/necat/src_ctgpm_ctgpm.mk.patch
  recipes/necat/src_ctgpm_fix_can_info.mk.patch
  recipes/necat/src_ctgpm_split_ctgs.mk.patch
  recipes/necat/src_extract_sequences_extract_sequences.mk.patch
  recipes/necat/src_fsa_assemble.mk.patch
  recipes/necat/src_fsa_bridge.mk.patch
  recipes/necat/src_fsa_filter.mk.patch
  recipes/necat/src_fsa_fsa.mk.patch
  recipes/necat/src_fsa_rd_extract.mk.patch
  recipes/necat/src_fsa_rd_stat.mk.patch
  recipes/necat/src_fsa_rd_tools.mk.patch
  recipes/necat/src_makedb_main.mk.patch
  recipes/necat/src_pairwise_mapping_main.mk.patch
  recipes/necat/src_partition_candidates_main.mk.patch
  recipes/necat/src_partition_m4_main.mk.patch
  recipes/necat/src_pm4_main.mk.patch
  recipes/necat/src_pm_one_volume_main.mk.patch
  recipes/necat/src_preprocess_raw_reads_main.mk.patch
  recipes/necat/src_reference_mapping_main.mk.patch
  recipes/necat/src_reference_mapping_rm_one_vol_main.mk.patch
  recipes/necat/src_renumber_sequences_main.mk.patch
  recipes/necat/src_reorder_cns_reads_main.mk.patch
  recipes/necat/src_sequence_length_stats_main.mk.patch
  recipes/necat/src_split_long_reads_main.mk.patch
  recipes/necat/src_test_main.mk.patch
  recipes/necat/src_trim_bases_accurate0_largest_cover_range.mk.patch
  recipes/necat/src_trim_bases_accurate0_pm4.mk.patch
  recipes/necat/src_trim_bases_accurate0_trim_bases.mk.patch
  recipes/necat/src_trim_bases_accurate_largest_cover_range.mk.patch
  recipes/necat/src_trim_bases_accurate_pm4.mk.patch
  recipes/necat/src_trim_bases_accurate_trim_bases.mk.patch
  recipes/necat/src_trim_bases_extract_trimmerd_reads.mk.patch
  recipes/necat/src_trim_bases_largest_cover_range.mk.patch
  recipes/necat/src_trim_bases_order_results.mk.patch
  recipes/necat/src_trim_bases_pm4.mk.patch
  recipes/necat/src_trim_bases_trim_bases.mk.patch
  recipes/necat/tool_main.mk.patch
Labels: please review & merge

#24385 Try to update to RepeatMasker 4.1.0 using new configure ... again ...
  recipes/repeatmasker/RepeatMaskerConfig.pm
  recipes/repeatmasker/build.sh
  recipes/repeatmasker/meta.yaml
  recipes/repeatmasker/patch1
Labels: please review & merge

#24422 bump build of bwameth and lofreq
  recipes/bwameth/meta.yaml
  recipes/lofreq/meta.yaml
Labels: please review & merge

#24394 Update bioconductor-purecn to 1.18.1.
  recipes/bioconductor-purecn/meta.yaml
Labels: please review & merge

#24360 add a bash script that invokes biotransformer
  recipes/biotransformer/biotransformer.py
  recipes/biotransformer/build.sh
  recipes/biotransformer/meta.yaml
Labels: please review & merge

#24424 Update dependencies of scvelo v0.2.2
  recipes/scvelo/meta.yaml
Labels: please review & merge

#24418 add scvi-tools
  recipes/scvi-tools/meta.yaml
Labels: please review & merge

#24452 snakemake: fix pulp>=2.0 dependency
  recipes/snakemake/meta.yaml
Labels: please review & merge

#24425 Updated entrez-direct to version 13.9, please merge
  recipes/entrez-direct/meta.yaml
Labels: please review & merge

#24410 Update HAPHPIPE recipe for v1.0.3
  recipes/haphpipe/meta.yaml
Labels: please review & merge

#24358 Macrel can build on OSX now
  recipes/macrel/meta.yaml
Labels: please review & merge

#24313 Update pgcgap to v1.0.19 build 1
  recipes/pgcgap/meta.yaml
Labels: please review & merge

#24478 Update Galaxy-ML
  recipes/galaxy-ml/meta.yaml
Labels: please review & merge

#24458 update meta.yaml -- hemdag in lowercase in github link
  recipes/r-hemdag/meta.yaml
Labels: please review & merge

#24476 Add perbase tool
  recipes/perbase/build.sh
  recipes/perbase/meta.yaml
Labels: please review & merge

#24459 Update Bactopia recipe dependencies
  recipes/bactopia/meta.yaml
Labels: please review & merge

#24503 Update PacBio `pbcopper` version 1.8.0
  recipes/pbcopper/meta.yaml
Labels: please review & merge

#24397 Update scapp
  recipes/scapp/meta.yaml
Labels: please review & merge

#24277 add plaster
  recipes/pan-plaster/build.sh
  recipes/pan-plaster/meta.yaml
  recipes/pan-plaster/run_test.sh
Labels: please review & merge

#24348 Add meskit recipe
  recipes/bioconductor-meskit/build.sh
  recipes/bioconductor-meskit/meta.yaml
Labels: please review & merge

#24541 Update drop 0.9.2
  recipes/drop/meta.yaml
Labels: please review & merge

#24534 Update perbase to v0.2.1
  recipes/perbase/build.sh
  recipes/perbase/meta.yaml
Labels: please review & merge

#24463 Update scvi-tools
  recipes/scvi-tools/meta.yaml
Labels: please review & merge

#24548 Update for Jalview 2.11.1.2 release
  recipes/jalview/meta.yaml
Labels: please review & merge

#24545 Add itolparser
  recipes/itolparser/LICENSE
  recipes/itolparser/meta.yaml
Labels: please review & merge

#24537 Hmmer2
  build-fail-blacklist
  recipes/hmmer/2.3.2/build.sh
  recipes/hmmer/2.3.2/meta.yaml
Labels: please review & merge

#24547 Add minirmd
  recipes/minirmd/build.sh
  recipes/minirmd/meta.yaml
Labels: please review & merge

#24574 Update dedup to 0.12.7
  recipes/dedup/dedup.py
  recipes/dedup/meta.yaml
Labels: please review & merge

#24568 Update amptk v1.5.1 -- add missing dependencies
  recipes/amptk/meta.yaml
Labels: please review & merge

#24585 Update Bugfix/remove perbase deps
  recipes/perbase/meta.yaml
Labels: please review & merge

#24595 Add psm validation tool using ion fragmentation comparision
  recipes/psm_fragments/meta.yaml
Labels: please review & merge

#24556 Update scvi-tools
  recipes/scvi-tools/meta.yaml
Labels: please review & merge

#24525 add chromeister
  recipes/chromeister/build.sh
  recipes/chromeister/meta.yaml
Labels: please review & merge
