Repository bioconda/bioconda-recipes, pull requests merged in 2020-05, with the labels that each got.

#21875 CircMiner recipe added to bioconda
  recipes/circminer/build.sh
  recipes/circminer/meta.yaml
Labels: please review & merge

#21862 Add gvcf2coverage
  recipes/gvcf2coverage/build.sh
  recipes/gvcf2coverage/meta.yaml
Labels: please review & merge

#21872 Update: add missing perl modules for evidencemodeler
  recipes/evidencemodeler/meta.yaml
Labels: please review & merge

#21877 Add varda2-client.
  recipes/varda2-client/meta.yaml
Labels: please review & merge

#21876 Add pygvcf2coverage
  recipes/pygvcf2coverage/meta.yaml
Labels: please review & merge

#21868 Scmap cli
  recipes/scmap-cli/meta.yaml
Labels: please review & merge

#21853 Upgrade HOMER to 4.11
  recipes/homer/meta.yaml
Labels: please review & merge

#21712 Update rdptools from release 2.0.2 to 2.0.3
  recipes/rdptools/build.sh
  recipes/rdptools/meta.yaml
Labels: please review & merge

#21867 Add vcf2variants
  recipes/vcf2variants/meta.yaml
Labels: please review & merge

#21821 add TransposonPSI
  recipes/transposonpsi/build.sh
  recipes/transposonpsi/meta.yaml
  recipes/transposonpsi/run_test.sh
Labels: please review & merge

#21878 Update cnv_facets
  recipes/cnv_facets/meta.yaml
Labels: please review & merge

#21851 Add pangolin tool
  recipes/pangolin/meta.yaml
Labels: please review & merge

#21881 Add start-asap 1.0.0
  recipes/start-asap/build.sh
  recipes/start-asap/meta.yaml
  recipes/start-asap/run_test.sh
Labels: please review & merge

#21824 Clipcontext new release
  recipes/clipcontext/meta.yaml
Labels: please review & merge

#21886 Update cthreepo
  recipes/cthreepo/meta.yaml
Labels: please review & merge

#21899 Add GenomeTreeTk
  recipes/genometreetk/meta.yaml
Labels: please review & merge

#21903 Update to rust-ncbitaxonomy 1.0.3
  recipes/rust-ncbitaxonomy/meta.yaml
Labels: please review & merge

#21906 Update varda2-client
  recipes/varda2-client/meta.yaml
Labels: please review & merge

#21575 Add CanSNPer2
  recipes/cansnper2/meta.yaml
Labels: WIP

#21910 [perl-fastx-reader] added new dependency Capture::Tiny and update to 0.90
  recipes/perl-fastx-reader/meta.yaml
Labels: please review & merge

#21929 Update Pangolin to v1.1.5
  recipes/pangolin/meta.yaml
Labels: please review & merge

#21948 Add bioconductor-sparsematrixstats recipe
  recipes/bioconductor-matrixgenerics/build.sh
  recipes/bioconductor-matrixgenerics/meta.yaml
  recipes/bioconductor-sparsematrixstats/build.sh
  recipes/bioconductor-sparsematrixstats/meta.yaml
Labels: please review & merge

#21951 Updated source_url for *PhlAn packages
  build-fail-blacklist
  recipes/export2graphlan/export2graphlan.py.patch
  recipes/export2graphlan/meta.yaml
  recipes/graphlan/build.sh
  recipes/graphlan/meta.yaml
  recipes/hclust2/meta.yaml
Labels: please review & merge

#21947 Update: OpenMS (third-party, build type, share)
  recipes/openms-meta/build.sh
  recipes/openms-meta/meta.yaml
  recipes/openms-meta/package_libopenms.sh
Labels: please review & merge

#21943 Add plncpro
  recipes/plncpro/LICENSE
  recipes/plncpro/meta.yaml
Labels: please review & merge

#21940 Update vibrant recipe with pinned scikit-learn version
  recipes/vibrant/build.sh
  recipes/vibrant/download-db.sh
  recipes/vibrant/meta.yaml
  recipes/vibrant/path.patch
  recipes/vibrant/post-link.sh
Labels: please review & merge

#21930 Add dadaist2
  recipes/dadaist2/build.sh
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#21784 Add EukCC
  recipes/eukcc/meta.yaml
Labels: please review & merge

#21980 update snpEff; include data/ sub-dir
  recipes/snpeff/4.5covid19/build.sh
  recipes/snpeff/4.5covid19/meta.yaml
Labels: please review & merge

#21981 Update new 0.3.1 version of smallgenomeutilities
  recipes/smallgenomeutilities/0.3.1/meta.yaml
Labels: please review & merge

#21996 Update dedup to 0.12.6
  recipes/dedup/dedup.py
  recipes/dedup/meta.yaml
Labels: please review & merge

#21997 Add recipe for bio-ting
  recipes/bio-ting/meta.yaml
Labels: please review & merge

#21999 Add Docking py
  recipes/docking_py/meta.yaml
  recipes/docking_py/run_test.sh
Labels: please review & merge

#22021 Update pangolin to v1.1.11
  recipes/pangolin/meta.yaml
Labels: please review & merge

#22023 Update Bandage
  recipes/bandage/meta.yaml
Labels: please review & merge

#22014 Add CompareM 0.1.1
  recipes/comparem/LICENSE
  recipes/comparem/meta.yaml
Labels: please review & merge

#22012 Add simplesam to bioconda
  recipes/simplesam/meta.yaml
Labels: please review & merge

#22013 Update to fix conflicts on osx of GenMap 1.2.0
  recipes/genmap/meta.yaml
Labels: please review & merge

#22032 Add PrimedLAMP
  recipes/primedlamp/meta.yaml
Labels: please review & merge

#22029 update kraken2 2.0.8_beta -> 2.0.9_beta
  recipes/kraken2/meta.yaml
Labels: please review & merge

#22037 Update StringTie to 2.1.2
  recipes/stringtie/meta.yaml
Labels: please review & merge

#22030 Add Virchip
  recipes/virchip/meta.yaml
Labels: please review & merge

#22039 add perl-if
  recipes/perl-if/build.sh
  recipes/perl-if/meta.yaml
Labels: please review & merge

#22022 Add reCOGnizer
  recipes/recognizer/meta.yaml
Labels: please review & merge

#22043 Update TideHunter v1.3.0
  recipes/tidehunter/build.sh
  recipes/tidehunter/meta.yaml
Labels: please review & merge

#22058 proteinortho bump to v6.0.16
  recipes/proteinortho/meta.yaml
Labels: please review & merge

#22086 Update strling 0.2.1
  recipes/strling/meta.yaml
Labels: please review & merge

#21835 Adding svtk
  recipes/svtk/LICENSE
  recipes/svtk/meta.yaml
  recipes/svtk/svtk.patch
Labels: help wanted, please review & merge

#22091 Bumping varfish-annotator to v0.12.
  recipes/varfish-annotator-cli/meta.yaml
Labels: please review & merge

#22092 Update r-qorts
  build-fail-blacklist
  recipes/r-qorts/build.sh
  recipes/r-qorts/meta.yaml
Labels: please review & merge

#22048 Add recipe: gFACs
  recipes/perl-gfacs/build.sh
  recipes/perl-gfacs/meta.yaml
Labels: please review & merge

#22010 Add stringtie version 1.3.3b
  recipes/stringtie/1.3.3b/build.sh
  recipes/stringtie/1.3.3b/meta.yaml
Labels: please review & merge

#22088 Update reCOGnizer to 1.2.2
  recipes/recognizer/meta.yaml
Labels: please review & merge

#22120 Update pangolin to v1.1.13
  recipes/pangolin/meta.yaml
Labels: please review & merge

#22111 Update Rebaler
  recipes/rebaler/meta.yaml
Labels: please review & merge

#22125 Add CheckQC 3.6.1.
  recipes/checkqc/meta.yaml
Labels: please review & merge

#22127 Add SpacePHARER 1-56925d2
  recipes/spacepharer/build.sh
  recipes/spacepharer/meta.yaml
Labels: please review & merge

#22144 Add emptydrops
  recipes/emptydrops/meta.yaml
Labels: please review & merge

#22140 Add UPIMAPI
  recipes/upimapi/meta.yaml
Labels: please review & merge

#22145 Add pafpy
  recipes/pafpy/meta.yaml
Labels: please review & merge

#22038 Add cami-amber meta file
  recipes/cami-amber/meta.yaml
Labels: please review & merge

#22121 Add SAMPEI recipe
  recipes/sampei/meta.yaml
Labels: please review & merge

#22101 hicstuff - add deps
  recipes/hicstuff/meta.yaml
Labels: please review & merge

#22064 add pyrpipe
  recipes/pyrpipe/LICENSE
  recipes/pyrpipe/meta.yaml
Labels: please review & merge

#22153 Update graphtyper to 2.5.1
  recipes/graphtyper/meta.yaml
Labels: please review & merge

#22154 Update cgatcore
  recipes/cgatcore/meta.yaml
Labels: please review & merge

#22044 Update abPOA to v1.0.2
  recipes/abpoa/build.sh
  recipes/abpoa/meta.yaml
Labels: please review & merge

#22158 Remove r-stampp, after it has been migrated to conda-forge.
  recipes/r-stampp/build.sh
  recipes/r-stampp/meta.yaml
Labels: please review & merge

#22168 Update: DIAMOND version and add pytest
  recipes/checkv/meta.yaml
Labels: please review & merge

#22187 Add recipe for cBioPortalData from Bioconductor
  recipes/bioconductor-cbioportaldata/build.sh
  recipes/bioconductor-cbioportaldata/meta.yaml
Labels: please review & merge

#22185 SanitizeMe recipe add awk and grep so biocontainer works
  recipes/sanitizeme/meta.yaml
Labels: please review & merge

#22114 Update bioconda/jalview to 2.11.1.0
  recipes/jalview/jalview.sh
  recipes/jalview/meta.yaml
Labels: please review & merge

#22087 Add ExpansionHunterDeNovo
  recipes/expansionhunterdenovo/build.sh
  recipes/expansionhunterdenovo/meta.yaml
Labels: please review & merge

#22135 Update QoRTs to 1.3.6
  recipes/qorts/build.sh
  recipes/qorts/meta.yaml
  recipes/qorts/qorts.py
Labels: please review & merge

#22215 Add scagaire
  recipes/scagaire/meta.yaml
Labels: please review & merge

#22222 Update CanSNPer dependencies
  recipes/cansnper/meta.yaml
Labels: please review & merge

#22216 update upimapi to 1.0.3
  recipes/upimapi/meta.yaml
Labels: please review & merge

#22045 Add gepard
  recipes/gepard/build.sh
  recipes/gepard/meta.yaml
  recipes/gepard/post-link.sh
Labels: please review & merge

#22231 Update PacBio `pbbam` to use new htslib 1.10
  recipes/pbbam/meta.yaml
Labels: please review & merge

#22220 Build mosdepth on OSX
  recipes/mosdepth/build.sh
  recipes/mosdepth/meta.yaml
Labels: please review & merge

#22221 Remove 1 package from blacklist
  build-fail-blacklist
Labels: please review & merge

#22270 Update: genomepy updated build for dependency
  recipes/genomepy/meta.yaml
Labels: please review & merge

#22280 Remove pytest from CheckV's dependencies
  recipes/checkv/meta.yaml
Labels: please review & merge

#22275 Update 0.4.0 to not use pandas >= 1
  recipes/staramr/0.4.0/meta.yaml
Labels: please review & merge

#22295 update Adpred
  recipes/adpred/meta.yaml
Labels: please review & merge

#22310 Add galru
  recipes/galru/meta.yaml
Labels: please review & merge

#22298 Add recipe for tool stark
  recipes/stark/build.sh
  recipes/stark/meta.yaml
Labels: please review & merge

#22318 update test for AGAT to work with version 0.3.0
  recipes/agat/meta.yaml
Labels: please review & merge

#22341 Add Recipe for Lorikeet
  recipes/lorikeet-genome/build.sh
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#22335 Update moabs to 1.3.9.3
  recipes/moabs/meta.yaml
Labels: please review & merge

#22331 Update plastid to 0.5.1
  build-fail-blacklist
  recipes/plastid/meta.yaml
Labels: please review & merge

#22348 Add im-pipelines
  recipes/im-pipelines/meta.yaml
Labels: please review & merge

#22354 Update Galru
  recipes/galru/meta.yaml
Labels: please review & merge

#22368 update ganon version 0.2.3
  recipes/ganon/meta.yaml
Labels: please review & merge

#22296 Update staramr 0.4.0 to really use pandas < 1
  recipes/staramr/0.4.0/meta.yaml
Labels: please review & merge

#22356 Update Hops to version 0.34
  recipes/hops/build.sh
  recipes/hops/hops.py
  recipes/hops/meta.yaml
Labels: please review & merge

#22382 Update GMAP to include zlib
  recipes/gmap/build.sh
  recipes/gmap/meta.yaml
Labels: please review & merge

#22379 Update svim to 1.4.0-1
  recipes/svim/meta.yaml
Labels: please review & merge

#22273 Update bellmans-gapc to source from upstream repo
  build-fail-blacklist
  recipes/bellmans-gapc/meta.yaml
Labels: please review & merge

#22406 Add trtools to bioconda
  recipes/trtools/meta.yaml
  recipes/trtools/run_test.sh
Labels: please review & merge

#22344 Add hypro recipe
  recipes/hypro/meta.yaml
Labels: please review & merge

#22398 Update Scpred-cli to 0.0.8
  recipes/scpred-cli/build.sh
  recipes/scpred-cli/meta.yaml
Labels: please review & merge
