Repository bioconda/bioconda-recipes, pull requests merged in 2020-06, with the labels that each got.

#22433 Update for htstream v1.3.0
  recipes/htstream/meta.yaml
Labels: please review & merge

#22441 Add Marvel, 0.2
  recipes/marvel/build.sh
  recipes/marvel/meta.yaml
Labels: please review & merge

#22445 Cell types analysis
  recipes/cell-types-analysis/meta.yaml
Labels: please review & merge

#22439 Add package contigtax (previously tango)
  recipes/contigtax/meta.yaml
  recipes/tango/meta.yaml
Labels: please review & merge

#22458 Add treerecs
  recipes/treerecs/build.sh
  recipes/treerecs/meta.yaml
Labels: please review & merge

#22455 Add pblat
  recipes/pblat/build.sh
  recipes/pblat/meta.yaml
Labels: please review & merge

#22453 Add vConTACT2
  recipes/vcontact2/meta.yaml
Labels: please review & merge

#22469 Update sra-tools 2.10.3 -> 2.10.7; restore GUID check (& create if not present)
  recipes/sra-tools/meta.yaml
  recipes/sra-tools/post-link.sh
  recipes/sra-tools/skip_config_interactive.diff
Labels: please review & merge

#22473 Update sra-tools; call "vdb-config --interactive" if post-link script is run from interactive terminal
  recipes/sra-tools/meta.yaml
  recipes/sra-tools/post-link.sh
Labels: please review & merge

#22482 Update rxdock recipe
  recipes/rxdock/build.sh
  recipes/rxdock/meta.yaml
  recipes/rxdock/rDock_fix_paths.patch
Labels: please review & merge

#22491 Update gsort version to 0.1.4
  recipes/gsort/meta.yaml
Labels: new version, please review & merge

#22495 Update Subread to 2.0.1
  recipes/subread/meta.yaml
Labels: please review & merge

#22493 Update rmats to 4.1.0
  recipes/rmats/LICENSE
  recipes/rmats/build.sh
  recipes/rmats/cc_cxx_env_var.patch
  recipes/rmats/linux.patch
  recipes/rmats/meta.yaml
Labels: please review & merge

#22516 Update Parsnp 1.5.0
  recipes/parsnp/build.sh
  recipes/parsnp/meta.yaml
  recipes/parsnp/run_test.sh
Labels: please review & merge

#22529 Update sequencetools to use new semi-automated releases
  build-fail-blacklist
  recipes/sequencetools/build.sh
  recipes/sequencetools/meta.yaml
Labels: please review & merge

#22526 Update: Adjust extra/identifiers and license of multiple recipes
  recipes/coinfinder/meta.yaml
  recipes/esimsa/meta.yaml
  recipes/gromacs/2018/meta.yaml
  recipes/gromacs/2019/meta.yaml
  recipes/gromacs/2020/meta.yaml
  recipes/msaprobs/meta.yaml
  recipes/plncpro/meta.yaml
  recipes/sexdeterrmine/meta.yaml
  recipes/srax/meta.yaml
Labels: please review & merge

#22521 Bump stringmeup to 0.1.1
  recipes/stringmeup/meta.yaml
Labels: please review & merge

#22524 Update plasmidid v1.6.0
  recipes/plasmidid/meta.yaml
Labels: please review & merge

#22545 Test bowtie2 OSX builds
  recipes/bowtie2/build.sh
  recipes/bowtie2/meta.yaml
Labels: please review & merge

#22547 Update ANGSD for rebuild against htslib1.10
  recipes/angsd/meta.yaml
Labels: please review & merge

#22548 Fix hisat2 on OSX
  recipes/hisat2/build.sh
  recipes/hisat2/meta.yaml
Labels: WIP

#22541 Update CircularMapper
  recipes/circularmapper/build.sh
  recipes/circularmapper/circulargenerator.py
  recipes/circularmapper/meta.yaml
  recipes/circularmapper/realignsamfile.py
Labels: please review & merge

#22561 3.0.0
  recipes/biobb_pmx/build.sh
  recipes/biobb_pmx/meta.yaml
Labels: please review & merge

#22565 Bump PMDTools for new Samtools/libdeflate version
  recipes/pmdtools/meta.yaml
Labels: please review & merge

#22555 Update virsorter to 2.0-alpha
  recipes/virsorter/build.sh
  recipes/virsorter/meta.yaml
Labels: please review & merge

#22078 Update Gimmemotifs build
  recipes/ananse/meta.yaml
  recipes/gimmemotifs/conda_build_config.yaml
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#22549 Update SpacePHARER to 2-fc5e668
  recipes/spacepharer/meta.yaml
Labels: please review & merge

#22546 Update plasmidid to 1.6.2
  recipes/plasmidid/meta.yaml
Labels: please review & merge

#22592 Update encyclopedia to 0.9.5
  recipes/encyclopedia/encyclopedia.py
  recipes/encyclopedia/meta.yaml
Labels: please review & merge

#22579 Add ctseq to bioconda
  recipes/ctseq/meta.yaml
Labels: please review & merge

#22602 Bbmap, add dependencies to work with compressed files
  recipes/bbmap/meta.yaml
Labels: please review & merge

#22587 Add variantbreak
  recipes/variantbreak/meta.yaml
Labels: please review & merge

#22573 Update Krona recipe to fix macOS installation
  recipes/krona/build.sh
  recipes/krona/meta.yaml
Labels: please review & merge

#22558 Update parsnp to have OpenMP support on MacOS
  recipes/parsnp/build.sh
  recipes/parsnp/meta.yaml
Labels: please review & merge

#22562 Add metabinkit
  recipes/metabinkit/build.sh
  recipes/metabinkit/meta.yaml
Labels: please review & merge

#22581 Update on VirSorter 2.0-alpha
  recipes/virsorter/meta.yaml
Labels: please review & merge

#22588 Update meme build to fix one of the included tools
  recipes/meme/build.sh
  recipes/meme/meta.yaml
Labels: please review & merge

#22537 Update Bumbershoot to 3.0.20163.6147e44
  build-fail-blacklist
  recipes/bumbershoot/meta.yaml
Labels: new version

#22633 Update mrsfast package to v3.4.2
  recipes/mrsfast/meta.yaml
Labels: please review & merge

#22636 Structtoolbox bump
  recipes/bioconductor-structtoolbox/meta.yaml
Labels: please review & merge

#22625 Update parsnp 1.5.0 (build 2)
  recipes/parsnp/build.sh
  recipes/parsnp/meta.yaml
Labels: please review & merge

#22644 Update calib to v0.3.4 with two execs
  recipes/calib/build.sh
  recipes/calib/meta.yaml
Labels: please review & merge

#22639 Update samplot to v1.0.14
  recipes/samplot/meta.yaml
Labels: please review & merge

#22638 Update bioconductor-FRASER from v1.0.0 to v1.0.1
  recipes/bioconductor-fraser/meta.yaml
Labels: please review & merge

#22647 Update parallel-fastq-dump
  recipes/parallel-fastq-dump/build.sh
  recipes/parallel-fastq-dump/meta.yaml
Labels: help wanted

#22613 Update bioconductor-phyloprofile
  recipes/bioconductor-phyloprofile/meta.yaml
Labels: please review & merge

#22650 Update pTrimmer to v1.3.2
  recipes/ptrimmer/meta.yaml
Labels: please review & merge

#22600 Add ANARCI
  recipes/anarci/meta.yaml
Labels: please review & merge

#22629 Add cdk-inchi-to-svg
  recipes/cdk-inchi-to-svg/build.sh
  recipes/cdk-inchi-to-svg/meta.yaml
  recipes/cdk-inchi-to-svg/run_test.sh
Labels: please review & merge

#22653 Remove r-transphylo after the move to conda-forge.
  recipes/r-transphylo/meta.yaml
Labels: please review & merge

#22662 Add PyTaxonKit
  recipes/pytaxonkit/meta.yaml
  recipes/pytaxonkit/run_test.sh
Labels: please review & merge

#22668 Virsorter 2.0-alpha update
  recipes/virsorter/meta.yaml
Labels: please review & merge

#22666 Remove r-shazam, it has moved to conda-forge.
  recipes/r-shazam/build.sh
  recipes/r-shazam/meta.yaml
Labels: please review & merge

#22672 Update genometreetk dependencies
  recipes/genometreetk/meta.yaml
Labels: please review & merge

#22675 Rebuild CMSIP 0.0.2.8
  recipes/cmsip/meta.yaml
Labels: please review & merge

#22673 Remove r-tigger, it moved to conda-forge.
  recipes/r-tigger/build.sh
  recipes/r-tigger/meta.yaml
Labels: please review & merge

#22663 Add recipe for chexalign
  recipes/chexalign/build.sh
  recipes/chexalign/chexalign.sh
  recipes/chexalign/meta.yaml
Labels: help wanted

#22687 Update parsnp 1.5.0
  recipes/parsnp/build.sh
  recipes/parsnp/meta.yaml
  recipes/parsnp/run_test.sh
Labels: please review & merge

#22688 Update sigmut
  recipes/sigmut/meta.yaml
Labels: please review & merge

#22686 Deleting_PrimedLAMP
  recipes/primedlamp/meta.yaml
Labels: please review & merge

#22679 r-dimsum initial commit
  recipes/r-dimsum/build.sh
  recipes/r-dimsum/meta.yaml
Labels: please review & merge

#22714 Update for new haphpipe version
  recipes/haphpipe/meta.yaml
Labels: please review & merge

#22731 Update ptrimmer v1.3.3
  recipes/ptrimmer/meta.yaml
Labels: please review & merge

#22729 Add LRez
  recipes/lrez/build.sh
  recipes/lrez/meta.yaml
Labels: please review & merge

#22752 Sampei - Updated version
  recipes/sampei/meta.yaml
Labels: please review & merge

#22698 Add recipe for sequnwinder
  recipes/sequnwinder/build.sh
  recipes/sequnwinder/meta.yaml
  recipes/sequnwinder/sequnwinder.sh
Labels: please review & merge

#22766 Bump stringmeup
  recipes/stringmeup/meta.yaml
Labels: please review & merge

#22754 bump rust-ncbitaxonomy to 1.0.5
  recipes/rust-ncbitaxonomy/build.sh
  recipes/rust-ncbitaxonomy/meta.yaml
Labels: please review & merge

#22710 Update GenMap to 1.3.0
  recipes/genmap/build.sh
  recipes/genmap/meta.yaml
Labels: new version, please review & merge

#22775 Update famsa to 1.6.1
  recipes/famsa/LICENSE
  recipes/famsa/build.sh
  recipes/famsa/fix-osx-vectorclass.patch
  recipes/famsa/fix_const_template.patch
  recipes/famsa/meta.yaml
Labels: please review & merge

#22744 Update razers3
  recipes/razers3/build.sh
  recipes/razers3/meta.yaml
Labels: please review & merge

#22764 gmap: single quote hardcoded path in perl scripts
  recipes/gmap/meta.yaml
  recipes/gmap/single_quote_paths.patch
Labels: please review & merge

#22777 Update blast 2.9.0 adding rpsbproc among blast tools - replace #21497
  recipes/blast/build.sh
  recipes/blast/meta.yaml
Labels: please review & merge

#22707 Update pgcgap to v1.0.18
  recipes/pgcgap/meta.yaml
Labels: new version

#22771 Add recipe for k8 dependency and update bwakit and minimap2 recipes
  recipes/bwakit/build.sh
  recipes/bwakit/meta.yaml
  recipes/k8/build.sh
  recipes/k8/meta.yaml
  recipes/minimap2/build.sh
  recipes/minimap2/meta.yaml
Labels: please review & merge

#22790 Update parsnp
  recipes/parsnp/meta.yaml
Labels: please review & merge

#22783 Update to VirSorter 2.0.beta
  recipes/virsorter/meta.yaml
Labels: please review & merge

#22745 Add recipe for atlas-data-import
  recipes/atlas-data-import/build.sh
  recipes/atlas-data-import/meta.yaml
Labels: please review & merge

#22774 Add gmgc-mapper
  recipes/gmgc-mapper/meta.yaml
Labels: please review & merge

#22779 Update RGI to 5.1.1
  recipes/rgi/meta.yaml
Labels: please review & merge

#22805 Update recipe for new version of mindthegap
  recipes/mindthegap/conda_build_config.yaml
  recipes/mindthegap/meta.yaml
Labels: please review & merge

#22797 aletsch
  recipes/aletsch/build.sh
  recipes/aletsch/meta.yaml
Labels: please review & merge

#22809 Update PanPhlAn recipe with new repo URL
  recipes/panphlan/1.2/meta.yaml
Labels: please review & merge

#22846 Update chemfp to 1.6
  recipes/chemfp/meta.yaml
Labels: please review & merge

#22850 Update trtools: Remove unncessary argparse dependency
  recipes/trtools/meta.yaml
Labels: please review & merge

#22852 remove old lumpyexpress.config from recipe
  recipes/lumpy-sv/build.sh
  recipes/lumpy-sv/lumpyexpress.config
  recipes/lumpy-sv/meta.yaml
Labels: please review & merge

#22858 Update xpressplot: matplotlib → matplotlib-base
  recipes/xpressplot/meta.yaml
Labels: please review & merge

#22863 Update wisestork: matplotlib → matplotlib-base
  recipes/wisestork/meta.yaml
Labels: please review & merge

#22862 Update wub: matplotlib → matplotlib-base
  recipes/wub/meta.yaml
Labels: please review & merge

#22860 Update xyalign: matplotlib → matplotlib-base
  recipes/xyalign/meta.yaml
Labels: please review & merge

#22821 Build gmap version 2019.02.26
  recipes/gmap/2019.02.26/build.sh
  recipes/gmap/2019.02.26/meta.yaml
Labels: please review & merge

#22838 Update cooler to 0.8.7
  recipes/cooler/build.sh
  recipes/cooler/meta.yaml
Labels: please review & merge

#22865 Update MetaPhlAn to version 3.0.1
  recipes/metaphlan/meta.yaml
Labels: please review & merge

#22839 Update cooler to 0.8.8
  recipes/cooler/meta.yaml
Labels: please review & merge

#22868 Lumpy
  recipes/lumpy-sv/build.sh
  recipes/lumpy-sv/meta.yaml
Labels: please review & merge

#22799 Add polystest
  recipes/polystest/build.sh
  recipes/polystest/meta.yaml
Labels: please review & merge

#22814 Add clipkit
  recipes/clipkit/meta.yaml
Labels: please review & merge

#22808 update bioconductor-phyloprofile to 1.2.6
  recipes/bioconductor-phyloprofile/meta.yaml
Labels: please review & merge

#22878 Update parsnp to version 1.5.1
  recipes/parsnp/meta.yaml
Labels: please review & merge

#22890 Add snakefmt 0.1.0
  recipes/snakefmt/meta.yaml
Labels: please review & merge

#22841 Update: Updating lorikeet-genome to v0.3.4
  recipes/lorikeet-genome/build.sh
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#22888 Update Bumbershoot to 3_0_20175
  recipes/bumbershoot/meta.yaml
Labels: please review & merge

#22896 Update Bumbershoot to 3_0_20178
  recipes/bumbershoot/meta.yaml
Labels: please review & merge

#22857 Update ngs-bits to version 2020_06
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#22892 new recipe bamkit
  recipes/bamkit/build.sh
  recipes/bamkit/meta.yaml
Labels: please review & merge

#22919 Update of bioconductor-org.Hs.eg.db to v3.11.4 from v3.11.1
  recipes/bioconductor-org.hs.eg.db/meta.yaml
  recipes/bioconductor-org.hs.eg.db/post-link.sh
Labels: please review & merge

#22921 Update of bioconductor-org.mm.eg.db from version 3.11.1 to version 3.11.4 to fix broken links
  recipes/bioconductor-org.mm.eg.db/meta.yaml
  recipes/bioconductor-org.mm.eg.db/post-link.sh
Labels: please review & merge

#22916 Add recipe for `pyrodigal` Python package
  recipes/pyrodigal/meta.yaml
Labels: please review & merge

#22897 Remove r-qtl2, it has been migrated to conda-forge.
  recipes/r-qtl2/build.sh
  recipes/r-qtl2/meta.yaml
Labels: please review & merge

#22937 updated sampei recipe to use version 0.0.8
  recipes/sampei/meta.yaml
Labels: please review & merge
