Repository bioconda/bioconda-recipes, pull requests merged in 2020-08, with the labels that each got.

#23437 Update cgatcore version 0.6.7
  recipes/cgatcore/meta.yaml
Labels: please review & merge

#23697 Update cellsnp-lite v0.3.1 to build 1
  recipes/cellsnp-lite/meta.yaml
Labels: please review & merge

#23689 Update jalview: enable maxMemory setting
  recipes/jalview/jalview.sh
  recipes/jalview/meta.yaml
Labels: please review & merge

#23684 Add PGDSpider 2.1.1.5
  recipes/pgdspider/PGDSpider2-cli.py
  recipes/pgdspider/PGDSpider2-gui.py
  recipes/pgdspider/build.sh
  recipes/pgdspider/meta.yaml
Labels: please review & merge

#23415 Add ragtag v1.0.0
  recipes/ragtag/LICENSE
  recipes/ragtag/meta.yaml
Labels: please review & merge

#23691 Add new recipe MetaPop
  recipes/metapop/build.sh
  recipes/metapop/meta.yaml
Labels: please review & merge

#23710 Use bgzip & tabix from htslib rather than the legacy tabix package
  recipes/biotradis/meta.yaml
  recipes/hint/meta.yaml
  recipes/pairtools/meta.yaml
  recipes/perl-vcftools-vcf/meta.yaml
  recipes/rsidx/meta.yaml
  recipes/surpyvor/meta.yaml
Labels: please review & merge

#23682 Update advntr to 1.4.0
  recipes/advntr/meta.yaml
Labels: please review & merge

#23731 Fix scanpy scripts pins
  recipes/scanpy-scripts/meta.yaml
Labels: please review & merge

#23730 Bumping Jannovar to v0.35
  recipes/jannovar-cli/meta.yaml
Labels: please review & merge

#23764 Update samplot to 1.0.16
  recipes/samplot/meta.yaml
Labels: please review & merge

#23759 Add MOSCA
  recipes/mosca/build.sh
  recipes/mosca/meta.yaml
Labels: please review & merge

#23782 NeatMS version upgrade
  recipes/neatms/meta.yaml
Labels: please review & merge

#23789 Update irissv openjdk requirement
  recipes/irissv/meta.yaml
Labels: please review & merge

#23777 Update taxsbp to version 1.0.0
  recipes/taxsbp/meta.yaml
Labels: please review & merge

#23796 Update SPAdes to 3.14.1
  recipes/spades/meta.yaml
Labels: please review & merge

#23792 Update chewBBACA to 2.5.1
  recipes/chewbbaca/meta.yaml
Labels: please review & merge

#23779 Add Pathracer recipe
  recipes/pathracer/0001-add-rt-lib-to-easel.patch
  recipes/pathracer/0001-change-verbosity.patch
  recipes/pathracer/0001-link-rt-for-static-jemalloc.patch
  recipes/pathracer/0002-add-missing-inittypes-header.patch
  recipes/pathracer/build.sh
  recipes/pathracer/meta.yaml
Labels: please review & merge

#23800 update merqury to v1.1
  recipes/merqury/meta.yaml
Labels: please review & merge

#23795 Add cluster_vcf_records recipe
  recipes/cluster_vcf_records/meta.yaml
Labels: please review & merge

#23720 update with biorxiv link
  recipes/popgen-entropy/meta.yaml
Labels: please review & merge

#23678 Parsnp 1.5.3
  recipes/parsnp/build.sh
  recipes/parsnp/meta.yaml
Labels: please review & merge

#23816 Update spoa to 3.4.0
  recipes/spoa/meta.yaml
Labels: please review & merge

#23807 Add varifier recipe
  recipes/varifier/meta.yaml
Labels: please review & merge

#23833 Update CellRank meta yaml
  recipes/cellrank/meta.yaml
Labels: please review & merge

#23830 add zga 0.0.7
  recipes/zga/meta.yaml
Labels: please review & merge

#23840 update cami-amber to 2.0.1
  recipes/cami-amber/meta.yaml
Labels: please review & merge

#23844 Fix Busco 4.1.2
  recipes/busco/meta.yaml
Labels: please review & merge

#23835 update cluster_vcf_records requirements
  recipes/cluster_vcf_records/meta.yaml
Labels: please review & merge, update build number

#23851 Add artic-tools
  recipes/artic-tools/build.sh
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#23854 Update samplot to 1.0.17
  recipes/samplot/meta.yaml
Labels: please review & merge

#23841 update cami-opal to 1.0.8.post0
  recipes/cami-opal/meta.yaml
Labels: please review & merge

#23858 Add recipe for f5c
  recipes/f5c/build.sh
  recipes/f5c/meta.yaml
Labels: please review & merge

#23825 Add isoquant recipe
  recipes/isoquant/build.sh
  recipes/isoquant/meta.yaml
Labels: please review & merge

#23874 Add mnnpy recipe
  recipes/mnnpy/meta.yaml
Labels: please review & merge

#23877 updated dxpy to 0.298.1
  recipes/dxpy/meta.yaml
Labels: new version, please review & merge

#23814 Add genomic_regions recipe
  recipes/genomic_regions/meta.yaml
Labels: please review & merge

#23881 Update artic-tools
  recipes/artic-tools/build.sh
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#23893 Update mnnpy: fix deps, cleanup
  recipes/mnnpy/0001-Fix-missing-forceobj-for-numba.jit.patch
  recipes/mnnpy/meta.yaml
Labels: please review & merge

#23901 Update jasminesv
  recipes/jasminesv/meta.yaml
Labels: please review & merge

#23910 Update augur 9.0.0 dependencies
  recipes/augur/meta.yaml
Labels: please review & merge

#23846 Adding bioconductor-apeglm as dependency to diffbind
  recipes/bioconductor-diffbind/meta.yaml
Labels: enhancement, please review & merge

#23887 Add dfast_qc recipe
  recipes/dfast_qc/build.sh
  recipes/dfast_qc/meta.yaml
Labels: please review & merge

#23922 update chexalign to v0.12
  recipes/chexalign/build.sh
  recipes/chexalign/chexalign.sh
  recipes/chexalign/meta.yaml
Labels: please review & merge

#23904 Adding dependencies to diffbind
  recipes/bioconductor-diffbind/meta.yaml
Labels: bug

#23952 Update jasminesv
  recipes/jasminesv/build.sh
  recipes/jasminesv/meta.yaml
Labels: please review & merge

#23942 Fix Orthofinder
  recipes/orthofinder/build.sh
  recipes/orthofinder/meta.yaml
Labels: please review & merge

#23947 upload recipe for pydownsampler
  recipes/pydownsampler/meta.yaml
Labels: please review & merge

#23957 new build of ShoRAH 1.99.2
  recipes/shorah/1.99.2/meta.yaml
Labels: please review & merge

#23930 Add constax package
  recipes/constax/build.sh
  recipes/constax/meta.yaml
  recipes/constax/run_test.sh
Labels: please review & merge

#23964 Update metaquantome
  recipes/metaquantome/meta.yaml
Labels: please review & merge

#23962 Update dfastqc. Fix broken recipe
  recipes/dfast_qc/build.sh
  recipes/dfast_qc/meta.yaml
Labels: please review & merge

#23974 Adding fonts-conda-ecosystem to diffbind to solve missing fonts
  recipes/bioconductor-diffbind/meta.yaml
Labels: bug

#23977 Update ragtag recipe for v1.0.1
  recipes/ragtag/meta.yaml
Labels: please review & merge

#23971 Add recipe for GRAFIMO
  recipes/grafimo/meta.yaml
Labels: please review & merge

#24003 add new recipe for paraclu
  recipes/paraclu/build.sh
  recipes/paraclu/meta.yaml
Labels: please review & merge

#24006 Update artic-tools
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#24010 Update - Patches for third party links used by Ariba
  recipes/ariba/meta.yaml
  recipes/ariba/pubmlst_getter.patch
  recipes/ariba/ref_genes_getter.patch
Labels: please review & merge

#24017 Update jbrowse to 1.16.9
  recipes/jbrowse/meta.yaml
Labels: please review & merge

#24025 Update artic-tools
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#23423 Add recipe for MBG
  recipes/mbg/build.sh
  recipes/mbg/meta.yaml
  recipes/mbg/version.patch
Labels: please review & merge

#23895 Adding standard link to the homer installation folder
  recipes/homer/build.sh
  recipes/homer/meta.yaml
Labels: enhancement, please review & merge

#23172 Update ont-tombo: rpy2 version pin
  build-fail-blacklist
  recipes/ont-tombo/meta.yaml
Labels: please review & merge

#24028 Update PretextMap, PretextGraph, PretextSnapshot
  recipes/pretextgraph/meta.yaml
  recipes/pretextmap/meta.yaml
  recipes/pretextsnapshot/conda_build_config.yaml
  recipes/pretextsnapshot/meta.yaml
Labels: please review & merge

#24048 Update artic-tools
  recipes/artic-tools/build.sh
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#24058 Update duplomap -> 0.9.4
  recipes/duplomap/meta.yaml
Labels: please review & merge

#24065 Fix inStrain requirements and add test commands
  recipes/instrain/meta.yaml
Labels: please review & merge

#24103 Update adam to 0.32.0
  recipes/adam/meta.yaml
Labels: please review & merge

#24104 Update cannoli to 0.10.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#24099 Update artic-tools
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#24107 Update meta.yaml
  recipes/crispritz/meta.yaml
Labels: please review & merge

#24105 Igblast parser
  recipes/igblast-parser/meta.yaml
Labels: please review & merge

#24117 Update CellRank
  recipes/cellrank/meta.yaml
Labels: please review & merge

#24130 Update VarDict-Java to 1.8.0.
  recipes/vardict-java/meta.yaml
Labels: please review & merge

#24120 Update HH-suite 3.3.0
  recipes/hhsuite/fmemopen-extern-c.patch
  recipes/hhsuite/meta.yaml
Labels: please review & merge

#24161 update platon dependency on diamond to version >=2.0.4
  recipes/platon/meta.yaml
Labels: please review & merge

#24153 Add CMIP recipe: CMIP - Classical Mollecular Interaction Potential
  recipes/cmip/build.sh
  recipes/cmip/meta.yaml
Labels: please review & merge

#24164 Update to gifrop v0.0.4
  recipes/gifrop/meta.yaml
Labels: please review & merge
