Repository bioconda/bioconda-recipes, pull requests merged in 2020-07, with the labels that each got.

#22843 Add recipe for jgoslin 1.1.2
  recipes/jgoslin/build.sh
  recipes/jgoslin/jgoslin.py
  recipes/jgoslin/meta.yaml
Labels: please review & merge

#22939 Update gtdbtk-1.2.0 to set tqdm>=4.31.0
  recipes/gtdbtk/meta.yaml
Labels: please review & merge

#22979 New recipie: isonclust2
  recipes/isonclust2/build.sh
  recipes/isonclust2/meta.yaml
Labels: please review & merge

#22976 Bumping varfish-annotator-cli to v0.13.
  recipes/varfish-annotator-cli/meta.yaml
Labels: please review & merge

#22977 Add mtglink
  recipes/mtglink/build.sh
  recipes/mtglink/meta.yaml
Labels: please review & merge

#22923 Update sra-tools (add missing curl dependency, rebuild hdf5)
  recipes/sra-tools/meta.yaml
Labels: please review & merge

#22940 Add SsuisSero
  recipes/ssuissero/build.sh
  recipes/ssuissero/meta.yaml
Labels: please review & merge

#22984 Add CellRank
  recipes/cellrank/meta.yaml
Labels: please review & merge

#22960 Add cyushuffle - a Cython wrapper for uShuffle
  recipes/cyushuffle/meta.yaml
Labels: please review & merge

#22981 Update sra-tools to 2.10.8
  recipes/sra-tools/meta.yaml
Labels: please review & merge

#22969 PR: Add NGSEP recipe
  recipes/ngsep/build.sh
  recipes/ngsep/meta.yaml
  recipes/ngsep/ngsep.py
Labels: please review & merge

#22932 add mimseq v0.2.5.1
  recipes/mimseq/meta.yaml
Labels: please review & merge

#22999 Update GraphAligner to version 1.0.12
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#23013 added samtools to meta
  recipes/breakdancer/meta.yaml
Labels: please review & merge

#22989 Update helperlibs to 0.2.1
  recipes/helperlibs/meta.yaml
Labels: please review & merge

#22922 add integron finder
  recipes/integron_finder/meta.yaml
Labels: please review & merge

#23032 Update - primedrpa updates
  recipes/primedrpa/meta.yaml
Labels: please review & merge

#22946 Update fsnviz to trigger rebuild
  recipes/fsnviz/meta.yaml
Labels: please review & merge

#23041 Update SeqKit to v0.13.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#23029 Update meryl to v1.0
  build-fail-blacklist
  recipes/meryl/build.sh
  recipes/meryl/meta.yaml
Labels: please review & merge

#23048 update atlas-data-import to 0.0.10
  recipes/atlas-data-import/meta.yaml
Labels: please review & merge

#23026 stacks kmer_filter returns wrong exit code
  recipes/stacks/kmer_exit.patch
  recipes/stacks/meta.yaml
Labels: please review & merge

#23059 Update hclust2 recipe
  recipes/hclust2/meta.yaml
Labels: please review & merge

#23060 Update wg-blimp to v0.9.6
  recipes/wg-blimp/meta.yaml
Labels: please review & merge

#23066 Add tbox-scan
  recipes/tbox-scan/build.sh
  recipes/tbox-scan/meta.yaml
Labels: please review & merge

#23065 Parsnp 1.5.2
  recipes/parsnp/meta.yaml
Labels: please review & merge

#23078 Add LDBlockShow v1.25
  recipes/ldblockshow/build.sh
  recipes/ldblockshow/meta.yaml
Labels: please review & merge

#23076 Update tbox-scan to 0.1.3
  recipes/tbox-scan/meta.yaml
Labels: please review & merge

#23058 add bmge-1.12
  recipes/bmge/LICENSE.txt
  recipes/bmge/build.sh
  recipes/bmge/meta.yaml
Labels: please review & merge

#23025 Update rnaQUAST to 2.1.0
  recipes/rnaquast/meta.yaml
Labels: please review & merge

#23011 Update GetOrganelle to 1.7.0 and update the meta.yaml
  recipes/getorganelle/meta.yaml
Labels: please review & merge

#22901 Update fastq-multx to version 1.4.0
  recipes/fastq-multx/build.sh
  recipes/fastq-multx/meta.yaml
Labels: please review & merge

#22935 Add irissv
  recipes/irissv/build.sh
  recipes/irissv/meta.yaml
Labels: please review & merge

#23089 seqkit-0.13.1
  recipes/seqkit/meta.yaml
Labels: please review & merge

#23090 Update GetOrganelle to 1.7.0 and Update meta.yaml
  recipes/getorganelle/meta.yaml
Labels: please review & merge

#23100 Add jasminesv
  recipes/jasminesv/build.sh
  recipes/jasminesv/meta.yaml
Labels: please review & merge

#23102 add bwa-mem2
  recipes/bwa-mem2/771c7692aeb857d5b9241a08bbd68f2c6be01811.patch
  recipes/bwa-mem2/Makefile.patch
  recipes/bwa-mem2/build.sh
  recipes/bwa-mem2/meta.yaml
Labels: please review & merge

#23107 Update percolator to version 3.5
  recipes/percolator/meta.yaml
Labels: please review & merge

#22856 Update yahmm: matplotlib → matplotlib-base
  build-fail-blacklist
  recipes/yahmm/meta.yaml
Labels: please review & merge

#23093 Mimseq update and ggplot2 version change
  recipes/mimseq/meta.yaml
Labels: please review & merge

#23110 Update lorikeet-genome to v0.3.5
  recipes/lorikeet-genome/build.sh
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#23108 Update Trtools
  recipes/trtools/meta.yaml
Labels: please review & merge

#23132 Update PGCGAP build number
  recipes/pgcgap/meta.yaml
Labels: please review & merge, update build number

#23156 Add CHISEL recipe
  recipes/chisel/meta.yaml
Labels: please review & merge

#23140 seqkit-0.13.2
  recipes/seqkit/meta.yaml
Labels: please review & merge

#23128 Add HpsuisSero
  recipes/hpsuissero/build.sh
  recipes/hpsuissero/meta.yaml
Labels: please review & merge

#23120 Update chexmix to 0.5
  recipes/chexmix/build.sh
  recipes/chexmix/chexmix.sh
  recipes/chexmix/meta.yaml
Labels: please review & merge

#23136 Add cellrank-krylov
  recipes/cellrank/meta.yaml
Labels: please review & merge

#23081 Add scapp - first attempt
  recipes/scapp/meta.yaml
Labels: please review & merge

#23142 ThermoRawFileParser: Add symlinks without .sh extension and lowercase for name
  recipes/thermorawfileparser/meta.yaml
Labels: please review & merge

#23196 Update spectrum_utils version 0.3.4
  recipes/spectrum_utils/meta.yaml
Labels: please review & merge

#23201 Add GeFaST
  recipes/gefast/build.sh
  recipes/gefast/meta.yaml
  recipes/gefast/patch
Labels: please review & merge

#23203 Update hapcut2 to 1.3.2
  recipes/hapcut2/flags.patch
  recipes/hapcut2/meta.yaml
Labels: please review & merge

#23169 Fix breakdancer st
  recipes/breakdancer/build.sh
  recipes/breakdancer/meta.yaml
  recipes/breakdancer/samtools.patch
Labels: please review & merge

#23195 Update chisel version with correction on setup
  recipes/chisel/meta.yaml
Labels: please review & merge

#23213 Update dsh-bio to 1.3.4
  recipes/dsh-bio/meta.yaml
Labels: new version, please review & merge

#23189 Add drop dependencies
  recipes/r-tmae/build.sh
  recipes/r-tmae/meta.yaml
  recipes/wbuild/meta.yaml
Labels: please review & merge

#23215 Add recipe for panphlan 3.0
  recipes/panphlan/1.3/build.sh
  recipes/panphlan/1.3/meta.yaml
  recipes/panphlan/license.txt
  recipes/panphlan/meta.yaml
Labels: please review & merge

#23129 Add drop, wbuild, and r-tmae
  recipes/drop/meta.yaml
Labels: please review & merge

#23217 Add DuploMap
  recipes/duplomap/build.sh
  recipes/duplomap/meta.yaml
Labels: please review & merge

#23214 Update PepQuery
  recipes/pepquery/meta.yaml
Labels: please review & merge

#23247 Update Chorus
  recipes/chorus2/meta.yaml
Labels: please review & merge

#23235 genometreetk missing dependencies
  recipes/genometreetk/meta.yaml
Labels: please review & merge

#23191 Centrifuge no-eval
  recipes/centrifuge-core/build.sh
  recipes/centrifuge-core/conda_build_config.yaml
  recipes/centrifuge-core/meta.yaml
Labels: please review & merge

#23243 Add smaca
  recipes/smaca/meta.yaml
Labels: please review & merge

#23251 Update recipe VerifyBamID2 - cmdline parsing logic to accept default usage on github page
  recipes/verifybamid2/meta.yaml
  recipes/verifybamid2/verifybamid2.sh
Labels: please review & merge

#23267 Add hifiasm-0.9 (new package, fixed receipt)
  recipes/hifiasm/build.sh
  recipes/hifiasm/meta.yaml
Labels: please review & merge

#23253 Update pretextmap, pretextsnapshot, pretextgraph
  recipes/pretextgraph/meta.yaml
  recipes/pretextmap/meta.yaml
  recipes/pretextsnapshot/meta.yaml
Labels: please review & merge

#23258 Update recipe for new version of MTG-Link v1.0.1
  recipes/mtglink/meta.yaml
Labels: please review & merge

#23074 Add Merqury v1.0
  recipes/merqury/activate.fish
  recipes/merqury/activate.sh
  recipes/merqury/build.sh
  recipes/merqury/deactivate.fish
  recipes/merqury/deactivate.sh
  recipes/merqury/meta.yaml
  recipes/merqury/post-link.sh
  recipes/merqury/run_test.sh
Labels: please review & merge

#23224 Add yak-0.1 (new package)
  recipes/yak/build.sh
  recipes/yak/meta.yaml
Labels: please review & merge

#23254 Update hiline
  recipes/hiline/meta.yaml
Labels: please review & merge

#23226 Add DNA Features Viewer
  recipes/dna_features_viewer/LICENSE
  recipes/dna_features_viewer/meta.yaml
Labels: please review & merge

#23193 Update VISPR to newer version (0.4.16)
  recipes/vispr/meta.yaml
Labels: please review & merge

#23286 Updated rappas to 1.21
  recipes/rappas/meta.yaml
Labels: please review & merge

#23278 Update - Add sdust to minimap2
  recipes/minimap2/build.sh
  recipes/minimap2/meta.yaml
Labels: please review & merge

#23292 Update drop to 0.9.1
  recipes/drop/meta.yaml
Labels: please review & merge

#23293 Add new recipe for cellsnp-lite
  recipes/cellsnp-lite/LICENSE
  recipes/cellsnp-lite/build.sh
  recipes/cellsnp-lite/meta.yaml
Labels: please review & merge

#23302 Add pileuppy
  recipes/pileuppy/meta.yaml
Labels: please review & merge

#23303 Add opentargets-urlzsource recipe
  recipes/opentargets-urlzsource/meta.yaml
Labels: please review & merge

#23299 Rebuild Sepp on osx
  build-fail-blacklist
  recipes/sepp/build.sh
  recipes/sepp/meta.yaml
  recipes/sepp/nodeps.setup.py.patch
Labels: please review & merge

#22998 ShoRAH 1.99.1
  recipes/shorah/1.99.1/meta.yaml
Labels: please review & merge

#23225 Update UniFrac to 0.20.0.
  recipes/unifrac/build.sh
  recipes/unifrac/meta.yaml
Labels: please review & merge

#23309 [bcalm] Enable macos build
  recipes/bcalm/meta.yaml
Labels: please review & merge

#23298 Update trinity to 2.11.0
  recipes/trinity/makefile.patch
  recipes/trinity/meta.yaml
Labels: please review & merge

#23318 Update lorikeet-genome to v0.3.6
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#23285 Add SeqScreen
  recipes/seqscreen/build.sh
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#23301 Update pauvre to 0.2.2.
  recipes/pauvre/meta.yaml
Labels: please review & merge

#23313 Add opentargets validator
  recipes/opentargets-validator/meta.yaml
Labels: please review & merge

#23327 Rebuild augustus on osx
  recipes/augustus/build.sh
  recipes/augustus/meta.yaml
  recipes/augustus/patches/bam2hints.makefile.patch
  recipes/augustus/patches/bam2wig.makefile.patch
  recipes/augustus/patches/filterBam.makefile.patch
  recipes/augustus/patches/filterBam.src.makefile.patch
  recipes/augustus/patches/filterBam.src.makefile.patch.osx
  recipes/augustus/patches/homGeneMapping.src.makefile.patch
Labels: please review & merge

#23281 Add catch_chimera
  recipes/catch_chimera/build.sh
  recipes/catch_chimera/meta.yaml
  recipes/catch_chimera/run_test.sh
Labels: please review & merge

#23333 Patch bwa-mem2 find executable
  recipes/bwa-mem2/find_executable.patch
  recipes/bwa-mem2/meta.yaml
Labels: please review & merge

#23176 Add MS²PIP recipe
  recipes/ms2pip/meta.yaml
Labels: please review & merge

#23344 Add metatree-0.0.1
  recipes/metatree/meta.yaml
Labels: please review & merge

#23342 Seqscreen: blast version update
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#23348 add galaxyxml
  recipes/galaxyxml/meta.yaml
Labels: please review & merge

#20874 Updated blast+ to 2.10.1 please merge soon
  recipes/blast/build.sh
  recipes/blast/configurellvm.patch
  recipes/blast/meta.yaml
  recipes/blast/run_test.sh
Labels: please review & merge

#23339 Update of check-sort-order
  recipes/check-sort-order/meta.yaml
Labels: please review & merge

#23356 Update opsin source from bitbucket to new github repo
  recipes/opsin/2.4.0/meta.yaml
Labels: please review & merge

#23374 ShoRAH v1.99.1 whitespace typo in requirements
  recipes/shorah/1.99.1/meta.yaml
Labels: please review & merge

#22241 Add Illumina's isaac4 aligner.
  recipes/isaac4/build.sh
  recipes/isaac4/meta.yaml
  recipes/isaac4/patch-configure.diff
  recipes/isaac4/patch-src-cplusplus-lib-alignment-TemplateBuilder.cpp.diff
  recipes/isaac4/patch-src-cplusplus-lib-io-FileBufWithReopen.cpp.diff
Labels: WIP

#23378 update meta.yaml for ncfp v0.2.0 (PyPI)
  recipes/ncfp/meta.yaml
Labels: please review & merge

#23391 Add pydp
  recipes/pydp/meta.yaml
Labels: please review & merge

#23394 updated sha256 and version
  recipes/htstream/meta.yaml
Labels: please review & merge

#23377 [seqfu] Added dependency
  recipes/seqfu/meta.yaml
Labels: please review & merge

#23403 Update pileuppy to 1.0.1
  recipes/pileuppy/meta.yaml
Labels: please review & merge

#23390 Add PyClone
  recipes/pyclone/meta.yaml
Labels: please review & merge

#23396 Update gmap to version 2020-06-30
  recipes/gmap/meta.yaml
Labels: please review & merge

#23368 Add bacphlip recipe
  recipes/bacphlip/meta.yaml
Labels: please review & merge

#23408 Update gffread to 0.12.1
  recipes/gffread/meta.yaml
Labels: please review & merge

#23386 update ShoRAH 1.99.2 (and 1.99.0 & 1.1.3)
  recipes/shorah/1.1.3/build.sh
  recipes/shorah/1.1.3/meta.yaml
  recipes/shorah/1.99.0/build.sh
  recipes/shorah/1.99.0/meta.yaml
  recipes/shorah/1.99.2/meta.yaml
Labels: please review & merge

#23427 Add KEGGCharter
  recipes/keggcharter/meta.yaml
Labels: please review & merge

#23433 added samtools to build and test
  recipes/rilseq/meta.yaml
Labels: please review & merge

#23440 bwa meth fix
  recipes/bwameth/build.sh
  recipes/bwameth/meta.yaml
Labels: please review & merge

#23441 let valet use only one thread for samtools sort
  recipes/valet/meta.yaml
  recipes/valet/valet.patch
Labels: please review & merge

#23347 add argparse2tool
  recipes/argparse2tool/meta.yaml
Labels: please review & merge

#23458 Update STAR-Fusion (requires openssl 1.0 to run)
  recipes/star-fusion/meta.yaml
Labels: please review & merge

#23435 Add wLogDate
  recipes/wlogdate/meta.yaml
Labels: please review & merge

#23431 add trycycler
  recipes/trycycler/meta.yaml
Labels: please review & merge

#23453 Update clustergrammer: pin pandas below 1.0 due to use of .ix
  recipes/clustergrammer/meta.yaml
Labels: please review & merge

#23467 Update gromacs to 2020.3
  recipes/gromacs/2020/meta.yaml
Labels: please review & merge

#23466 Add harmonypy recipe
  recipes/harmonypy/meta.yaml
Labels: please review & merge

#23416 Update: bifrost 1.0.4
  recipes/bifrost/build.sh
  recipes/bifrost/meta.yaml
Labels: please review & merge

#23465 Add recipe for harmony
  recipes/r-harmony/build.sh
  recipes/r-harmony/meta.yaml
Labels: please review & merge

#23685 galaxyxml: add missing license_file
  recipes/galaxyxml/meta.yaml
Labels: please review & merge

#23676 Update clustergrammer: pin pandas strictly below one
  recipes/clustergrammer/meta.yaml
Labels: please review & merge

#23462 update wlogdate to add more dependencies
  recipes/wlogdate/meta.yaml
Labels: please review & merge
