Repository bioconda/bioconda-recipes, pull requests merged in 2021-06, with the labels that each got.

#28703 update scvi-tools
  recipes/scvi-tools/meta.yaml
Labels: please review & merge

#28762 Bump build number
  recipes/komb/meta.yaml
Labels: please review & merge

#28767 mutliqc_sav: update repo URL
  recipes/multiqc_sav/meta.yaml
Labels: please review & merge

#28756 Isoplot update 1.2.1
  recipes/isoplot/meta.yaml
Labels: please review & merge

#28769 Planemo has been relicensed under MIT
  recipes/planemo/meta.yaml
Labels: please review & merge

#28771 Upload new version motulizer
  recipes/motulizer/meta.yaml
Labels: please review & merge

#28777 Ensure that pangolin 2.4.2 does not use pangoLEARN that requires pangolin 3+
  recipes/pangolin/meta.yaml
Labels: please review & merge

#28778 Update GECCO recipe for `v0.7.0`
  recipes/gecco/meta.yaml
Labels: please review & merge

#28779 Update pangolin to 3.0.3
  recipes/pangolin/meta.yaml
Labels: please review & merge

#28782 update arcs to 1.2.2
  recipes/arcs/build.sh
  recipes/arcs/meta.yaml
Labels: please review & merge

#28775 Add dvorfs
  recipes/dvorfs/meta.yaml
Labels: please review & merge

#28789 Add pyseq-align
  recipes/pyseq-align/meta.yaml
Labels: please review & merge

#28795 Update meta.yaml
  recipes/mirmachine/meta.yaml
Labels: please review & merge

#28798 Add iCount-Mini recipe
  recipes/icount-mini/meta.yaml
Labels: please review & merge

#28803 Update tigmint to 1.2.3
  recipes/tigmint/build.sh
  recipes/tigmint/meta.yaml
Labels: please review & merge

#28788 Add ngs-tools
  recipes/ngs-tools/meta.yaml
Labels: please review & merge

#28813 Update isoplot 1.2.2
  recipes/isoplot/meta.yaml
Labels: please review & merge

#28822 Update ostir to 1.0.4
  recipes/ostir/meta.yaml
Labels: please review & merge

#28810 bump prophane to v6.0.5
  recipes/prophane/meta.yaml
Labels: please review & merge

#28836 Update gNALI to 1.0.5
  recipes/gnali/meta.yaml
  recipes/gnali/post-link.sh
Labels: please review & merge

#28834 Add IRMA v1.0.2 recipe
  recipes/irma/build.sh
  recipes/irma/irma-fix-bin-cmds.patch
  recipes/irma/label-fix-bin-cmds.patch
  recipes/irma/meta.yaml
  recipes/irma/run_test.sh
  recipes/irma/test1.fa
  recipes/irma/test2.fastq
Labels: please review & merge

#28817 Update secimtools to version 21.6.3
  recipes/secimtools/meta.yaml
Labels: please review & merge

#28787 Add poseidon-hs recipe
  recipes/poseidon-trident/meta.yaml
Labels: please review & merge

#28790 Add sscocaller
  recipes/sscocaller/build.sh
  recipes/sscocaller/meta.yaml
Labels: please review & merge

#28114 Add apLCMS
  recipes/r-recetox-aplcms/meta.yaml
Labels: please review & merge

#28740 CodAn and MITGARD recipes
  recipes/codan/build.sh
  recipes/codan/meta.yaml
  recipes/codan/post-link.sh
  recipes/mitgard/build.sh
  recipes/mitgard/meta.yaml
Labels: please review & merge

#28862 Add sinto
  recipes/sinto/meta.yaml
Labels: please review & merge

#28864 Remove 2 recipes from the blacklist
  build-fail-blacklist
Labels: please review & merge

#28883 Add dependencies bioconductor-structtoolbox
  recipes/bioconductor-structtoolbox/meta.yaml
Labels: please review & merge

#28867 Update fwdpy11 to 0.15.0
  recipes/fwdpy11/meta.yaml
Labels: please review & merge

#28895 MITGARD recipe
  recipes/mitgard/build.sh
  recipes/mitgard/meta.yaml
Labels: please review & merge

#28863 Update links v1.8.7 build
  recipes/links/build.sh
  recipes/links/links-osx.patch
  recipes/links/meta.yaml
Labels: please review & merge

#28846 Update antiSMASH to 6.0.0
  recipes/antismash/meta.yaml
Labels: please review & merge

#28924 Add deepaccess
  recipes/deepaccess/meta.yaml
Labels: please review & merge

#28899 Update selene-sdk to 0.5.0
  recipes/selene-sdk/meta.yaml
Labels: new version, please review & merge

#28938 Update gNALI 1.0.5 recipe
  recipes/gnali/meta.yaml
Labels: please review & merge

#28940 update chexmix to 0.51
  recipes/chexmix/build.sh
  recipes/chexmix/chexmix.sh
  recipes/chexmix/meta.yaml
Labels: please review & merge

#28960 Update pangolearn to 2021-06-05
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#28871 bcftools fix 1.5
  recipes/bcftools/1.5/b37b03e815cd4f25af70a57c08449f8c719dcc6a.patch
  recipes/bcftools/1.5/build.sh
  recipes/bcftools/1.5/meta.yaml
Labels: please review & merge

#28967 Update BLAST recipe
  recipes/blast/build.sh
Labels: bug

#28908 Update BtToxin_Digger to v1.0.9
  build-fail-blacklist
  recipes/bttoxin_digger/build.sh
  recipes/bttoxin_digger/meta.yaml
Labels: new version, please review & merge

#28982 Adds prequal
  recipes/prequal/build.sh
  recipes/prequal/meta.yaml
Labels: please review & merge

#28992 Update prequal source and sha256
  recipes/prequal/meta.yaml
Labels: please review & merge

#29003 Add recipe for pyCRAC
  recipes/pycrac/meta.yaml
Labels: please review & merge

#29001 Update recipe for new version of mindthegap
  recipes/mindthegap/meta.yaml
Labels: please review & merge

#28814 bioconda recipe for guidemaker v0.2.0
  recipes/guidemaker/meta.yaml
Labels: please review & merge

#28983 Add recipe for GRAMPA
  recipes/grampa/grampa.patch
  recipes/grampa/meta.yaml
Labels: please review & merge

#29007 Un-blacklist and bump bbknn
  build-fail-blacklist
  recipes/bbknn/meta.yaml
Labels: please review & merge

#29016 Version bump for jannovar-cli
  recipes/jannovar-cli/meta.yaml
Labels: please review & merge

#29012 Add soda-gallery recipe
  recipes/soda-gallery/meta.yaml
Labels: please review & merge

#29011 Add recipe for amplicon_coverage_plot
  recipes/amplicon_coverage_plot/meta.yaml
Labels: please review & merge

#29015 wisecondorx: bump version
  recipes/wisecondorx/meta.yaml
Labels: please review & merge

#29023 add sambamba in order to use reformat.sh. => .bam files can only be …
  recipes/bbmap/meta.yaml
Labels: please review & merge

#29020 Update ngs-bits to 2021_06
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#29027 Update Easel v0.48 bump
  build-fail-blacklist
  recipes/easel/meta.yaml
Labels: please review & merge

#29029 Update epimuller
  recipes/epimuller/meta.yaml
Labels: please review & merge

#29046 update recetox-aplcms to new version
  recipes/r-recetox-aplcms/meta.yaml
Labels: please review & merge

#28733 Add orientagraph
  recipes/orientagraph/@
  recipes/orientagraph/build.sh
  recipes/orientagraph/meta.yaml
Labels: please review & merge

#29051 Update r-umi4c to version 0.0.1
  recipes/r-umi4c/build.sh
  recipes/r-umi4c/meta.yaml
Labels: please review & merge

#28923 Codan recipe
  recipes/codan/build.sh
  recipes/codan/meta.yaml
  recipes/codan/post-link.sh
Labels: please review & merge

#28978 openslide-python removed
  recipes/openslide-python/meta.yaml
Labels: please review & merge

#28997 Dnp mapping
  recipes/dnp-mapping/build.sh
  recipes/dnp-mapping/meta.yaml
Labels: please review & merge

#29080 Update Odgi v0.6
  recipes/odgi/meta.yaml
Labels: please review & merge

#29091 Updated HATCHet to v0.3.3
  recipes/hatchet/meta.yaml
Labels: please review & merge

#29100 Update GeneRax to 2.0.2
  build-fail-blacklist
  recipes/generax/meta.yaml
Labels: please review & merge

#29108 Update MBG to version 1.0.5
  recipes/mbg/meta.yaml
Labels: please review & merge

#29042 Add cyntenator
  recipes/cyntenator/build.sh
  recipes/cyntenator/cxx.patch
  recipes/cyntenator/meta.yaml
  recipes/cyntenator/run_test.sh
Labels: please review & merge

#29112 Add pypi aligment pkg
  recipes/alignment/meta.yaml
Labels: please review & merge

#29088 Add Diffacto
  recipes/diffacto/meta.yaml
Labels: please review & merge

#29126 Update deepaccess v0.1.2
  recipes/deepaccess/meta.yaml
Labels: please review & merge

#29101 Update recipe for new version of MTG-Link v2.0.0
  recipes/mtglink/build.sh
  recipes/mtglink/meta.yaml
Labels: please review & merge

#29146 Add ffq
  recipes/ffq/meta.yaml
Labels: please review & merge

#29158 Add minigraph
  recipes/minigraph/build.sh
  recipes/minigraph/meta.yaml
Labels: please review & merge

#29165 Update snvphyl-tools: Add missing grep dependency
  recipes/snvphyl-tools/meta.yaml
Labels: please review & merge

#29160 Add recipe for nextclade C++
  recipes/nextclade/build.sh
  recipes/nextclade/meta.yaml
  recipes/nextclade/post-link.sh
Labels: please review & merge

#29096 Add pyfba
  recipes/pyfba/meta.yaml
Labels: please review & merge

#29182 Update Megan6 to 6.21.7
  recipes/megan/meta.yaml
Labels: please review & merge

#28572 Update Phylics
  build-fail-blacklist
  recipes/phylics/meta.yaml
Labels: please review & merge

#29178 Update Gs-tama
  recipes/gs-tama/build.sh
  recipes/gs-tama/meta.yaml
Labels: please review & merge

#29218 add clair3 update
  recipes/clair3/build.sh
  recipes/clair3/meta.yaml
Labels: please review & merge

#29220 Update gridss' requirements
  recipes/gridss/meta.yaml
Labels: please review & merge

#29222 Add taranis recipe
  recipes/taranis/build.sh
  recipes/taranis/meta.yaml
Labels: please review & merge

#29203 Update IQ-TREE to v2.1.4-beta
  build-fail-blacklist
  recipes/iqtree/meta.yaml
Labels: please review & merge

#29232 Scallop-UMI
  recipes/scallop-umi/build.sh
  recipes/scallop-umi/meta.yaml
Labels: please review & merge

#29083 Pygtftk version 1.3.0
  build-fail-blacklist
  recipes/pygtftk/meta.yaml
Labels: please review & merge

#29235 Update CONSTAX to v2.0.14
  recipes/constax/build.sh
  recipes/constax/meta.yaml
  recipes/constax/run_test.sh
Labels: automerge

#29242 Update Damageprofiler font to fix downstream (bio)container issues
  recipes/damageprofiler/meta.yaml
Labels: please review & merge

#29244 update build.sh to include new test script
  recipes/crisprme/build.sh
  recipes/crisprme/meta.yaml
Labels: please review & merge

#29249 update dependencies
  recipes/r-metacoder/meta.yaml
Labels: please review & merge

#29250 Update snvphyl-tools: Remove extraneous host dependencies and pin samtools
  recipes/snvphyl-tools/meta.yaml
Labels: please review & merge

#29257 removing medpy recipe
  recipes/medpy/graphcut_boost_lib.patch
  recipes/medpy/meta.yaml
Labels: please review & merge

#29258 Fix CheckV recipe
  recipes/checkv/meta.yaml
Labels: please review & merge

#29255 add biocommons.seqrepo
  recipes/biocommons.seqrepo/meta.yaml
Labels: please review & merge

#29240 Update nextalign to version 1.2.0
  recipes/nextalign/meta.yaml
Labels: please review & merge

#29239 Update nextclade to version 1.2.0
  recipes/nextclade/meta.yaml
Labels: please review & merge

#29267 Update meta.yaml
  recipes/clair3/meta.yaml
Labels: please review & merge

#29275 2021.2
  recipes/biobb_io/meta.yaml
Labels: please review & merge

#29280 2021.2
  recipes/biobb_analysis/meta.yaml
Labels: please review & merge

#29307 Clair3 version update to v0.1.4.2
  recipes/clair3/meta.yaml
Labels: please review & merge

#29313 Update meta.yaml
  recipes/jasminesv/meta.yaml
Labels: please review & merge

#29303 Bump up AbNumber
  recipes/abnumber/meta.yaml
Labels: please review & merge

#29302 tracy v0.6.1
  recipes/tracy/meta.yaml
Labels: please review & merge

#29301 Bump version bioconductor-structtoolbox to v1.4.1
  recipes/bioconductor-structtoolbox/meta.yaml
Labels: please review & merge

#29329 Update CPAT to version 3.0.4
  build-fail-blacklist
  recipes/cpat/meta.yaml
Labels: please review & merge

#29320 Bump gubbins to 3.0.0
  build-fail-blacklist
  recipes/gubbins/meta.yaml
Labels: please review & merge

#29335 Add recipe for capcruncher package.
  recipes/capcruncher/meta.yaml
Labels: please review & merge

#29345 Update EUKulele to version 1.0.6
  recipes/eukulele/meta.yaml
Labels: please review & merge

#29348 Update CellRank recipe.yml version and dependencies
  recipes/cellrank/meta.yaml
Labels: please review & merge

#29349 Add recipe for longstitch
  recipes/longstitch/build.sh
  recipes/longstitch/meta.yaml
Labels: please review & merge
