Repository bioconda/bioconda-recipes, pull requests merged in 2021-12, with the labels that each got.

#31792 Update AMPlify to v1.0.2
  recipes/amplify/meta.yaml
Labels: please review & merge

#31796 Update TaxonKit to v0.9.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#31359 add new recipe selenzy_wrapper v0.0.4
  recipes/selenzy_wrapper/meta.yaml
  recipes/selenzy_wrapper/run_test.sh
Labels: help wanted

#31809 update recetox-waveica
  recipes/r-recetox-waveica/meta.yaml
Labels: please review & merge

#31785 add new recipe dnaweaver v0.3.7
  recipes/dnaweaver/meta.yaml
  recipes/dnaweaver/run_test.sh
Labels: please review & merge

#31801 Updated cutqc to 0.07
  recipes/cutqc/build.sh
  recipes/cutqc/meta.yaml
Labels: please review & merge

#31783 Add wally v0.2.5
  recipes/wally/build.sh
  recipes/wally/meta.yaml
Labels: please review & merge

#31758 Update nanopolish recipe to remove superfluous dependencies
  recipes/nanopolish/meta.yaml
Labels: please review & merge

#31786 Correct pbcore 1.2.7 version constraint
  recipes/pbcore/1.2.7/meta.yaml
Labels: please review & merge

#31821 Update Bakta meta information
  recipes/bakta/meta.yaml
Labels: please review & merge

#31816 Add Clippy recipe
  recipes/clippy/meta.yaml
Labels: please review & merge

#31819 Update mbgc recipe to v1.2.1
  recipes/mbgc/meta.yaml
Labels: please review & merge

#31814 Add matchtigs 1.0.0 recipe
  recipes/matchtigs/build.sh
  recipes/matchtigs/meta.yaml
Labels: please review & merge

#31830 update hecatomb to 1.0.0.beta.3
  recipes/hecatomb/meta.yaml
Labels: please review & merge

#31793 add igda-script
  recipes/igda-script/build.sh
  recipes/igda-script/meta.yaml
Labels: please review & merge

#31835 add new recipe dnaweaver_synbiocad v 1.0.0
  recipes/dnaweaver_synbiocad/meta.yaml
  recipes/dnaweaver_synbiocad/run_test.sh
Labels: please review & merge

#31824 Update raxml-ng to 1.0.1 (fix bison)
  recipes/raxml-ng/meta.yaml
Labels: please review & merge

#31841 Update longstitch build
  recipes/longstitch/meta.yaml
Labels: please review & merge

#31782 Modifying hmmcopy recipe to include all utility scripts and including…
  recipes/hmmcopy/build.sh
  recipes/hmmcopy/meta.yaml
Labels: please review & merge

#31837 Update VADR rebuild to include latest SARS-CoV-2 models
  recipes/vadr/meta.yaml
Labels: please review & merge

#28900 Add StrainGE bioconda package
  recipes/strainge/meta.yaml
Labels: please review & merge

#31842 Update r-liger; Use CRAN source
  recipes/r-liger/meta.yaml
Labels: please review & merge

#31840 Update numpy version for Clippy recipe
  recipes/clippy/meta.yaml
Labels: please review & merge

#31858 Add recipe for mseqtools
  recipes/mseqtools/build.sh
  recipes/mseqtools/meta.yaml
Labels: please review & merge

#31881 Update of ngs-bits to version 2021_12
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#31883 update: nextclade to 1.6.0
  recipes/nextclade/meta.yaml
Labels: please review & merge

#31882 Update Nextalign to 1.6.0
  recipes/nextalign/meta.yaml
Labels: please review & merge

#31892 Update pyfaidx as it needs setuptools as dependency
  recipes/pyfaidx/meta.yaml
Labels: please review & merge

#31890 Update HiTaC to 2.0.4
  recipes/hitac/meta.yaml
Labels: please review & merge

#31863 Add PEKA k-mer analysis
  recipes/peka/meta.yaml
Labels: please review & merge

#31905 Update cyvcf2 to 0.30.14
  recipes/cyvcf2/meta.yaml
  recipes/cyvcf2/patches/setup.py.patch
Labels: please review & merge

#31917 Update nextalign to 1.7.0
  recipes/nextalign/meta.yaml
Labels: automerge

#31916 Update nextclade to 1.7.0
  recipes/nextclade/meta.yaml
Labels: automerge

#31933 Fix version cssam
  recipes/r-cssam/meta.yaml
Labels: please review & merge

#31935 update seqwish v0.7.3
  recipes/seqwish/meta.yaml
Labels: please review & merge

#31920 Update hmmcopy - Removing hard coding in shebang of perl scripts
  recipes/hmmcopy/build.sh
  recipes/hmmcopy/meta.yaml
Labels: please review & merge

#31979 Update Hecatomb to 1.0.0.beta.4
  recipes/hecatomb/meta.yaml
Labels: please review & merge

#31972 Update dnaweaver_synbiocad to 1.0.1
  recipes/dnaweaver_synbiocad/meta.yaml
Labels: please review & merge

#32007 bump bcbio-nextgen to 1.2.9, correct pinnings
  recipes/bcbio-nextgen/meta.yaml
Labels: please review & merge

#32026 fix installation issue
  recipes/bcbio-nextgen/meta.yaml
Labels: please review & merge

#31988 r-ichorcna: install the Snakemake workflow as well; minor cleanups.
  recipes/r-ichorcna/build.sh
  recipes/r-ichorcna/meta.yaml
Labels: please review & merge

#32033 Update bcbio-nextgen: pin openssl
  recipes/bcbio-nextgen/meta.yaml
Labels: please review & merge

#31982 Add sgcocaller
  recipes/sgcocaller/build.sh
  recipes/sgcocaller/meta.yaml
Labels: please review & merge

#32036 Update tbb pinning in Bactopia recipe
  recipes/bactopia/meta.yaml
Labels: please review & merge

#32051 Add genion
  recipes/genion/build.sh
  recipes/genion/meta.yaml
Labels: please review & merge

#32059 Update LAST version
  recipes/last/meta.yaml
Labels: please review & merge

#32058 Add "Graphanalyzer" recipe
  recipes/graphanalyzer/build.sh
  recipes/graphanalyzer/meta.yaml
Labels: please review & merge

#32046 Add seqlike
  recipes/seqlike/meta.yaml
Labels: please review & merge

#32039 Update anchorwave to 1.0.1
  recipes/anchorwave/anchorwave
  recipes/anchorwave/build.sh
  recipes/anchorwave/meta.yaml
Labels: please review & merge

#32005 Add Rustybam
  recipes/rustybam/build.sh
  recipes/rustybam/meta.yaml
Labels: please review & merge

#32074 Update rustybam
  recipes/rustybam/meta.yaml
Labels: please review & merge

#31887 ampvis2: add missing requirements
  recipes/r-ampvis2/ggally.patch
  recipes/r-ampvis2/meta.yaml
Labels: please review & merge

#32042 Update metagraph to 0.3.2 and reduce the compile time by skipping non-essential targets in make install
  recipes/metagraph/build.sh
  recipes/metagraph/conda_build_config.yaml
  recipes/metagraph/meta.yaml
Labels: please review & merge

#31865 Update genometools-genometools: Add missing font dependency
  build-fail-blacklist
  recipes/genometools-genometools/meta.yaml
Labels: please review & merge

#32119 Update rmats build for osx
  recipes/rmats/meta.yaml
  recipes/rmats/rmats_c_myfunc.patch
Labels: please review & merge

#32139 Update ganon to 1.1.0
  recipes/ganon/build.sh
  recipes/ganon/meta.yaml
Labels: please review & merge

#32142 Update deeparg (missing dependency)
  recipes/deeparg/meta.yaml
Labels: please review & merge

#32172 Update: Pin biopython 1.79
  recipes/biobb_structure_checking/meta.yaml
Labels: please review & merge

#32156 Update GRIDSS 2.13.0
  recipes/gridss/build.sh
  recipes/gridss/meta.yaml
Labels: please review & merge

#32149 Update Nextstrain CLI version and dependencies
  recipes/nextstrain-cli/meta.yaml
Labels: please review & merge

#32141 Update PathRacer to the latest version (3.16.0-dev)
  build-fail-blacklist
  recipes/pathracer/0001-add-rt-lib-to-easel.patch
  recipes/pathracer/0001-change-verbosity.patch
  recipes/pathracer/0001-link-rt-for-static-jemalloc.patch
  recipes/pathracer/0002-add-missing-inittypes-header.patch
  recipes/pathracer/build.sh
  recipes/pathracer/conda_build_config.yaml
  recipes/pathracer/meta.yaml
Labels: please review & merge

#32203 Add new recipe for "guide-counter" (tool for counting guides in CRISPR screens)
  recipes/guide-counter/build.sh
  recipes/guide-counter/meta.yaml
Labels: please review & merge

#32210 Update superfocus: updating to pypi and adding setup tools
  recipes/super-focus/meta.yaml
Labels: please review & merge

#32200 Update FOCUS: adding setuptools
  recipes/focus/meta.yaml
Labels: please review & merge

#32135 Updated medicc2
  recipes/medicc2/meta.yaml
Labels: please review & merge

#32228 Update guide-counter recipe to v0.1.2
  recipes/guide-counter/meta.yaml
Labels: please review & merge

#32232 Update icescreen recipe: v1.0.1
  recipes/icescreen/build.sh
  recipes/icescreen/meta.yaml
Labels: please review & merge

#32223 v1.2.13
  recipes/ribocode/meta.yaml
Labels: please review & merge
