Repository bioconda/bioconda-recipes, pull requests merged in 2021-05, with the labels that each got.

#28267 Fixing varfish-cli dependencies, adding tests.
  recipes/varfish-cli/meta.yaml
Labels: please review & merge

#28233 Add bleties 0.1.9
  recipes/bleties/meta.yaml
Labels: please review & merge

#28230 Add bali-phy 3.6.0
  recipes/bali-phy/build.sh
  recipes/bali-phy/meta.yaml
Labels: please review & merge

#28247 Update RENANO to v1.1
  recipes/renano/build.sh
  recipes/renano/meta.yaml
Labels: please review & merge

#28304 Update CONSTAX to v2.0.10
  recipes/constax/build.sh
  recipes/constax/meta.yaml
Labels: please review & merge

#28296 Bump eggnog-mapper
  recipes/eggnog-mapper/meta.yaml
Labels: please review & merge

#28316 Add ChIA_Rep package
  recipes/chia-rep/meta.yaml
Labels: please review & merge

#28312 Update dsh-bio to 2.0.4
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#28333 Update gNALI to 1.0.4
  recipes/gnali/meta.yaml
Labels: please review & merge

#28269 Update homopolish to 0.0.2
  recipes/homopolish/meta.yaml
Labels: please review & merge

#28345 tracy version bump v0.5.9
  recipes/tracy/meta.yaml
Labels: please review & merge

#28337 Update ViennaRNA to 2.4.18
  recipes/viennarna/meta.yaml
Labels: please review & merge

#28349 Adding sodar-cli v0.1.0
  recipes/sodar-cli/meta.yaml
Labels: please review & merge

#28344 Update sdm to 1.83
  recipes/sdm/build.sh
  recipes/sdm/macOS_1.73.patch
  recipes/sdm/meta.yaml
  recipes/sdm/sdm_1.83.patch
Labels: please review & merge

#28323 Add new recipie for epimuller
  recipes/epimuller/meta.yaml
Labels: please review & merge

#28342 Update lotus2 to 2.02
  recipes/lotus2/build.sh
  recipes/lotus2/meta.yaml
Labels: please review & merge

#28350 Add recipe for Contrafold
  recipes/contrafold/LICENSE
  recipes/contrafold/build.sh
  recipes/contrafold/contrafold-2.02-legacy.patch
  recipes/contrafold/meta.yaml
Labels: please review & merge

#28373 Bump pangolin to 2.4.2
  recipes/pangolin/meta.yaml
Labels: please review & merge

#28066 Update HuMAnN (including renaming)
  recipes/humann/meta.yaml
  recipes/humann2/meta.yaml
Labels: please review & merge

#28380 Update ultraplex
  build-fail-blacklist
  recipes/ultraplex/meta.yaml
Labels: please review & merge

#28381 Add xpore
  recipes/xpore/meta.yaml
Labels: please review & merge

#28387 Update rsidx: pin minimum version for htslib dependency
  recipes/rsidx/meta.yaml
Labels: please review & merge

#28354 update scvi-tools
  recipes/scvi-tools/meta.yaml
Labels: please review & merge

#28394 Add recipe for GECCO python package
  recipes/gecco/meta.yaml
Labels: please review & merge

#28322 Update chia-rep
  recipes/chia-rep/meta.yaml
Labels: please review & merge

#28416 Update MBG to v1.0.4
  recipes/mbg/meta.yaml
Labels: please review & merge

#28372 Update RepeatMasker to 4.1.2-p1
  recipes/repeatmasker/meta.yaml
Labels: please review & merge

#28411 Remove r-taxonomizr after migration to conda-forge.
  recipes/r-taxonomizr/build.sh
  recipes/r-taxonomizr/meta.yaml
Labels: please review & merge

#28414 Add PBSIM2
  recipes/pbsim2/build.sh
  recipes/pbsim2/meta.yaml
Labels: please review & merge

#28446 Add bionetcomp
  recipes/bionetcomp/LICENSE
  recipes/bionetcomp/meta.yaml
Labels: please review & merge

#28447 Add Autodock
  recipes/autodock/build.sh
  recipes/autodock/meta.yaml
Labels: please review & merge

#28445 Update: SG 4.0.33 supporting Metamorpheus
  recipes/searchgui/build.sh
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#28413 nanoplot test bump
  recipes/nanoplot/meta.yaml
Labels: please review & merge

#28441 Update snakedeploy python dep to >= 3.8
  recipes/snakedeploy/meta.yaml
Labels: automerge

#28457 Add recipe for zgtf
  recipes/zgtf/meta.yaml
Labels: please review & merge

#28465 Update recipe for new version of MTG-Link v1.2.0
  recipes/mtglink/meta.yaml
Labels: please review & merge

#28453 Update galaxy_ml to v0.9.0
  recipes/galaxy-ml/meta.yaml
Labels: please review & merge

#28472 Add labrat recipe
  recipes/labrat/LICENSE
  recipes/labrat/meta.yaml
Labels: please review & merge

#28374 Updated HATCHet to 0.3.0
  recipes/hatchet/build.sh
  recipes/hatchet/meta.yaml
Labels: please review & merge

#28475 Bump pangolearn to 2021-05-10
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#28464 Add recipe for merge_kallisto
  recipes/r-merge-kallisto/meta.yaml
Labels: please review & merge

#28485 Update HATCHet to 0.3.1
  recipes/hatchet/meta.yaml
Labels: please review & merge

#28487 Update cannoli to 0.13.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#28486 Update adam to 0.35.0
  recipes/adam/meta.yaml
Labels: please review & merge

#28497 Add MAGE-Tab merger
  recipes/mage-tab-merger/meta.yaml
Labels: please review & merge

#28377 Update Gromacs to enable MPI support
  recipes/gromacs/2021/0001-Fix-OpenCL-build-on-OSX.patch
  recipes/gromacs/2021/0001-add-header.patch
  recipes/gromacs/2021/activate.sh
  recipes/gromacs/2021/build.sh
  recipes/gromacs/2021/conda_build_config.yaml
  recipes/gromacs/2021/gmx-chooser.bash
  recipes/gromacs/2021/meta.yaml
  recipes/gromacs/README.md
Labels: please review & merge

#28509 Add the ppx Python package
  recipes/ppx/meta.yaml
Labels: please review & merge

#28511 Update ADAPT dependencies
  recipes/adapt/meta.yaml
Labels: please review & merge

#28516 Update sdm to 1.83post0
  recipes/lotus2/meta.yaml
  recipes/lotus2/post-link.sh
  recipes/sdm/meta.yaml
Labels: please review & merge

#28512 Update recipe for beagle to 5.2
  recipes/beagle/build.sh
  recipes/beagle/meta.yaml
Labels: please review & merge

#27169 Update octopus to v0.7.4
  recipes/octopus/0001-Fix-Clang-8-compile-errors.patch
  recipes/octopus/build.sh
  recipes/octopus/meta.yaml
Labels: help wanted, please review & merge

#28535 Update PegasusIO to 0.2.11
  recipes/pegasusio/meta.yaml
Labels: please review & merge

#28532 Update recipe for komb
  build-fail-blacklist
  recipes/komb/meta.yaml
Labels: please review & merge

#28540 Add r-quilt to bioconda
  recipes/r-quilt/meta.yaml
Labels: please review & merge

#28563 Update epimuller
  recipes/epimuller/meta.yaml
Labels: please review & merge

#28561 Update skmer to 3.1.0
  recipes/skmer/meta.yaml
Labels: please review & merge

#28525 Update platon bump dependency versions
  recipes/platon/meta.yaml
Labels: enhancement, please review & merge, update build number

#28546 Update ANANSE to 0.2.0
  recipes/ananse/meta.yaml
Labels: please review & merge

#28582 Updating jellyfish name changed in recent versions
  recipes/skmer/meta.yaml
Labels: please review & merge

#28577 Update BacGWASim to 2.1.0
  recipes/bacgwasim/meta.yaml
Labels: please review & merge

#28586 Update PGCGAP to v1.0.29
  recipes/pgcgap/meta.yaml
Labels: please review & merge

#28584 Update SeqKit to 0.16.1
  recipes/seqkit/meta.yaml
Labels: please review & merge

#28594 vep: bump plugin versions
  recipes/ensembl-vep/build.sh
  recipes/ensembl-vep/meta.yaml
Labels: please review & merge

#28575 Update prophane to 6.0.1
  recipes/prophane/build.sh
  recipes/prophane/meta.yaml
Labels: please review & merge

#28566 new recipe: multiqc_sav
  recipes/multiqc_sav/meta.yaml
Labels: please review & merge

#28610 Bump bioconductor-pmp
  recipes/bioconductor-pmp/meta.yaml
Labels: please review & merge

#28613 Update tb_variant_filter to 0.3.0
  recipes/tb_variant_filter/meta.yaml
Labels: please review & merge

#28583 Add aptardi
  recipes/aptardi/meta.yaml
Labels: automerge, please review & merge

#28612 Add linearfold recipe
  recipes/linearfold/0001-FIX-command-broken-with-symbolic-link.patch
  recipes/linearfold/LICENSE
  recipes/linearfold/build.sh
  recipes/linearfold/meta.yaml
Labels: please review & merge

#28615 Add recipe for linearpartition
  recipes/linearpartition/0001-FIX-command-broken-with-symbolic-link.patch
  recipes/linearpartition/LICENSE
  recipes/linearpartition/build.sh
  recipes/linearpartition/meta.yaml
Labels: please review & merge

#28626 Update CONSTAX to v2.0.11 with improved input tests.
  recipes/constax/meta.yaml
Labels: please review & merge

#28448 Add r-autospill
  recipes/r-autospill/build.sh
  recipes/r-autospill/meta.yaml
Labels: please review & merge

#28636 Add the fuc package
  recipes/fuc/meta.yaml
Labels: please review & merge

#28645 Update lra to version 1.3.0
  recipes/lra/build.sh
  recipes/lra/meta.yaml
Labels: please review & merge

#28653 Add magetab-curation-scripts
  recipes/magetab-curation-scripts/build.sh
  recipes/magetab-curation-scripts/meta.yaml
Labels: please review & merge

#28658 Updated HATCHet to 0.3.2
  recipes/hatchet/meta.yaml
Labels: please review & merge

#28660 Rebuild mosdepth
  recipes/mosdepth/build.sh
  recipes/mosdepth/conda_build_config.yaml
  recipes/mosdepth/meta.yaml
Labels: please review & merge

#28673 Add recipe for buildH
  recipes/buildh/meta.yaml
Labels: please review & merge

#27768 Add pandora
  recipes/pandora/build.sh
  recipes/pandora/meta.yaml
Labels: please review & merge

#28672 Update blast-legacy to work on osx by building from source
  recipes/blast-legacy/2.2.26/build.sh
  recipes/blast-legacy/2.2.26/fix-osx-build.patch
  recipes/blast-legacy/2.2.26/meta.yaml
Labels: please review & merge

#28506 Add recipe for tin-score-calculation
  recipes/tin-score-calculation/meta.yaml
Labels: please review & merge

#28674 Update tatajuba
  recipes/tatajuba/meta.yaml
Labels: please review & merge

#28679 Update FROGS to release 3.2.3
  recipes/frogs/meta.yaml
Labels: please review & merge

#28617 Add recipe for multiqc-plugins
  recipes/zavolan-multiqc-plugins/meta.yaml
Labels: please review & merge

#28692 [dadaist2] Dependency version updates
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#28696 Add SemiBin to bioconda
  recipes/semibin/meta.yaml
Labels: please review & merge

#28331 Add recipie for OSTIR
  recipes/ostir/LICENSE
  recipes/ostir/meta.yaml
Labels: please review & merge

#28702 Update GeMoMa version & fix exit status
  recipes/gemoma/GeMoMa.py
  recipes/gemoma/meta.yaml
Labels: please review & merge

#28700 Add new tool PlotCritic - v1.0.0
  recipes/plotcritic/meta.yaml
Labels: please review & merge

#28705 Update LDBlockShow to v1.40; copy ShowLDSVG to $PATH
  build-fail-blacklist
  recipes/ldblockshow/build.sh
  recipes/ldblockshow/meta.yaml
Labels: please review & merge

#28706 Update SemiBin
  recipes/semibin/meta.yaml
Labels: please review & merge

#28729 add snakesv recipe
  recipes/snakesv/build.sh
  recipes/snakesv/meta.yaml
Labels: please review & merge

#28737 Update WhatsHap dependency to fix Python 3.9 incompatibility
  recipes/whatshap/meta.yaml
Labels: please review & merge

#28742 Update demuxEM to 0.1.6
  recipes/demuxem/meta.yaml
Labels: please review & merge

#28741 Initial commit of cs-blast recipe
  recipes/csblast/2.2.3/meta.yaml
Labels: please review & merge

#28743 Initial commit of lddt recipe
  recipes/lddt/2.2/meta.yaml
Labels: please review & merge

#28717 Update tb_variant_filter to 0.3.5
  recipes/tb_variant_filter/meta.yaml
Labels: please review & merge

#28732 Bump datafunk to 0.0.9
  recipes/datafunk/meta.yaml
Labels: please review & merge

#28720 Fix motulizer
  recipes/motulizer/meta.yaml
Labels: please review & merge

#28695 add recipe for cazy_webscraper
  recipes/cazy_webscraper/meta.yaml
Labels: please review & merge

#28750 Add strawC
  recipes/strawc/build.sh
  recipes/strawc/meta.yaml
Labels: please review & merge

#28676 Add gs-tama
  recipes/gs-tama/LICENSE
  recipes/gs-tama/build.sh
  recipes/gs-tama/meta.yaml
Labels: please review & merge
