Repository bioconda/bioconda-recipes, pull requests merged in 2021-01, with the labels that each got.

#26011 Update jmztab-m to 1.0.6
  recipes/jmztab-m/jmztab-m.py
  recipes/jmztab-m/meta.yaml
Labels: please review & merge

#26014 Update anvio-minimal to v7
  recipes/anvio-minimal/meta.yaml
Labels: please review & merge

#26027 Tool update to 1.2 because of incorrect versioning
  recipes/gecko/meta.yaml
Labels: please review & merge

#26033 Add epiweeks
  recipes/epiweeks/meta.yaml
Labels: please review & merge

#26035 Update HiTaC to v1.5.4
  recipes/hitac/meta.yaml
Labels: please review & merge

#26040 add recipe for shovill-se
  recipes/shovill-se/build.sh
  recipes/shovill-se/meta.yaml
Labels: please review & merge

#26044 add recipe for spaTyper
  recipes/spatyper/meta.yaml
Labels: please review & merge

#26047 Update PolySTest
  recipes/polystest/build.sh
  recipes/polystest/meta.yaml
Labels: please review & merge

#26050 Update: WisecondorX
  recipes/wisecondorx/meta.yaml
Labels: please review & merge

#26043 add reciper for clinker-py
  recipes/clinker-py/meta.yaml
Labels: please review & merge

#26064 Update trtools to 3.0.3
  recipes/trtools/meta.yaml
Labels: please review & merge

#26053 Add pangoLEARN
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#26070 Add uvaia
  recipes/uvaia/LICENSE
  recipes/uvaia/build.sh
  recipes/uvaia/meta.yaml
Labels: please review & merge

#26031 Add run_dbcan
  recipes/run-dbcan/meta.yaml
Labels: please review & merge

#26022 Add new recipe xtea
  recipes/xtea/LICENSE
  recipes/xtea/build.sh
  recipes/xtea/meta.yaml
Labels: please review & merge

#26079 Add recipe for SAP
  recipes/sap/build.sh
  recipes/sap/meta.yaml
Labels: please review & merge

#26081 Update samplot
  recipes/samplot/meta.yaml
Labels: please review & merge

#26100 NeatMS upgrade to v0.7
  recipes/neatms/meta.yaml
Labels: please review & merge

#26103 Update cannoli to 0.11.1
  recipes/cannoli/meta.yaml
Labels: please review & merge

#26102 Update adam to 0.33.0
  recipes/adam/meta.yaml
Labels: please review & merge

#26099 Add BayesASE
  recipes/bayesase/meta.yaml
Labels: please review & merge

#26087 Update BtToxin_Digger to v1.0.5 build 1
  recipes/bttoxin_digger/meta.yaml
Labels: please review & merge, update build number

#26078 Add primalscheme
  recipes/primalscheme/meta.yaml
Labels: please review & merge

#26114 Update bttoxin_digger build number
  recipes/bttoxin_digger/meta.yaml
Labels: please review & merge, update build number

#26115 Update samplot to 1.1.0
  recipes/samplot/meta.yaml
Labels: please review & merge

#26112 Update metaeuk to 4-a0f584d
  recipes/metaeuk/meta.yaml
Labels: please review & merge

#26143 Bump up Abnumber to 0.2.1
  recipes/abnumber/meta.yaml
Labels: please review & merge

#26144 add recipe for phirbo
  recipes/phirbo/build.sh
  recipes/phirbo/meta.yaml
Labels: please review & merge

#26166 seqkit-0.15.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#26168 csvtk-0.22.0
  recipes/csvtk/meta.yaml
Labels: please review & merge

#26165 Update ARTIC to 1.2.0
  recipes/artic/meta.yaml
Labels: please review & merge

#26172 Add probconsRNA
  recipes/probconsrna/build.sh
  recipes/probconsrna/file.patch
  recipes/probconsrna/meta.yaml
Labels: please review & merge

#26156 Update CONSTAX to v2.0.4
  recipes/constax/meta.yaml
Labels: please review & merge

#26177 add new recipe simba
  recipes/simba/meta.yaml
Labels: please review & merge

#26176 Update Iris to v1.0.4
  recipes/irissv/meta.yaml
Labels: please review & merge

#26180 Update requirements from git
  recipes/scanpy/meta.yaml
Labels: please review & merge

#23824 Update odgi to 0.4.1
  recipes/odgi/meta.yaml
Labels: please review & merge

#26179 add new recipe megatron
  recipes/megatron/meta.yaml
Labels: please review & merge

#26186 Update CHISEL to v0.0.5
  recipes/chisel/meta.yaml
Labels: please review & merge

#26094 Add recipe for `pyhmmer` PyPI package
  recipes/pyhmmer/meta.yaml
Labels: please review & merge

#26157 Add Rosella recipe
  recipes/rosella/build.sh
  recipes/rosella/meta.yaml
Labels: please review & merge

#26195 Update samtools dependency to avoid issues with samtools view in olde…
  recipes/irissv/meta.yaml
Labels: please review & merge

#26183 Add kalign2 and probcons run requirements to t-coffee
  recipes/t-coffee/activate.sh
  recipes/t-coffee/build.sh
  recipes/t-coffee/deactivate.sh
  recipes/t-coffee/meta.yaml
  recipes/t-coffee/t_coffee.sh
Labels: please review & merge

#26188 Add recipe for ExpressionNormalizationWorkflow
  recipes/bioconductor-expressionnormalizationworkflow/build.sh
  recipes/bioconductor-expressionnormalizationworkflow/meta.yaml
Labels: please review & merge

#26139 Build bump to hopefully handle runtime issues due to openblas.
  recipes/fwdpy11/meta.yaml
Labels: please review & merge

#26203 Update recipes and python script
  recipes/submission-tool-validator/meta.yaml
  recipes/submission-tool-validator/submission-tool-validator.py
Labels: please review & merge

#26208 bump spaTyper to 0.3.3
  recipes/spatyper/meta.yaml
Labels: please review & merge

#26210 Update recipe for new version of svjedi
  recipes/svjedi/meta.yaml
Labels: please review & merge

#26230 Update VirSorter to v2.1
  recipes/virsorter/meta.yaml
Labels: please review & merge

#26223 Update open-cravat
  recipes/open-cravat/meta.yaml
Labels: please review & merge

#26227 Update secapr
  recipes/secapr/meta.yaml
Labels: please review & merge

#26226 Add flight recipe
  recipes/flight-genome/meta.yaml
Labels: please review & merge

#26224 Update Rosella
  recipes/rosella/build.sh
  recipes/rosella/meta.yaml
Labels: please review & merge

#26202 update FROGS to 3.2
  recipes/frogs/build.sh
  recipes/frogs/meta.yaml
Labels: please review & merge

#26237 Rebuild htslib with current conda-forge libdeflate
  recipes/htslib/meta.yaml
Labels: please review & merge

#26246 Update hmmer2 to enable-threads
  recipes/hmmer2/build.sh
  recipes/hmmer2/meta.yaml
Labels: please review & merge

#26254 Add chip-r recipe
  recipes/chip-r/LICENSE
  recipes/chip-r/meta.yaml
Labels: please review & merge

#26250 Add cov-lineages
  recipes/cov-lineages/meta.yaml
Labels: please review & merge

#26251 Bump pangolearn to 2021-01-16
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#26258 Bump pangolin to 2.1.7
  recipes/pangolin/meta.yaml
Labels: new version, please review & merge

#26265 Add baltic
  recipes/baltic/meta.yaml
Labels: please review & merge

#26260 Update FastSpar to 1.0.0
  build-fail-blacklist
  recipes/fastspar/meta.yaml
Labels: new version, please review & merge

#26261 update to chromeister 1.5.a fixes potential memory errors
  recipes/chromeister/meta.yaml
Labels: please review & merge

#26269 Update secapr
  recipes/secapr/meta.yaml
Labels: please review & merge

#26190 Add recipe for EUKulele tool
  recipes/eukulele/meta.yaml
Labels: please review & merge

#26273 Update tigmint to 1.2.2
  recipes/tigmint/meta.yaml
Labels: please review & merge

#26274 Update gifrop to v0.0.5
  recipes/gifrop/meta.yaml
Labels: please review & merge

#26145 Update SG 4.0.12
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#26276 Update `EUKulele` back to `BUSCO` 4.0.6
  recipes/eukulele/meta.yaml
Labels: please review & merge

#26283 Bump up abnumber to 0.2.3
  recipes/abnumber/meta.yaml
Labels: please review & merge

#26281 Update PeptideShaker to 2.0.9
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
Labels: please review & merge

#26284 Update MALT to 0.5.1
  recipes/malt/build.sh
  recipes/malt/meta.yaml
Labels: please review & merge

#26275 Update lra to a new version V1.1.1
  recipes/lra/meta.yaml
Labels: please review & merge

#26310 Add r-sigminer
  recipes/r-sigminer/build.sh
  recipes/r-sigminer/meta.yaml
Labels: please review & merge

#26306 Add wgdi recipes
  recipes/wgdi/meta.yaml
Labels: please review & merge

#26314 Bump up DeepBGC to 0.1.22
  recipes/deepbgc/meta.yaml
Labels: please review & merge

#26320 Update seq-seq-pan dependencies.
  recipes/seq-seq-pan/meta.yaml
Labels: please review & merge

#26303 Update balrog
  recipes/balrog/meta.yaml
Labels: please review & merge

#26330 Update socru
  recipes/socru/meta.yaml
Labels: please review & merge

#26334 Update TaxonKit to v0.7.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#26321 [dadaist2] update dependencies for upcoming vers.
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#26317 Update dependencies
  recipes/edta/meta.yaml
Labels: please review & merge

#26341 Add president v0.2.1
  recipes/president/meta.yaml
Labels: please review & merge

#26319 Add HTSeqQC v1.0
  recipes/htseqqc/meta.yaml
Labels: please review & merge

#26308 Update dependencies
  recipes/msi/meta.yaml
Labels: please review & merge

#26342 Update dsh-bio to 2.0
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#26352 Update artic-tools
  recipes/artic-tools/meta.yaml
Labels: please review & merge

#26373 Update TaxonKit to 0.7.1
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#26374 Rebuild Bactopia v1.6.0
  recipes/bactopia/meta.yaml
Labels: please review & merge

#26329 Update Hail: update to support hailtop.batch
  recipes/hail/meta.yaml
Labels: please review & merge

#26379 Update lra to new version V1.1.2
  recipes/lra/meta.yaml
Labels: please review & merge

#26382 Bump gofasta
  recipes/gofasta/meta.yaml
Labels: please review & merge

#26383 Add fastafunk
  recipes/fastafunk/meta.yaml
Labels: please review & merge

#26384 Add reportfunk
  recipes/reportfunk/meta.yaml
Labels: please review & merge

#26385 Add clusterfunk
  recipes/clusterfunk/meta.yaml
Labels: please review & merge

#26372 New recipe: bamsnap.
  recipes/bamsnap/meta.yaml
Labels: please review & merge

#26305 Add make_prg recipe
  recipes/make_prg/meta.yaml
Labels: please review & merge

#26386 Add shigeifinder
  recipes/shigeifinder/meta.yaml
Labels: please review & merge

#26405 Update TaxonKit to v0.7.2
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#26411 Update transdecoder
  recipes/transdecoder/meta.yaml
Labels: please review & merge

#26416 Bump pangolearn
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#26420 Update gNALI recipe
  recipes/gnali/meta.yaml
Labels: please review & merge

#26408 Update dRep dependencies
  recipes/drep/meta.yaml
Labels: please review & merge

#26417 Update CONSTAX to v2.0.5. Simple database filtering.
  recipes/constax/meta.yaml
Labels: please review & merge

#26407 Update pantools to 2.0.0
  recipes/pantools/LICENSE
  recipes/pantools/build.sh
  recipes/pantools/meta.yaml
  recipes/pantools/pantools.py
Labels: please review & merge

#26425 Add: pyJASPAR
  recipes/pyjaspar/meta.yaml
Labels: please review & merge

#26437 Update ShigEiFinder to 1.2.0
  recipes/shigeifinder/meta.yaml
Labels: please review & merge

#26427 Update: TOIL patch to remove wdlparse dependency.
  recipes/toil/meta.yaml
  recipes/toil/remove_wdlparse.patch
Labels: please review & merge

#26440 Update ganon to 0.4.0
  recipes/ganon/meta.yaml
Labels: please review & merge

#26446 2020.4
  recipes/biobb_vs/build.sh
  recipes/biobb_vs/meta.yaml
Labels: please review & merge

#26443 Update wgdi to 0.4.4
  recipes/wgdi/build.sh
  recipes/wgdi/meta.yaml
Labels: please review & merge

#26447 Add PacBio trim_isoseq_polyA
  recipes/trim_isoseq_polya/build.sh
  recipes/trim_isoseq_polya/meta.yaml
Labels: please review & merge

#26451 Update Mikado to version 2.0
  recipes/mikado/LICENSE.txt
  recipes/mikado/meta.yaml
Labels: please review & merge

#26271 Update recipes
  recipes/submission-tool-validator/meta.yaml
  recipes/submission-tool-validator/submission-tool-validator.py
Labels: please review & merge

#26483 Remove smina
  recipes/smina/build.sh
  recipes/smina/meta.yaml
Labels: Move to Conda-Forge, please review & merge

#26478 Update ntJoin 1.0.5 recipe
  recipes/ntjoin/build.sh
  recipes/ntjoin/meta.yaml
Labels: please review & merge

#26461 Update meta.yaml
  recipes/crispritz/meta.yaml
Labels: please review & merge
