Repository bioconda/bioconda-recipes, pull requests merged in 2021-11, with the labels that each got.

#31298 Update mafft to version 7.490
  recipes/mafft/meta.yaml
Labels: please review & merge

#30990 Add Proksee
  recipes/proksee/meta.yaml
Labels: please review & merge

#31334 Update r-ichorcna to most recent github version (v0.3.2)
  recipes/r-ichorcna/meta.yaml
Labels: please review & merge

#31215 update: nextclade version bump to v1.4.4
  recipes/nextclade/meta.yaml
Labels: please review & merge

#31288 Update VADR build to better support container
  recipes/vadr/build.sh
  recipes/vadr/meta.yaml
Labels: please review & merge

#31331 Update recipe for new version of MTG-Link v2.3.0
  recipes/mtglink/build.sh
  recipes/mtglink/meta.yaml
Labels: please review & merge

#31364 Update elastic-blast to 0.1.10
  recipes/elastic-blast/meta.yaml
Labels: please review & merge

#31362 [n50] meta.yaml: dependency and metadata
  recipes/n50/meta.yaml
Labels: please review & merge

#30534 Update magicblast to 1.6.0
  build-fail-blacklist
  recipes/magicblast/build.sh
  recipes/magicblast/meta.yaml
Labels: please review & merge

#31372 Update: `gs-tama`
  recipes/gs-tama/meta.yaml
Labels: please review & merge

#31281 Add recipe for Perl package IO::Pager
  recipes/perl-io-pager/2.10/build.sh
  recipes/perl-io-pager/2.10/meta.yaml
Labels: please review & merge

#31352 Add Hecatomb pipeline
  recipes/hecatomb/build.sh
  recipes/hecatomb/meta.yaml
Labels: please review & merge

#31380 add psdm recipe
  recipes/psdm/build.sh
  recipes/psdm/meta.yaml
Labels: please review & merge

#31367 Add fasta_windows
  recipes/fasta_windows/build.sh
  recipes/fasta_windows/meta.yaml
Labels: please review & merge

#31292 Add recipe for Perl package MooseX::StrictConstructor
  recipes/perl-moosex-strictconstructor/0.21/build.sh
  recipes/perl-moosex-strictconstructor/0.21/meta.yaml
Labels: please review & merge

#31287 Add recipe for Perl package Digest::CRC
  recipes/perl-digest-crc/0.23/build.sh
  recipes/perl-digest-crc/0.23/meta.yaml
Labels: please review & merge

#31388 Update recipe for new version of MTG-Link v2.3.1
  recipes/mtglink/build.sh
  recipes/mtglink/meta.yaml
Labels: please review & merge

#31376 rebuild ngmaster to get docker container
  recipes/ngmaster/meta.yaml
Labels: please review & merge

#31403 Patch python requirements in previous version
  recipes/emu/meta.yaml
Labels: please review & merge

#31280 Remove "v" prefix from version numbers
  recipes/burst/meta.yaml
  recipes/codingorf/meta.yaml
  recipes/glimpse-bio/meta.yaml
  recipes/metaclassifier/meta.yaml
  recipes/msisensor-pro/meta.yaml
  recipes/r-scpred/meta.yaml
  recipes/scran-cli/meta.yaml
  recipes/slamem/meta.yaml
  recipes/svclone/meta.yaml
  recipes/talon/meta.yaml
Labels: please review & merge

#31411 Update: nextclade bump 1.4.4 -> 1.4.5
  recipes/nextclade/meta.yaml
Labels: please review & merge

#31412 Update nextalign 1.4.1 -> 1.4.5
  recipes/nextalign/meta.yaml
Labels: please review & merge

#31408 Add recipe for Perl module XXX (fixed)
  recipes/perl-xxx/0.35/build.sh
  recipes/perl-xxx/0.35/meta.yaml
Labels: please review & merge

#31417 Bumping cellxgene to 1.0.0
  recipes/cellxgene/meta.yaml
Labels: please review & merge

#31401 Update python version requirement
  recipes/emu/meta.yaml
Labels: please review & merge

#31397 Updated Entrez Direct to version 16.2
  recipes/entrez-direct/build.sh
  recipes/entrez-direct/meta.yaml
Labels: please review & merge, new version

#31423 Add recipe for msamtools
  recipes/msamtools/build.sh
  recipes/msamtools/meta.yaml
Labels: please review & merge

#31419 Update sha key for asset builder
  recipes/biscuit/meta.yaml
Labels: please review & merge

#31440 update sonicparanoid to v137
  recipes/sonicparanoid/meta.yaml
Labels: please review & merge

#31442 Update recipe for new version of MTG-Link v2.3.2
  recipes/mtglink/meta.yaml
Labels: please review & merge

#31441 [dadaist2] Update depencency version
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#31456 Update: Build fix for Hecatomb
  recipes/hecatomb/meta.yaml
Labels: please review & merge

#31477 updated sonicparanoid recipe to v1.3.8
  recipes/sonicparanoid/meta.yaml
Labels: please review & merge

#31478 [Update]: fix bin path problem in source code
  recipes/parallel-meta-suite/meta.yaml
Labels: please review & merge

#31484 Fix sra-tools “std::exception” error
  recipes/sra-tools/0003-_NSGetExecutablePath-macos.patch
  recipes/sra-tools/meta.yaml
Labels: please review & merge

#31492 Update meta.yaml
  recipes/coast/meta.yaml
Labels: please review & merge

#31495 add mhg
  recipes/mhg/meta.yaml
  recipes/mhg/run_test.sh
Labels: please review & merge

#31353 Update Novoalign to V4.03.04
  recipes/novoalign/build.sh
  recipes/novoalign/meta.yaml
Labels: automerge

#31485 add virstrain recipes
  recipes/virstrain/meta.yaml
Labels: please review & merge

#31471 Update Toil package dependency
  recipes/toil/meta.yaml
Labels: please review & merge

#31501 [Update]: remove useless arugments
  recipes/parallel-meta-suite/meta.yaml
Labels: please review & merge

#31503 [Update]: add make argument
  recipes/meta-apo/build.sh
  recipes/meta-apo/meta.yaml
Labels: please review & merge

#31511 [coast] Update meta.yaml
  recipes/coast/meta.yaml
Labels: please review & merge

#31512 update virstrain recipes
  recipes/virstrain/meta.yaml
Labels: please review & merge

#31506 Add WaveICA
  recipes/r-recetox-waveica/meta.yaml
Labels: please review & merge

#31540 Update SeqKit to v2.1.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#31542 Update dgenies to 1.2.0.2
  recipes/dgenies/meta.yaml
Labels: please review & merge

#31530 Update dsh-bio to 2.0.6
  recipes/dsh-bio/build.sh
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#31555 Update colord to version 1.1.0
  recipes/colord/meta.yaml
Labels: please review & merge

#31454 Update comet-ms recipe
  build-fail-blacklist
  recipes/comet-ms/build.sh
  recipes/comet-ms/meta.yaml
Labels: please review & merge

#31572 Update cirtap
  recipes/cirtap/meta.yaml
Labels: please review & merge

#31566 Add naf
  recipes/naf/build.sh
  recipes/naf/meta.yaml
Labels: please review & merge

#31582 Add freyja recipe
  recipes/freyja/meta.yaml
Labels: please review & merge

#31603 sarscov2formatter remove pyyaml requirement
  recipes/sarscov2formatter/meta.yaml
Labels: please review & merge

#31590 Fix recipe for naf 1.3.0: remove unused dependency
  recipes/naf/meta.yaml
Labels: please review & merge

#31587 Add pggb (PanGenome Graph Builder)
  recipes/pggb/build.sh
  recipes/pggb/meta.yaml
Labels: please review & merge

#31546 Update links to 2.0.0
  recipes/links/build.sh
  recipes/links/links-osx.patch
  recipes/links/links.patch
  recipes/links/meta.yaml
Labels: please review & merge

#31560 Add dependencies for bioconductor-structtoolbox
  recipes/bioconductor-structtoolbox/meta.yaml
Labels: please review & merge

#31592 Add MSMetaEnhancer
  recipes/msmetaenhancer/meta.yaml
Labels: please review & merge, automerge

#31644 sarscov2formatter bump
  recipes/sarscov2formatter/meta.yaml
Labels: please review & merge

#31645 Update gecco to v0.8.5
  recipes/gecco/meta.yaml
Labels: please review & merge

#31648 [bamtocov] remove variants, add zlib
  recipes/bamtocov/build.sh
  recipes/bamtocov/conda_build_config.yaml
  recipes/bamtocov/meta.yaml
Labels: please review & merge

#31526 Add genview build files to bioconda
  recipes/genview/LICENSE.md
  recipes/genview/meta.yaml
Labels: please review & merge

#31659 Update perbase deps
  recipes/perbase/meta.yaml
Labels: please review & merge

#31663 Patch Emu
  recipes/emu/meta.yaml
Labels: please review & merge

#31670 Update transrate: fix dependency
  recipes/transrate/meta.yaml
Labels: please review & merge

#31683 update freyja
  recipes/freyja/meta.yaml
Labels: please review & merge

#31691 gatk4: relax JDK requirement
  recipes/gatk4/meta.yaml
Labels: please review & merge

#31699 Update cgat-apps
  recipes/cgat-apps/meta.yaml
Labels: please review & merge

#31427 Add CORSID
  recipes/corsid/meta.yaml
Labels: please review & merge

#31706 Update dicey to 0.1.8
  recipes/dicey/meta.yaml
Labels: please review & merge

#31709 Update cgat-daisy to v1.10.0
  recipes/cgat-daisy/meta.yaml
Labels: please review & merge

#31722 Funannotate: restrict to matplotlib <3.5
  recipes/funannotate/meta.yaml
Labels: please review & merge

#31729 Add snap-aligner/1.0dev.96
  recipes/snap-aligner/1.0dev.96/build.sh
  recipes/snap-aligner/1.0dev.96/meta.yaml
Labels: please review & merge

#31731 [seqfu] Update build
  recipes/seqfu/build.sh
  recipes/seqfu/meta.yaml
Labels: please review & merge

#31740 update: bump nextalign to 1.5.0
  recipes/nextalign/meta.yaml
Labels: please review & merge

#31739 update: nextclade to 1.5.0
  recipes/nextclade/meta.yaml
Labels: please review & merge

#31745 Added recipe for cutqc, a wrapper to invoke cutadapt and fastqc to trim fastq files
  recipes/cutqc/build.sh
  recipes/cutqc/meta.yaml
Labels: please review & merge

#31765 update: nextclade to 1.5.1
  recipes/nextclade/meta.yaml
Labels: please review & merge

#31766 update: nextalign to 1.5.1
  recipes/nextalign/meta.yaml
Labels: please review & merge

#31774 Update vcfanno to 0.3.3.
  recipes/vcfanno/meta.yaml
Labels: please review & merge

#31754 Add methylartist 1.0.6
  recipes/methylartist/meta.yaml
Labels: please review & merge

#31780 update PPanGGOLiN dependencies
  recipes/ppanggolin/meta.yaml
Labels: please review & merge
