Repository bioconda/bioconda-recipes, pull requests merged in 2021-03, with the labels that each got.

#27047 Update GROMACS to fix AVX1 and AVX2 on OSX
  recipes/gromacs/2020/build.sh
  recipes/gromacs/2020/meta.yaml
Labels: please review & merge

#25918 update dms
  recipes/dms/build.sh
  recipes/dms/meta.yaml
Labels: please review & merge

#26980 recipe for building leeHom
  recipes/leehom/build.sh
  recipes/leehom/meta.yaml
Labels: please review & merge

#27115 Update r-acidgenerics to v0.5.16
  recipes/r-acidgenerics/meta.yaml
Labels: please review & merge

#27119 Update r-goalie to v0.5.0
  recipes/r-goalie/meta.yaml
Labels: please review & merge

#27104 Update flight-genome to v1.1.0
  recipes/flight-genome/meta.yaml
Labels: please review & merge

#27123 Create shared lib for vcflib
  recipes/vcflib/meta.yaml
  recipes/vcflib/pkg-config.patch
  recipes/vcflib/shared_lib.patch
Labels: please review & merge

#27116 Update krona recipe to extended-base image
  recipes/krona/2.7.1/meta.yaml
  recipes/krona/meta.yaml
Labels: please review & merge

#27106 Update Rosella to v0.3.0
  recipes/rosella/meta.yaml
Labels: please review & merge

#27112 Update deepnog: require PyTorch
  recipes/deepnog/meta.yaml
Labels: please review & merge

#27128 metaclassifier recipe
  recipes/metaclassifier/meta.yaml
Labels: please review & merge

#27126 update balrog
  recipes/balrog/meta.yaml
Labels: please review & merge

#27134 Rodeo
  recipes/rodeo/meta.yaml
  recipes/rodeo/run_test.sh
Labels: please review & merge

#27117 Fix Pandas/NumPy incompatibility in IgDiscover
  recipes/igdiscover/meta.yaml
Labels: please review & merge

#27092 Add mg-toolkit
  recipes/mg-toolkit/meta.yaml
Labels: please review & merge

#26897 Add metagraph
  recipes/metagraph/build.sh
  recipes/metagraph/conda_build_config.yaml
  recipes/metagraph/meta.yaml
Labels: please review & merge

#27161 Update ngs-bits to version 2021_03
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#27203 Update `pyrodigal` recipe to `v0.4.6` and make it run unit tests
  recipes/pyrodigal/meta.yaml
Labels: please review & merge

#27213 update SmallGenomeUtilities to 0.3.2
  recipes/smallgenomeutilities/0.3.2/meta.yaml
Labels: please review & merge

#27188 Add Auspice package
  recipes/auspice/build.sh
  recipes/auspice/meta.yaml
Labels: please review & merge

#27224 Update Sha-256
  recipes/submission-tool-validator/meta.yaml
Labels: please review & merge

#27214 Bump up DeepBGC to 0.1.26
  recipes/deepbgc/meta.yaml
Labels: please review & merge

#27145 Update vcflib to use bioconda libssw
  recipes/vcflib/build.sh
  recipes/vcflib/meta.yaml
  recipes/vcflib/shared_lib.patch
  recipes/vcflib/shared_ssw.patch
Labels: please review & merge

#27199 unimap: Add new package, version 0.1
  recipes/unimap/0001-gh-4-Consider-LDFLAGS-while-linking.patch
  recipes/unimap/build.sh
  recipes/unimap/meta.yaml
Labels: please review & merge

#27200 winnowmap: Add new package, version 2.0
  recipes/winnowmap/0001-Un-vendor-meryl.patch
  recipes/winnowmap/build.sh
  recipes/winnowmap/meta.yaml
Labels: please review & merge

#27198 bedtk: Add new package, version 0.0r25dirty
  recipes/bedtk/build.sh
  recipes/bedtk/meta.yaml
Labels: please review & merge

#27186 Update secimtools package recipe to 21.3.4.2
  build-fail-blacklist
  recipes/secimtools/meta.yaml
Labels: please review & merge

#27234 dadaist2, update deps
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#27239 Update bio_hansel to v2.6.1
  recipes/bio_hansel/meta.yaml
Labels: please review & merge

#27237 Add simde files to include directory for VCFLIB installation
  recipes/vcflib/build.sh
  recipes/vcflib/meta.yaml
Labels: please review & merge

#27207 Update CONSTAX to 2.0.7
  recipes/constax/build.sh
  recipes/constax/meta.yaml
Labels: please review & merge

#27193 Add nextstrain meta-package
  recipes/nextstrain/meta.yaml
Labels: please review & merge

#27250 Update MultiQC to 1.10
  recipes/multiqc/meta.yaml
Labels: please review & merge

#27245 Create pkg-config.patch for tabixpp
  recipes/tabixpp/meta.yaml
  recipes/tabixpp/pkg-config.patch
Labels: please review & merge

#27274 Update Jalview 2.11.1.4
  recipes/jalview/jalview.sh
  recipes/jalview/meta.yaml
Labels: please review & merge

#27271 [ADD] dadaist2-full meta package
  recipes/dadaist2-full/meta.yaml
Labels: please review & merge

#27273 Phylics
  build-fail-blacklist
  recipes/phylics/build.sh
  recipes/phylics/meta.yaml
Labels: please review & merge

#27286 bump/libmaus2
  recipes/libmaus2/meta.yaml
Labels: please review & merge

#27289 Update PanTools to 3.1.0
  recipes/pantools/meta.yaml
Labels: please review & merge

#27297 Add VIRULIGN v1.0.2
  recipes/virulign/build.sh
  recipes/virulign/meta.yaml
Labels: please review & merge

#27302 fix metaphlan-2.8.1
  recipes/metaphlan/2.8.1/meta.yaml
  recipes/metaphlan/meta.yaml
Labels: bug

#27305 Update: SG 4.0.22 & PS 2.0.14
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#27306 [dadaist2] update dependencies
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#27264 Update to gromacs 2021
  recipes/gromacs/2018/build.sh
  recipes/gromacs/2018/meta.yaml
  recipes/gromacs/2019/build.sh
  recipes/gromacs/2021/0001-add-header.patch
  recipes/gromacs/2021/activate.sh
  recipes/gromacs/2021/build.sh
  recipes/gromacs/2021/gmx-chooser.bash
  recipes/gromacs/2021/meta.yaml
  recipes/gromacs/README.md
Labels: please review & merge

#27307 Add Pyclone vi
  recipes/pyclone-vi/meta.yaml
Labels: please review & merge

#27318 update refgenconf after release
  recipes/refgenconf/meta.yaml
Labels: please review & merge

#27011 Update build for freebayes to include scripts
  recipes/freebayes/build.sh
  recipes/freebayes/meson.patch
  recipes/freebayes/meta.yaml
Labels: please review & merge

#27324 update refgenieserver recipe after release
  recipes/refgenieserver/meta.yaml
Labels: please review & merge

#27323 update refgenie after release
  recipes/refgenie/meta.yaml
Labels: please review & merge

#27262 Add PhyloCSF++ recipe (v1.0.0)
  recipes/phylocsfpp/build.sh
  recipes/phylocsfpp/meta.yaml
Labels: please review & merge

#27335 Update staden_io_lib
  recipes/staden_io_lib/meta.yaml
Labels: new version, please review & merge

#27336 Update dependencies for libmaus2
  recipes/libmaus2/build.sh
  recipes/libmaus2/meta.yaml
Labels: please review & merge

#27338 Update altamisa sources
  recipes/altamisa/0.2.0/meta.yaml
  recipes/altamisa/0.2.1/meta.yaml
  recipes/altamisa/0.2.2/meta.yaml
  recipes/altamisa/0.2.3/meta.yaml
  recipes/altamisa/0.2.4/meta.yaml
  recipes/altamisa/0.2.5/meta.yaml
  recipes/altamisa/0.2.6/meta.yaml
Labels: please review & merge

#27345 more dependencies in v2.2
  recipes/gnuvid/meta.yaml
Labels: please review & merge

#27276 update_pepquery
  recipes/pepquery/build.sh
  recipes/pepquery/meta.yaml
  recipes/pepquery/pepquery.sh
Labels: please review & merge

#27337 Update blast to 2.11.0
  recipes/blast/get_species_taxids.patch
  recipes/blast/meta.yaml
Labels: please review & merge

#27310 Update HiLine, add python39 build
  recipes/hiline/conda_build_config.yaml
  recipes/hiline/meta.yaml
Labels: please review & merge

#27282 bump clinker-py to v0.0.19
  recipes/clinker-py/meta.yaml
Labels: please review & merge

#27329 Update galaxy_ml
  recipes/galaxy-ml/meta.yaml
Labels: please review & merge

#27359 Update: PeptideShaker updated to 2.0.15
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
Labels: please review & merge

#27157 Update scvi-tools
  recipes/scvi-tools/meta.yaml
Labels: please review & merge

#27344 Properly limiting python version of freebayes recipe.
  recipes/freebayes/meta.yaml
Labels: please review & merge

#27369 Add BacGWASim 2.0.0
  recipes/bacgwasim/meta.yaml
Labels: please review & merge

#27249 Update RNAblueprint to 1.3.2
  recipes/rnablueprint/build.sh
  recipes/rnablueprint/meta.yaml
Labels: please review & merge

#27378 Update BacGWASim
  recipes/bacgwasim/meta.yaml
Labels: please review & merge

#27384 Update funannotate v1.8.5 pin less than diamond v2.0.8 as breaks code
  recipes/funannotate/meta.yaml
Labels: please review & merge

#27353 Update coconet-binning to v1.0.0
  recipes/coconet-binning/meta.yaml
Labels: please review & merge

#27390 Update jbrowse to 1.16.11
  recipes/jbrowse/meta.yaml
Labels: please review & merge

#27330 updated shiver recipe to new version
  recipes/shiver/meta.yaml
Labels: please review & merge

#27380 Update RNAblueprint: Fix release package distribution
  recipes/rnablueprint/meta.yaml
Labels: please review & merge

#27397 Update adam to 0.34.0
  recipes/adam/meta.yaml
Labels: please review & merge

#27399 Update dsh-bio to 2.0.3
  recipes/dsh-bio/build.sh
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#27398 Update cannoli to 0.12.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#27391 Update seroba to 1.0.2
  recipes/seroba/meta.yaml
Labels: please review & merge

#27406 Update gNALI recipe
  recipes/gnali/meta.yaml
Labels: please review & merge

#27401 Update wiggletools: remove superfluous prerequisites and tidy up recipe
  recipes/wiggletools/build.sh
  recipes/wiggletools/meta.yaml
Labels: please review & merge

#27395 fix/io_lib
  recipes/staden_io_lib/enable-custom-buffering-for-cram_bambam.patch
  recipes/staden_io_lib/enable-custom-buffering-for-cram_bambam2.patch
  recipes/staden_io_lib/init_order.patch
  recipes/staden_io_lib/meta.yaml
Labels: please review & merge

#27385 Update galaxy-ml
  recipes/galaxy-ml/meta.yaml
Labels: please review & merge

#27393 update coconet-binning to 1.1.0
  recipes/coconet-binning/meta.yaml
Labels: please review & merge

#27411 Add SCALOP package
  recipes/scalop/meta.yaml
Labels: please review & merge

#27409 Move perl and python dependencies to remove them from pinnings
  recipes/gromacs/2020/meta.yaml
Labels: please review & merge

#27448 Update LAST
  recipes/last/meta.yaml
Labels: please review & merge

#27334 Add GROMACS mpi recipe
  recipes/gromacs_mpi/2021/0001-Fix-OpenCL-build-on-OSX.patch
  recipes/gromacs_mpi/2021/activate.sh
  recipes/gromacs_mpi/2021/build.sh
  recipes/gromacs_mpi/2021/conda_build_config.yaml
  recipes/gromacs_mpi/2021/gmx-chooser.bash
  recipes/gromacs_mpi/2021/meta.yaml
  recipes/gromacs_mpi/README.md
Labels: please review & merge

#27438 Update GROMACS 2021: Move perl and python dependencies
  recipes/gromacs/2021/meta.yaml
Labels: please review & merge

#27452 update xtea
  recipes/xtea/meta.yaml
Labels: please review & merge

#27432 update staden_io_lib: clean up patches, bump version
  recipes/staden_io_lib/enable-custom-buffering-for-cram_bambam.patch
  recipes/staden_io_lib/enable-custom-buffering-for-cram_bambam2.patch
  recipes/staden_io_lib/init_order.patch
  recipes/staden_io_lib/meta.yaml
Labels: please review & merge

#27446 Update augur's dependencies to include xopen
  recipes/augur/meta.yaml
Labels: please review & merge

#25501 Add seidr - a gene network inference toolkit
  recipes/seidr/build.sh
  recipes/seidr/conda_build_config.yaml
  recipes/seidr/meta.yaml
Labels: please review & merge

#27459 Add recipe for alv, a command line alignment viewer
  recipes/alv/LICENSE
  recipes/alv/meta.yaml
Labels: please review & merge

#27475 Add: r-qtlseqr recipe
  recipes/r-qtlseqr/build.sh
  recipes/r-qtlseqr/meta.yaml
Labels: please review & merge

#27477 Update Bracken to v2.6.1
  recipes/bracken/ctime.patch
  recipes/bracken/meta.yaml
  recipes/bracken/osx.patch
Labels: please review & merge

#27485 Update KrakenTools to v1.0.1
  recipes/krakentools/build.sh
  recipes/krakentools/meta.yaml
  recipes/krakentools/patch_combine_kreports.py
  recipes/krakentools/patch_extract_kraken_reads.py
  recipes/krakentools/patch_filter_bracken.out.py
  recipes/krakentools/patch_fix_unmapped.py
  recipes/krakentools/patch_kreport2krona.py
  recipes/krakentools/patch_make_kreport.py
  recipes/krakentools/patch_make_ktaxonomy.py
Labels: please review & merge

#27482 Update bactopia to v1.6.2
  recipes/bactopia/meta.yaml
Labels: please review & merge

#27321 update spatyper - drop blake_sha256 requirement
  recipes/spatyper/meta.yaml
Labels: please review & merge

#27511 Update Ariba pinning in Bactopia
  recipes/bactopia/meta.yaml
Labels: please review & merge

#27260 Add Ra assembler
  recipes/ra/ra-assembler/build.sh
  recipes/ra/ra-assembler/meta.yaml
  recipes/ra/ra-assembler/minimap2.makefile.patch
Labels: please review & merge

#27366 debug Libmaus2 build
  recipes/libmaus2/build.sh
  recipes/libmaus2/meta.yaml
  recipes/libmaus2/patch2
Labels: new version, please review & merge

#27506 Add Lissero recipe
  recipes/lissero/meta.yaml
Labels: please review & merge

#25665 Add ngmaster v0.5.8
  recipes/ngmaster/meta.yaml
Labels: please review & merge

#27464 Add Abacas recipe
  recipes/abacas/build.sh
  recipes/abacas/meta.yaml
  recipes/abacas/patches/path.patch
Labels: please review & merge

#27480 Update plasmidid recipe with new version
  recipes/plasmidid/meta.yaml
Labels: please review & merge

#27347 Update biobambam - Clean messy build
  recipes/biobambam/build.sh
  recipes/biobambam/meta.yaml
Labels: new version, please review & merge

#27554 Update Elprep
  recipes/elprep/build.sh
  recipes/elprep/meta.yaml
Labels: new version, please review & merge

#27545 Add smartmap recipe
  recipes/smartmap/0001-fix-flags-for-bioconda.patch
  recipes/smartmap/build.sh
  recipes/smartmap/meta.yaml
Labels: please review & merge

#27534 Update poppunk to v2.4.0
  recipes/poppunk/meta.yaml
Labels: please review & merge

#27571 Add Meningotype
  recipes/meningotype/meta.yaml
Labels: please review & merge

#27437 Update Plink to v1.90b6.21
  recipes/plink/meta.yaml
Labels: please review & merge

#27547 Update shiver
  recipes/shiver/0001-changed-tools-to-shiver_tools.patch
  recipes/shiver/0002-changed-python2-to-python.patch
  recipes/shiver/0003-added-fastaq-installation-on-demand.patch
  recipes/shiver/0004-fixed-pyfastaq-installation.patch
  recipes/shiver/build.sh
  recipes/shiver/meta.yaml
Labels: please review & merge

#27580 Update PSASS version and URL
  recipes/psass/meta.yaml
Labels: please review & merge

#27563 update vep: bump plugins version
  recipes/ensembl-vep/build.sh
  recipes/ensembl-vep/meta.yaml
Labels: please review & merge

#27558 Update radsex to 1.1.3 + osx build
  recipes/radsex/meta.yaml
Labels: please review & merge

#27322 Update GROMACS to 2021.1
  recipes/gromacs/2021/meta.yaml
Labels: please review & merge

#27574 Add leviosam recipe
  recipes/leviosam/build.sh
  recipes/leviosam/meta.yaml
Labels: please review & merge

#27576 Adding hifiasm_meta
  recipes/hifiasm_meta/build.sh
  recipes/hifiasm_meta/meta.yaml
Labels: please review & merge

#27095 Update realphy to 1.13
  recipes/realphy/build.sh
  recipes/realphy/meta.yaml
Labels: please review & merge

#27597 Fix meningotype recipe
  recipes/meningotype/meta.yaml
Labels: please review & merge

#26848 Add recipe MAPseq v1.2.6
  recipes/mapseq/build.sh
  recipes/mapseq/meta.yaml
  recipes/mapseq/post-link.sh
Labels: please review & merge

#27540 Update galaxy_ml to v0.8.3
  recipes/galaxy-ml/meta.yaml
Labels: please review & merge

#27584 Add zpca recipe
  recipes/zpca/meta.yaml
Labels: please review & merge

#27546 Add python-codon-tables
  recipes/python-codon-tables/meta.yaml
Labels: please review & merge

#27496 updated machina recipe to work on osx
  recipes/machina/build.sh
  recipes/machina/meta.yaml
Labels: please review & merge

#27516 modified HATCHet recipe to work on osx
  recipes/hatchet/build.sh
  recipes/hatchet/meta.yaml
Labels: help wanted, please review & merge

#27418 Add r-acidcli 0.1.0
  recipes/r-acidcli/build.sh
  recipes/r-acidcli/meta.yaml
Labels: please review & merge

#27201 dipcall: Add new package, version 0.2
  recipes/dipcall/build.sh
  recipes/dipcall/meta.yaml
Labels: please review & merge

#27607 Add renet v1.2
  recipes/renet2/meta.yaml
Labels: please review & merge

#27611 Update wisecondorX
  recipes/wisecondorx/meta.yaml
Labels: please review & merge

#27613 Update virulign to v1.1
  recipes/virulign/meta.yaml
Labels: please review & merge

#27492 Add isoplot package
  recipes/isoplot/LICENSE.txt
  recipes/isoplot/meta.yaml
Labels: please review & merge

#27609 Add Hopla
  recipes/hopla/build.sh
  recipes/hopla/meta.yaml
Labels: please review & merge

#27619 Add panoptes (panoptes-ui) recipe
  recipes/panoptes-ui/meta.yaml
Labels: please review & merge

#27626 Add dnachisel recipe
  recipes/dnachisel/LICENCE.txt
  recipes/dnachisel/meta.yaml
Labels: please review & merge

#27628 update meta.yaml
  recipes/xtea/meta.yaml
Labels: please review & merge

#27627 Update isescan meta.yaml to remove the pathes
  recipes/isescan/meta.yaml
Labels: please review & merge

#27622 Update r-syntactic to 0.4.5
  recipes/r-syntactic/meta.yaml
Labels: please review & merge

#27636 add multitax recipe
  recipes/multitax/meta.yaml
Labels: please review & merge

#27637 Update IsoQuant to 1.2.0
  recipes/isoquant/meta.yaml
Labels: please review & merge

#27651 update meta.yaml
  recipes/xtea/meta.yaml
Labels: please review & merge

#27657 Add extracthifi
  recipes/extracthifi/build.sh
  recipes/extracthifi/meta.yaml
  recipes/extracthifi/post-link.sh
Labels: please review & merge

#27655 Update GraphAligner to version 1.0.13
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#27661 Updata Hopla - add missing dependency
  recipes/hopla/meta.yaml
Labels: please review & merge

#27662 Update malt to v0.5.2
  recipes/malt/build.sh
  recipes/malt/meta.yaml
Labels: please review & merge

#27666 Update to v2.2
  recipes/virsorter/meta.yaml
Labels: please review & merge

#27650 Updating dipcall recipe - adding bedtk depdendency
  recipes/dipcall/meta.yaml
Labels: please review & merge

#27687 Upgrade IQ-TREE to v2.1.2
  recipes/iqtree/0001-PATCH-macos-10.9.patch
  recipes/iqtree/build.sh
  recipes/iqtree/conda_build_config.yaml
  recipes/iqtree/meta.yaml
Labels: please review & merge

#27683 dipcall: Fix version
  recipes/dipcall/meta.yaml
Labels: please review & merge

#27685 Add zmwfilter
  recipes/zmwfilter/build.sh
  recipes/zmwfilter/meta.yaml
  recipes/zmwfilter/post-link.sh
Labels: please review & merge

#27684 Update savvy to 2.0.0
  recipes/savvy/build.sh
  recipes/savvy/meta.yaml
  recipes/savvy/patches/0001-patch-cmakelists-for-conda-build.patch
Labels: please review & merge

#27696 Add exome resources verifybamid2 to build.
  recipes/verifybamid2/build.sh
  recipes/verifybamid2/meta.yaml
Labels: please review & merge

#27703 Update meta.yaml
  recipes/liftoff/meta.yaml
Labels: please review & merge

#27701 Add recipe for COBS + python extension
  recipes/cobs/0001-Add-openmp-to-compile-flags.patch
  recipes/cobs/meta.yaml
Labels: please review & merge
