Repository bioconda/bioconda-recipes, pull requests merged in 2021-08, with the labels that each got.

#29859 Update pangolearn to 2021-07-28
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#29650 Added lrphase package
  recipes/lrphase/meta.yaml
Labels: please review & merge

#29901 Update velocyto.py: Add missing samtools dependency
  recipes/velocyto.py/meta.yaml
Labels: please review & merge

#29909 Update GeneRax to v2.0.4
  recipes/generax/meta.yaml
Labels: please review & merge

#29898 New recipe: slaMEM
  recipes/slamem/LICENSE
  recipes/slamem/build.sh
  recipes/slamem/meta.yaml
Labels: please review & merge

#29887 add hgvs
  recipes/hgvs/meta.yaml
Labels: please review & merge

#29926 add recipe for sra-human-scrubber
  recipes/sra-human-scrubber/build.sh
  recipes/sra-human-scrubber/fix_init_db_path.patch
  recipes/sra-human-scrubber/fix_scrub_path.patch
  recipes/sra-human-scrubber/meta.yaml
  recipes/sra-human-scrubber/post-link.sh
Labels: please review & merge

#29877 Add endorspy
  recipes/endorspy/build.sh
  recipes/endorspy/meta.yaml
Labels: please review & merge

#29943 Add TELR
  recipes/telr/meta.yaml
Labels: please review & merge

#29229 Meta-apo
  recipes/meta-apo/build.sh
  recipes/meta-apo/meta.yaml
Labels: please review & merge

#29949 Add baredSC recipe
  recipes/baredsc/meta.yaml
Labels: please review & merge

#29941 Add recipe for ggmsa
  recipes/r-ggmsa/build.sh
  recipes/r-ggmsa/meta.yaml
Labels: please review & merge

#29919 Update rnastructure and add mac OS build
  recipes/rnastructure/build.sh
  recipes/rnastructure/meta.yaml
Labels: please review & merge

#29960 Update TELR dependencies
  recipes/telr/meta.yaml
Labels: please review & merge

#29963 update viewbs: a small bug fix
  recipes/viewbs/build.sh
  recipes/viewbs/meta.yaml
Labels: please review & merge

#29991 Update vadr build
  recipes/vadr/build.sh
  recipes/vadr/download-vadr-models.sh
  recipes/vadr/meta.yaml
Labels: please review & merge

#29962 Add BioPhi first release
  recipes/biophi/meta.yaml
Labels: please review & merge

#29996 Update metaSNV to 2.0.0
  recipes/metasnv/build.sh
  recipes/metasnv/meta.yaml
Labels: please review & merge

#29982 Peakhoodv02
  recipes/peakhood/meta.yaml
Labels: please review & merge

#30006 Add r-seqmagick
  recipes/r-seqmagick/build.sh
  recipes/r-seqmagick/meta.yaml
Labels: please review & merge

#30003 Add sonneityping
  recipes/sonneityping/build.sh
  recipes/sonneityping/meta.yaml
  recipes/sonneityping/parse_mykrobe_predict
Labels: please review & merge

#30011 updating Duet to v0.3
  recipes/duet/meta.yaml
Labels: please review & merge

#30009 Update nextclade to version 1.2.1
  recipes/nextclade/meta.yaml
Labels: please review & merge

#30020 Update r-ggmsa
  recipes/r-ggmsa/meta.yaml
Labels: please review & merge

#30022 metaSNV: add missing dependency
  recipes/metasnv/meta.yaml
Labels: please review & merge

#30032 Update auspice to 2.29.1
  recipes/auspice/meta.yaml
Labels: please review & merge

#29615 bump scvi-tools to v0.12.2
  recipes/scvi-tools/meta.yaml
Labels: please review & merge

#30014 Updated SemiBin to 0.3
  recipes/semibin/changes.patch
  recipes/semibin/meta.yaml
Labels: please review & merge

#30036 Fix jcvi - Add new deps
  recipes/jcvi/meta.yaml
Labels: please review & merge

#30046 Update bedtools license
  recipes/bedtools/meta.yaml
Labels: please review & merge

#30058 Update celltypist to 0.1.4
  recipes/celltypist/meta.yaml
Labels: please review & merge

#30071 Update CRISPResso2 to v2.2.0
  recipes/crispresso2/meta.yaml
Labels: please review & merge

#30074 update smoothxg to v.0.6.0
  recipes/smoothxg/meta.yaml
Labels: please review & merge

#30081 Update augur to 12.1.1
  recipes/augur/meta.yaml
Labels: please review & merge, automerge

#30090 Update build number for shovill-se
  recipes/shovill-se/meta.yaml
Labels: please review & merge

#30089 Meta apo
  recipes/meta-apo/build.sh
  recipes/meta-apo/meta.yaml
Labels: please review & merge

#30097 Update nextclade to version 1.2.3
  recipes/nextclade/meta.yaml
Labels: please review & merge

#30098 Update nextalign to version 1.2.3
  recipes/nextalign/meta.yaml
Labels: please review & merge

#30088 uLTRA aligner
  recipes/ultra_bioinformatics/LICENSE
  recipes/ultra_bioinformatics/meta.yaml
Labels: please review & merge

#30099 add recipe for Titan-GC
  recipes/titan-gc/build.sh
  recipes/titan-gc/fix_version.patch
  recipes/titan-gc/meta.yaml
Labels: please review & merge

#29965 Add hesslab-gambit
  recipes/hesslab-gambit/meta.yaml
  recipes/hesslab-gambit/run_test.sh
Labels: help wanted

#30065 update publication info add test to labrat
  recipes/labrat/meta.yaml
Labels: please review & merge

#30113 Ultra - update recipe
  recipes/ultra_bioinformatics/meta.yaml
Labels: please review & merge

#30138 Update nextclade to include a package-appropriate version of the nextclade data
  recipes/nextclade/build.sh
  recipes/nextclade/meta.yaml
  recipes/nextclade/post-link.sh
Labels: please review & merge

#30111 Add riassigner 0.2.0
  recipes/riassigner/meta.yaml
Labels: please review & merge

#30131 Add new recipe for GFAffix (pangenomics)
  recipes/gfaffix/build.sh
  recipes/gfaffix/meta.yaml
Labels: please review & merge

#30145 Change requirements in abnumber
  recipes/abnumber/meta.yaml
Labels: please review & merge

#30171 Add stecfinder
  recipes/stecfinder/meta.yaml
Labels: please review & merge

#30172 adding abismal 1.0.0
  recipes/abismal/build.sh
  recipes/abismal/meta.yaml
Labels: please review & merge

#30155 Meta apo
  recipes/meta-apo/build.sh
  recipes/meta-apo/meta.yaml
Labels: please review & merge

#30152 Rebuild augustus 3.3.3
  recipes/augustus/3.3.3/Build.PL
  recipes/augustus/3.3.3/build.sh
  recipes/augustus/3.3.3/meta.yaml
  recipes/augustus/3.3.3/patches/bam2hints.makefile.patch
  recipes/augustus/3.3.3/patches/bam2wig.makefile.patch
  recipes/augustus/3.3.3/patches/compileSpliceCands.makefile.patch
  recipes/augustus/3.3.3/patches/filterBam.makefile.patch
  recipes/augustus/3.3.3/patches/filterBam.src.makefile.patch
  recipes/augustus/3.3.3/patches/filterBam.src.makefile.patch.osx
  recipes/augustus/3.3.3/patches/homGeneMapping.src.makefile.patch
  recipes/augustus/3.3.3/patches/joingenes.makefile.patch
  recipes/augustus/3.3.3/patches/src.makefile.patch
  recipes/augustus/3.3.3/patches/utrrnaseq.patch
  recipes/augustus/3.3.3/patches/utrrnaseq.src.patch
Labels: please review & merge

#29997 Add bamAlignCleaner
  recipes/bamaligncleaner/LICENSE
  recipes/bamaligncleaner/meta.yaml
Labels: please review & merge

#30168 Add recipe for RogueNaRok
  recipes/roguenarok/build.sh
  recipes/roguenarok/exit-h.patch
  recipes/roguenarok/fcommon.patch
  recipes/roguenarok/meta.yaml
Labels: please review & merge, automerge

#30183 Update adam to 0.36.0
  recipes/adam/meta.yaml
Labels: please review & merge

#30184 Update cannoli to 0.14.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#29865 Added HDF5 plugin for ONT VBZ compression
  recipes/ont_vbz_hdf_plugin/build.sh
  recipes/ont_vbz_hdf_plugin/meta.yaml
  recipes/ont_vbz_hdf_plugin/run_test.sh
Labels: please review & merge

#30048 Add metabinner recipes
  recipes/metabinner/build.sh
  recipes/metabinner/meta.yaml
Labels: please review & merge

#30165 Fast pcst
  recipes/pcst-fast/meta.yaml
Labels: please review & merge

#30203 Add Domino
  recipes/domino/meta.yaml
Labels: please review & merge

#30226 Update cmseq
  recipes/cmseq/meta.yaml
Labels: please review & merge

#30223 Add slow5tools recipi
  recipes/slow5tools/build.sh
  recipes/slow5tools/meta.yaml
Labels: please review & merge

#30205 Update smallgenomeutilities to version 0.3.4
  recipes/smallgenomeutilities/0.3.4/meta.yaml
Labels: please review & merge

#30208 Update kneaddata recipe to newer version
  recipes/kneaddata/meta.yaml
Labels: please review & merge

#30227 Update ganon to 1.0.0
  recipes/ganon/build.sh
  recipes/ganon/meta.yaml
Labels: please review & merge

#30175 add recipe: Illumina Dragmap
  recipes/dragmap/build.sh
  recipes/dragmap/meta.yaml
Labels: please review & merge

#30239 Add nopilesum
  recipes/nopilesum/build.sh
  recipes/nopilesum/meta.yaml
Labels: please review & merge

#30225 add pyslow5
  recipes/pyslow5/build.sh
  recipes/pyslow5/meta.yaml
Labels: please review & merge

#30213 Update Domino
  recipes/domino/meta.yaml
  recipes/pcst-fast/meta.yaml
Labels: please review & merge

#30247 Update MALT to 0.53
  recipes/malt/build.sh
  recipes/malt/meta.yaml
Labels: please review & merge

#30294 update version and package to 0.4.4
  recipes/mimsi/meta.yaml
Labels: please review & merge

#30301 Update SeqKit to 2.0.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#30297 Add rd-analyzer recipe
  recipes/rd-analyzer/build.sh
  recipes/rd-analyzer/meta.yaml
  recipes/rd-analyzer/patch-ref-location
Labels: please review & merge

#30302 fix valet: bowtie2 libtbb problem
  recipes/valet/meta.yaml
Labels: please review & merge

#30313 Update sevenbridges-python maintainers
  recipes/sevenbridges-python/meta.yaml
Labels: please review & merge

#30314 Update to pangoLEARN 2021-08-24
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#30309 Update irida-uploader: remove extended_base
  recipes/irida-uploader/meta.yaml
Labels: please review & merge, automerge

#30316 Update pangolin to use ca-certificates and the latest cov-lineages dependencies
  recipes/pangolin/meta.yaml
Labels: automerge

#30326 Update for nextclade 1.3.0
  recipes/nextclade/build.sh
  recipes/nextclade/meta.yaml
  recipes/nextclade/post-link.sh
Labels: please review & merge, automerge

#30299 Update pins for dram
  recipes/dram/meta.yaml
Labels: automerge

#30323 Updated HATCHet to 0.4.6
  recipes/hatchet/meta.yaml
Labels: automerge

#30322 bump sirius
  recipes/sirius-csifingerid/build.sh
  recipes/sirius-csifingerid/meta.yaml
Labels: automerge

#30292 add oncoenrichr dependencies
  recipes/r-gganatogram/build.sh
  recipes/r-gganatogram/gpl-2.0.txt
  recipes/r-gganatogram/meta.yaml
  recipes/r-oncopharmadb/build.sh
  recipes/r-oncopharmadb/meta.yaml
Labels: please review & merge, automerge

#30330 Update to nextalign 1.3.0
  recipes/nextalign/meta.yaml
Labels: please review & merge
