Repository bioconda/bioconda-recipes, pull requests merged in 2021-07, with the labels that each got.

#29364 Add: first build for microphaser
  recipes/microphaser/build.sh
  recipes/microphaser/meta.yaml
Labels: please review & merge

#28278 Add DeepSig v1.0
  recipes/deepsig/activate.sh
  recipes/deepsig/build.sh
  recipes/deepsig/deactivate.sh
  recipes/deepsig/meta.yaml
Labels: please review & merge

#29323 Update sentieon recipe to version 202010.02
  recipes/sentieon/build.sh
  recipes/sentieon/bwa_symlinks.patch
  recipes/sentieon/meta.yaml
  recipes/sentieon/sentieon_symlinks.patch
Labels: please review & merge

#29373 Update plasclass
  recipes/plasclass/meta.yaml
Labels: please review & merge

#29369 Add cuttlefish recipe
  recipes/cuttlefish/build.sh
  recipes/cuttlefish/meta.yaml
Labels: please review & merge

#29376 Update Cuttlefish build
  recipes/cuttlefish/build.sh
  recipes/cuttlefish/meta.yaml
Labels: please review & merge

#29371 Update BioExt to 0.20.1
  build-fail-blacklist
  recipes/python-bioext/meta.yaml
  recipes/python-bioext/scipy-stats.patch
Labels: enhancement, new version, please review & merge

#29383 Revert "[ci skip] Merge PR 28871"
  recipes/bcftools/1.5/b37b03e815cd4f25af70a57c08449f8c719dcc6a.patch
  recipes/bcftools/1.5/build.sh
  recipes/bcftools/1.5/meta.yaml
Labels: please review & merge

#29388 Add recipe for PyDamage
  recipes/pydamage/LICENSE
  recipes/pydamage/meta.yaml
Labels: please review & merge

#29386 Add CoMut recipe
  recipes/comut/meta.yaml
Labels: please review & merge

#29389 Update xcode version, bump MethylDackel to test
  .circleci/config.yml
Labels: please review & merge

#29394 Update tbvcfreport to 0.1.8
  recipes/tbvcfreport/meta.yaml
Labels: please review & merge

#29400 Update: MultiQC version 1.11 release
  recipes/multiqc/meta.yaml
Labels: please review & merge

#29406 Update CMIP new version
  recipes/cmip/meta.yaml
Labels: please review & merge

#29413 Add COAST
  recipes/coast/meta.yaml
Labels: please review & merge

#29412 Rebuild perl-bio-db-hts with current pinned htslib
  build-fail-blacklist
  recipes/perl-bio-db-hts/meta.yaml
Labels: please review & merge

#29417 Update PyDamage recipe
  recipes/pydamage/meta.yaml
Labels: please review & merge

#29405 Add missing networkx dependency
  recipes/matchms/meta.yaml
Labels: please review & merge

#29418 Update recipe snakeSV to v0.3.1
  recipes/snakesv/build.sh
  recipes/snakesv/meta.yaml
Labels: please review & merge

#29422 Update ganon to 0.4.1
  recipes/ganon/meta.yaml
Labels: please review & merge

#29425 Update gmap to v2021.05.27
  recipes/gmap/meta.yaml
Labels: please review & merge

#29414 Enable homer on conda environement with @
  recipes/homer/build.sh
  recipes/homer/configureHomer.patch
  recipes/homer/meta.yaml
Labels: please review & merge

#29434 Updated HATCHet to v0.4.1
  recipes/hatchet/meta.yaml
Labels: please review & merge

#26174 Update python dependency to 3.6+
  build-fail-blacklist
Labels: please review & merge

#29440 Add jbrowse2 1.3.2
  recipes/jbrowse2/build.sh
  recipes/jbrowse2/meta.yaml
Labels: please review & merge

#29420 update mykrobe to v0.10.0
  build-fail-blacklist
  recipes/mykrobe/build.sh
  recipes/mykrobe/meta.yaml
Labels: new version, please review & merge

#29444 Update CMIP new version
  recipes/cmip/meta.yaml
Labels: please review & merge

#29452 Updated HATCHet to v0.4.2
  recipes/hatchet/meta.yaml
Labels: please review & merge

#29457 Update metacache to 2.0.0
  recipes/metacache/build.sh
  recipes/metacache/meta.yaml
Labels: please review & merge

#29459 Update recipe for new version of MTG-Link v2.1.0
  recipes/mtglink/meta.yaml
Labels: please review & merge

#29450 Add Recontig version 1.1.1
  recipes/recontig/build.sh
  recipes/recontig/meta.yaml
Labels: please review & merge

#29467 small reqs change and updated version
  recipes/motulizer/meta.yaml
Labels: please review & merge

#29463 Fix EukRep requirements
  recipes/eukrep/meta.yaml
Labels: please review & merge

#29469 Add MeSS recipe
  recipes/mess/meta.yaml
Labels: please review & merge

#29477 Add Fade version 0.3.6
  recipes/fade/build.sh
  recipes/fade/meta.yaml
Labels: please review & merge

#29478 Update COAST to v0.1.2
  recipes/coast/meta.yaml
Labels: please review & merge

#29424 SearchGUI 4.0.41 & PeptideShaker 2.0.29
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
  recipes/searchgui/build.sh
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#29487 damn python requ. is wrong too... sorry
  recipes/motulizer/meta.yaml
Labels: please review & merge

#29486 Update Mappy to v2.21
  recipes/mappy/meta.yaml
Labels: please review & merge

#29504 Update hicup to 0.8.1
  recipes/hicup/meta.yaml
Labels: please review & merge

#29507 Still not right python version....
  recipes/motulizer/meta.yaml
Labels: please review & merge

#29508 Update pangolearn to 2021-07-09
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#29511 Update Dependencies for scanpy-scripts
  recipes/scanpy-scripts/meta.yaml
Labels: please review & merge

#29514 Update mess to 0.2.2
  recipes/mess/meta.yaml
Labels: please review & merge

#27848 Add xMSannotator
  recipes/r-recetox-xmsannotator/meta.yaml
Labels: please review & merge

#29525 Update islandpath to v1.0.6
  recipes/islandpath/meta.yaml
Labels: please review & merge

#29533 update LAST
  recipes/last/meta.yaml
Labels: please review & merge

#29519 Update: umi_tools
  recipes/umi_tools/meta.yaml
Labels: please review & merge

#29518 update msisensor-pro
  recipes/msisensor-pro/build.sh
  recipes/msisensor-pro/meta.yaml
Labels: please review & merge

#29540 Add recipe: PREFACE
  recipes/preface/build.sh
  recipes/preface/meta.yaml
  recipes/preface/shebang.patch
Labels: please review & merge

#29537 Update blast to 2.12.0
  recipes/blast/configurellvm.patch
  recipes/blast/get_species_taxids.patch
  recipes/blast/meta.yaml
Labels: please review & merge

#29544 Update perbase
  build-fail-blacklist
  recipes/perbase/meta.yaml
Labels: please review & merge

#29552 Update taranis version 2.0.1
  recipes/taranis/meta.yaml
Labels: please review & merge

#29562 Update gimmemotifs (fix pandas dependency)
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#29581 Update GECCO recipe for `v0.8.0`
  recipes/gecco/meta.yaml
Labels: please review & merge

#29608 Update Vulcan to 1.0.3
  recipes/vulcan/meta.yaml
Labels: please review & merge

#29607 Add atlas-gene-annotation-manipulation
  recipes/atlas-gene-annotation-manipulation/build.sh
  recipes/atlas-gene-annotation-manipulation/meta.yaml
Labels: please review & merge

#29610 Update trnascan-se to 2.0.9
  recipes/trnascan-se/meta.yaml
  recipes/trnascan-se/patches/libdir.patch
Labels: please review & merge

#29620 Scallop2
  recipes/scallop-umi/meta.yaml
  recipes/scallop2/build.sh
  recipes/scallop2/meta.yaml
Labels: please review & merge

#29618 Update PhyloCSFpp to 1.1.0
  recipes/phylocsfpp/meta.yaml
Labels: new version, please review & merge

#29588 Add PASTE recipe
  recipes/paste-bio/meta.yaml
Labels: please review & merge

#29328 First release for srnaMapper.
  recipes/srnamapper/build.sh
  recipes/srnamapper/meta.yaml
Labels: please review & merge

#29623 Patch Kleborate's method for discovering Kaptive
  recipes/kleborate/fix_get_kaptive_path.patch
  recipes/kleborate/meta.yaml
Labels: please review & merge

#29593 metaplatanus
  recipes/metaplatanus/build.sh
  recipes/metaplatanus/meta.yaml
Labels: please review & merge

#29629 Add ClusterONE
  recipes/clusterone/LICENSE
  recipes/clusterone/build.sh
  recipes/clusterone/meta.yaml
Labels: please review & merge

#29641 Add recipe for singlecellnet-cli
  recipes/singlecellnet-cli/build.sh
  recipes/singlecellnet-cli/meta.yaml
Labels: please review & merge

#29656 change scikit version
  recipes/gnuvid/meta.yaml
Labels: please review & merge

#29582 Update SearchGUI: Fixing metamorpheus execution problems
  recipes/searchgui/build.sh
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#29668 Add scanpy multiplet entry point
  recipes/scanpy-scripts/meta.yaml
Labels: please review & merge

#29658 Update mafft to 8.486
  recipes/mafft/meta.yaml
Labels: please review & merge

#29659 Update ANARCI to 2021.02.04
  recipes/anarci/meta.yaml
Labels: please review & merge

#29644 Mwga utils 0.1.4
  recipes/mwga-utils/meta.yaml
Labels: please review & merge

#29640 Add new recipe for mmquant.
  recipes/mmquant/build.sh
  recipes/mmquant/meta.yaml
Labels: please review & merge

#29670 Update hicup to 0.8.2
  recipes/hicup/get_captured_reads.patch
  recipes/hicup/meta.yaml
Labels: please review & merge

#29575 Update PGCGAP to v1.0.31
  recipes/pgcgap/meta.yaml
Labels: new version, please review & merge

#29688 update tasmanian
  recipes/tasmanian-mismatch/meta.yaml
Labels: please review & merge

#29678 Update VirSorter2 to v2.2.3 build1
  recipes/virsorter/meta.yaml
Labels: please review & merge

#29696 add recipe for dragonflye
  recipes/dragonflye/build.sh
  recipes/dragonflye/meta.yaml
Labels: please review & merge

#29726 [dadaist2] adding python-rich
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#29695 Update ssocaller
  recipes/sscocaller/meta.yaml
Labels: please review & merge

#29609 Update bealign recipe
  recipes/python-bioext/build.sh
  recipes/python-bioext/meta.yaml
Labels: enhancement, please review & merge

#29718 add recipe for SerotypeFinder
  recipes/serotypefinder/build.sh
  recipes/serotypefinder/database_path.patch
  recipes/serotypefinder/meta.yaml
  recipes/serotypefinder/post-link.sh
  recipes/serotypefinder/update-serotypefinder-db.sh
Labels: please review & merge

#29732 Add irida-staramr-results
  recipes/irida-staramr-results/LICENSE
  recipes/irida-staramr-results/meta.yaml
Labels: please review & merge

#29724 Add deepsignal-plant recipe
  recipes/deepsignal-plant/meta.yaml
Labels: please review & merge

#29756 Update mafft to 7.487
  recipes/mafft/meta.yaml
Labels: please review & merge

#29769 Update meta.yaml
  recipes/scanpy-scripts/meta.yaml
Labels: please review & merge

#29773 [dadaist2] Update build.sh
  recipes/dadaist2/build.sh
  recipes/dadaist2/meta.yaml
Labels: please review & merge

#29771 Update antiSMASH to 6.0.1
  recipes/antismash/meta.yaml
Labels: please review & merge

#29780 Update dsh-bio to 2.0.5
  recipes/dsh-bio/build.sh
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#29774 Add celltypist package
  recipes/celltypist/meta.yaml
Labels: please review & merge

#29776 bump r-saige version to 0.44.6
  recipes/r-saige/meta.yaml
Labels: please review & merge

#29782 Update gNALI Recipe
  recipes/gnali/meta.yaml
  recipes/gnali/patch
Labels: please review & merge

#29794 Update r-deseqanalysis to 0.4.3
  recipes/r-deseqanalysis/meta.yaml
Labels: please review & merge

#29783 Update celltypist package build
  recipes/celltypist/meta.yaml
Labels: please review & merge

#29792 Peakhood
  recipes/peakhood/meta.yaml
Labels: please review & merge

#29796 Update mauve dependencies for GUI support
  recipes/mauve/build.sh
  recipes/mauve/meta.yaml
Labels: please review & merge

#29785 Add duet by yekaizhou
  recipes/duet/meta.yaml
Labels: please review & merge

#29797 Add r-acidgsea recipe
  recipes/r-acidgsea/build.sh
  recipes/r-acidgsea/meta.yaml
Labels: please review & merge

#29809 Updated HATCHet to v0.4.3
  recipes/hatchet/meta.yaml
Labels: please review & merge

#29793 Update hmftools-linx to version 1.16
  recipes/hmftools-linx/build.sh
  recipes/hmftools-linx/meta.yaml
Labels: please review & merge

#29423 Update prophane to v6.2.1
  recipes/prophane/meta.yaml
Labels: please review & merge

#29725 Update cgat-apps v0.6.3
  build-fail-blacklist
  recipes/cgat-apps/build.sh
  recipes/cgat-apps/meta.yaml
Labels: please review & merge

#29824 add recipe for bio easel
  recipes/perl-bio-easel/build.sh
  recipes/perl-bio-easel/fix_easel_path_msa.patch
  recipes/perl-bio-easel/fix_easel_path_random.patch
  recipes/perl-bio-easel/fix_easel_path_sqfile.patch
  recipes/perl-bio-easel/meta.yaml
Labels: please review & merge

#29828 Update to 1.0.7
  recipes/srnamapper/meta.yaml
Labels: please review & merge

#29786 bump r-saige version to 0.44.6.1
  recipes/r-saige/meta.yaml
Labels: please review & merge

#29820 add recipe for sequip
  recipes/sequip/build.sh
  recipes/sequip/meta.yaml
Labels: please review & merge

#29838 Add ngs_te_mapper2
  recipes/ngs_te_mapper2/meta.yaml
Labels: please review & merge

#29839 Update ngs_te_mapper2
  recipes/ngs_te_mapper2/meta.yaml
Labels: please review & merge

#29764 Add ssDripPipelines recipes
  recipes/ssdrippipeline/meta.yaml
Labels: please review & merge

#29840 Add: mstmap
  recipes/mstmap/build.sh
  recipes/mstmap/meta.yaml
Labels: please review & merge

#29846 Updated HATCHet to v0.4.4
  recipes/hatchet/meta.yaml
Labels: please review & merge
