Repository bioconda/bioconda-recipes, pull requests merged in 2021-04, with the labels that each got.

#27710 Bump pangoLEARN
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#27674 Update r-pipette to 0.5.14
  recipes/r-pipette/meta.yaml
Labels: please review & merge

#27676 Add r-acidmarkdown 0.1.1
  recipes/r-acidmarkdown/build.sh
  recipes/r-acidmarkdown/meta.yaml
Labels: please review & merge

#27704 In Progress: Add gangstr
  recipes/gangstr/0001-Unvendor-dependencies-use-pkg-config-instead.patch
  recipes/gangstr/build.sh
  recipes/gangstr/meta.yaml
Labels: please review & merge

#27729 add gcen recipes
  recipes/gcen/build.sh
  recipes/gcen/meta.yaml
Labels: please review & merge

#27709 bump r-saige to 0.44.0
  recipes/r-saige/meta.yaml
Labels: please review & merge

#27746 Update rmats2sashimiplot to version 2.0.4
  recipes/rmats2sashimiplot/build.sh
  recipes/rmats2sashimiplot/meta.yaml
Labels: please review & merge

#27741 Update VirSorter to v2.2.1
  recipes/virsorter/meta.yaml
Labels: please review & merge

#27735 update FROGS recipe to 3.2.2 release
  recipes/frogs/meta.yaml
Labels: please review & merge

#27743 Update r-acidgenomes to 0.2.11
  recipes/r-acidgenomes/meta.yaml
Labels: please review & merge

#27719 Update zga to 0.0.9.post2 with dependency update
  recipes/zga/meta.yaml
Labels: please review & merge

#27653 Update PICRUSt2 (version v2.4.1)
  recipes/picrust2/meta.yaml
  recipes/picrust2/post-link.sh
Labels: new version, please review & merge

#27752 Update rust-bio-tools to add explicit blis dependency
  recipes/rust-bio-tools/meta.yaml
Labels: please review & merge

#27713 Add doubletd recipe
  recipes/doubletd/meta.yaml
Labels: please review & merge

#27758 Add tritimap recipes
  recipes/tritimap/meta.yaml
Labels: please review & merge

#27748 Update correlationplus to 0.1.9
  recipes/correlationplus/meta.yaml
Labels: please review & merge

#27753 Update searchgui and peptideshaker
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#27761 Update rmats2sashimiplot to remove noarch
  recipes/rmats2sashimiplot/meta.yaml
Labels: please review & merge

#27774 Bump pangoLEARN
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#27769 update binsanity 0.5.3
  recipes/binsanity/meta.yaml
Labels: please review & merge

#27765 Add r-acidexperiment 0.1.10
  recipes/r-acidexperiment/build.sh
  recipes/r-acidexperiment/meta.yaml
Labels: please review & merge

#27767 Renano
  recipes/renano/build.sh
  recipes/renano/meta.yaml
Labels: please review & merge

#27817 Update infernal to 1.1.4
  recipes/infernal/meta.yaml
Labels: new version

#27787 Add r-acidsinglecell 0.1.7
  recipes/r-acidsinglecell/build.sh
  recipes/r-acidsinglecell/meta.yaml
Labels: please review & merge

#27834 Update MEGAN to 6.21.2
  build-fail-blacklist
  recipes/megan/build.sh
  recipes/megan/meta.yaml
Labels: please review & merge

#27820 fix gmap
  recipes/gmap/meta.yaml
Labels: please review & merge

#27843 Update deepvariant to enable GPU support
  recipes/deepvariant/meta.yaml
Labels: please review & merge

#27856 Update CONSTAX to v2.0.9 with OSX usage fixes.
  recipes/constax/build.sh
  recipes/constax/meta.yaml
Labels: please review & merge

#27849 Update r-basejump to 0.14.17
  build-fail-blacklist
  recipes/r-basejump/meta.yaml
Labels: please review & merge

#27862 Update tritimap to v0.9.1
  recipes/tritimap/meta.yaml
Labels: please review & merge

#27860 Update DOI for BRAKER2
  recipes/braker2/meta.yaml
Labels: please review & merge

#27667 Add protgraph / 0.0.2b3
  recipes/protgraph/meta.yaml
Labels: please review & merge

#27872 Bump up abnumber
  recipes/abnumber/meta.yaml
Labels: please review & merge

#27832 add squeegee recipes
  recipes/squeegee/meta.yaml
Labels: please review & merge

#27836 Add viewbs
  recipes/viewbs/build.sh
  recipes/viewbs/meta.yaml
Labels: please review & merge

#27877 Update ldsc recipe: Relax version requirement for dependency nose.
  recipes/ldsc/meta.yaml
Labels: please review & merge

#27874 disco: compile with zlib support
  build-fail-blacklist
  recipes/disco/1.2/build.sh
  recipes/disco/1.2/meta.yaml
  recipes/disco/1.2/sstr.patch
Labels: please review & merge

#27873 Fix rust-bio-tools BLAS linking
  recipes/rust-bio-tools/build.sh
  recipes/rust-bio-tools/meta.yaml
Labels: please review & merge

#27883 Update build.sh to add *.py scripts to bin
  recipes/braker2/build.sh
  recipes/braker2/meta.yaml
Labels: please review & merge

#26906 Update deeplc to 0.1.29
  recipes/deeplc/meta.yaml
Labels: please review & merge

#27889 Add recipe for shiptv
  recipes/shiptv/meta.yaml
Labels: please review & merge

#27892 Update tritimap requirements and update version
  recipes/tritimap/meta.yaml
Labels: please review & merge

#27734 Add recipe
  recipes/orsum/build.sh
  recipes/orsum/meta.yaml
Labels: please review & merge

#27851 Update_encylopedia_1.2.2
  recipes/encyclopedia/build.sh
  recipes/encyclopedia/encyclopedia.py
  recipes/encyclopedia/meta.yaml
Labels: please review & merge

#27904 Update predex package
  recipes/predex/meta.yaml
Labels: please review & merge

#27908 Pin numpy to avoid illegal instruction issue
  recipes/scanpy-scripts/meta.yaml
Labels: please review & merge

#27917 Update gefast to version 2.01
  recipes/gefast/build.sh
  recipes/gefast/meta.yaml
  recipes/gefast/patch
Labels: please review & merge

#27840 fix rnaquast
  recipes/rnaquast/meta.yaml
Labels: please review & merge

#27922 Update r-stitch to 1.6.6
  recipes/r-stitch/meta.yaml
Labels: please review & merge

#27900 Update graphtyper to 2.7.1
  build-fail-blacklist
  recipes/graphtyper/build.sh
  recipes/graphtyper/meta.yaml
Labels: please review & merge

#27926 savvy - remove dependency on htslib
  recipes/savvy/meta.yaml
Labels: please review & merge

#27923 Update CellRank recipe.yaml
  recipes/cellrank/meta.yaml
Labels: please review & merge

#27927 Add nanoq
  recipes/nanoq/build.sh
  recipes/nanoq/meta.yaml
Labels: please review & merge

#27925 Update new version
  recipes/submission-tool-validator/meta.yaml
  recipes/submission-tool-validator/submission-tool-validator.py
Labels: please review & merge

#27898 Update libsbml to contain extensions
  recipes/libsbml/build.sh
  recipes/libsbml/meta.yaml
Labels: please review & merge

#27899 Update immuneML version number and dependencies
  recipes/immuneml/meta.yaml
Labels: please review & merge

#27911 Update GROMACS_MPI: move perl and python dependencies
  recipes/gromacs_mpi/2021/meta.yaml
Labels: please review & merge

#27903 Adds Archer
  recipes/archer/build.sh
  recipes/archer/meta.yaml
Labels: please review & merge

#27915 Add SamHaplotag
  recipes/samhaplotag/build.sh
  recipes/samhaplotag/meta.yaml
Labels: please review & merge

#27847 Add NorESM recipe (Climate)
  recipes/noresm/LICENSE.txt
  recipes/noresm/build.sh
  recipes/noresm/case.py.patch
  recipes/noresm/ch4Mod.F90.patch
  recipes/noresm/config_compilers.xml.patch
  recipes/noresm/config_compilers_xml.patch
  recipes/noresm/config_machines_xml.patch
  recipes/noresm/meta.yaml
  recipes/noresm/micro_mg2_0.F90.patch
  recipes/noresm/run_test.sh
  recipes/noresm/seq_infodata_mod.F90.patch
Labels: please review & merge

#27935 Update r-saige to 0.44.1
  build-fail-blacklist
  recipes/r-saige/conda_build_config.yaml
  recipes/r-saige/meta.yaml
  recipes/r-saige/patches/0001-use-shared-libs-in-makevars.patch
Labels: please review & merge

#27955 rebuild savvy 1.3.0
  recipes/savvy/1.3.0/build.sh
  recipes/savvy/1.3.0/meta.yaml
  recipes/savvy/1.3.0/patches/0001-patch-cmakelists-for-conda-build.patch
Labels: please review & merge

#27948 Add rustyread
  recipes/rustyread/build.sh
  recipes/rustyread/meta.yaml
Labels: please review & merge

#27953 Update Pretext{Map,Snapshot,Graph}
  build-fail-blacklist
  recipes/pretextgraph/bioconda_libdeflate_include_path.patch
  recipes/pretextgraph/build.sh
  recipes/pretextgraph/meta.yaml
  recipes/pretextmap/bioconda_libdeflate_include_path.patch
  recipes/pretextmap/build.sh
  recipes/pretextmap/meta.yaml
  recipes/pretextsnapshot/0001-disable-auto-vectorisation-for-conda-libm.patch
  recipes/pretextsnapshot/bioconda_libdeflate_include_path.patch
  recipes/pretextsnapshot/build.sh
  recipes/pretextsnapshot/meta.yaml
Labels: please review & merge

#27949 rebuild r-saige 0.35.8.8
  recipes/r-saige/0.35.8.8/build.sh
  recipes/r-saige/0.35.8.8/conda_build_config.yaml
  recipes/r-saige/0.35.8.8/meta.yaml
  recipes/r-saige/0.35.8.8/patches/0001-use-shared-libs-in-makevars.patch
  recipes/r-saige/0.35.8.8/patches/0002-fix-rcpp-returns.patch
  recipes/r-saige/0.35.8.8/patches/0003-fix-gettimeofday-import.patch
  recipes/r-saige/0.35.8.8/patches/0004-fix-paths-of-imported-libs-should-never-use-path.patch
  recipes/r-saige/0.35.8.8/patches/0005-add-minCovariateCount-in-step-1.patch
  recipes/r-saige/0.35.8.8/patches/0358-use-shared-libs-in-makevars-0.35.8.patch
Labels: please review & merge

#27954 Add fba
  recipes/fba/meta.yaml
Labels: please review & merge

#27959 Updata: check meme build on Python 3.9
  build-fail-blacklist
  recipes/meme/meta.yaml
Labels: please review & merge

#27963 update SamHaplotag
  recipes/samhaplotag/build.sh
  recipes/samhaplotag/meta.yaml
Labels: please review & merge

#27827 Update recipe for new version of MTG-Link v1.1.0
  recipes/mtglink/build.sh
  recipes/mtglink/meta.yaml
Labels: please review & merge

#27980 Rebuild jbrowse 1.16.11
  recipes/jbrowse/meta.yaml
Labels: please review & merge

#27990 Update plasmidid version 1.6.5
  recipes/plasmidid/meta.yaml
Labels: please review & merge

#28005 update meryl
  recipes/meryl/0001-Do-not-bail-out-for-Clang-on-macOS.patch
  recipes/meryl/0001-meryl-utility-gh-2-Add-license-information-for-parasail.patch
  recipes/meryl/0002-macos-cmath.patch
  recipes/meryl/meta.yaml
Labels: please review & merge

#28006 Braker2 fix
  recipes/braker2/meta.yaml
  recipes/braker2/post-link.sh
Labels: please review & merge

#28012 update Tatajuba
  recipes/tatajuba/meta.yaml
Labels: please review & merge

#28010 delete bioservices recipe because of conda forge integration
  recipes/bioservices/build.sh
  recipes/bioservices/meta.yaml
Labels: please review & merge

#28011 update merqury
  recipes/merqury/meta.yaml
  recipes/merqury/run_test.sh
Labels: please review & merge

#28033 bump metaphlan
  recipes/metaphlan/meta.yaml
Labels: please review & merge

#28002 Update star-fusion to 1.10.0-1
  recipes/star-fusion/meta.yaml
Labels: automerge, please review & merge

#28023 update rgi5.2.0 recipe
  recipes/rgi/meta.yaml
Labels: please review & merge

#27781 Update PGCGAP to v1.0.27
  recipes/pgcgap/build.sh
  recipes/pgcgap/meta.yaml
Labels: new version

#28030 Update pandas dependency for LDSC
  recipes/ldsc/meta.yaml
  recipes/ldsc/setup.py
Labels: automerge

#28058 Update gifrop to 0.0.9
  recipes/gifrop/meta.yaml
Labels: please review & merge

#28055 update hifiasm_meta to v0.2.
  recipes/hifiasm_meta/meta.yaml
Labels: please review & merge

#28004 Update ProtGraph to 0.1.0
  recipes/protgraph/meta.yaml
Labels: please review & merge

#28062 simug: Remove backup files from package
  recipes/simug/build.sh
  recipes/simug/meta.yaml
Labels: automerge

#27997 Bump RNAsamba to 0.2.5
  build-fail-blacklist
  recipes/rnasamba/0001-Enable-stable-Rust.patch
  recipes/rnasamba/meta.yaml
Labels: new version, please review & merge

#28074 Add ribocutter
  recipes/ribocutter/meta.yaml
Labels: please review & merge

#28065 Update PGCGAP to v1.0.28
  build-fail-blacklist
  recipes/pgcgap/meta.yaml
Labels: new version, please review & merge

#28043 Add recipe for nextclade Javascript command line tool
  recipes/nextclade_js/build.sh
  recipes/nextclade_js/meta.yaml
Labels: please review & merge

#27968 Add MiMSI to recipes
  recipes/mimsi/meta.yaml
Labels: please review & merge

#27988 Updates deepvariant recipe
  recipes/deepvariant/dv_make_examples.py
  recipes/deepvariant/meta.yaml
Labels: please review & merge

#28067 bump version 0.6.1
  build-fail-blacklist
  recipes/agat/meta.yaml
Labels: please review & merge

#28063 Riboloco
  recipes/riboloco/meta.yaml
Labels: please review & merge

#27876 Update wg-blimp to v0.9.8
  recipes/wg-blimp/meta.yaml
Labels: please review & merge

#28086 Update gmap to v2021.03.08
  recipes/gmap/meta.yaml
Labels: please review & merge

#28041 Updated gromacs to 2021.1
  recipes/gromacs_mpi/2021/activate.sh
  recipes/gromacs_mpi/2021/build.sh
  recipes/gromacs_mpi/2021/gmx-chooser.bash
  recipes/gromacs_mpi/2021/meta.yaml
Labels: please review & merge

#28093 Updated HATCHet to 0.2.10
  build-fail-blacklist
  recipes/hatchet/build.sh
  recipes/hatchet/meta.yaml
Labels: please review & merge

#28115 Add r-metap recipe
  recipes/r-metap/build.sh
  recipes/r-metap/meta.yaml
Labels: please review & merge

#28019 Update recipe for new version of Lrez v2.0
  recipes/lrez/build.sh
  recipes/lrez/meta.yaml
Labels: please review & merge

#28127 Update libmaus2
  recipes/libmaus2/meta.yaml
  recipes/libmaus2/patch
  recipes/libmaus2/patch2
Labels: please review & merge

#28122 Update: watden titration
  recipes/cmip/build.sh
  recipes/cmip/meta.yaml
  recipes/cmip/post-link.sh
Labels: please review & merge

#28131 Update IsoQuant to 1.2.1
  recipes/isoquant/meta.yaml
Labels: please review & merge

#28135 Update: biobambam v2.0.182
  recipes/biobambam/meta.yaml
Labels: please review & merge

#28136 New recipe for leviathan
  recipes/leviathan/build.sh
  recipes/leviathan/meta.yaml
Labels: please review & merge

#28144 Update SpacePHARER to 5.c2e680a
  recipes/spacepharer/meta.yaml
Labels: please review & merge

#28141 Updated HATCHet to 0.2.11
  recipes/hatchet/meta.yaml
Labels: please review & merge

#28148 Update VirSorter to v2.2.2
  recipes/virsorter/meta.yaml
Labels: please review & merge

#28138 Update tabix to 1.11 (metapackage)
  recipes/tabix/meta.yaml
Labels: please review & merge

#28152 Remove absurdly out-dated tabix. It's been in htslib for years.
  recipes/tabix/0.2.5/build.sh
  recipes/tabix/0.2.5/meta.yaml
  recipes/tabix/0.2.6/Makefile.patch
  recipes/tabix/0.2.6/build.sh
  recipes/tabix/0.2.6/meta.yaml
Labels: please review & merge

#28106 Add Haploflow
  recipes/haploflow/bioconda-adjustments.patch
  recipes/haploflow/build.sh
  recipes/haploflow/meta.yaml
Labels: automerge

#28153 Remove retro-tabix as a dependency
  recipes/coolbox/meta.yaml
  recipes/crispritz/meta.yaml
  recipes/drop/meta.yaml
  recipes/galaxy-ml/meta.yaml
  recipes/genomestrip/meta.yaml
Labels: please review & merge

#28161 more retro-tabix removal
  recipes/ctat-mutations/meta.yaml
  recipes/grafimo/meta.yaml
  recipes/mutmap/meta.yaml
  recipes/panpasco/meta.yaml
Labels: please review & merge

#28172 Update grafimo to 1.1.4
  recipes/grafimo/meta.yaml
Labels: please review & merge

#28159 update isoquant 1.2.1
  recipes/isoquant/meta.yaml
Labels: please review & merge

#28088 Update scanpy-scripts deps to anticipate py3.6 deprecation in scanpy 1.8
  recipes/scanpy-scripts/meta.yaml
Labels: please review & merge

#28108 Update Gromacs py
  recipes/gromacs_py/meta.yaml
Labels: please review & merge

#28179 Update sensv v1.0.4
  recipes/sensv/meta.yaml
Labels: please review & merge

#28186 Update mpa-server by fixing dependencies
  recipes/mpa-server/meta.yaml
Labels: please review & merge

#28181 Add psap
  recipes/psap/LICENSE
  recipes/psap/meta.yaml
Labels: please review & merge

#28192 Update abyss 2.3.1
  build-fail-blacklist
  recipes/abyss/meta.yaml
Labels: please review & merge

#28188 add snakedeploy
  recipes/snakedeploy/0001-gh-13-Exclude-tests-package-from-dist.patch
  recipes/snakedeploy/meta.yaml
Labels: automerge, please review & merge

#28207 Add new recipe for figaro
  recipes/figaro/LICENSE
  recipes/figaro/build.sh
  recipes/figaro/meta.yaml
Labels: please review & merge

#28212 Update BioProv to v0.1.23
  recipes/bioprov/meta.yaml
Labels: please review & merge

#28214 add recipe for staphopia-sccmec
  recipes/staphopia-sccmec/build.sh
  recipes/staphopia-sccmec/meta.yaml
Labels: please review & merge

#28204 Add agrvate to Bioconda recipes
  recipes/agrvate/build.sh
  recipes/agrvate/meta.yaml
Labels: please review & merge

#28218 Update r-deconstructsigs to 1.9.0
  recipes/r-deconstructsigs/meta.yaml
Labels: please review & merge

#28137 build sra_tools
  build-fail-blacklist
  recipes/sra-tools/0001-No-libhdf5-libxml2-static-link-sra-tools.patch
  recipes/sra-tools/0002-No-libhdf5-libxml2-static-link-ncbi-vdb.patch
  recipes/sra-tools/build.sh
  recipes/sra-tools/meta.yaml
Labels: automerge

#28226 Bump up abnumber to 0.2.6
  recipes/abnumber/meta.yaml
Labels: please review & merge

#28236 Add saspector
  recipes/saspector/meta.yaml
Labels: please review & merge

#28227 Update cmip 2.6.7
  recipes/cmip/build.sh
  recipes/cmip/meta.yaml
  recipes/cmip/post-link.sh
Labels: please review & merge

#28268 update usher
  build-fail-blacklist
  recipes/usher/meta.yaml
Labels: please review & merge

#28155 bump searchgui and peptideshaker
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#28299 Bump pangolearn
  recipes/pangolearn/meta.yaml
Labels: please review & merge

#28297 Fix bioconductor-cytolib by reapplying existing patch
  recipes/bioconductor-cytolib/meta.yaml
Labels: please review & merge

#28310 Update braker2: add GUSHR
  recipes/braker2/braker.pl.patch
  recipes/braker2/build.sh
  recipes/braker2/gushr.py.patch
  recipes/braker2/meta.yaml
  recipes/braker2/path.patch
Labels: please review & merge

#28280 Add MetaCache v1.1.1
  recipes/metacache/build.sh
  recipes/metacache/meta.yaml
Labels: please review & merge
