Repository bioconda/bioconda-recipes, pull requests merged in 2022-06, with the labels that each got.

#35149 Upgrade & reactivate NGLess
  build-fail-blacklist
  recipes/ngless/build.sh
  recipes/ngless/meta.yaml
Labels: please review & merge

#35106 bigscape: update to python 3.7
  recipes/bigscape/meta.yaml
Labels: please review & merge

#35166 Add strobealign recipe
  recipes/strobealign/build.sh
  recipes/strobealign/meta.yaml
Labels: please review & merge

#35161 update shigatyper recipe for better container support
  recipes/shigatyper/add-index.patch
  recipes/shigatyper/add-outdir.patch
  recipes/shigatyper/build.sh
  recipes/shigatyper/meta.yaml
Labels: please review & merge

#35095 Install version snpeff 3.6
  recipes/snpeff/3.6/build.sh
  recipes/snpeff/3.6/meta.yaml
  recipes/snpeff/3.6/snpeff.sh
Labels: please review & merge

#35196 Update deblur to 1.1.1
  recipes/deblur/meta.yaml
Labels: please review & merge

#35188 Update staramr to remove restriction on pandas version
  recipes/staramr/meta.yaml
Labels: please review & merge

#35186 Rebuild mitoz 3.3
  recipes/mitoz/meta.yaml
Labels: please review & merge

#35212 Update Ngless to v1.4.1
  recipes/ngless/build.sh
  recipes/ngless/meta.yaml
Labels: please review & merge

#35203 Add MarkerMAG package
  recipes/markermag/meta.yaml
Labels: please review & merge

#35215 Update ViennaRNA Package to upstream version 2.5.1
  recipes/viennarna/meta.yaml
Labels: please review & merge

#35183 Update sam2lca python version to 3.7
  recipes/sam2lca/meta.yaml
Labels: please review & merge

#35255 Update arcs to 1.2.4
  recipes/arcs/build.sh
  recipes/arcs/meta.yaml
Labels: please review & merge

#35206 Add scoper recipe
  recipes/r-scoper/build.sh
  recipes/r-scoper/meta.yaml
Labels: please review & merge

#35263 Update TaxonKit to v0.12.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#35231 Update pcaone
  recipes/pcaone/build.sh
  recipes/pcaone/meta.yaml
Labels: please review & merge

#35279 Update cladebreaker to v0.2.2
  recipes/cladebreaker/meta.yaml
Labels: please review & merge

#35080 update tbpore dependencies
  recipes/tbpore/meta.yaml
Labels: please review & merge

#35272 Update Tiddit to pull code from Scilife organisation
  recipes/tiddit/meta.yaml
Labels: please review & merge

#35266 Update AGAT recipe
  recipes/agat/meta.yaml
Labels: please review & merge

#35274 Add openssl runtime dependency for bioconductor-rtracklayer
  recipes/bioconductor-rtracklayer/meta.yaml
Labels: please review & merge

#35283 update nanocaller
  recipes/nanocaller/build.sh
  recipes/nanocaller/meta.yaml
Labels: please review & merge

#35207 Add recipe for `pytrimal` PyPI package
  recipes/pytrimal/meta.yaml
Labels: please review & merge

#35249 Update mercat2
  recipes/mercat2/meta.yaml
Labels: please review & merge

#35321 Re-enable build of r-intlim.
  build-fail-blacklist
  recipes/r-intlim/meta.yaml
Labels: please review & merge

#35286 Add binary RepeatFinder from MANTIS (mantis-msi)
  recipes/mantis-msi/Makefile.patch
  recipes/mantis-msi/build.sh
  recipes/mantis-msi/meta.yaml
Labels: please review & merge

#35314 Update PlasmidFinder for better container support
  recipes/plasmidfinder/build.sh
  recipes/plasmidfinder/download-db.sh
  recipes/plasmidfinder/meta.yaml
  recipes/plasmidfinder/python_path.patch
Labels: please review & merge

#35228 Install_miga_v1.0.0
  recipes/miga/meta.yaml
Labels: please review & merge

#35340 Update pcaone
  recipes/pcaone/build.sh
  recipes/pcaone/meta.yaml
Labels: please review & merge

#35142 Update krakenuniq to 0.7.1
  recipes/krakenuniq/krakenuniq2.patch
  recipes/krakenuniq/meta.yaml
Labels: please review & merge

#35235 Update entrez-direct recipe to use extended-base
  recipes/entrez-direct/meta.yaml
Labels: please review & merge

#35379 patch pymummer recipe
  recipes/pymummer/meta.yaml
  recipes/pymummer/temp_dir_path.patch
Labels: please review & merge

#35357 Add recipe for HmnFusion
  recipes/hmnfusion/meta.yaml
  recipes/hmnfusion/run_test.sh
Labels: please review & merge

#35385 Update quast for python 3.8+
  recipes/quast/meta.yaml
Labels: please review & merge

#35393 Add recipe for TMB-curie
  recipes/tmb/build.sh
  recipes/tmb/meta.yaml
Labels: please review & merge

#35388 Update genotyphi recipe for mykrobe based analysis
  recipes/genotyphi/build.sh
  recipes/genotyphi/meta.yaml
Labels: please review & merge

#35230 Add recipe for MLST by CGE
  recipes/mlst-cge/LICENSE-2.0.txt
  recipes/mlst-cge/build.sh
  recipes/mlst-cge/download-db.sh
  recipes/mlst-cge/meta.yaml
  recipes/mlst-cge/python_path.patch
Labels: please review & merge

#35091 Update adam to 1.0
  recipes/adam/meta.yaml
Labels: please review & merge

#35092 Update cannoli to 1.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#35399 add gothresher to bioconda
  recipes/gothresher/meta.yaml
Labels: please review & merge

#35407 Update Clippy to v1.5.0
  recipes/clippy/meta.yaml
Labels: please review & merge

#35409 Update QUILT to 1.0.3
  recipes/r-quilt/meta.yaml
Labels: please review & merge

#35418 Update genomepy to 0.13.1
  recipes/genomepy/meta.yaml
Labels: new version

#35402 Add r-geneexpressionfromgeo.
  recipes/r-geneexpressionfromgeo/build.sh
  recipes/r-geneexpressionfromgeo/meta.yaml
Labels: please review & merge

#32429 Add b2btools
  recipes/b2btools/meta.yaml
  recipes/b2btools/run_test.sh
Labels: please review & merge

#35439 Update n50 to 1.4.10
  recipes/n50/meta.yaml
Labels: autobump, new version

#35437 Update usher to 0.5.5
  recipes/usher/meta.yaml
Labels: autobump, new version

#35435 Update medaka to 1.6.1
  recipes/medaka/meta.yaml
Labels: autobump, new version

#35427 Update recognizer to 1.8.0
  recipes/recognizer/meta.yaml
Labels: autobump, new version

#35436 Update igv to 2.13.1
  recipes/igv/meta.yaml
Labels: autobump, new version

#35434 Update jbrowse2 to 1.7.11
  recipes/jbrowse2/meta.yaml
Labels: autobump, new version

#35431 Update cstag to 0.2.3
  recipes/cstag/meta.yaml
Labels: autobump, new version

#35432 Update quatradis to 0.8.3
  recipes/quatradis/meta.yaml
Labels: autobump, new version

#35428 Update hat-phasing to 0.1.7
  recipes/hat-phasing/meta.yaml
Labels: autobump, new version

#35421 Add alignoth recipe
  recipes/alignoth/build.sh
  recipes/alignoth/meta.yaml
Labels: please review & merge

#35425 updating freyja to v1.3.8
  recipes/freyja/meta.yaml
Labels: please review & merge

#35430 Update augur to 16.0.1
  recipes/augur/meta.yaml
Labels: autobump, new version

#35412 Add recipe for SCExecute and SCReadCounts
  recipes/scexecute/build.sh
  recipes/scexecute/meta.yaml
  recipes/screadcounts/build.sh
  recipes/screadcounts/meta.yaml
Labels: please review & merge

#35501 Update eigenstratdatabasetools recipe
  recipes/eigenstratdatabasetools/build.sh
  recipes/eigenstratdatabasetools/meta.yaml
Labels: please review & merge

#35505 Add r-easydifferentialgenecoexpression.
  recipes/r-easydifferentialgenecoexpression/build.sh
  recipes/r-easydifferentialgenecoexpression/meta.yaml
Labels: please review & merge

#35483 Update seqan3: remove range-v3 reference
  recipes/seqan3/build.sh
Labels: please review & merge

#35521 Add pyfastg
  recipes/pyfastg/meta.yaml
Labels: please review & merge

#35520 Update epytope to 3.1.0
  recipes/epytope/meta.yaml
Labels: please review & merge

#35438 Update seqan3 to 3.2.0
  recipes/seqan3/build.sh
  recipes/seqan3/meta.yaml
Labels: autobump, new version

#35517 Fix gsl version needed for fastANI
  recipes/fastani/meta.yaml
Labels: please review & merge

#35523 MultiQC v1.13a0
  recipes/multiqc/meta.yaml
Labels: please review & merge

#35547 Bump nextalign to 2.0.0
  recipes/nextalign/meta.yaml
  recipes/nextalign/run_test.sh
Labels: please review & merge

#35546 Bump nextclade to 2.0.0
  recipes/nextclade/meta.yaml
  recipes/nextclade/run_test.sh
Labels: please review & merge

#35528 Update deepsignal-plant to 0.1.6
  recipes/deepsignal-plant/meta.yaml
Labels: please review & merge

#35542 Update goalign and gotree recipes: update go + build number
  recipes/goalign/conda_build_config.yaml
  recipes/goalign/meta.yaml
  recipes/gotree/conda_build_config.yaml
  recipes/gotree/meta.yaml
Labels: please review & merge

#35550 Update delly
  recipes/delly/build.sh
  recipes/delly/meta.yaml
Labels: please review & merge

#35568 Update
  recipes/primedrpa/meta.yaml
Labels: please review & merge

#35570 update delly
  recipes/delly/build.sh
  recipes/delly/meta.yaml
Labels: please review & merge

#35586 Update delly
  recipes/delly/build.sh
  recipes/delly/meta.yaml
Labels: please review & merge
