Repository bioconda/bioconda-recipes, pull requests merged in 2022-08, with the labels that each got.

#36160 Update spring
  recipes/spring/meta.yaml
Labels: please review & merge

#36173 Update Foldseek to 3-915ef7d
  recipes/foldseek/meta.yaml
Labels: please review & merge

#36166 Add r-mixedcca
  recipes/r-mixedcca/build.sh
  recipes/r-mixedcca/meta.yaml
Labels: please review & merge

#36051 update plink2 to alpha 3.3, v2.00a3.3
  recipes/plink2/meta.yaml
Labels: please review & merge

#36174 Update genomepy to 1.14.0
  recipes/genomepy/meta.yaml
Labels: new version

#36181 Updated HATCHet to v1.0.2
  recipes/hatchet/meta.yaml
Labels: please review & merge

#36149 add quantpi
  recipes/quantpi/LICENSE
  recipes/quantpi/meta.yaml
Labels: please review & merge

#36184 Add r-spring
  recipes/r-spring/build.sh
  recipes/r-spring/meta.yaml
Labels: please review & merge

#36138 Add mcross
  recipes/mcross/build.sh
  recipes/mcross/meta.yaml
Labels: please review & merge

#36214 Add r-noisyr.
  recipes/r-noisyr/build.sh
  recipes/r-noisyr/meta.yaml
Labels: please review & merge

#36218 Update TN93 to version 1.0.9.
  build-fail-blacklist
  recipes/tn93/meta.yaml
Labels: please review & merge

#36223 Update hitac to v2.0.10
  recipes/hitac/meta.yaml
Labels: please review & merge

#36189 Add r-netcomi
  recipes/r-netcomi/build.sh
  recipes/r-netcomi/meta.yaml
Labels: please review & merge

#36239 Update HiTaC's license
  recipes/hitac/meta.yaml
Labels: please review & merge

#36235 Neofox move (second try)
  recipes/neofox/meta.yaml
Labels: please review & merge

#36222 add recipe for pbptyper
  recipes/pbptyper/build.sh
  recipes/pbptyper/meta.yaml
Labels: please review & merge

#36194 Update to 22.08
  recipes/smashpp/build.sh
  recipes/smashpp/meta.yaml
Labels: please review & merge

#36256 Add metacoag v1.1
  recipes/metacoag/meta.yaml
Labels: please review & merge

#36257 Add r-abdiv
  recipes/r-abdiv/build.sh
  recipes/r-abdiv/meta.yaml
Labels: please review & merge

#36238 Update Pydamage
  recipes/pydamage/meta.yaml
Labels: please review & merge

#36252 Update proteomiqon psmstatistics 0.0.8
  recipes/proteomiqon-psmstatistics/meta.yaml
Labels: please review & merge

#36266 Remove r-mixedcca after move to conda-forge.
  recipes/r-mixedcca/build.sh
  recipes/r-mixedcca/meta.yaml
Labels: please review & merge

#36276 Update breseq to 0.37.0
  recipes/breseq/meta.yaml
Labels: please review & merge

#36279 [cd-hit] allow clustering sequences >64kb
  recipes/cd-hit/build.sh
  recipes/cd-hit/meta.yaml
Labels: please review & merge

#36278 Update singlem: update graftm dependency.
  recipes/singlem/meta.yaml
Labels: please review & merge

#36264 Add recipe for `pyfamsa`
  recipes/pyfamsa/meta.yaml
Labels: please review & merge

#36287 Update Sentieon recipe to 202112.05
  recipes/sentieon/meta.yaml
Labels: please review & merge

#36288 Update singlem: Pin graftm=0.13.1.
  recipes/singlem/meta.yaml
Labels: please review & merge

#36293 Bump abnumber to 0.3.0
  recipes/abnumber/meta.yaml
Labels: please review & merge

#36298 Add recipe for svjedi-graph v1.0.0
  recipes/svjedi-graph/build.sh
  recipes/svjedi-graph/meta.yaml
Labels: please review & merge

#36304 Update RLPipes to version 0.9.3
  recipes/rlpipes/meta.yaml
Labels: please review & merge

#36316 Update flexbar to add macos version to build
  recipes/flexbar/3.5.0/march.patch
  recipes/flexbar/3.5.0/meta.yaml
Labels: please review & merge

#36327 add_saintbioutils
  recipes/saintbioutils/meta.yaml
Labels: please review & merge

#36358 Update cazy_webscraper V2
  recipes/cazy_webscraper/meta.yaml
Labels: please review & merge

#36357 Update `gecco` recipe to `v0.9.5`
  recipes/gecco/meta.yaml
Labels: please review & merge

#36353 Add @corneliusroemer as augur maintainer
  recipes/augur/meta.yaml
Labels: please review & merge

#36372 Update FAMSA to 2.1.2
  recipes/famsa/meta.yaml
Labels: please review & merge

#36382 Remove perl-memoize, it has been migrated to conda-forge.
  recipes/perl-memoize/build.sh
  recipes/perl-memoize/meta.yaml
Labels: please review & merge

#36309 Remove perl-scalar-list-utils after migration to conda-forge.
  recipes/perl-scalar-list-utils/build.sh
  recipes/perl-scalar-list-utils/meta.yaml
Labels: please review & merge

#36263 Remove perl-try-tiny after conda-forge migration.
  recipes/perl-try-tiny/build.sh
  recipes/perl-try-tiny/meta.yaml
Labels: please review & merge

#36297 Add recipe for hmftools-lilac
  recipes/hmftools-lilac/LILAC.sh
  recipes/hmftools-lilac/build.sh
  recipes/hmftools-lilac/meta.yaml
Labels: please review & merge

#36375 Update vafator to version 2.0.0
  recipes/vafator/meta.yaml
Labels: please review & merge

#36370 Update version to 1.1
  recipes/verkko/meta.yaml
  recipes/verkko/version.patch
Labels: please review & merge

#36385 Update Jalview to 2.11.2.4
  recipes/jalview/meta.yaml
Labels: please review & merge

#36378 Add taxadb python package
  recipes/taxadb/meta.yaml
Labels: please review & merge

#36396 Update `btyper3` to `v3.3.0`
  recipes/btyper3/meta.yaml
Labels: please review & merge

#36403 Remove perl-test-simple, it has been migrated to conda-forge.
  recipes/perl-test-simple/build.sh
  recipes/perl-test-simple/meta.yaml
Labels: please review & merge

#36409 Update SeqKit to v2.3.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#36402 Remove perl-pathtools, it has been migrated to conda-forge.
  recipes/perl-pathtools/build.sh
  recipes/perl-pathtools/meta.yaml
Labels: please review & merge

#36392 Remove perl-proc-fork, it has been migrated to conda-forge.
  recipes/perl-proc-fork/build.sh
  recipes/perl-proc-fork/meta.yaml
Labels: please review & merge

#36391 Remove perl-exporter-tidy, it has been migrated to conda-forge.
  recipes/perl-exporter-tidy/build.sh
  recipes/perl-exporter-tidy/meta.yaml
Labels: please review & merge

#36405 Remove perl-apache-test, it has been migrated to conda-forge.
  recipes/perl-apache-test/build.sh
  recipes/perl-apache-test/meta.yaml
Labels: please review & merge

#36394 Remove perl-storable, it has been migrated to conda-forge.
  recipes/perl-storable/build.sh
  recipes/perl-storable/meta.yaml
Labels: please review & merge

#36389 Update AmpliGone recipe for version 1.1.0
  recipes/ampligone/meta.yaml
Labels: please review & merge

#36416 Remove perl-exporter-tiny, it has been migrated to conda-forge.
  recipes/perl-exporter-tiny/build.sh
  recipes/perl-exporter-tiny/meta.yaml
Labels: please review & merge

#36422 Remove perl-type-tiny, it has been migrated to conda-forge.
  recipes/perl-type-tiny/build.sh
  recipes/perl-type-tiny/meta.yaml
Labels: please review & merge

#36421 Remove perl-test-needs, it has been migrated to conda-forge.
  recipes/perl-test-needs/build.sh
  recipes/perl-test-needs/meta.yaml
Labels: please review & merge

#36420 Remove perl-data-dumper, it has been migrated to conda-forge.
  recipes/perl-data-dumper/build.sh
  recipes/perl-data-dumper/meta.yaml
Labels: please review & merge

#36417 Remove perl-mime-base64, it has been migrated to conda-forge.
  recipes/perl-mime-base64/build.sh
  recipes/perl-mime-base64/meta.yaml
Labels: please review & merge

#36410 Remove perl-file-chdir, it has been migrated to conda-forge.
  recipes/perl-file-chdir/build.sh
  recipes/perl-file-chdir/meta.yaml
Labels: please review & merge

#36226 new dependencies for atlas 2.11
  recipes/metagenome-atlas/meta.yaml
Labels: please review & merge

#36426 Remove perl-compress-raw-zlib, it has been migrated to conda-forge
  recipes/perl-compress-raw-zlib/build.sh
  recipes/perl-compress-raw-zlib/meta.yaml
Labels: please review & merge

#36428 Remove perl-sub-uplevel, it has been migrated to conda-forge.
  recipes/perl-sub-uplevel/build.sh
  recipes/perl-sub-uplevel/meta.yaml
Labels: please review & merge

#36430 Remove perl-business-isbn-data, it has been migrated to conda-forge.
  recipes/perl-business-isbn-data/build.sh
  recipes/perl-business-isbn-data/meta.yaml
Labels: please review & merge

#36429 Remove perl-test-warn, it has been migrated to conda-forge.
  recipes/perl-test-warn/build.sh
  recipes/perl-test-warn/meta.yaml
Labels: please review & merge

#36433 Remove perl-version, it has been migrated to conda-forge.
  recipes/perl-version/build.sh
  recipes/perl-version/meta.yaml
Labels: please review & merge

#36441 Remove perl-test-output, it has been migrated to conda-forge.
  recipes/perl-test-output/build.sh
  recipes/perl-test-output/meta.yaml
Labels: please review & merge

#36255 Add r-bulkanalyzer.
  recipes/r-bulkanalyser/build.sh
  recipes/r-bulkanalyser/meta.yaml
Labels: please review & merge

#36440 Remove perl-io-stringy, it has been migrated to conda-forge.
  recipes/perl-io-stringy/build.sh
  recipes/perl-io-stringy/meta.yaml
Labels: please review & merge

#36439 Remove perl-capture-tiny, it has been migrated to conda-forge.
  recipes/perl-capture-tiny/build.sh
  recipes/perl-capture-tiny/meta.yaml
Labels: please review & merge

#36434 Remove perl-io-tty, it has been migrated to conda-forge.
  recipes/perl-io-tty/build.sh
  recipes/perl-io-tty/meta.yaml
Labels: please review & merge

#36438 Remove perl-compress-raw-bzip2, it has been migrated to conda-forge.
  recipes/perl-compress-raw-bzip2/build.sh
  recipes/perl-compress-raw-bzip2/meta.yaml
Labels: please review & merge

#36437 Remove perl-env, it has been migrated to conda-forge.
  recipes/perl-env/build.sh
  recipes/perl-env/meta.yaml
Labels: please review & merge

#36435 Remove perl-carp, it has been migrated to conda-forge.
  recipes/perl-carp/build.sh
  recipes/perl-carp/meta.yaml
Labels: please review & merge

#36446 Remove perl-path-tiny, it has been migrated to conda-forge.
  recipes/perl-path-tiny/0.076/build.sh
  recipes/perl-path-tiny/0.076/meta.yaml
  recipes/perl-path-tiny/build.sh
  recipes/perl-path-tiny/meta.yaml
Labels: please review & merge

#36445 Remove perl-json-pp, it has been migrated to conda-forge.
  recipes/perl-json-pp/build.sh
  recipes/perl-json-pp/meta.yaml
Labels: please review & merge

#36444 Remove perl-common-sense, it has been migrated to conda-forge.
  recipes/perl-common-sense/build.sh
  recipes/perl-common-sense/meta.yaml
Labels: please review & merge

#36447 Remove perl-xml-xpath, it has been migrated to conda-forge.
  recipes/perl-xml-xpath/build.sh
  recipes/perl-xml-xpath/meta.yaml
Labels: please review & merge

#36452 Remove perl-scope-guard, it has been migrated to conda-forge.
  recipes/perl-scope-guard/build.sh
  recipes/perl-scope-guard/meta.yaml
Labels: please review & merge

#36451 Remove perl-importer, it has been migrated to conda-forge.
  recipes/perl-importer/build.sh
  recipes/perl-importer/meta.yaml
Labels: please review & merge

#36457 Update KMCP to v0.8.3
  recipes/kmcp/meta.yaml
Labels: please review & merge

#36476 Update emu
  recipes/emu/meta.yaml
Labels: please review & merge

#36412 Add Biocode recipe
  recipes/biocode/biocode.patch
  recipes/biocode/meta.yaml
Labels: please review & merge

#36478 Disable AVX2 in StrobeAlign
  recipes/strobealign/build.sh
  recipes/strobealign/meta.yaml
Labels: please review & merge

#36488 Update meta.yaml new release of flashlfq
  recipes/flashlfq/meta.yaml
Labels: please review & merge

#36143 Add Fiji plugin Max_Inscribed_Circles
  recipes/fiji-max-inscribed_circles/LICENSE.txt
  recipes/fiji-max-inscribed_circles/build.sh
  recipes/fiji-max-inscribed_circles/meta.yaml
  recipes/fiji-max-inscribed_circles/run_test.sh
  recipes/fiji-max-inscribed_circles/test.groovy
Labels: please review & merge

#36399 Add phcue-ck recipe
  recipes/phcue-ck/build.sh
  recipes/phcue-ck/meta.yaml
Labels: please review & merge

#36473 Add haplomap-0.1.0
  recipes/haplomap/build.sh
  recipes/haplomap/meta.yaml
Labels: please review & merge

#36497 Update Auspice to 2.37.3
  recipes/auspice/meta.yaml
Labels: help wanted, please review & merge

#36517 vsnp3 version 3.09
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#36521 Add Physiofit4galaxy v2.0.4
  recipes/physiofit4galaxy/LICENSE
  recipes/physiofit4galaxy/meta.yaml
Labels: please review & merge

#36522 add cdhit-reader
  cdhit-reader/meta.yaml
Labels: please review & merge

#36511 Update dependencies for reference inference
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#36540 update cdhit-reader
  recipes/cdhit-reader/meta.yaml
Labels: please review & merge

#36547 Updated HATCHet to v1.0.3
  recipes/hatchet/meta.yaml
Labels: please review & merge

#36551 Update treetime dependency version for augur
  recipes/augur/meta.yaml
Labels: please review & merge

#36566 New sam2lca build to fix broken dependancy
  recipes/sam2lca/meta.yaml
Labels: please review & merge

#36565 Remove perl-test-exception, it has been migrated to conda-forge.
  recipes/perl-test-exception/build.sh
  recipes/perl-test-exception/meta.yaml
Labels: please review & merge

#36564 Remove perl-env-path, it has been migrated to conda-forge.
  recipes/perl-env-path/build.sh
  recipes/perl-env-path/meta.yaml
Labels: please review & merge

#36573 Add learnMSA
  recipes/learnmsa/LICENSE.md
  recipes/learnmsa/meta.yaml
Labels: please review & merge

#36601 Update CCTK recipe to version 0.8.4
  recipes/cctk/meta.yaml
Labels: please review & merge

#36483 Add ccsmeth recipe
  recipes/ccsmeth/meta.yaml
Labels: please review & merge

#36618 Update jgoslin to version 2.0.2 and JDK 17
  recipes/jgoslin/meta.yaml
Labels: please review & merge

#36576 Remove perl-test-without-module, it has been migrated to conda-forge.
  recipes/perl-test-without-module/build.sh
  recipes/perl-test-without-module/meta.yaml
Labels: please review & merge

#36589 Add PGR-TK
  recipes/pgr-tk/LICENSE
  recipes/pgr-tk/build.sh
  recipes/pgr-tk/meta.yaml
Labels: please review & merge

#36641 PGR-tk run time dependence update
  recipes/pgr-tk/meta.yaml
Labels: please review & merge

#36637 Update meta.yaml
  recipes/gothresher/meta.yaml
Labels: please review & merge

#36639 Add dist_est
  recipes/dist_est/build.sh
  recipes/dist_est/meta.yaml
Labels: please review & merge

#36650 Update: lorikeet-genome v0.7.2
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#36651 CIRCexplorer2: add dependencies
  recipes/circexplorer2/meta.yaml
Labels: please review & merge

#36528 Update to smallgenomeutilities v0.3.7
  recipes/smallgenomeutilities/0.3.7/meta.yaml
Labels: please review & merge

#36666 Remove perl-svg, it has been migrated to conda-forge.
  recipes/perl-svg/build.sh
  recipes/perl-svg/meta.yaml
Labels: do-not-close

#36668 Update pygenomeviz to 0.2.2
  recipes/pygenomeviz/meta.yaml
Labels: please review & merge

#36664 Update meta.yaml
  recipes/gothresher/meta.yaml
Labels: please review & merge

#36672 Remove numkit
  recipes/numkit/meta.yaml
Labels: please review & merge

#36696 Update pypints with dependent_tools
  recipes/pypints/meta.yaml
Labels: please review & merge

#36655 Remove perl-if, it has been migrated to conda-forge.
  recipes/perl-if/build.sh
  recipes/perl-if/meta.yaml
Labels: please review & merge

#36657 add python-nextflow
  recipes/python-nextflow/meta.yaml
Labels: please review & merge

#36685 Update scar 0.4.4
  recipes/scar/meta.yaml
Labels: please review & merge

#36712 Add r-dinamic.duo.
  recipes/r-dinamic.duo/build.sh
  recipes/r-dinamic.duo/meta.yaml
Labels: please review & merge

#36713 Update MSMetaEnhancer: add aiocircuitbreaker dependency
  recipes/msmetaenhancer/meta.yaml
Labels: please review & merge

#36703 Add tecount recipe
  recipes/tecount/meta.yaml
Labels: please review & merge

#36683 Update truvari meta.yaml
  recipes/truvari/meta.yaml
Labels: please review & merge
