Repository bioconda/bioconda-recipes, pull requests merged in 2022-07, with the labels that each got.

#35565 Add r-pathwaytmb.
  recipes/r-pathwaytmb/build.sh
  recipes/r-pathwaytmb/meta.yaml
Labels: please review & merge

#35151 add new recipe sbol-utilities 1.0a16
  recipes/sbol-utilities/meta.yaml
  recipes/sbol-utilities/run_test.sh
  recipes/sbol-utilities/sbolgraph-standalone.patch
Labels: please review & merge

#35593 Add cctk recipe
  recipes/cctk/meta.yaml
Labels: please review & merge

#35595 Add agouti
  recipes/agouti/LICENSE
  recipes/agouti/meta.yaml
Labels: please review & merge

#34788 Add genmod v3.7.4
  recipes/genmod/meta.yaml
Labels: please review & merge

#35620 Prune msisensor-pro requirements and fix macOS build
  recipes/msisensor-pro/build.sh
  recipes/msisensor-pro/buildfixes.patch
  recipes/msisensor-pro/meta.yaml
Labels: please review & merge

#35621 Updated HATCHet to v1.0.0
  recipes/hatchet/meta.yaml
Labels: please review & merge

#35510 Update bowtie: remove osx platform build preclusion
  recipes/bowtie/meta.yaml
  recipes/bowtie/rename_version_to_version_txt.patch
Labels: please review & merge

#35572 Add recipe for HmnTrimmer
  recipes/hmntrimmer/build.sh
  recipes/hmntrimmer/conda_build_config.yaml
  recipes/hmntrimmer/meta.yaml
  recipes/hmntrimmer/run_test.sh
Labels: please review & merge

#35643 Update: Lorikeet genome v0.6.6 -> v0.7.0
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#35628 Install scte v1.0.0
  recipes/scte/meta.yaml
Labels: please review & merge

#35660 Add initial recipe for covsonar
  recipes/covsonar/meta.yaml
Labels: please review & merge

#35666 add pyabpoa
  recipes/pyabpoa/LICENSE
  recipes/pyabpoa/meta.yaml
Labels: please review & merge

#35655 update Drop to 1.2.1
  recipes/drop/meta.yaml
  recipes/drop/run_test.sh
Labels: please review & merge

#35640 Updated HATCHet to v1.0.1
  recipes/hatchet/meta.yaml
Labels: please review & merge

#35629 mantis_pfa 1.5.5
  recipes/mantis_pfa/meta.yaml
Labels: please review & merge

#35685 Add AmpliGone
  recipes/ampligone/meta.yaml
Labels: please review & merge

#35392 Add gfmix
  recipes/gfmix/build.sh
  recipes/gfmix/meta.yaml
Labels: please review & merge

#35726 update wfmash 0.9.1
  recipes/wfmash/meta.yaml
Labels: please review & merge

#35748 Update `fastobo` recipe and skip build for Python 3.6
  recipes/fastobo/meta.yaml
Labels: please review & merge

#35701 Add Merqury fonts for biocontainer
  recipes/merqury/meta.yaml
Labels: please review & merge

#35708 Update to BISCUIT 1.1.0
  recipes/biscuit/meta.yaml
  recipes/biscuit/patch
Labels: please review & merge

#35693 Add mgcod
  recipes/mgcod/build.sh
  recipes/mgcod/meta.yaml
  recipes/mgcod/post-link.sh
Labels: help wanted, please review & merge

#35687 Rebuild nullarbor container
  recipes/nullarbor/meta.yaml
Labels: please review & merge

#35771 [seqfu] update build to install utilities
  recipes/seqfu/build.sh
  recipes/seqfu/meta.yaml
Labels: please review & merge

#34330 Add recipe for Physlr
  recipes/physlr/build.sh
  recipes/physlr/meta.yaml
Labels: please review & merge

#35791 Update vembrane: fix intervaltree versions
  recipes/vembrane/meta.yaml
Labels: please review & merge

#35647 Update to bedops 2.4.40 and reinstate macOS build
  build-fail-blacklist
  recipes/bedops/meta.yaml
  recipes/bedops/omit-bad-mutable.patch
Labels: please review & merge

#35793 Update Nexstalign to 2.3.0
  recipes/nextalign/meta.yaml
Labels: please review & merge

#35797 Update dgenies to 1.4.0
  recipes/dgenies/build.sh
  recipes/dgenies/meta.yaml
Labels: please review & merge, new version

#35749 Add goldrush
  recipes/goldrush/build.sh
  recipes/goldrush/meta.yaml
Labels: please review & merge

#35560 Install_vrhyme_v1.1.0
  recipes/vrhyme/meta.yaml
Labels: please review & merge

#35809 Add blastMining
  recipes/blastmining/meta.yaml
Labels: please review & merge

#35836 Update Duet to v0.4
  recipes/duet/meta.yaml
Labels: please review & merge

#35828 update pysradb
  recipes/pysradb/meta.yaml
Labels: please review & merge

#35827 update tcoffee version
  recipes/t_coffee/meta.yaml
Labels: please review & merge

#35840 Update captus recipe
  recipes/captus/meta.yaml
Labels: please review & merge

#35833 Add SELAM
  recipes/selam/build.sh
  recipes/selam/meta.yaml
Labels: please review & merge

#35820 Add multivelo
  recipes/multivelo/meta.yaml
Labels: please review & merge

#35877 Update Lorikeet genome to v0.7.1
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#35902 Add Aviary v0.4.1
  recipes/aviary/meta.yaml
Labels: please review & merge

#35906 Update meta.yaml
  recipes/eggnog-mapper/meta.yaml
Labels: please review & merge

#35837 Update COBS to v0.2.0
  recipes/cobs/0001-Add-openmp-to-compile-flags.patch
  recipes/cobs/build.sh
  recipes/cobs/meta.yaml
Labels: MacOS related, new version

#35839 Add pharokka
  recipes/pharokka/build.sh
  recipes/pharokka/meta.yaml
Labels: please review & merge

#35895 Update mothur: remove osx platform build preclusion
  recipes/mothur/meta.yaml
Labels: please review & merge

#35918 update Physlr to v1.0.4
  recipes/physlr/meta.yaml
Labels: please review & merge

#35908 Feat/nightly update repodata patches
  azure-pipeline-nightly.yml
Labels: WIP

#35907 Add paplot
  recipes/paplot/meta.yaml
Labels: please review & merge

#35858 Add r-disprose.
  recipes/r-disprose/build.sh
  recipes/r-disprose/meta.yaml
Labels: please review & merge

#35887 Add ashleys-qc
  recipes/ashleys-qc/meta.yaml
Labels: please review & merge

#35831 Add r-umianalyzer.
  recipes/r-umianalyzer/build.sh
  recipes/r-umianalyzer/meta.yaml
Labels: please review & merge

#35930 add recipe for pasty
  recipes/pasty/build.sh
  recipes/pasty/meta.yaml
Labels: please review & merge

#35929 Update cryfa to version 20.04
  recipes/cryfa/build.sh
  recipes/cryfa/meta.yaml
Labels: please review & merge

#35778 Update nanopolish
  recipes/nanopolish/build.sh
  recipes/nanopolish/meta.yaml
  recipes/nanopolish/patch
Labels: please review & merge

#35463 Add recipe for Corekaburra
  recipes/corekaburra/meta.yaml
Labels: please review & merge

#35948 Downgrade HiTaC's dependency
  recipes/hitac/meta.yaml
Labels: please review & merge

#35935 add interval-binning package
  recipes/interval-binning/meta.yaml
Labels: please review & merge

#35954 Add mammal
  recipes/mammal/build.sh
  recipes/mammal/meta.yaml
Labels: please review & merge

#35953 Add the lrtk recipes
  recipes/lrtk/meta.yaml
Labels: please review & merge

#35960 Update GRIMER to 1.0.0
  recipes/grimer/meta.yaml
Labels: please review & merge

#35974 Update meta.yaml
  recipes/blastmining/meta.yaml
Labels: please review & merge

#35922 add contatester
  recipes/contatester/meta.yaml
Labels: please review & merge

#35980 Update ccne to 1.1.2
  recipes/ccne/meta.yaml
Labels: please review & merge

#35959 Add nanomonsv
  recipes/nanomonsv/meta.yaml
Labels: please review & merge

#35977 Update pharokka v 0.1.7
  recipes/pharokka/meta.yaml
Labels: please review & merge

#35845 Add Ancestry_HMM
  recipes/ancestry_hmm/build.sh
  recipes/ancestry_hmm/meta.yaml
Labels: please review & merge

#35897 Update blast to 2.13.0
  recipes/blast/build.sh
  recipes/blast/meta.yaml
  recipes/blast/phonehome.patch
Labels: please review & merge

#35303 Add c4counter hla-asm mhc-annotation
  recipes/c4counter/meta.yaml
  recipes/hla-asm/build.sh
  recipes/hla-asm/meta.yaml
  recipes/hla-asm/post-link.sh
  recipes/hla-asm/pre-unlink.sh
  recipes/mhc-annotation/meta.yaml
Labels: please review & merge

#35531 Add sciphin bioconda recipe.
  recipes/sciphin/build.sh
  recipes/sciphin/meta.yaml
Labels: please review & merge

#35408 Add fastremap-bio
  recipes/fastremap-bio/build.sh
  recipes/fastremap-bio/meta.yaml
Labels: please review & merge

#35544 Add runjob recipe
  recipes/runjob/meta.yaml
Labels: please review & merge

#35994 Add nedrex recipe
  recipes/nedrex/meta.yaml
Labels: please review & merge

#35996 Update ntjoin to 1.1.1
  recipes/ntjoin/build.sh
  recipes/ntjoin/meta.yaml
Labels: please review & merge

#35983 Busco update
  recipes/busco/meta.yaml
Labels: please review & merge

#36011 Busco fix
  recipes/busco/meta.yaml
Labels: please review & merge

#36000 Update Physlr v1.0.4 build 1
  recipes/physlr/build.sh
  recipes/physlr/meta.yaml
Labels: please review & merge

#36006 Update influx_si for dependencies and test
  recipes/influx_si/meta.yaml
Labels: please review & merge

#35992 Update Phanotate: Add trnascan-se
  recipes/phanotate/meta.yaml
Labels: please review & merge

#36044 Update nextflow to 22.04.5
  recipes/nextflow/meta.yaml
Labels: please review & merge

#36033 Add recipe for fibertools-rs
  recipes/fibertools-rs/build.sh
  recipes/fibertools-rs/meta.yaml
Labels: please review & merge

#36047 vsnp version update 3.08
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#36029 Update to PINTS 1.1.6
  recipes/pypints/meta.yaml
Labels: please review & merge

#36058 Update CheckV to 1.0.0
  recipes/checkv/meta.yaml
Labels: please review & merge

#36101 [seqfu] add conda forge channel
  recipes/seqfu/meta.yaml
Labels: please review & merge

#36108 Update pybedlite
  recipes/pybedlite/meta.yaml
Labels: please review & merge

#36122 Add czlab_perl_lib
  recipes/czlab_perl_lib/build.sh
  recipes/czlab_perl_lib/meta.yaml
Labels: please review & merge

#36035 Update Fiji build
  recipes/fiji/ImageJ.sh
  recipes/fiji/build.sh
  recipes/fiji/meta.yaml
  recipes/fiji/run_test.sh
Labels: please review & merge

#36110 Update igblast to 1.19.0
  recipes/igblast/meta.yaml
Labels: please review & merge

#35806 Add geNomad
  recipes/genomad/meta.yaml
Labels: please review & merge

#36100 Add r-lipidomer.
  recipes/r-lipidomer/build.sh
  recipes/r-lipidomer/meta.yaml
Labels: please review & merge

#36141 add parallel-virfinder
  recipes/parallel-virfinder/build.sh
  recipes/parallel-virfinder/meta.yaml
Labels: please review & merge

#36146 Update isescan
  build-fail-blacklist
  recipes/isescan/build.sh
  recipes/isescan/constants.patch
  recipes/isescan/meta.yaml
Labels: please review & merge

#33559 Update nextstrain-cli: add zika build test
  recipes/nextstrain-cli/meta.yaml
  recipes/nextstrain-cli/run_test.sh
Labels: please review & merge

#36152 Add r-tidyheatmap.
  recipes/r-tidyheatmap/build.sh
  recipes/r-tidyheatmap/meta.yaml
Labels: please review & merge
