Repository bioconda/bioconda-recipes, pull requests merged in 2022-10, with the labels that each got.

#37138 Add recipe for VASE by David A. Parry
  recipes/vase/0.2.4/meta.yaml
  recipes/vase/0.5.1/meta.yaml
  recipes/vase/LICENSE
Labels: please review & merge

#36692 bump stacks1
  recipes/stacks/1.37/build.sh
  recipes/stacks/1.37/meta.yaml
  recipes/stacks/1.46/meta.yaml
  recipes/stacks/1.48/at.patch
  recipes/stacks/1.48/build.sh
  recipes/stacks/1.48/meta.yaml
  recipes/stacks/2.0/build.sh
  recipes/stacks/2.0/meta.yaml
  recipes/stacks/2.1/build.sh
  recipes/stacks/2.1/meta.yaml
  recipes/stacks/2.2/at.patch
  recipes/stacks/2.2/build.sh
  recipes/stacks/2.2/meta.yaml
  recipes/stacks/2.3/at.patch
  recipes/stacks/2.3/build.sh
  recipes/stacks/2.3/meta.yaml
  recipes/stacks/2.3b/at.patch
  recipes/stacks/2.3b/build.sh
  recipes/stacks/2.3c/at.patch
  recipes/stacks/2.3c/build.sh
  recipes/stacks/2.3c/meta.yaml
Labels: please review & merge

#37244 Update seqscreen meta.yaml
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#37233 Add pybmtools
  recipes/pybmtools/build.sh
  recipes/pybmtools/meta.yaml
Labels: please review & merge

#37211 Install phamb v1.0.1
  recipes/phamb/meta.yaml
Labels: please review & merge

#37265 Remove perl-xml-filter-buffertext, it has been migrated to conda-forge.
  recipes/perl-xml-filter-buffertext/build.sh
  recipes/perl-xml-filter-buffertext/meta.yaml
Labels: please review & merge

#37281 Update igvtools to 2.14.1
  recipes/igvtools/meta.yaml
Labels: please review & merge

#37289 Update tRNAscan-SE to 2.0.11
  recipes/trnascan-se/meta.yaml
Labels: please review & merge

#37267 update Freyja to v1.3.11
  recipes/freyja/meta.yaml
Labels: please review & merge

#37279 Update nextclade to 2.6.0
  recipes/nextclade/meta.yaml
Labels: please review & merge

#37296 Update ngs-bits to version 2022_10
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#37294 Update: Lorikeet v0.7.3
  recipes/lorikeet-genome/meta.yaml
Labels: please review & merge

#37317 Update dnmtools
  recipes/dnmtools/meta.yaml
Labels: please review & merge

#37231 add recipe for PAVFinder
  recipes/pavfinder/meta.yaml
Labels: please review & merge

#37229 Update auspice requirements
  recipes/auspice/meta.yaml
Labels: please review & merge

#37262 Add Calder R package for hierarchical Hi-C compartments analysis
  recipes/r-calder2/build.sh
  recipes/r-calder2/meta.yaml
Labels: please review & merge

#37269 Update unitig-caller to v1.3.0
  recipes/unitig-caller/0001-patch-for-conda-OS-X.patch
  recipes/unitig-caller/0002-Change-linker-for-filesystem-path.patch
  recipes/unitig-caller/build.sh
  recipes/unitig-caller/meta.yaml
Labels: please review & merge

#37290 Bump hopla version
  recipes/hopla/meta.yaml
Labels: please review & merge

#37283 Update SeqScreen meta.yaml
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#37291 Update SierraPy to 0.4.1
  recipes/sierrapy/meta.yaml
Labels: please review & merge

#37306 update fasta3 to latest version
  recipes/fasta3/meta.yaml
Labels: please review & merge

#37314 update abismal to 3.1.1
  recipes/abismal/meta.yaml
Labels: please review & merge

#37292 [Update] BTE version bump + updated dependency
  recipes/bte/meta.yaml
Labels: please review & merge

#37270 Update parse-vcf
  recipes/parse-vcf/meta.yaml
Labels: please review & merge

#37320 Update nextclade and nextalign to version 2.7.0
  recipes/nextalign/meta.yaml
  recipes/nextclade/meta.yaml
Labels: please review & merge

#37312 Add Porechop abi
  recipes/porechop_abi/meta.yaml
Labels: please review & merge

#37324 Update gambit to 1.0.0
  recipes/gambit/meta.yaml
Labels: please review & merge

#37325 Semibin v1.1.1 relax deps
  recipes/semibin/meta.yaml
Labels: please review & merge

#37328 Update spectrum_utils to version 0.4.0
  recipes/spectrum_utils/meta.yaml
Labels: please review & merge

#37326 Add recipe for bayescode v1.1.6
  recipes/bayescode/build.sh
  recipes/bayescode/meta.yaml
Labels: please review & merge

#37327 Update preseq
  recipes/preseq/meta.yaml
Labels: please review & merge

#37364 update augustus 3.5.0 recipe
  recipes/augustus/Build.PL
  recipes/augustus/build.sh
  recipes/augustus/meta.yaml
  recipes/augustus/patches/bam2hints.makefile.patch
  recipes/augustus/patches/bam2wig.makefile.patch
  recipes/augustus/patches/compileSpliceCands.makefile.patch
  recipes/augustus/patches/filterBam.makefile.patch
  recipes/augustus/patches/filterBam.src.makefile.patch
  recipes/augustus/patches/filterBam.src.makefile.patch.osx
  recipes/augustus/patches/homGeneMapping.src.makefile.patch
  recipes/augustus/patches/joingenes.makefile.patch
  recipes/augustus/patches/pp_profile.patch
  recipes/augustus/patches/src.makefile.patch
  recipes/augustus/patches/utrrnaseq.patch
  recipes/augustus/patches/utrrnaseq.src.patch
Labels: please review & merge, new version

#37371 Update seqscreen meta.yaml
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#37382 Update the segmetrics recipe to 1.0.0
  recipes/segmetrics/meta.yaml
Labels: please review & merge

#37392 Update irescue to 1.0.2
  recipes/irescue/meta.yaml
Labels: please review & merge

#37425 Update pharokka v1.0.1
  recipes/pharokka/meta.yaml
Labels: please review & merge

#37387 Update build number of PGCGAP
  recipes/pgcgap/meta.yaml
Labels: please review & merge

#37449 Update unifrac-binaries to 1.1.2
  recipes/unifrac-binaries/meta.yaml
  recipes/unifrac-binaries/mkstemp.patch
Labels: please review & merge

#37415 Update influx 6.1
  recipes/influx_si/meta.yaml
Labels: please review & merge

#37456 Bump Nextflow 22.10.0
  recipes/nextflow/meta.yaml
Labels: please review & merge

#37457 Update MMseqs2 to 14-7e284
  recipes/mmseqs2/meta.yaml
Labels: please review & merge

#37441 Update phylofisher
  recipes/phylofisher/meta.yaml
Labels: please review & merge

#37458 Add libgd for graphical output
  recipes/rnahybrid/meta.yaml
Labels: please review & merge

#37395 Update AODP to v2.5.0.2
  recipes/aodp/meta.yaml
Labels: please review & merge

#37469 Update tigmint to v1.2.7
  recipes/tigmint/build.sh
  recipes/tigmint/meta.yaml
Labels: please review & merge

#37477 update mirfix to 2.1.0
  recipes/mirfix/meta.yaml
Labels: please review & merge

#37484 Fix geNomad requirements
  recipes/genomad/meta.yaml
Labels: please review & merge

#37485 Update bioconductor-genomeinfodb to latest patch release for BioC 3.14
  recipes/bioconductor-genomeinfodb/meta.yaml
Labels: please review & merge

#37372 Update glimmerhmm 3.0.4 build 5
  build-fail-blacklist
  recipes/glimmerhmm/meta.yaml
Labels: please review & merge, update build number

#37375 Update gimmemotifs to 0.17.2 and unpin python
  recipes/gimmemotifs/conda_build_config.yaml
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge

#37474 Add recipe for psm_utils
  recipes/psm-utils/LICENSE
  recipes/psm-utils/meta.yaml
Labels: please review & merge

#37486 Bump bioconductor-annotationdbi to latest patch release for BioC 3.14
  recipes/bioconductor-annotationdbi/meta.yaml
Labels: please review & merge

#37322 Update metagenome-atlas v2.12 with new dependencies
  recipes/metagenome-atlas/meta.yaml
Labels: please review & merge

#37493 [Add] LolliPop
  recipes/lollipop/meta.yaml
Labels: please review & merge

#37495 add args_oap
  recipes/args_oap/meta.yaml
Labels: please review & merge

#37494 Update lukasa to 0.10.0
  recipes/lukasa/meta.yaml
Labels: please review & merge

#37513 Update r-calder2 to version 0.3
  recipes/r-calder2/build.sh
  recipes/r-calder2/meta.yaml
  recipes/r-calder2/run_test.sh
Labels: please review & merge

#37480 Add StrandPhaseR
  recipes/strandphaser/build.sh
  recipes/strandphaser/meta.yaml
Labels: please review & merge

#37520 Update meta.yaml
  recipes/ampcombi/meta.yaml
Labels: please review & merge

#37536 Add missing dep for shinyngs
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#37541 Add pyrovelocity 0.1.0 to bioconda
  recipes/pyrovelocity/meta.yaml
Labels: please review & merge

#37545 Update lukasa to 0.11.0
  recipes/lukasa/meta.yaml
Labels: please review & merge

#37533 Update Semibin to v1.2.0
  recipes/semibin/meta.yaml
Labels: please review & merge

#37552 Add physiofit manager 1.0.1
  recipes/physiofit_data_manager/LICENSE
  recipes/physiofit_data_manager/meta.yaml
Labels: please review & merge

#37557 Update ashleys-qc to 0.2.1
  recipes/ashleys-qc/meta.yaml
Labels: please review & merge

#37568 Update phyloacc
  recipes/phyloacc/build.sh
  recipes/phyloacc/meta.yaml
Labels: please review & merge

#37569 Update TELR dependency list
  recipes/telr/meta.yaml
Labels: please review & merge

#37572 Update Bismark recipe for v0.24.0
  recipes/bismark/meta.yaml
Labels: please review & merge

#37576 update pharokka v1.1.0
  recipes/pharokka/meta.yaml
Labels: please review & merge

#37593 relaxing mirfix dependencies for better upstream integration
  recipes/mirfix/meta.yaml
Labels: please review & merge

#37598 bump r-shinyngs version
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#37563 Update vgan to version 1.0.1
  recipes/vgan/meta.yaml
Labels: please review & merge

#37586 Update aviary to 0.5.4.
  recipes/aviary/meta.yaml
Labels: please review & merge

#37612 Update to r-enchantr 0.0.3
  recipes/r-enchantr/meta.yaml
Labels: please review & merge

#37644 Update nextstrain-cli to 5.0.0
  recipes/nextstrain-cli/meta.yaml
Labels: please review & merge

#37524 Update magicblast to 1.7.0
  recipes/magicblast/build.sh
  recipes/magicblast/meta.yaml
Labels: please review & merge

#37643 update smallgenomeutilities to 0.3.9
  recipes/smallgenomeutilities/0.2.1/build.sh
  recipes/smallgenomeutilities/0.2.1/meta.yaml
  recipes/smallgenomeutilities/0.3.0/build.sh
  recipes/smallgenomeutilities/0.3.0/meta.yaml
  recipes/smallgenomeutilities/0.3.6/meta.yaml
  recipes/smallgenomeutilities/0.3.7/meta.yaml
  recipes/smallgenomeutilities/0.3.8/meta.yaml
  recipes/smallgenomeutilities/meta.yaml
Labels: please review & merge

#37616 Update MALT to 0.6.1
  recipes/malt/build.sh
  recipes/malt/meta.yaml
Labels: please review & merge

#37661 Update ngmaster v1.0.0 recipe
  recipes/ngmaster/meta.yaml
Labels: please review & merge

#37602 cooltools: update meta.yml for 0.5.2
  recipes/cooltools/meta.yaml
Labels: please review & merge

#37664 add svhip to fork
  recipes/svhip/build.sh
  recipes/svhip/meta.yaml
Labels: please review & merge

#37638 shinyngs: bump and pin pandoc to avoid bad build
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#37587 Update MBG to version 1.0.12
  recipes/mbg/meta.yaml
Labels: please review & merge

#37383 Update mummer4 to fix mummerplot
  recipes/mummer4/meta.yaml
  recipes/mummer4/mummerplot.pl.patch
Labels: please review & merge

#37588 Update dicey to 0.2.1
  recipes/dicey/meta.yaml
Labels: please review & merge

#37645 Update meta.yaml
  recipes/eigensoft/build.sh
  recipes/eigensoft/meta.yaml
Labels: please review & merge

#37608 add sanntis
  recipes/sanntis/meta.yaml
Labels: please review & merge

#37651 Add geofetch to bioconda
  recipes/geofetch/meta.yaml
Labels: please review & merge

#37652 Update for thermorawfileparser v1.4.1
  recipes/thermorawfileparser/meta.yaml
Labels: please review & merge

#37666 Add programs in UShER package
  recipes/usher/build.sh
  recipes/usher/meta.yaml
Labels: please review & merge

#37669 Update meta.yaml for abritamr 1.0.13
  recipes/abritamr/meta.yaml
Labels: please review & merge

#37660 Update locarna recipe, pin to current Vienna RNA
  recipes/locarna/meta.yaml
Labels: please review & merge

#37672 Update wfmash to 0.10.0
  recipes/wfmash/build.sh
  recipes/wfmash/meta.yaml
Labels: please review & merge

#37585 Add sashimi-py to bioconda
  recipes/sashimi-py/LICENSE
  recipes/sashimi-py/meta.yaml
Labels: please review & merge

#37080 Add cvlr
  recipes/cvlr/build.sh
  recipes/cvlr/meta.yaml
Labels: please review & merge

#36563 Update angsd
  recipes/angsd/build.sh
  recipes/angsd/meta.yaml
  recipes/angsd/vcfreader.patch
Labels: please review & merge

#37682 Add GToTree v1.7.05
  recipes/gtotree/build.sh
  recipes/gtotree/meta.yaml
  recipes/gtotree/post-link.sh
Labels: please review & merge
