Repository bioconda/bioconda-recipes, pull requests merged in 2022-01, with the labels that each got.

#32248 Update build for rustybam
  recipes/rustybam/meta.yaml
Labels: please review & merge

#32256 Make sure r-lymphclon package works with packages from the same era
  recipes/r-lymphclon/meta.yaml
Labels: please review & merge

#31652 Update ViennaRNA to v2.5.0
  recipes/viennarna/build.sh
  recipes/viennarna/meta.yaml
Labels: please review & merge

#32269 Update pantools to 3.3.3
  recipes/pantools/build.sh
  recipes/pantools/meta.yaml
Labels: please review & merge

#32071 Update STREAM to v1.1
  recipes/stream/meta.yaml
  recipes/stream/patch
Labels: help wanted, please review & merge

#32277 Update MBG to version 1.0.8
  recipes/mbg/meta.yaml
Labels: please review & merge

#32279 Update kmc to version 3.2.1
  build-fail-blacklist
  recipes/kmc/3.0.0_static/meta.yaml
  recipes/kmc/build.sh
  recipes/kmc/meta.yaml
  recipes/kmc/shared_library.patch
Labels: please review & merge

#32278 Update GraphAligner to version 1.0.14
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#32280 Update smallgenomeutilies to version 0.3.5
  recipes/smallgenomeutilities/0.3.5/meta.yaml
Labels: please review & merge

#32271 Update PhyloCSFpp to 1.2.0
  recipes/phylocsfpp/meta.yaml
Labels: please review & merge, new version

#32297 update GCEN to 0.6.0
  recipes/gcen/meta.yaml
Labels: please review & merge

#32260 Update fade to v0.5.5
  recipes/fade/build.sh
  recipes/fade/meta.yaml
Labels: please review & merge

#32282 New unifrac-binaries recipe - v1.0.0
  recipes/unifrac-binaries/build.sh
  recipes/unifrac-binaries/meta.yaml
Labels: please review & merge

#32288 Update recontig package to 1.4.0
  recipes/recontig/build.sh
  recipes/recontig/meta.yaml
Labels: please review & merge

#31468 Update: Pre-test for OpenMS 2.7
  build-fail-blacklist
  recipes/openms-meta/ParamValue_h.patch
  recipes/openms-meta/build.sh
  recipes/openms-meta/conda_build_config.yaml
  recipes/openms-meta/init.py.patch
  recipes/openms-meta/install_pyopenms.sh
  recipes/openms-meta/meta.yaml
  recipes/openms-meta/package_libopenms.sh
Labels: please review & merge

#32314 Update nextclade recipe to latest version 1.8.1
  recipes/nextclade/meta.yaml
  recipes/nextclade/run_test.sh
Labels: please review & merge

#32315 Update nextalign recipe to latest version 1.8.1
  recipes/nextalign/meta.yaml
  recipes/nextalign/run_test.sh
  recipes/nextalign/test-data/genemap.gff
  recipes/nextalign/test-data/reference.fasta
  recipes/nextalign/test-data/sequences.fasta
Labels: please review & merge

#32325 Update unifrac to 1.0.0
  recipes/unifrac/build.sh
  recipes/unifrac/meta.yaml
Labels: please review & merge

#32332 Update recipi for f5c
  recipes/f5c/build.sh
  recipes/f5c/meta.yaml
Labels: please review & merge

#32353 Update SemiBin to 0.5.0
  recipes/semibin/meta.yaml
Labels: please review & merge

#32354 bump snap-aligner
  recipes/snap-aligner/meta.yaml
Labels: please review & merge

#32363 Update rgi to 5.2.1
  recipes/rgi/meta.yaml
Labels: please review & merge

#31655 Update odgi to 0.6.3
  recipes/odgi/build.sh
  recipes/odgi/meta.yaml
Labels: please review & merge

#32355 Update peka to 0.1.4 and add new maintainer
  recipes/peka/meta.yaml
Labels: please review & merge

#32370 Bump nextalign to 1.9.0
  recipes/nextalign/meta.yaml
Labels: please review & merge

#32371 Bump nextclade to 1.9.0
  recipes/nextclade/meta.yaml
Labels: please review & merge

#32372 Update Rgi to 5.2.1
  recipes/rgi/meta.yaml
Labels: please review & merge

#32374 ampvis2: add missing r-foreach requirement
  recipes/r-ampvis2/meta.yaml
Labels: please review & merge

#32382 Update interproscan to version 5.54-87.0
  recipes/interproscan/initial_setup.py.patch
  recipes/interproscan/meta.yaml
  recipes/interproscan/post-link.sh
Labels: please review & merge

#32347 adding mantis_pfa recipe;
  recipes/mantis_pfa/meta.yaml
Labels: please review & merge

#32390 Update dsh-bio to 2.0.7
  recipes/dsh-bio/build.sh
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#32387 Add plotsr
  recipes/plotsr/meta.yaml
Labels: please review & merge

#32385 Update mashmap (to fix build on macOS)
  build-fail-blacklist
  recipes/mashmap/meta.yaml
Labels: please review & merge

#32406 update mantis_pfa recipe
  recipes/mantis_pfa/meta.yaml
Labels: please review & merge

#32416 Update biscuit to 1.0.2
  recipes/biscuit/meta.yaml
Labels: please review & merge

#32423 Add agc
  recipes/agc/meta.yaml
Labels: please review & merge

#32422 update mantis_pfa
  recipes/mantis_pfa/meta.yaml
Labels: please review & merge

#32432 Add ConSplice bioconda recipe
  recipes/consplice/meta.yaml
Labels: please review & merge

#32428 Add Fiji morpholibj
  recipes/fiji-morpholibj/LICENSE
  recipes/fiji-morpholibj/basic.ijm
  recipes/fiji-morpholibj/build.sh
  recipes/fiji-morpholibj/grains.png
  recipes/fiji-morpholibj/meta.yaml
  recipes/fiji-morpholibj/run_test.sh
Labels: please review & merge

#32453 Update Chromap 0.1.5 recipes for macos
  recipes/chromap/meta.yaml
Labels: please review & merge

#32143 Add r-alakazam
  recipes/r-alakazam/build.sh
  recipes/r-alakazam/meta.yaml
Labels: please review & merge

#32443 Update toil reqs from main repository
  recipes/toil/meta.yaml
  recipes/toil/remove_wdlparse.patch
Labels: please review & merge

#32466 Update Biobb_cmip new prepare_pdb module 2021.4
  recipes/biobb_cmip/meta.yaml
Labels: please review & merge

#32448 Update coprarna with less constraint dependencies
  recipes/coprarna/meta.yaml
Labels: please review & merge

#32477 Add shazam recipe
  recipes/r-shazam/build.sh
  recipes/r-shazam/meta.yaml
Labels: please review & merge

#32435 probeit v2.1
  recipes/probeit/meta.yaml
Labels: please review & merge

#32484 Update ganon to 1.1.1
  recipes/ganon/meta.yaml
Labels: please review & merge

#32513 add HiLineToJuicer
  recipes/hilinetojuicer/meta.yaml
Labels: please review & merge

#32393 Add recipe for bamcmp
  recipes/bamcmp/build.sh
  recipes/bamcmp/meta.yaml
  recipes/bamcmp/run_test.sh
  recipes/bamcmp/test.bam
Labels: please review & merge

#32480 Add dowser recipe
  recipes/r-dowser/build.sh
  recipes/r-dowser/meta.yaml
Labels: please review & merge

#32534 Update MicroHapulator: fix entry point
  recipes/microhapulator/meta.yaml
Labels: help wanted, please review & merge

#32541 adding joblib dependency
  recipes/freyja/meta.yaml
Labels: please review & merge

#32449 Update integron_finder, bump to 2.0
  recipes/integron_finder/meta.yaml
Labels: please review & merge

#32517 Update KMC to non static compilation on linux bioconda and adds libraries
  recipes/kmc/Makefile.patch
  recipes/kmc/build.sh
  recipes/kmc/meta.yaml
Labels: please review & merge

#32360 Update Snakelines
  recipes/snakelines/meta.yaml
Labels: please review & merge

#32545 r-saige - rebuild with patched dependency
  recipes/r-saige/meta.yaml
Labels: please review & merge

#32553 Update genome_updater to 0.3.0
  recipes/genome_updater/meta.yaml
Labels: please review & merge

#32554 Update nextflow to 21.10.6
  recipes/nextflow/meta.yaml
Labels: please review & merge

#32555 rebuild Intarna 2.4.1
  recipes/intarna/2.x/build.sh
  recipes/intarna/2.x/meta.yaml
Labels: please review & merge

#32514 Add r-beyondcell package
  recipes/r-beyondcell/build.sh
  recipes/r-beyondcell/meta.yaml
Labels: please review & merge

#32570 Bump nextalign to 1.10.0
  recipes/nextalign/meta.yaml
Labels: please review & merge

#32571 Bump nextclade to 1.10.0
  recipes/nextclade/meta.yaml
Labels: please review & merge

#32577 Update pegasusio to 0.5.0
  recipes/pegasusio/meta.yaml
Labels: please review & merge

#32543 Add new recipe DeBreak
  recipes/debreak/build.sh
  recipes/debreak/meta.yaml
Labels: please review & merge

#32568 update freyja dependencies to allow python >=3.7
  recipes/freyja/meta.yaml
Labels: please review & merge

#32547 Add new recipe Inspector
  recipes/inspector/build.sh
  recipes/inspector/meta.yaml
Labels: please review & merge

#32567 Update `fastobo` to `v0.11.1`
  build-fail-blacklist
  recipes/fastobo/meta.yaml
Labels: please review & merge

#32582 bump r-saige version to 0.45
  recipes/r-saige/meta.yaml
Labels: please review & merge

#32578 Bump BioPhi to 1.0.3
  recipes/biophi/meta.yaml
Labels: please review & merge

#32574 Updated HATCHet to 0.4.10
  recipes/hatchet/meta.yaml
Labels: please review & merge

#32588 Update adam to 0.37.0
  recipes/adam/meta.yaml
Labels: please review & merge

#32589 Update cannoli to 0.15.0
  recipes/cannoli/meta.yaml
Labels: please review & merge

#32549 bump gembs v3.5.5_IHEC
  recipes/gembs/meta.yaml
  recipes/gembs/patch
Labels: please review & merge

#32579 [bamtocov] Update metadata fields
  recipes/bamtocov/meta.yaml
Labels: please review & merge

#32610 Bump nextalign to 1.10.1
  recipes/nextalign/meta.yaml
Labels: please review & merge

#32609 Bump nextclade to 1.10.1
  recipes/nextclade/meta.yaml
Labels: please review & merge

#32612 update gcen to 0.6.1
  recipes/gcen/meta.yaml
Labels: please review & merge

#32623 Update ICEscreen v1.0.2
  recipes/icescreen/meta.yaml
Labels: please review & merge

#32630 Add recipe for fastqtk
  recipes/fastqtk/build.sh
  recipes/fastqtk/makefile.patch
  recipes/fastqtk/meta.yaml
Labels: please review & merge

#32640 Pin tbb version and add fastqtk
  recipes/fusioncatcher/meta.yaml
Labels: please review & merge

#32641 Update ganon to 1.1.2
  recipes/ganon/meta.yaml
Labels: please review & merge

#32649 Update to ICEscreen v1.0.3
  recipes/icescreen/meta.yaml
Labels: please review & merge

#32648 Update OSX building
  recipes/verifybamid2/meta.yaml
Labels: please review & merge

#32633 Add stranger
  recipes/stranger/meta.yaml
Labels: please review & merge

#32663 Update biobb_structure_utils: update biobb_structure_checking version
  recipes/biobb_structure_utils/meta.yaml
Labels: please review & merge
