Repository bioconda/bioconda-recipes, pull requests merged in 2022-09, with the labels that each got.

#36762 Update HATCHet to v1.1.1
  recipes/hatchet/meta.yaml
Labels: please review & merge

#36755 Add recipe for `peptides` package
  recipes/peptides/meta.yaml
Labels: please review & merge

#36801 Remove perl-net-ssleay, it has been migrated to conda-forge.
  recipes/perl-net-ssleay/build.sh
  recipes/perl-net-ssleay/meta.yaml
Labels: please review & merge

#36805 Remove perl-io-socket-ssl, it has been migrated to conda-forge.
  recipes/perl-io-socket-ssl/build.sh
  recipes/perl-io-socket-ssl/meta.yaml
Labels: please review & merge

#36804 Remove perl-log-log4perl, it has been migrated to conda-forge.
  recipes/perl-log-log4perl/build.sh
  recipes/perl-log-log4perl/meta.yaml
Labels: please review & merge

#36802 Remove perl-dbi, it has been migrated to conda-forge.
  recipes/perl-dbi/build.sh
  recipes/perl-dbi/meta.yaml
Labels: please review & merge

#36811 Update Hecatomb to 1.1.0
  recipes/hecatomb/build.sh
  recipes/hecatomb/meta.yaml
Labels: please review & merge, new version

#36817 Add r-ggcoverage.
  recipes/r-ggcoverage/build.sh
  recipes/r-ggcoverage/meta.yaml
Labels: please review & merge

#36815 Update preseq
  recipes/preseq/build.sh
  recipes/preseq/meta.yaml
Labels: please review & merge

#36825 Remove perl-test-deep, it has been migrated to conda-forge.
  recipes/perl-test-deep/build.sh
  recipes/perl-test-deep/meta.yaml
Labels: please review & merge

#36824 Remove perl-test-harness, it has been migrated to conda-forge.
  recipes/perl-test-harness/build.sh
  recipes/perl-test-harness/meta.yaml
Labels: please review & merge

#36836 Update superfocus recipe - add mmseqs2
  recipes/super-focus/meta.yaml
Labels: please review & merge

#36800 bump build number for prinseq++ to debug #36561
  recipes/prinseq-plus-plus/meta.yaml
Labels: please review & merge

#36871 augustus: add a patch
  recipes/augustus/meta.yaml
  recipes/augustus/patches/pp_profile.patch
Labels: please review & merge

#36858 update dnmtools
  recipes/dnmtools/meta.yaml
Labels: please review & merge

#36880 Update MultiQC: Bump to v1.13, remove test imports
  recipes/multiqc/meta.yaml
Labels: please review & merge

#36876 Update dsh-bio to 2.1
  recipes/dsh-bio/build.sh
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#36894 Update hmftools-amber: add missing dplyr dependency
  recipes/hmftools-amber/meta.yaml
Labels: please review & merge

#36907 Reinstate python-bioext build
  build-fail-blacklist
  recipes/python-bioext/build.sh
  recipes/python-bioext/cythonize.patch
  recipes/python-bioext/meta.yaml
Labels: please review & merge, addressed-bulk-skip

#36877 Add somalier
  recipes/somalier/build.sh
  recipes/somalier/meta.yaml
Labels: please review & merge

#36875 Update flair to latest version (v1.6.3)
  recipes/flair/build.sh
  recipes/flair/flair.patch
  recipes/flair/meta.yaml
Labels: please review & merge

#36915 update falco to v1.2.0
  recipes/falco/build.sh
  recipes/falco/meta.yaml
Labels: please review & merge

#36864 Update WisecondorX recipe to 1.2.5
  recipes/wisecondorx/meta.yaml
Labels: please review & merge

#36900 Update hmftools-cobalt: add missing dplyr dependency
  recipes/hmftools-cobalt/meta.yaml
Labels: please review & merge

#36640 Add MArVD2
  recipes/marvd2/meta.yaml
Labels: please review & merge

#36918 Update scexecute to 1.3.2
  recipes/scexecute/meta.yaml
Labels: please review & merge

#36920 [python-nextflow] update specs
  recipes/python-nextflow/meta.yaml
Labels: please review & merge

#36658 Add phylofisher
  recipes/phylofisher/meta.yaml
Labels: help wanted, please review & merge

#36684 Add Macsyfinder recipe
  recipes/macsyfinder/meta.yaml
Labels: please review & merge

#36860 Add Relion
  recipes/relion/build.sh
  recipes/relion/meta.yaml
Labels: please review & merge

#36942 Remove perl-test, it has been migrated to conda-forge.
  recipes/perl-test/1.26/build.sh
  recipes/perl-test/1.26/meta.yaml
Labels: please review & merge

#36948 Update meta.yaml for seqfu
  recipes/seqfu/meta.yaml
Labels: please review & merge

#36940 Update Red to 2.0/2018.09.10
  recipes/red/build.sh
  recipes/red/makefile.patch
  recipes/red/meta.yaml
Labels: please review & merge

#36823 new recipe: nf-test
  recipes/nf-test/build.sh
  recipes/nf-test/meta.yaml
Labels: please review & merge

#36928 Add recipe for miniprot
  recipes/miniprot/build.sh
  recipes/miniprot/meta.yaml
Labels: please review & merge

#36853 vsnp3
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#36861 Update mafft to 7.508
  recipes/mafft/meta.yaml
Labels: please review & merge

#36964 bftools update
  recipes/bftools/meta.yaml
Labels: please review & merge

#36969 Upgrade scramble to v1.0.2
  recipes/scramble/meta.yaml
Labels: please review & merge

#36978 Update pharokka to v 1.0.0
  recipes/pharokka/meta.yaml
Labels: please review & merge

#36947 Update screadcounts to 1.3.1
  recipes/screadcounts/meta.yaml
Labels: please review & merge

#36981 Update rgi to 6.0.0
  recipes/rgi/meta.yaml
Labels: please review & merge

#36995 Update falco to 1.2.1
  recipes/falco/build.sh
  recipes/falco/meta.yaml
Labels: please review & merge

#36914 Reinstate atropos build
  build-fail-blacklist
  recipes/atropos/meta.yaml
  recipes/atropos/python310.patch
Labels: please review & merge, addressed-bulk-skip

#37004 Add irescue recipe
  recipes/irescue/meta.yaml
Labels: please review & merge

#37008 changing falco's meta to a (hopefully) fixed version of falco that ru…
  recipes/falco/meta.yaml
Labels: please review & merge

#37011 Add fgsv
  recipes/fgsv/build.sh
  recipes/fgsv/fgsv.py
  recipes/fgsv/meta.yaml
Labels: please review & merge

#37018 update falco release and build instructions
  recipes/falco/build.sh
  recipes/falco/meta.yaml
Labels: please review & merge

#37030 Update meta.yaml FlashLFQ new release v 1.2.4
  recipes/flashlfq/meta.yaml
Labels: please review & merge

#37024 Use older protobuf version in DeepBGC
  recipes/deepbgc/meta.yaml
Labels: please review & merge

#36779 Update Snakelines to version 1.1.0
  recipes/snakelines/build.sh
  recipes/snakelines/meta.yaml
Labels: please review & merge

#37033 Update CRISPResso2 dependency
  recipes/crispresso2/meta.yaml
Labels: please review & merge

#36582 add recipe for NextPolish
  recipes/nextpolish/build.sh
  recipes/nextpolish/fix_get_version.patch
  recipes/nextpolish/fix_nextpolish_paths.patch
  recipes/nextpolish/meta.yaml
Labels: please review & merge

#36872 Update HiCUP (dependencies and test)
  recipes/hicup/hicup_reporter.rmd
  recipes/hicup/meta.yaml
  recipes/hicup/run_test.sh
  recipes/hicup/test_dataset1_2.ditag_size_distribution_report.txt
  recipes/hicup/test_dataset1_2.hicup.bam.HiCUP_summary_report_xRCWhUMSZD_16-13-38_08-09-2022.txt
Labels: please review & merge

#37060 Update Snakelines
  recipes/snakelines/meta.yaml
Labels: please review & merge

#37058 Update gotree: Correction of package version in gotree build
  recipes/gotree/build.sh
  recipes/gotree/meta.yaml
Labels: please review & merge

#37057 Add hap-ibd
  recipes/hap-ibd/build.sh
  recipes/hap-ibd/hap-ibd.py
  recipes/hap-ibd/meta.yaml
Labels: please review & merge

#37071 Update augur to 18.0.0
  recipes/augur/meta.yaml
Labels: please review & merge

#37070 add recipe for pHierCC
  recipes/phiercc/fix_distance_tempfile.patch
  recipes/phiercc/fix_hcceval_tempfile.patch
  recipes/phiercc/meta.yaml
Labels: please review & merge

#37076 Update cstag
  recipes/cstag/meta.yaml
Labels: please review & merge

#36992 Add segzoo
  recipes/segzoo/meta.yaml
Labels: please review & merge

#37078 Update seqscreen sha
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#37081 Update TaxonKit to v0.13.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#37083 Update SeqKit to v2.3.1
  recipes/seqkit/meta.yaml
Labels: please review & merge

#37084 Update csvtk to v0.25.0
  recipes/csvtk/meta.yaml
Labels: please review & merge

#37088 Add pango_aliasor with grayskull generated recipe
  recipes/pango_aliasor/meta.yaml
Labels: please review & merge

#37096 remove gramacswrapper to add it to conda-forge
  recipes/gromacswrapper/meta.yaml
Labels: please review & merge

#35704 Update egglib to 3.1.0.
  build-fail-blacklist
  recipes/egglib/build.sh
  recipes/egglib/meta.yaml
Labels: please review & merge

#37093 Update artic to v1.2.3
  recipes/artic/meta.yaml
Labels: please review & merge

#37109 Update phylofisher
  recipes/phylofisher/meta.yaml
Labels: please review & merge

#37101 Add shinyngs
  recipes/r-shinyngs/build.sh
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#37102 Update physiofit to 2.1.0
  recipes/physiofit4galaxy/meta.yaml
Labels: please review & merge

#37054 update ena-webin-cli to 5.0.0
  recipes/ena-webin-cli/ena_webin_cli.py
  recipes/ena-webin-cli/meta.yaml
Labels: please review & merge

#37099 Update btllib to 1.4.8
  recipes/btllib/meta.yaml
Labels: please review & merge

#37112 Update Sketchy
  recipes/sketchy/build.sh
  recipes/sketchy/meta.yaml
Labels: please review & merge

#37108 Remove perl-lib, it has been migrated to conda-forge.
  recipes/perl-lib/0.63/build.sh
  recipes/perl-lib/0.63/meta.yaml
Labels: please review & merge

#37105 Remove perl-text-diff, it has been migrated to conda-forge.
  recipes/perl-text-diff/build.sh
  recipes/perl-text-diff/meta.yaml
Labels: please review & merge

#37098 Remove perl-digest-md5, it has been migrated to conda-forge.
  recipes/perl-digest-md5/build.sh
  recipes/perl-digest-md5/meta.yaml
Labels: please review & merge

#37085 Remove perl-sub-info, it has been migrated to conda-forge.
  recipes/perl-sub-info/build.sh
  recipes/perl-sub-info/meta.yaml
Labels: please review & merge

#37141 Update goldrush to 1.0.1
  recipes/goldrush/meta.yaml
Labels: please review & merge

#37124 Remove perl-extutils-constant, it has been migrated to conda-forge.
  recipes/perl-extutils-constant/build.sh
  recipes/perl-extutils-constant/meta.yaml
Labels: please review & merge

#37122 Remove perl-config-simple, it has been migrated to conda-forge.
  recipes/perl-config-simple/build.sh
  recipes/perl-config-simple/meta.yaml
Labels: please review & merge

#37146 Add lorax v0.3.5
  recipes/lorax/build.sh
  recipes/lorax/meta.yaml
Labels: please review & merge

#37139 Reinstate re-released illumina-interop 1.1.27
  build-fail-blacklist
  recipes/illumina-interop/meta.yaml
Labels: please review & merge, addressed-bulk-skip

#37150 Update emu
  recipes/emu/meta.yaml
Labels: please review & merge

#37154 Add ContamMix
  recipes/contammix/build.sh
  recipes/contammix/meta.yaml
Labels: please review & merge

#37160 Update contammix
  recipes/contammix/meta.yaml
Labels: please review & merge

#37152 Remove perl-io-gzip, it has been migrated to conda-forge.
  recipes/perl-io-gzip/build.sh
  recipes/perl-io-gzip/meta.yaml
Labels: please review & merge

#37148 Remove perl-text-csv, it has been migrated to conda-forge.
  recipes/perl-text-csv/build.sh
  recipes/perl-text-csv/meta.yaml
Labels: please review & merge

#37147 Remove perl-tie-refhash, it has been migrated to conda-forge.
  recipes/perl-tie-refhash/1.39/build.sh
  recipes/perl-tie-refhash/1.39/meta.yaml
Labels: please review & merge

#37116 Remove perl-ostype, it has been migrated to conda-forge.
  recipes/perl-ostype/build.sh
  recipes/perl-ostype/meta.yaml
Labels: please review & merge

#37115 Remove perl-config-tiny, it has been migrated to conda-forge.
  recipes/perl-config-tiny/build.sh
  recipes/perl-config-tiny/meta.yaml
Labels: please review & merge

#37110 Remove perl-number-compare, it has been migrated to conda-forge.
  recipes/perl-number-compare/build.sh
  recipes/perl-number-compare/meta.yaml
Labels: please review & merge

#37162 Reinstate unifrac-binaries on macOS by patching to avoid using mkostemp()
  recipes/unifrac-binaries/meta.yaml
  recipes/unifrac-binaries/mkstemp.patch
Labels: please review & merge, addressed-bulk-skip

#37069 add recipe for EToKi
  recipes/etoki/build.sh
  recipes/etoki/fix_configure_paths.patch
  recipes/etoki/fix_tempfile.patch
  recipes/etoki/meta.yaml
  recipes/etoki/post-link.sh
Labels: WIP, please review & merge

#37168 Update KMCP to v0.9.0
  recipes/kmcp/meta.yaml
Labels: please review & merge

#37169 Remove perl-set-scalar, it has been migrated to conda-forge.
  recipes/perl-set-scalar/build.sh
  recipes/perl-set-scalar/meta.yaml
Labels: please review & merge

#37174 Add parse-vcf
  recipes/parse-vcf/meta.yaml
Labels: please review & merge

#37194 Remove perl-encode, it has been migrated to conda-forge.
  recipes/perl-encode/build.sh
  recipes/perl-encode/meta.yaml
Labels: please review & merge

#37197 Update - fix for failed autobump of spaln to 2.4.13
  recipes/spaln/meta.yaml
Labels: please review & merge

#37210 Remove perl-file-tee, it has been migrated to conda-forge.
  recipes/perl-file-tee/0.07/build.sh
  recipes/perl-file-tee/0.07/meta.yaml
Labels: please review & merge

#37180 Update contammix
  recipes/contammix/meta.yaml
Labels: please review & merge

#36767 Add EzAAI 1.2.2
  recipes/ezaai/build.sh
  recipes/ezaai/meta.yaml
Labels: please review & merge

#37219 Update breseq to 0.37.1
  recipes/breseq/meta.yaml
Labels: please review & merge

#37164 Update smallgenomeutilities to version 0.3.8
  recipes/smallgenomeutilities/0.3.8/meta.yaml
Labels: please review & merge

#37243 Remove perl-xml-sax-base, it has been migrated to conda-forge.
  recipes/perl-xml-sax-base/build.sh
  recipes/perl-xml-sax-base/meta.yaml
Labels: please review & merge

#37240 Remove perl-text-levenshteinxs, it has been migrated to conda-forge.
  recipes/perl-text-levenshteinxs/0.03/build.sh
  recipes/perl-text-levenshteinxs/0.03/meta.yaml
Labels: please review & merge

#37220 Reinstate 3seq: cull unnecessary dependencies and update checksum
  build-fail-blacklist
  recipes/3seq/meta.yaml
Labels: please review & merge, addressed-bulk-skip

#37228 Add package seqchromloader
  recipes/seqchromloader/meta.yaml
Labels: please review & merge

#37175 Add ASTER
  recipes/aster/build.sh
  recipes/aster/meta.yaml
Labels: please review & merge

#37226 Update recipe for new version of MTG-Link v2.4.0
  recipes/mtglink/build.sh
  recipes/mtglink/meta.yaml
Labels: please review & merge
