Repository bioconda/bioconda-recipes, pull requests merged in 2023-11, with the labels that each got.

#43715 Colabfold 1.5.3
  recipes/colabfold/meta.yaml
Labels: please review & merge

#44001 Adds Rmath4 library
  recipes/rmath4/meta.yaml
Labels: please review & merge

#44000 Add pysais library
  recipes/pysais/meta.yaml
Labels: please review & merge

#44011 Add ucsc-chainscore
  recipes/ucsc-chainscore/build.sh
  recipes/ucsc-chainscore/include.patch
  recipes/ucsc-chainscore/meta.yaml
  recipes/ucsc-chainscore/run_test.sh
Labels: please review & merge

#44012 Add ucsc-pslsortacc
  recipes/ucsc-pslsortacc/build.sh
  recipes/ucsc-pslsortacc/include.patch
  recipes/ucsc-pslsortacc/meta.yaml
  recipes/ucsc-pslsortacc/run_test.sh
Labels: please review & merge

#43993 Add ucsc-chaincleaner
  recipes/ucsc-chaincleaner/build.sh
  recipes/ucsc-chaincleaner/include.patch
  recipes/ucsc-chaincleaner/meta.yaml
  recipes/ucsc-chaincleaner/run_test.sh
Labels: please review & merge

#43815 Update dwgsim to 1.1.14
  recipes/dwgsim/meta.yaml
Labels: please review & merge, new version

#43820 Add pspecterlib
  recipes/r-pspecterlib/meta.yaml
Labels: please review & merge

#43791 Update CAFE to 5.1
  recipes/cafe/meta.yaml
Labels: please review & merge

#44004 update syngap recipes
  recipes/syngap/build.sh
  recipes/syngap/meta.yaml
Labels: please review & merge

#43966 Add recipe for orthofisher v1.1.0
  recipes/orthofisher/meta.yaml
Labels: please review & merge

#43982 Add recipe for gfftk v23.9.6
  recipes/gfftk/meta.yaml
Labels: please review & merge

#44008 Add pytrf
  recipes/pytrf/meta.yaml
Labels: please review & merge

#44039 Update ucsc-twobittofa from 447 to 455
  recipes/ucsc-twobittofa/meta.yaml
Labels: please review & merge

#44040 Update ucsc-fatotwobit from 447 to 455
  recipes/ucsc-fatotwobit/meta.yaml
Labels: please review & merge

#44041 Update ucsc-chainsort from 377 to 455
  build-fail-blacklist
  recipes/ucsc-chainsort/include.patch
  recipes/ucsc-chainsort/meta.yaml
Labels: please review & merge

#43730 add mTM-align
  recipes/mtm-align/build.sh
  recipes/mtm-align/meta.yaml
Labels: please review & merge

#44048 Update HTSeq to 2.0.4
  recipes/htseq/meta.yaml
Labels: please review & merge

#44047 Update ms2rescore: Add pyopenms as dependency
  recipes/ms2rescore/meta.yaml
Labels: please review & merge

#44055 Add recipe for gapmm2 v0.2.0
  recipes/gapmm2/meta.yaml
Labels: please review & merge

#44056 Add recipe for buscolite v23.10.26
  recipes/buscolite/meta.yaml
Labels: please review & merge

#44026 update recipe for newest v0.4 version
  recipes/metadmg/meta.yaml
Labels: please review & merge

#44059 Update ucsc-axtchain from 377 to 455
  build-fail-blacklist
  recipes/ucsc-axtchain/include.patch
  recipes/ucsc-axtchain/meta.yaml
Labels: please review & merge

#44069 Update snakeSV recipe
  recipes/snakesv/build.sh
  recipes/snakesv/meta.yaml
Labels: please review & merge

#42756 Add NORDic recipe
  recipes/nordic/LICENSE
  recipes/nordic/build.sh
  recipes/nordic/meta.yaml
Labels: please review & merge

#44064 Update ucsc-chainnet from 377 to 455
  build-fail-blacklist
  recipes/ucsc-chainnet/include.patch
  recipes/ucsc-chainnet/meta.yaml
Labels: please review & merge

#44060 Update ucsc-axttopsl from 377 to 455
  build-fail-blacklist
  recipes/ucsc-axttopsl/include.patch
  recipes/ucsc-axttopsl/meta.yaml
Labels: please review & merge

#44061 Update ucsc-chainantirepeat from 377 to 455
  build-fail-blacklist
  recipes/ucsc-chainantirepeat/include.patch
  recipes/ucsc-chainantirepeat/meta.yaml
Labels: please review & merge

#44062 Update ucsc-chainfilter from 377 to 455
  build-fail-blacklist
  recipes/ucsc-chainfilter/include.patch
  recipes/ucsc-chainfilter/meta.yaml
Labels: please review & merge

#44082 Update eigensoft: fix build for osx-arm64
  recipes/eigensoft/0002-replace-finite.patch
  recipes/eigensoft/0003-remove-wrong-cflag.patch
  recipes/eigensoft/build.sh
  recipes/eigensoft/meta.yaml
Labels: please review & merge

#44088 Update abricate: add missing dep to fix database download issues
  recipes/abricate/meta.yaml
Labels: please review & merge

#44063 Update ucsc-chainmergesort from 377 to 455
  build-fail-blacklist
  recipes/ucsc-chainmergesort/include.patch
  recipes/ucsc-chainmergesort/meta.yaml
Labels: please review & merge

#44028 Add el_gato package to Bioconda
  recipes/el_gato/build.sh
  recipes/el_gato/meta.yaml
Labels: please review & merge

#44092 Update meta.yaml to a new build due to a package update bug
  recipes/cellsnake/meta.yaml
Labels: please review & merge

#44109 Update SnakeSV recipe
  recipes/snakesv/meta.yaml
Labels: please review & merge

#44115 Update ucsc-fasomerecords from 377 to 455
  build-fail-blacklist
  recipes/ucsc-fasomerecords/include.patch
  recipes/ucsc-fasomerecords/meta.yaml
Labels: please review & merge

#41091 bandage_ng: add a real test
  recipes/bandage_ng/build.sh
  recipes/bandage_ng/meta.yaml
Labels: help wanted

#44136 Update dgenies flask version
  recipes/dgenies/meta.yaml
Labels: please review & merge

#44135 vsnp3 version 3.17
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#44127 Update meta.yaml
  recipes/physiofit/meta.yaml
Labels: please review & merge

#44166 Update idemuxcpp to 0.2.0
  recipes/idemuxcpp/build.sh
  recipes/idemuxcpp/meta.yaml
Labels: please review & merge

#44171 Update sequenceTools to 1.5.3.2
  recipes/sequencetools/meta.yaml
Labels: please review & merge

#44164 Fix NaN issue in ColabFold 1.5.3
  recipes/colabfold/fix-jax-04-nan.patch
  recipes/colabfold/meta.yaml
Labels: please review & merge

#44179 Correct plassembler dependencies v1.4.1
  recipes/plassembler/meta.yaml
Labels: please review & merge

#44178 vsnp3 version 3.18
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#44138 Update r-monocle3 to 1.3.1
  recipes/r-monocle3/meta.yaml
Labels: please review & merge

#44185 Update meta.yaml
  recipes/cellsnake/meta.yaml
Labels: please review & merge

#44183 Update BLAST to 2.15.0
  recipes/blast/meta.yaml
Labels: please review & merge

#44177 Update Augur dependencies for 23.1.1
  recipes/augur/meta.yaml
Labels: please review & merge

#44195 Update lima to v2.9.0
  recipes/lima/meta.yaml
Labels: please review & merge

#44161 Update cooltools to 0.6.0
  recipes/cooltools/meta.yaml
Labels: please review & merge

#44199 Add sequali recipe
  recipes/sequali/meta.yaml
Labels: please review & merge

#44065 Update r-saige to version 1.3.1
  recipes/r-saige/meta.yaml
Labels: please review & merge

#44212 Update BLAST: add blastdb integrity check
  recipes/blast/meta.yaml
  recipes/blast/run_test.sh
Labels: please review & merge

#44230 Add annembed v0.1.1
  recipes/annembed/build.sh
  recipes/annembed/meta.yaml
Labels: please review & merge

#44241 Update FastANI
  recipes/fastani/meta.yaml
Labels: please review & merge

#44240 Update megalodon version
  recipes/megalodon/meta.yaml
Labels: please review & merge

#44279 Update Metaphor dependencies
  recipes/metaphor/meta.yaml
Labels: please review & merge

#44306 Update tracy to v0.7.6
  recipes/tracy/meta.yaml
Labels: please review & merge

#44309 Add reneo v0.2.0
  recipes/reneo/meta.yaml
Labels: please review & merge

#44325 Update Ampliconsuite to 1.1.0
  recipes/ampliconsuite/build.sh
  recipes/ampliconsuite/meta.yaml
Labels: please review & merge

#44329 Update SeqKit to v2.6.1
  recipes/seqkit/meta.yaml
Labels: please review & merge

#42930 Rebuild: emerald 1.2.1
  recipes/emerald/functional.patch
  recipes/emerald/meta.yaml
  recipes/emerald/no_filesystem.patch
Labels: please review & merge

#44345 Update MBG to version 1.0.16
  recipes/mbg/meta.yaml
Labels: please review & merge

#44343 Update gsearch v0.1.5
  recipes/gsearch/build_failure.osx-64.yaml
  recipes/gsearch/meta.yaml
Labels: please review & merge

#44215 Add bacpage recipe
  recipes/bacpage/meta.yaml
Labels: please review & merge

#44338 Add Centrifuger
  recipes/centrifuger/build.sh
  recipes/centrifuger/meta.yaml
Labels: please review & merge

#44351 Update to mmquant 1.0.9
  recipes/mmquant/meta.yaml
Labels: please review & merge

#44346 Update GraphAligner to version 1.0.18
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#44366 Add recipe for peaks2utr v1.2.0
  recipes/peaks2utr/LICENSE
  recipes/peaks2utr/meta.yaml
Labels: please review & merge

#44335 Update meta.yaml
  recipes/ultraplex/meta.yaml
Labels: please review & merge

#44382 Update of ngs-bits to version 2023_11
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#44384 Update ganon to 2.0.0
  recipes/ganon/build_failure.linux-64.yaml
  recipes/ganon/conda_build_config.yaml
  recipes/ganon/meta.yaml
Labels: please review & merge

#44360 Update qualimap to v2.3
  recipes/qualimap/meta.yaml
Labels: please review & merge

#44388 Update lima: set binary_relocation: False to fix EL8 segfault
  recipes/lima/meta.yaml
Labels: please review & merge

#44380 Add hpcblast recipe
  recipes/hpcblast/meta.yaml
Labels: please review & merge

#44358 Add BOMS to bioconda.
  recipes/boms/meta.yaml
Labels: please review & merge

#44402 Added run_exports to meta.yaml
  recipes/genomepy/meta.yaml
Labels: please review & merge, update pinning

#44401 Update ribotin to version 1.2
  recipes/ribotin/build.sh
  recipes/ribotin/meta.yaml
Labels: please review & merge

#44406 Update poppunk to v2.6.1
  recipes/poppunk/meta.yaml
Labels: please review & merge

#44405 Added run_exports to meta.yaml
  recipes/gimmemotifs/meta.yaml
Labels: please review & merge, update pinning

#44297 Update Jalview to 2.11.3.0
  recipes/jalview/build.sh
  recipes/jalview/jalview.sh
  recipes/jalview/meta.yaml
Labels: please review & merge

#44381 Update spagrn to v1.0.7
  recipes/spagrn/meta.yaml
Labels: please review & merge

#44430 Update pantools to 4.3.0
  recipes/pantools/meta.yaml
Labels: please review & merge

#44429 Update anansnake to 0.1.0
  recipes/anansnake/meta.yaml
Labels: please review & merge

#44421 Add dodge to bioconda
  recipes/dodge/meta.yaml
Labels: please review & merge

#44417 Update HyPhy to 2.5.57
  recipes/hyphy/meta.yaml
Labels: please review & merge

#44443 Update TaxonKit to v0.15.1
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#44436 add slow5curl
  recipes/slow5curl/build.sh
  recipes/slow5curl/meta.yaml
Labels: please review & merge

#44454 Update the recipe of cstag-cli
  recipes/cstag-cli/meta.yaml
Labels: please review & merge

#44452 Update annembed v0.1.2
  recipes/annembed/meta.yaml
Labels: please review & merge

#44476 update csvtk to v0.29.0
  recipes/csvtk/meta.yaml
Labels: please review & merge

#44483 Update trtools to 5.1.1
  recipes/trtools/meta.yaml
Labels: please review & merge

#44283 Update: multiple python versions for pytrf
  recipes/pytrf/meta.yaml
Labels: please review & merge

#44473 Update earlgrey meta.yaml
  recipes/earlgrey/meta.yaml
Labels: please review & merge

#44528 Fix geNomad dependencies
  recipes/genomad/meta.yaml
Labels: please review & merge
