Repository bioconda/bioconda-recipes, pull requests merged in 2023-02, with the labels that each got.

#39092 SemiBin: update python constraint to ≥3.7
  recipes/semibin/meta.yaml
Labels: please review & merge

#39091 Update pygenomeviz to 0.3.2
  recipes/pygenomeviz/meta.yaml
Labels: please review & merge

#39058 Update pantools to v4.1.1
  recipes/pantools/meta.yaml
Labels: please review & merge

#39109 Update version to 1.1.2
  recipes/msamtools/meta.yaml
Labels: please review & merge

#39085 Add varfish-server-worker 0.2.1
  recipes/varfish-server-worker/build.sh
  recipes/varfish-server-worker/meta.yaml
Labels: please review & merge

#38469 Msmc install v2.1.4
  recipes/msmc2/meta.yaml
Labels: please review & merge

#38804 Update MHCnuggets to 2.4.0
  recipes/mhcnuggets/meta.yaml
Labels: please review & merge

#39129 bump piscem to 0.4.1
  recipes/piscem/meta.yaml
Labels: please review & merge

#38827 [Update] fibertools-rs to include libtorch c++ libraries
  recipes/fibertools-rs/activate.sh
  recipes/fibertools-rs/build.sh
  recipes/fibertools-rs/deactivate.sh
  recipes/fibertools-rs/meta.yaml
Labels: please review & merge

#38728 Add gum recipe
  recipes/gum/00-fix-ext-cmake.patch
  recipes/gum/LICENSE
  recipes/gum/build.sh
  recipes/gum/meta.yaml
Labels: please review & merge

#38766 Add circle-map-cpp
  recipes/circle-map-cpp/build.sh
  recipes/circle-map-cpp/conda_build_config.yaml
  recipes/circle-map-cpp/meta.yaml
Labels: please review & merge

#39063 Add AltaiR Recipe
  recipes/altair-mf/LICENSE
  recipes/altair-mf/build.sh
  recipes/altair-mf/meta.yaml
Labels: please review & merge

#39064 Update DAStk to v1.0.1
  recipes/dastk/meta.yaml
Labels: please review & merge

#39077 update to biscuit v1.2.0
  recipes/biscuit/meta.yaml
Labels: please review & merge

#39086 Update pbiotools
  recipes/pbiotools/meta.yaml
Labels: please review & merge

#39101 Update smafa to 0.6.1
  recipes/smafa/meta.yaml
Labels: please review & merge

#39098 Update TRTools to 5.0.0
  recipes/trtools/meta.yaml
Labels: please review & merge

#39104 Add SaLTy (v1.0.0)
  recipes/salty/meta.yaml
Labels: please review & merge

#39113 updated learnMSA to version 1.1.1
  recipes/learnmsa/meta.yaml
Labels: please review & merge

#39124 Update strobealign to 0.8.0
  recipes/strobealign/build.sh
  recipes/strobealign/meta.yaml
  recipes/strobealign/xxhash.patch
Labels: please review & merge

#39128 Update longstitch to v1.0.4
  recipes/longstitch/meta.yaml
Labels: please review & merge

#39135 Bump shinyngs
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#39139 Update Trim Galore version
  recipes/trim-galore/meta.yaml
Labels: please review & merge

#39152 Update haptools to 0.1.2
  recipes/haptools/meta.yaml
Labels: please review & merge

#39106 new file: dmbiolib/meta.yaml
  recipes/dmbiolib/meta.yaml
Labels: please review & merge

#39149 Update guidescan to 2.1.2
  recipes/guidescan/build.sh
  recipes/guidescan/meta.yaml
Labels: please review & merge

#37237 fix strainGE
  build-fail-blacklist
  recipes/strainge/meta.yaml
Labels: please review & merge, addressed-bulk-skip

#39175 Update scar recipe
  recipes/scar/meta.yaml
Labels: please review & merge

#39173 Update GW meta.yaml -> rebuild v0.5.3
  recipes/gw/meta.yaml
Labels: please review & merge

#39197 Update rgi to 6.0.2
  recipes/rgi/meta.yaml
Labels: please review & merge

#39148 Update recipe - biocondutor - msPurityData - bump to v1.26.0
  recipes/bioconductor-mspuritydata/meta.yaml
Labels: please review & merge

#39169 Update Toil to 5.9.2
  recipes/toil/meta.yaml
  recipes/toil/remove_wdlparse.patch
Labels: please review & merge

#39181 Update: Update urls and clean unnecessary parts of the build
  recipes/fibertools-rs/activate.sh
  recipes/fibertools-rs/build.sh
  recipes/fibertools-rs/deactivate.sh
  recipes/fibertools-rs/meta.yaml
Labels: please review & merge

#39194 Update grimer to 1.1.0
  recipes/grimer/meta.yaml
Labels: please review & merge

#39168 Add package SEM
  recipes/sem/build.sh
  recipes/sem/meta.yaml
  recipes/sem/sem.py
Labels: please review & merge

#39158 Use sqlalchemy <2 in biophi
  recipes/biophi/meta.yaml
Labels: please review & merge

#39182 Barseqcount
  recipes/barseqcount/meta.yaml
  recipes/barseqcount/post-link.sh
  recipes/barseqcount/pre-unlink.sh
Labels: please review & merge

#39205 Update IsoQuant to 3.1.2
  recipes/isoquant/meta.yaml
Labels: please review & merge

#39189 Update recipe to build against r-base 3.6 and 4.0
  recipes/r-dimsum/conda_build_config.yaml
  recipes/r-dimsum/meta.yaml
Labels: please review & merge

#39222 Update auspice to 2.43.0
  recipes/auspice/meta.yaml
Labels: please review & merge

#39246 Build piscem without `-march=native`
  recipes/piscem/meta.yaml
Labels: please review & merge

#39228 Update IsoQuant 3.1.2, fix build
  recipes/isoquant/meta.yaml
Labels: please review & merge

#39209 Update to 1.6.8
  recipes/r-stitch/meta.yaml
Labels: please review & merge

#39254 [UPDATE] BTE to v0.9.0
  recipes/bte/meta.yaml
Labels: please review & merge

#39225 Add recipe for HmnQc
  recipes/hmnqc/meta.yaml
Labels: please review & merge

#39206 Fix mrbayes - libhmsbeagle.so.1
  recipes/mrbayes/meta.yaml
Labels: please review & merge

#39216 update: add tabix to ngsderive dependencies
  recipes/ngsderive/meta.yaml
Labels: please review & merge

#39243 Bump bioconductor-structtoolbox version to 1.10.1
  recipes/bioconductor-structtoolbox/meta.yaml
Labels: please review & merge

#39273 Update meta.yaml
  recipes/eggnog-mapper/meta.yaml
Labels: please review & merge

#39214 Add recipe for SKA 2
  recipes/ska2/meta.yaml
Labels: please review & merge

#39253 Add drtransformer recipe
  recipes/drtransformer/meta.yaml
Labels: please review & merge

#39311 Update to piscem 0.4.3
  recipes/piscem/meta.yaml
Labels: please review & merge

#39268 Add Netsyn v0.1.1
  recipes/netsyn/meta.yaml
Labels: please review & merge

#39297 Update GraphAligner to version 1.0.17b
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#39296 Fix onetbb flexbar issue
  build-fail-blacklist
  recipes/flexbar/meta.yaml
  recipes/flexbar/onetbb.patch
Labels: please review & merge

#39237 new file: dmbiolib/meta.yaml
  recipes/dmbiolib/meta.yaml
Labels: please review & merge

#39298 Update ska2 to v0.1.2
  recipes/ska2/meta.yaml
Labels: please review & merge

#39319 Update subread 2.0.3 build for macOS
  recipes/subread/meta.yaml
Labels: please review & merge

#39330 update mimseq
  recipes/mimseq/meta.yaml
Labels: please review & merge

#39314 Update to ThermoRawFileParser v 1.4.2
  recipes/thermorawfileparser/meta.yaml
Labels: please review & merge

#38769 Added INSurVeyor.
  recipes/insurveyor/build.sh
  recipes/insurveyor/meta.yaml
  recipes/insurveyor/run_test.sh
Labels: please review & merge

#39299 Add AuthentiCT recipe
  recipes/authentict/meta.yaml
Labels: please review & merge

#39361 Add recipe for bactopia subtools
  recipes/bactopia-teton/build.sh
  recipes/bactopia-teton/meta.yaml
  recipes/bactopia-variants/build.sh
  recipes/bactopia-variants/meta.yaml
Labels: please review & merge

#39367 update tbpore to 0.5.0
  recipes/tbpore/meta.yaml
Labels: please review & merge, new version

#39388 rebuild again newer pins
  recipes/gtdbtk/meta.yaml
Labels: automerge

#39393 Update Olivar to 1.1.0
  recipes/olivar/meta.yaml
Labels: please review & merge

#39402 Update ProteomIQon toolchain
  recipes/proteomiqon-alignmentbasedquantstatistics/meta.yaml
  recipes/proteomiqon-joinquantpepionswithproteins/meta.yaml
  recipes/proteomiqon-labeledproteinquantification/meta.yaml
  recipes/proteomiqon-labelfreeproteinquantification/meta.yaml
  recipes/proteomiqon-psmbasedquantification/meta.yaml
Labels: please review & merge

#39442 Update aniclustermap to 1.2.0
  recipes/aniclustermap/meta.yaml
Labels: please review & merge

#39438 Update fiji-max_inscribed_circles
  recipes/fiji-max_inscribed_circles/meta.yaml
  recipes/fiji-max_inscribed_circles/test.groovy
Labels: please review & merge

#39439 Pin biopython<=1.80, sort requirements alphabetically
  recipes/augur/meta.yaml
Labels: please review & merge

#39429 Add hmftools-pave
  recipes/hmftools-pave/build.sh
  recipes/hmftools-pave/meta.yaml
  recipes/hmftools-pave/pave.sh
Labels: please review & merge

#39425 Add hmftools-sv-prep
  recipes/hmftools-sv-prep/SvPrep.sh
  recipes/hmftools-sv-prep/build.sh
  recipes/hmftools-sv-prep/meta.yaml
Labels: please review & merge

#39424 Update hmftools-sage to version 3.2.3
  recipes/hmftools-sage/meta.yaml
Labels: please review & merge

#39436 Update hmftools-purple to 3.7.1
  recipes/hmftools-purple/meta.yaml
Labels: please review & merge

#39441 add metagem bioconda recipe
  recipes/metagem/meta.yaml
Labels: please review & merge

#39454 Bump shinyngs to 1.5.6
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#39448 Update Augur to 21.0.1, pinning BioPython version
  recipes/augur/meta.yaml
Labels: please review & merge

#39433 Update AuthentiCT to include missing dependency
  recipes/authentict/meta.yaml
Labels: please review & merge

#39466 Update CCTK to version 1.0
  recipes/cctk/meta.yaml
Labels: please review & merge

#39423 Add mapAD
  recipes/mapad/build.sh
  recipes/mapad/meta.yaml
Labels: please review & merge

#39473 add recipe for bactopia-py
  recipes/bactopia-py/meta.yaml
Labels: please review & merge

#39444 Add recipe for Phaser
  recipes/phaser/build.sh
  recipes/phaser/meta.yaml
Labels: please review & merge

#39464 Upgrade dbCAN to dbCAN4
  recipes/dbcan/meta.yaml
Labels: automerge

#39463 Update icescreen v1.1.1
  recipes/icescreen/meta.yaml
Labels: please review & merge

#39323 Parent map patch 1
  post-link.sh
  pre-unlink.sh
  recipes/parent-map/meta.yaml
Labels: please review & merge

#39511 Add recipe for nda-tools
  recipes/nda-tools/meta.yaml
Labels: please review & merge

#39503 restrict matchms version
  recipes/riassigner/meta.yaml
Labels: please review & merge

#39495 Update Massiveqc
  recipes/massiveqc/meta.yaml
Labels: please review & merge

#39490 Update hmftools-lilac to 1.4.2
  recipes/hmftools-lilac/meta.yaml
Labels: please review & merge

#39521 Bump up abnumber to 0.3.1
  recipes/abnumber/meta.yaml
Labels: please review & merge

#39477 Update pharokka to v1.2.1
  recipes/pharokka/meta.yaml
Labels: please review & merge

#39489 Update hmftools-linx to 1.22
  recipes/hmftools-linx/meta.yaml
Labels: please review & merge

#39524 Bump paml to 4.10.6
  recipes/paml/meta.yaml
Labels: please review & merge

#39507 Add PAIRADISE recipe
  recipes/r-pairadise/build.sh
  recipes/r-pairadise/meta.yaml
Labels: please review & merge

#39502 Add hmftools-protect
  recipes/hmftools-protect/build.sh
  recipes/hmftools-protect/meta.yaml
  recipes/hmftools-protect/protect.sh
Labels: please review & merge

#39419 Add obonet v 0.2.3
  recipes/obonet/meta.yaml
Labels: please review & merge

#39481 Update meta.yaml
  recipes/mirge3/meta.yaml
Labels: please review & merge

#39378 Update of ngs-bits to version 2023_02
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#39517 Add files via upload
  recipes/parent-map/meta.yaml
  recipes/parent-map/post-link.sh
  recipes/parent-map/pre-unlink.sh
Labels: please review & merge

#39573 bump mitos and mitos2
  recipes/mitos/meta.yaml
  recipes/mitos/mitos1/meta.yaml
Labels: please review & merge

#39581 Add graphmb
  recipes/graphmb/meta.yaml
Labels: please review & merge

#39552 Add hmftools-orange
  recipes/hmftools-orange/build.sh
  recipes/hmftools-orange/meta.yaml
  recipes/hmftools-orange/orange.sh
Labels: please review & merge

#39561 Add hmftools-rose
  recipes/hmftools-rose/build.sh
  recipes/hmftools-rose/meta.yaml
  recipes/hmftools-rose/rose.sh
Labels: please review & merge

#39492 Add hmftools-sigs
  recipes/hmftools-sigs/build.sh
  recipes/hmftools-sigs/meta.yaml
  recipes/hmftools-sigs/sigs.sh
Labels: please review & merge

#39611 update instrain requirements
  recipes/instrain/meta.yaml
Labels: please review & merge

#39601 MITOS: try to pin pillow
  recipes/mitos/meta.yaml
  recipes/mitos/mitos1/meta.yaml
Labels: please review & merge

#39509 Update bioconvert version to 1.0.0.post0
  recipes/bioconvert/meta.yaml
Labels: please review & merge

#39550 bump picard to 3.0
  recipes/picard/meta.yaml
Labels: please review & merge

#39474 Update polystest
  recipes/polystest/meta.yaml
Labels: please review & merge

#39467 Update PPanGGOLiN 1.2.105 recipe
  recipes/ppanggolin/meta.yaml
Labels: please review & merge

#39639 Bump megan
  recipes/megan/meta.yaml
Labels: please review & merge

#39633 update haystac from version 0.4.8 to 0.4.9
  recipes/haystac/meta.yaml
Labels: please review & merge

#39621 add gsearch v0.0.12
  recipes/gsearch/build.sh
  recipes/gsearch/meta.yaml
Labels: please review & merge

#39640 Update MBG to version 1.0.14
  recipes/mbg/meta.yaml
Labels: please review & merge

#39592 Update Traitar to v3
  recipes/traitar/meta.yaml
Labels: please review & merge
