Repository bioconda/bioconda-recipes, pull requests merged in 2023-07, with the labels that each got.

#41776 Add CRBHits
  recipes/r-crbhits/build.sh
  recipes/r-crbhits/meta.yaml
Labels: please review & merge

#41763 Update parasail-python to 1.3.4
  recipes/parasail-python/darwin-libtool-name.patch
  recipes/parasail-python/meta.yaml
Labels: please review & merge

#41786 Update pbfusion recipe for v0.2.2
  recipes/pbfusion/build.sh
  recipes/pbfusion/meta.yaml
Labels: please review & merge

#41685 Add geno2phenoTB
  recipes/geno2phenotb/meta.yaml
Labels: please review & merge

#41617 Remove `scVelo`
  recipes/scvelo/meta.yaml
Labels: please review & merge

#41596 Update MEME to 5.5.3
  recipes/meme/build.sh
  recipes/meme/meta.yaml
Labels: please review & merge

#41588 remove cwltest
  recipes/cwltest/meta.yaml
Labels: please review & merge

#41618 Update sage-proteomics to 0.13.3
  recipes/sage-proteomics/build.sh
  recipes/sage-proteomics/meta.yaml
Labels: please review & merge

#41579 Add skc recipe
  recipes/skc/build.sh
  recipes/skc/meta.yaml
Labels: please review & merge

#41533 Update Toil to v5.10 (fixed)
  recipes/toil/meta.yaml
  recipes/toil/remove_wdlparse.patch
Labels: please review & merge

#41667 Add oligomap software package
  recipes/oligomap/meta.yaml
Labels: please review & merge

#41597 Add recipe for WFA2-lib v2.3.3
  recipes/wfa2-lib/build.sh
  recipes/wfa2-lib/makefile.patch
  recipes/wfa2-lib/meta.yaml
Labels: please review & merge

#41397 Update sra-human-scrubber to 2.1.0
  recipes/sra-human-scrubber/fix_init_db_path.patch
  recipes/sra-human-scrubber/meta.yaml
Labels: please review & merge

#41532 Add HLAfreq recipe
  recipes/hlafreq/meta.yaml
Labels: please review & merge

#41531 Update poseidon-trident to v1.2.0.0
  recipes/poseidon-trident/meta.yaml
Labels: please review & merge

#40700 Add MZmine
  recipes/mzmine/build.patch
  recipes/mzmine/build.sh
  recipes/mzmine/meta.yaml
Labels: please review & merge

#41645 Add Python-MonoVar recipe
  recipes/python-monovar/build.sh
  recipes/python-monovar/meta.yaml
Labels: please review & merge

#41512 Update GMAP to 2023-06-01
  recipes/gmap/build.sh
  recipes/gmap/meta.yaml
Labels: please review & merge

#40664 initial commit of deepfplearn
  recipes/deepfplearn/meta.yaml
Labels: please review & merge

#41451 Update pyspoa to 0.0.9
  recipes/pyspoa/build.sh
  recipes/pyspoa/meta.yaml
Labels: please review & merge

#41766 Update meryl to 1.4
  recipes/meryl/0002-macos-cmath.patch
  recipes/meryl/README.licenses
  recipes/meryl/build.sh
  recipes/meryl/build_failure.osx-64.yaml
  recipes/meryl/meta.yaml
Labels: please review & merge

#41796 Update fasta3 to v38.3.8i
  recipes/fasta3/meta.yaml
Labels: please review & merge

#41060 Update MoDLE to v1.1.0
  recipes/modle/build.sh
  recipes/modle/build_failure.linux-64.yaml
  recipes/modle/build_failure.osx-64.yaml
  recipes/modle/conan_profiles/clang
  recipes/modle/conan_profiles/gcc
  recipes/modle/cross-linux.cmake
  recipes/modle/meta.yaml
  recipes/modle/run_test.sh
Labels: please review & merge

#41821 Scirpy: unpin pandas
  recipes/scirpy/meta.yaml
Labels: please review & merge

#41803 Add Pedesigner
  recipes/pedesigner/meta.yaml
Labels: please review & merge

#41811 Update ngs-bits to version 2023_06
  recipes/ngs-bits/build.sh
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#41840 Update superdsm to 0.1.3
  recipes/superdsm/meta.yaml
Labels: please review & merge

#41862 Update ultra_bioinformatics
  recipes/ultra_bioinformatics/meta.yaml
Labels: please review & merge

#41850 Update pbpigeon to v1.1.0
  recipes/pbpigeon/meta.yaml
Labels: please review & merge

#41538 Update nrpys recipe to build shared python module
  recipes/nrpys/build.sh
  recipes/nrpys/meta.yaml
  recipes/nrpys/patch
Labels: please review & merge

#41863 Add r-wormbase 0.4.1
  recipes/r-wormbase/build.sh
  recipes/r-wormbase/meta.yaml
Labels: please review & merge

#41860 Add Verticall
  recipes/verticall/meta.yaml
Labels: please review & merge

#41867 Add gnparser 1.7.3
  recipes/gnparser/build.sh
  recipes/gnparser/meta.yaml
Labels: please review & merge

#41866 Update btllib to 1.6.2
  recipes/btllib/meta.yaml
Labels: please review & merge

#41868 Update: Remove extra libs from being linked in with gmtk build
  recipes/gmtk/build.sh
  recipes/gmtk/meta.yaml
Labels: please review & merge

#41838 Update searchgui to 4.2.17
  recipes/searchgui/build.sh
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#41837 Update vcflib to 1.0.9
  recipes/vcflib/build.sh
  recipes/vcflib/meta.yaml
  recipes/vcflib/pkg-config.patch
  recipes/vcflib/shared_lib.patch
  recipes/vcflib/shared_ssw.patch
  recipes/vcflib/tabix.patch
Labels: please review & merge

#41875 Update matchms with pandas dependency
  recipes/matchms/meta.yaml
Labels: automerge

#41876 Update svim to 2.0.0
  recipes/svim/meta.yaml
Labels: please review & merge

#41849 Update esviritu to 0.2.3
  recipes/esviritu/meta.yaml
Labels: please review & merge

#41861 Update blast: include *_vdb
  recipes/blast/build.sh
  recipes/blast/meta.yaml
Labels: please review & merge

#41895 Update pxblat recipe and reset build number
  recipes/pxblat/meta.yaml
  recipes/pxblat/meta.yml
Labels: please review & merge

#41880 Remove outdated dependency restrictions for pangolin
  recipes/pangolin/meta.yaml
Labels: please review & merge

#41893 Update spoa to 4.0.8
  recipes/spoa/build.sh
  recipes/spoa/meta.yaml
Labels: please review & merge

#41902 update clair3
  recipes/duet/meta.yaml
Labels: please review & merge

#41908 Updates recipe for superdsm 0.1.3
  recipes/superdsm/meta.yaml
Labels: please review & merge

#41912 Update tobias to 0.15.1
  build-fail-blacklist
  recipes/tobias/build.sh
  recipes/tobias/meta.yaml
Labels: please review & merge

#41925 Add viramp-hub
  recipes/viramp-hub/meta.yaml
Labels: please review & merge

#41841 Update b2btools to 3.0.6
  recipes/b2btools/meta.yaml
  recipes/b2btools/run_test.sh
Labels: please review & merge

#41978 Add hmftools-neo
  recipes/hmftools-neo/build.sh
  recipes/hmftools-neo/meta.yaml
  recipes/hmftools-neo/neo.sh
Labels: please review & merge

#41979 Update hmftools-isofox to v1.6.2
  recipes/hmftools-isofox/meta.yaml
Labels: please review & merge

#41972 Add replidec
  recipes/replidec/meta.yaml
Labels: please review & merge

#41938 Update arcasHLA requirements for scipy version
  recipes/arcas-hla/meta.yaml
Labels: please review & merge

#41976 add vcflib to freebayes run section
  recipes/freebayes/meta.yaml
Labels: WIP

#41905 Update Clair3-Trio to v0.7
  recipes/clair3-trio/build.sh
  recipes/clair3-trio/meta.yaml
Labels: please review & merge

#41960 update ltr_retriever to v2.9.5
  recipes/ltr_retriever/meta.yaml
Labels: please review & merge

#42000 Update version to 1.1.3 build 0
  recipes/msamtools/meta.yaml
Labels: please review & merge

#41962 Update phyml to 3.3.20220408
  recipes/phyml/Makefile.patch
  recipes/phyml/build.sh
  recipes/phyml/meta.yaml
  recipes/phyml/phytime.patch
Labels: please review & merge

#41971 Update ratatosk to 0.9.0
  recipes/ratatosk/build.sh
  recipes/ratatosk/cmakelists.patch
  recipes/ratatosk/meta.yaml
Labels: please review & merge

#41961 Update tabixpp to 1.1.2
  recipes/tabixpp/build.sh
  recipes/tabixpp/meta.yaml
  recipes/tabixpp/shared_lib.patch
Labels: please review & merge

#41953 Graphaligner fixing OSX build
  recipes/graphaligner/build_failure.osx-64.yaml
  recipes/graphaligner/linux_link.patch
  recipes/graphaligner/meta.yaml
Labels: please review & merge

#41956 Update downgraded minimap2, incompatibility issues
  recipes/flair/meta.yaml
Labels: please review & merge

#41931 Add recipe for liftover v1.1.16
  recipes/liftover/meta.yaml
Labels: please review & merge

#41952 add conda recipe for est-sfs
  recipes/est-sfs/build.sh
  recipes/est-sfs/meta.yaml
  recipes/est-sfs/run_test.sh
Labels: please review & merge

#41921 Add peekseq recipe
  recipes/peekseq/build.sh
  recipes/peekseq/meta.yaml
Labels: please review & merge

#41832 Update itsxpress to 2.0.0
  recipes/itsxpress/meta.yaml
Labels: please review & merge

#41825 Add kmtricks v1.4.0
  recipes/kmtricks/build.sh
  recipes/kmtricks/conda_build_config.yaml
  recipes/kmtricks/meta.yaml
Labels: please review & merge

#41864 Add conipher
  recipes/conipher/build.sh
  recipes/conipher/meta.yaml
Labels: please review & merge

#42009 Update KMCP to v0.9.3
  recipes/kmcp/meta.yaml
Labels: please review & merge

#42008 Update SeqKit to v2.5.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#42038 Update MEDICC2 to version 1.0.2
  recipes/medicc2/meta.yaml
Labels: please review & merge

#42054 update clair3 to v1.0.4
  recipes/clair3/meta.yaml
Labels: please review & merge

#42035 Add gut microbiome wellness index 2 :hankey:
  recipes/gmwi2/meta.yaml
Labels: please review & merge

#41894 Update celltypist: fix numpy requirement
  recipes/celltypist/meta.yaml
Labels: please review & merge

#42046 Update OpenMS recipies for 3.0.0 release
  recipes/openms-meta/meta.yaml
  recipes/pyopenms/pyopenms_cmakelist.patch
  recipes/pyopenms/pyopenms_cmakelist2.patch
Labels: please review & merge

#42088 Update pyopenms to 3.0.0
  recipes/pyopenms/meta.yaml
Labels: please review & merge

#42111 Update macs2 to 2.2.9.1
  recipes/macs2/build_failure.linux-64.yaml
  recipes/macs2/build_failure.osx-64.yaml
  recipes/macs2/meta.yaml
Labels: please review & merge

#42109 Update GMAP to 2023-07-20
  recipes/gmap/build.sh
  recipes/gmap/meta.yaml
Labels: please review & merge

#42108 Update bioconvert to 1.1.1
  recipes/bioconvert/COPYING
  recipes/bioconvert/meta.yaml
Labels: please review & merge

#42101 Update GMWI2 to 1.4
  recipes/gmwi2/meta.yaml
Labels: please review & merge

#42110 Update table2asn to 2023-07-13
  recipes/table2asn/build.sh
  recipes/table2asn/meta.yaml
Labels: please review & merge

#42128 Update planemo to 0.75.9
  recipes/planemo/meta.yaml
Labels: please review & merge

#42084 Add r-metadig
  recipes/r-metadig/build.sh
  recipes/r-metadig/meta.yaml
Labels: please review & merge

#42057 Update ViennaRNA to v2.6.3
  recipes/viennarna/build.sh
  recipes/viennarna/meta.yaml
Labels: please review & merge

#42044 Update polystest to 3.2.4
  recipes/polystest/meta.yaml
Labels: please review & merge

#42042 Update oakvar to 2.9.34
  recipes/oakvar/meta.yaml
Labels: please review & merge

#42050 update phylofisher
  recipes/phylofisher/meta.yaml
Labels: please review & merge

#42073 Add recipe for pyeasyfuse
  recipes/pyeasyfuse/meta.yml
Labels: please review & merge

#42040 Add recipe referee
  recipes/referee/build.sh
  recipes/referee/meta.yaml
Labels: please review & merge

#42142 Fix bioconductor-preprocesscore again after bulk update
  recipes/bioconductor-preprocesscore/build.sh
  recipes/bioconductor-preprocesscore/meta.yaml
Labels: please review & merge

#42147 Update snakemake Python dependency
  recipes/snakemake/meta.yaml
Labels: please review & merge

#42158 Update graphbin to v1.7.1
  recipes/graphbin/meta.yaml
Labels: please review & merge

#42141 Remove mamba from Snakemake deps
  recipes/snakemake/meta.yaml
Labels: please review & merge

#42062 Update Snippy - restrict versions of snpeff and vcflib
  recipes/snippy/meta.yaml
Labels: please review & merge

#42188 Update IsoQuant to 3.3.1
  recipes/isoquant/meta.yaml
Labels: please review & merge

#42024 Update evofr to fix dependencies for v0.1.20
  recipes/evofr/meta.yaml
Labels: please review & merge

#42179 Galah - fix versions as not compatible with dashing >0.4.0
  recipes/galah/meta.yaml
Labels: please review & merge

#42060 Update make_prg to 0.5.0
  recipes/make_prg/meta.yaml
  recipes/make_prg/poetry.patch
Labels: please review & merge

#42218 Update beav: version 0.4.5
  recipes/beav/build.sh
  recipes/beav/meta.yaml
Labels: please review & merge

#42225 Update bx-python to 0.10.0
  recipes/bx-python/meta.yaml
Labels: please review & merge

#42219 Update pbfusion to v0.3.0
  recipes/pbfusion/meta.yaml
Labels: please review & merge

#42217 Add MARTi 0.9.14
  recipes/marti/build.sh
  recipes/marti/meta.yaml
Labels: please review & merge

#42205 Add ORFanage
  recipes/orfanage/build.sh
  recipes/orfanage/meta.yaml
Labels: please review & merge

#42131 Update mob_suite to 3.1.5
  recipes/mob_suite/meta.yaml
  recipes/mob_suite/setup.py.patch
Labels: please review & merge

#42055 Updated bayescode to v1.2.2
  recipes/bayescode/build.sh
  recipes/bayescode/meta.yaml
Labels: please review & merge

#42229 Update GMWI2 to 1.5
  recipes/gmwi2/meta.yaml
Labels: please review & merge

#42207 Add recipe for ribotin
  recipes/ribotin/build.sh
  recipes/ribotin/makefile.patch
  recipes/ribotin/meta.yaml
Labels: please review & merge

#42243 Update pasa to 2.5.3
  recipes/pasa/build.sh
  recipes/pasa/meta.yaml
Labels: please review & merge

#42224 Update pxblat to 0.3.0
  recipes/pxblat/build_failure.linux-64.yaml
  recipes/pxblat/build_failure.osx-64.yaml
  recipes/pxblat/meta.yaml
Labels: please review & merge

#42238 Update Guidescan to v2.1.5
  recipes/guidescan/meta.yaml
Labels: please review & merge

#42200 Update: snakemake, BugFix dependencies
  recipes/snakemake/meta.yaml
Labels: please review & merge

#42156 Add skDER to bioconda
  recipes/skder/build.sh
  recipes/skder/meta.yaml
Labels: please review & merge

#42227 Update toil to 5.12.0
  recipes/toil/build.sh
  recipes/toil/meta.yaml
  recipes/toil/remove_wdlparse.patch
Labels: please review & merge

#42242 Update pyeasyfuse recipe and reset build number
  recipes/pyeasyfuse/meta.yaml
  recipes/pyeasyfuse/meta.yml
Labels: please review & merge

#41813 Add rsv-typer v0.1
  recipes/rsv-typer/meta.yaml
Labels: please review & merge

#42271 Update Augur to 22.2.0
  recipes/augur/meta.yaml
Labels: please review & merge
