Repository bioconda/bioconda-recipes, pull requests merged in 2023-08, with the labels that each got.

#42275 Update recipe: + bump patch version, ∆ change deps
  recipes/plannotate/build.sh
  recipes/plannotate/meta.yaml
  recipes/plannotate/patch
Labels: please review & merge

#42281 Bump StructToolbox to v1.12.2 and add missing dependencies
  recipes/bioconductor-structtoolbox/meta.yaml
Labels: please review & merge

#42293 Update ncbi-datasets-pylib to 15.11.0
  recipes/ncbi-datasets-pylib/meta.yaml
Labels: please review & merge

#42278 Update savana to 1.0.0 - autobump fix
  recipes/savana/meta.yaml
Labels: please review & merge

#42294 Add phynteny v0.1.11
  recipes/phynteny/meta.yaml
Labels: please review & merge

#42307 Update smallgenomeutilities to 0.4.0
  recipes/smallgenomeutilities/meta.yaml
Labels: please review & merge, new version

#42252 Update rmblast recipe to build on macOS
  recipes/rmblast/build.sh
  recipes/rmblast/isb-2.14.0+-rmblast.patch
  recipes/rmblast/meta.yaml
Labels: please review & merge

#42308 update genome_updater
  recipes/genome_updater/meta.yaml
Labels: update build number

#42309 Update ribotin to v1.1
  recipes/ribotin/meta.yaml
Labels: please review & merge

#42312 Update dicey 0.2.6
  recipes/dicey/meta.yaml
Labels: please review & merge

#42321 Update recipe for Genomedata 1.7.0
  recipes/genomedata/meta.yaml
Labels: please review & merge

#42310 Add metasnek v0.0.5
  recipes/metasnek/meta.yaml
Labels: please review & merge

#42324 Add snaketool-utils v0.0.3
  recipes/snaketool-utils/meta.yaml
Labels: please review & merge

#42325 Add condiga v0.2.0
  recipes/condiga/meta.yaml
Labels: please review & merge

#42330 bump shinyngs to 1.8.1
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#42333 Update dsh-bio to 2.2.2
  recipes/dsh-bio/meta.yaml
Labels: please review & merge, new version

#42345 Update version and library dependencies
  recipes/abismal/meta.yaml
Labels: please review & merge

#41948 Add perl-uri-nested
  recipes/perl-uri-nested/build.sh
  recipes/perl-uri-nested/meta.yaml
Labels: please review & merge

#42350 Update easypqp to 0.1.39
  recipes/easypqp/meta.yaml
Labels: please review & merge

#42352 Update iqtree to 2.2.2.9
  recipes/iqtree/build.sh
  recipes/iqtree/meta.yaml
Labels: please review & merge

#42366 Update midsv
  recipes/midsv/meta.yaml
Labels: please review & merge

#42011 Add perl-json-validator
  recipes/perl-json-validator/build.sh
  recipes/perl-json-validator/meta.yaml
Labels: please review & merge

#42365 Update savana to 1.0.3 - autobump dependency fix
  recipes/savana/meta.yaml
Labels: please review & merge

#42377 Update skder meta.yaml to include wget in run dependencies
  recipes/skder/meta.yaml
Labels: please review & merge

#41947 Add perl-uri-db
  recipes/perl-uri-db/build.sh
  recipes/perl-uri-db/meta.yaml
Labels: please review & merge

#41942 Add perl-sql-abstract
  recipes/perl-sql-abstract/build.sh
  recipes/perl-sql-abstract/meta.yaml
Labels: please review & merge, automerge

#41943 Add perl-mojo-sqlite
  recipes/perl-mojo-sqlite/build.sh
  recipes/perl-mojo-sqlite/meta.yaml
Labels: please review & merge

#41944 Add perl-mojo-pg
  recipes/perl-mojo-pg/build.sh
  recipes/perl-mojo-pg/meta.yaml
Labels: please review & merge

#41946 Add perl-minion
  recipes/perl-minion/build.sh
  recipes/perl-minion/meta.yaml
Labels: please review & merge

#42187 Concoct: fix sklearn version
  recipes/concoct/meta.yaml
Labels: please review & merge

#42398 Update SeqKit to v2.5.1
  recipes/seqkit/meta.yaml
Labels: please review & merge

#42397 Update pyspoa to 0.0.10
  recipes/pyspoa/build.sh
  recipes/pyspoa/meta.yaml
Labels: please review & merge

#42415 Update dnmtools version
  recipes/dnmtools/meta.yaml
Labels: please review & merge

#42403 Update conipher
  recipes/conipher/meta.yaml
Labels: please review & merge

#42026 Update VirSorter2 v2.2.4 to fix dependency issue
  recipes/virsorter/meta.yaml
Labels: please review & merge

#42434 Update matchms to 0.21.2
  recipes/matchms/meta.yaml
Labels: please review & merge

#42416 Update ufcg to 1.0.5
  recipes/ufcg/build.sh
  recipes/ufcg/meta.yaml
Labels: please review & merge

#42433 Update mimseq to 1.3.6
  recipes/mimseq/meta.yaml
Labels: please review & merge

#42326 Update recipe for cogent3 v2023.7.18a1
  recipes/cogent3/meta.yaml
Labels: please review & merge

#42439 Update trackplot to 0.3.2 and add flask in requirements
  recipes/trackplot/meta.yaml
Labels: please review & merge

#42279 Add recipe for hictk
  recipes/hictk/build.sh
  recipes/hictk/conan_profiles/apple-clang
  recipes/hictk/conan_profiles/gcc
  recipes/hictk/conanfile.txt.patch
  recipes/hictk/cross-linux.cmake
  recipes/hictk/meta.yaml
  recipes/hictk/run_test.sh
Labels: please review & merge

#42425 Add cycle_finder
  recipes/cycle_finder/build.sh
  recipes/cycle_finder/meta.yaml
Labels: please review & merge

#42466 Update iqtree to 2.2.3
  recipes/iqtree/meta.yaml
Labels: please review & merge

#42399 Add new recipe Inverted Repeats Finder (IRF)
  recipes/irf/build.sh
  recipes/irf/meta.yaml
Labels: please review & merge

#42486 Update rsv-typer to 0.2.0
  recipes/rsv-typer/meta.yaml
Labels: please review & merge

#42469 Update sirius to latest version
  recipes/sirius-csifingerid/Kaempferol.ms
  recipes/sirius-csifingerid/build.sh
  recipes/sirius-csifingerid/meta.yaml
  recipes/sirius-csifingerid/post-link.sh
  recipes/sirius-csifingerid/run_test.sh
  recipes/sirius-csifingerid/sirius.patch
Labels: please review & merge

#42459 Add r-eggnog 0.2.2
  recipes/r-eggnog/build.sh
  recipes/r-eggnog/meta.yaml
Labels: please review & merge

#41997 Update r-saige to 1.2.0
  recipes/r-saige/meta.yaml
Labels: please review & merge

#42358 add sdeper v1.0.0
  recipes/sdeper/LICENSE
  recipes/sdeper/meta.yaml
Labels: please review & merge

#42490 Update csvtk to v0.27.0
  recipes/csvtk/meta.yaml
Labels: please review & merge

#42495 Update r-stitch
  recipes/r-stitch/conda_build_config.yaml
  recipes/r-stitch/meta.yaml
Labels: please review & merge

#42507 Update Metamobilepicker to version 0.7.3
  recipes/metamobilepicker/meta.yaml
Labels: please review & merge

#42471 Add ArcSV
  recipes/arcsv/build.sh
  recipes/arcsv/license.txt
  recipes/arcsv/meta.yaml
Labels: please review & merge

#42511 Add sativa
  recipes/sativa/build.sh
  recipes/sativa/meta.yaml
Labels: please review & merge

#42502 Update piper to 0.13.2
  recipes/piper/meta.yaml
Labels: please review & merge

#42503 Update spaln to 2.4.13g
  recipes/spaln/meta.yaml
Labels: please review & merge

#42522 Update csvtk to v0.27.1
  recipes/csvtk/meta.yaml
Labels: please review & merge

#42524 Update Jalview to 2.11.2.7
  recipes/jalview/meta.yaml
Labels: please review & merge

#42551 Update dnaapler to v0.3.0
  recipes/dnaapler/meta.yaml
Labels: please review & merge

#42556 Update perl dependencies for Captus
  recipes/captus/meta.yaml
Labels: please review & merge

#42549 Update TaxonKit to v0.15.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#42569 Update pbfusion to v0.3.1
  recipes/pbfusion/meta.yaml
Labels: please review & merge

#42536 Add xengsort
  recipes/xengsort/meta.yaml
Labels: please review & merge

#42362 Add hictkpy
  recipes/hictkpy/build.sh
  recipes/hictkpy/conan_profiles/apple-clang
  recipes/hictkpy/conan_profiles/gcc
  recipes/hictkpy/conanfile.txt.patch
  recipes/hictkpy/cross-linux.cmake
  recipes/hictkpy/meta.yaml
  recipes/hictkpy/run_test.sh
Labels: please review & merge

#42577 Update csvtk to v0.27.2
  recipes/csvtk/meta.yaml
Labels: please review & merge

#42034 Add recipe for umi-transfer
  recipes/umi-transfer/build.sh
  recipes/umi-transfer/meta.yaml
Labels: please review & merge

#42483 Add TaDReP
  recipes/tadrep/meta.yaml
Labels: please review & merge

#42545 Add `r-pathfindr` recipe
  recipes/r-pathfindr/build.sh
  recipes/r-pathfindr/meta.yaml
Labels: please review & merge

#42555 Add binny
  recipes/binny/meta.yaml
Labels: please review & merge

#42616 Update pxblat to 0.3.1
  recipes/pxblat/meta.yaml
Labels: please review & merge

#42589 Update specific MEGAHIT build for macOS
  recipes/captus/meta.yaml
Labels: please review & merge

#42598 Update pyabpoa to 1.4.1
  recipes/pyabpoa/build_failure.linux-64.yaml
  recipes/pyabpoa/meta.yaml
Labels: please review & merge

#42607 Update dependencies for learnMSA v1.3.0
  recipes/learnmsa/meta.yaml
Labels: please review & merge

#42613 Update unifrac-binaries to 1.4
  recipes/unifrac-binaries/meta.yaml
Labels: please review & merge

#42568 Update Beav to version 0.5.1
  recipes/beav/build.sh
  recipes/beav/meta.yaml
Labels: please review & merge

#42620 Update mtbseq to v.1.1.0
  recipes/mtbseq/meta.yaml
Labels: please review & merge

#42636 Update ganon to 1.8.0
  recipes/ganon/meta.yaml
Labels: please review & merge

#42632 Update SACCHARIS to 2.0.0.dev19
  recipes/saccharis/meta.yaml
Labels: please review & merge

#42515 Add crispector2 2.0.0
  recipes/crispector2/meta.yaml
Labels: please review & merge

#42625 Update recipe syntax for a specific build of MEGAHIT in macOS
  recipes/captus/meta.yaml
Labels: please review & merge

#42676 Update blast to 2.14.1
  recipes/blast/build.sh
  recipes/blast/meta.yaml
Labels: please review & merge

#42679 Update ntedit to 1.4.3
  recipes/ntedit/meta.yaml
Labels: please review & merge

#42687 Update pygenomeviz to 0.4.2
  recipes/pygenomeviz/meta.yaml
Labels: please review & merge

#42685 Update cstag
  recipes/cstag/meta.yaml
Labels: please review & merge

#42668 Add RIblast
  recipes/riblast/meta.yaml
Labels: please review & merge

#42644 Add READ
  recipes/kinship-read/build.sh
  recipes/kinship-read/meta.yaml
Labels: please review & merge

#42626 Update MetaCerberus
  recipes/metacerberus/meta.yaml
Labels: please review & merge

#42619 Update pyrodigal recipe to build on separate python versions
  recipes/pyrodigal/meta.yaml
Labels: please review & merge

#42618 Update bioconductor-epialleler to 1.8.1
  recipes/bioconductor-epialleler/build.sh
  recipes/bioconductor-epialleler/build_failure.linux-64.yaml
  recipes/bioconductor-epialleler/meta.yaml
  recipes/bioconductor-epialleler/patch
Labels: please review & merge

#42574 update lrtk1.6 to 1.7
  recipes/lrtk/meta.yaml
Labels: please review & merge

#42477 Add Binette v0.1.6
  recipes/binette/meta.yaml
Labels: please review & merge

#42617 Add DAJIN2
  recipes/dajin2/meta.yaml
Labels: please review & merge

#42600 Add DNAMarkMaker
  recipes/dnamarkmaker/LICENSE.txt
  recipes/dnamarkmaker/build.sh
  recipes/dnamarkmaker/meta.yaml
Labels: please review & merge

#42597 Add recipe for HapPy-python v0.2.1rc0
  recipes/happy-python/LICENSE
  recipes/happy-python/meta.yaml
Labels: please review & merge

#42144 Update ngscheckmate
  build-fail-blacklist
  recipes/ngscheckmate/build.sh
  recipes/ngscheckmate/meta.yaml
Labels: please review & merge

#41810 Update geno2phenotb to 1.0.1
  recipes/geno2phenotb/meta.yaml
Labels: please review & merge

#42601 Add ms-entropy recipe
  recipes/ms-entropy/meta.yaml
Labels: please review & merge

#42051 Add sylph
  recipes/sylph/build.sh
  recipes/sylph/meta.yaml
Labels: please review & merge

#41728 evidencemodeller: symlink all required code into $PREFIX/bin
  recipes/evidencemodeler/build.sh
  recipes/evidencemodeler/meta.yaml
Labels: please review & merge

#42693 Update pharokka to v1.4.0
  recipes/pharokka/build.sh
  recipes/pharokka/meta.yaml
Labels: please review & merge

#42734 Update Ampliconsuite
  recipes/ampliconsuite/meta.yaml
Labels: please review & merge

#42720 add rbpbench meta yaml
  recipes/rbpbench/meta.yaml
Labels: please review & merge

#42750 update dnaapler to v0.3.1
  recipes/dnaapler/meta.yaml
Labels: please review & merge

#42721 Update decoupler (add seaborn as missing dep.)
  recipes/decoupler/meta.yaml
Labels: please review & merge

#42732 Update SACCHARIS
  recipes/saccharis/meta.yaml
Labels: please review & merge

#42705 Update mimseq gmap dependency
  recipes/mimseq/meta.yaml
Labels: please review & merge

#42707 Add noah-cli
  recipes/noah-cli/meta.yaml
Labels: please review & merge
