Repository bioconda/bioconda-recipes, pull requests merged in 2023-10, with the labels that each got.

#43322 Add ViralConsensus v0.0.4
  recipes/viral_consensus/build.sh
  recipes/viral_consensus/meta.yaml
Labels: please review & merge

#43373 Update cstag
  recipes/cstag/meta.yaml
Labels: please review & merge

#43369 Add ViralMSA v1.1.35
  recipes/viralmsa/build.sh
  recipes/viralmsa/meta.yaml
Labels: please review & merge

#43396 update ice-cream recipe
  recipes/ice-cream/build.sh
  recipes/ice-cream/meta.yaml
Labels: please review & merge

#43372 Update peptide-shaker to 3.0.0
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
Labels: please review & merge

#43384 :hankey: add GMWI2 package
  recipes/gmwi2/meta.yaml
Labels: please review & merge

#43383 Add noise2read recipe
  recipes/noise2read/meta.yaml
Labels: please review & merge

#43363 Made change to openpyxl version requirement
  recipes/physiofit/meta.yaml
Labels: please review & merge

#43364 Update dsh-bio to 2.3
  recipes/dsh-bio/meta.yaml
Labels: please review & merge, new version

#43355 Update hictk to v0.0.3
  recipes/hictk/build.sh
  recipes/hictk/conanfile.txt.patch
  recipes/hictk/meta.yaml
Labels: please review & merge

#43310 Update srnaminer to v1.1.1
  recipes/srnaminer/meta.yaml
Labels: help wanted, please review & merge, licence_problem

#43395 Update recipe for new version of SVJedi-graph v1.2.1
  recipes/svjedi-graph/meta.yaml
Labels: please review & merge

#43308 Add cospar
  recipes/cospar/meta.yaml
Labels: please review & merge

#43338 Add pbsim3, a simulator for PacBio and Oxford Nanopore long reads
  recipes/pbsim3/build.sh
  recipes/pbsim3/meta.yaml
Labels: please review & merge

#43474 Update to two months ago's bcftools 1.18 release
  recipes/bcftools/meta.yaml
Labels: please review & merge

#43275 Add initial commit for amplisim
  recipes/amplisim/build.sh
  recipes/amplisim/meta.yaml
  recipes/amplisim/run_test.sh
Labels: please review & merge

#43460 Add sharg, the argument parser for bio-c++ tools from the seqan3 library
  recipes/sharg/build.sh
  recipes/sharg/meta.yaml
  recipes/sharg/patch
  recipes/sharg/run_test.sh
Labels: please review & merge

#43414 Add gogstools
  recipes/gogstools/meta.yaml
Labels: please review & merge

#43489 Update pixelator to 0.14.0
  recipes/pixelator/meta.yaml
Labels: please review & merge

#43482 new tandem-genotypes
  recipes/tandem-genotypes/meta.yaml
Labels: please review & merge

#43476 Rebuild samtools using an up-to-date htslib
  recipes/samtools/meta.yaml
Labels: please review & merge

#43501 Update searchgui to 4.3.1
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#43499 Update peptide-shaker to 3.0.1
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
Labels: please review & merge

#43511 Add khipu metabolomics
  khipu-metabolomics/meta.yaml
Labels: please review & merge

#43295 Add recipe for erah
  recipes/r-erah/meta.yaml
Labels: please review & merge

#43486 added cascade-config
  recipes/cascade-config/meta.yaml
Labels: help wanted, please review & merge

#43537 Update fgsv recipe to 0.1.0.
  recipes/fgsv/meta.yaml
Labels: please review & merge

#43510 Add asari prerequisites metdatamodel, mass2chem, jms-metabolite-services
  recipes/jms-metabolite-services/meta.yaml
  recipes/mass2chem/meta.yaml
  recipes/metdatamodel/meta.yaml
Labels: please review & merge

#43492 Update beagle to 5.4
  recipes/beagle/build.sh
  recipes/beagle/gpl_license
  recipes/beagle/meta.yaml
Labels: please review & merge

#43532 biocantor 1.1.0
  recipes/biocantor/meta.yaml
Labels: please review & merge

#43546 dimet update to 0.1.4: add six library
  recipes/dimet/meta.yaml
Labels: please review & merge

#43502 Update GMAP to 2023-10-01
  recipes/gmap/meta.yaml
Labels: please review & merge

#43418 Add deepdirect recipe
  recipes/deepdirect/meta.yaml
Labels: please review & merge

#43479 add pneumo-typer recipes
  recipes/pneumo-typer/build.sh
  recipes/pneumo-typer/meta.yaml
Labels: autobump, please review & merge, new version

#43391 Add assemblycomparator2
  recipes/assemblycomparator2/build.sh
  recipes/assemblycomparator2/meta.yaml
Labels: please review & merge

#43550 Update freebayes to 1.3.7
  recipes/freebayes/0001-make-meson-build-conda-friendly.patch
  recipes/freebayes/0002-fix-intervaltree-include-path.patch
  recipes/freebayes/LICENSE
  recipes/freebayes/build.sh
  recipes/freebayes/meson.patch
  recipes/freebayes/meta.yaml
  recipes/freebayes/qcfail.diff
Labels: please review & merge

#43553 Add new tool kosudoku
  recipes/kosudoku/LICENSE.md
  recipes/kosudoku/build.sh
  recipes/kosudoku/meta.yaml
Labels: please review & merge

#43562 Add recipe for Koverage 0.1.6
  recipes/koverage/meta.yaml
Labels: please review & merge

#43567 Add recipe for Trimnami version 0.1.1
  recipes/trimnami/meta.yaml
Labels: please review & merge

#43569 moved khipu-metabolomics into recipes folder
  recipes/khipu-metabolomics/meta.yaml
Labels: please review & merge

#43359 Add phytest 1.4.0
  recipes/phytest/meta.yaml
Labels: please review & merge

#43452 Enable macOS builds for AnchorWave
  recipes/anchorwave/build.sh
  recipes/anchorwave/meta.yaml
  recipes/anchorwave/patches/01-macOS-x86-build.patch
Labels: please review & merge

#43583 Update rmblast to 2.14.1
  recipes/rmblast/isb-2.14.1+-rmblast.patch
  recipes/rmblast/meta.yaml
Labels: please review & merge

#43545 Update dev version ms2pip
  recipes/ms2pip/meta.yaml
Labels: help wanted, please review & merge, new version

#43354 Add metaMDBG v0.3
  recipes/metamdbg/build.sh
  recipes/metamdbg/meta.yaml
Labels: please review & merge

#43340 Add Seqstr
  recipes/seqstr/meta.yaml
Labels: please review & merge

#43604 Add pypolca 0.1.1
  recipes/pypolca/meta.yaml
Labels: please review & merge

#43571 Update t-coffee and merge t_coffee
  recipes/t-coffee/meta.yaml
  recipes/t_coffee
  recipes/t_coffee/build.sh
  recipes/t_coffee/meta.yaml
  recipes/t_coffee/t_coffee/__init__.py
  recipes/t_coffee/t_coffee/__main__.py
  recipes/t_coffee/t_coffee/config.py
Labels: please review & merge

#43605 Update GMAP to 2023-10-10
  recipes/gmap/meta.yaml
Labels: please review & merge

#43601 Add Tadlib
  recipes/tadlib/meta.yaml
Labels: please review & merge

#43607 customtkinter dependency of ms2rescore
  recipes/customtkinter/meta.yaml
Labels: please review & merge

#43594 Add scRNAsim-toolz
  recipes/scrnasim-toolz/meta.yaml
Labels: please review & merge

#43584 Add Neoloopfinder
  recipes/neoloop/meta.yaml
Labels: please review & merge

#43385 Add submission_excel2xml
  recipes/submission-excel2xml/build.sh
  recipes/submission-excel2xml/meta.yaml
  recipes/submission-excel2xml/patch
Labels: please review & merge

#43608 Vvv2 display 0.1.10
  recipes/vvv2_display/meta.yaml
Labels: please review & merge

#43646 Update chewBBACA recipe.
  recipes/chewbbaca/meta.yaml
Labels: please review & merge

#43593 Add recipe for aspera-cli
  recipes/aspera-cli/build.sh
  recipes/aspera-cli/meta.yaml
Labels: please review & merge

#43556 add pneumo-typer recipes
  recipes/pneumo-typer/build.sh
  recipes/pneumo-typer/meta.yaml
Labels: autobump, please review & merge, new version, update build number

#43339 Update mercat2
  recipes/mercat2/meta.yaml
Labels: please review & merge

#43487 added ms2rescore tool
  recipes/ms2rescore/meta.yaml
Labels: please review & merge

#43325 add GDmicro recipes
  recipes/gdmicro/meta.yaml
Labels: please review & merge

#43350 Add vcfsim
  recipes/vcfsim/meta.yaml
Labels: please review & merge

#43677 Add recipe for hybracter v0.1.2
  recipes/hybracter/meta.yaml
Labels: please review & merge

#43638 Add Rabies 0.5.1
  recipes/rabies/meta.yaml
Labels: please review & merge

#43587 Add orthoflow
  recipes/orthoflow/meta.yaml
Labels: please review & merge

#43696 Add recipe for assembly finder
  recipes/assembly_finder/meta.yaml
Labels: please review & merge

#43702 Update rmats2sashimiplot to v3.0.0
  recipes/rmats2sashimiplot/build_failure.linux-64.yaml
  recipes/rmats2sashimiplot/build_failure.osx-64.yaml
  recipes/rmats2sashimiplot/meta.yaml
Labels: please review & merge

#43679 add pneumo-typer recipes
  recipes/pneumo-typer/meta.yaml
Labels: autobump, please review & merge, new version, automerge

#43701 Update SnpEff
  recipes/snpeff/meta.yaml
Labels: please review & merge

#43660 bump shinyngs
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#43723 bump stacks
  recipes/stacks/limits.patch
  recipes/stacks/meta.yaml
Labels: please review & merge

#43727 Update zdb to v1.2.1
  recipes/zdb/build.sh
  recipes/zdb/meta.yaml
Labels: please review & merge

#43713 update deepdirect to 0.2.5
  recipes/deepdirect/meta.yaml
Labels: please review & merge

#43292 Add redundans
  recipes/redundans/build.sh
  recipes/redundans/meta.yaml
Labels: please review & merge

#43788 Update assembly_finder recipe
  recipes/assembly_finder/meta.yaml
Labels: please review & merge

#43774 Update OpenMS to 3.1.0
  recipes/openms-meta/build.sh
  recipes/openms-meta/meta.yaml
Labels: please review & merge

#43288 Update post-link.sh script for RepeatMasker
  recipes/repeatmasker/meta.yaml
  recipes/repeatmasker/post-link.sh
Labels: please review & merge

#43800 Add auriclass
  recipes/auriclass/meta.yaml
Labels: please review & merge

#43812 Add taxmyPHAGE recipe
  recipes/taxmyphage/meta.yaml
Labels: please review & merge

#43804 add syngap recipes
  recipes/syngap/build.sh
  recipes/syngap/meta.yaml
Labels: please review & merge

#43822 Add bamdash
  recipes/bamdash/LICENSE
  recipes/bamdash/meta.yaml
Labels: please review & merge

#43833 Update dnmtools: new version 1.4.2
  recipes/dnmtools/build.sh
  recipes/dnmtools/meta.yaml
Labels: please review & merge

#43832 Add recipe for mavis-config v1.2.2
  recipes/mavis-config/meta.yaml
Labels: please review & merge

#43846 added recipe for isospecpy
  recipes/isospecpy/meta.yaml
Labels: please review & merge

#43799 Update pyopenms 3.1.0
  recipes/pyopenms/build.sh
  recipes/pyopenms/meta.yaml
Labels: please review & merge

#43121 Add pyrodigal-gv
  recipes/pyrodigal-gv/meta.yaml
Labels: please review & merge

#43854 Update table2asn to 2023-10-05
  recipes/table2asn/meta.yaml
Labels: please review & merge

#43856 Update License info for pxblat
  recipes/pxblat/meta.yaml
Labels: please review & merge

#43865 Update DAJIN2
  recipes/dajin2/meta.yaml
Labels: please review & merge

#43879 Update aspera-cli recipe
  recipes/aspera-cli/build.sh
  recipes/aspera-cli/meta.yaml
Labels: please review & merge

#43334 Update StrainGE recipe, new version, add run_exports, and fix scipy dependency version
  recipes/strainge/meta.yaml
Labels: please review & merge

#43912 Fix Python version to macrel execution
  recipes/macrel/meta.yaml
Labels: please review & merge

#43894 Update assembly_finder recipe
  recipes/assembly_finder/meta.yaml
Labels: please review & merge

#43919 Fixing the perl paths for all relevant gmap scripts
  recipes/gmap/build.sh
  recipes/gmap/meta.yaml
Labels: please review & merge

#43909 Update snakeSV recipe
  recipes/snakesv/build.sh
  recipes/snakesv/meta.yaml
Labels: please review & merge

#43910 Add COMEBin
  recipes/comebin/build.sh
  recipes/comebin/meta.yaml
Labels: please review & merge

#43949 update recipe for args_oap
  recipes/args_oap/meta.yaml
Labels: please review & merge

#43944 Update beav v0.5.5
  recipes/beav/build.sh
  recipes/beav/meta.yaml
Labels: please review & merge

#43943 Update snakesv build
  recipes/snakesv/build.sh
  recipes/snakesv/meta.yaml
Labels: please review & merge

#43941 Add Phylogenize
  recipes/phylogenize/build.sh
  recipes/phylogenize/meta.yaml
Labels: please review & merge

#43961 Update psm-utils: Add missing pyopenms dependency
  recipes/psm-utils/meta.yaml
Labels: please review & merge

#43963 Add severus
  recipes/severus/build.sh
  recipes/severus/meta.yaml
Labels: please review & merge

#43756 Update GFAffix
  recipes/gfaffix/meta.yaml
Labels: please review & merge

#43932 Update biscuit to v1.3.0
  recipes/biscuit/meta.yaml
Labels: please review & merge

#43984 Update auspice to 2.50.0
  recipes/auspice/meta.yaml
Labels: please review & merge

#43977 Update: gtfparse: fix dependency
  recipes/gtfparse/meta.yaml
Labels: please review & merge

#44002 Update mbgc recipe
  recipes/mbgc/build.sh
  recipes/mbgc/meta.yaml
Labels: please review & merge
