Repository bioconda/bioconda-recipes, pull requests merged in 2023-04, with the labels that each got.

#40175 Update hmftools-linx to 1.22.1
  recipes/hmftools-linx/meta.yaml
Labels: please review & merge

#40061 initial release of fastQuast
  recipes/fastquast/meta.yaml
Labels: please review & merge

#40125 vgan 2.0
  recipes/vgan/meta.yaml
Labels: please review & merge

#40135 Update the segmetrics recipe to 1.2.3
  recipes/segmetrics/meta.yaml
Labels: please review & merge

#40166 Add espresso recipe
  recipes/espresso/LICENSE
  recipes/espresso/build.sh
  recipes/espresso/meta.yaml
Labels: please review & merge

#39987 Add viralflye
  recipes/viralflye/build.sh
  recipes/viralflye/meta.yaml
  recipes/viralflye/post-link.sh
Labels: please review & merge

#40055 Update abPOA build.sh
  recipes/abpoa/build.sh
  recipes/abpoa/meta.yaml
Labels: please review & merge

#40200 Update TEsorter to 1.4.6
  recipes/tesorter/meta.yaml
Labels: please review & merge

#40108 Add new recipe for bamstats
  recipes/bamstats/build.sh
  recipes/bamstats/meta.yaml
Labels: please review & merge

#40149 Add new recipe for pecat
  recipes/pecat/build.sh
  recipes/pecat/meta.yaml
Labels: please review & merge

#40225 Update freyja to 1.4.1
  recipes/freyja/meta.yaml
Labels: please review & merge

#40187 Add recipe for FFGC (Family Free Genome Comparison) workflow
  recipes/ffgc/meta.yaml
Labels: please review & merge

#40172 Update fastq_utils recipe (fixed linting issues)
  recipes/fastq_utils/meta.yaml
Labels: please review & merge

#40262 Update: Added pandas requirement
  recipes/mindagap/meta.yaml
Labels: please review & merge

#40099 Attempt rebuild unitig-caller with new bifrost ver
  recipes/unitig-caller/0001-No-experimental.patch
  recipes/unitig-caller/0002-Change-linker-for-filesystem-path.patch
  recipes/unitig-caller/meta.yaml
Labels: please review & merge

#40288 pin r-stringi to avoid libicui18n.so.58 error
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#40260 Update PICRUSt2 to 2.5.2
  recipes/picrust2/meta.yaml
  recipes/picrust2/post-link.sh
Labels: please review & merge

#40228 add pepsirf recipe
  recipes/pepsirf/build.sh
  recipes/pepsirf/meta.yaml
Labels: please review & merge

#40230 Update EVidenceModeler to 2.1.0
  recipes/evidencemodeler/build.sh
  recipes/evidencemodeler/meta.yaml
Labels: please review & merge

#40072 Update mnnpy: Pin scipy to <1.9.0 as mmnpy uses n_jobs
  recipes/mnnpy/meta.yaml
Labels: please review & merge

#39885 Add: pyctv taxonomy
  recipes/pyctv_taxonomy/meta.yaml
Labels: please review & merge

#40240 Update recipe for exomiser-rest-prioritiser to v13.2
  recipes/exomiser-rest-prioritiser/meta.yaml
Labels: please review & merge

#40242 vsnp3 version 3.12
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#40250 [Update] Updating EUKulele to 2.0.6
  recipes/eukulele/meta.yaml
Labels: please review & merge

#40264 Update evofr to 0.1.17, update dependencies
  recipes/evofr/meta.yaml
Labels: please review & merge

#40265 Update rmblast to 2.13.0
  recipes/rmblast/build.sh
  recipes/rmblast/isb-2.11.0+-rmblast.patch
  recipes/rmblast/isb-2.13.0+-rmblast.patch
  recipes/rmblast/meta.yaml
Labels: please review & merge

#40273 Update NextDenovo to 2.5.2
  recipes/nextdenovo/meta.yaml
Labels: please review & merge

#40276 Update runjob to 2.10.4
  recipes/runjob/meta.yaml
Labels: please review & merge

#40314 vSNP3
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#40289 Pin to Pandas < 2
  recipes/igdiscover/meta.yaml
Labels: please review & merge

#39384 recipes/cellqc/meta.yaml: add graphviz to generate dot graph
  recipes/cellqc/meta.yaml
Labels: please review & merge

#39350 Add pydmtools
  recipes/pydmtools/build.sh
  recipes/pydmtools/meta.yaml
Labels: please review & merge

#40299 pbhoover: add missing runtime dependency on htslib
  recipes/pbhoover/meta.yaml
Labels: please review & merge

#40301 Added brooklyn-plot
  recipes/brooklyn_plot/LICENSE
  recipes/brooklyn_plot/meta.yaml
Labels: please review & merge

#40315 add drprg recipe
  recipes/drprg/build.sh
  recipes/drprg/meta.yaml
Labels: please review & merge

#40292 Bump iqtree2 to v2.2.2.3
  recipes/iqtree/meta.yaml
Labels: please review & merge

#40321 Update ninja-nj to 0.98
  recipes/ninja-nj/meta.yaml
Labels: please review & merge

#40330 Update trinity to 2.15.1
  recipes/trinity/build.sh
  recipes/trinity/makefile.patch
  recipes/trinity/meta.yaml
Labels: please review & merge

#40331 Update masurca to 4.1.0
  recipes/masurca/build.sh
  recipes/masurca/meta.yaml
Labels: please review & merge

#40347 update-piscem
  recipes/piscem/meta.yaml
Labels: please review & merge

#40346 vSNP3
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#40350 update piscem
  recipes/piscem/meta.yaml
Labels: please review & merge

#40332 Update GMAP to 2023-03-24
  recipes/gmap/build.sh
  recipes/gmap/meta.yaml
  recipes/gmap/single_quote_paths.patch
Labels: please review & merge

#40333 Update GTDB-tk recipe
  recipes/gtdbtk/download-db.sh
  recipes/gtdbtk/meta.yaml
Labels: please review & merge

#40342 Update meta.yaml
  recipes/clair3-trio/meta.yaml
Labels: please review & merge

#40340 Update Trinotate to 4.0.0
  recipes/trinotate/build.sh
  recipes/trinotate/meta.yaml
  recipes/trinotate/trinotate.patch
Labels: please review & merge

#40341 Add: defense finder
  recipes/defense-finder/0001-fix-no-results.patch
  recipes/defense-finder/meta.yaml
Labels: please review & merge

#40397 update piscem
  recipes/piscem/meta.yaml
Labels: please review & merge

#40379 Update pharokka to 1.3.0
  recipes/pharokka/meta.yaml
Labels: please review & merge

#40413 Fixed help string in MashMap v3.0.1
  recipes/mashmap/meta.yaml
Labels: please review & merge

#40399 Update tracy v0.7.5
  recipes/tracy/meta.yaml
Labels: please review & merge

#40409 Update dsh-bio to 2.2.1
  recipes/dsh-bio/meta.yaml
Labels: please review & merge

#40419 Update peptide-shaker to 2.2.23
  recipes/peptide-shaker/meta.yaml
  recipes/peptide-shaker/peptide-shaker.py
Labels: please review & merge

#40389 Add pbfusion v0.1.0
  recipes/pbfusion/build.sh
  recipes/pbfusion/meta.yaml
Labels: please review & merge

#40421 Update: antismash-lite relaxed hmmer3 and diamond reqs
  recipes/antismash-lite/meta.yaml
Labels: please review & merge

#40414 Update segtools to 1.3.0 and set minimum python version requirement to 3.7
  recipes/segtools/meta.yaml
Labels: please review & merge

#40422 Update funannotate v1.8.15: evm tag to v1.1.1 as cli options changed in newest version
  recipes/funannotate/meta.yaml
Labels: please review & merge

#40220 Add recipe for SuperDSM
  recipes/superdsm/meta.yaml
Labels: please review & merge

#40424 Update TaxonKit to 0.14.2
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#40461 upgrade to MitoZ 3.6
  recipes/mitoz/meta.yaml
Labels: please review & merge

#40462 Update SearchGUI to 4.2.9
  recipes/searchgui/build.sh
  recipes/searchgui/meta.yaml
  recipes/searchgui/searchgui.py
Labels: please review & merge

#40286 Add recipe for mehari v0.1.1
  recipes/mehari/build.sh
  recipes/mehari/meta.yaml
Labels: please review & merge

#40453 Update hmftools-sv-prep: add samtools as dependency
  recipes/hmftools-sv-prep/meta.yaml
Labels: please review & merge

#40471 Update Guidescan to v2.1.4
  recipes/guidescan/meta.yaml
Labels: please review & merge

#40464 Add samcut
  recipes/samcut/build.sh
  recipes/samcut/meta.yaml
Labels: please review & merge

#40218 Add cellsnake recipe
  recipes/cellsnake/meta.yaml
Labels: please review & merge

#40394 Patch rmblast 2.13.0 and remove from blacklist
  build-fail-blacklist
  recipes/rmblast/build.sh
  recipes/rmblast/configurellvm.patch
  recipes/rmblast/get_species_taxids.patch
  recipes/rmblast/meta.yaml
  recipes/rmblast/phonehome.patch
Labels: please review & merge

#40475 Update icescreen v1.2.0
  recipes/icescreen/meta.yaml
Labels: please review & merge

#40435 Update FFGC to 2.4.2
  recipes/ffgc/meta.yaml
Labels: please review & merge

#40490 Update mapad to 0.42.1
  recipes/mapad/meta.yaml
Labels: please review & merge

#40484 Update RepeatMasker to 4.1.5
  recipes/repeatmasker/build.sh
  recipes/repeatmasker/meta.yaml
  recipes/repeatmasker/post-link.sh
Labels: please review & merge

#40497 Update diamond: build with zstd & blast support
  recipes/diamond/build.sh
  recipes/diamond/meta.yaml
Labels: please review & merge

#40506 Update JCVI: include missing dependencies
  recipes/jcvi/meta.yaml
Labels: please review & merge

#40495 Update MEME to 5.5.2
  recipes/meme/build.sh
  recipes/meme/meta.yaml
Labels: please review & merge

#40498 Update requirements: add mamba
  recipes/snakemake/meta.yaml
Labels: please review & merge

#40463 Update breseq to 0.38.1
  recipes/breseq/meta.yaml
Labels: please review & merge

#40527 JCVI: include additional dependiencies
  recipes/jcvi/meta.yaml
Labels: please review & merge

#40535 Update ntlink to 1.3.9
  recipes/ntlink/meta.yaml
Labels: please review & merge

#40504 Update tyto to 1.4
  recipes/tyto/meta.yaml
Labels: please review & merge

#40544 Update seq2science to 0.9.9
  recipes/seq2science/meta.yaml
Labels: new version

#40526 Add hybpiper
  recipes/hybpiper/LICENSE.txt
  recipes/hybpiper/build.sh
  recipes/hybpiper/meta.yaml
Labels: please review & merge

#40528 Add ndex2
  recipes/ndex2/meta.yaml
Labels: please review & merge

#40518 Add recipe for mSWEEP v1.6.3
  recipes/msweep/build.sh
  recipes/msweep/meta.yaml
Labels: please review & merge

#40557 Update meme 4.11.2 and remove from blacklist
  build-fail-blacklist
  recipes/meme/4.11.2/build.sh
  recipes/meme/4.11.2/meta.yaml
Labels: please review & merge

#40483 Add hybkit Recipe
  recipes/hybkit/meta.yaml
Labels: please review & merge

#40591 Update epiweeks to 2.2.0
  recipes/epiweeks/meta.yaml
Labels: please review & merge

#40593 Bump r-shinyngs to 1.7.2
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#40588 Update to v0.6
  recipes/clair3-trio/meta.yaml
Labels: please review & merge

#40585 Update MArVD2 to 0.11.9
  recipes/marvd2/meta.yaml
Labels: please review & merge

#40489 Add kGWASflow v1.2.1
  recipes/kgwasflow/meta.yaml
Labels: please review & merge

#40632 Funannotate: pin pandas
  recipes/funannotate/meta.yaml
Labels: please review & merge

#40651 Patch pasa and update dependencies
  recipes/pasa/meta.yaml
Labels: please review & merge

#40610 update CCTK to version 1.0.1
  recipes/cctk/meta.yaml
Labels: please review & merge

#40708 Update unifrac-binaries to 1.3.1
  recipes/unifrac-binaries/build.sh
  recipes/unifrac-binaries/meta.yaml
Labels: please review & merge

#40719 Update meta.yaml
  recipes/vgan/meta.yaml
Labels: automerge
