Repository bioconda/bioconda-recipes, pull requests merged in 2024-11, with the labels that each got.

#51846 Update SACCHARIS
  recipes/saccharis/meta.yaml
Labels: please review & merge

#51881 Bump MUSCLE to 5.2
  recipes/muscle/build.sh
  recipes/muscle/meta.yaml
  recipes/muscle/support-linux-aarch64.patch
  recipes/muscle/vcxproj_make.py
Labels: please review & merge

#51863 Update vg to 1.60.0
  recipes/vg/meta.yaml
Labels: please review & merge

#51864 Adding msa4u
  recipes/msa4u/meta.yaml
Labels: please review & merge

#51826 Update meta-neuro version 1.0.0
  recipes/meta-neuro/build.sh
  recipes/meta-neuro/conda_build_config.yaml
  recipes/meta-neuro/meta.yaml
Labels: please review & merge

#51893 Bump `pyrodigal` to v3.6.3
  recipes/pyrodigal/meta.yaml
Labels: please review & merge

#51811 Update JARVIS3 recipe
  recipes/jarvis3/build.sh
  recipes/jarvis3/meta.yaml
Labels: please review & merge

#51831 Use openjdk 11 for hmftools-redux and update hmftools-sage jar
  recipes/hmftools-esvee/meta.yaml
  recipes/hmftools-redux/meta.yaml
  recipes/hmftools-sage/meta.yaml
Labels: please review & merge

#51865 Pathogen profiler
  recipes/pathogen-profiler/meta.yaml
Labels: please review & merge

#51905 mutyper: add aarch64/arm64 builds
  recipes/mutyper/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51901 Update stranger with setuptools and change dev url
  recipes/stranger/meta.yaml
Labels: please review & merge

#51897 Add ntStat
  recipes/ntstat/build.sh
  recipes/ntstat/meta.yaml
Labels: please review & merge

#51711 zol: add aarch64/arm64 builds
  recipes/zol/build.sh
  recipes/zol/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51911 Update decom recipe by adding kmtricks dependency
  recipes/decom/meta.yaml
Labels: please review & merge

#51882 Add Reseek
  recipes/reseek/build.sh
  recipes/reseek/meta.yaml
  recipes/reseek/vcxproj_make.py
Labels: please review & merge

#51801 install_rotate_1.0
  recipes/rotate/build.sh
  recipes/rotate/meta.yaml
Labels: please review & merge

#51936 Update seqspec to 0.3.1
  recipes/seqspec/meta.yaml
Labels: please review & merge

#51931 Add gaftools
  recipes/gaftools/meta.yaml
Labels: please review & merge

#51950 Update SACCHARIS
  recipes/saccharis/meta.yaml
Labels: please review & merge

#51709 Update CAT (CAT_pack) to 6.0.1
  recipes/cat/build.sh
  recipes/cat/meta.yaml
Labels: please review & merge

#51956 cuttlefish: add arm64 build
  recipes/cuttlefish/build.sh
  recipes/cuttlefish/build_failure.osx-64.yaml
  recipes/cuttlefish/meta.yaml
Labels: osx-arm64

#51982 Update TRTools to 6.1.0
  recipes/trtools/meta.yaml
Labels: please review & merge

#51975 Add bam2plot
  recipes/bam2plot/meta.yaml
Labels: please review & merge

#50011 Add M1 builds for PopPUNK
  recipes/poppunk/meta.yaml
Labels: osx-arm64

#51997 Update PhaBOX to 2.1.5
  recipes/phabox/meta.yaml
Labels: please review & merge

#52010 update longcallr_nn
  recipes/longcallr_nn/meta.yaml
Labels: please review & merge

#51969 Add r-remapenrich to bioconda-recipes
  recipes/r-remapenrich/build.sh
  recipes/r-remapenrich/meta.yaml
Labels: please review & merge

#52041 update argo to 0.1.2 and fix setuptool
  recipes/argo/meta.yaml
Labels: please review & merge

#52039 update melon to 0.2.1 and fix summary
  recipes/melon/meta.yaml
Labels: please review & merge

#52059 Proteinortho update, the automatic update does not work anymore ...
  recipes/proteinortho/build.sh
  recipes/proteinortho/meta.yaml
Labels: aarch64

#52061 cd-hit: add osx-arm64 build
  recipes/cd-hit/build.sh
  recipes/cd-hit/cd-hit.patch
  recipes/cd-hit/meta.yaml
Labels: osx-arm64

#52050 Coptr python version
  recipes/coptr/meta.yaml
Labels: please review & merge

#52030 Update atlas to 2.0.0-rc.6
  recipes/atlas/build.sh
  recipes/atlas/meta.yaml
Labels: please review & merge

#52076 bayestyper: add arm64/aarch64 builds
  build-fail-blacklist
  recipes/bayestyper/0001-CMakeLists.patch
  recipes/bayestyper/bayestyper.patch
  recipes/bayestyper/build.sh
  recipes/bayestyper/kmer_defs.patch
  recipes/bayestyper/meta.yaml
  recipes/bayestyper/stdafx.patch
Labels: aarch64, osx-arm64

#52069 Update revbayes to v1.2.4
  recipes/revbayes/build.sh
  recipes/revbayes/meta.yaml
Labels: osx-arm64

#52077 Rebuild bayestyper recipe
  recipes/bayestyper/bayestyper.patch
  recipes/bayestyper/meta.yaml
Labels: aarch64, osx-arm64

#52081 Update hmftools-orange to 3.7.1_beta.3
  recipes/hmftools-orange/meta.yaml
Labels: please review & merge

#52066 Update strangepg to 0.8.14, remove non-functional aarch64 platform and obsolete test
  recipes/strangepg/build.sh
  recipes/strangepg/meta.yaml
  recipes/strangepg/run_test.sh
Labels: please review & merge

#52125 krakentools: alpha_diversity requires scipy
  recipes/krakentools/meta.yaml
Labels: please review & merge

#52124 Pinning ggplot2 version
  recipes/merqury/meta.yaml
Labels: please review & merge

#52130 version upgrade for jaeger-bio
  recipes/jaeger-bio/meta.yaml
Labels: please review & merge

#52095 Add rdeval
  recipes/rdeval/Makefile.patch
  recipes/rdeval/build.sh
  recipes/rdeval/gfalibs-Makefile.patch
  recipes/rdeval/gfalibs.patch
  recipes/rdeval/meta.yaml
  recipes/rdeval/zlib.patch
Labels: please review & merge

#51810 Add new package kestrel in version 1.0.3
  recipes/kestrel/build.sh
  recipes/kestrel/meta.yaml
Labels: please review & merge

#52143 Update Snk-CLI
  recipes/snk-cli/meta.yaml
Labels: please review & merge

#51796 Add Instanovo
  recipes/instanovo/meta.yaml
Labels: please review & merge

#52180 Add osx-arm64 to agc
  recipes/agc/meta.yaml
Labels: please review & merge

#52197 Update lsabgc recipe/build to constrain dependency
  recipes/lsabgc/meta.yaml
Labels: please review & merge

#52184 Update ampcombi to v.2.0.1
  recipes/ampcombi/meta.yaml
Labels: please review & merge

#52173 update dependancies
  recipes/tb-profiler/meta.yaml
Labels: please review & merge

#52181 Update mess recipe
  recipes/mess/meta.yaml
Labels: please review & merge

#52177 Update Commec
  recipes/commec/meta.yaml
Labels: please review & merge

#52166 Add mzpaf as requirement for mzSpecLib
  recipes/mzpaf/LICENSE
  recipes/mzpaf/meta.yaml
Labels: please review & merge

#52144 Add recipe for snpick
  recipes/snpick/meta.yaml
Labels: please review & merge

#52209 Racon: add arm64 build
  recipes/racon/build.sh
  recipes/racon/meta.yaml
  recipes/racon/racon_wrapper.patch
Labels: osx-arm64

#52164 update gempipe to v1.37.3
  recipes/gempipe/meta.yaml
Labels: please review & merge

#52103 Add search ncbi
  recipes/search_ncbi/meta.yaml
Labels: please review & merge

#52216 Update Palantir v1.3.3 -> v1.3.4
  recipes/palantir/meta.yaml
Labels: please review & merge

#52215 Update Saccharis
  recipes/saccharis/meta.yaml
Labels: please review & merge

#52187 Add mzspeclib
  recipes/mzspeclib/meta.yaml
Labels: please review & merge

#52230 psmc: add aarch64/arm64 builds
  recipes/psmc/build.sh
  recipes/psmc/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52236 relion: add aarch64/arm64 builds
  recipes/relion/build.sh
  recipes/relion/build_failure.osx-64.yaml
  recipes/relion/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52229 Update Trinity requirements
  recipes/trinity/meta.yaml
Labels: please review & merge

#52237 meryl: add linux-aarch64 and osx-arm64 build
  recipes/meryl/0003-align.patch
  recipes/meryl/build.sh
  recipes/meryl/meryl-utility-aarch64.patch
  recipes/meryl/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52272 Enforce openjdk 21, part 3/4 (Linx, Neo, Orange, Pave, Peach)
  recipes/hmftools-linx/meta.yaml
  recipes/hmftools-neo/meta.yaml
  recipes/hmftools-orange/meta.yaml
  recipes/hmftools-pave/meta.yaml
  recipes/hmftools-peach/meta.yaml
Labels: please review & merge

#52264 Update PhaBOX to 2.1.6
  recipes/phabox/meta.yaml
Labels: please review & merge

#52268 Enforce openjdk 21 for hmftools, part 2/4 (Cuppa, Esvee, Isofox, Lilac)
  recipes/hmftools-cuppa/meta.yaml
  recipes/hmftools-esvee/meta.yaml
  recipes/hmftools-isofox/meta.yaml
  recipes/hmftools-lilac/meta.yaml
Labels: please review & merge

#52267 Enforce openjdk 21 for hmftools, part 1/4 (Amber, Bamtools, Chord, Cobalt)
  recipes/hmftools-amber/meta.yaml
  recipes/hmftools-bam-tools/meta.yaml
  recipes/hmftools-chord/meta.yaml
  recipes/hmftools-cobalt/meta.yaml
Labels: please review & merge

#52261 Update Saccharis
  recipes/saccharis/meta.yaml
Labels: please review & merge

#52257 updated pgrc revision to 2.0.2
  recipes/pgrc/meta.yaml
Labels: please review & merge

#52211 Add wipertools
  recipes/wipertools/LICENSE.txt
  recipes/wipertools/build.sh
  recipes/wipertools/meta.yaml
Labels: please review & merge

#51890 Building pblat for more platforms
  recipes/pblat/meta.yaml
  recipes/pblat/pblat-aarch64.patch
Labels: please review & merge, aarch64, osx-arm64

#51978 Update FINEMAP to 1.4.2
  recipes/finemap/meta.yaml
Labels: please review & merge

#51108 Add EGA-Cryptor
  recipes/ega-cryptor/LICENSE
  recipes/ega-cryptor/build.sh
  recipes/ega-cryptor/ega-cryptor.py
  recipes/ega-cryptor/meta.yaml
Labels: please review & merge

#52287 Update psm_utils recipe
  recipes/psm-utils/meta.yaml
Labels: please review & merge

#52289 Update recipe of artic 1.5.5
  recipes/artic/meta.yaml
Labels: please review & merge

#52288 Update r-stitch to v1.7.2
  recipes/r-stitch/meta.yaml
Labels: please review & merge

#52294 Update Saccharis
  recipes/saccharis/meta.yaml
Labels: please review & merge

#52293 Update version, add dev url
  recipes/simug/meta.yaml
Labels: please review & merge

#52291 Update deeplcretrainer
  recipes/deeplcretrainer/meta.yaml
Labels: please review & merge

#52308 Update htsinfer to 1.0.0-rc.1
  recipes/htsinfer/meta.yaml
Labels: please review & merge

#52306 Add PanTA pan-genome pipeline
  recipes/panta/meta.yaml
Labels: please review & merge

#52286 Update DeepLC to 3.1.3
  recipes/deeplc/LICENSE
  recipes/deeplc/meta.yaml
Labels: please review & merge

#52325 updating to release v0.0.10+
  recipes/genodsp/meta.yaml
  recipes/genodsp/stringop-truncation.patch
Labels: please review & merge

#52329 updating version of required package genodsp to 0.0.10
  recipes/halfdeep/meta.yaml
Labels: please review & merge

#52322 Update dysgu v1.70
  recipes/dysgu/meta.yaml
Labels: please review & merge

#52333 Add recipe hifiadapterfilt
  recipes/hifiadapterfilt/build.sh
  recipes/hifiadapterfilt/meta.yaml
Labels: please review & merge

#52332 Update recipe wipertools
  recipes/wipertools/meta.yaml
Labels: please review & merge

#52337 adding recipe for absense to prevent issue with genera
  recipes/absense/build.sh
  recipes/absense/meta.yaml
Labels: please review & merge

#52328 Add recipe for PhyClone
  recipes/phyclone/meta.yaml
Labels: please review & merge

#52318 Add recipe for Clipp v1.3.3
  recipes/clipp/meta.yaml
Labels: osx-arm64

#52262 Add ntsm recipe https://github.com/JustinChu/ntsm
  recipes/ntsm/LICENSE
  recipes/ntsm/build.sh
  recipes/ntsm/meta.yaml
Labels: please review & merge

#52274 Enforce openjdk 21, part 4/4 (Purple, Sage, Sigs, Virusinterpreter)
  recipes/hmftools-purple/meta.yaml
  recipes/hmftools-sage/meta.yaml
  recipes/hmftools-sigs/meta.yaml
  recipes/hmftools-virus-interpreter/meta.yaml
Labels: please review & merge

#52350 cobs: add aarch64/arm64 builds
  recipes/cobs/cobs-aarch64.patch
  recipes/cobs/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52347 Update agc to 3.2
  recipes/agc/meta.yaml
Labels: please review & merge

#51721 GenEra Conda Recipes Submission
  recipes/genera/build.sh
  recipes/genera/meta.yaml
Labels: please review & merge

#52356 Add lrge v0.1.1
  recipes/lrge/build.sh
  recipes/lrge/meta.yaml
Labels: please review & merge

#45370 EDTA - fix and clean recipe
  recipes/edta/build.sh
  recipes/edta/meta.yaml
Labels: please review & merge

#52369 Update gretl recipe
  recipes/gretl/meta.yaml
Labels: please review & merge

#52382 Updated MMseqs2 to 16.747c6
  recipes/mmseqs2/build.sh
  recipes/mmseqs2/meta.yaml
Labels: please review & merge

#52371 Add mirscore 0.3.0
  recipes/mirscore/build.sh
  recipes/mirscore/meta.yaml
Labels: please review & merge

#52405 Update Kmer-db to 2.2.5
  recipes/kmer-db/meta.yaml
Labels: please review & merge

#52406 Update lz-ani to 1.2.3
  recipes/lz-ani/meta.yaml
Labels: please review & merge

#52407 Update clusty to 1.1.5
  recipes/clusty/build.sh
  recipes/clusty/buildfixes.patch
  recipes/clusty/meta.yaml
Labels: please review & merge

#52396 linux-aarch64 control-freec support
  recipes/control-freec/build.sh
  recipes/control-freec/meta.yaml
Labels: aarch64

#52400 Add linux-aarch64 to perl-extutils-cppguess and perl-set-intervaltree
  recipes/perl-extutils-cppguess/meta.yaml
  recipes/perl-set-intervaltree/meta.yaml
Labels: aarch64

#50566 meraculous: add linux-aarch64 build
  recipes/meraculous/build.sh
  recipes/meraculous/meraculous-aarch64.patch
  recipes/meraculous/meta.yaml
Labels: please review & merge, aarch64

#52413 rsem: add linux-aarch64 support and document missing osx-arm64 dependencies.
  recipes/rsem/build.sh
  recipes/rsem/meta.yaml
Labels: aarch64

#52420 Update vclust to 1.2.9
  recipes/vclust/meta.yaml
Labels: please review & merge

#52412 hisat2: Add linux-aarch64 and osx-arm64 support
  recipes/hisat2/build.sh
  recipes/hisat2/meta.yaml
  recipes/hisat2/simde-mr-c.patch
Labels: aarch64, osx-arm64

#52414 Kraken2: add linux-aarch64 support and document missing osx-arm64
  recipes/kraken2/meta.yaml
Labels: aarch64

#52411 bracken: add linux-aarch64 support
  recipes/bracken/meta.yaml
Labels: aarch64

#52427 Update ninja-nj to 1.00
  recipes/ninja-nj/0001-Makefile.patch
  recipes/ninja-nj/build.sh
  recipes/ninja-nj/meta.yaml
Labels: aarch64, osx-arm64

#52430 nseg: add aarch64/arm64 build
  recipes/nseg/build.sh
  recipes/nseg/meta.yaml
Labels: aarch64, osx-arm64

#52431 trf: add arm64 build
  recipes/trf/build.sh
  recipes/trf/meta.yaml
Labels: osx-arm64

#52428 Update RepeatScout to 1.0.7
  recipes/repeatscout/build.sh
  recipes/repeatscout/build_failure.linux-64.yaml
  recipes/repeatscout/build_failure.osx-64.yaml
  recipes/repeatscout/meta.yaml
Labels: aarch64, osx-arm64

#52402 strelka: enable linux-aarch64
  recipes/strelka/meta.yaml
Labels: aarch64

#52450 Update busco to 5.8.1
  recipes/busco/meta.yaml
Labels: please review & merge

#52449 Update pytximport to 0.11.0
  recipes/pytximport/meta.yaml
Labels: please review & merge

#52440 Update quota_anchor to v0.0.1b1
  recipes/quota_anchor/build.sh
  recipes/quota_anchor/meta.yaml
Labels: please review & merge

#46839 linux-aarch64 build for amplisim
  recipes/amplisim/build.sh
  recipes/amplisim/meta.yaml
Labels: aarch64

#52433 Update: v2.2.4 build1 -> v2.2.4 build2
  recipes/virsorter/meta.yaml
Labels: please review & merge

#52480 yacht: add linux-aarch64 build
  recipes/yacht/meta.yaml
Labels: please review & merge, aarch64

#52478 fairy: add aarch64/arm64 builds
  recipes/fairy/build.sh
  recipes/fairy/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52474 bed2gtf: add aarch64 builds
  recipes/bed2gtf/build.sh
  recipes/bed2gtf/meta.yaml
Labels: please review & merge, aarch64

#52469 Bump deepfplearn
  recipes/deepfplearn/meta.yaml
Labels: please review & merge

#52473 gretl: add aarch64/arm64 builds
  recipes/gretl/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52472 r-lisi: add linux-aarch64 build
  recipes/r-lisi/meta.yaml
Labels: please review & merge, aarch64

#52250 Update ntStat to 1.0.1-1
  recipes/ntstat/meta.yaml
Labels: please review & merge

#52470 viral_consensus: add aarch64/arm64 builds
  recipes/viral_consensus/build.sh
  recipes/viral_consensus/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52248 Update ntedit to 2.1.0
  recipes/ntedit/meta.yaml
Labels: please review & merge
