Repository bioconda/bioconda-recipes, pull requests merged in 2024-03, with the labels that each got.

#46096 anndata2ri: fix rpy2 dependency for v1.3.1
  recipes/anndata2ri/meta.yaml
Labels: please review & merge

#45954 update bio digest recipe
  recipes/biodigest/meta.yaml
  recipes/biodigest/post-link.sh
Labels: please review & merge

#46111 pin Diamond to 2.1.8
  recipes/bakta/meta.yaml
Labels: please review & merge

#46109 hybran: limit biopython dependency to <1.82 due to breaking change
  recipes/hybran/meta.yaml
Labels: please review & merge

#46093 Add JRONN recipe
  recipes/jronn/build.gradle
  recipes/jronn/build.sh
  recipes/jronn/jronn.sh
  recipes/jronn/meta.yaml
Labels: please review & merge

#46124 Fix IonQuant Recipe
  recipes/ionquant/build.sh
  recipes/ionquant/ionquant.py
  recipes/ionquant/meta.yaml
Labels: please review & merge

#46148 Update gum to v2.0.2
  recipes/gum/meta.yaml
Labels: please review & merge

#45910 Update `pyhmmer` recipe to `v0.10.7` and run integrated unit tests
  recipes/pyhmmer/meta.yaml
Labels: please review & merge

#40550 feat: add initial support for arm builds
  .circleci/check-for-additional-platforms.sh
  .circleci/config.yml
  recipes/abra2/meta.yaml
Labels: WIP

#46157 captus - add version restriction for pandas (second try)
  recipes/captus/meta.yaml
Labels: please review & merge

#46107 Add phynder
  recipes/phynder/build.sh
  recipes/phynder/meta.yaml
Labels: please review & merge

#46164 Update MMseqs2 build-number for arm build
  recipes/mmseqs2/meta.yaml
Labels: please review & merge

#46159 Add phold
  recipes/phold/meta.yaml
Labels: please review & merge

#46139 update biodigest
  recipes/biodigest/meta.yaml
Labels: please review & merge

#46125 Fix MSFragger Recipe
  recipes/msfragger/build.sh
  recipes/msfragger/meta.yaml
  recipes/msfragger/msfragger.py
Labels: please review & merge

#46172 Update metaeuk for linux-aarch64
  recipes/metaeuk/build.sh
  recipes/metaeuk/meta.yaml
Labels: please review & merge

#46173 Update spacepharer for linux-aarch64
  recipes/spacepharer/build.sh
  recipes/spacepharer/meta.yaml
Labels: please review & merge

#46171 Update metabuli for linux-aarch64
  recipes/metabuli/build.sh
  recipes/metabuli/meta.yaml
Labels: please review & merge

#46158 Build htslib for linux-aarch64
  recipes/htslib/arm_hwcap.patch
  recipes/htslib/meta.yaml
Labels: please review & merge

#46193 Build bcftools and samtools for linux-aarch64
  recipes/bcftools/meta.yaml
  recipes/samtools/meta.yaml
Labels: please review & merge

#46194 Build bedtools for linux-aarch64
  recipes/bedtools/meta.yaml
Labels: please review & merge

#46168 build fastq-scan for linux-aarch64
  recipes/fastq-scan/meta.yaml
Labels: please review & merge

#46195 Update MS2PIP to 4.0.0.dev8
  recipes/ms2pip/meta.yaml
Labels: please review & merge

#46166 add dosage_score
  recipes/dosage_score/LICENSE.txt
  recipes/dosage_score/meta.yaml
Labels: please review & merge

#46206 moving org for varfish-server-worker
  recipes/varfish-server-worker/meta.yaml
Labels: please review & merge

#46205 Update ms2pip version in ms2rescore
  recipes/ms2rescore/meta.yaml
Labels: please review & merge

#46199 Build pysam for linux-aarch64
  recipes/pysam/arm_hwcap.patch
  recipes/pysam/meta.yaml
Labels: please review & merge

#46212 Update ToulligQC to v2.5.2
  recipes/toulligqc/meta.yaml
Labels: please review & merge

#46213 bump mitos2
  recipes/mitos/meta.yaml
Labels: please review & merge

#46227 Update TaxonKit to v0.16.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#46136 Add gxf2chrom
  recipes/gxf2chrom/build.sh
  recipes/gxf2chrom/meta.yaml
Labels: please review & merge

#46215 Add ribotools
  recipes/ribotools/meta.yaml
Labels: please review & merge

#46256 colabfold: fix incompatibility with jax and dm-tree
  recipes/colabfold/meta.yaml
Labels: please review & merge

#46265 Update `RDP Classifier` to 2.14
  recipes/rdp_classifier/meta.yaml
  recipes/rdp_classifier/rdp_classifier.sh
Labels: please review & merge

#46185 Update Nextclade: Enable linux-aarch64
  recipes/nextclade/meta.yaml
  recipes/nextclade/run_test.sh
Labels: please review & merge, aarch64

#46264 Add architeuthis
  recipes/architeuthis/meta.yaml
Labels: please review & merge

#46105 Add FragPipe Recipe
  recipes/fragpipe/build.sh
  recipes/fragpipe/fragpipe
  recipes/fragpipe/licenses/dia-umpire_LICENSE.txt
  recipes/fragpipe/licenses/easypqp_LICENSE.txt
  recipes/fragpipe/licenses/fragpipe_LICENSE.txt
  recipes/fragpipe/licenses/msbooster_LICENSE.txt
  recipes/fragpipe/licenses/ptm-shepherd_LICENSE.txt
  recipes/fragpipe/meta.yaml
Labels: please review & merge

#46115 Add VCF-Validator
  recipes/vcf-validator/LICENSE
  recipes/vcf-validator/LICENSE_ODB
  recipes/vcf-validator/build.sh
  recipes/vcf-validator/meta.yaml
Labels: please review & merge

#46174 Add cuteFC recipe
  recipes/cutefc/meta.yaml
Labels: please review & merge

#46056 Add recipe for robust-bias-aware
  recipes/robust-bias-aware/meta.yaml
Labels: please review & merge

#46301 Update ms2rescore: Constraint pyteomics version
  recipes/ms2rescore/meta.yaml
Labels: please review & merge

#46317 Update SeqKit to v2.8.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#46269 Add Locityper
  recipes/locityper/build.sh
  recipes/locityper/meta.yaml
Labels: please review & merge

#46311 Update viralmsa meta.yaml
  recipes/viralmsa/meta.yaml
Labels: please review & merge

#46310 Update viral_consensus meta.yaml
  recipes/viral_consensus/meta.yaml
Labels: please review & merge

#46314 Added identifiers to tn93
  recipes/tn93/meta.yaml
Labels: please review & merge

#46302 perl-digest-sha1: enable linux-aarch64 builds
  recipes/perl-digest-sha1/meta.yaml
Labels: please review & merge

#46339 update taxor to version 0.1.2
  recipes/taxor/meta.yaml
Labels: please review & merge

#46259 Reduce requirements for GW
  recipes/gw/meta.yaml
Labels: please review & merge

#46308 Update CoaTran to v0.0.4
  recipes/coatran/LICENSE
  recipes/coatran/build.sh
  recipes/coatran/meta.yaml
Labels: please review & merge

#46357 Update ribotin to version 1.3
  recipes/ribotin/build.sh
  recipes/ribotin/makefile.patch
  recipes/ribotin/meta.yaml
Labels: please review & merge

#46292 Add FAVITES-Lite v1.0.1 and its dependencies
  recipes/favites_lite/build.sh
  recipes/favites_lite/meta.yaml
  recipes/gemf_favites/build.sh
  recipes/gemf_favites/meta.yaml
  recipes/niemagraphgen/build.sh
  recipes/niemagraphgen/meta.yaml
  recipes/treesap/meta.yaml
Labels: please review & merge

#46258 Build entrez-direct from source code instead of using prebuilt binaries
  recipes/entrez-direct/aarch64.patch
  recipes/entrez-direct/build.sh
  recipes/entrez-direct/meta.yaml
  recipes/entrez-direct/xtract.patch
Labels: please review & merge, aarch64

#46391 Bump poppunk to v2.6.5
  recipes/poppunk/meta.yaml
Labels: please review & merge

#45887 Update recipe for metamaps
  recipes/metamaps/meta.yaml
Labels: please review & merge

#46420 Update deepmei to version 1.6.24
  recipes/deepmei/meta.yaml
Labels: please review & merge

#46430 snakemake: add linux-aarch64 build
  recipes/snakemake/meta.yaml
Labels: please review & merge

#46431 mafft: add linux-aarch64 build
  recipes/mafft/meta.yaml
Labels: please review & merge

#46435 vsearch: add linux-aarch64 build
  recipes/vsearch/meta.yaml
Labels: please review & merge, aarch64

#46429 dnaio: add linux-aarch64 build
  recipes/dnaio/meta.yaml
Labels: please review & merge, aarch64

#46410 Update gubbins
  recipes/gubbins/build.sh
  recipes/gubbins/meta.yaml
Labels: please review & merge

#46417 Add campygstyper
  recipes/campygstyper/meta.yaml
Labels: please review & merge

#46309 Add BioCamLib
  recipes/biocamlib/build.sh
  recipes/biocamlib/meta.yaml
Labels: please review & merge

#46453 Add libraries necessary for database splitting in FragPipe.
  recipes/fragpipe/meta.yaml
Labels: please review & merge

#45914 Add azimuth and dependencies
  recipes/r-azimuth/meta.yaml
  recipes/r-presto/meta.yaml
  recipes/r-seurat-data/meta.yaml
  recipes/r-seurat-disk/meta.yaml
Labels: please review & merge

#46464 Update csvtk to v0.30.0
  recipes/csvtk/meta.yaml
Labels: please review & merge

#46403 Add revoluzer 0.1.5
  recipes/revoluzer/meta.yaml
Labels: please review & merge

#46500 Falco update
  recipes/falco/meta.yaml
Labels: please review & merge

#46467 linux-aarch64 build for pybedtools
  recipes/pybedtools/meta.yaml
Labels: please review & merge

#46472 linux-aarch64 build for bgreat
  recipes/bgreat/meta.yaml
Labels: please review & merge

#46482 clustalw: add linux-aarch64 build
  recipes/clustalw/build.sh
  recipes/clustalw/config.guess
  recipes/clustalw/config.sub
  recipes/clustalw/meta.yaml
Labels: please review & merge

#46459 update kallisto: enable linux-aarch64 build
  recipes/kallisto/meta.yaml
Labels: please review & merge

#46505 Update Plink2 to Alpha 5.10 final (5 Jan)
  recipes/plink2/meta.yaml
Labels: please review & merge

#46361 bowtie: enable linux-aarch64 build
  recipes/bowtie/meta.yaml
Labels: please review & merge, aarch64

#46424 cutadapt: add linux-aarch64 build
  recipes/cutadapt/meta.yaml
Labels: please review & merge

#46517 bump revoluzer 0.1.6
  recipes/revoluzer/meta.yaml
Labels: please review & merge

#46436 fasttree: add linux-aarch64 build
  recipes/fasttree/meta.yaml
Labels: please review & merge, aarch64

#46513 update python-edlib: enable linux-aarch64 build
  recipes/python-edlib/meta.yaml
Labels: please review & merge

#46525 muscle: add linux-aarch64 build
  recipes/muscle/0001-Replace-zero-macro-with-memset_zero.patch
  recipes/muscle/0002-Move-va_start-va_end-out-of-critical-section.patch
  recipes/muscle/meta.yaml
  recipes/muscle/support-linux-aarch64.patch
Labels: please review & merge

#46359 hmmcopy: enable linux-aarch64 build
  recipes/hmmcopy/build.sh
  recipes/hmmcopy/meta.yaml
Labels: please review & merge, aarch64

#46388 linux-aarch64 build for alcor
  recipes/alcor/meta.yaml
Labels: please review & merge

#46362 linux-aarch64 build for ac
  recipes/ac/meta.yaml
Labels: please review & merge, aarch64

#46423 bowtie2: add linux-aarch64 build
  recipes/bowtie2/build.sh
  recipes/bowtie2/meta.yaml
Labels: please review & merge

#46569 update stringtie adding new platform
  recipes/stringtie/build.sh
  recipes/stringtie/meta.yaml
Labels: please review & merge

#46563 make linux-aarch64 build for age_metasv
  recipes/age-metasv/meta.yaml
Labels: please review & merge

#46243 Add srahunter/meta.yaml
  recipes/srahunter/meta.yaml
Labels: please review & merge

#46555 update star adding new platform
  recipes/star/build.sh
  recipes/star/meta.yaml
Labels: please review & merge

#46574 Updated ToulligQC to v2.5.3
  recipes/toulligqc/meta.yaml
Labels: please review & merge

#46606 Update pixelator to 0.16.2
  recipes/pixelator/LICENSE.txt
  recipes/pixelator/meta.yaml
Labels: please review & merge

#46596 update preseq adding new platform
  recipes/preseq/meta.yaml
Labels: please review & merge

#46604 linux-aarch64 build for bioawk
  recipes/bioawk/meta.yaml
Labels: please review & merge, aarch64

#46601 linux-aarch64 build for bfc
  recipes/bfc/meta.yaml
Labels: please review & merge, aarch64

#46600 linux-aarch64 build for Bcalm
  recipes/bcalm/meta.yaml
Labels: please review & merge, aarch64

#46599 update fq adding new platform
  recipes/fq/meta.yaml
Labels: please review & merge, aarch64

#46595 update gffread adding new platform
  recipes/gffread/meta.yaml
Labels: please review & merge, aarch64

#46592 linux-aarch64 build for aragorn
  recipes/aragorn/meta.yaml
Labels: please review & merge, aarch64

#46516 update bedgraphtobigwig with additional platform
  recipes/ucsc-bedgraphtobigwig/meta.yaml
  recipes/ucsc-bedgraphtobigwig/patch1.patch
Labels: please review & merge, aarch64

#46609 linux-aarch64 build for addrg
  recipes/addrg/meta.yaml
Labels: aarch64

#46620 Add linux-aarch64 build for seqkit
  recipes/seqkit/meta.yaml
Labels: aarch64

#46625 Update: Musgy - Fix issue with sed on macos m1
  recipes/mugsy/meta.yaml
Labels: please review & merge

#46543 Add splitcode recipe
  recipes/splitcode/build.sh
  recipes/splitcode/meta.yaml
Labels: please review & merge

#46540 Update agc to 3.1
  recipes/agc/meta.yaml
Labels: please review & merge

#46638 bump mitos
  recipes/mitos/mitos1/meta.yaml
Labels: please review & merge

#46619 Update Cenote-Taker3 v3.3.0
  recipes/cenote-taker3/meta.yaml
Labels: please review & merge

#46656 Update TREE-QMC to 3.0.0
  recipes/tree-qmc/build.sh
  recipes/tree-qmc/meta.yaml
Labels: please review & merge

#46610 linux-aarch64 build for 3seq
  recipes/3seq/meta.yaml
Labels: please review & merge, aarch64

#46633 linux-aarch64 build for abundancebin
  recipes/abundancebin/meta.yaml
Labels: please review & merge, aarch64

#46626 update ucsc-bedclip adding new platform
  build-fail-blacklist
  recipes/ucsc-bedclip/build.sh
  recipes/ucsc-bedclip/conda_build_config.yaml
  recipes/ucsc-bedclip/meta.yaml
  recipes/ucsc-bedclip/patch1.patch
Labels: please review & merge

#46659 Update ntsynt build
  recipes/ntsynt/meta.yaml
Labels: please review & merge

#46663 Update ntlink build
  recipes/ntlink/meta.yaml
Labels: please review & merge

#46689 Updated ToulligQc to v2.5.4
  recipes/toulligqc/meta.yaml
Labels: please review & merge

#46674 linux-aarch64 build for mappy
  recipes/mappy/meta.yaml
Labels: please review & merge, aarch64

#46673 inux-aarch64 build for altair-mf
  recipes/altair-mf/meta.yaml
Labels: please review & merge, aarch64

#46711 Update ampliconsuite
  recipes/ampliconsuite/meta.yaml
Labels: please review & merge

#46587 Add new package for genotyping reads
  recipes/handyreadgenotyper/meta.yaml
  recipes/handyreadgenotyper/setup.py
Labels: please review & merge

#46678 update taxor to version 0.1.3
  recipes/taxor/meta.yaml
Labels: please review & merge

#46703 Update hictk to v0.0.11
  recipes/hictk/conanfile.txt.patch
  recipes/hictk/meta.yaml
  recipes/hictk/run_test.sh
Labels: please review & merge

#46646 add linux-aarch64-alignoth
  recipes/alignoth/meta.yaml
Labels: please review & merge, aarch64

#46734 bamtools: add linux-aarch64 build
  recipes/bamtools/meta.yaml
Labels: please review & merge

#46730 seqtk: add linux-aarch64 build
  recipes/seqtk/meta.yaml
Labels: please review & merge

#46598 update umi_tools adding new platform
  recipes/umi_tools/meta.yaml
Labels: please review & merge, aarch64

#46686 update ucsc-bedclip
  recipes/ucsc-bedclip/build.sh
  recipes/ucsc-bedclip/meta.yaml
Labels: aarch64

#46658 Harpy 0.8.0 + recipe change
  recipes/harpy/meta.yaml
Labels: please review & merge

#46469 raxml: add linux-aarch64 build
  recipes/raxml/build.sh
  recipes/raxml/meta.yaml
Labels: please review & merge, aarch64

#46756 update from 0.2.0 to 0.3.0
  recipes/rsv-typer/meta.yaml
Labels: please review & merge

#46764 vcftools: add linux-aarch64 build
  recipes/vcftools/meta.yaml
Labels: please review & merge, aarch64

#46763 prodigal: add linux-aarch64 build
  recipes/prodigal/meta.yaml
Labels: please review & merge, aarch64

#46765 usher & ucsc-fatovcf: add linux-aarch64 build
  recipes/ucsc-fatovcf/build.sh
  recipes/ucsc-fatovcf/htmshell.patch
  recipes/ucsc-fatovcf/meta.yaml
  recipes/usher/meta.yaml
Labels: please review & merge, aarch64

#46672 linux-aarch64 build for allegro
  recipes/allegro/build.sh
  recipes/allegro/meta.yaml
Labels: please review & merge, aarch64

#46794 linux-aarch64 build for selam
  recipes/selam/meta.yaml
Labels: please review & merge, aarch64

#46806 version bump, dependency cleanup, snakemake>8 support
  recipes/monsda/meta.yaml
Labels: please review & merge

#46783 linux-aarch64 build for annonars
  recipes/annonars/meta.yaml
Labels: please review & merge, aarch64

#46768 Update hictkpy to v0.0.4
  recipes/hictkpy/CMakeLists.txt.patch
  recipes/hictkpy/build.sh
  recipes/hictkpy/conanfile.txt.patch
  recipes/hictkpy/meta.yaml
  recipes/hictkpy/pyproject.toml.patch
Labels: please review & merge

#46747 Add ntroot recipe
  recipes/ntroot/build.sh
  recipes/ntroot/meta.yaml
  recipes/ntroot/ntroot.patch
Labels: please review & merge

#46744 Add `gb-io` Python package
  recipes/gb-io/build.sh
  recipes/gb-io/meta.yaml
Labels: please review & merge

#46733 ViennaRNA: add linux-aarch64 build
  recipes/viennarna/meta.yaml
Labels: please review & merge, aarch64

#46840 Linux-aarch64 build for assembly-stats
  recipes/assembly-stats/meta.yaml
Labels: please review & merge, aarch64

#46785 linux-aarch64 build for anise_basil
  recipes/anise_basil/meta.yaml
Labels: please review & merge, aarch64

#46852 linux-aarch64 build for bamcmp
  recipes/bamcmp/meta.yaml
Labels: please review & merge, aarch64

#46849 linux-aarch64 build for balrog
  recipes/balrog/meta.yaml
Labels: please review & merge, aarch64

#46851 Linux-aarch64 build for aster
  recipes/aster/build.sh
  recipes/aster/meta.yaml
Labels: please review & merge, aarch64

#46850 Linux-aarch64 build for atac
  recipes/atac/build.sh
  recipes/atac/meta.yaml
Labels: please review & merge, aarch64

#46860 vsnp3 version 3.20
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#46814 Update assembly_finder to v0.6.0
  recipes/assembly_finder/meta.yaml
Labels: please review & merge

#46845 Update - clean dependencies for liger
  recipes/r-liger/meta.yaml
Labels: please review & merge

#46790 linux-aarch64 build for ancestry_hmm
  recipes/ancestry_hmm/meta.yaml
Labels: aarch64

#46808 last: add linux-aarch64 build
  recipes/last/build.sh
  recipes/last/meta.yaml
Labels: aarch64

#46736 freebayes: add linux-aarch64 build
  recipes/freebayes/meta.yaml
  recipes/vcflib/build.sh
  recipes/vcflib/meta.yaml
Labels: aarch64

#46869 Update STECFinder
  recipes/stecfinder/meta.yaml
Labels: please review & merge

#46877 linux-aarch64 build for bcftools-gtc2vcf-plugin
  recipes/bcftools-gtc2vcf-plugin/meta.yaml
Labels: please review & merge
