Repository bioconda/bioconda-recipes, pull requests merged in 2024-04, with the labels that each got.

#46838 Add rabbitqcplus
  recipes/rabbitqcplus/build.sh
  recipes/rabbitqcplus/meta.yaml
Labels: please review & merge

#46916 Update dexseq to reinstate htseq-count dependency
  recipes/bioconductor-dexseq/meta.yaml
Labels: please review & merge

#46922 Update cgatcore 0.6.16
  recipes/cgatcore/meta.yaml
Labels: please review & merge

#46485 prank: add linux-aarch64 build
  recipes/prank/LICENSE.md
  recipes/prank/meta.yaml
Labels: please review & merge, aarch64

#46854 linux-aarch64 build for gatk
  recipes/gatk/meta.yaml
Labels: aarch64

#46671 Update for amplicon_coverage_plot
  recipes/amplicon_coverage_plot/meta.yaml
Labels: please review & merge

#46629 linux-aarch64 build for angsd
  recipes/angsd/meta.yaml
Labels: please review & merge, aarch64

#46634 Update for amdirt
  recipes/amdirt/meta.yaml
Labels: please review & merge, aarch64

#46953 Update dinopy
  recipes/dinopy/meta.yaml
Labels: please review & merge

#46954 paml: add linux-aarch64 build
  recipes/paml/meta.yaml
Labels: please review & merge

#46948 Update to 5.7.1
  recipes/busco/0001-Set-conda-distribution.patch
  recipes/busco/meta.yaml
Labels: please review & merge

#46880 linux-aarch64 build for abpoa
  recipes/abpoa/meta.yaml
Labels: aarch64

#46964 Update cgat-apps 0.7.0
  build-fail-blacklist
  recipes/cgat-apps/meta.yaml
Labels: please review & merge

#46939 Update PhiSpy with fixed biopython version
  recipes/phispy/meta.yaml
Labels: please review & merge

#46940 Downgrade Philosopher for compatibility with FragPipe
  recipes/fragpipe/meta.yaml
Labels: please review & merge

#46844 Add physher recipe
  recipes/physher/build.sh
  recipes/physher/meta.yaml
Labels: please review & merge

#46803 megahit: add linux-aarch64 build
  recipes/megahit/linux-aarch64-support-pr-368.patch
  recipes/megahit/meta.yaml
Labels: please review & merge, aarch64

#46986 Add mtgrasp
  recipes/mtgrasp/build.sh
  recipes/mtgrasp/meta.yaml
Labels: please review & merge

#46993 Update graphembed v0.1.1
  recipes/graphembed/meta.yaml
Labels: please review & merge

#46784 Add argNorm recipe
  recipes/argnorm/meta.yaml
Labels: please review & merge

#47030 Update SeqKit to v2.8.1
  recipes/seqkit/meta.yaml
Labels: please review & merge

#47012 gofasta: add linux-aarch64 build
  recipes/gofasta/meta.yaml
Labels: please review & merge

#47055 kma: add linux-aarch64 build
  recipes/kma/meta.yaml
Labels: please review & merge

#47020 Update cgat-apps v0.7.2
  recipes/cgat-apps/meta.yaml
Labels: please review & merge

#47011 htseq: add linux-aarch64 build
  recipes/htseq/meta.yaml
Labels: please review & merge

#47060 tidyp: add linux-aarch64 build
  recipes/tidyp/build.sh
  recipes/tidyp/meta.yaml
Labels: please review & merge

#47053 ucsc-fatotwobit: add linux-aarch64 build
  recipes/ucsc-fatotwobit/build.sh
  recipes/ucsc-fatotwobit/htmshell.patch
  recipes/ucsc-fatotwobit/meta.yaml
Labels: please review & merge

#47059 gseapy: add linux-aarch64 build
  recipes/gseapy/meta.yaml
Labels: please review & merge

#47076 Update r-dimsum to v1.3.1
  recipes/r-dimsum/meta.yaml
Labels: please review & merge

#47057 ncbi-ngs-sdk: add linux-aarch64 build
  recipes/ncbi-ngs-sdk/meta.yaml
Labels: please review & merge

#47040 Severus 1.0
  recipes/severus/meta.yaml
Labels: please review & merge

#47068 Update ntedit to 2.0.0
  recipes/ntedit/build.sh
  recipes/ntedit/meta.yaml
Labels: please review & merge

#47081 BUG specify pronto version for argnorm
  recipes/argnorm/meta.yaml
Labels: please review & merge

#47092 gmap: add linux-aarch64 build
  recipes/gmap/build.sh
  recipes/gmap/meta.yaml
Labels: please review & merge

#47091 csvtk: add linux-aarch64 build
  recipes/csvtk/meta.yaml
Labels: please review & merge

#47089 whatshap: add linux-aarch64 build
  recipes/whatshap/meta.yaml
Labels: please review & merge

#47090 glimmerhmm: add linux-aarch64 build
  recipes/glimmerhmm/meta.yaml
Labels: please review & merge, aarch64

#47065 Add MicroView
  recipes/microview/meta.yaml
Labels: please review & merge

#47096 ucsc-wigtobigwig: add linux-aarch64 build
  recipes/ucsc-wigtobigwig/htmshell.patch
  recipes/ucsc-wigtobigwig/meta.yaml
Labels: please review & merge, aarch64

#47105 Added jaeger-bio 1.1.251
  recipes/jaeger-bio/meta.yaml
Labels: please review & merge

#47107 Add isonform
  recipes/isonform/meta.yaml
Labels: WIP

#47050 Add recipe for pycomo
  recipes/pycomo/meta.yaml
Labels: please review & merge

#47125 Add galitime recipe
  recipes/galitime/meta.yaml
Labels: please review & merge

#46966 Add tntblast-2.4
  recipes/tntblast/2.4/build.sh
  recipes/tntblast/2.4/meta.yaml
Labels: please review & merge

#47006 Update rsv-typer recipe
  recipes/rsv-typer/meta.yaml
Labels: please review & merge

#47154 cd-hit: add linux-aarch64 build
  recipes/cd-hit/meta.yaml
Labels: please review & merge

#47166 perl-algorithm-cluster: add linux-aarch64 build
  recipes/perl-algorithm-cluster/meta.yaml
Labels: please review & merge

#47163 gadem: add linux-aarch64 build
  recipes/gadem/meta.yaml
Labels: please review & merge

#47162 prosampler: add linux-aarch64 build
  build-fail-blacklist
  recipes/prosampler/build.sh
  recipes/prosampler/meta.yaml
Labels: please review & merge

#47160 weeder: add linux-aarch64 build
  recipes/weeder/meta.yaml
Labels: please review & merge

#47159 homer: add linux-aarch64 build
  recipes/homer/meta.yaml
Labels: please review & merge

#47157 dinamo: add linux-aarch64 build
  recipes/dinamo/meta.yaml
Labels: please review & merge

#47139 Update Cenote-Taker3 v3.3.1
  recipes/cenote-taker3/meta.yaml
Labels: please review & merge

#47022 Add ms2rescore-rs recipe
  recipes/ms2rescore-rs/build.sh
  recipes/ms2rescore-rs/meta.yaml
Labels: please review & merge

#46915 Update Maaslin2 version to use latest from BioC
  build-fail-blacklist
  recipes/maaslin2/meta.yaml
Labels: please review & merge

#46313 Add KPop
  recipes/kpop/build.sh
  recipes/kpop/meta.yaml
Labels: please review & merge

#47203 Update ntroot to 1.0.1
  recipes/ntroot/build.sh
  recipes/ntroot/meta.yaml
  recipes/ntroot/ntroot.patch
Labels: please review & merge

#47184 pairix: add linux-aarch64 build
  recipes/pairix/meta.yaml
Labels: please review & merge

#47183 hyphy: add linux-aarch64 build
  recipes/hyphy/build.sh
  recipes/hyphy/meta.yaml
Labels: please review & merge

#47161 xxmotif: add linux-aarch64 build
  build-fail-blacklist
  recipes/xxmotif/conda_build_config.yaml
  recipes/xxmotif/fix-build.patch
  recipes/xxmotif/meta.yaml
Labels: please review & merge, aarch64

#47121 add localhgt
  recipes/localhgt/build.sh
  recipes/localhgt/meta.yaml
Labels: please review & merge

#47064 Add recipe for igfinder
  recipes/igfinder/build.sh
  recipes/igfinder/meta.yaml
Labels: please review & merge

#47047 Add primers recipe
  recipes/primers/0001-directly-write-requirements-in-setup.py.patch
  recipes/primers/meta.yaml
Labels: please review & merge

#46903 add dmtools
  recipes/dmtools/build.sh
  recipes/dmtools/conda_build_config.yaml
  recipes/dmtools/meta.yaml
Labels: please review & merge

#46804 iow: add linux-aarch64 build
  recipes/iow/meta.yaml
Labels: please review & merge, aarch64

#46415 Add seqsizzle
  recipes/seqsizzle/LICENSE.md
  recipes/seqsizzle/build.sh
  recipes/seqsizzle/meta.yaml
Labels: please review & merge

#46992 Added HelitronScanner
  recipes/helitronscanner/HelitronScanner.sh
  recipes/helitronscanner/build.sh
  recipes/helitronscanner/meta.yaml
Labels: please review & merge

#47200 fix clippy install
  recipes/clippy/meta.yaml
Labels: please review & merge

#47240 bioconda-repodata-patches: Bump for new htslib and libdeflate releases
  recipes/bioconda-repodata-patches/gen_patch_json.py
  recipes/bioconda-repodata-patches/meta.yaml
Labels: please review & merge

#47227 sorted_nearest: add linux-aarch64 build
  recipes/sorted_nearest/meta.yaml
Labels: please review & merge

#47254 ucsc-gtftogenepred: add linux-aarch64 build
  recipes/ucsc-gtftogenepred/htmshell.patch
  recipes/ucsc-gtftogenepred/meta.yaml
Labels: please review & merge

#47251 pyrle: add linux-aarch64 build
  recipes/pyrle/meta.yaml
Labels: please review & merge

#47252 mawk: add linux-aarch64 build
  recipes/mawk/meta.yaml
Labels: please review & merge

#47253 grabix: add linux-aarch64 build
  recipes/grabix/meta.yaml
Labels: please review & merge

#47245 Add Canopy
  recipes/canopy/build.sh
  recipes/canopy/meta.yaml
Labels: please review & merge

#47230 seqfu: add linux-aarch64 build
  recipes/seqfu/build.sh
  recipes/seqfu/meta.yaml
Labels: please review & merge

#47259 staden_io_lib: add linux-aarch64 build
  recipes/staden_io_lib/meta.yaml
Labels: please review & merge

#47239 Update ntedit build
  recipes/ntedit/meta.yaml
Labels: please review & merge

#47291 Update ntroot build
  recipes/ntroot/meta.yaml
Labels: please review & merge

#46970 Added TIR-Learner
  recipes/tir-learner/build.sh
  recipes/tir-learner/meta.yaml
Labels: please review & merge

#47260 libmaus2: add linux-aarch64 build
  recipes/libmaus2/build.sh
  recipes/libmaus2/meta.yaml
Labels: please review & merge

#47258 delly: add linux-aarch64 build
  recipes/delly/build.sh
  recipes/delly/meta.yaml
Labels: please review & merge

#47289 Update hictkpy to v0.0.5
  recipes/hictkpy/conanfile.txt.patch
  recipes/hictkpy/meta.yaml
Labels: please review & merge

#47267 Update hictk to v0.0.12 and enable linux-aarch64 builds
  recipes/hictk/conanfile.txt.patch
  recipes/hictk/meta.yaml
Labels: please review & merge

#47262 Update malva requirements and fix compilation issues
  recipes/malva/build_failure.linux-64.yaml
  recipes/malva/malva.CMakeList.patch
  recipes/malva/meta.yaml
Labels: please review & merge

#47301 Update salty to 1.0.6
  recipes/salty/meta.yaml
Labels: please review & merge

#47287 Update mess recipe to 0.8.0
  recipes/mess/meta.yaml
Labels: please review & merge

#47320 miniasm: add linux-aarch64 build
  recipes/miniasm/meta.yaml
Labels: please review & merge

#47303 mummer: add linux-aarch64 build
  recipes/mummer/meta.yaml
Labels: please review & merge

#47300 Update tcdemux pinning
  recipes/tcdemux/meta.yaml
Labels: please review & merge

#47304 ucsc-bedtobigbed: add linux-aarch64 build
  recipes/ucsc-bedtobigbed/htmshell.patch
  recipes/ucsc-bedtobigbed/meta.yaml
Labels: please review & merge

#47305 intarna: add linux-aarch64 build
  recipes/intarna/meta.yaml
Labels: please review & merge

#47306 ucsc-twobitinfo: add linux-aarch64 build
  recipes/ucsc-twobitinfo/htmshell.patch
  recipes/ucsc-twobitinfo/meta.yaml
Labels: please review & merge

#47307 pyfastx: add linux-aarch64 build
  recipes/pyfastx/meta.yaml
Labels: please review & merge

#47308 umis: add linux-aarch64 build
  recipes/umis/meta.yaml
Labels: please review & merge

#47310 atropos: add linux-aarch64 build
  recipes/atropos/meta.yaml
Labels: please review & merge

#47311 pytabix: add linux-aarch64 build
  recipes/pytabix/meta.yaml
Labels: please review & merge

#47312 vcfanno: add linux-aarch64 build
  recipes/vcfanno/meta.yaml
Labels: please review & merge

#47316 crispresso2: add linux-aarch64 build
  recipes/crispresso2/meta.yaml
Labels: please review & merge

#47317 pb-falcon & python-msgpack: add linux-aarch64 build
  recipes/pb-falcon/meta.yaml
  recipes/python-msgpack/meta.yaml
Labels: please review & merge

#47318 taxonkit: add linux-aarch64 build
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#47319 pbgzip: add linux-aarch64 build
  recipes/pbgzip/build.sh
  recipes/pbgzip/meta.yaml
Labels: please review & merge

#47313 deeptoolsintervals: add linux-aarch64 build
  recipes/deeptoolsintervals/meta.yaml
Labels: please review & merge

#47226 Update description for localhgt in the same version
  recipes/localhgt/meta.yaml
Labels: please review & merge

#46802 rust-bio-tools & starcode: add linux-aarch64 build
  recipes/rust-bio-tools/meta.yaml
  recipes/starcode/meta.yaml
Labels: please review & merge, aarch64

#47215 Add recipe for rnamining package
  recipes/rnamining/meta.yaml
Labels: please review & merge

#47294 Update PhyloAcc recipe
  recipes/phyloacc/build.sh
  recipes/phyloacc/meta.yaml
Labels: please review & merge

#47330 Update localhgt v1.0.1
  recipes/localhgt/meta.yaml
Labels: please review & merge

#47271 fix: Nextclade sha256sum for 3.3.1 osx_64
  recipes/nextclade/meta.yaml
Labels: please review & merge

#47331 ivar: add linux-aarch64 build
  recipes/ivar/build.sh
  recipes/ivar/meta.yaml
Labels: please review & merge

#47343 ucsc-liftover: add linux-aarch64 build
  recipes/ucsc-liftover/build.sh
  recipes/ucsc-liftover/htmshell.patch
  recipes/ucsc-liftover/meta.yaml
Labels: please review & merge

#47341 primer3-py: add linux-aarch64 build
  recipes/primer3-py/meta.yaml
Labels: please review & merge

#47338 samblaster: add linux-aarch64 build
  recipes/samblaster/build.sh
  recipes/samblaster/meta.yaml
Labels: please review & merge

#47333 alfred: add linux-aarch64 build
  recipes/alfred/build.sh
  recipes/alfred/meta.yaml
Labels: please review & merge

#47337 ucsc-genepredtobed: add linux-aarch64 build
  recipes/ucsc-genepredtobed/build.sh
  recipes/ucsc-genepredtobed/htmshell.patch
  recipes/ucsc-genepredtobed/meta.yaml
Labels: please review & merge

#47342 exonerate: add linux-aarch64 build
  recipes/exonerate/build.sh
  recipes/exonerate/conda_build_config.yaml
  recipes/exonerate/meta.yaml
Labels: please review & merge

#47282 Add beacon2-import and beacon2- search tools
  recipes/beacon2-import/LICENSE
  recipes/beacon2-import/meta.yaml
Labels: please review & merge

#47367 Update sdeper to version 1.1.0
  recipes/sdeper/LICENSE
  recipes/sdeper/meta.yaml
Labels: please review & merge

#47354 goleft: add linux-aarch64 build
  recipes/goleft/build.sh
  recipes/goleft/meta.yaml
Labels: please review & merge

#47378 Add giatools recipe
  recipes/giatools/meta.yaml
Labels: please review & merge

#47377 Updated ToulligQc to v2.5.5
  recipes/toulligqc/meta.yaml
Labels: please review & merge

#47374 Update snakemake minimum version for smart-open
  recipes/snakemake/meta.yaml
Labels: please review & merge

#46956 infernal: add linux-aarch64 build
  recipes/infernal/build.sh
  recipes/infernal/meta.yaml
Labels: please review & merge, aarch64

#47409 kmc: add linux-aarch64 build
  recipes/kmc/meta.yaml
Labels: please review & merge

#47395 cdbtools: add linux-aarch64 build
  recipes/cdbtools/build.sh
  recipes/cdbtools/meta.yaml
Labels: please review & merge

#47398 trimal: add linux-aarch64 build
  recipes/trimal/build.sh
  recipes/trimal/meta.yaml
Labels: please review & merge

#47394 nextalign: add linux-aarch64 build
  recipes/nextalign/meta.yaml
  recipes/nextalign/run_test.sh
Labels: please review & merge

#47399 illumina-interop: add linux-aarch64 build
  recipes/illumina-interop/build.sh
  recipes/illumina-interop/meta.yaml
Labels: please review & merge

#47384 Update shiver: fix non-fatal absence of HXB2 sequence file
  recipes/shiver/build.sh
  recipes/shiver/meta.yaml
Labels: please review & merge

#47405 vt: add linux-aarch64 build
  recipes/vt/meta.yaml
Labels: please review & merge

#47406 cmappy: add linux-aarch64 build
  recipes/cmappy/meta.yaml
Labels: please review & merge

#47408 bindash: add linux-aarch64 build
  recipes/bindash/build.sh
  recipes/bindash/meta.yaml
Labels: please review & merge

#47410 popdel: add linux-aarch64 build
  recipes/popdel/build.sh
  recipes/popdel/meta.yaml
Labels: please review & merge

#47411 kaiju: add linux-aarch64 build
  recipes/kaiju/build.sh
  recipes/kaiju/meta.yaml
Labels: please review & merge

#47403 update phynteny v0.1.13
  recipes/phynteny/meta.yaml
Labels: please review & merge

#47412 groot: add linux-aarch64 build
  build-fail-blacklist
  recipes/groot/build.sh
  recipes/groot/meta.yaml
Labels: please review & merge

#47401 epic2: add linux-aarch64 build
  recipes/epic2/meta.yaml
Labels: please review & merge

#47436 lofreq: add linux-aarch64 build
  recipes/lofreq/build.sh
  recipes/lofreq/meta.yaml
Labels: please review & merge

#47432 megalodon: add linux-aarch64 build
  recipes/megalodon/meta.yaml
Labels: please review & merge

#47435 comet-ms: add linux-aarch64 build
  recipes/comet-ms/build.sh
  recipes/comet-ms/meta.yaml
Labels: aarch64

#46434 iqtree: add linux-aarch64 build
  recipes/iqtree/build.sh
  recipes/iqtree/meta.yaml
Labels: aarch64

#46955 varlociraptor: add linux-aarch64 build
  recipes/varlociraptor/meta.yaml
Labels: please review & merge, aarch64

#47446 Update gottcha2 to v2.1.8.6
  recipes/gottcha2/meta.yaml
Labels: please review & merge

#47414 Update percolator to version 3.6.5
  build-fail-blacklist
  recipes/percolator/build.sh
  recipes/percolator/meta.yaml
Labels: please review & merge

#47453 add recipe for camlhmp
  recipes/camlhmp/meta.yaml
Labels: please review & merge

#47474 Updated ToulligQc to v2.5.6
  recipes/toulligqc/meta.yaml
Labels: please review & merge

#47456 pindel: add linux-aarch64 build
  recipes/pindel/meta.yaml
Labels: please review & merge

#47454 longshot: add linux-aarch64 build
  recipes/longshot/meta.yaml
  recipes/longshot/update-rust-htslib.patch
Labels: please review & merge

#46360 gemini: enable linux-aarch64 build
  recipes/gemini/meta.yaml
Labels: please review & merge, aarch64

#47385 Update Sequenoscope: Rebuild version 0.0.5 with Updated Dependencies
  recipes/sequenoscope/meta.yaml
Labels: please review & merge
