Repository bioconda/bioconda-recipes, pull requests merged in 2024-12, with the labels that each got.

#52495 Update hictkpy v1.1.0
  recipes/hictkpy/conanfile.py.patch
  recipes/hictkpy/meta.yaml
Labels: please review & merge

#46797 linux-aarch64 build for Baitfisher
  recipes/baitfisher/meta.yaml
Labels: aarch64

#52501 Update gambit to 1.1.0
  recipes/gambit/meta.yaml
Labels: please review & merge

#52518 gambit: add aarch64/arm64 builds
  recipes/gambit/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52482 strainge: add aarch64/arm64 builds
  recipes/strainge/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52479 gubbins: add aarch64/arm64 builds
  recipes/gubbins/build.sh
  recipes/gubbins/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52527 Update to v0.0.1b2
  recipes/quota_anchor/build.sh
  recipes/quota_anchor/meta.yaml
Labels: please review & merge

#52530 Add recipe for `grz-cli`
  recipes/grz-cli/meta.yaml
Labels: please review & merge

#52534 Update seqscreen to v4.4
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#52535 Update quota_anchor to v0.0.1rc
  recipes/quota_anchor/meta.yaml
Labels: please review & merge

#52511 Update cadd-scripts to v1.6.1
  recipes/cadd-scripts/v1.6/build.sh
  recipes/cadd-scripts/v1.6/cadd-install-wrapper.sh
  recipes/cadd-scripts/v1.6/cadd-wrapper.sh
  recipes/cadd-scripts/v1.6/meta.yaml
Labels: please review & merge

#52545 ms-entropy: add aarch64/arm64 builds
  recipes/ms-entropy/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52547 rotate: add aarch64/arm64 builds
  recipes/rotate/build.sh
  recipes/rotate/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52544 cramino: add linux-aarch64 build
  recipes/cramino/build.sh
  recipes/cramino/meta.yaml
Labels: please review & merge, aarch64

#52566 Update pybigwig to v0.3.23
  recipes/pybigwig/build.sh
  recipes/pybigwig/meta.yaml
Labels: osx-arm64

#52567 alignlib-lite: add arm64 build
  recipes/alignlib-lite/meta.yaml
Labels: osx-arm64

#52373 Fix MashMap v3.1.3 build.
  recipes/mashmap/build.sh
  recipes/mashmap/conda_build_config.yaml
  recipes/mashmap/meta.yaml
Labels: please review & merge

#52571 Fix gambit Python version
  recipes/gambit/meta.yaml
Labels: please review & merge

#52557 Samtools 0.1.19 and 0.1.18 - linux-aarch64 and osx-arm64 (0.1.18) support
  recipes/samtools/0.1.18/build.sh
  recipes/samtools/0.1.18/meta.yaml
  recipes/samtools/0.1.19/build.sh
  recipes/samtools/0.1.19/meta.yaml
Labels: please review & merge

#46207 Build ncbi-amrfinderplus for linux-aarch64
  recipes/ncbi-amrfinderplus/build.sh
  recipes/ncbi-amrfinderplus/meta.yaml
Labels: please review & merge, aarch64

#52582 Add predictosaurus recipe
  recipes/predictosaurus/build.sh
  recipes/predictosaurus/meta.yaml
Labels: please review & merge

#52579 Update ppanggolin
  recipes/ppanggolin/meta.yaml
Labels: please review & merge

#52556 Mosdepth: add linux-aarch64 support.
  recipes/mosdepth/build.sh
  recipes/mosdepth/meta.yaml
Labels: please review & merge

#52576 perl-bio-samtools: bump samtools minor version and add linux-aarch64 and osx-arm64
  recipes/perl-bio-samtools/build-pl.patch
  recipes/perl-bio-samtools/build.sh
  recipes/perl-bio-samtools/meta.yaml
  recipes/samtools/0.1.19/build.sh
  recipes/samtools/0.1.19/meta.yaml
Labels: please review & merge

#52517 Manta: add linux-aarch64 builds
  recipes/manta/boost-shlibs.patch
  recipes/manta/build.sh
  recipes/manta/meta.yaml
Labels: please review & merge

#52551 Bwa-mem2 linux aarch64 and re-trying osx-64
  recipes/bwa-mem2/build.sh
  recipes/bwa-mem2/conda_build_config.yaml
  recipes/bwa-mem2/meta.yaml
  recipes/bwa-mem2/simde.patch
Labels: please review & merge

#52601 Update meta.yaml
  recipes/busco/meta.yaml
Labels: please review & merge

#52395 Update: Pplacer osx 1.1.alpha17
  recipes/pplacer/1.1.alpha17/build.sh
  recipes/pplacer/1.1.alpha17/meta.yaml
Labels: please review & merge

#52563 Update: TIPP Version 1.2.0 Released
  recipes/tipp/build.sh
  recipes/tipp/meta.yaml
Labels: please review & merge

#52562 dysgu build for osx x64
  recipes/dysgu/build.sh
  recipes/dysgu/meta.yaml
Labels: please review & merge

#52602 Update earlgrey `build.sh`
  recipes/earlgrey/build.sh
  recipes/earlgrey/meta.yaml
Labels: please review & merge

#52606 Add recipe for `pyskani` Python package
  recipes/pyskani/meta.yaml
Labels: please review & merge

#52621 consan, tmalign, sap: add linux-aarch64, and osx-arm64 where possible
  recipes/consan/meta.yaml
  recipes/sap/build.sh
  recipes/sap/meta.yaml
  recipes/tmalign/meta.yaml
Labels: please review & merge

#52409 Add recipe for OptiLCMS
  recipes/optilcms/meta.yaml
Labels: please review & merge

#52644 Update Tesorter - replace blast by rmblast
  recipes/tesorter/meta.yaml
Labels: please review & merge

#52643 Update ltr_retriever - unpin repeatmasker pin <4.1.5
  recipes/ltr_retriever/meta.yaml
Labels: please review & merge

#52635 Update varifier to 0.4.0
  recipes/varifier/meta.yaml
Labels: please review & merge

#52624 Update ANARCI to the latest version
  recipes/anarci/meta.yaml
Labels: please review & merge

#52649 gzrt: add linuxaarch64 builds
  recipes/gzrt/build.sh
  recipes/gzrt/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52648 fc: add linux-aarch64 build
  recipes/fc/build.sh
  recipes/fc/meta.yaml
Labels: please review & merge, aarch64

#52645 nordic: add aarch64/arm64 builds
  recipes/nordic/build.sh
  recipes/nordic/build_failure.linux-64.yaml
  recipes/nordic/build_failure.osx-64.yaml
  recipes/nordic/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52642 jarvis3: add aarch64/arm64 build
  recipes/jarvis3/build.sh
  recipes/jarvis3/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52636 locityper: add linux-aarch64 build
  recipes/locityper/meta.yaml
Labels: please review & merge, aarch64

#52632 phylip: remove from blacklist and enable linux-aarch64
  build-fail-blacklist
  recipes/phylip/build.sh
  recipes/phylip/externs.patch
  recipes/phylip/meta.yaml
Labels: please review & merge

#52627 probcons, probconsrna: Add linux-aarch64, osx-arm64, remove probcons from build blacklist
  build-fail-blacklist
  recipes/probcons/build.sh
  recipes/probcons/file.patch
  recipes/probcons/meta.yaml
  recipes/probconsrna/conda_build_config.yaml
  recipes/probconsrna/meta.yaml
Labels: please review & merge

#52668 Update voyager
  recipes/voyager/build.sh
  recipes/voyager/meta.yaml
  recipes/voyager/run_test.sh
Labels: please review & merge

#52675 Add opticlust
  recipes/opticlust/meta.yaml
Labels: please review & merge

#52680 emu-pca: add aarch64/arm64 builds
  recipes/emu-pca/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52650 Add mmft 0.2.1
  recipes/mmft/build.sh
  recipes/mmft/meta.yaml
Labels: please review & merge

#52688 Update augur to 27.0.0
  recipes/augur/meta.yaml
Labels: please review & merge

#52691 Build mdust on osx
  recipes/mdust/0001-Makefile.patch
  recipes/mdust/build.sh
  recipes/mdust/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#51972 add files for equirep
  recipes/equirep/build.sh
  recipes/equirep/meta.yaml
Labels: please review & merge

#52697 blast-legacy: add aarch64/arm64 builds
  recipes/blast-legacy/2.2.26/build.sh
  recipes/blast-legacy/2.2.26/makedis.patch
  recipes/blast-legacy/2.2.26/meta.yaml
Labels: aarch64, osx-arm64

#52699 Build poa on osx
  recipes/poa/build.sh
  recipes/poa/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#52701 glimmerhmm: add arm64 build
  recipes/glimmerhmm/0001-sources-makefile.patch
  recipes/glimmerhmm/0002-train-makefile.patch
  recipes/glimmerhmm/build.sh
  recipes/glimmerhmm/build_failure.osx-64.yaml
  recipes/glimmerhmm/meta.yaml
Labels: osx-arm64

#52718 Update subread to v2.0.8 and enable arm64 build
  recipes/subread/0001-macOS-Makefile.patch
  recipes/subread/0002-longread-Makefile.patch
  recipes/subread/0003-Linux-Makefile.patch
  recipes/subread/0004-macOS-sse.patch
  recipes/subread/build.sh
  recipes/subread/meta.yaml
Labels: osx-arm64

#52726 Add `pseqsid`
  recipes/pseqsid/build.sh
  recipes/pseqsid/meta.yaml
Labels: please review & merge

#52722 Update Saccharis
  recipes/saccharis/meta.yaml
Labels: please review & merge

#52728 unitig-caller: add aarch64/arm64 build
  recipes/unitig-caller/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52698 Update to version 1.28.0
  recipes/bioconductor-mpra/meta.yaml
Labels: please review & merge

#52745 khmer: enable linux-aarch64 and osx-arm64 support
  recipes/khmer/0002-remove-m64.patch
  recipes/khmer/meta.yaml
Labels: please review & merge

#52734 extract-sv-reads: add linux-aarch64 build
  recipes/extract-sv-reads/build.sh
  recipes/extract-sv-reads/meta.yaml
Labels: please review & merge, aarch64

#52730 msisensor: add linux-aarch64 build
  recipes/msisensor/build.sh
  recipes/msisensor/meta.yaml
Labels: please review & merge, aarch64

#52674 porechop_abi: Add linux-aarch64 (works locally), osx-arm64 (test in CI)
  recipes/porechop_abi/build.sh
  recipes/porechop_abi/meta.yaml
Labels: please review & merge

#52731 simlord: add aarch64/arm64 builds
  recipes/simlord/build_failure.linux-64.yaml
  recipes/simlord/build_failure.osx-64.yaml
  recipes/simlord/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52751 Update ampliconsuite
  recipes/ampliconsuite/meta.yaml
Labels: please review & merge

#52775 new ectyperv2.0.0 recipe
  recipes/ectyper/meta.yaml
Labels: please review & merge

#52780 lrez: add aarch64/arm64 builds
  recipes/lrez/lrez-aarch64.patch
  recipes/lrez/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52777 Add bindashtree
  recipes/bindashtree/build.sh
  recipes/bindashtree/meta.yaml
Labels: please review & merge

#52769 Update : (harpy) add dep to environment
  recipes/harpy/meta.yaml
Labels: please review & merge

#52600 Adding superintervals v0.2.3
  recipes/superintervals/meta.yaml
Labels: please review & merge

#52747 Update recipe for bioconductor-minfi
  recipes/bioconductor-minfi/meta.yaml
Labels: please review & merge

#52758 deepfplearn: bump keras
  recipes/deepfplearn/meta.yaml
Labels: please review & merge

#52791 Update Saccharis
  recipes/saccharis/meta.yaml
Labels: please review & merge

#52782 Add a recipe for PopIns2
  recipes/popins2/build.sh
  recipes/popins2/meta.yaml
  recipes/popins2/popins2.patch
Labels: please review & merge, aarch64, osx-arm64

#52793 Rebuild stringtie on osx
  recipes/stringtie/build.sh
  recipes/stringtie/meta.yaml
  recipes/stringtie/patch
Labels: MacOS related, osx-arm64

#52798 Update gsearch v0.2.3
  recipes/gsearch/build.sh
  recipes/gsearch/meta.yaml
Labels: please review & merge

#52807 Update genome_updater to 0.6.4
  recipes/genome_updater/meta.yaml
Labels: please review & merge

#52787 Add recipe for softsv
  recipes/softsv/build.sh
  recipes/softsv/meta.yaml
  recipes/softsv/softsv.patch
Labels: please review & merge, aarch64, osx-arm64

#52800 add paf2chain
  recipes/paf2chain/build.sh
  recipes/paf2chain/meta.yaml
Labels: please review & merge

#52816 purge_dups: add aarch64/arm64 builds
  recipes/purge_dups/0001-makefile.patch
  recipes/purge_dups/build.sh
  recipes/purge_dups/makefile.patch
  recipes/purge_dups/meta.yaml
Labels: aarch64, osx-arm64

#52814 Add seshat
  recipes/seshat/meta.yaml
Labels: please review & merge

#52817 Add recipe for smcpp
  recipes/smcpp/build.sh
  recipes/smcpp/conda_build_config.yaml
  recipes/smcpp/meta.yaml
  recipes/smcpp/run_test.sh
Labels: please review & merge, aarch64

#52833 selene-sdk: update dependencies for 0.6.0 release
  recipes/selene-sdk/meta.yaml
Labels: please review & merge

#52840 Patch MHCflurry dependencies and bump build
  recipes/mhcflurry/meta.yaml
Labels: please review & merge

#52854 Add a recipe for MCScanX
  recipes/mcscanx/.gitattributes
  recipes/mcscanx/build.sh
  recipes/mcscanx/makefile.patch
  recipes/mcscanx/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52851 Update trycycler
  recipes/trycycler/meta.yaml
Labels: please review & merge

#52823 mrbayes: add aarch64/arm64 builds
  recipes/beagle-lib/3.1.2/build.sh
  recipes/beagle-lib/3.1.2/meta.yaml
  recipes/mrbayes/build.sh
  recipes/mrbayes/config.guess
  recipes/mrbayes/config.sub
  recipes/mrbayes/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52863 Update canu to v2.3
  recipes/canu/arm_hwcap.patch
  recipes/canu/build.sh
  recipes/canu/fewreads.patch
  recipes/canu/meta.yaml
Labels: aarch64, osx-arm64

#52820 Add echidna package to bioconda. See https://pypi.org/project/sc-e…
  recipes/echidna/meta.yaml
Labels: please review & merge

#52801 add chain2paf
  recipes/chain2paf/meta.yaml
Labels: please review & merge

#52870 Update gzrt to v0.9.1
  recipes/gzrt/0001-Makefile.patch
  recipes/gzrt/build.sh
  recipes/gzrt/meta.yaml
Labels: osx-arm64

#52873 NECAT: add arm64 builds
  recipes/necat/build.sh
  recipes/necat/meta.yaml
  recipes/necat/simple_align.patch
Labels: osx-arm64

#52733 cortexpy: add aarch64/arm64 builds
  recipes/cortexpy/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52875 seqsizzle: add aarch64/arm64 builds
  recipes/seqsizzle/build.sh
  recipes/seqsizzle/meta.yaml
Labels: aarch64, osx-arm64

#52881 Add a recipe for SVseq2
  recipes/svseq2/.gitattributes
  recipes/svseq2/build.sh
  recipes/svseq2/meta.yaml
  recipes/svseq2/svseq2.patch
Labels: please review & merge, aarch64, osx-arm64

#52891 Try specific megahits for Linux and OSX
  recipes/captus/meta.yaml
Labels: please review & merge

#52899 Update vConTACT3
  recipes/vcontact3/meta.yaml
Labels: please review & merge

#52913 update gzrt
  recipes/gzrt/build.sh
  recipes/gzrt/meta.yaml
Labels: please review & merge

#52920 ECTyper v2.0.0 build #1 now with fixed automatic database init
  recipes/ectyper/meta.yaml
  recipes/ectyper/post-link.sh
Labels: please review & merge

#52914 Add recipe for Tinker 8.11.3
  recipes/tinker/build.sh
  recipes/tinker/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52927 Update midsv
  recipes/midsv/meta.yaml
Labels: please review & merge

#52916 Add biox v1.0.0 - A universal biological sequence compressor
  recipes/biox/meta.yaml
Labels: please review & merge

#52879 add unicore recipe
  recipes/unicore/build.sh
  recipes/unicore/meta.yaml
Labels: please review & merge

#52855 Add novae package
  recipes/novae/meta.yaml
Labels: please review & merge

#52937 Update PanTools to v4.3.2
  recipes/pantools/meta.yaml
Labels: please review & merge

#52936 add recipe for pymethylation_utils pypi package
  recipes/pymethylation_utils/meta.yaml
Labels: please review & merge

#52931 AllHIC: Update to v0.9.14
  recipes/allhic/meta.yaml
Labels: please review & merge

#52930 MCScanX: Update to v1.0.0
  recipes/mcscanx/makefile.patch
  recipes/mcscanx/meta.yaml
Labels: please review & merge

#52941 Add `pycoverm`
  recipes/pycoverm/build.sh
  recipes/pycoverm/meta.yaml
  recipes/pycoverm/run_test.py
  recipes/pycoverm/test.bam
Labels: please review & merge

#52906 Bump bioconda-repodata-patches for new libdeflate release
  recipes/bioconda-repodata-patches/gen_patch_json.py
  recipes/bioconda-repodata-patches/meta.yaml
Labels: please review & merge

#52945 Add recipe for stripepy-hic
  recipes/stripepy-hic/meta.yaml
  recipes/stripepy-hic/run_test.sh
Labels: please review & merge

#52960 phasius: Update to 0.2.0 and add linux-aarch64 build
  recipes/phasius/build.sh
  recipes/phasius/meta.yaml
Labels: aarch64

#52962 unicore: add aarch64/arm64 builds
  recipes/unicore/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#52968 Updated TIPP
  recipes/tipp/build.sh
  recipes/tipp/meta.yaml
Labels: please review & merge

#52967 ghostx: add aarch64/arm64 builds
  build-fail-blacklist
  recipes/ghostx/build.sh
  recipes/ghostx/ghostx-makefile.patch
  recipes/ghostx/meta.yaml
Labels: aarch64, osx-arm64

#48803 pylibseq: add linux-aarch64 build
  recipes/pylibseq/meta.yaml
Labels: aarch64

#52973 Add `pdb2fasta`
  recipes/pdb2fasta/build.sh
  recipes/pdb2fasta/meta.yaml
  recipes/pdb2fasta/pdb2fasta.patch
Labels: please review & merge

#52980 Update `FusionInspector` to 2.10.0
  recipes/fusion-inspector/meta.yaml
Labels: please review & merge

#52963 Add a recipe for nanopack.
  recipes/nanopack/meta.yaml
Labels: please review & merge

#51986 Update crux-toolkit to 4.2
  recipes/crux-toolkit/meta.yaml
Labels: please review & merge

#52987 Update isescan to use fraggenescan >= 1.32 dependency so it is compatible with MacOSX
  recipes/isescan/meta.yaml
Labels: please review & merge
