Repository bioconda/bioconda-recipes, pull requests merged in 2024-08, with the labels that each got.

#49724 Update Reduce v4.14 without libboost-python-devel
  recipes/reduce/meta.yaml
Labels: please review & merge

#49715 Update sequencetools to v1.5.4.0
  recipes/sequencetools/meta.yaml
Labels: please review & merge

#49720 Add lsaBGC
  recipes/lsabgc/meta.yaml
Labels: please review & merge

#49744 Add FoldMason
  recipes/foldmason/build.sh
  recipes/foldmason/meta.yaml
Labels: please review & merge

#49734 ataqv: add aarch64/arm64 builds
  recipes/ataqv/build.sh
  recipes/ataqv/build_failure.linux-64.yaml
  recipes/ataqv/build_failure.osx-64.yaml
  recipes/ataqv/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49735 filtlong: add aarch64/arm64 builds
  recipes/filtlong/build.sh
  recipes/filtlong/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49747 Reviving no_static.patch to fix segmentation faults
  recipes/ncbi-fcs-gx/meta.yaml
  recipes/ncbi-fcs-gx/no_static.patch
Labels: please review & merge

#49743 quicksect: add aarch64/arm64 builds
  recipes/quicksect/meta.yaml
Labels: aarch64, osx-arm64

#49390 Add recipe for grenedalf
  recipes/grenedalf/build.sh
  recipes/grenedalf/meta.yaml
Labels: please review & merge

#49752 Add radtk
  recipes/radtk/build.sh
  recipes/radtk/meta.yaml
Labels: please review & merge

#49754 bam-readcount: add linux-aarch64 support
  recipes/bam-readcount/build.sh
  recipes/bam-readcount/meta.yaml
Labels: please review & merge, aarch64

#49780 Update isoquant to 3.5.0
  recipes/isoquant/meta.yaml
Labels: please review & merge

#49782 Add osx-arm64 support for TRUST4
  recipes/trust4/LICENSE
  recipes/trust4/meta.yaml
Labels: please review & merge

#49443 Update blast OSX and add ARM builds
  recipes/blast/build.sh
  recipes/blast/conda_build_config.yaml
  recipes/blast/configurellvm.patch
  recipes/blast/get_species_taxids.patch
  recipes/blast/meta.yaml
  recipes/blast/normbase.patch
  recipes/blast/phonehome.patch
  recipes/blast/update_configsub.patch
Labels: please review & merge, aarch64, osx-arm64

#49789 Add osx-arm64 support to centrifuger
  recipes/centrifuger/meta.yaml
Labels: please review & merge

#49794 pybedlite & cgranges: add aarch64/arm64 builds
  recipes/cgranges/meta.yaml
  recipes/pybedlite/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49800 insurveyor: add aarch64/arm64 builds
  recipes/insurveyor/INSurVeyor-aarch64.patch
  recipes/insurveyor/build.sh
  recipes/insurveyor/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49802 Update sdeper to 1.6.2
  recipes/sdeper/meta.yaml
Labels: please review & merge

#49818 Bump bioconda-repodata-patches for new libdeflate release
  recipes/bioconda-repodata-patches/gen_patch_json.py
  recipes/bioconda-repodata-patches/meta.yaml
Labels: please review & merge

#49829 Add graphbin2 v1.3.1
  recipes/graphbin2/meta.yaml
Labels: please review & merge

#49838 Update mpra-data-access-portal to 0.1.9
  recipes/mpra-data-access-portal/meta.yaml
Labels: please review & merge

#48200 Add KIN
  recipes/kin/meta.yaml
Labels: please review & merge

#49841 Pin taxonkit>=0.17
  recipes/pytaxonkit/meta.yaml
Labels: update pinning, update build number

#49433 add flexynesis
  recipes/flexynesis/meta.yaml
Labels: please review & merge

#49850 fastool: add aarch64/arm64 builds
  recipes/fastool/build.sh
  recipes/fastool/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49846 Update cospar to 0.4.1
  recipes/cospar/meta.yaml
Labels: please review & merge

#49854 sage-proteomics: add aarch64/arm64 builds
  recipes/sage-proteomics/build.sh
  recipes/sage-proteomics/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49853 irfinder: add aarch64/arm64 builds
  recipes/irfinder/build.sh
  recipes/irfinder/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49847 blast: bump build number to rebuild linux
  recipes/blast/meta.yaml
Labels: please review & merge

#49855 Update Hairsplitter
  recipes/hairsplitter/build.sh
  recipes/hairsplitter/meta.yaml
Labels: please review & merge

#49757 Add new recipe for bcgtree
  recipes/bcgtree/build.sh
  recipes/bcgtree/meta.yaml
Labels: please review & merge

#49200 hictkpy: enable osx-arm64 build
  recipes/hictkpy/build_failure.osx-64.yaml
  recipes/hictkpy/meta.yaml
Labels: please review & merge, osx-arm64

#49870 Fix mummer hashbang and build on macOS including ARM
  recipes/mummer/build.sh
  recipes/mummer/meta.yaml
  recipes/mummer/patches/addleafcount_explicit.patch
  recipes/mummer/patches/findmaxmat_explicit.patch
  recipes/mummer/patches/findmumcand_explicit.patch
  recipes/mummer/patches/linkloc_explicit.patch
  recipes/mummer/patches/procmaxmat_explicit.patch
Labels: MacOS related, please review & merge, osx-arm64

#49878 hictk: remove stale build failure logs
  recipes/hictk/build_failure.linux-aarch64.yaml
  recipes/hictk/build_failure.osx-64.yaml
  recipes/hictk/meta.yaml
Labels: please review & merge

#49874 GW recipe update
  recipes/gw/meta.yaml
Labels: please review & merge

#49796 yak: add aarch64/arm64 build
  recipes/yak/build.sh
  recipes/yak/meta.yaml
  recipes/yak/yak.patch
Labels: aarch64, osx-arm64

#49891 Update strainr2
  recipes/strainr2/build.sh
  recipes/strainr2/meta.yaml
Labels: please review & merge

#49911 Update fastani to build osx-arm64
  recipes/fastani/build.sh
  recipes/fastani/meta.yaml
Labels: osx-arm64

#49920 Update Picrust2 v2.5.3
  recipes/picrust2/meta.yaml
  recipes/picrust2/post-link.sh
Labels: please review & merge

#49905 fastme: add aarch64/arm64 builds
  recipes/fastme/build.sh
  recipes/fastme/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49893 nextpolish2: add aarch64/arm64 builds
  recipes/nextpolish2/build.sh
  recipes/nextpolish2/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49902 rust-ncbitaxonomy: add aarch64/arm64 builds
  recipes/rust-ncbitaxonomy/build.sh
  recipes/rust-ncbitaxonomy/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49851 parafly: add linux-aarch64 build
  build-fail-blacklist
  recipes/parafly/build.sh
  recipes/parafly/meta.yaml
  recipes/parafly/parafly-aarch64.patch
Labels: please review & merge, aarch64, osx-arm64

#49883 Add NCBI StxTyper
  recipes/ncbi-stxtyper/build.sh
  recipes/ncbi-stxtyper/meta.yaml
Labels: please review & merge

#49929 Add Promoter-Calculator
  recipes/promotercalculator/meta.yaml
Labels: please review & merge

#49926 Add RhoTermPredict
  recipes/rhotermpredict/meta.yaml
Labels: please review & merge

#49890 Add build recipe for commec
  recipes/commec/meta.yaml
Labels: please review & merge

#49935 ratatosk: add aarch64 build
  recipes/ratatosk/build.sh
  recipes/ratatosk/meta.yaml
Labels: aarch64

#49941 Update Comet-ms to version 2024.01.01
  recipes/comet-ms/meta.yaml
Labels: please review & merge

#49943 Bump poppunk to v2.7.0
  recipes/poppunk/meta.yaml
Labels: please review & merge

#49944 Build gofasta on osx-arm64
  recipes/gofasta/meta.yaml
Labels: please review & merge, osx-arm64

#49934 Adding pdbx
  recipes/pdbx/build.sh
  recipes/pdbx/meta.yaml
Labels: please review & merge

#49949 Add Cryptkeeper
  recipes/cryptkeeper/meta.yaml
Labels: please review & merge

#49954 feat: recipe to install tool sdust
  recipes/sdust/build.sh
  recipes/sdust/meta.yaml
Labels: please review & merge

#49968 Update matchtigs to 2.1.7.
  recipes/matchtigs/build.sh
  recipes/matchtigs/build_failure.linux-64.yaml
  recipes/matchtigs/build_failure.osx-64.yaml
  recipes/matchtigs/meta.yaml
Labels: please review & merge

#49987 matchtigs: add aarch64/arm64 builds
  recipes/matchtigs/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49981 acms: add linux-aarch64 support
  recipes/acms/meta.yaml
Labels: please review & merge, aarch64

#49980 hairsplitter & minigraph: add aarch64/arm64 builds
  recipes/hairsplitter/build.sh
  recipes/hairsplitter/hairsplitter-aarch64.patch
  recipes/hairsplitter/meta.yaml
  recipes/minigraph/build.sh
  recipes/minigraph/meta.yaml
  recipes/minigraph/minigraph-aarch64.patch
Labels: please review & merge, aarch64, osx-arm64

#49973 rapidnj: add aarch64/arm64 builds
  recipes/rapidnj/build.sh
  recipes/rapidnj/meta.yaml
  recipes/rapidnj/rapidnj-aarch64.patch
Labels: please review & merge, aarch64, osx-arm64

#49953 feat: add recipe for tool dna-nn
  recipes/dna-nn/build.sh
  recipes/dna-nn/meta.yaml
Labels: please review & merge

#49966 Add phyloaln
  recipes/phyloaln/build.sh
  recipes/phyloaln/meta.yaml
Labels: please review & merge

#49970 Pdbx v1.0.0 for ARM platforms
  recipes/pdbx/build.sh
  recipes/pdbx/meta.yaml
Labels: please review & merge, osx-arm64

#49995 Build hyphy for osx-arm64
  recipes/hyphy/meta.yaml
Labels: please review & merge

#49998 dna-nn: add linux-aarch64 build
  recipes/dna-nn/meta.yaml
Labels: please review & merge, aarch64

#49975 sequali: add aarch64/arm64 builds
  recipes/sequali/build_failure.osx-64.yaml
  recipes/sequali/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49999 libsbml: add aarch64/arm64 builds
  recipes/libsbml/build.sh
  recipes/libsbml/meta.yaml
Labels: aarch64, osx-arm64

#50003 Update assembly_finder recipe
  recipes/assembly_finder/meta.yaml
Labels: please review & merge

#50004 Update MeSS recipe
  recipes/mess/meta.yaml
Labels: please review & merge

#50016 Update VITAP from v.1.1 to v.1.5
  recipes/vitap/meta.yaml
Labels: please review & merge

#50010 discosnp & dsk & short-read-connector: add linux-aarch64 builds
  recipes/discosnp/meta.yaml
  recipes/dsk/build.sh
  recipes/dsk/meta.yaml
  recipes/short-read-connector/meta.yaml
Labels: please review & merge, aarch64

#50040 sainsc: add linux-aarch64 build
  recipes/sainsc/meta.yaml
Labels: please review & merge, aarch64

#50042 Update sainsc: Multiple python versions
  recipes/sainsc/meta.yaml
Labels: please review & merge

#50049 Update sainsc: add osx support
  recipes/sainsc/meta.yaml
Labels: please review & merge

#47895 update PASTA to 1.9.2 and SEPP to 4.5.4, i.e. unpin HMMER and lift py <=3.9
  recipes/pasta/meta.yaml
  recipes/sepp/meta.yaml
  recipes/sepp/nodeps.setup.py.patch
Labels: please review & merge

#49952 Add "roadies" package
  recipes/roadies/build.sh
  recipes/roadies/meta.yaml
Labels: please review & merge

#50075 lift restrictions of dendropy, which is a dependency of SEPP
  recipes/pasta/meta.yaml
  recipes/sepp/meta.yaml
Labels: please review & merge

#50047 idemuxcpp: add aarch64/arm64 builds
  recipes/idemuxcpp/build.sh
  recipes/idemuxcpp/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#50070 add tracs
  recipes/tracs/meta.yaml
Labels: please review & merge

#50073 htsbox: add aarch64/arm64 build
  recipes/htsbox/build.sh
  recipes/htsbox/meta.yaml
Labels: aarch64, osx-arm64

#50082 Update beacon-import tool
  recipes/beacon2-import/meta.yaml
Labels: please review & merge

#50089 Update Metabinner (Make scripts/auxilirary tools available on path)
  recipes/metabinner/build.sh
  recipes/metabinner/meta.yaml
Labels: please review & merge

#50106 ucsc-subchar: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-subchar/build.sh
  recipes/ucsc-subchar/include.patch
  recipes/ucsc-subchar/meta.yaml
Labels: please review & merge, aarch64

#50072 prot-scriber: add aarch64 build
  recipes/prot-scriber/build.sh
  recipes/prot-scriber/meta.yaml
Labels: please review & merge, aarch64

#50100 apu-label-propagation: add aarch64/arm64 builds
  recipes/apu-label-propagation/build.sh
  recipes/apu-label-propagation/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#50099 msweep: add linux-aarch64 build
  recipes/msweep/meta.yaml
Labels: please review & merge, aarch64

#50101 varfish-server-worker: add linux-aarch64 build
  recipes/varfish-server-worker/build.sh
  recipes/varfish-server-worker/meta.yaml
Labels: please review & merge, aarch64

#50102 nedbit-features-calculator: add aarch64/arm64 builds
  recipes/nedbit-features-calculator/meta.yaml
Labels: please review & merge, aarch64

#50109 ucsc-qactowig: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-qactowig/build.sh
  recipes/ucsc-qactowig/include.patch
  recipes/ucsc-qactowig/meta.yaml
Labels: please review & merge, aarch64

#50108 ucsc-pslhisto: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-pslhisto/build.sh
  recipes/ucsc-pslhisto/include.patch
  recipes/ucsc-pslhisto/meta.yaml
Labels: please review & merge, aarch64

#50107 ucsc-pslrecalcmatch: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-pslrecalcmatch/build.sh
  recipes/ucsc-pslrecalcmatch/include.patch
  recipes/ucsc-pslrecalcmatch/meta.yaml
Labels: please review & merge, aarch64

#50119 Build bustools for aarch/arm
  recipes/bustools/meta.yaml
Labels: please review & merge

#50117 Add nanocount
  recipes/nanocount/meta.yaml
Labels: please review & merge

#50027 Update r-stitch version 1.7.0
  recipes/r-stitch/build.sh
  recipes/r-stitch/conda_build_config.yaml
  recipes/r-stitch/meta.yaml
  recipes/r-stitch/seqlib-aarch64.patch
Labels: please review & merge

#50142 Add `alen`
  recipes/alen/build.sh
  recipes/alen/meta.yaml
Labels: please review & merge

#50146 Update graphbin to v1.7.4
  recipes/graphbin/meta.yaml
Labels: please review & merge

#50145 Add r-mspbwt package
  recipes/r-mspbwt/LICENSE
  recipes/r-mspbwt/build.sh
  recipes/r-mspbwt/meta.yaml
Labels: please review & merge

#50115 add chromsize v.0.0.2 recipe
  recipes/chromsize/build.sh
  recipes/chromsize/meta.yaml
Labels: please review & merge

#50166 update to latest version of segalign
  recipes/segalign-full/meta.yaml
  recipes/segalign-galaxy/meta.yaml
Labels: please review & merge

#50155 r-mspbwt: add aarch64 build
  recipes/r-mspbwt/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#50154 python-bioext: add aarch64/arm64 builds
  recipes/python-bioext/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#50158 Update r-quilt version to 2.0.0
  recipes/r-quilt/build.sh
  recipes/r-quilt/meta.yaml
Labels: please review & merge

#50189 cellsnp-lite: add aarch64/arm64 build
  recipes/cellsnp-lite/LICENSE
  recipes/cellsnp-lite/build.sh
  recipes/cellsnp-lite/build_failure.osx-64.yaml
  recipes/cellsnp-lite/meta.yaml
Labels: aarch64, osx-arm64

#50187 r-quilt: add aarch64 build
  recipes/r-quilt/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49921 GW update recipe
  recipes/gw/build.sh
  recipes/gw/meta.yaml
Labels: please review & merge

#50172 Add recipe for miniprot-boundary-scorer
  recipes/miniprot-boundary-scorer/build.sh
  recipes/miniprot-boundary-scorer/meta.yaml
Labels: please review & merge

#50207 Add osx-arm64 build for dnaio
  recipes/dnaio/meta.yaml
Labels: please review & merge

#50196 ucsc-bigwigmerge: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-bigwigmerge/build.sh
  recipes/ucsc-bigwigmerge/include.patch
  recipes/ucsc-bigwigmerge/meta.yaml
Labels: please review & merge, aarch64

#50213 muscle - enable osx-arm64 builds in meta.yaml
  recipes/muscle/meta.yaml
Labels: please review & merge

#50203 Update bowtie2 to remove TBB dependencies
  recipes/bowtie2/build.sh
  recipes/bowtie2/meta.yaml
Labels: please review & merge

#50220 Update pgenlib to 0.91.0 and enable arm64/aarch64 builds
  recipes/pgenlib/meta.yaml
Labels: please review & merge

#50218 Update GMWI2 package
  recipes/gmwi2/meta.yaml
Labels: please review & merge

#50219 cyvcf2: enable osx-arm64 build
  recipes/cyvcf2/meta.yaml
Labels: please review & merge

#50223 fast-edit-distance: add aarch64/arm64 build
  recipes/fast-edit-distance/meta.yaml
Labels: aarch64, osx-arm64

#50232 python-hyphy-python: add aarch64/arm64 build
  recipes/python-hyphy-python/build.sh
  recipes/python-hyphy-python/build_failure.osx-64.yaml
  recipes/python-hyphy-python/meta.yaml
Labels: aarch64, osx-arm64

#50231 whatshap: add arm64 build
  recipes/whatshap/build_failure.linux-64.yaml
  recipes/whatshap/build_failure.linux-aarch64.yaml
  recipes/whatshap/meta.yaml
Labels: osx-arm64

#50238 Update MultiQC to 1.24.1 Patch Release
  recipes/multiqc/meta.yaml
Labels: please review & merge

#50249 Add new recipe prymer
  recipes/prymer/meta.yaml
Labels: please review & merge

#50253 Add biobox_add_taxid recipe
  recipes/biobox_add_taxid/meta.yaml
Labels: please review & merge

#50266 vsnp3 version 3.24
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#50262 Update strangepg
  recipes/strangepg/meta.yaml
Labels: please review & merge

#50270 art: enable osx-arm64 build
  recipes/art/build.sh
  recipes/art/meta.yaml
Labels: please review & merge

#50252 Add tribal
  recipes/tribal/meta.yaml
  recipes/tribal/run_test.py
Labels: please review & merge

#50269 Add new recipe for bwa-aln-interactive
  recipes/bwa-aln-interactive/build.sh
  recipes/bwa-aln-interactive/meta.yaml
Labels: please review & merge

#50267 add pling
  recipes/pling/meta.yaml
Labels: please review & merge

#50281 Build hmmer for osx-arm64
  recipes/hmmer/build.sh
  recipes/hmmer/config.guess
  recipes/hmmer/config.sub
  recipes/hmmer/meta.yaml
Labels: please review & merge

#41052 Update minimap2 to install the man page
  recipes/minimap2/build.sh
  recipes/minimap2/meta.yaml
Labels: please review & merge

#50295 Add spatialleiden recipe
  recipes/spatialleiden/meta.yaml
Labels: please review & merge

#50292 Update metacerberus
  recipes/metacerberus/meta.yaml
Labels: please review & merge

#50298 Update metacerberus-lite
  recipes/metacerberus-lite/meta.yaml
Labels: please review & merge

#50340 Update Auspice to 2.56.1
  recipes/auspice/meta.yaml
Labels: please review & merge

#49946 Build k8 on osx-arm64
  recipes/k8/build.sh
  recipes/k8/meta.yaml
Labels: osx-arm64

#49945 Build minimap2 on osx-arm64
  recipes/minimap2/build.sh
  recipes/minimap2/meta.yaml
Labels: osx-arm64

#50324 ucsc-pslmrnacover: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-pslmrnacover/build.sh
  recipes/ucsc-pslmrnacover/include.patch
  recipes/ucsc-pslmrnacover/meta.yaml
Labels: please review & merge, aarch64

#50325 Update the scripts used to generate the ucsc-XYZ recipes
  scripts/check-for-additional-platforms.sh
  scripts/ucsc/create-ucsc-packages.py
  scripts/ucsc/include.patch
  scripts/ucsc/template-build-cp-short.sh
  scripts/ucsc/template-build-cp.sh
  scripts/ucsc/template-build-fetchChromSizes.sh
  scripts/ucsc/template-build-no-bin.sh
  scripts/ucsc/template-build-parasol.sh
  scripts/ucsc/template-build-with-stringify.sh
  scripts/ucsc/template-build.sh
  scripts/ucsc/template-meta-with-python.yaml
  scripts/ucsc/template-meta.yaml
  scripts/ucsc/ucsc_config.yaml
Labels: please review & merge

#50323 Update ucsc-addCols to v469
  recipes/ucsc-addcols/build.sh
  recipes/ucsc-addcols/meta.yaml
Labels: please review & merge

#50226 spoa: add arm64 build
  recipes/spoa/build.sh
  recipes/spoa/meta.yaml
Labels: osx-arm64

#50361 sorted_nearest: add arm64 build
  recipes/sorted_nearest/build_failure.osx-64.yaml
  recipes/sorted_nearest/meta.yaml
Labels: osx-arm64

#50353 Update emu v3.4.6
  recipes/emu/meta.yaml
Labels: please review & merge

#50389 ci: Fix platform script echo
  scripts/check-for-additional-platforms.sh
Labels: please review & merge

#50390 scoring-matrices: add arm64 build
  recipes/scoring-matrices/meta.yaml
Labels: osx-arm64

#50391 trimal: add arm64 build
  recipes/trimal/build.sh
  recipes/trimal/meta.yaml
Labels: osx-arm64

#50394 ci: nightly builds for linux-aarch64 and osx-arm64
  .circleci/config.yml
  .github/workflows/nightly.yml
Labels: please review & merge

#50366 tigmint: add linux-aarch64 and osx-arm64 build
  recipes/tigmint/build.sh
  recipes/tigmint/meta.yaml
Labels: please review & merge

#50354 Add r-cobrar
  recipes/r-cobrar/meta.yaml
Labels: please review & merge

#50372 GW v1.0.3 patch
  recipes/gw/build.sh
  recipes/gw/fix-context.patch
  recipes/gw/meta.yaml
Labels: please review & merge

#50411 Adding kegalign-full, where development for segalign-full and segalign-galaxy will continue
  recipes/kegalign-full/meta.yaml
Labels: please review & merge

#50410 Update fastahack to 1.0.0 and modernize recipe style
  recipes/fastahack/meta.yaml
Labels: please review & merge

#50400 Update vConTACT3
  recipes/vcontact3/meta.yaml
Labels: please review & merge

#50421 fastahack: add linux-aarch64 build
  recipes/fastahack/build.sh
  recipes/fastahack/meta.yaml
Labels: aarch64

#50429 Update dbcanlight to 1.1.0
  recipes/dbcanlight/meta.yaml
Labels: please review & merge
