Repository bioconda/bioconda-recipes, pull requests merged in 2024-07, with the labels that each got.

#48817 add recipe argo
  recipes/argo/meta.yaml
Labels: please review & merge

#48837 Add flumutdb
  recipes/flumut/meta.yaml
  recipes/flumutdb/meta.yaml
Labels: please review & merge

#48841 r-sigminer: add linux-aarch64 build
  recipes/r-sigminer/meta.yaml
Labels: please review & merge, aarch64

#48842 expansionhunter: add linux-aarch64 build
  recipes/expansionhunter/build.sh
  recipes/expansionhunter/meta.yaml
Labels: please review & merge, aarch64

#48843 rasusa: add linux-aarch64 build
  recipes/rasusa/meta.yaml
Labels: please review & merge, aarch64

#48844 krbalancing: add linux-aarch64 build
  recipes/krbalancing/meta.yaml
Labels: please review & merge, aarch64

#48812 Update : Fix build script for fibertools-rs
  recipes/fibertools-rs/build.sh
  recipes/fibertools-rs/meta.yaml
Labels: please review & merge

#48846 squizz: add linux-aarch64 build
  recipes/squizz/build.sh
  recipes/squizz/meta.yaml
Labels: please review & merge, aarch64

#48848 add pysam dep
  recipes/harpy/meta.yaml
Labels: please review & merge

#48876 Update hairsplitter package to version 1.9.5
  recipes/hairsplitter/meta.yaml
Labels: please review & merge

#45309 Update recipe MS2Query
  recipes/ms2query/meta.yaml
Labels: please review & merge

#48865 harpy: add linux-aarch64 build
  recipes/harpy/meta.yaml
Labels: please review & merge, aarch64

#48866 centrifuger: add linux-aarch64 build
  recipes/centrifuger/build.sh
  recipes/centrifuger/meta.yaml
Labels: aarch64

#48878 r-biodb: add linux-aarch64 build
  recipes/r-biodb/meta.yaml
Labels: please review & merge, aarch64

#48885 Update bwakit to use 0.7.18
  recipes/bwakit/build.sh
  recipes/bwakit/meta.yaml
Labels: please review & merge

#48867 simpleaf & alevin-fry & piscem: add linux-aarch64 build
  recipes/alevin-fry/build.sh
  recipes/alevin-fry/meta.yaml
  recipes/alevin-fry/use-libradicl-0.8.2.patch
  recipes/piscem/build_failure.osx-64.yaml
  recipes/piscem/meta.yaml
  recipes/simpleaf/build_failure.linux-64.yaml
  recipes/simpleaf/build_failure.osx-64.yaml
  recipes/simpleaf/meta.yaml
Labels: please review & merge, aarch64

#48899 Update pathogen-embed to 2.1.0
  recipes/pathogen-embed/meta.yaml
Labels: please review & merge

#48894 Add cloci
  recipes/cloci/meta.yaml
Labels: please review & merge

#48917 Update TaxonKit to 0.17.0
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#48914 arriba: add linux-aarch64 build
  recipes/arriba/build.sh
  recipes/arriba/meta.yaml
  recipes/star/meta.yaml
Labels: aarch64

#48923 Update codoff
  recipes/codoff/meta.yaml
Labels: please review & merge

#48911 survivor: add linux-aarch64 build
  recipes/survivor/build.sh
  recipes/survivor/meta.yaml
Labels: please review & merge, aarch64

#48928 Update codoff
  recipes/codoff/meta.yaml
Labels: please review & merge

#48904 skder & skani: add linux-aarch64 build
  recipes/skani/meta.yaml
  recipes/skder/build_failure.linux-64.yaml
  recipes/skder/build_failure.osx-64.yaml
  recipes/skder/meta.yaml
Labels: please review & merge, aarch64

#48931 Update tcdemux recipe
  recipes/tcdemux/meta.yaml
Labels: please review & merge

#46735 sambamba: add linux-aarch64 build
  .circleci/config.yml
  recipes/sambamba/build.sh
  recipes/sambamba/meta.yaml
Labels: please review & merge, aarch64

#48933 dysgu 1.6.4 Update meta.yaml
  recipes/dysgu/meta.yaml
Labels: please review & merge

#48957 add cpstools recipes
  recipes/cpstools/build.sh
  recipes/cpstools/meta.yaml
Labels: please review & merge

#48749 Update b2bTools to v3.0.7
  recipes/b2btools/LICENSE
  recipes/b2btools/meta.yaml
  recipes/b2btools/run_test.sh
  recipes/b2btools/test.msa.fasta
  recipes/b2btools/test.singleseq.fasta
Labels: please review & merge

#48963 decifer: add linux-aarch64 build
  recipes/decifer/build.sh
  recipes/decifer/meta.yaml
Labels: please review & merge, aarch64

#48961 bigtools: add linux-aarch64 build
  recipes/bigtools/meta.yaml
Labels: please review & merge, aarch64

#48960 dysgu: add linux-aarch64 build
  recipes/dysgu/conda_build_config.yaml
  recipes/dysgu/meta.yaml
Labels: please review & merge, aarch64

#48981 Add kmertools v0.1.0
  recipes/kmertools/build.sh
  recipes/kmertools/meta.yaml
Labels: please review & merge

#48978 Update NARFMAP to 1.4.2
  recipes/narfmap/build_failure.linux-64.yaml
  recipes/narfmap/meta.yaml
Labels: please review & merge

#48989 Update DAJIN2
  recipes/dajin2/meta.yaml
Labels: please review & merge

#49004 chore: Emiller88 => bioinformaticsorphanange
  recipes/narfmap/meta.yaml
Labels: please review & merge

#49014 update ufcg to 1.0.6
  recipes/ufcg/meta.yaml
Labels: please review & merge

#49020 bump piscem to v0.10.0
  recipes/piscem/meta.yaml
Labels: please review & merge

#49017 Bump pybigtools to 0.2.0
  recipes/pybigtools/build.sh
  recipes/pybigtools/build_failure.osx-64.yaml
  recipes/pybigtools/meta.yaml
Labels: please review & merge

#49025 Update sentieon to 202308.03
  recipes/sentieon/meta.yaml
Labels: please review & merge

#49027 pybigtools: add linux-aarch64 build
  recipes/pybigtools/meta.yaml
Labels: please review & merge, aarch64

#48998 art: add linux-aarch64 build
  recipes/art/build.sh
  recipes/art/build_failure.linux-64.yaml
  recipes/art/build_failure.osx-64.yaml
  recipes/art/meta.yaml
Labels: please review & merge, aarch64

#49038 Update zol
  recipes/zol/meta.yaml
Labels: please review & merge

#49045 fasta3: add linux-aarch64 build
  recipes/fasta3/build.sh
  recipes/fasta3/meta.yaml
Labels: aarch64

#49044 cpat: add linux-aarch64 build
  recipes/cpat/meta.yaml
Labels: aarch64

#49043 generax: add linux-aarch64 build
  recipes/generax/build.sh
  recipes/generax/meta.yaml
Labels: aarch64

#48996 ipk: add linux-aarch64 build
  recipes/ipk/meta.yaml
Labels: please review & merge, aarch64

#49035 trust4: add linux-aarch64 build
  recipes/trust4/build.sh
  recipes/trust4/meta.yaml
Labels: aarch64

#49007 Gw v0.10.0
  recipes/gw/build.sh
  recipes/gw/fix-ldflags.patch
  recipes/gw/fix-linker-issues.patch
  recipes/gw/meta.yaml
Labels: please review & merge

#49069 Fix pathphynder to include auxiliary function files
  recipes/pathphynder/build.sh
  recipes/pathphynder/meta.yaml
Labels: please review & merge

#49077 t1k: add linux-aarch64 build
  recipes/t1k/build.sh
  recipes/t1k/meta.yaml
Labels: please review & merge, aarch64

#49070 physher: add linux-aarch64 build
  recipes/physher/build.sh
  recipes/physher/meta.yaml
  recipes/physher/physher-aarch64.patch
Labels: please review & merge, aarch64

#49068 haplomap: add linux-aarch64 build
  recipes/haplomap/build.sh
  recipes/haplomap/meta.yaml
Labels: please review & merge, aarch64

#49067 vamos: add linux-aarch64 build
  recipes/vamos/build.sh
  recipes/vamos/meta.yaml
  recipes/vamos/vamos-aarch64.patch
Labels: please review & merge, aarch64

#46775 feat: support for osx-arm64 builds
  .circleci/config.yml
  .github/workflows/Bulk.yml
  .github/workflows/PR.yml
  .github/workflows/master.yml
  recipes/bamtools/meta.yaml
  recipes/bioawk/meta.yaml
  scripts/check-for-additional-platforms.sh
Labels: MacOS related, osx-arm64

#49088 Build htslib on macOS ARM
  recipes/htslib/meta.yaml
Labels: please review & merge, osx-arm64

#49090 Build Iqtree for osx-arm64
  recipes/iqtree/meta.yaml
Labels: please review & merge, osx-arm64

#49093 Build pyfastx for osx-arm64
  recipes/pyfastx/meta.yaml
Labels: please review & merge, osx-arm64

#49101 Build ncbi-vdb on osx-arm64
  recipes/ncbi-vdb/meta.yaml
Labels: osx-arm64

#49092 Build bx-python for osx-arm64
  recipes/bx-python/meta.yaml
Labels: please review & merge, osx-arm64

#49095 Build nextclade for osx-arm64
  recipes/nextclade/meta.yaml
Labels: please review & merge, osx-arm64

#49104 Build samtools and bcftools on macOS ARM
  recipes/bcftools/meta.yaml
  recipes/samtools/meta.yaml
Labels: osx-arm64

#49105 Build pysam on macOS ARM
  recipes/pysam/meta.yaml
Labels: osx-arm64

#49103 Build auspice for osx-arm64
  recipes/auspice/meta.yaml
Labels: please review & merge, osx-arm64

#49100 Build fasttree for osx-arm64
  recipes/fasttree/meta.yaml
Labels: please review & merge, osx-arm64

#49097 Build nextclade2 for osx-arm64
  recipes/nextclade2/meta.yaml
Labels: please review & merge, osx-arm64

#49108 Build bedtools on macOS ARM
  recipes/bedtools/meta.yaml
Labels: osx-arm64

#49128 Update foldcomp with ARM support
  recipes/foldcomp/meta.yaml
Labels: please review & merge

#49127 Update plass with MacOS ARM support
  recipes/plass/meta.yaml
Labels: please review & merge

#49126 Update metaeuk with MacOS ARM support
  recipes/metaeuk/meta.yaml
Labels: please review & merge

#49124 Update spacpharer with MacOS ARM support
  recipes/spacepharer/meta.yaml
Labels: please review & merge

#49123 Update kalign2 with MacOS ARM support
  recipes/kalign2/meta.yaml
Labels: please review & merge

#49122 Update metabuli with MacOS ARM support
  recipes/metabuli/meta.yaml
Labels: please review & merge

#49121 Update hhsuite with MacOS ARM support
  recipes/hhsuite/meta.yaml
Labels: please review & merge

#49119 Update MMseqs2 with MacOS ARM support
  recipes/mmseqs2/meta.yaml
Labels: please review & merge

#49118 Update foldseek with MacOS ARM support
  recipes/foldseek/fix-rust-1.79.patch
  recipes/foldseek/meta.yaml
Labels: please review & merge

#49115 Update psdm with arm support
  recipes/psdm/meta.yaml
Labels: please review & merge

#49113 update rasusa with osx arm64 support
  recipes/rasusa/meta.yaml
Labels: please review & merge

#49099 Build seqkit for osx-arm64
  recipes/seqkit/meta.yaml
Labels: please review & merge, osx-arm64

#49096 Build nextalign for osx-arm64
  recipes/nextalign/meta.yaml
Labels: please review & merge, osx-arm64

#49094 Builds csvtk for osx-arm64
  recipes/csvtk/meta.yaml
Labels: please review & merge, osx-arm64

#49131 xtandem: add linux-aarch64 build
  recipes/xtandem/build.sh
  recipes/xtandem/meta.yaml
Labels: aarch64

#49098 Build raxml for osx-arm64
  recipes/raxml/build.sh
  recipes/raxml/meta.yaml
Labels: please review & merge, osx-arm64

#49117 Build vsearch for osx-arm64
  recipes/vsearch/build.sh
  recipes/vsearch/meta.yaml
Labels: help wanted, osx-arm64

#49134 Add osx-arm64 support for TaxonKit
  recipes/taxonkit/meta.yaml
Labels: please review & merge

#49142 change name "Assemblycomparator2" -> "CompareM2"
  recipes/assemblycomparator2/build.sh
  recipes/assemblycomparator2/meta.yaml
Labels: please review & merge

#49150 bowtie2: add osx-arm64
  recipes/bowtie2/meta.yaml
Labels: please review & merge, osx-arm64

#49080 epik: add linux-aarch64 build
  recipes/epik/build.sh
  recipes/epik/epik-aarch64.patch
  recipes/epik/meta.yaml
Labels: please review & merge, aarch64

#49141 gap2seq: add linux-aarch64 build
  recipes/gap2seq/build.sh
  recipes/gap2seq/meta.yaml
Labels: aarch64

#49143 phylodm: add aarch64/arm64 builds
  recipes/phylodm/meta.yaml
Labels: aarch64

#49145 mbg: add aarch64/arm64 builds
  recipes/mbg/.gitattributes
  recipes/mbg/build.sh
  recipes/mbg/mbg-aarch64.patch
  recipes/mbg/meta.yaml
Labels: aarch64

#48962 skesa: add linux-aarch64 build
  recipes/skesa/build.sh
  recipes/skesa/meta.yaml
  recipes/skesa/skesa-aarch64.patch
Labels: aarch64

#49129 breseq: add aarch64/arm64 support
  recipes/breseq/build.sh
  recipes/breseq/meta.yaml
Labels: please review & merge, aarch64

#49163 Add new recipe gtdb_to_taxdump
  recipes/gtdb_to_taxdump/meta.yml
Labels: please review & merge

#49175 perl-digest-sha1: enable osx-arm64 build
  recipes/perl-digest-sha1/meta.yaml
Labels: please review & merge

#49177 pairix: enable osx-arm64 build
  recipes/pairix/meta.yaml
Labels: please review & merge

#49183 Update poseidon-trident to 1.5.4.0
  recipes/poseidon-trident/meta.yaml
Labels: please review & merge

#49157 hictk: enable osx-arm64 build
  recipes/hictk/meta.yaml
Labels: please review & merge, osx-arm64

#49190 Update GW to v0.10.1
  recipes/gw/fix-ldflags.patch
  recipes/gw/fix-linker-issues.patch
  recipes/gw/fix-version.patch
  recipes/gw/meta.yaml
Labels: please review & merge

#49219 Rebuild piscem
  recipes/piscem/build.sh
  recipes/piscem/meta.yaml
Labels: please review & merge

#49189 Fix NARFMAP static build
  recipes/narfmap/build.sh
  recipes/narfmap/meta.yaml
Labels: please review & merge

#49210 perbase: add osx-arm64 build
  recipes/perbase/meta.yaml
Labels: please review & merge

#49209 Update gsearch v0.2.0
  recipes/gsearch/meta.yaml
Labels: please review & merge

#47447 ncls: update osx-arm64 build
  recipes/ncls/meta.yaml
Labels: osx-arm64

#49194 Update CompareM2 to v2.8.2
  recipes/comparem2/build.sh
  recipes/comparem2/meta.yaml
Labels: please review & merge

#49230 Fix pypi urls for bot autobump: setuptools changed some source paths
  recipes/galaxy-files/meta.yaml
  recipes/galaxy-objectstore/meta.yaml
  recipes/galaxy_sequence_utils/meta.yaml
  recipes/jms-metabolite-services/meta.yaml
  recipes/khipu-metabolomics/meta.yaml
Labels: please review & merge, new version

#49231 Bump bx-python to 0.12, fix pypi url
  recipes/bx-python/meta.yaml
Labels: help wanted, please review & merge, new version

#49241 Update pathogen-embed to 2.2.0
  recipes/pathogen-embed/meta.yaml
Labels: please review & merge

#49235 Update MetaCerberus
  recipes/metacerberus/meta.yaml
Labels: please review & merge

#49239 singlem: Pin deps and update description.
  recipes/singlem/meta.yaml
Labels: please review & merge

#49240 Update recipe for paragone
  recipes/paragone/meta.yaml
  recipes/paragone/post-link.sh
  recipes/paragone/pre-unlink.sh
Labels: please review & merge

#49204 Add MethBat to bioconda recipes
  recipes/methbat/build.sh
  recipes/methbat/meta.yaml
Labels: please review & merge

#49251 Update hicap recipe
  recipes/hicap/meta.yaml
Labels: please review & merge

#49245 viguno: add linux-aarch64 build
  recipes/viguno/meta.yaml
Labels: please review & merge, aarch64

#49246 knotinframe & bellmans-gapc: add linux-aarch64 build
  recipes/bellmans-gapc/build.sh
  recipes/bellmans-gapc/meta.yaml
  recipes/knotinframe/build.sh
  recipes/knotinframe/meta.yaml
Labels: please review & merge, aarch64

#49256 r-rrbgen: add aarch64/arm64 builds
  recipes/r-rrbgen/meta.yaml
Labels: please review & merge, aarch64

#49257 architeuthis: add aarch64/arm64 builds
  recipes/architeuthis/meta.yaml
Labels: please review & merge, aarch64

#49247 egglib: add aarch64/arm64 builds
  recipes/egglib/meta.yaml
Labels: please review & merge, aarch64

#49263 gtdb_to_taxdump: rename yml to yaml
  recipes/gtdb_to_taxdump/meta.yaml
Labels: please review & merge

#49275 Build mappy on macOS ARM
  recipes/mappy/meta.yaml
Labels: please review & merge, osx-arm64

#49273 Update ORFanage to 1.2.0
  recipes/orfanage/meta.yaml
Labels: please review & merge

#49278 Update DAJIN2
  recipes/dajin2/meta.yaml
Labels: please review & merge

#49282 Pinned minimap2 version in liftoff
  recipes/liftoff/meta.yaml
Labels: please review & merge

#49299 Update pixelator to 0.18.2
  recipes/pixelator/meta.yaml
Labels: please review & merge

#49260 pytrf: add aarch64/arm64 builds
  recipes/pytrf/meta.yaml
Labels: please review & merge, aarch64

#49296 ucsc-pslsort: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-pslsort/build.sh
  recipes/ucsc-pslsort/include.patch
  recipes/ucsc-pslsort/meta.yaml
Labels: please review & merge, aarch64

#49298 ucsc-nibfrag: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-nibfrag/build.sh
  recipes/ucsc-nibfrag/include.patch
  recipes/ucsc-nibfrag/meta.yaml
Labels: please review & merge, aarch64

#49289 libbigwig: add osx-arm64 build
  recipes/libbigwig/meta.yaml
Labels: please review & merge, aarch64

#49301 ucsc-xmlcat: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-xmlcat/build.sh
  recipes/ucsc-xmlcat/include.patch
  recipes/ucsc-xmlcat/meta.yaml
Labels: please review & merge, aarch64

#49302 ucsc-toLower: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-tolower/build.sh
  recipes/ucsc-tolower/include.patch
  recipes/ucsc-tolower/meta.yaml
Labels: please review & merge, aarch64

#49286 orfanage: add aarch64/arm64 builds
  recipes/orfanage/build.sh
  recipes/orfanage/meta.yaml
Labels: please review & merge, aarch64

#49293 fastp: add osx-arm64 build
  recipes/fastp/build.sh
  recipes/fastp/meta.yaml
Labels: please review & merge

#49132 r-stitch: add linux-aarch64 build
  recipes/r-stitch/build.sh
  recipes/r-stitch/conda_build_config.yaml
  recipes/r-stitch/meta.yaml
  recipes/r-stitch/seqlib-aarch64.patch
Labels: please review & merge, aarch64

#49285 strainr2: add aarch64/arm64 builds
  recipes/strainr2/meta.yaml
Labels: please review & merge, aarch64

#49310 Add MetaCerberus-lite
  recipes/metacerberus-lite/meta.yaml
Labels: please review & merge

#49327 manual update v6.3.2
  recipes/proteinortho/meta.yaml
Labels: please review & merge

#49324 Build bwa on macOS ARM
  recipes/bwa/meta.yaml
Labels: please review & merge, osx-arm64

#49238 Update hmftools-neo to 1.2_beta
  recipes/hmftools-neo/meta.yaml
  recipes/hmftools-neo/neo.sh
Labels: please review & merge

#49326 Build bowtie on macOS ARM
  recipes/bowtie/build.sh
  recipes/bowtie/meta.yaml
Labels: please review & merge, osx-arm64

#49168 Add hmftools-esvee 1.0_beta
  recipes/hmftools-esvee/build.sh
  recipes/hmftools-esvee/esvee.sh
  recipes/hmftools-esvee/meta.yaml
Labels: please review & merge

#49074 Add longphase
  recipes/longphase/build.sh
  recipes/longphase/meta.yaml
Labels: please review & merge

#49332 ucsc-psltochain: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-psltochain/build.sh
  recipes/ucsc-psltochain/include.patch
  recipes/ucsc-psltochain/meta.yaml
Labels: please review & merge, aarch64

#49333 ucsc-stringify: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-stringify/build.sh
  recipes/ucsc-stringify/include.patch
  recipes/ucsc-stringify/meta.yaml
Labels: please review & merge, aarch64

#49335 ucsc-psltobed: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-psltobed/build.sh
  recipes/ucsc-psltobed/include.patch
  recipes/ucsc-psltobed/meta.yaml
Labels: please review & merge, aarch64

#49336 ucsc-oligomatch: add linux-aarch64 build
  build-fail-blacklist
  recipes/ucsc-oligomatch/build.sh
  recipes/ucsc-oligomatch/include.patch
  recipes/ucsc-oligomatch/meta.yaml
Labels: please review & merge, aarch64

#49342 kalign3: add aarch64/arm64 builds
  recipes/kalign3/build.sh
  recipes/kalign3/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49343 cancerit-allelecount: add linux-aarch64 build
  recipes/cancerit-allelecount/build.sh
  recipes/cancerit-allelecount/meta.yaml
Labels: please review & merge, aarch64

#49347 fido: add linux-aarch64 build
  recipes/fido/build.sh
  recipes/fido/meta.yaml
Labels: please review & merge, aarch64

#49346 famsa: add aarch64/arm64 builds
  recipes/famsa/build.sh
  recipes/famsa/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#49356 Update crispresso2: osx-arm64 additional platform
  recipes/crispresso2/meta.yaml
Labels: please review & merge, osx-arm64
