Repository bioconda/bioconda-recipes, pull requests merged in 2024-10, with the labels that each got.

#51067 bambamc: add aarch64/arm64 builds
  recipes/bambamc/build.sh
  recipes/bambamc/config.guess
  recipes/bambamc/config.sub
  recipes/bambamc/meta.yaml
  recipes/smalt/build.sh
Labels: please review & merge, aarch64, osx-arm64

#51098 gappa: add arm64 build
  recipes/gappa/build.sh
  recipes/gappa/meta.yaml
Labels: osx-arm64

#51092 Update Hsdfinder
  recipes/hsdfinder/meta.yaml
Labels: please review & merge

#51084 Bump nanosim build
  recipes/nanosim/build.sh
  recipes/nanosim/meta.yaml
Labels: please review & merge

#51102 galaxy_sequence_util: pin python
  recipes/galaxy_sequence_utils/meta.yaml
Labels: please review & merge

#51090 Update PhyloAcc recipe
  recipes/phyloacc/meta.yaml
Labels: please review & merge

#51107 perl-convert-binary-c: add aarch64/arm64 build
  recipes/perl-convert-binary-c/build.sh
  recipes/perl-convert-binary-c/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51106 metacache: add linux-aarch64 build
  recipes/metacache/build.sh
  recipes/metacache/meta.yaml
Labels: please review & merge, aarch64

#51105 pyslow5: add aarch64/arm64 builds
  recipes/pyslow5/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#50836 tidk v0.2.62
  recipes/tidk/build.sh
  recipes/tidk/meta.yaml
Labels: please review & merge

#51123 Use medium VM for Linux ARM64
  .circleci/config.yml
Labels: aarch64

#51121 longreadsum: add aarch64/arm64 builds
  recipes/longreadsum/build_failure.linux-64.yaml
  recipes/longreadsum/build_failure.osx-64.yaml
  recipes/longreadsum/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51120 gxf2bed: add aarch64/arm64 builds
  recipes/gxf2bed/build.sh
  recipes/gxf2bed/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51136 lighter: add aarch64/arm64 builds
  recipes/lighter/build.sh
  recipes/lighter/meta.yaml
Labels: aarch64, osx-arm64

#50103 tracs: add aarch64/arm64 builds
  recipes/tracs/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51151 Add hmftools-redux 1.0_beta
  recipes/hmftools-redux/build.sh
  recipes/hmftools-redux/meta.yaml
  recipes/hmftools-redux/redux.sh
Labels: please review & merge

#51141 Update hmftools-amber to 4.1_beta
  recipes/hmftools-amber/meta.yaml
Labels: please review & merge

#51150 Add hmftools-peach 2.0.0
  recipes/hmftools-peach/build.sh
  recipes/hmftools-peach/meta.yaml
  recipes/hmftools-peach/peach.sh
Labels: please review & merge

#51143 Update hmftools-cobalt to 2.0_beta
  recipes/hmftools-cobalt/meta.yaml
Labels: please review & merge

#51147 Update hmftools-sage to 4.0_beta
  recipes/hmftools-sage/meta.yaml
Labels: please review & merge

#51159 tidk: add aarch64/arm64 builds
  recipes/tidk/build.sh
  recipes/tidk/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51124 phables: add aarch64/arm64 builds
  recipes/phables/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51161 mashmap: add aarch64 build
  recipes/mashmap/build.sh
  recipes/mashmap/meta.yaml
Labels: please review & merge, aarch64

#51176 updated revision and enabled osx build
  recipes/pgrc/meta.yaml
Labels: please review & merge

#51178 Add get_mnv
  recipes/get_mnv/meta.yaml
Labels: please review & merge

#50861 Add gsmap
  recipes/gsmap/meta.yaml
Labels: please review & merge

#51202 Update orthofinder for 3.0.1b1 beta release
  recipes/orthofinder/build.sh
  recipes/orthofinder/meta.yaml
Labels: please review & merge

#51205 Update pyliftover to 0.4.1
  recipes/pyliftover/meta.yaml
Labels: please review & merge

#51184 added arm and aarch64 builds
  recipes/mbgc/asmlib_off.patch
  recipes/mbgc/build.sh
  recipes/mbgc/meta.yaml
Labels: please review & merge

#51201 Update pgscatalog.core to 0.3.1
  recipes/pgscatalog.core/meta.yaml
Labels: please review & merge

#51222 Update pgscatalog.calc to 0.3.0
  recipes/pgscatalog.calc/meta.yaml
Labels: please review & merge

#51203 r-cobrar: add aarch64/arm64 builds
  recipes/r-cobrar/meta.yaml
Labels: aarch64, osx-arm64

#51220 Update meta.yaml, VITAP v.1.7
  recipes/vitap/meta.yaml
Labels: please review & merge

#51153 Add Snk-CLI
  recipes/snk-cli/meta.yaml
Labels: please review & merge

#51145 Update hmftools-orange to 3.7.1_beta
  recipes/hmftools-orange/meta.yaml
Labels: please review & merge

#51241 Revert back to medium VM for Linux aarch64.
  .circleci/config.yml
Labels: aarch64

#51239 Update piawka
  recipes/piawka/build.sh
  recipes/piawka/meta.yaml
Labels: please review & merge

#51206 pepnovo: add aarch64/arm64 build
  build-fail-blacklist
  recipes/pepnovo/.gitattributes
  recipes/pepnovo/0002-fix-float-positive-infinity.patch
  recipes/pepnovo/build.sh
  recipes/pepnovo/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51246 Update gfastats tool version
  recipes/gfastats/meta.yaml
Labels: please review & merge

#51190 get_mnv: add aarch64/arm64 builds
  recipes/get_mnv/get_mnv-aarch64.patch
  recipes/get_mnv/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51242 Update pgscatalog.match to 0.3.3
  recipes/pgscatalog.match/meta.yaml
Labels: please review & merge

#51258 `pggb`: update `vg` to v 1.59.0
  recipes/pggb/meta.yaml
Labels: please review & merge

#51152 Add Snk
  recipes/snk/meta.yaml
Labels: please review & merge

#51263 Update Woltka to 0.1.7
  recipes/woltka/meta.yaml
Labels: please review & merge

#51149 Add hmftools-chord 2.1.0_beta
  recipes/hmftools-chord/LICENSE
  recipes/hmftools-chord/build.sh
  recipes/hmftools-chord/chord.sh
  recipes/hmftools-chord/meta.yaml
Labels: please review & merge

#51256 Fix pgscatalog-utils 1.4.1
  recipes/pgscatalog-utils/meta.yaml
Labels: please review & merge

#49740 Update kmer-db
  recipes/kmer-db/build.sh
  recipes/kmer-db/meta.yaml
Labels: please review & merge

#51238 Update Earl Grey meta.yaml
  recipes/earlgrey/meta.yaml
Labels: please review & merge

#51267 kmercamel: add aarch64/arm64 builds
  recipes/kmercamel/build.sh
  recipes/kmercamel/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51278 Update Harpy deps
  recipes/harpy/meta.yaml
Labels: please review & merge

#49578 Add lz-ani
  recipes/lz-ani/meta.yaml
Labels: please review & merge

#51091 add sipros
  recipes/sipros/LICENSE
  recipes/sipros/Raxport.sh
  recipes/sipros/build.sh
  recipes/sipros/copyConfigTemplate.sh
  recipes/sipros/meta.yaml
Labels: please review & merge

#51281 kmc: add arm64 build
  recipes/kmc/build.sh
  recipes/kmc/meta.yaml
Labels: osx-arm64

#51224 Update PhyloAcc recipe
  recipes/phyloacc/meta.yaml
  recipes/phyloacc/run_test.sh
Labels: please review & merge

#50983 add pantax
  recipes/pantax/build.sh
  recipes/pantax/meta.yaml
Labels: please review & merge

#51322 Updating gfastats tool recipe with tarball source
  recipes/gfastats/meta.yaml
Labels: please review & merge

#51324 Update Earl Grey build.sh
  recipes/earlgrey/build.sh
  recipes/earlgrey/meta.yaml
Labels: please review & merge

#51337 Update busco to v5.8.0
  recipes/busco/build.sh
  recipes/busco/meta.yaml
Labels: please review & merge

#51314 Update Saccharis
  recipes/saccharis/meta.yaml
Labels: please review & merge

#51342 Update rna-seqc to 2.4.2
  recipes/rna-seqc/build.sh
  recipes/rna-seqc/meta.yaml
Labels: please review & merge

#51346 Update to Cenote-Taker 3 v3.3.2
  recipes/cenote-taker3/meta.yaml
Labels: please review & merge

#51317 Don't remove DIA-NN from FragPipe installation.
  recipes/fragpipe/build.sh
  recipes/fragpipe/fragpipe
  recipes/fragpipe/licenses/diann_LICENSE.txt
  recipes/fragpipe/meta.yaml
Labels: please review & merge

#51294 Update hmftools-{esvee,purple,linx,redux}
  recipes/hmftools-esvee/meta.yaml
  recipes/hmftools-linx/meta.yaml
  recipes/hmftools-purple/meta.yaml
  recipes/hmftools-redux/meta.yaml
Labels: please review & merge

#51328 Add meta_eukaryome_detect
  recipes/meta_eukaryome_detect/meta.yml
Labels: please review & merge

#51343 Add `cosigt`
  recipes/cosigt/build.sh
  recipes/cosigt/meta.yaml
Labels: please review & merge

#51366 Update meta_eukaryome_detect: Rename meta.yml to meta.yaml
  recipes/meta_eukaryome_detect/meta.yaml
Labels: please review & merge

#51367 Add sopa package
  sopa/meta.yaml
Labels: please review & merge

#51326 Add seqspec
  recipes/seqspec/meta.yaml
Labels: please review & merge

#51376 gnparser: add aarch64/arm64 builds
  recipes/gnparser/build.sh
  recipes/gnparser/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51391 update cosigt to v0.1.2
  recipes/cosigt/meta.yaml
Labels: please review & merge

#51398 Generate some older R builds for `r-presto`
  recipes/r-presto/conda_build_config.yaml
  recipes/r-presto/meta.yaml
Labels: please review & merge

#51370 devider: add aarch64/arm64 builds
  recipes/devider/build.sh
  recipes/devider/devider-aarch64.patch
  recipes/devider/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51277 Add FMSI
  recipes/fmsi/0001-Makefile.patch
  recipes/fmsi/0002-version.patch
  recipes/fmsi/build.sh
  recipes/fmsi/meta.yaml
Labels: help wanted, aarch64

#51417 lofreq: add osx-arm64 build
  recipes/lofreq/0001-patches
  recipes/lofreq/build.sh
  recipes/lofreq/build_failure.osx-64.yaml
  recipes/lofreq/meta.yaml
Labels: osx-arm64

#51421 Update vcf-validator to v0.10.0
  recipes/vcf-validator/LICENSE_ODB
  recipes/vcf-validator/build.sh
  recipes/vcf-validator/meta.yaml
Labels: please review & merge

#51440 Update HATCHeT to 2.1.0
  recipes/hatchet/meta.yaml
Labels: please review & merge

#51447 Update mess recipe
  recipes/mess/meta.yaml
Labels: please review & merge

#51446 cloudspades: add linux-aarch64 build
  .circleci/config.yml
  recipes/cloudspades/build.sh
  recipes/cloudspades/meta.yaml
Labels: please review & merge, aarch64

#51425 vcf-validator: add linux-aarch64 build
  recipes/vcf-validator/build.sh
  recipes/vcf-validator/meta.yaml
Labels: please review & merge, aarch64

#51448 genbank: add aarch64/arm64 builds
  recipes/genbank/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51465 Update annembed to v0.1.5
  recipes/annembed/build.sh
  recipes/annembed/meta.yaml
Labels: please review & merge

#51456 Update Cloudspades
  recipes/cloudspades/build.sh
  recipes/cloudspades/meta.yaml
Labels: please review & merge

#51476 Add gene-trajectory-python recipe
  recipes/gene-trajectory-python/LICENSE
  recipes/gene-trajectory-python/meta.yaml
Labels: please review & merge

#50881 Update hictk to v2.0.0
  recipes/hictk/build.sh
  recipes/hictk/conan_profiles/clang
  recipes/hictk/conanfile.Dockerfile.py.patch
  recipes/hictk/conanfile.py.patch
  recipes/hictk/conda_build_config.yaml
  recipes/hictk/meta.yaml
  recipes/hictk/run_test.sh
Labels: please review & merge

#51516 pybbi: add linux-aarch64 build
  recipes/pybbi/meta.yaml
Labels: please review & merge, aarch64

#51517 centrifuge-core: add linux-aarch64 build
  recipes/centrifuge-core/build.sh
  recipes/centrifuge-core/meta.yaml
Labels: aarch64

#51520 Add splash
  recipes/splash/meta.yaml
Labels: please review & merge

#51490 Add `pyhmmsearch`
  recipes/pyhmmsearch/meta.yaml
Labels: please review & merge

#51540 Update `cosigt` to version 0.1.3
  recipes/cosigt/meta.yaml
Labels: please review & merge

#51513 Add snipe
  recipes/snipe/meta.yaml
Labels: please review & merge

#51438 Initial add telosearchlr-v1.0.0
  recipes/telosearchlr/build.sh
  recipes/telosearchlr/meta.yaml
Labels: please review & merge

#51426 Update GW to v1.1.1
  recipes/gw/build.sh
  recipes/gw/conda_build_config.yaml
  recipes/gw/meta.yaml
Labels: please review & merge

#51488 Add genodsp
  recipes/genodsp/build.sh
  recipes/genodsp/meta.yaml
  recipes/genodsp/stringop-truncation.patch
Labels: please review & merge

#51557 Sainsc: adjust dependencies
  recipes/sainsc/meta.yaml
Labels: please review & merge

#51309 Add zamp
  recipes/zamp/meta.yaml
Labels: please review & merge

#51552 Update matchms dependencies
  recipes/matchms/meta.yaml
Labels: please review & merge

#51468 Add r-saccharis
  recipes/r-saccharis/LICENSE.md
  recipes/r-saccharis/build.sh
  recipes/r-saccharis/conda_build_config.yaml
  recipes/r-saccharis/meta.yaml
Labels: please review & merge

#51550 Bump pyfastani to v0.6.0
  recipes/pyfastani/meta.yaml
Labels: please review & merge

#51537 Add `pykofamsearch`
  recipes/pykofamsearch/meta.yaml
Labels: please review & merge

#49759 Pegas
  recipes/pegas/meta.yaml
Labels: please review & merge

#51597 genodsp: add linux-aarch64 build
  recipes/genodsp/meta.yaml
Labels: aarch64

#51584 Update iSeq
  recipes/iseq/meta.yaml
Labels: please review & merge

#51612 add recipe for steamboat
  recipes/steamboat/meta.yaml
Labels: please review & merge

#51608 Fix pgscatalog-utils patch update 1.4.2
  recipes/pgscatalog-utils/meta.yaml
Labels: please review & merge

#51643 Add svtopovz python package
  recipes/svtopovz/meta.yaml
Labels: please review & merge

#51661 Build bindash on osx
  recipes/bindash/build.sh
  recipes/bindash/meta.yaml
Labels: osx-arm64

#51671 genoflu version 1.04
  recipes/genoflu/meta.yaml
Labels: please review & merge

#51679 Update Saccharis
  recipes/saccharis/meta.yaml
Labels: please review & merge

#51684 Update poseidon-trident to 1.5.7.0
  recipes/poseidon-trident/meta.yaml
Labels: please review & merge

#51665 Add svtopo recipe
  recipes/svtopo/build.sh
  recipes/svtopo/meta.yaml
Labels: please review & merge

#51598 d4binding: add aarch64/arm64 builds
  recipes/d4binding/build.sh
  recipes/d4binding/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#51349 add meta
  recipes/meta/build.sh
  recipes/meta/meta.yaml
Labels: please review & merge

#51715 prodigal-gv: add aarch64/arm64 builds
  recipes/prodigal-gv/build.sh
  recipes/prodigal-gv/meta.yaml
Labels: aarch64, osx-arm64

#51714 miniprot: add aarch64/arm64 builds
  recipes/miniprot/build.sh
  recipes/miniprot/meta.yaml
Labels: aarch64, osx-arm64

#51688 add ampd-up v1.0.0
  recipes/ampd-up/build.sh
  recipes/ampd-up/meta.yaml
Labels: please review & merge

#51692 Update vclust to 1.2.8
  recipes/vclust/meta.yaml
Labels: please review & merge

#51698 Update hmftools-{esvee,linx,purple,redux,sage}
  recipes/hmftools-esvee/meta.yaml
  recipes/hmftools-linx/meta.yaml
  recipes/hmftools-purple/meta.yaml
  recipes/hmftools-redux/meta.yaml
  recipes/hmftools-sage/meta.yaml
Labels: please review & merge

#51764 Add coptr
  recipes/coptr/meta.yaml
Labels: please review & merge

#51754 Update chopper for M3s
  recipes/chopper/meta.yaml
Labels: please review & merge

#51769 bump prodigal-gv build number
  recipes/prodigal-gv/meta.yaml
Labels: please review & merge

#51768 bump sainsc build number
  recipes/sainsc/meta.yaml
Labels: please review & merge

#51802 Update meta.yaml
  recipes/resistify/meta.yaml
Labels: please review & merge

#51835 Update TIRmite recipe
  recipes/tirmite/meta.yaml
Labels: please review & merge

#51845 Update seqscreen meta.yaml
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#51829 Update - add setuptools to host requirements as hybpiper conda build now failing without it
  recipes/hybpiper/meta.yaml
Labels: please review & merge

#51561 hictkpy: add v1.0.0
  recipes/hictkpy/CMakeLists.txt.patch
  recipes/hictkpy/build.sh
  recipes/hictkpy/conan_profiles/clang
  recipes/hictkpy/conanfile.py.patch
  recipes/hictkpy/conanfile.txt.patch
  recipes/hictkpy/conda_build_config.yaml
  recipes/hictkpy/meta.yaml
  recipes/hictkpy/pyproject.toml.patch
  recipes/hictkpy/run_test.sh
Labels: please review & merge

#51800 Update hmftools-purple and hmftools-orange
  recipes/hmftools-orange/meta.yaml
  recipes/hmftools-purple/meta.yaml
Labels: please review & merge
