Repository bioconda/bioconda-recipes, pull requests merged in 2025-05, with the labels that each got.

#55619 Add Bioconda recipe for amalgkit
  recipes/amalgkit/meta.yaml
Labels: please review & merge

#55671 Add recipe for MoGAAAP
  recipes/mogaaap/LICENSE
  recipes/mogaaap/meta.yaml
Labels: please review & merge

#55841 Update graphembed v0.1.7
  recipes/graphembed/meta.yaml
Labels: please review & merge

#55844 Update PIPITS to 4.0 with changes to dependencies
  recipes/pipits/meta.yaml
Labels: please review & merge

#55855 Update unifrac-binaries to v1.5
  recipes/unifrac-binaries/build.sh
  recipes/unifrac-binaries/build_failure.osx-64.yaml
  recipes/unifrac-binaries/meta.yaml
Labels: please review & merge

#55822 sneep: add linux-aarch64
  recipes/sneep/build.sh
  recipes/sneep/conda_build_config.yaml
  recipes/sneep/meta.yaml
Labels: please review & merge

#55865 Update aniclustermap to 2.0.1
  recipes/aniclustermap/meta.yaml
  recipes/aniclustermap/run_test.sh
Labels: please review & merge

#55866 Update FROGS v5.0.2
  recipes/frogs/meta.yaml
Labels: please review & merge

#55864 Add pyani-plus
  recipes/pyani-plus/meta.yaml
Labels: please review & merge

#55850 kernel_density_plots version 0.1
  recipes/kernel_density_plots/build.sh
  recipes/kernel_density_plots/meta.yaml
Labels: please review & merge

#55789 Add oligon-design
  recipes/oligon-design/build.sh
  recipes/oligon-design/meta.yaml
Labels: please review & merge

#55873 Update Phylogenize
  recipes/phylogenize/build.sh
  recipes/phylogenize/meta.yaml
Labels: please review & merge

#55719 Add recipe for pgap2 version 1.0.3
  recipes/pgap2/meta.yaml
Labels: please review & merge

#55694 Add kractor v1.0.0
  recipes/kractor/build.sh
  recipes/kractor/meta.yaml
Labels: please review & merge

#55878 regtools: add arm64 build
  recipes/regtools/build.sh
  recipes/regtools/build_failure.osx-64.yaml
  recipes/regtools/meta.yaml
Labels: MacOS related, osx-arm64

#55725 recipe for tomm40_wgs
  recipes/tomm40_wgs/LICENSE
  recipes/tomm40_wgs/build.sh
  recipes/tomm40_wgs/licenses/ExpansionHunter-LICENCE
  recipes/tomm40_wgs/licenses/GangSTR-LICENCE
  recipes/tomm40_wgs/licenses/HipSTR-LICENCE
  recipes/tomm40_wgs/licenses/TOMM40_WGS-LICENSE-INFO
  recipes/tomm40_wgs/meta.yaml
Labels: please review & merge

#55090 Update rDock to v24.04.204-legacy
  build-fail-blacklist
  recipes/rdock/NMObjective.h.patch
  recipes/rdock/activate.sh
  recipes/rdock/build.sh
  recipes/rdock/deactivate.sh
  recipes/rdock/meta.yaml
  recipes/rdock/rDock_fix_paths.patch
  recipes/rdock/rDock_python_fixes.patch
  recipes/rdock/wrapper.sh
Labels: please review & merge

#53458 Add StemCNV-check
  recipes/stemcnv-check/meta.yaml
Labels: please review & merge

#55839 Add mameshiba recipe
  recipes/mameshiba/meta.yaml
Labels: please review & merge

#55883 rdock: add numpy version constraint
  recipes/rdock/activate.sh
  recipes/rdock/deactivate.sh
  recipes/rdock/meta.yaml
Labels: please review & merge

#55907 update starfusion to 1.15.0
  recipes/star-fusion/meta.yaml
Labels: please review & merge

#55900 Update bwa-mem2 dependency
  recipes/bwameth/meta.yaml
Labels: please review & merge

#55343 Update fusionreport
  recipes/fusion-report/meta.yaml
Labels: please review & merge

#54744 Add genedom recipe
  recipes/genedom/meta.yaml
  recipes/genedom/patches/0001-restrict-installed-modules.patch
Labels: please review & merge

#55894 Update flye 2.9.6
  recipes/flye/meta.yaml
Labels: please review & merge, new version

#55934 bwapy: add linux-aarch64
  recipes/bwapy/meta.yaml
Labels: please review & merge

#55753 phipack: add linux-aarch64
  recipes/phipack/conda_build_config.yaml
  recipes/phipack/meta.yaml
Labels: please review & merge

#55915 Add sunbeamlib recipe
  recipes/sunbeamlib/meta.yaml
Labels: please review & merge

#55888 Update mameshiba to v0.6.1
  recipes/mameshiba/meta.yaml
Labels: please review & merge

#55926 update version 1.0.0rc
  recipes/quota_anchor/meta.yaml
Labels: please review & merge

#55871 Rebuild bioconductor-metmashr v1.0.0 and include suggests
  recipes/bioconductor-metmashr/meta.yaml
Labels: please review & merge

#55946 Adding parasail v2.6.2
  recipes/parasail/build.sh
  recipes/parasail/meta.yaml
Labels: please review & merge

#55955 Update `pyhmmer` to pin `psutil` and `cython` version
  recipes/pyhmmer/meta.yaml
Labels: please review & merge

#55983 Update ervmancer to 0.0.3
  recipes/ervmancer/meta.yaml
Labels: please review & merge

#55957 mtbseq: adds linux-aarch64
  recipes/mtbseq/meta.yaml
  recipes/samtools/1.6/meta.yaml
Labels: please review & merge

#55954 add recipe for snakemake-executor-plugin-cannon
  recipes/snakemake-executor-plugin-cannon/meta.yaml
Labels: please review & merge

#55968 fix dependency for recipe Argo
  recipes/argo/meta.yaml
Labels: please review & merge

#55967 update taxor version to 0.2.1
  recipes/taxor/build.sh
  recipes/taxor/meta.yaml
Labels: please review & merge

#55897 Update meta.yaml v3
  recipes/egap/build.sh
  recipes/egap/meta.yaml
Labels: please review & merge

#55932 Add r-ctree
  recipes/r-ctree/build.sh
  recipes/r-ctree/meta.yaml
Labels: please review & merge

#55994 Update quota_anchor to 1.0.0
  recipes/quota_anchor/meta.yaml
Labels: please review & merge

#55991 Rebuild snap-aligner
  recipes/snap-aligner/0001-Makefile.patch
  recipes/snap-aligner/0002-snap-aligner-aarch64.patch
  recipes/snap-aligner/0003-header.patches
  recipes/snap-aligner/0004-main.cpp.patch
  recipes/snap-aligner/build.sh
  recipes/snap-aligner/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#56002 Update vg to v1.65.0
  recipes/vg/meta.yaml
Labels: please review & merge

#55861 Add r-amlmapr
  recipes/r-amlmapr/meta.yaml
Labels: please review & merge

#56029 Update EUKulele to v2.1.2
  recipes/eukulele/meta.yaml
Labels: please review & merge

#56038 fix sed command to touch the correct file
  recipes/ltr_harvest_parallel/build.sh
  recipes/ltr_harvest_parallel/meta.yaml
Labels: please review & merge

#56007 Add r-mobster
  recipes/r-dndscv/build.sh
  recipes/r-dndscv/meta.yaml
  recipes/r-mobster/build.sh
  recipes/r-mobster/meta.yaml
Labels: please review & merge

#56036 Updata pgap2 from 1.0.3 to 1.0.4
  recipes/pgap2/meta.yaml
Labels: please review & merge

#56042 Add gene-fetch v1.0.9
  recipes/gene-fetch/meta.yaml
Labels: please review & merge

#56032 Update cdskit to 0.14.4
  recipes/cdskit/meta.yaml
Labels: please review & merge

#55982 Updated meta.yaml
  recipes/mysterymaster/meta.yaml
Labels: please review & merge

#56004 Update: amalgkit 0.12.16 with full dependencies
  recipes/amalgkit/meta.yaml
Labels: please review & merge

#55922 Update longcalld v0.0.4
  recipes/longcalld/meta.yaml
Labels: please review & merge

#55933 Add recipe for `igua` Python package
  recipes/igua/meta.yaml
Labels: please review & merge

#55524 Add Voronota v1.29.4370
  recipes/voronota/build.sh
  recipes/voronota/meta.yaml
Labels: please review & merge

#55591 Add csubst v1.4.17
  recipes/csubst/meta.yaml
Labels: please review & merge

#55512 Add recipe for cuteSV-OL
  recipes/cutesv-ol/build.sh
  recipes/cutesv-ol/meta.yaml
Labels: please review & merge

#55655 Add kanpig recipe
  recipes/kanpig/build.sh
  recipes/kanpig/meta.yaml
Labels: please review & merge

#55773 Update MethylDackel: add mac ARM build
  recipes/methyldackel/meta.yaml
Labels: please review & merge

#56031 Update plassembler canu dependency >=2.2
  recipes/plassembler/meta.yaml
Labels: please review & merge

#56069 parasail: Fix extra section
  recipes/parasail/build.sh
  recipes/parasail/meta.yaml
Labels: please review & merge

#56083 Update libcarna to 3.4.0
  recipes/libcarna/build.sh
  recipes/libcarna/meta.yaml
  recipes/libcarna/test/CMakeLists.txt
  recipes/libcarna/test/test.cpp
Labels: please review & merge

#56064 Update Egap recipe to v3.0.0f
  recipes/egap/build.sh
  recipes/egap/meta.yaml
Labels: please review & merge

#56056 Add: reactome cli recipe to bioconda recipes
  recipes/reactome-cli/build.sh
  recipes/reactome-cli/meta.yaml
  recipes/reactome-cli/reactome.sh
Labels: please review & merge

#56101 ECTYPER v2.0.0 Updated build to #4 due to BioPython issue AttributeError: 'FastaWrit…
  recipes/ectyper/meta.yaml
Labels: please review & merge

#56106 Update ncbi-amrfinderplus to 4.0.23
  recipes/ncbi-amrfinderplus/meta.yaml
Labels: new version

#56107 Rebuild cpat recipe
  recipes/cpat/build.sh
  recipes/cpat/meta.yaml
Labels: osx-arm64

#56005 Add r-viber
  recipes/r-viber/build.sh
  recipes/r-viber/meta.yaml
Labels: please review & merge

#56030 Update singlem: Update to 0.19.0.
  recipes/singlem/meta.yaml
Labels: please review & merge

#56109 Update twilight to v0.1.3
  recipes/twilight/CMakeLists.txt
  recipes/twilight/build.sh
  recipes/twilight/meta.yaml
Labels: please review & merge

#56116 Update/sigprofilerassignment 0.2.2
  recipes/sigprofilerassignment/meta.yaml
Labels: please review & merge

#56117 iow: add arm64 build
  recipes/iow/build.sh
  recipes/iow/meta.yaml
Labels: osx-arm64

#55654 Add nwkit recipe (v0.17.2)
  recipes/nwkit/meta.yaml
Labels: please review & merge

#56110 Add blobtk v0.6.5 recipe
  recipes/blobtk/build.sh
  recipes/blobtk/meta.yaml
Labels: osx-arm64

#56129 genomepy: fix mysql (again)
  recipes/genomepy/meta.yaml
Labels: please review & merge

#56131 Bump biophi to 1.0.11
  recipes/biophi/meta.yaml
Labels: please review & merge

#56027 Add dampa
  recipes/dampa/meta.yaml
Labels: please review & merge

#56132 Rebuild openms-meta recipe
  recipes/openms-meta/build.sh
  recipes/openms-meta/meta.yaml
Labels: aarch64

#56139 Fix PICRUSt2 v2.6.2
  recipes/picrust2/meta.yaml
  recipes/picrust2/post-link.sh
Labels: please review & merge

#56142 Update dmox to 0.2.1
  recipes/dmox/meta.yaml
Labels: please review & merge

#56173 meme 4.11.2: reenable and add linux-aarch64
  build-fail-blacklist
  recipes/meme/4.11.2/meta.yaml
Labels: please review & merge

#56162 Add recipe for gbdraw v0.1.0
  recipes/gbdraw/meta.yaml
Labels: please review & merge

#56180 Added fa-lint
  recipes/fa-lint/build.sh
  recipes/fa-lint/meta.yaml
Labels: please review & merge

#56197 Bump bioconda-repodata-patches for new libdeflate release
  recipes/bioconda-repodata-patches/gen_patch_json.py
Labels: please review & merge

#56195 Update mirmachine meta.yaml
  recipes/mirmachine/meta.yaml
Labels: please review & merge

#56082 Added juicebox_scripts
  recipes/juicebox_scripts/build.sh
  recipes/juicebox_scripts/meta.yaml
Labels: please review & merge

#56177 Add fastreer 1.13.20
  recipes/fastreer/build.sh
  recipes/fastreer/meta.yaml
Labels: please review & merge

#56199 Update pyOpenMS to 3.4
  recipes/pyopenms/build.sh
  recipes/pyopenms/meta.yaml
Labels: please review & merge

#56214 Add recipe for LibCarna-Python
  recipes/libcarna-python/build.sh
  recipes/libcarna-python/meta.yaml
Labels: please review & merge

#55643 sipros limit mono version
  recipes/sipros/meta.yaml
Labels: please review & merge

#56226 Update meta.yaml for kb-python
  recipes/kb-python/meta.yaml
Labels: please review & merge

#56234 Update gbdraw to v0.1.1
  recipes/gbdraw/meta.yaml
Labels: please review & merge

#56181 antismash-lite: add linux-aarch64
  recipes/antismash-lite/meta.yaml
Labels: please review & merge

#56179 Add pcdl physicell data loader bioconda recipe
  recipes/pcdl/meta.yaml
Labels: please review & merge

#56258 vsnp3 version 3.29
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#56265 Update Egap recipe v3.1
  recipes/egap/meta.yaml
Labels: please review & merge

#56257 fix pcaone recipe
  recipes/pcaone/build.sh
  recipes/pcaone/meta.yaml
Labels: please review & merge

#56277 Update longbow to 2.3.1
  recipes/longbow/meta.yaml
Labels: please review & merge

#56185 New longcallr
  recipes/longcallr/build.sh
  recipes/longcallr/meta.yaml
Labels: please review & merge

#56279 Update OpenMS to 3.4.1
  recipes/openms-meta/meta.yaml
Labels: please review & merge

#56280 Vsnp3
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#56248 Update polap recipe: build 2
  recipes/polap/meta.yaml
Labels: please review & merge

#56186 Add radte 0.2.3 to bioconda
  recipes/radte/build.sh
  recipes/radte/meta.yaml
Labels: please review & merge

#56025 Added JuicerTools
  recipes/juicertools/build.sh
  recipes/juicertools/juicer_tools.sh
  recipes/juicertools/meta.yaml
Labels: please review & merge

#55970 Add Amira
  recipes/amira/meta.yaml
Labels: please review & merge

#55981 Add Recipe for UNetCoreograph package
  recipes/unetcoreograph/meta.yaml
Labels: please review & merge

#56013 TreeSwirl version 2
  recipes/treeswirl/build.sh
  recipes/treeswirl/meta.yaml
Labels: please review & merge

#56296 Update influx_si for r-nlsic >=1.1.0
  recipes/influx_si/meta.yaml
Labels: please review & merge

#56319 Update Mumemto to v1.3.0
  recipes/mumemto/build.sh
  recipes/mumemto/meta.yaml
Labels: please review & merge

#55492 Add recipe for pcne v0.1.0
  recipes/pcne/build.sh
  recipes/pcne/meta.yaml
Labels: please review & merge

#54780 build deepvariant by removing old skip
  recipes/deepvariant/build.sh
  recipes/deepvariant/meta.yaml
  recipes/deepvariant/post-link.sh
Labels: help wanted

#56313 Update metator to 1.3.10
  recipes/metator/meta.yaml
Labels: please review & merge

#56357 update to 3.7.1
  recipes/orthologer/meta.yaml
Labels: please review & merge

#56349 Update bamtools dependency
  recipes/ngs-disambiguate/meta.yaml
Labels: please review & merge

#56351 Update vclust to 1.3.1
  recipes/vclust/meta.yaml
Labels: please review & merge

#56347 Update RATT to v1.1.0
  build-fail-blacklist
  recipes/ratt/build.sh
  recipes/ratt/meta.yaml
  recipes/ratt/ratt_home.patch
Labels: please review & merge

#56374 Update gbdraw to v0.2.0
  recipes/gbdraw/meta.yaml
Labels: please review & merge

#56364 Update hictk to 2.1.2
  recipes/hictk/conanfile.Dockerfile.py.patch
  recipes/hictk/meta.yaml
Labels: please review & merge

#56343 Add seabreeze
  recipes/seabreeze-genomics/meta.yaml
Labels: please review & merge

#56244 medaka: fix license
  recipes/medaka/0001-setup.py.patch
  recipes/medaka/build.sh
  recipes/medaka/build_failure.linux-64.yaml
  recipes/medaka/meta.yaml
Labels: osx-arm64

#56368 Add suvtk
  recipes/suvtk/meta.yaml
Labels: please review & merge

#56400 Update OpenStructure to 2.10.0
  recipes/openstructure/conda.patch
  recipes/openstructure/meta.yaml
Labels: please review & merge

#56406 Update spaln to 3.0.7
  recipes/spaln/0001-configure.patch
  recipes/spaln/build.sh
  recipes/spaln/meta.yaml
Labels: MacOS related, osx-arm64

#56365 fix LTR_HARVEST_parallel that still does not work as expected
  recipes/ltr_harvest_parallel/build.sh
  recipes/ltr_harvest_parallel/meta.yaml
Labels: please review & merge

#56312 Add crossfilt
  recipes/crossfilt/meta.yaml
Labels: please review & merge

#56321 Sigprofilerextractor 1.2.1
  recipes/sigprofilerextractor/meta.yaml
Labels: please review & merge

#56382 Add quaqc
  recipes/quaqc/build.sh
  recipes/quaqc/meta.yaml
Labels: please review & merge

#56198 Add MetaCompass to bioconda
  recipes/metacompass/build.sh
  recipes/metacompass/meta.yaml
Labels: please review & merge

#56228 Update MSMS: Replace `msms` with `scripps-msms` and add `osx-arm64`
  recipes/msms/build.sh
  recipes/msms/meta.yaml
  recipes/scripps-msms/build.sh
  recipes/scripps-msms/meta.yaml
  recipes/scripps-msms/pdb_to_xyzr.patch
  recipes/scripps-msms/pdb_to_xyzrn.patch
  recipes/scripps-msms/run_test.sh
Labels: please review & merge

#55684 Update KAT to run on MacOS
  build-fail-blacklist
  recipes/kat/0001-install.patch
  recipes/kat/0002-libs.patch
  recipes/kat/0003-kat.patch
  recipes/kat/build.sh
  recipes/kat/meta.yaml
Labels: MacOS related

#56442 add rearr
  recipes/rearr/LICENSE.md
  recipes/rearr/meta.yaml
  recipes/rearr/run_test.sh
Labels: please review & merge

#56283 Add: marbel build recipe
  recipes/marbel/build.sh
  recipes/marbel/meta.yaml
Labels: please review & merge

#56454 pdbx: Change semantic versioning to commit hash use
  recipes/pdbx/build.sh
  recipes/pdbx/meta.yaml
Labels: please review & merge

#56460 Add vidjil-algo 2025.02
  recipes/vidjil-algo/meta.yaml
Labels: please review & merge

#56470 mcl: add arm64 build
  recipes/mcl/build.sh
  recipes/mcl/meta.yaml
Labels: osx-arm64

#56386 Adding PLINDER v0.2.25
  recipes/plinder/meta.yaml
Labels: please review & merge

#56476 beagle-lib: add arm64 build
  recipes/beagle-lib/build.sh
  recipes/beagle-lib/meta.yaml
  recipes/beagle-lib/osx_jni.patch
  recipes/beagle-lib/osx_ltdl.patch
Labels: osx-arm64

#56482 evidencemodeler: add arm64/aarch64 builds
  recipes/evidencemodeler/build.sh
  recipes/evidencemodeler/build_failure.osx-64.yaml
  recipes/evidencemodeler/meta.yaml
Labels: aarch64, osx-arm64

#56494 Update eva-sub-cli to 0.4.7
  recipes/eva-sub-cli/build.sh
  recipes/eva-sub-cli/meta.yaml
Labels: please review & merge

#56499 Update bioconductor-decipher: add osx-arm64 build
  recipes/bioconductor-decipher/meta.yaml
Labels: please review & merge

#56487 plinder: Add `mmpdb` to requirements
  recipes/plinder/meta.yaml
Labels: please review & merge

#56490 Adding ligand-validation v0.0.1
  recipes/ligand-validation/meta.yaml
Labels: please review & merge

#56459 Update MSFragger to Version 4.2
  recipes/msfragger/academic_install.py
  recipes/msfragger/build.sh
  recipes/msfragger/licenses/LICENSE-ACADEMIC.pdf
  recipes/msfragger/licenses/MSFragger-LICENSE-3RD-PARTY.txt
  recipes/msfragger/licenses/MSFragger-LICENSE.pdf
  recipes/msfragger/meta.yaml
Labels: please review & merge

#56515 Add wtv v0.0.2
  recipes/wtv/meta.yaml
Labels: please review & merge
