Repository bioconda/bioconda-recipes, pull requests merged in 2025-10, with the labels that each got.

#59789 Upgrade rnablueprint to v1.3.3
  recipes/rnablueprint/build.sh
  recipes/rnablueprint/build_failure.linux-64.yaml
  recipes/rnablueprint/build_failure.osx-64.yaml
  recipes/rnablueprint/meta.yaml
Labels: aarch64, osx-arm64

#59792 Rebuild bioconductor-rhisat2 recipe
  recipes/bioconductor-rhisat2/build.sh
  recipes/bioconductor-rhisat2/build_failure.osx-64.yaml
  recipes/bioconductor-rhisat2/meta.yaml
Labels: aarch64, osx-arm64

#59798 Rebuild eternafold recipe
  recipes/eternafold/build.sh
  recipes/eternafold/meta.yaml
Labels: aarch64, osx-arm64

#59777 Update coreprofiler version to 1.1.5
  recipes/coreprofiler/meta.yaml
Labels: please review & merge

#59818 pkiss: add arm64 build
  recipes/pkiss/build.sh
  recipes/pkiss/build_failure.osx-64.yaml
  recipes/pkiss/conda_build_config.yaml
  recipes/pkiss/meta.yaml
Labels: MacOS related, osx-arm64

#59787 coot-headless: Add Doxygen python modules' documentation generation step
  recipes/coot-headless/build.sh
  recipes/coot-headless/meta.yaml
Labels: please review & merge

#59822 wtdbg: add aarch64 build
  recipes/wtdbg/0001-master.patch
  recipes/wtdbg/build.sh
  recipes/wtdbg/meta.yaml
Labels: aarch64

#59824 phipack: add arm64 build
  recipes/phipack/build.sh
  recipes/phipack/meta.yaml
Labels: osx-arm64

#58698 Rebuild estmapper recipe
  build-fail-blacklist
  recipes/estmapper/0001-configure.sh.patch
  recipes/estmapper/Makefile.patch
  recipes/estmapper/build.sh
  recipes/estmapper/meta.yaml
Labels: aarch64, osx-arm64

#58532 paladin: add aarch64/arm64 builds
  recipes/paladin/build.sh
  recipes/paladin/meta.yaml
Labels: aarch64, osx-arm64

#59814 Update coreprofiler v1.1.6
  recipes/coreprofiler/meta.yaml
Labels: please review & merge

#59849 Add regain cli 1.6.2 fix
  recipes/regain-cli/meta.yaml
Labels: please review & merge

#59851 bump macs2; include better import test
  recipes/macs2/meta.yaml
Labels: please review & merge

#59837 Update hictk to v2.1.5
  recipes/hictk/build.sh
  recipes/hictk/conanfile.py.patch
  recipes/hictk/conda_build_config.yaml
  recipes/hictk/meta.yaml
Labels: please review & merge

#59864 snoscan: add aarch64/arm64 builds
  recipes/snoscan/0.9.1/Build.PL
  recipes/snoscan/0.9.1/build.sh
  recipes/snoscan/0.9.1/meta.yaml
  recipes/snoscan/build_failure.linux-64.yaml
  recipes/snoscan/build_failure.osx-64.yaml
Labels: aarch64, osx-arm64

#59868 atac: add arm64 build
  recipes/atac/Makefile.patch
  recipes/atac/build.sh
  recipes/atac/meta.yaml
Labels: aarch64, osx-arm64

#59772 Add atol-qc-raw-shortread
  recipes/atol-qc-raw-shortread/meta.yaml
Labels: please review & merge

#59788 Nifflr software version 2.0.0
  recipes/nifflr/build.sh
  recipes/nifflr/meta.yaml
Labels: please review & merge

#59826 Add atol-qc-raw-ont
  recipes/atol-qc-raw-ont/meta.yaml
Labels: please review & merge

#59819 Update KegAlign to v0.1.2.8
  recipes/kegalign-full/meta.yaml
Labels: please review & merge

#59862 Update Amulety
  recipes/amulety/meta.yaml
Labels: please review & merge

#59863 Update annembed v0.2.6
  recipes/annembed/meta.yaml
  recipes/dartunifrac/meta.yaml
Labels: please review & merge

#59892 Update DartUniFrac
  recipes/dartunifrac/meta.yaml
Labels: please review & merge

#59904 python-msgpack: add arm64
  recipes/python-msgpack/build.sh
  recipes/python-msgpack/meta.yaml
Labels: osx-arm64

#59928 gvcfgenotyper: add arm64 build
  recipes/gvcfgenotyper/build.sh
  recipes/gvcfgenotyper/meta.yaml
Labels: aarch64, osx-arm64

#59929 akt: add arm64 build
  recipes/akt/build.sh
  recipes/akt/build_failure.osx-64.yaml
  recipes/akt/meta.yaml
Labels: osx-arm64

#59921 Update nomadic
  recipes/nomadic/meta.yaml
Labels: please review & merge
