Repository bioconda/bioconda-recipes, pull requests merged in 2025-01, with the labels that each got.

#52995 [Update] metabuli 1.0.9
  recipes/metabuli/build.sh
  recipes/metabuli/meta.yaml
Labels: please review & merge

#53000 Add mumemto recipe
  recipes/mumemto/build.sh
  recipes/mumemto/meta.yaml
Labels: please review & merge

#53014 Add scarap recipe
  recipes/scarap/meta.yaml
Labels: please review & merge

#53016 Update `fusion-report` version to 3.1.1
  recipes/fusion-report/meta.yaml
Labels: please review & merge

#53028 perl-alien-build & perl-alien-libxml2 & perl-xml-libxml: add aarch64 build
  build-fail-blacklist
  recipes/perl-alien-build/meta.yaml
  recipes/perl-alien-libxml2/meta.yaml
  recipes/perl-xml-libxml/build.sh
  recipes/perl-xml-libxml/meta.yaml
Labels: please review & merge, aarch64

#53030 Add taranys tool - Version 3.0.1
  recipes/taranis/build.sh
  recipes/taranis/meta.yaml
  recipes/taranys/meta.yaml
Labels: please review & merge

#53022 Add digest
  recipes/digest/build.sh
  recipes/digest/meta.yaml
Labels: please review & merge

#52961 Add a recipe for kyber
  recipes/kyber/build.sh
  recipes/kyber/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53036 Update phyclone to 0.6.0
  recipes/phyclone/meta.yaml
Labels: please review & merge

#53049 Update Resistify meta.yaml
  recipes/resistify/meta.yaml
Labels: please review & merge

#53050 Update strangepg to 0.8.17, add OpenGL ES dependency for aarch64
  recipes/strangepg/build.sh
  recipes/strangepg/meta.yaml
Labels: please review & merge

#53052 fasten: add aarch64/arm64 builds
  recipes/fasten/build.sh
  recipes/fasten/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53071 Build divvier on aarch64/arm64
  recipes/divvier/0001-Makefile.patch
  recipes/divvier/0002-aarch64.patch
  recipes/divvier/bionj.cxx
  recipes/divvier/build.sh
  recipes/divvier/meta.yaml
Labels: aarch64, osx-arm64

#53066 Update mumemto v1.1.1 (patched correct release)
  recipes/mumemto/build.sh
  recipes/mumemto/meta.yaml
Labels: please review & merge

#53069 add caspeak recipe
  recipes/caspeak/meta.yaml
Labels: please review & merge

#53083 mumemto: add aarch64/arm64 builds
  recipes/mumemto/build.sh
  recipes/mumemto/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53082 suchtree: add aarch64/arm64 builds
  recipes/suchtree/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53088 Add PyTorch 2.x (CPU-only) dependency for immuneML
  recipes/immuneml/meta.yaml
Labels: please review & merge

#53074 Add primalbedtools
  recipes/primalbedtools/meta.yaml
Labels: please review & merge

#53079 Add ExcludonFinder recipe with run_exports
  recipes/excludonfinder/meta.yaml
Labels: please review & merge

#53038 Add IsoRefiner 0.1.0
  recipes/isorefiner/meta.yaml
Labels: please review & merge

#53097 Add new recipe for relecov-tools
  recipes/relecov-tools/meta.yaml
Labels: please review & merge

#53138 osx-arm error for gfaffix
  recipes/gfaffix/build_failure.osx-arm64.yaml
  recipes/gfaffix/meta.yaml
Labels: please review & merge

#53136 Update meta.yaml to v1.1.0
  recipes/spagrn/meta.yaml
Labels: please review & merge

#53156 Add a recipe for glean-gene
  recipes/glean-gene/meta.yaml
Labels: please review & merge

#53169 Update `pyhmmer` to `v0.11.0`
  recipes/pyhmmer/meta.yaml
Labels: please review & merge

#53172 Update atlas to 2.0.0-rc.7
  recipes/atlas/meta.yaml
Labels: please review & merge

#53181 Update annembed v0.1.8
  recipes/annembed/meta.yaml
Labels: please review & merge

#53179 Add 2fast2q V2.7.2
  recipes/fast2q/meta.yaml
Labels: please review & merge

#53177 Add mSOMA recipe for somatic mutation calling. python/R/samtools/bam dependencies
  recipes/msoma/meta.yaml
Labels: please review & merge

#53201 Add gtars crate
  recipes/rust-gtars/build.sh
  recipes/rust-gtars/meta.yaml
Labels: please review & merge

#53205 gffread: add arm64 build
  recipes/gffread/Makefile.patch
  recipes/gffread/build.sh
  recipes/gffread/meta.yaml
Labels: osx-arm64

#53196 ngscheckmate - migrate to python3 and enable linux-aarch64 and osx-arm64
  recipes/ngscheckmate/build.sh
  recipes/ngscheckmate/meta.yaml
  recipes/ngscheckmate/py3.patch
Labels: please review & merge

#52477 poppunk: add linux-aarch64 build
  recipes/poppunk/meta.yaml
Labels: aarch64

#53207 Re-enable broken dialign-tx (dep of t-coffee, dep of pasta), add linux-aarch64
  recipes/dialign-tx/meta.yaml
Labels: please review & merge

#53206 Move recipes from perl-lwp-simple to perl-libwww-perl - part 1
  recipes/abricate/meta.yaml
  recipes/agat/meta.yaml
  recipes/ensembl-vep/meta.yaml
  recipes/mirdeep2/meta.yaml
  recipes/perl-bio-phylo/meta.yaml
  recipes/srax/meta.yaml
  recipes/unitas/meta.yaml
Labels: please review & merge

#53208 Muscle - add legacy version - required by pasta
  recipes/muscle/3.8.1551/build.sh
  recipes/muscle/3.8.1551/meta.yaml
  recipes/muscle/3.8.1551/osx-makefile.patch
Labels: please review & merge

#53193 add seg-suite
  recipes/seg-suite/build.sh
  recipes/seg-suite/meta.yaml
Labels: please review & merge

#53215 pasta: add linux-aarch64; muscle/3.8 enable osx-arm64
  recipes/muscle/3.8.1551/meta.yaml
  recipes/pasta/meta.yaml
Labels: please review & merge

#53224 Update meta.yaml for htstream 1.4.0 release
  recipes/htstream/build.sh
  recipes/htstream/meta.yaml
Labels: please review & merge

#53220 Add snakebids
  recipes/snakebids/meta.yaml
Labels: please review & merge

#53216 Update Homer to 5.1
  recipes/homer/configureHomer.patch
  recipes/homer/meta.yaml
Labels: please review & merge

#53243 Update build number of arborator
  recipes/arborator/meta.yaml
Labels: please review & merge

#53231 htstream: add aarch64/arm64 builds
  recipes/htstream/build.sh
  recipes/htstream/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53230 rust-gtars: add linux-aarch64 build
  recipes/rust-gtars/build.sh
  recipes/rust-gtars/meta.yaml
Labels: please review & merge, aarch64

#53245 remove gget (moved to conda-forge)
  recipes/gget/meta.yaml
Labels: please review & merge

#53256 easypqp: export matplotlib and xdc cache dir
  recipes/easypqp/meta.yaml
Labels: please review & merge

#53258 Update pymethylation_utils to 0.5.2
  recipes/pymethylation_utils/meta.yaml
Labels: please review & merge

#53248 Update bioconductor-biostrings for osx-arm64
  recipes/bioconductor-biostrings/meta.yaml
  recipes/bioconductor-iranges/meta.yaml
  recipes/bioconductor-s4vectors/meta.yaml
  recipes/bioconductor-xvector/meta.yaml
  recipes/bioconductor-zlibbioc/meta.yaml
Labels: please review & merge

#53275 Add centrifuger-quant to Centrifuger
  recipes/centrifuger/build.sh
  recipes/centrifuger/meta.yaml
Labels: please review & merge

#53276 add qimba
  recipes/qimba/meta.yaml
Labels: please review & merge

#53287 bayescode: add aarch64/arm64 builds
  recipes/bayescode/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53299 Update wipertools to 1.1.4
  recipes/wipertools/meta.yaml
Labels: please review & merge

#53305 update OpenMS to 3.3
  recipes/openms-meta/meta.yaml
Labels: please review & merge

#53312 Update seismic-rna to v0.22.3
  recipes/seismic-rna/meta.yaml
Labels: please review & merge

#53316 Update Foldseek to release 10
  recipes/foldseek/build.sh
  recipes/foldseek/conda_build_config.yaml
  recipes/foldseek/fix-rust-1.79.patch
  recipes/foldseek/meta.yaml
Labels: please review & merge

#53318 Add a recipe for Ouro-Tools v0.2.7
  recipes/ourotools/meta.yaml
Labels: please review & merge

#53242 t-coffee: add linux-aarch64 and build from source
  recipes/t-coffee/build.sh
  recipes/t-coffee/coredump.patch
  recipes/t-coffee/meta.yaml
Labels: please review & merge

#53326 Update poseidon-trident to 1.6.2.1
  recipes/poseidon-trident/meta.yaml
Labels: please review & merge

#53330 Fix macOS Metal in Foldseek release 10
  recipes/foldseek/build.sh
  recipes/foldseek/meta.yaml
  recipes/foldseek/prostt5-memory.patch
Labels: please review & merge

#53247 Update ms2rescore-rs to 0.4.1
  recipes/ms2rescore-rs/build.sh
  recipes/ms2rescore-rs/build_failure.osx-64.yaml
  recipes/ms2rescore-rs/meta.yaml
Labels: please review & merge

#53325 Fix OpenMS symlink issue
  recipes/openms-meta/meta.yaml
Labels: please review & merge

#53341 Update igv to add missing glib dependency
  recipes/igv/meta.yaml
Labels: please review & merge

#53327 khmer: python update to support python 3.8-3.11 ; enable linux-aarch64
  recipes/khmer/0000-Upgrade-to-python3.10.patch
  recipes/khmer/0001-Inject-compiler-and-flags-for-third-party-compilation.patch
  recipes/khmer/0004-builddirs-setup.patch
  recipes/khmer/0005-enable-aarch64.patch
  recipes/khmer/conda_build_config.yaml
  recipes/khmer/meta.yaml
Labels: please review & merge

#53348 Update psm_utils
  recipes/psm-utils/meta.yaml
Labels: please review & merge

#53100 Add Linkedsv
  recipes/linkedsv/build.sh
  recipes/linkedsv/meta.yaml
Labels: please review & merge

#53351 Add eastr recipe
  recipes/eastr/meta.yaml
Labels: please review & merge

#53358 Add kbo-cli v0.1.1
  recipes/kbo-cli/meta.yaml
Labels: please review & merge

#53347 Update ms2pip
  recipes/ms2pip/build_failure.linux-64.yaml
  recipes/ms2pip/build_failure.osx-64.yaml
  recipes/ms2pip/meta.yaml
Labels: please review & merge

#53366 Update crocodeel
  recipes/crocodeel/meta.yaml
Labels: please review & merge

#53372 Update Emu v3.5.1
  recipes/emu/meta.yaml
Labels: please review & merge

#52171 sra-tools: build for linux-aarch64
  recipes/sra-tools/build.sh
  recipes/sra-tools/conda_build_config.yaml
  recipes/sra-tools/meta.yaml
Labels: please review & merge

#53381 Update GRAMPA recipe
  recipes/grampa/meta.yaml
Labels: please review & merge

#53257 Add recipe for pybwa
  recipes/pybwa/meta.yaml
Labels: please review & merge

#53392 perl-socket: add linux-aarch64 supprt
  recipes/perl-socket/2.027/conda_build_config.yaml
  recipes/perl-socket/2.027/meta.yaml
Labels: please review & merge

#53403 Update MetaCerberus
  recipes/metacerberus/meta.yaml
Labels: please review & merge

#53406 Update MetaCerberus-lite
  recipes/metacerberus-lite/meta.yaml
Labels: please review & merge

#53412 ECTYPER v2.0.0 build #2 addressing the bioconda 1.85 incompatibility
  recipes/ectyper/meta.yaml
Labels: please review & merge

#53413 khmer: add arm64 build
  recipes/khmer/0000-Upgrade-to-python3.10.patch
  recipes/khmer/0001-Inject-compiler-and-flags-for-third-party-compilation.patch
  recipes/khmer/0002-remove-m64.patch
  recipes/khmer/0003-enable-aarch64.patch
  recipes/khmer/0004-arm64.patch
  recipes/khmer/0004-builddirs-setup.patch
  recipes/khmer/build_failure.linux-64.yaml
  recipes/khmer/build_failure.linux-aarch64.yaml
  recipes/khmer/meta.yaml
Labels: osx-arm64

#53416 Update LongStitch
  recipes/longstitch/meta.yaml
Labels: please review & merge

#53402 update OpenMS 3.3 with mac builds
  recipes/openms-meta/meta.yaml
Labels: please review & merge

#53422 ncbi-stxtyper: add aarch64/arm64 builds
  recipes/ncbi-stxtyper/build.sh
  recipes/ncbi-stxtyper/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53428 fastqsplitter & rnastructure: add aarch64/arm64 builds
  recipes/fastqsplitter/meta.yaml
  recipes/rnastructure/build.sh
  recipes/rnastructure/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53448 Add `nafcodec`
  recipes/nafcodec/meta.yaml
Labels: please review & merge

#53396 Disable mac builds for pyopenms again
  recipes/pyopenms/meta.yaml
Labels: please review & merge

#53463 gdc-client: remove pyopenssl pin
  recipes/gdc-client/meta.yaml
Labels: please review & merge

#53462 Update strangepg to 0.8.18
  recipes/strangepg/build_failure.linux-64.yaml
  recipes/strangepg/meta.yaml
Labels: please review & merge

#53423 seismic-rna : add aarch64/arm64 builds
  recipes/seismic-rna/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53460 Add nbitk to bioconda
  recipes/nbitk/meta.yaml
Labels: please review & merge

#53495 miniasm: add arm64 build
  recipes/miniasm/build.sh
  recipes/miniasm/meta.yaml
Labels: osx-arm64

#53496 unicycler: add aarch64 build
  recipes/unicycler/meta.yaml
Labels: aarch64

#53499 Update PopPUNK to v2.7.5
  recipes/poppunk/meta.yaml
Labels: please review & merge

#53424 Manta boost fix: add boost-cpp dependency at runtime.
  recipes/manta/meta.yaml
Labels: please review & merge

#53497 tgsgapcloser: add aarch64/arm64 builds
  recipes/tgsgapcloser/0001-master.patch
  recipes/tgsgapcloser/0002-Makefile.patch
  recipes/tgsgapcloser/0003-main-src-ont.patch
  recipes/tgsgapcloser/0004-tgsgapcloser.patch
  recipes/tgsgapcloser/0005-headers.patch
  recipes/tgsgapcloser/0006-aarch64.patch
  recipes/tgsgapcloser/build.sh
  recipes/tgsgapcloser/build_failure.osx-64.yaml
  recipes/tgsgapcloser/conda_build_config.yaml
  recipes/tgsgapcloser/meta.yaml
Labels: aarch64, osx-arm64

#53507 Update Earl Grey meta.yaml
  recipes/earlgrey/meta.yaml
Labels: please review & merge

#53500 Update of ngs-bits to version 2025_01
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#53502 Update ms2pip recipe
  recipes/ms2pip/meta.yaml
Labels: please review & merge

#53515 Update to AMRFinderPlus 4.0.15
  recipes/ncbi-amrfinderplus/build.sh
  recipes/ncbi-amrfinderplus/meta.yaml
Labels: please review & merge, new version

#53512 Update pybigwig to 0.3.24
  recipes/pybigwig/meta.yaml
Labels: please review & merge

#53489 Add recipe for GET_PANGENES
  recipes/get_pangenes/build.sh
  recipes/get_pangenes/meta.yaml
  recipes/get_pangenes/post-link.sh
Labels: please review & merge

#53542 perl-html-parser: add linux-aarch64, bump build
  recipes/perl-html-parser/meta.yaml
Labels: please review & merge

#53513 bioconductor-copynumber restore to enable aarch64 supporting package
  recipes/bioconductor-biocgenerics/meta.yaml
  recipes/bioconductor-copynumber/build.sh
  recipes/bioconductor-copynumber/meta.yaml
  recipes/bioconductor-genomeinfodb/meta.yaml
  recipes/bioconductor-genomicranges/meta.yaml
  recipes/bioconductor-iranges/meta.yaml
  recipes/bioconductor-s4vectors/meta.yaml
  recipes/bioconductor-ucsc.utils/meta.yaml
  recipes/bioconductor-xvector/meta.yaml
  recipes/bioconductor-zlibbioc/meta.yaml
Labels: please review & merge

#53555 Update vg to v.1.63.1
  recipes/vg/meta.yaml
Labels: please review & merge

#53520 Add recipe for pb-CpG-tools
  recipes/pb-cpg-tools/build.sh
  recipes/pb-cpg-tools/meta.yaml
Labels: please review & merge

#53560 perl-lwp-simple: bump the version number of perl-libwww-perl to match
  build-fail-blacklist
  recipes/perl-libwww-perl/meta.yaml
  recipes/perl-lwp-simple/meta.yaml
Labels: please review & merge

#53565 Tidy up `vartrix` recipe
  recipes/vartrix/LICENSE
  recipes/vartrix/meta.yaml
Labels: please review & merge

#53367 Update ms2rescore
  recipes/ms2rescore/meta.yaml
Labels: please review & merge

#53586 Update nbitk v0.3.3
  recipes/nbitk/meta.yaml
Labels: please review & merge

#53592 Update r-ukbrapr - remove deprecated dependencies
  recipes/r-ukbrapr/meta.yaml
Labels: please review & merge

#53579 Update snakebids
  recipes/snakebids/meta.yaml
Labels: please review & merge

#53606 krakenuniq, kmer-jellyfish 1.1.12: enable aarch64, reenable x86
  recipes/kmer-jellyfish/1.1.12/build.sh
  recipes/kmer-jellyfish/1.1.12/configure.patch
  recipes/kmer-jellyfish/1.1.12/meta.yaml
  recipes/krakenuniq/conda_build_config.yaml
  recipes/krakenuniq/meta.yaml
Labels: please review & merge
