Repository bioconda/bioconda-recipes, pull requests merged in 2025-03, with the labels that each got.

#54250 Update poly-qtlseq to 1.0.2
  recipes/poly-qtlseq/meta.yaml
Labels: please review & merge

#54271 Remove pronto recipe as it is now in conda-forge
  recipes/pronto/meta.yaml
Labels: please review & merge

#54283 Update: Preserve existing PERL5LIB path on run
  recipes/pfam_scan/build.sh
  recipes/pfam_scan/meta.yaml
Labels: please review & merge

#54188 Add VueGen recipe 🎉
  recipes/vuegen/meta.yaml
Labels: please review & merge

#54163 Add Mity recipe
  recipes/mity/LICENSE.txt
  recipes/mity/_version.patch
  recipes/mity/meta.yaml
  recipes/mity/setup.patch
Labels: please review & merge

#54269 Update rnalyze version to 1.0.1
  recipes/rnalyze/meta.yaml
Labels: please review & merge

#54296 ngscheckmate: python2=>3 migration fix
  recipes/ngscheckmate/meta.yaml
  recipes/ngscheckmate/py3.patch
Labels: please review & merge

#54229 Add recipe for `cayman` Python package
  recipes/cayman/meta.yaml
Labels: please review & merge

#54308 update plink1.907.7
  recipes/plink/meta.yaml
Labels: please review & merge

#54222 bam-readcount: add arm64 build
  recipes/bam-readcount/0001_configure_boost_toolset.patch
  recipes/bam-readcount/0002_configure_boost_toolset_macOS.patch
  recipes/bam-readcount/0003-BuildSamtools.cmake.patch
  recipes/bam-readcount/build.sh
  recipes/bam-readcount/build_failure.linux-64.yaml
  recipes/bam-readcount/build_failure.linux-aarch64.yaml
  recipes/bam-readcount/build_failure.osx-64.yaml
  recipes/bam-readcount/meta.yaml
Labels: osx-arm64

#53571 Add snakemake storage plugin for Microsoft SharePoint
  recipes/snakemake-storage-plugin-sharepoint/meta.yaml
Labels: please review & merge

#54191 hictk: fix sigkill on macos
  recipes/hictk/build.sh
  recipes/hictk/conan_profiles/apple-clang
  recipes/hictk/conan_profiles/clang
  recipes/hictk/conan_profiles/gcc
  recipes/hictk/conda_build_config.yaml
  recipes/hictk/meta.yaml
  recipes/hictk/run_test.sh
Labels: please review & merge

#54322 bump revoluzer to 0.1.7
  recipes/revoluzer/meta.yaml
Labels: please review & merge

#54333 Updated 2fast2q to 2.7.7
  recipes/fast2q/meta.yaml
Labels: please review & merge

#54347 perl-db-file usages: move to perl-db_file
  recipes/fusion-filter/meta.yaml
  recipes/fusion-inspector/meta.yaml
  recipes/gmap-fusion/meta.yaml
  recipes/rsat-core/meta.yaml
  recipes/transdecoder/meta.yaml
Labels: please review & merge

#54348 bioconductor-glmgampoi: add linux-aarch64
  recipes/bioconductor-glmgampoi/meta.yaml
Labels: please review & merge

#54363 Update pLannotate to v1.2.3 (patch version bump)
  recipes/plannotate/meta.yaml
Labels: please review & merge

#54349 Update: Resistify - remove unused dependencies
  recipes/resistify/meta.yaml
Labels: please review & merge

#54345 bioconductor-dada2: add linux-aarch64
  recipes/bioconductor-dada2/meta.yaml
Labels: please review & merge

#54294 Add Lassaseq and ebolaseq
  recipes/ebolaseq/meta.yaml
  recipes/lassaseq/meta.yaml
Labels: please review & merge

#54372 Update perl-bio-phylo-forest-dbtree to v0.2.1
  recipes/perl-bio-phylo-forest-dbtree/meta.yaml
Labels: please review & merge

#54380 Update meta.yaml
  recipes/busco/meta.yaml
Labels: please review & merge

#54383 Build r-signac 1.13.0 with the latest r-base 4.4
  recipes/r-signac/1.13.0/build.sh
  recipes/r-signac/1.13.0/meta.yaml
Labels: please review & merge

#54389 gmap: add osx build
  recipes/gmap/0002-genome_sites.patch
  recipes/gmap/build.sh
  recipes/gmap/meta.yaml
Labels: MacOS related

#54350 Add longbow recipe
  recipes/longbow/build.sh
  recipes/longbow/meta.yaml
Labels: please review & merge

#54391 Add danbing-tk v1.3.2.5
  recipes/danbing-tk/build.sh
  recipes/danbing-tk/meta.yaml
Labels: please review & merge

#54341 Add amiga recipe
  recipes/amiga/meta.yaml
Labels: please review & merge

#54401 Update (~ish kind-of: buildbump) pysamstat
  recipes/pysamstats/meta.yaml
Labels: please review & merge

#54407 Update olivar to 1.3.0
  recipes/olivar/meta.yaml
Labels: please review & merge

#54414 Add metafun package
  recipes/metafun/build.sh
  recipes/metafun/meta.yaml
Labels: please review & merge

#54423 Update r-psminer and rename to r-pathosurveilr
  recipes/r-pathosurveilr/meta.yaml
Labels: please review & merge

#54098 Update Cleanifier
  recipes/cleanifier/meta.yaml
Labels: please review & merge

#54302 Add recipe for AliView
  recipes/aliview/meta.yaml
Labels: please review & merge

#54204 Add jacusa2
  recipes/jacusa2/LICENSE
  recipes/jacusa2/build.sh
  recipes/jacusa2/meta.yaml
Labels: please review & merge

#54429 perl-cgi: add linux-aarch64
  recipes/perl-cgi/meta.yaml
Labels: please review & merge

#54431 Update Binette to 1.1.0
  recipes/binette/meta.yaml
Labels: please review & merge

#54436 update autobigs-cli bioconda recipe to PYPI autobigs-cli 0.6.3.
  recipes/autobigs-cli/meta.yaml
Labels: please review & merge

#54384 meme: add linux-aarch64
  recipes/meme/meta.yaml
Labels: please review & merge

#54425 Update: smallgenomeutilities - fix dependencies
  recipes/smallgenomeutilities/meta.yaml
Labels: please review & merge

#54442 Update amiga recipe
  recipes/amiga/meta.yaml
Labels: please review & merge

#54456 pear: add linux-aarch64
  recipes/pear/meta.yaml
Labels: please review & merge

#54457 wgsim: add linux-aarch64
  recipes/wgsim/meta.yaml
Labels: please review & merge

#54458 py_fasta_validator: add linux-aarch64
  recipes/py_fasta_validator/meta.yaml
Labels: please review & merge

#54453 segemehl: add linux-aarch64
  recipes/segemehl/meta.yaml
Labels: please review & merge

#54452 Add AFragmenter
  recipes/afragmenter/meta.yaml
Labels: please review & merge

#54444 ci: adding caching of bioconda-utils install in PR workflow
  .github/workflows/PR.yml
Labels: please review & merge

#54451 add recipe pilea
  recipes/pilea/meta.yaml
Labels: please review & merge

#54463 easel: add linux-aarch64
  recipes/easel/conda_build_config.yaml
  recipes/easel/meta.yaml
Labels: please review & merge

#54464 eggnog-mapper: add linux-aarch64
  recipes/eggnog-mapper/meta.yaml
Labels: please review & merge

#54477 Update Snakebids
  recipes/snakebids/meta.yaml
Labels: please review & merge

#53888 Update latch to 2.57.2
  recipes/latch/00001.patch
  recipes/latch/build.sh
  recipes/latch/meta.yaml
Labels: please review & merge

#54490 perl-list-moreutils-xs: add osx-arm64
  recipes/perl-list-moreutils-xs/meta.yaml
Labels: please review & merge

#54483 namfinder: add linux-aarch64
  recipes/namfinder/build.sh
  recipes/namfinder/meta.yaml
Labels: please review & merge

#54484 Update SeqKit to v2.10.0
  recipes/seqkit/meta.yaml
Labels: please review & merge

#54474 add requirements of caspeak
  recipes/caspeak/meta.yaml
Labels: please review & merge

#54481 plek: add linux-aarch64
  recipes/plek/build.sh
  recipes/plek/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#54508 miranda: use replacement URL - and add linux-aarch64
  recipes/miranda/build.sh
  recipes/miranda/meta.yaml
Labels: please review & merge

#54507 mtm-align: use new source URL for download and add linux-aarch64
  recipes/mtm-align/meta.yaml
Labels: please review & merge

#54518 Update atol-bpa-datamapper dependencies
  recipes/atol-bpa-datamapper/meta.yaml
Labels: please review & merge

#54514 Update Commec v0.3.1
  recipes/commec/meta.yaml
Labels: please review & merge

#54502 Update met4j to 2.0.1
  recipes/met4j/meta.yaml
Labels: please review & merge

#54461 Add hippunfold
  recipes/hippunfold/meta.yaml
Labels: please review & merge

#54519 linux-aarch64 aarch64 build for nrpys
  recipes/nrpys/meta.yaml
Labels: please review & merge

#54184 Add rabbitsketch package to Bioconda
  recipes/rabbitsketch/build.sh
  recipes/rabbitsketch/meta.yaml
Labels: please review & merge

#54533 percolator, xsd: add linux-aarch64; restore xsd from compile fail blacklist
  build-fail-blacklist
  recipes/percolator/boost-dynamic.patch
  recipes/percolator/build.sh
  recipes/percolator/meta.yaml
  recipes/xsd/build.sh
  recipes/xsd/meta.yaml
  recipes/xsd/ostream-include.patch
Labels: please review & merge

#54506 Update: genomic_address_service python requirements
  recipes/genomic_address_service/meta.yaml
Labels: please review & merge

#54489 perl-io-compress: add osx-arm64
  recipes/perl-io-compress/meta.yaml
Labels: please review & merge

#54561 linux-aarch64 build for kraken
  recipes/kraken/meta.yaml
Labels: please review & merge

#54548 Update `ena-webin-cli` to use newer openjdk dependency
  recipes/ena-webin-cli/meta.yaml
Labels: please review & merge

#54505 Add formulaic contrasts
  recipes/formulaic-contrasts/meta.yaml
Labels: please review & merge

#54504 update pydeseq2
  recipes/pydeseq2/meta.yaml
Labels: please review & merge

#54572 Update lassaseq
  recipes/lassaseq/meta.yaml
Labels: please review & merge

#54594 updated ectyper_v2.0.0 build #3 recipe to fix minor bugs in serotyping
  recipes/ectyper/meta.yaml
Labels: please review & merge

#54604 Update mgnify pipelines toolkit to version 1.0.1
  recipes/mgnify-pipelines-toolkit/meta.yaml
Labels: please review & merge

#54537 Update STRdust
  recipes/strdust/meta.yaml
Labels: please review & merge

#54643 perl-xml-libxslt: add linux-aarch64
  recipes/perl-xml-libxslt/meta.yaml
Labels: please review & merge

#54636 liana: update to 1.5.1 and add aarch64, bump python max version of cell2cell
  recipes/cell2cell/meta.yaml
  recipes/liana/meta.yaml
Labels: please review & merge

#54593 chore: add DOI to pybwa
  recipes/pybwa/meta.yaml
Labels: please review & merge

#54585 chore: add doi to fgpyo
  recipes/fgpyo/meta.yaml
Labels: please review & merge

#54584 chore: add DOI to fgsv
  recipes/fgsv/meta.yaml
Labels: please review & merge

#54583 chore: add doi to fgbio
  recipes/fgbio/meta.yaml
Labels: please review & merge

#54639 Update: Rebuild of arborator container
  recipes/arborator/meta.yaml
Labels: please review & merge

#54630 Add hippunfold-dev
  recipes/hippunfold-dev/meta.yaml
Labels: please review & merge

#54619 Add Mutserve recipe
  recipes/mutserve/build.sh
  recipes/mutserve/meta.yaml
Labels: please review & merge

#54581 update autobigs-engine bioconda recipe to 0.14.2.
  recipes/autobigs-engine/meta.yaml
Labels: please review & merge

#54635 Add snakemake-storage-plugin-xrootd
  recipes/snakemake-storage-plugin-xrootd/meta.yaml
Labels: please review & merge

#54552 Rebuild gubbins for newer python versions
  recipes/gubbins/meta.yaml
Labels: please review & merge

#54647 Add shiba2sashimi
  recipes/shiba2sashimi/meta.yaml
Labels: please review & merge

#54655 plink: build from source and add linux-aarch64
  recipes/plink/build.sh
  recipes/plink/cxx_linking.patch
  recipes/plink/makefile.patch
  recipes/plink/meta.yaml
  recipes/plink/signed_int64_osx.patch
  recipes/plink/socks.patch
Labels: please review & merge

#54653 Update Commec v0.3.2
  recipes/commec/meta.yaml
Labels: please review & merge

#54661 Update gubbins for python 3.10 and above
  recipes/gubbins/meta.yaml
Labels: please review & merge

#54663 update autobigs-cli bioconda recipe to 0.6.5.
  recipes/autobigs-cli/meta.yaml
Labels: please review & merge

#54638 added vcf_parser python module
  recipes/vcf_parser/meta.yaml
Labels: please review & merge

#54662 Add Gencube version 1.1.0
  recipes/gencube/meta.yaml
Labels: please review & merge

#53709 Add mysterymaster
  recipes/mysterymaster/build.sh
  recipes/mysterymaster/meta.yaml
Labels: please review & merge

#54644 perl-html-tidy: add linux-aarch64
  recipes/perl-html-tidy/build.sh
  recipes/perl-html-tidy/meta.yaml
  recipes/tidyp/build.sh
  recipes/tidyp/meta.yaml
Labels: please review & merge

#54654 add pisad
  recipes/pisad/build.sh
  recipes/pisad/meta.yaml
Labels: please review & merge

#54704 bioconductor-dropletutils: add linux-aarch64
  recipes/bioconductor-dropletutils/meta.yaml
Labels: please review & merge

#54705 bioconductor-ncdfflow: add linux-aarch64
  recipes/bioconductor-ncdfflow/meta.yaml
Labels: please review & merge

#54701 bioconductor-oligo: add linux-aarch64
  recipes/bioconductor-oligo/meta.yaml
Labels: please review & merge

#54698 bioconductor-cn.mops: add linux-aarch64
  recipes/bioconductor-cn.mops/meta.yaml
Labels: please review & merge

#54696 bioconductor-titancna: add linux-aarch64
  recipes/bioconductor-titancna/meta.yaml
Labels: please review & merge

#54712 build: Bump python version
  recipes/deepvariant/meta.yaml
Labels: please review & merge

#54650 Update polap recipe
  recipes/polap/build.sh
  recipes/polap/meta.yaml
Labels: please review & merge

#54722 bioconductor-aseb: add linux-aarch64
  recipes/bioconductor-aseb/meta.yaml
Labels: please review & merge

#54717 bioconductor-tweedeseq: add linux-aarch64
  recipes/bioconductor-tweedeseq/meta.yaml
Labels: please review & merge

#54721 bioconductor-beaddatapackr: add linux-aarch64
  recipes/bioconductor-beaddatapackr/meta.yaml
Labels: please review & merge

#54716 bioconductor-deepsnv: add linux-aarch64
  recipes/bioconductor-deepsnv/meta.yaml
Labels: please review & merge

#54718 bioconductor-rgadem: add linux-aarch64
  recipes/bioconductor-rgadem/meta.yaml
Labels: please review & merge

#54711 bioconductor-flowworkspace: add linux-aarch64
  recipes/bioconductor-flowworkspace/meta.yaml
Labels: please review & merge

#54723 Update of ngs-bits to version 2025_03
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#54702 Update meta.yaml for RepeatMasker 4.1.8
  recipes/repeatmasker/meta.yaml
  recipes/repeatmasker/post-link.sh
Labels: please review & merge

#54703 bioconductor-lpsymphony: add linux-aarch64 ; skip osx
  recipes/bioconductor-lpsymphony/build.sh
  recipes/bioconductor-lpsymphony/meta.yaml
Labels: please review & merge

#54657 Wakhan recipe fix -- added missing requirement
  recipes/wakhan/meta.yaml
Labels: please review & merge

#54660 nrpys: Use Python <3.12
  recipes/nrpys/meta.yaml
Labels: please review & merge

#54756 Fix bioconductor-scds 1.22.0
  recipes/bioconductor-scds/build_failure.linux-64.yaml
  recipes/bioconductor-scds/build_failure.osx-64.yaml
  recipes/bioconductor-scds/meta.yaml
Labels: please review & merge

#54755 Update bioconductor-scdblfinder 1.20.2
  recipes/bioconductor-scdblfinder/build_failure.linux-64.yaml
  recipes/bioconductor-scdblfinder/meta.yaml
Labels: please review & merge

#54757 Update bioconductor-scater 1.34.1
  recipes/bioconductor-scater/meta.yaml
Labels: please review & merge

#54740 bump binette to v1.1.1
  recipes/binette/meta.yaml
Labels: please review & merge

#54743 Update SemiBin to 2.2.0
  recipes/semibin/meta.yaml
Labels: please review & merge

#54683 Update cctyper - new build to automatically install database
  recipes/cctyper/activate.sh
  recipes/cctyper/build.sh
  recipes/cctyper/deactivate.sh
  recipes/cctyper/meta.yaml
  recipes/cctyper/post-link.sh
  recipes/cctyper/pre-unlink.sh
Labels: please review & merge

#54697 Add PIMENTO to bioconda
  recipes/mi-pimento/meta.yaml
Labels: please review & merge

#54748 Add FastGA
  recipes/fastga/build.sh
  recipes/fastga/meta.yaml
Labels: please review & merge

#54741 Add spacedust
  recipes/spacedust/3e436173321a2d0365a08bfb3b281108ed9ad414.patch
  recipes/spacedust/build.sh
  recipes/spacedust/meta.yaml
Labels: please review & merge

#54762 Fix rtg-tools java installation path
  recipes/rtg-tools/0001-feat-support-arm64.patch
  recipes/rtg-tools/build.sh
  recipes/rtg-tools/meta.yaml
Labels: please review & merge

#54765 bump freebayes dependency of pypolca to v1.3.9
  recipes/pypolca/meta.yaml
Labels: please review & merge

#54763 Add isotools 0.3.4
  recipes/isotools/meta.yaml
Labels: please review & merge

#54793 Add longcallD to Bioconda
  recipes/longcalld/build.sh
  recipes/longcalld/meta.yaml
Labels: please review & merge

#54768 Update hmftools-orange to v3.8.0
  recipes/hmftools-orange/meta.yaml
Labels: please review & merge

#54761 Update r-pathosurveilr
  recipes/r-pathosurveilr/meta.yaml
Labels: please review & merge

#54800 Update polap to v0.4.3.7.2
  recipes/polap/build.sh
  recipes/polap/meta.yaml
Labels: please review & merge

#54665 Add bcftools +liftover
  recipes/bcftools-liftover-plugin/build.sh
  recipes/bcftools-liftover-plugin/conda_build_config.yaml
  recipes/bcftools-liftover-plugin/meta.yaml
Labels: please review & merge

#54806 update antismash
  recipes/antismash/meta.yaml
Labels: please review & merge

#54826 Update bcftools-gtc2vcf-plugin for new content and bcftools 1.21
  recipes/bcftools-gtc2vcf-plugin/build.sh
  recipes/bcftools-gtc2vcf-plugin/conda_build_config.yaml
  recipes/bcftools-gtc2vcf-plugin/meta.yaml
Labels: please review & merge

#54816 add fastcov
  recipes/fastcov/build.sh
  recipes/fastcov/meta.yaml
Labels: please review & merge

#54875 Update graphembed v0.1.5
  recipes/graphembed/meta.yaml
Labels: please review & merge

#54853 Update meta.yaml for Earl Grey v6.0.0
  recipes/earlgrey/meta.yaml
Labels: please review & merge

#54874 Update snippy 4.6 recipe to not use vt from 2015
  recipes/snippy/meta.yaml
Labels: please review & merge

#54852 Update LexicMap to v0.6.0
  recipes/lexicmap/build.sh
  recipes/lexicmap/meta.yaml
Labels: please review & merge

#54835 SISTR v1.1.3 build #1 due to pytables < 3.10.2 req
  recipes/sistr_cmd/meta.yaml
Labels: please review & merge

#54910 Update zdb
  recipes/zdb/build.sh
  recipes/zdb/meta.yaml
Labels: please review & merge

#54794 Add spacerextractor
  recipes/spacerextractor/meta.yaml
Labels: please review & merge

#54924 Add PSAURON
  recipes/psauron/meta.yaml
Labels: please review & merge

#54911 rpsbproc: add osx-arm64
  recipes/rpsbproc/meta.yaml
  recipes/rpsbproc/project_tree_builder.patch
Labels: please review & merge

#54889 vsnp3 version 3.27
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#54901 commec meta.yaml meta data patch
  recipes/commec/meta.yaml
Labels: please review & merge

#54892 slivar: add linux-aarch64
  recipes/slivar/meta.yaml
Labels: please review & merge

#54890 r-signac: add linux-aarch64
  recipes/r-signac/meta.yaml
Labels: please review & merge

#54891 treesapp: add linux-aarch64
  recipes/treesapp/meta.yaml
Labels: please review & merge

#54887 Add Yleaf @3.2.1
  recipes/yleaf/build.sh
  recipes/yleaf/conda_build_config.yaml
  recipes/yleaf/meta.yaml
Labels: please review & merge
