Repository bioconda/bioconda-recipes, pull requests merged in 2025-09, with the labels that each got.

#59009 Update Auspice to 2.65.0
  recipes/auspice/meta.yaml
Labels: please review & merge

#58993 update haplotype-lso
  recipes/haplotype-lso/meta.yaml
Labels: please review & merge

#58973 Update gbdraw to v0.5.0
  recipes/gbdraw/meta.yaml
Labels: please review & merge

#58920 update pureclip and enabled linux-aarch64
  build-fail-blacklist
  recipes/pureclip/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#58919 update quip and enabled linux-aarch64
  build-fail-blacklist
  recipes/quip/build.sh
  recipes/quip/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#58921 update probeit and enabled linux-aarch64
  recipes/probeit/build.sh
  recipes/probeit/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#58922 update cycle_finder and enabled linux-aarch64
  recipes/cycle_finder/build.sh
  recipes/cycle_finder/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#59025 Update coreprofile
  recipes/coreprofiler/meta.yaml
Labels: please review & merge

#58988 Add phu meta.yaml recipe
  recipes/phu/LICENSE
  recipes/phu/meta.yaml
Labels: please review & merge

#58960 Update mitosalt (build 2)
  recipes/mitosalt/download-mitosalt-db.sh
  recipes/mitosalt/meta.yaml
Labels: please review & merge

#58976 Add padloc
  recipes/padloc/build.sh
  recipes/padloc/meta.yaml
Labels: please review & merge

#58994 update haploclique and enabled linux-aarch64
  build-fail-blacklist
  recipes/haploclique/1.3.1/build.sh
  recipes/haploclique/1.3.1/meta.yaml
Labels: aarch64

#58959 Add decenttree 1.0.0
  recipes/decenttree/build.sh
  recipes/decenttree/conda_build_config.yaml
  recipes/decenttree/meta.yaml
Labels: please review & merge

#58985 Add art_modern 1.1.4
  recipes/art_modern/build.sh
  recipes/art_modern/meta.yaml
Labels: please review & merge

#59047 mawk: add arm64 build
  recipes/mawk/build.sh
  recipes/mawk/meta.yaml
Labels: osx-arm64

#59049 atropos: add arm64 build
  recipes/atropos/meta.yaml
Labels: osx-arm64

#59051 mageck: add arm64 build
  recipes/mageck/build.sh
  recipes/mageck/meta.yaml
Labels: osx-arm64

#59054 gridss: add arm64 build
  recipes/gridss/build.sh
  recipes/gridss/meta.yaml
Labels: MacOS related, osx-arm64

#59055 goleft: add arm64 build
  recipes/goleft/build.sh
  recipes/goleft/meta.yaml
Labels: osx-arm64

#59053 pyrle: add arm64 build
  recipes/pyrle/meta.yaml
Labels: osx-arm64

#59072 Update Jalview to 2.11.5.0
  recipes/jalview/meta.yaml
Labels: please review & merge

#59064 update peregrine-2021 and enabled linux-aarch64
  recipes/peregrine-2021/0001-main.patch
  recipes/peregrine-2021/build.sh
  recipes/peregrine-2021/meta.yaml
  recipes/peregrine-2021/patch
Labels: aarch64, osx-arm64

#59083 galah: add aarch64/arm64 builds
  recipes/galah/build.sh
  recipes/galah/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#59035 Add rastair: TAPS methylation caller
  recipes/rastair/build.sh
  recipes/rastair/meta.yaml
Labels: please review & merge

#59036 Add sierra local
  recipes/sierra-local/meta.yaml
Labels: please review & merge

#59127 update gempipe to v1.38.2
  recipes/gempipe/meta.yaml
Labels: please review & merge

#59169 groot: add arm64 build
  recipes/groot/build.sh
  recipes/groot/meta.yaml
Labels: osx-arm64

#59171 kaiju: add arm64 build
  recipes/kaiju/build.sh
  recipes/kaiju/meta.yaml
Labels: osx-arm64

#59168 locarna: add aarch64/arm64 builds
  recipes/locarna/build.sh
  recipes/locarna/meta.yaml
Labels: aarch64, osx-arm64

#59182 svdb: add arm64 build
  recipes/svdb/meta.yaml
Labels: osx-arm64

#59183 samsum: add arm64 build
  recipes/samsum/meta.yaml
Labels: osx-arm64

#59205 callerpp: add arm64 build
  recipes/callerpp/build.sh
  recipes/callerpp/meta.yaml
Labels: osx-arm64

#59207 fermi2 and bfc: add arm64 builds
  recipes/bfc/0001-Makefile-append-LIBS.patch
  recipes/bfc/build.sh
  recipes/bfc/meta.yaml
  recipes/fermi2/build.sh
  recipes/fermi2/meta.yaml
Labels: osx-arm64

#59222 splicemap: add aarch64/arm64 builds
  recipes/splicemap/0001-fix-string-array-initializer-assignment.patch
  recipes/splicemap/build.sh
  recipes/splicemap/meta.yaml
Labels: aarch64, osx-arm64

#59225 addrg: add arm64 build
  recipes/addrg/build.sh
  recipes/addrg/meta.yaml
Labels: osx-arm64

#59155 v3.3c Update
  recipes/egap/meta.yaml
Labels: please review & merge

#59084 Add allshp recipe
  recipes/alloshp/build.sh
  recipes/alloshp/meta.yaml
  recipes/alloshp/post-link.sh
Labels: please review & merge

#59304 Update suvtk to 0.1.6
  recipes/suvtk/LICENSE
  recipes/suvtk/meta.yaml
Labels: please review & merge

#59277 update bamm and enabled linux-aarch64
  recipes/bamm/build.sh
  recipes/bamm/meta.yaml
Labels: please review & merge

#59284 Update bcftools dependency
  recipes/vcf2maf/meta.yaml
Labels: please review & merge

#59286 Update pandas dependency
  recipes/tmb/meta.yaml
Labels: please review & merge

#59263 update gsearch and enabled linux-aarch64
  recipes/gsearch/meta.yaml
Labels: please review & merge

#59261 Add censtats
  recipes/censtats/meta.yaml
Labels: please review & merge

#59230 Add x-mapper
  recipes/x-mapper/build.sh
  recipes/x-mapper/meta.yaml
  recipes/x-mapper/x-mapper.sh
Labels: please review & merge

#59258 Add AltEx-BE
  altex-be/meta.yaml
Labels: please review & merge

#59313 added entry point to influx_si
  recipes/influx_si/meta.yaml
Labels: please review & merge

#59298 r-dimsum: relax cutadapt pin (>=2.4-0); bump build number
  recipes/r-dimsum/meta.yaml
Labels: please review & merge

#59321 Add quick-variants
  recipes/quick-variants/build.sh
  recipes/quick-variants/meta.yaml
  recipes/quick-variants/quick-variants.sh
Labels: please review & merge

#59272 v3.3 Updates
  recipes/egap/meta.yaml
Labels: please review & merge

#59329 Add Oxbow
  recipes/oxbow/meta.yaml
Labels: please review & merge

#59340 elprep: add arm64 build
  recipes/elprep/build.sh
  recipes/elprep/meta.yaml
Labels: osx-arm64

#59341 genepop: add arm64 build
  recipes/genepop/build.sh
  recipes/genepop/meta.yaml
Labels: osx-arm64

#59344 fraggenescan: add arm64 build
  recipes/fraggenescan/build.sh
  recipes/fraggenescan/meta.yaml
Labels: osx-arm64

#59348 phispy: add arm64 build
  recipes/phispy/meta.yaml
Labels: osx-arm64

#59346 clever-toolkit: add arm64 build
  recipes/clever-toolkit/build.sh
  recipes/clever-toolkit/meta.yaml
Labels: osx-arm64

#59372 ngs-bits: add arm64 build
  recipes/ngs-bits/build.sh
  recipes/ngs-bits/meta.yaml
Labels: osx-arm64

#59378 nonpareil: add arm64 build
  recipes/nonpareil/meta.yaml
Labels: osx-arm64

#59379 ont-modkit: add arm64 build
  recipes/ont-modkit/build.sh
  recipes/ont-modkit/build_failure.osx-64.yaml
  recipes/ont-modkit/meta.yaml
Labels: osx-arm64

#59380 tpmcalculator: add arm64 build
  recipes/tpmcalculator/build.sh
  recipes/tpmcalculator/meta.yaml
Labels: osx-arm64

#59382 bamutil: add arm64 build
  recipes/bamutil/build.sh
  recipes/bamutil/build_failure.osx-64.yaml
  recipes/bamutil/meta.yaml
Labels: osx-arm64

#59383 dsrc: add arm64 build
  recipes/dsrc/build.sh
  recipes/dsrc/meta.yaml
Labels: osx-arm64

#59407 Update meta.yaml for magneto 1.4
  recipes/magneto/meta.yaml
Labels: please review & merge

#59396 Update stripepy-hic to v1.2.0
  recipes/stripepy-hic/meta.yaml
Labels: please review & merge

#59419 Update beagle to 5.5_27Feb25.75f
  recipes/beagle/meta.yaml
Labels: please review & merge

#59392 Update COMEBin to use the utility script
  recipes/comebin/build.sh
  recipes/comebin/meta.yaml
Labels: please review & merge

#59350 update mtsv and enabled linux-aarch64
  build-fail-blacklist
  recipes/mtsv/meta.yaml
Labels: please review & merge

#58774 Add HyPlAs
  recipes/hyplas/build.sh
  recipes/hyplas/conda_build_config.yaml
  recipes/hyplas/meta.yaml
Labels: please review & merge

#59448 rust-bio-tools: add arm64 build
  recipes/rust-bio-tools/build.sh
  recipes/rust-bio-tools/build_failure.linux-64.yaml
  recipes/rust-bio-tools/build_failure.linux-aarch64.yaml
  recipes/rust-bio-tools/meta.yaml
Labels: MacOS related, osx-arm64

#59450 smalt: add aarch64 build
  build-fail-blacklist
  recipes/smalt/build.sh
  recipes/smalt/config.guess
  recipes/smalt/config.sub
  recipes/smalt/meta.yaml
Labels: aarch64

#59459 snp-dists: add arm64 build
  recipes/snp-dists/0001-Makefile-append-CFLAGS-LIBS.patch
  recipes/snp-dists/build.sh
  recipes/snp-dists/meta.yaml
Labels: osx-arm64

#59462 phynder: add arm64 build
  recipes/phynder/build.sh
  recipes/phynder/meta.yaml
Labels: osx-arm64

#59466 Update genbank to support python 3.13
  recipes/genbank/conda_build_config.yaml
  recipes/genbank/meta.yaml
Labels: please review & merge

#59465 Update art_modern to 1.1.7
  recipes/art_modern/build.sh
  recipes/art_modern/meta.yaml
Labels: please review & merge

#59463 Update gtars recipe
  recipes/rust-gtars/build.sh
  recipes/rust-gtars/meta.yaml
Labels: please review & merge

#59424 Add: `ipcr` 1.1.0 — pure‑Go in‑silico PCR CLI
  recipes/ipcr/LICENSE
  recipes/ipcr/build.sh
  recipes/ipcr/meta.yaml
Labels: please review & merge

#59471 Update concoct to fix numpy pinning
  recipes/concoct/meta.yaml
Labels: please review & merge

#59460 gangstr: add arm64 build
  recipes/gangstr/build.sh
  recipes/gangstr/build_failure.linux-64.yaml
  recipes/gangstr/build_failure.linux-aarch64.yaml
  recipes/gangstr/build_failure.osx-64.yaml
  recipes/gangstr/meta.yaml
Labels: osx-arm64

#59486 espresso: add aarch64 build
  recipes/espresso/LICENSE
  recipes/espresso/build.sh
  recipes/espresso/check_for_cc_env_var.patch
  recipes/espresso/meta.yaml
Labels: aarch64

#59488 stringdecomposer: add aarch64 build
  recipes/stringdecomposer/meta.yaml
Labels: aarch64

#59166 vt: add arm64 build
  recipes/vt/build.sh
  recipes/vt/meta.yaml
Labels: osx-arm64

#59490 decifer: add arm64 build
  recipes/decifer/build.sh
  recipes/decifer/meta.yaml
Labels: osx-arm64

#59492 survivor: add arm64 build
  recipes/survivor/build.sh
  recipes/survivor/meta.yaml
Labels: osx-arm64

#59495 bigtools: add arm64 build
  recipes/bigtools/build.sh
  recipes/bigtools/meta.yaml
Labels: osx-arm64

#59515 update mindthegap and enabled linux-aarch64
  recipes/mindthegap/build.sh
  recipes/mindthegap/meta.yaml
Labels: aarch64

#59528 knotinframe: add arm64 build
  recipes/knotinframe/build.sh
  recipes/knotinframe/meta.yaml
Labels: osx-arm64

#59533 fasta3: add arm64 build
  recipes/fasta3/build.sh
  recipes/fasta3/meta.yaml
Labels: osx-arm64

#59531 r-stitch: add arm64 build
  recipes/r-stitch/build.sh
  recipes/r-stitch/meta.yaml
Labels: osx-arm64

#59532 physher: add arm64 build
  recipes/physher/build.sh
  recipes/physher/build_failure.linux-64.yaml
  recipes/physher/build_failure.linux-aarch64.yaml
  recipes/physher/build_failure.osx-64.yaml
  recipes/physher/meta.yaml
  recipes/physher/physher-aarch64.patch
Labels: osx-arm64

#59537 dsk: add arm64 build
  recipes/dsk/build.sh
  recipes/dsk/install_paths.patch
  recipes/dsk/meta.yaml
Labels: MacOS related, osx-arm64

#59588 dbgraph: add arm64 build
  build-fail-blacklist
  recipes/dbgraph/build.sh
  recipes/dbgraph/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#59586 Update mira to v5.0.0rc2
  build-fail-blacklist
  recipes/mira/0001-cstdint.patch
  recipes/mira/build.sh
  recipes/mira/meta.yaml
Labels: aarch64

#59593 flash2: add arm64 build
  recipes/flash2/build.sh
  recipes/flash2/meta.yaml
  recipes/predicthaplo/build_failure.osx-64.yaml
Labels: osx-arm64

#59592 Update phanotate to support Python v3.13
  recipes/phanotate/conda_build_config.yaml
  recipes/phanotate/meta.yaml
Labels: aarch64, osx-arm64

#59594 Update tophat to v2.1.2
  recipes/tophat/0001-configure.ac.patch
  recipes/tophat/0002-make_pair.patch
  recipes/tophat/0003-tophat.patch
  recipes/tophat/0004-Makefile.patch
  recipes/tophat/build.sh
  recipes/tophat/meta.yaml
Labels: aarch64, osx-arm64

#59595 wgsim: add arm64 build
  recipes/wgsim/0001-Fix-shebang-in-perl-script.patch
  recipes/wgsim/build.sh
  recipes/wgsim/meta.yaml
Labels: osx-arm64

#59598 update genomeconstellation and enabled linux-aarch64
  recipes/genomeconstellation/build.sh
  recipes/genomeconstellation/jgi_gc.patch
  recipes/genomeconstellation/meta.yaml
Labels: aarch64, osx-arm64

#59319 update squid and linux-aarch64
  recipes/squid/build.sh
  recipes/squid/build_failure.linux-64.yaml
  recipes/squid/meta.yaml
Labels: aarch64, osx-arm64

#59318 update rxdock and linux-aarch64
  build-fail-blacklist
  recipes/rxdock/build.sh
  recipes/rxdock/meta.yaml
Labels: aarch64

#59640 Revert "update pbstarphase and enabled linux-aarch64 "
  recipes/pbstarphase/build.sh
  recipes/pbstarphase/meta.yaml
Labels: please review & merge

#59635 Fix ena-webin-cli bug due to unsafe wrapper script not doing proper shell quoting
  recipes/ena-webin-cli/ena_webin_cli.py
  recipes/ena-webin-cli/meta.yaml
Labels: please review & merge

#59628 Update Seqwin build number
  recipes/seqwin/meta.yaml
Labels: please review & merge

#58924 pxblat: enable osx-arm64
  recipes/pxblat/build_failure.linux-64.yaml
  recipes/pxblat/build_failure.osx-64.yaml
  recipes/pxblat/meta.yaml
Labels: osx-arm64

#59619 Update cenmap repeatmasker version due to minimized database
  recipes/cenmap/meta.yaml
Labels: please review & merge

#59641 Updated ngs-bits to version 2025_09
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#59616 add paraviewer recipe
  recipes/paraviewer/meta.yaml
Labels: please review & merge

#59651 Rebuild soapdenovo2-gapcloser recipe
  build-fail-blacklist
  recipes/soapdenovo2-gapcloser/build.sh
  recipes/soapdenovo2-gapcloser/meta.yaml
Labels: aarch64

#59631 Add bgen-cpp
  recipes/bgen-cpp/build.sh
  recipes/bgen-cpp/meta.yaml
Labels: please review & merge

#59658 clustalo: add arm64 build
  recipes/clustalo/build.sh
  recipes/clustalo/config.guess
  recipes/clustalo/config.sub
  recipes/clustalo/meta.yaml
Labels: osx-arm64

#59663 Update lodei v1.1.0
  recipes/lodei/meta.yaml
Labels: please review & merge

#59660 lca: add arm64 build
  recipes/lca/build.sh
  recipes/lca/meta.yaml
Labels: aarch64, osx-arm64

#59643 Update beacon2-ri-tools to V2 that uses python
  recipes/beacon2-ri-tools/build.sh
  recipes/beacon2-ri-tools/meta.yaml
Labels: please review & merge

#59683 prinseq-plus-plus: add arm64 build
  recipes/prinseq-plus-plus/build.sh
  recipes/prinseq-plus-plus/meta.yaml
Labels: osx-arm64

#59688 randfold: add arm64 build
  recipes/randfold/build.sh
  recipes/randfold/meta.yaml
Labels: osx-arm64

#59676 CryptoGenotyper v1.5.0 build #3
  recipes/cryptogenotyper/meta.yaml
Labels: please review & merge

#59671 Add r-hmm
  recipes/r-hmm/meta.yaml
Labels: please review & merge

#59724 Rebuild sweepfinder2 recipe
  build-fail-blacklist
  recipes/sweepfinder2/0001-Use-CC-and-flags.patch
  recipes/sweepfinder2/build.sh
  recipes/sweepfinder2/meta.yaml
Labels: aarch64, osx-arm64

#59725 Update RNAcode to v0.3.1
  build-fail-blacklist
  recipes/rnacode/build.sh
  recipes/rnacode/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#59729 rnabridge-align: add aarch64/arm64 builds
  recipes/rnabridge-align/build.sh
  recipes/rnabridge-align/meta.yaml
Labels: aarch64, osx-arm64

#59731 scallop: add aarch64/arm64 builds
  recipes/scallop/build.sh
  recipes/scallop/meta.yaml
Labels: aarch64, osx-arm64

#59733 scallop2: add aarch64/arm64 builds
  recipes/scallop2/build.sh
  recipes/scallop2/meta.yaml
Labels: aarch64, osx-arm64

#58661 update metawrap-mg recipe
  recipes/metawrap-mg/build.sh
  recipes/metawrap-mg/meta.yaml
Labels: please review & merge

#59753 Rebuild stacks recipe
  recipes/stacks/build.sh
  recipes/stacks/kmer_exit.patch
  recipes/stacks/limits.patch
  recipes/stacks/meta.yaml
  recipes/stacks/perl.patches
Labels: MacOS related, osx-arm64

#59761 rainbow: add aarch64/arm64 builds
  recipes/rainbow/build.sh
  recipes/rainbow/meta.yaml
Labels: aarch64, osx-arm64

#59765 Update nwalign3 to v0.1.6
  recipes/nwalign3/build_failure.linux-64.yaml
  recipes/nwalign3/build_failure.osx-64.yaml
  recipes/nwalign3/meta.yaml
Labels: aarch64, osx-arm64
