Repository bioconda/bioconda-recipes, pull requests merged in 2025-04, with the labels that each got.

#55002 fix freyja recipe with required minimum version for pyarrow
  recipes/freyja/meta.yaml
Labels: please review & merge

#55034 Update AmpliGone recipe for version 2.0.1
  recipes/ampligone/meta.yaml
Labels: please review & merge

#55061 Update eva-sub-cli to v0.4.6
  recipes/eva-sub-cli/meta.yaml
Labels: please review & merge

#55059 Update stare-abc yaml
  recipes/stare-abc/meta.yaml
Labels: please review & merge

#55064 update FROGS : create intermediate release 4.2.0
  recipes/frogs/4.2.0/build.sh
  recipes/frogs/4.2.0/meta.yaml
Labels: please review & merge

#54998 Proteinortho update to v6.3.5
  recipes/proteinortho/meta.yaml
Labels: please review & merge, new version

#55085 Update mumemto to 1.2.2
  recipes/mumemto/build.sh
  recipes/mumemto/meta.yaml
Labels: please review & merge

#55066 update sra-tools to 3.2.1
  recipes/sra-tools/meta.yaml
Labels: please review & merge

#55051 Update polap to v0.4.3.7.4
  recipes/polap/build.sh
  recipes/polap/meta.yaml
Labels: please review & merge

#55108 Update pybwa to 2.0.0
  recipes/pybwa/build.py.patch
  recipes/pybwa/meta.yaml
Labels: please review & merge

#55073 vsnp3 version 3.28
  recipes/vsnp3/meta.yaml
Labels: please review & merge

#55047 Bump `clusty` to 1.2.0
  recipes/clusty/meta.yaml
Labels: please review & merge

#55112 stacks: add linux-aarch64
  recipes/stacks/meta.yaml
Labels: please review & merge

#54894 solvebio: add linux-aarch64
  recipes/solvebio/meta.yaml
Labels: please review & merge

#55058 Bump `hmnfusion` to 1.3.0
  recipes/hmnfusion/meta.yaml
Labels: please review & merge

#55007 Update flumut
  recipes/flumut/meta.yaml
Labels: please review & merge

#54977 Update phyloacc to 2.4.3
  recipes/phyloacc/meta.yaml
  recipes/phyloacc/run_test.sh
Labels: please review & merge

#54976 Update el_gato version 1.21.2
  recipes/el_gato/meta.yaml
Labels: please review & merge

#55113 portcullis: Fix compile error, all platforms (boost deprecation); Add…
  recipes/portcullis/boost-leaf.patch
  recipes/portcullis/build.sh
  recipes/portcullis/build_failure.linux-64.yaml
  recipes/portcullis/m64.patch
  recipes/portcullis/meta.yaml
Labels: please review & merge

#54981 Add Yleaf-pipelines at 3.3.0
  recipes/yleaf-pipelines/build.sh
  recipes/yleaf-pipelines/conda_build_config.yaml
  recipes/yleaf-pipelines/meta.yaml
Labels: please review & merge

#54610 Update for CNAsim
  recipes/cnasim/meta.yaml
Labels: please review & merge

#55095 Update pantax to 1.2.0
  recipes/pantax/build.sh
  recipes/pantax/meta.yaml
Labels: please review & merge

#55021 add ddqc
  recipes/ddqc/meta.yaml
Labels: please review & merge

#55044 Add OGTFinder
  recipes/ogtfinder/meta.yaml
Labels: please review & merge

#55042 Add metaspace2020 recipe
  recipes/metaspace2020/meta.yaml
Labels: please review & merge

#55116 Add VCFX recipe
  recipes/vcfx/build.sh
  recipes/vcfx/meta.yaml
Labels: please review & merge

#55134 add pysctransform
  recipes/pysctransform/meta.yaml
Labels: please review & merge

#55089 Update met4j to 2.0.2
  recipes/met4j/meta.yaml
Labels: please review & merge

#55114 Add perl-postscript-simple recipe
  recipes/perl-postscript-simple/build.sh
  recipes/perl-postscript-simple/meta.yaml
Labels: please review & merge

#55100 Add clam
  recipes/clam/build.sh
  recipes/clam/meta.yaml
Labels: please review & merge

#54772 Add: derip2 recipe
  recipes/derip2/meta.yaml
Labels: please review & merge

#55004 Update Aliceasm
  recipes/aliceasm/meta.yaml
Labels: please review & merge

#54994 Add sr2silo package
  recipes/sr2silo/meta.yaml
Labels: please review & merge

#54979 Update elastic-blast to 1.4.0
  recipes/elastic-blast/meta.yaml
Labels: please review & merge

#55097 Add hisat-3n
  recipes/hisat-3n/build.sh
  recipes/hisat-3n/meta.yaml
  recipes/hisat-3n/simde-mr-c.patch
Labels: please review & merge

#55179 update dependencies of recipe pilea
  recipes/pilea/meta.yaml
Labels: please review & merge

#55167 Update hictk to v2.1.0
  recipes/hictk/build.sh
  recipes/hictk/conanfile.Dockerfile.py.patch
  recipes/hictk/meta.yaml
  recipes/hictk/run_test.sh
Labels: please review & merge

#55163 Update GRAMPA recipe
  recipes/grampa/meta.yaml
  recipes/grampa/run_test.sh
Labels: please review & merge

#55169 Update s4pred
  recipes/s4pred/build.sh
  recipes/s4pred/meta.yaml
Labels: please review & merge

#55168 Add cawlign recipe
  recipes/cawlign/build.sh
  recipes/cawlign/meta.yaml
Labels: please review & merge

#55159 Add MPRAlib
  recipes/mpralib/meta.yaml
Labels: please review & merge

#55124 Add rdrpcatch
  recipes/rdrpcatch/LICENSE
  recipes/rdrpcatch/meta.yaml
Labels: please review & merge

#55161 install_mimi_1.0.0
  recipes/mimi/meta.yaml
Labels: please review & merge

#55183 Add ovrlpy
  recipes/ovrlpy/meta.yaml
Labels: please review & merge

#55171 Add mypmfs_py package
  recipes/mypmfs_py/meta.yaml
Labels: please review & merge

#54829 Add recipe for GCI
  recipes/gci/meta.yaml
Labels: please review & merge

#55217 Update ToolDistillator from 0.9.1 to 0.9.2
  recipes/tooldistillator/meta.yaml
Labels: please review & merge

#55212 Update virulencefinder version
  recipes/virulencefinder/build.sh
  recipes/virulencefinder/download-virulence-db.sh
  recipes/virulencefinder/meta.yaml
  recipes/virulencefinder/post-link.sh
Labels: please review & merge

#55246 Update GRAMPA recipe
  recipes/grampa/build.sh
  recipes/grampa/meta.yaml
  recipes/grampa/run_test.sh
Labels: please review & merge

#55227 Update kbo-cli to v0.2.1.
  recipes/kbo-cli/meta.yaml
Labels: please review & merge

#55248 Update ganon to 2.1.1
  recipes/ganon/meta.yaml
Labels: please review & merge

#55209 fastqtk: add linux-aarch64
  recipes/fastqtk/meta.yaml
Labels: please review & merge

#55210 ➕ Update dependencies for vuegen v0.3.2
  recipes/vuegen/meta.yaml
Labels: please review & merge

#55238 epa-ng: add linux-aarch64
  recipes/epa-ng/build.sh
  recipes/epa-ng/cmake.patch
  recipes/epa-ng/genesis.patch
  recipes/epa-ng/meta.yaml
  recipes/epa-ng/pll_modules.patch
Labels: please review & merge

#55237 Update aliceasm
  recipes/aliceasm/build.sh
  recipes/aliceasm/meta.yaml
Labels: please review & merge

#55220 Update plink2 to 2.0.0-a.6.9
  recipes/plink2/meta.yaml
Labels: please review & merge

#55218 Updated build for ARM
  recipes/popgen-entropy/build.sh
  recipes/popgen-entropy/meta.yaml
Labels: please review & merge

#55258 Add amulety recipe
  recipes/amulety/meta.yaml
Labels: please review & merge

#54954 Add epicore recipe
  recipes/epicore/meta.yaml
Labels: please review & merge

#55262 Add cvanmf recipe
  recipes/cvanmf/meta.yaml
Labels: please review & merge

#55279 Add eider recipe
  recipes/eider/build.sh
  recipes/eider/meta.yaml
Labels: please review & merge

#55300 reduce: Update build script to add `-DHET_DICTIONARY` and `-DHET_DICTOLD` flags
  recipes/reduce/build.sh
  recipes/reduce/meta.yaml
Labels: please review & merge

#55299 Update to v4.5
  recipes/seqscreen/meta.yaml
Labels: please review & merge

#55298 Update ampliconsuite to 1.3.6
  recipes/ampliconsuite/meta.yaml
Labels: please review & merge

#55295 Update Sentieon recipe to 202503
  recipes/sentieon/meta.yaml
  recipes/sentieon/sentieon_symlinks.patch
Labels: please review & merge

#55263 Update recipe for dysgu
  recipes/dysgu/build.sh
  recipes/dysgu/meta.yaml
Labels: please review & merge

#55261 Add tmscoring
  recipes/tmscoring/meta.yaml
Labels: please review & merge

#55241 Update srnaMapper to new version
  recipes/srnamapper/build.sh
  recipes/srnamapper/meta.yaml
Labels: please review & merge

#55278 Update build of arborator to incorporate updated dependencies in container
  recipes/arborator/meta.yaml
Labels: please review & merge

#55284 Add mimick recipe
  recipes/mimick/meta.yaml
  recipes/visor/meta.yaml
Labels: please review & merge

#55277 Removed wfa2 external dependency in linux
  recipes/vcflib/build.sh
  recipes/vcflib/meta.yaml
Labels: please review & merge

#55269 eskrim does not work with python 3.13
  recipes/eskrim/meta.yaml
Labels: please review & merge

#54261 Add MACH2 v1.0.1
  recipes/mach2/meta.yaml
Labels: please review & merge

#55260 Update PPanGGOLiN
  recipes/ppanggolin/meta.yaml
Labels: please review & merge

#55349 Add DeepDETAILS
  recipes/deepdetails/meta.yaml
Labels: please review & merge

#55339 hictkpy: bump to v1.2.0
  recipes/hictkpy/build.sh
  recipes/hictkpy/conan_profiles/apple-clang
  recipes/hictkpy/conan_profiles/clang
  recipes/hictkpy/conanfile.py.patch
  recipes/hictkpy/conda_build_config.yaml
  recipes/hictkpy/meta.yaml
  recipes/hictkpy/pyproject.toml.patch
Labels: please review & merge

#55203 Add TWILIGHT v0.1.1
  recipes/twilight/CMakeLists.txt
  recipes/twilight/build.sh
  recipes/twilight/meta.yaml
Labels: please review & merge

#55204 Add recipe for bbmapy
  recipes/bbmapy/meta.yaml
Labels: please review & merge

#54983 Update Vamb to 5.0.3
  recipes/vamb/meta.yaml
Labels: please review & merge

#54922 Add bakrep-cli to BioConda
  recipes/bakrep-cli/meta.yaml
Labels: help wanted

#55347 Update mysterymaster meta.yaml
  recipes/mysterymaster/meta.yaml
Labels: please review & merge

#55257 Add cdskit
  recipes/cdskit/meta.yaml
Labels: please review & merge

#55224 Add kmer2stats recipe
  recipes/kmer2stats/meta.yaml
Labels: please review & merge

#55118 add r-bpcells
  recipes/r-bpcells/build.sh
  recipes/r-bpcells/meta.yaml
  recipes/r-bpcells/patches/0001-fix-libhwy-config.patch
  recipes/r-bpcells/patches/0002-granges-conversion.patch
Labels: please review & merge

#54563 update pasta
  recipes/pasta/build.sh
  recipes/pasta/meta.yaml
  recipes/pasta/share/pasta/data/small.fasta
Labels: please review & merge

#55385 Add ervmancer
  recipes/ervmancer/meta.yaml
Labels: please review & merge

#55392 sfld: add linux-aarch64
  recipes/sfld/meta.yaml
Labels: please review & merge

#55384 paraclu: add linux-aarch64
  recipes/paraclu/meta.yaml
Labels: please review & merge

#55132 Add r-floral
  recipes/r-floral/meta.yaml
Labels: please review & merge

#55375 Update Replidec v0.3.4
  recipes/replidec/meta.yaml
Labels: please review & merge

#55398 delly: add arm64 build
  recipes/delly/build.sh
  recipes/delly/meta.yaml
Labels: osx-arm64

#55400 Rebuild postmaster recipe
  recipes/postmaster/meta.yaml
Labels: aarch64, osx-arm64

#54560 update concoct
  recipes/concoct/build.sh
  recipes/concoct/meta.yaml
Labels: please review & merge

#55406 Update pneumo-typer to v2.0.1#2
  recipes/pneumo-typer/build.sh
  recipes/pneumo-typer/meta.yaml
Labels: please review & merge

#55405 Update gcluster to v2.0.7#4
  recipes/gcluster/build.sh
  recipes/gcluster/meta.yaml
Labels: please review & merge

#55407 Relax Python version requirement to >=3.8 (support Python 3.12)
  recipes/cdskit/meta.yaml
Labels: please review & merge

#54546 update pigpen_0.0.6 to include r-lme4 and postmaster
  recipes/pigpen/meta.yaml
Labels: please review & merge

#55413 augustus: add linux-aarch64
  recipes/augustus/conda_build_config.yaml
  recipes/augustus/meta.yaml
Labels: please review & merge

#55415 aster: add arm64 build
  recipes/aster/build.sh
  recipes/aster/meta.yaml
Labels: osx-arm64

#53044 Update roadies to 0.1.8
  recipes/roadies/build.sh
  recipes/roadies/meta.yaml
Labels: please review & merge

#55439 Add libcarna
  recipes/libcarna/build.sh
  recipes/libcarna/meta.yaml
  recipes/libcarna/run_test.sh
  recipes/libcarna/test/CMakeLists.txt
  recipes/libcarna/test/test.cpp
Labels: please review & merge

#55467 Update GEMMA to 0.98.5, fix build issues
  build-fail-blacklist
  recipes/gemma/build.sh
  recipes/gemma/meta.yaml
Labels: please review & merge

#55455 Add nail
  recipes/nail/meta.yaml
Labels: please review & merge

#55448 Update: Codingquarry add osx-arm64
  recipes/codingquarry/meta.yaml
Labels: help wanted, please review & merge, osx-arm64

#55445 Update: Emboss add osx-arm64
  recipes/emboss/meta.yaml
Labels: help wanted, please review & merge, osx-arm64

#55419 rgi: update to 6.0.4, add linux-aarch64, by enabling diamond 0.8.36 for linux-aarch64
  recipes/diamond/0.8.36/build.sh
  recipes/diamond/0.8.36/meta.yaml
  recipes/diamond/2.0.4/build.sh
  recipes/diamond/2.0.4/meta.yaml
  recipes/diamond/build.sh
  recipes/diamond/meta.yaml
  recipes/rgi/meta.yaml
Labels: please review & merge

#55429 hictkpy: pin numpy version
  recipes/hictkpy/meta.yaml
Labels: please review & merge

#54370 Add MVAPICH4.0 to ESME
  recipes/esme/conda_build_config.yaml
  recipes/esme/meta.yaml
Labels: please review & merge

#55424 Update stripepy-hic to 1.0.0
  recipes/stripepy-hic/meta.yaml
  recipes/stripepy-hic/run_test.sh
Labels: please review & merge

#55180 Update maxit to v11.300
  recipes/maxit/Makefile.patch
  recipes/maxit/meta.yaml
Labels: please review & merge

#55521 Update usalign to 20241201
  recipes/usalign/meta.yaml
Labels: please review & merge

#55500 Update r-dimsum to 1.4; Fix: Incorporate autobump version update and allow any patch version of fastqc 0.11
  recipes/r-dimsum/meta.yaml
Labels: please review & merge

#55495 Update annembed v0.2.4
  recipes/annembed/meta.yaml
Labels: please review & merge

#55461 Update dmox to 0.2.0
  recipes/dmox/meta.yaml
Labels: please review & merge

#55450 Add recipe for hmftools-teal 1.3.3
  recipes/hmftools-teal/build.sh
  recipes/hmftools-teal/meta.yaml
  recipes/hmftools-teal/teal.sh
Labels: please review & merge

#55449 Add recipe for hmftools-cider 1.0.3
  recipes/hmftools-cider/build.sh
  recipes/hmftools-cider/cider.sh
  recipes/hmftools-cider/meta.yaml
Labels: please review & merge

#55516 Update cogclassifier to 2.0.0
  recipes/cogclassifier/meta.yaml
  recipes/cogclassifier/run_test.sh
Labels: please review & merge

#55457 Add HYMET
  recipes/hymet/LICENSE
  recipes/hymet/build.sh
  recipes/hymet/meta.yaml
  recipes/hymet/post-link.sh
Labels: please review & merge

#55444 Update Recon add osx-arm64
  recipes/recon/build.sh
  recipes/recon/meta.yaml
Labels: help wanted, osx-arm64

#55566 Update nail
  recipes/nail/meta.yaml
Labels: please review & merge

#55576 Update ncbi-amrfinderplus to 4.0.22
  recipes/ncbi-amrfinderplus/build.sh
  recipes/ncbi-amrfinderplus/meta.yaml
Labels: please review & merge, new version

#55567 Bump shinyngs
  recipes/r-shinyngs/meta.yaml
Labels: please review & merge

#55577 Update TD2
  recipes/td2/meta.yaml
Labels: please review & merge

#55581 Update twilight (only modify description)
  recipes/twilight/meta.yaml
Labels: please review & merge

#55583 Update nbitk to v0.5.2
  recipes/nbitk/meta.yaml
Labels: please review & merge

#55519 initial release of conservation
  recipes/conservation/meta.yaml
Labels: please review & merge

#55569 Add cligv: command line Interactive Genome Viewer
  recipes/cligv/meta.yaml
Labels: please review & merge

#55585 Add Bygul
  recipes/bygul/meta.yaml
Labels: please review & merge

#55584 Add PanMAN v0.1.2
  recipes/panman/CMakeLists.txt
  recipes/panman/build.sh
  recipes/panman/meta.yaml
Labels: please review & merge

#55571 Add prooverlap
  recipes/prooverlap/meta.yaml
Labels: please review & merge

#55425 Add r-easypar
  recipes/r-easypar/build.sh
  recipes/r-easypar/meta.yaml
Labels: please review & merge

#55593 Fixed wakhan numpy version
  recipes/wakhan/meta.yaml
Labels: please review & merge

#55608 Update mimick build
  recipes/mimick/meta.yaml
Labels: please review & merge

#55570 Add barcode-validator v2.0.0
  recipes/barcode-validator/meta.yaml
Labels: please review & merge

#55597 perl-html-parser: add osx-arm64
  recipes/perl-html-parser/meta.yaml
Labels: please review & merge

#55586 Update eukfinder to v1.2.4
  recipes/eukfinder/build.sh
  recipes/eukfinder/meta.yaml
Labels: please review & merge

#55645 SISTR v1.1.3 build #2 release to fix I 1,4,[5],12:i:- serovar mistyped for I 1,4,[5],12:b:-
  recipes/sistr_cmd/meta.yaml
Labels: please review & merge

#55580 Add spacerplacer
  recipes/spacerplacer/meta.yaml
Labels: please review & merge

#55153 Add plasmidcommunity version 1.0.0
  recipes/plasmidcommunity/meta.yaml
Labels: please review & merge

#55661 📌 Update python version for vuegen
  recipes/vuegen/meta.yaml
Labels: please review & merge

#55666 perl-sereal-encoder: add osx-arm64
  recipes/perl-sereal-encoder/meta.yaml
Labels: please review & merge

#55664 perl-cgi: add osx-arm64
  recipes/perl-cgi/meta.yaml
Labels: please review & merge

#55642 ➕ Add Nim-abif 🧬
  recipes/nim-abif/build.sh
  recipes/nim-abif/meta.yaml
Labels: please review & merge

#55683 Update: added arm support for proteinortho
  recipes/proteinortho/meta.yaml
Labels: please review & merge

#55690 add dependency for recipe melon
  recipes/melon/meta.yaml
Labels: please review & merge

#55699 Updated barcode_validator to v2.0.1
  recipes/barcode-validator/meta.yaml
Labels: please review & merge

#55696 Update nbitk to v0.5.3
  recipes/nbitk/meta.yaml
Labels: please review & merge

#55677 star: add osx-arm64
  recipes/star/build.sh
  recipes/star/meta.yaml
  recipes/star/patches/0004-use-cxxflags-depends.patch
Labels: please review & merge

#55691 update ice-cream to v2.0.0
  recipes/ice-cream/build.sh
  recipes/ice-cream/meta.yaml
Labels: please review & merge

#55695 Add phlame v.1.0.8
  recipes/phlame/LICENSE.md
  recipes/phlame/meta.yaml
Labels: please review & merge
