Repository bioconda/bioconda-recipes, pull requests merged in 2025-07, with the labels that each got.

#57409 Update ucsc-overlapselect to v482
  recipes/ucsc-overlapselect/build.sh
  recipes/ucsc-overlapselect/meta.yaml
Labels: please review & merge

#57402 Update ucsc-hgloadbed
  recipes/ucsc-hgloadbed/build.sh
  recipes/ucsc-hgloadbed/meta.yaml
Labels: please review & merge

#57438 Update NORDic to 2.7.0
  recipes/nordic/build.sh
  recipes/nordic/meta.yaml
Labels: please review & merge

#57421 update flash2 and enabled linux-aarch64
  recipes/flash2/meta.yaml
Labels: please review & merge

#57164 update domclust
  build-fail-blacklist
  recipes/domclust/build.sh
  recipes/domclust/meta.yaml
Labels: aarch64

#57430 update ls-gkm
  build-fail-blacklist
  recipes/ls-gkm/0001-master.patch
  recipes/ls-gkm/build.sh
  recipes/ls-gkm/meta.yaml
Labels: please review & merge

#57473 libcifpp: Update CMake configuration
  recipes/libcifpp/activate.sh
  recipes/libcifpp/build.sh
  recipes/libcifpp/deactivate.sh
  recipes/libcifpp/meta.yaml
Labels: please review & merge

#57487 Update vcf-validator to 0.10.1
  recipes/vcf-validator/build.sh
  recipes/vcf-validator/meta.yaml
Labels: please review & merge

#57481 Update dependencies of matchms 0.30.2 to fit with pyproject.toml file
  recipes/matchms/meta.yaml
Labels: please review & merge

#57439 Add recipe for newmap
  recipes/newmap/0001-CMakeLists.patch
  recipes/newmap/build.sh
  recipes/newmap/meta.yaml
  recipes/newmap/run_test.sh
Labels: please review & merge

#57509 coot-headless: Update `run_exports`
  recipes/coot-headless/meta.yaml
Labels: please review & merge

#57526 Fix Python host version in `pyhmmer` recipe
  recipes/pyhmmer/meta.yaml
Labels: please review & merge

#57516 update fwdpp and enabled linux-aarch64
  build-fail-blacklist
  recipes/fwdpp/build.sh
  recipes/fwdpp/meta.yaml
Labels: please review & merge

#57517 ADD: Finaletoolkit 0.10.7
  recipes/finaletoolkit/meta.yaml
Labels: please review & merge

#57518 update fqtools and enabled linux-aarch64
  recipes/fqtools/build.sh
  recipes/fqtools/meta.yaml
Labels: please review & merge

#57281 update r-rphast
  recipes/r-rphast/0001-fix-lapack-interfaces.patch
  recipes/r-rphast/build.sh
  recipes/r-rphast/meta.yaml
Labels: please review & merge

#57556 Update snap to 2017_03_01
  recipes/snap/0001-Makefile.patch
  recipes/snap/build.sh
  recipes/snap/build_failure.linux-64.yaml
  recipes/snap/meta.yaml
  recipes/snap/wrapper
Labels: aarch64, osx-arm64

#57574 Update hifiasm_meta to version 0.3.3
  recipes/hifiasm_meta/meta.yaml
Labels: please review & merge

#57559 update flams
  recipes/flams/meta.yaml
Labels: please review & merge

#57572 Update n50
  recipes/n50/build.sh
  recipes/n50/meta.yaml
  recipes/n50/run_test.sh
  recipes/n50/test.fa
Labels: aarch64, osx-arm64

#57603 Update stripepy-hic to v1.1.1
  recipes/stripepy-hic/meta.yaml
Labels: please review & merge

#57608 seqtk: add arm64 build
  recipes/seqtk/0001-makefile.patch
  recipes/seqtk/build.sh
  recipes/seqtk/meta.yaml
Labels: osx-arm64

#57609 Rebuild slivar recipe
  recipes/slivar/0001-master.patch
  recipes/slivar/build.sh
  recipes/slivar/meta.yaml
Labels: MacOS related, aarch64

#57612 Update vcfanno to 0.3.6
  recipes/vcfanno/build.sh
  recipes/vcfanno/meta.yaml
Labels: osx-arm64

#57615 Update mosdepth to v0.3.11
  recipes/mosdepth/build.sh
  recipes/mosdepth/meta.yaml
Labels: osx-arm64

#57585 Rebuild odgi recipe
  recipes/odgi/0001-master.patch
  recipes/odgi/build.sh
  recipes/odgi/meta.yaml
Labels: MacOS related, osx-arm64

#57616 d4tools: add arm64 build
  recipes/d4tools/build.sh
  recipes/d4tools/build_failure.osx-64.yaml
  recipes/d4tools/build_htslib.sh
  recipes/d4tools/conda_build_config.yaml
  recipes/d4tools/meta.yaml
Labels: osx-arm64

#57614 coot-headless: Add python3.13 to build matrix
  recipes/coot-headless/conda_build_config.yaml
  recipes/coot-headless/meta.yaml
Labels: please review & merge

#57618 ropebwt2: add arm64 build
  recipes/ropebwt2/build.sh
  recipes/ropebwt2/meta.yaml
Labels: osx-arm64

#57619 Update FMLRC2 to v0.1.8
  build-fail-blacklist
  recipes/fmlrc2/build.sh
  recipes/fmlrc2/meta.yaml
Labels: aarch64, osx-arm64

#57617 d4binding: add arm64 build
  recipes/d4binding/build.sh
  recipes/d4binding/build_failure.osx-64.yaml
  recipes/d4binding/build_htslib.sh
  recipes/d4binding/conda_build_config.yaml
  recipes/d4binding/meta.yaml
Labels: osx-arm64

#54714 linux-aarch64 build for coverm
  recipes/coverm/build.sh
  recipes/coverm/meta.yaml
Labels: please review & merge

#54731 Add recipe AdDeam
  recipes/addeam/build.sh
  recipes/addeam/meta.yaml
Labels: please review & merge

#55035 add clinCNV, R tools
  recipes/clincnv/build.sh
  recipes/clincnv/meta.yaml
Labels: please review & merge

#57648 update marker-magu
  recipes/marker-magu/meta.yaml
Labels: please review & merge

#54760 Add pangwas-0.1.0
  recipes/pangwas/meta.yaml
Labels: please review & merge

#57631 Add pyngost 1.1.3
  recipes/pyngost/build.sh
  recipes/pyngost/meta.yaml
Labels: please review & merge

#57678 Enable ARM builds for `kcounter`
  recipes/kcounter/build.sh
  recipes/kcounter/meta.yaml
Labels: please review & merge

#57645 Update: Enable osx-arm64 build for csubst (bump build number)
  recipes/csubst/meta.yaml
Labels: please review & merge

#57525 Update ucsc-hgspeciesrna to v482
  recipes/ucsc-hgspeciesrna/build.sh
  recipes/ucsc-hgspeciesrna/meta.yaml
Labels: please review & merge

#57700 Update bindash v2.6
  recipes/bindash/meta.yaml
Labels: please review & merge

#53137 bioconductor-alabaster.base: fix osx-64 build
  recipes/bioconductor-alabaster.base/build.sh
  recipes/bioconductor-alabaster.base/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.base/conda_build_config.yaml
  recipes/bioconductor-alabaster.base/meta.yaml
Labels: please review & merge

#57727 Build bioconductor-alabaster.matrix for osx-64 (and remove old failures)
  recipes/bioconductor-alabaster.bumpy/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.files/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.mae/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.matrix/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.matrix/meta.yaml
  recipes/bioconductor-alabaster.ranges/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.sce/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.se/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.spatial/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.string/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster.vcf/build_failure.osx-64.yaml
  recipes/bioconductor-alabaster/build_failure.osx-64.yaml
  recipes/bioconductor-celldex/build_failure.osx-64.yaml
  recipes/bioconductor-scrnaseq/build_failure.osx-64.yaml
  recipes/bioconductor-singlecelltk/build_failure.osx-64.yaml
Labels: please review & merge

#57718 Update amdirt build (pin dependency to ensure correct version for table view)
  recipes/amdirt/meta.yaml
Labels: please review & merge

#57653 update maxentpy
  recipes/maxentpy/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#57715 Update atlas
  recipes/atlas/meta.yaml
Labels: please review & merge

#57712 Add minimod
  recipes/minimod/build.sh
  recipes/minimod/meta.yaml
Labels: please review & merge

#57763 New EviAnn evidence-based eukaryotic annotation pipeline
  recipes/eviann/build.sh
  recipes/eviann/meta.yaml
Labels: please review & merge

#57774 Update dependencies for snakemake-storage-plugin-s3
  recipes/snakemake-storage-plugin-s3/meta.yaml
Labels: please review & merge

#57754 Add NetMD recipe
  recipes/netmd/build.sh
  recipes/netmd/meta.yaml
Labels: please review & merge

#57786 dna-nn: add arm64 build
  recipes/dna-nn/build.sh
  recipes/dna-nn/build_failure.osx-64.yaml
  recipes/dna-nn/meta.yaml
Labels: osx-arm64

#53141 fix bioconductor-rbowtie2
  recipes/bioconductor-rbowtie2/0001-Makefile.patch
  recipes/bioconductor-rbowtie2/build.sh
  recipes/bioconductor-rbowtie2/build_failure.linux-64.yaml
  recipes/bioconductor-rbowtie2/build_failure.linux-aarch64.yaml
  recipes/bioconductor-rbowtie2/build_failure.osx-64.yaml
  recipes/bioconductor-rbowtie2/meta.yaml
Labels: please review & merge

#57418 Add genome-uploader recipe
  recipes/genome-uploader/meta.yaml
Labels: please review & merge

#57717 Add ccp4srs
  recipes/ccp4srs/LICENSE
  recipes/ccp4srs/build.sh
  recipes/ccp4srs/meta.yaml
Labels: please review & merge

#57699 Add tortoize v2.0.15
  recipes/tortoize/build.sh
  recipes/tortoize/meta.yaml
  recipes/tortoize/run_test.sh
Labels: please review & merge

#57802 reduce: Enable python bindings
  recipes/reduce/3QUG.pdb
  recipes/reduce/build.sh
  recipes/reduce/meta.yaml
  recipes/reduce/run_test.sh
Labels: please review & merge

#57814 arriba: add arm64 build
  recipes/arriba/build.sh
  recipes/arriba/build_failure.linux-64.yaml
  recipes/arriba/build_failure.linux-aarch64.yaml
  recipes/arriba/build_failure.osx-64.yaml
  recipes/arriba/meta.yaml
Labels: osx-arm64

#57818 Update pyrodigal build python 3.13 issue
  recipes/pyrodigal/conda_build_config.yaml
  recipes/pyrodigal/meta.yaml
Labels: please review & merge

#57843 Udapte TWILIGHT to v0.1.4a
  recipes/twilight/meta.yaml
Labels: please review & merge

#57834 Update: add flye to amira dependencies
  recipes/amira/meta.yaml
Labels: please review & merge

#57794 Update scispacy to add models
  recipes/scispacy/meta.yaml
  recipes/scispacy/post-link.sh
Labels: please review & merge

#57881 htseq: add osx-arm64
  recipes/htseq/meta.yaml
Labels: please review & merge, osx-arm64

#57866 Update bioconductor-hmmcopy to build on osx-arm64
  recipes/bioconductor-hmmcopy/meta.yaml
Labels: please review & merge, osx-arm64

#57863 Update NetMD
  recipes/netmd/meta.yaml
Labels: please review & merge

#57869 libcifpp: Enable downloading a CCD file
  recipes/libcifpp/build.sh
  recipes/libcifpp/meta.yaml
Labels: please review & merge

#57861 Rebuild pantax version 2.0.0
  recipes/pantax/build.sh
  recipes/pantax/meta.yaml
Labels: please review & merge

#57907 Update Renaming package bio-unicorn to enhjoerning
  recipes/bio-unicorn/build.sh
  recipes/enhjoerning/build.sh
  recipes/enhjoerning/meta.yaml
Labels: please review & merge

#57945 Update craq build script with expected relative paths
  recipes/craq/build.sh
  recipes/craq/meta.yaml
Labels: please review & merge

#57952 bump kma
  recipes/kma/meta.yaml
Labels: please review & merge

#57836 Add privateer MK V
  recipes/privateer/activate.fish
  recipes/privateer/activate.sh
  recipes/privateer/build.sh
  recipes/privateer/deactivate.fish
  recipes/privateer/deactivate.sh
  recipes/privateer/meta.yaml
  recipes/privateer/run_test.py
  recipes/privateer/run_test.sh
Labels: please review & merge

#57943 Update hmftools-chord to 2.1.2
  recipes/hmftools-chord/meta.yaml
Labels: please review & merge

#57920 update gctb and enabled linux-aarch64
  recipes/gctb/build.sh
  recipes/gctb/meta.yaml
Labels: please review & merge

#57927 Update kmergenie
  recipes/kmergenie/build.sh
  recipes/kmergenie/meta.yaml
Labels: please review & merge

#57944 Add hmftools-wisp
  recipes/hmftools-wisp/build.sh
  recipes/hmftools-wisp/meta.yaml
  recipes/hmftools-wisp/wisp.sh
Labels: please review & merge

#57942 In hmftools, use com.hartwig. to detect class path being provided to java call
  recipes/hmftools-amber/amber.sh
  recipes/hmftools-cobalt/cobalt.sh
  recipes/hmftools-isofox/isofox.sh
  recipes/hmftools-lilac/lilac.sh
  recipes/hmftools-orange/orange.sh
  recipes/hmftools-pave/pave.sh
  recipes/hmftools-peach/peach.sh
  recipes/hmftools-sigs/sigs.sh
  recipes/hmftools-virus-interpreter/virusinterpreter.sh
Labels: please review & merge

#57982 bellmans-gapc: add arm64 build
  recipes/bellmans-gapc/build.sh
  recipes/bellmans-gapc/build_failure.linux-aarch64.yaml
  recipes/bellmans-gapc/meta.yaml
Labels: osx-arm64

#57977 update genefuse and enabled lniux-aarch64
  recipes/genefuse/build.sh
  recipes/genefuse/meta.yaml
  recipes/genefuse/patch
Labels: aarch64, osx-arm64

#57985 Update MutScan to v1.14.1
  recipes/mutscan/build.sh
  recipes/mutscan/meta.yaml
  recipes/mutscan/patch
Labels: aarch64, osx-arm64

#57979 update genform and enabled linux-aarch64
  recipes/genform/build.sh
  recipes/genform/meta.yaml
Labels: please review & merge

#58006 Update met4j to 2.1.0
  recipes/met4j/meta.yaml
Labels: please review & merge

#58015 Update lsabgc build
  recipes/lsabgc/meta.yaml
Labels: please review & merge

#57946 Add alphafill v2.2.0
  recipes/alphafill/build.sh
  recipes/alphafill/meta.yaml
  recipes/alphafill/run_test.sh
Labels: please review & merge

#58056 Winnowmap: add aarch64/arm64 builds
  recipes/winnowmap/build.sh
  recipes/winnowmap/meta.yaml
Labels: aarch64, osx-arm64

#58022 update mp-est
  recipes/mp-est/build.sh
  recipes/mp-est/meta.yaml
Labels: aarch64, osx-arm64

#58023 Update ribotin to version 1.5
  recipes/ribotin/build.sh
  recipes/ribotin/meta.yaml
Labels: please review & merge

#58061 readfq: add aarch64/arm64 builds
  recipes/readfq/build.sh
  recipes/readfq/meta.yaml
Labels: aarch64, osx-arm64

#58016 Trigger building hmftools containers with fix "Use com.hartwig. to detect class path being provided to java call"
  recipes/hmftools-cobalt/meta.yaml
  recipes/hmftools-isofox/meta.yaml
  recipes/hmftools-pave/meta.yaml
Labels: please review & merge

#58065 Update antismash to v8.0.2
  recipes/antismash/build.sh
  recipes/antismash/meta.yaml
Labels: please review & merge

#58069 update nanoblaster
  recipes/nanoblaster/build.sh
  recipes/nanoblaster/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#58079 privateer: Rename activation and deactivation scripts
  recipes/privateer/build.sh
  recipes/privateer/meta.yaml
Labels: please review & merge

#58074 reduce: Change `het_dict` files location
  recipes/reduce/build.sh
  recipes/reduce/meta.yaml
Labels: please review & merge

#58096 Add smakcr
  recipes/smakcr/meta.yaml
Labels: please review & merge

#58151 Update soapdenovo-trans to v1.0.5
  recipes/soapdenovo-trans/0001-makefile.patch
  recipes/soapdenovo-trans/0002-osx-no-rt-link.patch
  recipes/soapdenovo-trans/build.sh
  recipes/soapdenovo-trans/meta.yaml
Labels: MacOS related, aarch64

#58156 update ghostz and enabled linux-aarch64
  recipes/ghostz/build.sh
  recipes/ghostz/meta.yaml
Labels: please review & merge

#58169 Update nomadic to v0.5.0
  recipes/nomadic/meta.yaml
Labels: please review & merge
