Repository bioconda/bioconda-recipes, pull requests merged in 2025-02, with the labels that each got.

#53611 Update `nafcodec` to `v0.3.1`
  recipes/nafcodec/meta.yaml
Labels: please review & merge

#53621 Enable `linux-aarch64` for `nafcodec`
  recipes/nafcodec/meta.yaml
Labels: please review & merge

#53635 Update NanoPlot to v1.44.1
  recipes/nanoplot/meta.yaml
Labels: please review & merge

#53629 Add `osx-arm64` build to `pydustmasker`
  recipes/pydustmasker/build.sh
  recipes/pydustmasker/meta.yaml
Labels: please review & merge

#53633 Add a3partitioner v0.1.0
  recipes/a3partitioner/meta.yaml
Labels: please review & merge

#53626 SPP-DCJ
  recipes/spp-dcj/meta.yaml
Labels: please review & merge

#53638 twopaco: add aarch64/arm64 builds
  recipes/twopaco/build.sh
  recipes/twopaco/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53608 perl-gd & perl-gdtextutil: add aarch64/arm64 builds
  build-fail-blacklist
  recipes/perl-gd/build.sh
  recipes/perl-gd/meta.yaml
  recipes/perl-gdtextutil/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53668 Update nbitk to v0.4.0
  recipes/nbitk/meta.yaml
Labels: please review & merge

#53663 Update build number of arborator (2->3)
  recipes/arborator/meta.yaml
Labels: please review & merge

#53674 Add recipe for ctyper v1.0
  recipes/ctyper/0001-Makefile.patch
  recipes/ctyper/0002-src.patch
  recipes/ctyper/build.sh
  recipes/ctyper/meta.yaml
Labels: aarch64

#53488 UPDATE troubleshoot transannot build
  recipes/transannot/build.sh
  recipes/transannot/meta.yaml
Labels: please review & merge

#53667 fastx_toolkit: add linux-aarch64 build
  recipes/fastx_toolkit/build.sh
  recipes/fastx_toolkit/build_failure.osx-64.yaml
  recipes/fastx_toolkit/fastx-toolkit-gcc7.patch
  recipes/fastx_toolkit/fastx.patch
  recipes/fastx_toolkit/meta.yaml
Labels: please review & merge, aarch64

#53583 Add magneto
  recipes/magneto/meta.yaml
Labels: please review & merge

#53679 Update cramino to 0.16.0
  recipes/cramino/meta.yaml
Labels: please review & merge

#53640 Update manta - Add back missing scripts
  recipes/manta/build.sh
  recipes/manta/meta.yaml
Labels: please review & merge

#53681 update yaml
  recipes/a3partitioner/meta.yaml
Labels: please review & merge

#53688 krbalancing: add arm64 build
  recipes/krbalancing/build.sh
  recipes/krbalancing/meta.yaml
Labels: osx-arm64

#53685 Update biobox_add_taxid
  recipes/biobox_add_taxid/meta.yaml
Labels: please review & merge

#53690 Updating bioconductor-limma for osx-arm64
  recipes/bioconductor-limma/meta.yaml
Labels: please review & merge

#53694 Updating bioconductor-pcamethods for osx-arm64
  recipes/bioconductor-pcamethods/meta.yaml
Labels: please review & merge

#53697 Updating bioconductor-biocparallel for osx-arm64
  recipes/bioconductor-biocparallel/meta.yaml
Labels: please review & merge

#53700 dialign-tx: add arm64 build
  recipes/dialign-tx/Makefile
  recipes/dialign-tx/Makefile.MAC_OS
  recipes/dialign-tx/build.sh
  recipes/dialign-tx/build_failure.linux-64.yaml
  recipes/dialign-tx/build_failure.osx-64.yaml
  recipes/dialign-tx/meta.yaml
Labels: osx-arm64

#53701 perl-data-uuid: add aarch64/arm64 builds
  recipes/perl-data-uuid/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53702 clustalw: add arm64 build
  recipes/clustalw/build.sh
  recipes/clustalw/build_failure.osx-64.yaml
  recipes/clustalw/meta.yaml
Labels: osx-arm64

#53080 Add muset recipe
  recipes/muset/build.sh
  recipes/muset/conda_build_config.yaml
  recipes/muset/meta.yaml
Labels: please review & merge

#53705 perl-params-validate: add linux-aarch64
  recipes/perl-params-validate/meta.yaml
Labels: please review & merge

#53718 Updating bioconductor-globalancova for osx-arm64
  recipes/bioconductor-globalancova/meta.yaml
  recipes/bioconductor-graph/meta.yaml
Labels: please review & merge

#53715 Updating some bioconductor packages for osx-arm64
  recipes/bioconductor-genefilter/meta.yaml
  recipes/bioconductor-impute/meta.yaml
  recipes/bioconductor-preprocesscore/meta.yaml
  recipes/bioconductor-rgraphviz/meta.yaml
  recipes/bioconductor-sva/meta.yaml
Labels: please review & merge

#53716 Update biox to 1.2.0
  recipes/biox/meta.yaml
Labels: please review & merge

#53725 Update learnmsa to 2.0.10
  recipes/learnmsa/meta.yaml
Labels: please review & merge

#53736 Updating bioconductor-rbgl for osx-arm64
  recipes/bioconductor-rbgl/meta.yaml
Labels: please review & merge

#53735 Updating bioconductor-multtest for osx-arm64
  recipes/bioconductor-multtest/meta.yaml
Labels: please review & merge

#53733 Updating bioconductor-msnbase for osx-arm64
  recipes/bioconductor-msnbase/meta.yaml
Labels: please review & merge

#53723 Add linux-aarch64 to bioconductor-globalancova
  recipes/bioconductor-globalancova/meta.yaml
Labels: please review & merge, aarch64

#53738 Update ncbi-amrfinderplus to version 4.0.19
  recipes/ncbi-amrfinderplus/meta.yaml
Labels: please review & merge, new version

#53739 Updating bioconductor-camera to build on osx-arm64
  recipes/bioconductor-camera/meta.yaml
Labels: please review & merge

#53737 Updating bioconductor-fgsea for osx-arm64
  recipes/bioconductor-fgsea/meta.yaml
Labels: please review & merge

#53742 Add adas v0.1.2
  recipes/adas/build.sh
  recipes/adas/meta.yaml
Labels: please review & merge

#53758 Update annembed v0.1.9
  recipes/annembed/meta.yaml
Labels: please review & merge

#53772 [Update] Metabuli v1.1.0
  recipes/metabuli/meta.yaml
Labels: please review & merge

#53785 maf2synteny: add arm64/aarch64 builds
  recipes/maf2synteny/Makefile.patch
  recipes/maf2synteny/build.sh
  recipes/maf2synteny/meta.yaml
Labels: aarch64, osx-arm64

#53784 Update fast2q to 2.7.4
  recipes/fast2q/meta.yaml
Labels: please review & merge

#53795 raven-assembler: add osx-arm64 build
  recipes/raven-assembler/build.sh
  recipes/raven-assembler/meta.yaml
Labels: osx-arm64

#53801 update unicore to 1.1.0
  recipes/unicore/build.sh
  recipes/unicore/meta.yaml
Labels: please review & merge

#53807 piler-cr: add linux-aarch64
  recipes/piler-cr/build.sh
  recipes/piler-cr/meta.yaml
Labels: please review & merge

#53806 Tbl2asn-forever: add aarch64
  recipes/tbl2asn-forever/gettimeofday_proto.patch
  recipes/tbl2asn-forever/meta.yaml
  recipes/tbl2asn-forever/test_makefile.patch
Labels: please review & merge

#53707 r-crbhits & dagchainer & bioconductor-msa2dist & kakscalculator2: add linux-aarch64 build
  recipes/bioconductor-msa2dist/meta.yaml
  recipes/dagchainer/build.sh
  recipes/dagchainer/meta.yaml
  recipes/kakscalculator2/build.sh
  recipes/kakscalculator2/meta.yaml
  recipes/r-crbhits/build_failure.linux-64.yaml
  recipes/r-crbhits/build_failure.osx-64.yaml
  recipes/r-crbhits/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53708 mashtree & quicktree & perl-aceperl: add aarch64 build
  recipes/mashtree/meta.yaml
  recipes/perl-aceperl/meta.yaml
  recipes/quicktree/build.sh
  recipes/quicktree/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53821 quicktree: add arm64 build
  recipes/quicktree/build.sh
  recipes/quicktree/meta.yaml
  recipes/quicktree/patches/0001-Add-rule-to-build-shared-library.patch
Labels: osx-arm64

#53834 prinseq-plus-plus: add linux-aarch64
  recipes/prinseq-plus-plus/meta.yaml
Labels: please review & merge

#53835 rhocall: add linux-aarch64
  recipes/rhocall/meta.yaml
Labels: please review & merge

#53824 pullseq: add linux-aarch64
  recipes/pullseq/build.sh
  recipes/pullseq/conda_build_config.yaml
  recipes/pullseq/implicit.patch
  recipes/pullseq/meta.yaml
Labels: please review & merge

#53846 hmmer2: add linux-aarch64
  recipes/hmmer2/build.sh
  recipes/hmmer2/meta.yaml
Labels: please review & merge

#53749 added a recipe for `wakhan`
  recipes/wakhan/meta.yaml
Labels: please review & merge

#53855 randfold: add linux-aarch64
  recipes/randfold/meta.yaml
Labels: please review & merge

#53845 Revert "t-coffee: add linux-aarch64 and build from source"
  recipes/t-coffee/build.sh
  recipes/t-coffee/coredump.patch
  recipes/t-coffee/meta.yaml
Labels: please review & merge

#53857 Add tagbam 0.1.0
  recipes/tagbam/build.sh
  recipes/tagbam/meta.yaml
Labels: please review & merge

#53867 t-coffee: add versions of dependencies and revert the removal of arm64 support
  recipes/t-coffee/build.sh
  recipes/t-coffee/coredump.patch
  recipes/t-coffee/meta.yaml
  recipes/t-coffee/t_coffee.sh
Labels: please review & merge

#53822 r-metacoder: add aarch64/arm64 builds
  recipes/r-metacoder/meta.yaml
Labels: aarch64, osx-arm64

#53885 Update seismic-rna to v0.23.1
  recipes/seismic-rna/meta.yaml
Labels: please review & merge

#53868 chopper: add aarch64, update to v0.9.1
  recipes/chopper/conda_build_config.yaml
  recipes/chopper/meta.yaml
Labels: please review & merge

#53808 Update SvABA
  recipes/svaba/build.sh
  recipes/svaba/build_failure.linux-64.yaml
  recipes/svaba/meta.yaml
Labels: please review & merge

#53894 Update HiTaC dependencies
  recipes/hitac/meta.yaml
Labels: please review & merge

#53840 pbsim3: add aarch64/arm64 builds
  recipes/pbsim3/build.sh
  recipes/pbsim3/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53897 Add fastoma recipe
  recipes/fastoma/meta.yaml
Labels: please review & merge

#53906 Update seg-suite
  recipes/seg-suite/build.sh
  recipes/seg-suite/meta.yaml
Labels: please review & merge

#53909 Fix geNomad requirements
  recipes/genomad/meta.yaml
Labels: please review & merge

#53913 neffy: add aarch64/arm64 builds
  recipes/neffy/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53912 svaba: add aarch64/arm64 builds
  recipes/svaba/build.sh
  recipes/svaba/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#53911 Add s4pred
  recipes/s4pred/build.sh
  recipes/s4pred/meta.yaml
Labels: please review & merge

#53905 Add metafx recipe
  recipes/metafx/build.sh
  recipes/metafx/meta.yaml
Labels: please review & merge

#53928 Rebuild fastahack
  recipes/fastahack/0001-Makefile.patch
  recipes/fastahack/build.sh
  recipes/fastahack/meta.yaml
Labels: aarch64, osx-arm64

#53930 feat: add recipe for genin2
  recipes/genin2/meta.yaml
Labels: please review & merge

#53914 Add met4j
  recipes/met4j/build.sh
  recipes/met4j/met4j.sh
  recipes/met4j/meta.yaml
Labels: please review & merge

#53931 Add recipe for mutalyzer_hgvs_parser
  recipes/mutalyzer_hgvs_parser/meta.yaml
Labels: please review & merge

#53938 Update hmftools-chord to 2.1.0
  recipes/hmftools-chord/meta.yaml
Labels: please review & merge

#53939 Update hmftools-linx to 2.0
  recipes/hmftools-linx/meta.yaml
Labels: please review & merge

#53934 Update hmftools-esvee to 1.0
  recipes/hmftools-esvee/meta.yaml
Labels: please review & merge

#53951 GW v1.1.4
  recipes/gw/meta.yaml
Labels: please review & merge

#53927 Add recipe for SeqLib v1.2.0
  recipes/seqlib/build.sh
  recipes/seqlib/bwa-Makefile.patch
  recipes/seqlib/fermi-Makefile.patch
  recipes/seqlib/meta.yaml
Labels: aarch64, osx-arm64

#53932 Rebuild CONSENT
  recipes/consent/0001-waterman-lib-Makefile.patch
  recipes/consent/0002-makefile.patch
  recipes/consent/0003-Makefile.patch
  recipes/consent/build.sh
  recipes/consent/conda_build_config.yaml
  recipes/consent/meta.yaml
  recipes/consent/sse2neon.h
Labels: aarch64, osx-arm64

#53966 genmap: add arm64/aarch64 builds
  recipes/genmap/build.sh
  recipes/genmap/build_failure.linux-64.yaml
  recipes/genmap/build_failure.osx-64.yaml
  recipes/genmap/meta.yaml
Labels: aarch64, osx-arm64

#53968 Update hmftools-cuppa to 2.3.1
  recipes/hmftools-cuppa/meta.yaml
Labels: please review & merge

#52546 quast: add linux-aarch64 build
  recipes/quast/build.sh
  recipes/quast/meta.yaml
Labels: please review & merge, aarch64

#53973 Update libssw to 1.2.5
  recipes/libssw/build.sh
  recipes/libssw/meta.yaml
  recipes/libssw/waterman-lib.patch
Labels: aarch64, osx-arm64

#53952 Add vcfexpress
  recipes/vcfexpress/build.sh
  recipes/vcfexpress/meta.yaml
Labels: please review & merge

#53969 Add samtools dependency to hmftools-redux
  recipes/hmftools-redux/meta.yaml
Labels: please review & merge

#53960 Update autobigs engine to 0.12.0
  recipes/autobigs-engine/meta.yaml
Labels: please review & merge

#53937 Add mlstdb package
  recipes/mlstdb/meta.yaml
Labels: please review & merge

#53974 perl-template-toolkit: Do not build for osx-arm64
  recipes/perl-template-toolkit/meta.yaml
  scripts/check-for-additional-platforms.sh
Labels: please review & merge

#53980 Rebuild shapeit5
  recipes/shapeit5/arm64.patch
  recipes/shapeit5/build.sh
  recipes/shapeit5/build_failure.linux-64.yaml
  recipes/shapeit5/meta.yaml
  recipes/shapeit5/sse2neon.h
Labels: MacOS related

#53948 Update hmftools orange
  recipes/hmftools-orange/meta.yaml
Labels: please review & merge

#53991 Update bioconductor-bambu to 3.8.3
  recipes/bioconductor-bambu/meta.yaml
Labels: please review & merge

#53996 Update python pinned version for scarap
  recipes/scarap/meta.yaml
Labels: please review & merge

#53995 Add `micomplete`
  recipes/micomplete/meta.yaml
Labels: please review & merge

#53986 Update autobigs-cli to 0.5.0
  recipes/autobigs-cli/meta.yaml
Labels: please review & merge

#54009 Update hmftools-neo to 1.2
  recipes/hmftools-neo/meta.yaml
Labels: please review & merge

#53987 Update gapseq
  recipes/gapseq/build.sh
  recipes/gapseq/meta.yaml
Labels: please review & merge

#54001 Add bioconda recipe for ensembl-py
  recipes/ensembl-py/meta.yaml
Labels: please review & merge

#54022 Update grz-cli to 0.1.4
  recipes/grz-cli/meta.yaml
Labels: please review & merge

#54000 Add bioconda recipe for ensembl-genomio
  recipes/ensembl-genomio/meta.yaml
Labels: please review & merge

#54017 Re-upload plink
  recipes/plink/build.sh
  recipes/plink/meta.yaml
Labels: please review & merge

#54019 pigpen: add aarch64/arm64 builds
  recipes/pigpen/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#54012 Update Mumemto to 1.2.0
  recipes/mumemto/build.sh
  recipes/mumemto/meta.yaml
Labels: please review & merge

#54040 Update seismic-rna to 0.24.0
  recipes/seismic-rna/meta.yaml
Labels: please review & merge

#54025 Update PanTools to version v4.3.3
  recipes/pantools/meta.yaml
Labels: please review & merge

#54045 Add atol-bpa-datamapper
  recipes/atol-bpa-datamapper/meta.yaml
Labels: please review & merge

#54056 s4pred build version bump to retry creating container
  recipes/s4pred/meta.yaml
Labels: please review & merge

#54039 Add rnalyze recipe
  recipes/rnalyze/meta.yaml
Labels: please review & merge

#54055 Add Cleanifier
  recipes/cleanifier/meta.yaml
Labels: please review & merge

#53384 ci: optimize fetch-depth in github actions
  .github/workflows/PR.yml
  .github/workflows/build-failures.yml
  .github/workflows/master.yml
  .github/workflows/nightly.yml
Labels: please review & merge

#54063 perl-sereal-decoder: add linux-aarch64
  build-fail-blacklist
  recipes/perl-sereal-decoder/meta.yaml
Labels: please review & merge

#54067 bump radiantkit and wakhan build number
  recipes/radiantkit/meta.yaml
  recipes/wakhan/meta.yaml
Labels: please review & merge

#47228 gridss: add linux-aarch64 build
  recipes/gridss/meta.yaml
Labels: please review & merge, aarch64

#54072 ont_vbz_hdf_plugin: update to 1.0.12, add linux-aarch64, resolve x86 build fails
  recipes/ont_vbz_hdf_plugin/conda_build_config.yaml
  recipes/ont_vbz_hdf_plugin/meta.yaml
Labels: please review & merge

#54083 Fix star-fusion: rename use of perl-io-gzip to perl-perlio-gzip
  recipes/star-fusion/meta.yaml
Labels: please review & merge

#54085 Trinity: add linux-aarch64 support
  recipes/trinity/cflags-remove-m64.patch
  recipes/trinity/meta.yaml
Labels: please review & merge

#54087 Update lsabgc build
  recipes/lsabgc/meta.yaml
Labels: please review & merge

#54091 Update lsabgc
  recipes/lsabgc/meta.yaml
Labels: please review & merge

#54110 update gempipe to v1.37.7
  recipes/gempipe/meta.yaml
Labels: please review & merge

#54112 kmcp: add linux-aarch64, osx-arm64 binaries
  recipes/kmcp/meta.yaml
Labels: please review & merge

#54107 yara: build from source, bump to version 1.0.3 and add linux-aarch64
  recipes/yara/build.sh
  recipes/yara/meta.yaml
Labels: please review & merge

#54119 hic-straw: add arm64/aarch64 builds
  recipes/hic-straw/meta.yaml
Labels: aarch64, osx-arm64

#54115 bandage: add linux-aarch64
  build-fail-blacklist
  recipes/bandage/meta.yaml
Labels: please review & merge

#54066 Update pairtools to v1.1.3
  recipes/pairtools/build.sh
  recipes/pairtools/meta.yaml
Labels: osx-arm64

#54092 salmon: add arm64 build
  recipes/salmon/0001-CMakeLists.patch
  recipes/salmon/build.sh
  recipes/salmon/config.guess
  recipes/salmon/config.sub
  recipes/salmon/meta.yaml
Labels: osx-arm64

#54103 Add ctc-scite
  recipes/ctc-scite/build.sh
  recipes/ctc-scite/meta.yaml
Labels: please review & merge

#54020 Add metator
  recipes/metator/meta.yaml
Labels: please review & merge

#54130 metaMDBG: add osx builds
  recipes/metamdbg/0001-CMakeLists.patch
  recipes/metamdbg/ContigPolisher.hpp
  recipes/metamdbg/build.sh
  recipes/metamdbg/meta.yaml
Labels: MacOS related, osx-arm64

#54100 Add setuptools and core utils to dependencies of kgwasflow
  recipes/kgwasflow/meta.yaml
Labels: please review & merge

#54133 oligoarrayaux: restore package, add linux-aarch64
  build-fail-blacklist
  recipes/oligoarrayaux/meta.yaml
Labels: please review & merge

#54132 update ppanggolin for osx-arm64
  recipes/ppanggolin/meta.yaml
Labels: please review & merge

#54116 fastobo: moved to conda-forge
  recipes/fastobo/build.sh
  recipes/fastobo/meta.yaml
Labels: please review & merge

#54136 Update NORDic to 2.6.0
  recipes/nordic/LICENSE
  recipes/nordic/build.sh
  recipes/nordic/meta.yaml
Labels: please review & merge

#54118 update build failure for bioconductor-lpsymphony
  recipes/bioconductor-lpsymphony/build_failure.osx-64.yaml
Labels: please review & merge

#54145 Update autobigs engine to 0.13.0
  recipes/autobigs-engine/meta.yaml
Labels: please review & merge

#54129 sambamba: add arm64 build
  recipes/sambamba/0001-fix-osx-compile.patch
  recipes/sambamba/0002-Makefile.macos.patch
  recipes/sambamba/build.sh
  recipes/sambamba/meta.yaml
Labels: osx-arm64

#54144 megan: update to 6.25.10, add linux-aarch64
  recipes/megan/meta.yaml
Labels: please review & merge

#54159 Update autobigs-cli bioconda to 0.6.0
  recipes/autobigs-cli/meta.yaml
Labels: please review & merge

#54134 bwa-mem2: fix build for aarch64 to pin to not use SVE
  recipes/bwa-mem2/build.sh
  recipes/bwa-mem2/meta.yaml
Labels: please review & merge

#54154 raptor: add linux-aarch64
  recipes/raptor/build.sh
  recipes/raptor/meta.yaml
Labels: please review & merge

#54146 Patch dragmap
  recipes/dragmap/boost.patch
  recipes/dragmap/meta.yaml
Labels: WIP

#54059 Update hictk to v2.0.2
  recipes/hictk/build.sh
  recipes/hictk/conanfile.Dockerfile.py.patch
  recipes/hictk/meta.yaml
  recipes/hictk/run_test.sh
Labels: please review & merge

#54178 ganon: add linux-aarch64
  recipes/ganon/meta.yaml
Labels: please review & merge

#54177 Add artex recipe
  recipes/artex/build.sh
  recipes/artex/meta.yaml
Labels: please review & merge

#54176 Update magneto
  recipes/magneto/meta.yaml
Labels: please review & merge

#54174 Update wBuild to 1.8.2
  recipes/wbuild/meta.yaml
Labels: please review & merge

#54106 Add mitorsaw recipe
  recipes/mitorsaw/build.sh
  recipes/mitorsaw/meta.yaml
Labels: please review & merge

#54071 Add new recipe: Mitosalt
  recipes/mitosalt/LICENSE.txt
  recipes/mitosalt/build.sh
  recipes/mitosalt/configs.patch
  recipes/mitosalt/download-mitosalt-db.sh
  recipes/mitosalt/meta.yaml
  recipes/mitosalt/perl_script.patch
  recipes/mitosalt/r_script.patch
  recipes/mitosalt/setup.patch
Labels: please review & merge
