Repository bioconda/bioconda-recipes, pull requests merged in 2025-08, with the labels that each got.

#58190 libsequence: add arm64 build
  recipes/libsequence/build.sh
  recipes/libsequence/build_failure.osx-64.yaml
  recipes/libsequence/meta.yaml
Labels: osx-arm64

#58191 megahit: add arm64 build
  recipes/megahit/0001-master.patch
  recipes/megahit/build.sh
  recipes/megahit/conda_build_config.yaml
  recipes/megahit/meta.yaml
Labels: MacOS related, osx-arm64

#58194 hapcut2: add aarch64/arm64 builds
  recipes/hapcut2/0001-master.patch
  recipes/hapcut2/0002-Makefile.patch
  recipes/hapcut2/build.sh
  recipes/hapcut2/meta.yaml
Labels: aarch64, osx-arm64

#58051 Add tgv
  recipes/tgv/build.sh
  recipes/tgv/meta.yaml
Labels: please review & merge

#58054 Add recipe for bioemu
  recipes/bioemu/meta.yaml
Labels: please review & merge

#57986 update geno2phenotb
  recipes/geno2phenotb/meta.yaml
Labels: please review & merge

#58201 update oligomap and enabled linux-aarch64
  recipes/oligomap/meta.yaml
Labels: aarch64, osx-arm64

#58208 Update ngs-bits to version 2025_07
  recipes/ngs-bits/meta.yaml
Labels: please review & merge

#58206 update ontime
  recipes/ontime/build.sh
  recipes/ontime/meta.yaml
Labels: aarch64, osx-arm64

#58207 update rtk
  recipes/rtk/build.sh
  recipes/rtk/meta.yaml
Labels: aarch64, osx-arm64

#58215 samtools v0.1.19: add arm64 build
  recipes/samtools/0.1.19/build.sh
  recipes/samtools/0.1.19/meta.yaml
Labels: MacOS related, osx-arm64

#58213 perl-bio-samtools: add arm64 build
  build-fail-blacklist
  recipes/grep/build_failure.linux-64.yaml
  recipes/grep/build_failure.osx-64.yaml
  recipes/logomaker/build_failure.linux-64.yaml
  recipes/logomaker/build_failure.osx-64.yaml
  recipes/perl-bio-samtools/build-pl.patch
  recipes/perl-bio-samtools/build.sh
  recipes/perl-bio-samtools/build_failure.osx-64.yaml
  recipes/perl-bio-samtools/meta.yaml
  recipes/piler-cr/build_failure.osx-64.yaml
Labels: osx-arm64

#58223 v3.1b Corrected build.sh
  recipes/egap/build.sh
  recipes/egap/meta.yaml
Labels: please review & merge

#58237 yacrd: add osx-arm64
  recipes/yacrd/meta.yaml
Labels: osx-arm64

#58234 unicycler: add osx-arm64
  recipes/unicycler/meta.yaml
Labels: osx-arm64

#58232 cooltools: add osx-arm64
  recipes/cooltools/meta.yaml
Labels: osx-arm64

#58235 slow5tools: add osx-arm64
  recipes/slow5tools/meta.yaml
Labels: osx-arm64

#58242 sickle-trim: add arm64 build
  recipes/sickle-trim/0001-master-sickle.patch
  recipes/sickle-trim/build.sh
  recipes/sickle-trim/meta.yaml
Labels: osx-arm64

#58258 rscape: add osx-arm64
  recipes/rscape/meta.yaml
Labels: please review & merge

#58249 Update scxmatch
  recipes/scxmatch/meta.yaml
Labels: please review & merge

#58256 Update mason to 2.0.12
  recipes/mason/build.sh
  recipes/mason/meta.yaml
Labels: please review & merge

#58244 update gocr and enabled linux-aarch64
  recipes/gocr/0.50/build.sh
  recipes/gocr/0.50/meta.yaml
Labels: please review & merge

#58246 update strawc and enabled linux-aarch64
  recipes/strawc/build.sh
  recipes/strawc/meta.yaml
Labels: aarch64, osx-arm64

#58269 libgenome: add aarch64/arm64 builds
  recipes/libgenome/build.sh
  recipes/libgenome/meta.yaml
Labels: aarch64, osx-arm64

#58272 Add agtools v0.1.0
  recipes/agtools/meta.yaml
Labels: please review & merge

#58092 Update bedops recipe for osx-arm64 installation
  recipes/bedops/0001-Makefile.patch
  recipes/bedops/0002-Makefile-darwin.patch
  recipes/bedops/build.sh
  recipes/bedops/build_failure.osx-64.yaml
  recipes/bedops/meta.yaml
Labels: help wanted, osx-arm64

#58273 Libmems update
  recipes/bioconductor-chromvar/build_failure.osx-64.yaml
  recipes/libmems/build.sh
  recipes/libmems/build_failure.linux-64.yaml
  recipes/libmems/meta.yaml
Labels: aarch64

#58274 Rebuild dinopy recipe
  recipes/dinopy/build.sh
  recipes/dinopy/build_failure.linux-64.yaml
  recipes/dinopy/build_failure.linux-aarch64.yaml
  recipes/dinopy/build_failure.osx-64.yaml
  recipes/dinopy/meta.yaml
Labels: osx-arm64

#58278 Update yara to 1.0.5
  recipes/yara/build.sh
  recipes/yara/meta.yaml
Labels: please review & merge

#58227 coot-headless: Remove post-link.sh
  recipes/coot-headless/build.sh
  recipes/coot-headless/meta.yaml
  recipes/coot-headless/post-link.sh
Labels: please review & merge

#58257 Add the kled recipe.
  recipes/kled/build.sh
  recipes/kled/meta.yaml
Labels: please review & merge

#58302 Rebuild dinamo recipe
  recipes/dinamo/Makefile.patch
  recipes/dinamo/build.sh
  recipes/dinamo/meta.yaml
Labels: MacOS related, osx-arm64

#58305 prosampler: add arm64 build
  recipes/prosampler/build.sh
  recipes/prosampler/meta.yaml
Labels: osx-arm64

#58338 Update structure-threader recipe to fix interpreter
  recipes/structure-threader/meta.yaml
Labels: please review & merge

#58373 Update graphembed v0.1.8
  recipes/graphembed/meta.yaml
Labels: please review & merge

#58372 Update remag to v0.1.5
  recipes/remag/meta.yaml
Labels: please review & merge

#58341 Update PhyClone to 0.7.1
  recipes/phyclone/meta.yaml
Labels: please review & merge

#58390 Update kled to v1.2.10.
  recipes/kled/build.sh
  recipes/kled/meta.yaml
Labels: please review & merge

#58401 Update dbcanlight to 1.1.1
  recipes/dbcanlight/meta.yaml
Labels: please review & merge

#58027 Add ProMod3 recipe
  recipes/promod3/build.sh
  recipes/promod3/meta.yaml
  recipes/promod3/run_test.sh
Labels: please review & merge

#58404 Add taxburst
  recipes/taxburst/meta.yaml
Labels: please review & merge

#58340 update karect and enabled linux-aarch64
  recipes/karect/meta.yaml
Labels: please review & merge

#58316 update sts-smctc and enabled linux-aarch64
  recipes/sts-smctc/meta.yaml
Labels: please review & merge

#58314 update ir and enabled linux-aarch64
  recipes/ir/meta.yaml
Labels: please review & merge

#58413 gimmemotifs: add aarch64/arm64 builds
  recipes/gimmemotifs/build_failure.linux-64.yaml
  recipes/gimmemotifs/build_failure.osx-64.yaml
  recipes/gimmemotifs/meta.yaml
  recipes/proteinortho/build_failure.osx-64.yaml
Labels: MacOS related, aarch64, osx-arm64

#58422 Add psipred v3.5
  recipes/psipred/build.sh
  recipes/psipred/meta.yaml
  recipes/psipred/run_test.sh
Labels: please review & merge

#58433 gvcf2coverage: add arm64 build
  recipes/gvcf2coverage/build.sh
  recipes/gvcf2coverage/meta.yaml
Labels: osx-arm64

#58382 update svmlight and enabled linux-aarch64
  recipes/svmlight/build.sh
  recipes/svmlight/meta.yaml
Labels: aarch64, osx-arm64

#58384 update lightassembler and enabled linux-aarch64
  recipes/lightassembler/meta.yaml
Labels: aarch64, osx-arm64

#58434 karect: add arm64 build
  recipes/karect/build.sh
  recipes/karect/meta.yaml
Labels: MacOS related, osx-arm64

#58128 update seqan-tcoffee and enabled linux-aarch64
  recipes/seqan_tcoffee/build.sh
  recipes/seqan_tcoffee/meta.yaml
Labels: aarch64

#58438 Update annembed v0.2.5
  recipes/annembed/meta.yaml
Labels: please review & merge

#58392 Update to OpenStructure 2.11.1
  recipes/openstructure/build.sh
  recipes/openstructure/meta.yaml
Labels: please review & merge

#58458 gustaf v1.0.10: add aarch64/arm64 builds
  recipes/gustaf/build.sh
  recipes/gustaf/meta.yaml
Labels: aarch64, osx-arm64

#58345 update kraken-ea and enabled linux-aarch64
  build-fail-blacklist
  recipes/kraken-ea/0001-install.sh.patch
  recipes/kraken-ea/build.sh
  recipes/kraken-ea/meta.yaml
Labels: aarch64

#58449 Update fgpyo by adding dependency python-zlib-ng
  recipes/fgpyo/meta.yaml
Labels: please review & merge

#57833 update methpipe
  recipes/methpipe/0001-sam_record_cstdint.patch
  recipes/methpipe/build.sh
  recipes/methpipe/meta.yaml
Labels: aarch64, osx-arm64

#58463 ligand-validation: Update recipe
  recipes/ligand-validation/build.sh
  recipes/ligand-validation/meta.yaml
Labels: please review & merge

#58473 add samtools as dependency
  recipes/pbsim3/meta.yaml
Labels: please review & merge

#58479 Add fstic
  recipes/fstic/meta.yaml
Labels: please review & merge

#58504 Update cuna 0.3.0 pin pyarrow
  recipes/cuna/meta.yaml
Labels: please review & merge

#58490 update livekraken and enabled linux-aarch64
  recipes/livekraken/meta.yaml
Labels: aarch64

#58527 Add seqforge 1.0.0
  recipes/seqforge/meta.yaml
Labels: please review & merge

#58491 update longgf and enabled linux-aarch64
  recipes/longgf/meta.yaml
Labels: aarch64, osx-arm64

#58489 update libstatgen and enabled linux-aarch64
  recipes/libstatgen/build.sh
  recipes/libstatgen/meta.yaml
Labels: aarch64, osx-arm64

#58500 update haproh and enabled linux-aarch64
  recipes/haproh/meta.yaml
Labels: aarch64, osx-arm64

#58556 Update augur to 31.4.0
  recipes/augur/meta.yaml
Labels: please review & merge

#58559 [auspice] version bump to 2.64.0
  recipes/auspice/meta.yaml
Labels: please review & merge

#58561 seqforge 1.0.4; Conda install bug fix; correct version
  recipes/seqforge/meta.yaml
Labels: please review & merge

#58570 perl-dbd-pg: add arm64 build
  recipes/perl-dbd-pg/build.sh
  recipes/perl-dbd-pg/meta.yaml
Labels: osx-arm64

#57997 perl-forks: add aarch64/arm64 builds
  recipes/perl-forks/build.sh
  recipes/perl-forks/meta.yaml
Labels: aarch64, osx-arm64

#58587 perl-bio-bigfile: add aarch64 build
  recipes/perl-bio-bigfile/build.sh
  recipes/perl-bio-bigfile/meta.yaml
Labels: aarch64

#57782 update mdasim
  recipes/mdasim/meta.yaml
Labels: aarch64

#58592 intarna: add arm64 build
  recipes/intarna/build.sh
  recipes/intarna/meta.yaml
Labels: osx-arm64

#58593 matam: add aarch64 build
  recipes/matam/build.sh
  recipes/matam/meta.yaml
Labels: aarch64

#58636 fastq-tools: add aarch64/arm64 builds
  recipes/fastq-tools/build.sh
  recipes/fastq-tools/build_failure.osx-64.yaml
  recipes/fastq-tools/meta.yaml
Labels: aarch64, osx-arm64

#58640 update unimap and enabled linux-aarch64
  recipes/unimap/build.sh
  recipes/unimap/meta.yaml
Labels: aarch64

#58638 update dragmap and enabled linux-aarch64
  recipes/dragmap/build.sh
  recipes/dragmap/meta.yaml
Labels: aarch64

#58566 update tgt and enabled linux-aarch64
  build-fail-blacklist
  recipes/tgt/meta.yaml
Labels: please review & merge

#58644 update pfp and enabled linux-aarch64
  recipes/pfp/meta.yaml
Labels: aarch64

#58637 Rebuild predictosaurus recipe
  .circleci/config.yml
  recipes/predictosaurus/meta.yaml
Labels: aarch64

#58646 update hesslab-gambit
  recipes/hesslab-gambit/meta.yaml
  recipes/hesslab-gambit/run_test.sh
Labels: aarch64, osx-arm64

#57791 update gargammel and enable to linux-aarch64
  recipes/gargammel/build.sh
  recipes/gargammel/build_failure.linux-64.yaml
  recipes/gargammel/build_failure.osx-64.yaml
  recipes/gargammel/meta.yaml
Labels: aarch64, osx-arm64

#58688 update ushuffle and enabled linux-aarch64
  recipes/ushuffle/meta.yaml
Labels: aarch64, osx-arm64

#58689 update hi-corrector and enabled linux-aarch64
  recipes/hi-corrector/build.sh
  recipes/hi-corrector/meta.yaml
Labels: aarch64, osx-arm64

#58721 Rebuild paml recipe
  recipes/paml/build.sh
  recipes/paml/meta.yaml
Labels: osx-arm64

#58684 perl-bio-db-hts: add arm64 build
  recipes/perl-bio-db-hts/build.sh
  recipes/perl-bio-db-hts/meta.yaml
Labels: osx-arm64

#58723 perl-bio-bigfile: add arm64 build
  recipes/perl-bio-bigfile/meta.yaml
Labels: osx-arm64

#58737 update hmnillumina and enabled linux-aarch64
  recipes/hmnillumina/meta.yaml
Labels: aarch64

#58729 add MaAsLin3
  recipes/maaslin3/build.sh
  recipes/maaslin3/meta.yaml
Labels: please review & merge

#58736 Rebuild btrim recipe
  recipes/btrim/0001-fix-push_back-initializer_list-and-abs-from-uint.patch
  recipes/btrim/build.sh
  recipes/btrim/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#58749 Update alfred v0.5.1
  recipes/alfred/build.sh
  recipes/alfred/meta.yaml
Labels: please review & merge

#58757 wally: add arm64 build
  recipes/wally/build.sh
  recipes/wally/meta.yaml
Labels: osx-arm64

#58761 macs2: add arm64 build
  recipes/macs2/conda_build_config.yaml
  recipes/macs2/meta.yaml
Labels: osx-arm64

#58759 Update bioconductor-chromvar to v1.30.1
  recipes/bioconductor-chromvar/build.sh
  recipes/bioconductor-chromvar/meta.yaml
Labels: osx-arm64

#58765 skesa: add arm64 build
  recipes/skesa/build.sh
  recipes/skesa/meta.yaml
Labels: osx-arm64

#58769 r-presto: add aarch64/arm64 builds
  recipes/r-presto/conda_build_config.yaml
  recipes/r-presto/meta.yaml
Labels: aarch64, osx-arm64

#58776 r-azimuth: add aarch64/arm64 builds and build on R 4.4
  recipes/r-azimuth/meta.yaml
  recipes/r-chromvarmotifs/conda_build_config.yaml
  recipes/r-presto/conda_build_config.yaml
Labels: aarch64, osx-arm64

#58845 Update artic 1.8.0 version metadata
  recipes/artic/meta.yaml
Labels: please review & merge

#58842 bump r-presto
  recipes/r-presto/meta.yaml
Labels: please review & merge

#58816 coot-headless: remove a unused dependency
  recipes/coot-headless/meta.yaml
Labels: please review & merge

#58853 Update sha256 and build number for Olivar 1.3.3
  recipes/olivar/meta.yaml
Labels: please review & merge

#58811 Update vContact3 3.1.4 to R1
  recipes/vcontact3/meta.yaml
Labels: please review & merge

#58781 update pin_hic and enabled linux-aarch64
  recipes/pin_hic/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#58779 update phcue-ck and enabled linux-aarch64
  recipes/phcue-ck/meta.yaml
Labels: aarch64, osx-arm64

#58879 Update sistem to version 1.0.4
  recipes/sistem/meta.yaml
Labels: please review & merge

#58663 Add epimetheus-py recipe
  recipes/epimetheus-py/meta.yaml
Labels: please review & merge

#58744 update seqmap and enabled linux-aarch64
  build-fail-blacklist
  recipes/seqmap/meta.yaml
Labels: aarch64, osx-arm64

#58884 bioconductor-motifmatchr: add arm64 build
  recipes/bioconductor-motifmatchr/build.sh
  recipes/bioconductor-motifmatchr/meta.yaml
Labels: osx-arm64

#58813 Update EGAP meta.yaml v3.2c
  recipes/egap/meta.yaml
Labels: please review & merge

#58745 update tssar and enabled linux-aarch64
  recipes/tssar/build.sh
  recipes/tssar/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#58662 update gtdbtk 2.0.0 and enabled linux-aarch64
  recipes/gtdbtk/2.0.0/build.sh
  recipes/gtdbtk/2.0.0/download-db.sh
  recipes/gtdbtk/2.0.0/meta.yaml
  recipes/gtdbtk/2.0.0/post-link.sh
Labels: please review & merge

#58660 update xunit-wrapper and enabled linux-aarch64
  recipes/xunit-wrapper/meta.yaml
Labels: please review & merge

#58859 Add fastmd5
  recipes/fastmd5/build.sh
  recipes/fastmd5/meta.yaml
Labels: please review & merge

#58834 update transrate-tools and enabled linux-aarch64
  recipes/transrate-tools/0001-CMakeLists.patch
  recipes/transrate-tools/build.sh
  recipes/transrate-tools/build_failure.linux-64.yaml
  recipes/transrate-tools/meta.yaml
Labels: aarch64, osx-arm64

#58687 update unitig-counter and enabled linux-aarch64
  build-fail-blacklist
  recipes/unitig-counter/build.sh
  recipes/unitig-counter/meta.yaml
Labels: aarch64

#58696 update r-histonehmm and enabled linux-aarch64
  recipes/r-histonehmm/build.sh
  recipes/r-histonehmm/build_failure.linux-64.yaml
  recipes/r-histonehmm/fix-dgemm-call.patch
  recipes/r-histonehmm/meta.yaml
  recipes/r-histonehmm/patch
Labels: aarch64, osx-arm64

#58897 abawaca: add arm64 build
  recipes/abawaca/0001-Use-CXX-and-flags.patch
  recipes/abawaca/build.sh
  recipes/abawaca/meta.yaml
Labels: osx-arm64
