Repository bioconda/bioconda-recipes, pull requests merged in 2025-06, with the labels that each got.

#55976 Add r-cnaqc
  conda_build_config.yaml
  recipes/r-cnaqc/build.sh
  recipes/r-cnaqc/meta.yaml
  recipes/r-peakpick/build.sh
  recipes/r-peakpick/meta.yaml
Labels: please review & merge

#56570 mmcif: Update URLs
  recipes/mmcif/meta.yaml
Labels: please review & merge

#56566 Update ToolDistillator from 0.9.2 to 0.9.3
  recipes/tooldistillator/meta.yaml
Labels: please review & merge

#56506 Update vcontact3
  recipes/vcontact3/meta.yaml
Labels: please review & merge

#56539 pdbx: enable python build matrix
  recipes/pdbx/conda_build_config.yaml
  recipes/pdbx/meta.yaml
Labels: please review & merge

#56544 Add recipe for DupHIST v1.0.0
  recipes/duphist/meta.yaml
  recipes/duphist/v1.0.0.tar.gz
Labels: please review & merge

#56588 Bump bioconda-repodata-patches for new htslib release
  recipes/bioconda-repodata-patches/gen_patch_json.py
  recipes/bioconda-repodata-patches/meta.yaml
Labels: please review & merge

#56535 Add longtrack 1.0.0 recipe
  recipes/longtrack/meta.yaml
Labels: please review & merge

#56580 Add r-tinc recipe
  recipes/r-tinc/build.sh
  recipes/r-tinc/meta.yaml
Labels: please review & merge

#56589 Add `uniprot-id-mapper`
  recipes/uniprot-id-mapper/meta.yaml
Labels: please review & merge

#56614 Update bcftools-liftover-plugin
  recipes/bcftools-liftover-plugin/conda_build_config.yaml
  recipes/bcftools-liftover-plugin/meta.yaml
Labels: please review & merge

#56655 Update pasta to change build.sh and 1.9.3
  recipes/pasta/build.sh
  recipes/pasta/meta.yaml
Labels: please review & merge

#56641 Update nbitk to 0.5.9
  recipes/nbitk/meta.yaml
Labels: please review & merge

#56643 Add phynteny_transformer v0.1.2
  recipes/phynteny_transformer/meta.yaml
Labels: please review & merge

#56660 Fix dependencies for augur to include referencing like the pip pkg
  recipes/augur/meta.yaml
Labels: please review & merge

#56662 moabs: add aarch64/arm64 builds
  recipes/moabs/0001-moab.patch
  recipes/moabs/build.sh
  recipes/moabs/build_failure.linux-64.yaml
  recipes/moabs/build_failure.osx-64.yaml
  recipes/moabs/meta.yaml
  recipes/moabs/post-link.sh
Labels: aarch64, osx-arm64

#56642 Add hmftools-bwa-plus
  recipes/hmftools-bwa-plus/build.sh
  recipes/hmftools-bwa-plus/meta.yaml
Labels: please review & merge

#56667 Update Phylogenize to v2.0-alpha
  recipes/phylogenize/build.sh
  recipes/phylogenize/meta.yaml
Labels: please review & merge

#56324 Add: flexidot
  recipes/flexidot/meta.yaml
Labels: help wanted, please review & merge

#56672 gfatools: add aarch64/arm64 builds
  recipes/gfatools/0001-Makefile.patch
  recipes/gfatools/0002-asm.c.patch
  recipes/gfatools/build.sh
  recipes/gfatools/meta.yaml
Labels: aarch64, osx-arm64

#55483 fix: emboss on osx-arm64
  recipes/emboss/build.sh
  recipes/emboss/meta.yaml
Labels: help wanted

#56640 OpenStructure: Update OpenGL/OpenCL deps and post-link script
  recipes/openstructure/meta.yaml
  recipes/openstructure/post-link.sh
Labels: please review & merge

#56661 Bump/marbel
  recipes/marbel/meta.yaml
Labels: please review & merge

#56671 Rebuild aliceasm recipe
  recipes/aliceasm/LICENSE
  recipes/aliceasm/build.sh
  recipes/aliceasm/meta.yaml
Labels: aarch64, osx-arm64

#56693 Add barcodeforge recipe
  recipes/barcodeforge/meta.yaml
Labels: please review & merge

#56691 r-bpcells: add osx build
  recipes/r-bpcells/build.sh
  recipes/r-bpcells/meta.yaml
  recipes/r-bpcells/patches/0001-fix-libhwy-config.patch
Labels: MacOS related, aarch64, osx-arm64

#56710 Update polap recipe to v0.4.3.7.6
  recipes/polap/build.sh
  recipes/polap/meta.yaml
Labels: please review & merge

#56706 Add BeEM
  recipes/beem-bio/build.sh
  recipes/beem-bio/meta.yaml
Labels: please review & merge

#56700 Update `r-quilt` to 2.0.2
  recipes/r-mspbwt/LICENSE
  recipes/r-mspbwt/build.sh
  recipes/r-mspbwt/meta.yaml
  recipes/r-quilt/build.sh
  recipes/r-quilt/build_failure.osx-64.yaml
  recipes/r-quilt/meta.yaml
Labels: please review & merge

#56717 Update pyvcf3 to v1.0.4
  recipes/pyvcf3/meta.yaml
Labels: aarch64, osx-arm64

#56728 Update PhaBOX's meta.yaml to solve a "ValueError" caused by the update of PyTorch
  recipes/phabox/meta.yaml
Labels: please review & merge

#56729 Update polap recipe to v0.4.3.7.6 build1
  recipes/polap/build.sh
  recipes/polap/meta.yaml
Labels: please review & merge

#56720 update r-cimpl
  recipes/r-cimpl/build.sh
  recipes/r-cimpl/meta.yaml
Labels: please review & merge

#56737 Rebuild tagger recipe
  build-fail-blacklist
  recipes/tagger/0001-makefile.patch
  recipes/tagger/0002-tagger.patch
  recipes/tagger/build.sh
  recipes/tagger/meta.yaml
Labels: aarch64

#56734 Update polap recipe to v0.4.3.7.7
  recipes/polap/build.sh
  recipes/polap/meta.yaml
Labels: please review & merge

#56768 Update polap recipe to v0.4.3.7.8
  recipes/polap/meta.yaml
Labels: please review & merge

#56767 Update vcontact3 to 3.0.5
  recipes/vcontact3/meta.yaml
Labels: please review & merge

#56772 update r-htssip
  recipes/r-htssip/meta.yaml
Labels: please review & merge

#56787 update plannotate to 1.2.4
  recipes/plannotate/meta.yaml
Labels: please review & merge

#56802 Update EarlGrey meta.yaml
  recipes/earlgrey/meta.yaml
Labels: please review & merge

#56807 Update MBG to version 1.0.17
  recipes/mbg/mbg-aarch64.patch
  recipes/mbg/meta.yaml
  recipes/mbg/osx_availability.patch
Labels: please review & merge

#56795 update r-ic10
  recipes/r-ic10/meta.yaml
Labels: please review & merge

#56793 Update rascaf and enabled aarch64
  recipes/rascaf/build.sh
  recipes/rascaf/meta.yaml
Labels: please review & merge

#56829 Rebuild perl-devel-checklib recipe
  build-fail-blacklist
  recipes/perl-devel-checklib/build.sh
  recipes/perl-devel-checklib/meta.yaml
Labels: aarch64, osx-arm64

#56863 Update panacus to v0.4.0
  recipes/panacus/meta.yaml
Labels: please review & merge

#56865 Update CroCoDeEL to 1.0.7
  recipes/crocodeel/meta.yaml
Labels: please review & merge

#56877 Update galaxy-data to add rocrate dep now that it exists in conda-forge
  recipes/galaxy-data/meta.yaml
Labels: please review & merge

#56876 Update Mimick to 2.1 and recipe
  recipes/mimick/meta.yaml
Labels: please review & merge

#56861 Add cram-archiver
  recipes/cram-archiver/meta.yaml
Labels: please review & merge

#56848 Update rcorrector and enabled aarch64
  recipes/rcorrector/build.sh
  recipes/rcorrector/meta.yaml
Labels: aarch64, osx-arm64

#56746 Add eDentity v1.4.4
  recipes/edentity/meta.yaml
Labels: please review & merge

#56930 Update barcodeforge to version 1.1.1 and update source SHA256
  recipes/barcodeforge/meta.yaml
Labels: please review & merge

#56925 version 1.0.1 of mi-pimento, with updated cli_path
  recipes/mi-pimento/meta.yaml
Labels: please review & merge

#56902 Update Flexiplex to v1.02.3
  recipes/flexiplex/meta.yaml
Labels: please review & merge

#56900 Update PhaBOX to a fixed Transformer package version
  recipes/phabox/meta.yaml
Labels: please review & merge

#56927 Update learnmsa to 2.0.11
  recipes/learnmsa/meta.yaml
Labels: please review & merge

#56957 mgnify-pipelines-toolkit v1.2.1
  recipes/mgnify-pipelines-toolkit/meta.yaml
Labels: please review & merge

#56954 Update DupHIST to v1.0.3 with complete dependency specification
  recipes/duphist/meta.yaml
Labels: please review & merge

#56956 Update reffinder enabled aarch64
  recipes/reffinder/build.sh
  recipes/reffinder/meta.yaml
Labels: please review & merge, aarch64, osx-arm64

#56744 Add mmdb2 v2.0.22
  recipes/mmdb2/build.sh
  recipes/mmdb2/meta.yaml
Labels: please review & merge

#56908 Add isodesign v2.0.1
  recipes/isodesign/meta.yaml
Labels: please review & merge

#56866 Add r-flanders
  recipes/r-flanders/meta.yaml
Labels: please review & merge

#56854 update perl-ipc-cmd
  recipes/perl-ipc-cmd/meta.yaml
Labels: please review & merge

#56269 Add MavericK v1.0.5
  recipes/maverick/meta.yaml
  recipes/maverick/run_test.sh
Labels: please review & merge

#56968 update Gustaf to v1.0.10
  recipes/gustaf/build.sh
  recipes/gustaf/meta.yaml
Labels: please review & merge

#56966 update Sak
  recipes/sak/build.sh
  recipes/sak/meta.yaml
Labels: please review & merge

#56924 Accusnv - High-accuracy SNV calling for bacterial isolates using AccuSNV
  recipes/accusnv/meta.yaml
Labels: please review & merge

#56755 Add varlinker version 1.1.0
  recipes/varlinker/build.sh
  recipes/varlinker/meta.yaml
Labels: please review & merge

#56668 Add rtg-core package
  recipes/rtg-core/build.sh
  recipes/rtg-core/meta.yaml
Labels: please review & merge

#56923 Add CoreProfiler recipe
  recipes/coreprofiler/meta.yaml
Labels: please review & merge

#57017 Update edentity to 1.4.5
  recipes/edentity/meta.yaml
Labels: please review & merge

#56959 update r-isogene
  recipes/r-isogene/build.sh
  recipes/r-isogene/meta.yaml
Labels: please review & merge

#57030 easel: add arm64 build
  recipes/easel/build.sh
  recipes/easel/meta.yaml
Labels: osx-arm64

#56915 update cvlr and enabled linux-aarch64
  recipes/cvlr/build.sh
  recipes/cvlr/meta.yaml
Labels: please review & merge, aarch64

#57056 libccp4: Add DOI identifier
  recipes/libccp4/meta.yaml
Labels: please review & merge

#57053 trinity: add arm64 build
  recipes/trinity/build.sh
  recipes/trinity/meta.yaml
Labels: osx-arm64

#57072 Update ucsc-twobittofa to v482
  recipes/ucsc-twobittofa/build.sh
  recipes/ucsc-twobittofa/include.linux.patch
  recipes/ucsc-twobittofa/include.macos.patch
  recipes/ucsc-twobittofa/include.patch
  recipes/ucsc-twobittofa/meta.yaml
Labels: osx-arm64

#57074 Update ucsc-twobitinfo to v482
  recipes/ucsc-twobitinfo/build.sh
  recipes/ucsc-twobitinfo/meta.yaml
Labels: osx-arm64

#57091 Update PCNE v1.0.0
  recipes/pcne/build.sh
  recipes/pcne/meta.yaml
Labels: please review & merge

#57120 Update: samtools dependency
  recipes/agat/meta.yaml
Labels: please review & merge

#57097 Add hmftools-gene-utils
  recipes/hmftools-gene-utils/build.sh
  recipes/hmftools-gene-utils/gene-utils.sh
  recipes/hmftools-gene-utils/meta.yaml
Labels: please review & merge

#56940 Update hictk to 2.1.4
  recipes/hictk/build.sh
  recipes/hictk/conanfile.Dockerfile.py.patch
  recipes/hictk/conanfile.py.patch
  recipes/hictk/conda_build_config.yaml
  recipes/hictk/meta.yaml
Labels: please review & merge

#57124 Update bioconductor-geometadb to 1.68.1
  recipes/bioconductor-geometadb/meta.yaml
Labels: please review & merge

#57141 ucsc-stringify: ucsc-stringify to v482
  recipes/ucsc-stringify/build.sh
  recipes/ucsc-stringify/meta.yaml
Labels: osx-arm64

#57051 Update ucsc-liftover to v482
  recipes/ucsc-liftover/0001-include.patch
  recipes/ucsc-liftover/0002-include.linux.patch
  recipes/ucsc-liftover/0003-common.mk.patch
  recipes/ucsc-liftover/0004-straw.patch
  recipes/ucsc-liftover/build.sh
  recipes/ucsc-liftover/htmshell.patch
  recipes/ucsc-liftover/include.patch
  recipes/ucsc-liftover/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#55658 Update ucsc-bedtogenepred to v482
  recipes/ucsc-bedtogenepred/0001-include.patch
  recipes/ucsc-bedtogenepred/0002-include.linux.patch
  recipes/ucsc-bedtogenepred/0003-common.mk.patch
  recipes/ucsc-bedtogenepred/0004-straw.patch
  recipes/ucsc-bedtogenepred/build.sh
  recipes/ucsc-bedtogenepred/include.patch
  recipes/ucsc-bedtogenepred/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#57152 Update sourmash metadata: authors & papers
  recipes/sourmash/meta.yaml
Labels: please review & merge

#57143 Update ucsc-gtftogenepred to v482
  recipes/ucsc-gtftogenepred/0001-include.patch
  recipes/ucsc-gtftogenepred/0002-include.linux.patch
  recipes/ucsc-gtftogenepred/0003-common.mk.patch
  recipes/ucsc-gtftogenepred/0004-straw.patch
  recipes/ucsc-gtftogenepred/build.sh
  recipes/ucsc-gtftogenepred/htmshell.patch
  recipes/ucsc-gtftogenepred/include.patch
  recipes/ucsc-gtftogenepred/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#57157 Update bioconductor-scmet recipe - additional platforms
  recipes/bioconductor-scmet/meta.yaml
Labels: please review & merge

#57173 Add recipe for bifrost-httr 0.1.0
  recipes/bifrost-httr/LICENSE
  recipes/bifrost-httr/meta.yaml
Labels: please review & merge

#57096 Adding clipper v2.1.20180802
  recipes/clipper/build.sh
  recipes/clipper/clipper-configure-2.patch
  recipes/clipper/meta.yaml
Labels: please review & merge

#57136 ➕ new recipe for 🧬 'dnadotplot'
  recipes/dnadotplot/meta.yaml
Labels: please review & merge

#57160 update kcounter
  recipes/kcounter/build.sh
  recipes/kcounter/meta.yaml
Labels: please review & merge

#57105 Update riblast enabled linux-aarch64
  recipes/riblast/build.sh
  recipes/riblast/meta.yaml
Labels: please review & merge

#57080 update dailign2 and enabled linux-arrch64
  recipes/dialign2/meta.yaml
  recipes/dialign2/patches/makefile.patch
Labels: please review & merge

#57183 Rebuild ssm for linux-64
  recipes/ssm/meta.yaml
Labels: please review & merge

#57243 Update Harpy build
  recipes/harpy/meta.yaml
Labels: please review & merge

#57216 Add pybascule recipe
  recipes/pybascule/meta.yaml
Labels: please review & merge

#57015 Adding r-bascule
  recipes/r-bascule/build.sh
  recipes/r-bascule/meta.yaml
Labels: please review & merge

#57244 eklipse: migrate from python2 to python3
  recipes/eklipse/build.sh
  recipes/eklipse/meta.yaml
  recipes/eklipse/py2to3.patch
  recipes/eklipse/py310.patch
  recipes/eklipse/syntax.patch
Labels: please review & merge

#57236 Update poseidon-trident to 1.6.7.1
  recipes/poseidon-trident/meta.yaml
Labels: please review & merge

#57252 Update ucsc-bigwigtowig to v482
  recipes/ucsc-bigwigtowig/0001-include.patch
  recipes/ucsc-bigwigtowig/0002-include.linux.patch
  recipes/ucsc-bigwigtowig/0003-common.mk.patch
  recipes/ucsc-bigwigtowig/0004-straw.patch
  recipes/ucsc-bigwigtowig/build.sh
  recipes/ucsc-bigwigtowig/htmshell.patch
  recipes/ucsc-bigwigtowig/include.patch
  recipes/ucsc-bigwigtowig/meta.yaml
Labels: osx-arm64

#57253 Update ucsc-nibfrag to v482
  recipes/ucsc-nibfrag/0001-include.patch
  recipes/ucsc-nibfrag/0002-include.linux.patch
  recipes/ucsc-nibfrag/0003-common.mk.patch
  recipes/ucsc-nibfrag/0004-straw.patch
  recipes/ucsc-nibfrag/build.sh
  recipes/ucsc-nibfrag/include.patch
  recipes/ucsc-nibfrag/meta.yaml
Labels: osx-arm64

#57255 Update ucsc-gff3togenepred to v482
  recipes/ucsc-gff3togenepred/0001-include.patch
  recipes/ucsc-gff3togenepred/0002-include.linux.patch
  recipes/ucsc-gff3togenepred/0003-common.mk.patch
  recipes/ucsc-gff3togenepred/0004-straw.patch
  recipes/ucsc-gff3togenepred/build.sh
  recipes/ucsc-gff3togenepred/htmshell.patch
  recipes/ucsc-gff3togenepred/include.patch
  recipes/ucsc-gff3togenepred/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#57260 Update some ucsc tools to v482
  recipes/ucsc-pslsort/0001-include.patch
  recipes/ucsc-pslsort/0002-include.linux.patch
  recipes/ucsc-pslsort/0003-common.mk.patch
  recipes/ucsc-pslsort/0004-straw.patch
  recipes/ucsc-pslsort/build.sh
  recipes/ucsc-pslsort/include.patch
  recipes/ucsc-pslsort/meta.yaml
  recipes/ucsc-pslsortacc/0001-include.patch
  recipes/ucsc-pslsortacc/0002-include.linux.patch
  recipes/ucsc-pslsortacc/0003-common.mk.patch
  recipes/ucsc-pslsortacc/0004-straw.patch
  recipes/ucsc-pslsortacc/build.sh
  recipes/ucsc-pslsortacc/include.patch
  recipes/ucsc-pslsortacc/meta.yaml
  recipes/ucsc-pslstats/0001-include.patch
  recipes/ucsc-pslstats/0002-include.linux.patch
  recipes/ucsc-pslstats/0003-common.mk.patch
  recipes/ucsc-pslstats/0004-straw.patch
  recipes/ucsc-pslstats/build.sh
  recipes/ucsc-pslstats/include.patch
  recipes/ucsc-pslstats/meta.yaml
  recipes/ucsc-psltobed/0001-include.patch
  recipes/ucsc-psltobed/0002-include.linux.patch
  recipes/ucsc-psltobed/0003-common.mk.patch
  recipes/ucsc-psltobed/0004-straw.patch
  recipes/ucsc-psltobed/build.sh
  recipes/ucsc-psltobed/include.patch
  recipes/ucsc-psltobed/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#57262 metadmg: add aarch64/arm64 builds
  recipes/metadmg/0001-Makefile.patch
  recipes/metadmg/build.sh
  recipes/metadmg/build_failure.osx-64.yaml
  recipes/metadmg/meta.yaml
Labels: aarch64, osx-arm64

#57261 Update more ucsc tools to v482
  recipes/ucsc-fatrans/0001-include.patch
  recipes/ucsc-fatrans/0002-include.linux.patch
  recipes/ucsc-fatrans/0003-common.mk.patch
  recipes/ucsc-fatrans/0004-straw.patch
  recipes/ucsc-fatrans/build.sh
  recipes/ucsc-fatrans/include.patch
  recipes/ucsc-fatrans/meta.yaml
  recipes/ucsc-gaptolift/0001-include.patch
  recipes/ucsc-gaptolift/0002-include.linux.patch
  recipes/ucsc-gaptolift/0003-common.mk.patch
  recipes/ucsc-gaptolift/0004-straw.patch
  recipes/ucsc-gaptolift/build.sh
  recipes/ucsc-gaptolift/include.patch
  recipes/ucsc-gaptolift/meta.yaml
  recipes/ucsc-oligomatch/0001-include.patch
  recipes/ucsc-oligomatch/0002-include.linux.patch
  recipes/ucsc-oligomatch/0003-common.mk.patch
  recipes/ucsc-oligomatch/0004-straw.patch
  recipes/ucsc-oligomatch/build.sh
  recipes/ucsc-oligomatch/include.patch
  recipes/ucsc-oligomatch/meta.yaml
  recipes/ucsc-pslpostarget/0001-include.patch
  recipes/ucsc-pslpostarget/0002-include.linux.patch
  recipes/ucsc-pslpostarget/0003-common.mk.patch
  recipes/ucsc-pslpostarget/0004-straw.patch
  recipes/ucsc-pslpostarget/build.sh
  recipes/ucsc-pslpostarget/include.patch
  recipes/ucsc-pslpostarget/meta.yaml
  recipes/ucsc-psltochain/0001-include.patch
  recipes/ucsc-psltochain/0002-include.linux.patch
  recipes/ucsc-psltochain/0003-common.mk.patch
  recipes/ucsc-psltochain/0004-straw.patch
  recipes/ucsc-psltochain/build.sh
  recipes/ucsc-psltochain/include.patch
  recipes/ucsc-psltochain/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#57264 Update ucsc-genepredtogtf to v482
  recipes/ucsc-genepredtogtf/0001-include.patch
  recipes/ucsc-genepredtogtf/0002-include.linux.patch
  recipes/ucsc-genepredtogtf/0003-common.mk.patch
  recipes/ucsc-genepredtogtf/0004-straw.patch
  recipes/ucsc-genepredtogtf/build.sh
  recipes/ucsc-genepredtogtf/include.patch
  recipes/ucsc-genepredtogtf/meta.yaml
Labels: osx-arm64

#57265 update expansionhunterdenovo and enabled linux-aarch64
  recipes/expansionhunterdenovo/build.sh
  recipes/expansionhunterdenovo/meta.yaml
Labels: please review & merge

#57266 update famseq and enabled linux-aarch64
  recipes/famseq/build.sh
  recipes/famseq/meta.yaml
Labels: aarch64, osx-arm64

#57270 Update some UCSC tools to v482
  recipes/ucsc-bigbedtobed/0001-include.patch
  recipes/ucsc-bigbedtobed/0002-include.linux.patch
  recipes/ucsc-bigbedtobed/0003-common.mk.patch
  recipes/ucsc-bigbedtobed/0004-straw.patch
  recipes/ucsc-bigbedtobed/build.sh
  recipes/ucsc-bigbedtobed/include.patch
  recipes/ucsc-bigbedtobed/meta.yaml
  recipes/ucsc-genepredcheck/0001-include.patch
  recipes/ucsc-genepredcheck/0002-include.linux.patch
  recipes/ucsc-genepredcheck/0003-common.mk.patch
  recipes/ucsc-genepredcheck/0004-straw.patch
  recipes/ucsc-genepredcheck/build.sh
  recipes/ucsc-genepredcheck/htmshell.patch
  recipes/ucsc-genepredcheck/include.patch
  recipes/ucsc-genepredcheck/meta.yaml
  recipes/ucsc-genepredtobiggenepred/0001-include.patch
  recipes/ucsc-genepredtobiggenepred/0002-include.linux.patch
  recipes/ucsc-genepredtobiggenepred/0003-common.mk.patch
  recipes/ucsc-genepredtobiggenepred/0004-straw.patch
  recipes/ucsc-genepredtobiggenepred/build.sh
  recipes/ucsc-genepredtobiggenepred/htmshell.patch
  recipes/ucsc-genepredtobiggenepred/include.patch
  recipes/ucsc-genepredtobiggenepred/meta.yaml
  recipes/ucsc-hggcpercent/0001-include.patch
  recipes/ucsc-hggcpercent/0002-include.linux.patch
  recipes/ucsc-hggcpercent/0003-common.mk.patch
  recipes/ucsc-hggcpercent/0004-straw.patch
  recipes/ucsc-hggcpercent/build.sh
  recipes/ucsc-hggcpercent/htmshell.patch
  recipes/ucsc-hggcpercent/include.patch
  recipes/ucsc-hggcpercent/meta.yaml
Labels: MacOS related, aarch64, osx-arm64

#57288 Update some ucsc tools to v482
  recipes/ucsc-bedclip/0001-include.patch
  recipes/ucsc-bedclip/0002-include.linux.patch
  recipes/ucsc-bedclip/0003-common.mk.patch
  recipes/ucsc-bedclip/0004-straw.patch
  recipes/ucsc-bedclip/build.sh
  recipes/ucsc-bedclip/conda_build_config.yaml
  recipes/ucsc-bedclip/include.patch
  recipes/ucsc-bedclip/meta.yaml
  recipes/ucsc-bedclip/patch1.patch
  recipes/ucsc-bedsort/0001-include.patch
  recipes/ucsc-bedsort/0002-include.linux.patch
  recipes/ucsc-bedsort/0003-common.mk.patch
  recipes/ucsc-bedsort/0004-straw.patch
  recipes/ucsc-bedsort/build.sh
  recipes/ucsc-bedsort/include.patch
  recipes/ucsc-bedsort/meta.yaml
  recipes/ucsc-bigbedinfo/0001-include.patch
  recipes/ucsc-bigbedinfo/0002-include.linux.patch
  recipes/ucsc-bigbedinfo/0003-common.mk.patch
  recipes/ucsc-bigbedinfo/0004-straw.patch
  recipes/ucsc-bigbedinfo/build.sh
  recipes/ucsc-bigbedinfo/include.patch
  recipes/ucsc-bigbedinfo/meta.yaml
  recipes/ucsc-bigbedsummary/0001-include.patch
  recipes/ucsc-bigbedsummary/0002-include.linux.patch
  recipes/ucsc-bigbedsummary/0003-common.mk.patch
  recipes/ucsc-bigbedsummary/0004-straw.patch
  recipes/ucsc-bigbedsummary/build.sh
  recipes/ucsc-bigbedsummary/include.patch
  recipes/ucsc-bigbedsummary/meta.yaml
  recipes/ucsc-bigwigaverageoverbed/0001-include.patch
  recipes/ucsc-bigwigaverageoverbed/0002-include.linux.patch
  recipes/ucsc-bigwigaverageoverbed/0003-common.mk.patch
  recipes/ucsc-bigwigaverageoverbed/0004-straw.patch
  recipes/ucsc-bigwigaverageoverbed/build.sh
  recipes/ucsc-bigwigaverageoverbed/include.patch
  recipes/ucsc-bigwigaverageoverbed/meta.yaml
  recipes/ucsc-xmlcat/0001-include.patch
  recipes/ucsc-xmlcat/0002-include.linux.patch
  recipes/ucsc-xmlcat/0003-common.mk.patch
  recipes/ucsc-xmlcat/0004-straw.patch
  recipes/ucsc-xmlcat/build.sh
  recipes/ucsc-xmlcat/include.patch
  recipes/ucsc-xmlcat/meta.yaml
Labels: please review & merge

#57220 Add vpt plugin cellpose2
  recipes/vpt-plugin-cellpose2/meta.yaml
Labels: please review & merge

#57196 Add IlluminaHumanMethylationEPICv2anno.20a1.hg38 and IlluminaHumanMethylationEPICv2manifest
  recipes/bioconductor-data-packages/dataURLs.json
  recipes/bioconductor-data-packages/meta.yaml
  recipes/bioconductor-illuminahumanmethylationepicv2anno.20a1.hg38/meta.yaml
  recipes/bioconductor-illuminahumanmethylationepicv2anno.20a1.hg38/post-link.sh
  recipes/bioconductor-illuminahumanmethylationepicv2anno.20a1.hg38/pre-unlink.sh
  recipes/bioconductor-illuminahumanmethylationepicv2manifest/meta.yaml
  recipes/bioconductor-illuminahumanmethylationepicv2manifest/post-link.sh
  recipes/bioconductor-illuminahumanmethylationepicv2manifest/pre-unlink.sh
Labels: please review & merge

#57317 starcode: add arm64 build
  recipes/starcode/0001-master.patch
  recipes/starcode/build.sh
  recipes/starcode/meta.yaml
Labels: osx-arm64

#57314 Re-try missMethyl
  build-fail-blacklist
Labels: please review & merge

#57320 Update resistify recipe
  recipes/resistify/meta.yaml
Labels: please review & merge

#57353 update kractor to version to 1.0.1
  recipes/kractor/meta.yaml
Labels: please review & merge

#57360 openstructure: Update documentation in post-link.sh
  recipes/openstructure/build.sh
  recipes/openstructure/meta.yaml
  recipes/openstructure/post-link.sh
Labels: please review & merge

#57359 Update PhaBOX environments
  recipes/phabox/meta.yaml
Labels: please review & merge

#57332 enable dmrcate and bump build version
  build-fail-blacklist
  recipes/bioconductor-dmrcate/meta.yaml
Labels: please review & merge

#57292 Adding coot-headless
  recipes/coot-headless/activate.sh
  recipes/coot-headless/build.sh
  recipes/coot-headless/deactivate.sh
  recipes/coot-headless/meta.yaml
  recipes/coot-headless/post-link.sh
  recipes/coot-headless/run_test.py
Labels: please review & merge

#57227 Update: bump metadmg version
  recipes/metadmg/0001-Makefile.patch
  recipes/metadmg/build.sh
  recipes/metadmg/meta.yaml
Labels: please review & merge
